### ISSUE TITLE
How to debug a mpv Lua script

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10007]
I might have found an issue here:

```C
static void load_file(lua_State *L, const char *fname)
{
    struct script_ctx *ctx = get_ctx(L);
    MP_DBG(ctx, "loading file %s\n", fname);
    struct bstr s = stream_read_file(fname, ctx, ctx->mpctx->global, 100000000);
    if (!s.start)
        luaL_error(L, "Could not read file.\n");
    if (luaL_loadbuffer(L, s.start, s.len, fname))
        lua_error(L);
    lua_call(L, 0, 1);
    talloc_free(s.start);
}
```

luaL_loadbuffer passes a path in fname, but in order to use a Lua debugger this path must have a @ character at the beginning, which is missing. I tried to modify the mpv code in order to test Lua debugging, using strcpy and strcat I get build errors, [my last c++ project was 12 months ago](https://github.com/staxrip/staxrip/tree/master/Source/FrameServer), I used c++ strings and have meanwhile forgotten half of it. I will learn Lua this year, C next year.

https://github.com/actboy168/lua-debug/issues/164

**Comment by avih** [comment]
> How to debug a mpv Lua script

Lua does not have an official debugger, mpv does not have a builtin lua debugger, and mpv does not have any support for such functionality. The most reliable method it can offer is to add `print` statements to your lua code to figure out what the code does.

Third party debuggers could have various requirements which may or may not be satisfied with mpv.

There is no issue in mpv or in how it uses lua, even if that's not how your debugger expects it to be.

mpv always uses the lua API to load content as string, and not as files, because:
- For builtin files (`defaults.lua`, `ytdl_hook.lua`, etc) because they're strings embedded into the binary and not files on disk.
- For user scripts, because lua doesn't support unicode file names correctly on windows, so mpv reads the file correctly into RAM, and then loads it into lua as a string.

The fact that some introspection APIs do or don't prefix the name with `@` is internal lua thing, and mpv does not and should not add such prefix on its own.

I don't have some a solution for debugger integration which depends on the `@` prefix for things, but maybe if the debugger supported some statement to specify the source file on disk from within the file itself, then you could use that.

**Comment by sfan5** [comment]
> As explained earlier, the @ is an internal lua thing, and it's not intended to be prefixed manually when using the lua APIs.

What are you basing this on?
The Lua manual has a clearly documented convention that is even referenced in the documentation of `lua_load` and you are claiming mpv should not have to follow it.

**Comment by avih** [comment]
> What are you basing this on?
> The Lua manual has a clearly documented convention that is even referenced in the documentation of `lua_load` and you are claiming mpv should not have to follow it.

The lua docs.

The symbol `@` is mentioned exactly twice at the (5.1) docs:
1. (this is irrelevant for us) at section 6 Lua Stand-alone: "Before running any argument, the interpreter checks for an environment variable [LUA_INIT](). If its format is @filename, then lua executes the file. Otherwise, lua executes the string itself."
2. at 3.8 debug interface: "source: If the function was defined in a string, then source is that string. If the function was defined in a file, then source starts with a '@' followed by the file name. "

And that's it. The application can use any valid API to load it. It's not required or recommented to prefix it with anything. It just tells you that the `@` is an internal indication which helps someone identify which API was used to load the content.

Now, can you point to the lua documentation which you claim describes a convention which an API user should follow?

**Comment by stax76** [comment]
> For user scripts, because lua doesn't support unicode file names correctly on windows

mpv has UTF8 enforced in the manifest, so it should be no problem since Windows 10 1903, it's not much asking Win 7 users to use ASCII filenames for scripts, I think. But that particular change would only have an effect on script debugging, probably.

**Comment by avih** [comment]
> mpv has UTF8 enforced in the manifest, so it should be no problem since Windows 10 1903, it's not much asking Win 7 users to use ASCII filenames for scripts, I think

Correct. But we still support Windows 7 and 10 earlier than 1903.

**Comment by sfan5** [comment]
> The application can use any valid API to load it.

Yes

> It's not required or recommented to prefix it with anything.

No. `lua_load` documentation references the exact part of 3.8 you quoted: "The chunkname argument gives a name to the chunk, which is used for error messages and in debug information (see §3.8)."
If this isn't a recommendation to follow this convention then I don't know why they bothered writing it.

> `@` is an internal indication which helps someone identify which API was used to load the content.

This is incorrect. As described, the chunkname prefix is supposed to indicate *where* something was defined, either in a file or in a string. This has nothing to do with which API you use to pass source to Lua.

> Correct. But we still support Windows 7 and 10 earlier than 1903.

Are you implying that because it cannot work before 1903 that it shouldn't work anywhere?

**Comment by avih** [comment]
> If this isn't a recommendation to follow this convention then I don't know why they bothered writing it.

Because they document how this argument is used.

I don't find it even mildly recommending or even entertaining the possibility of using some specific form of string here.

> If adding a @ on Win 7 would be an issue

I never suggested this would be an issue, I was describing why we use the string API (which doesn't add @ to the name) rather than the file API (which does add @ to the name) - because unicode file names on win7 and older win10.

The reason I'm against adding the @ prefix is because I don't think we should fake it. We use the string load API, and that's it. We describe it as best we can, using the correct chunkname as the file path, and that's how it appears at the `source` member.

I could be misinterpreting the docs here, but I just completely don't see it as a recommendation to add fake @ prefix when loading it as a string if we want whatever internal things to think that we loaded it from a file.

**Comment by sfan5** [comment]
> We describe it as best we can, using the correct chunkname as the file path, and that's how it appears at the `source` member.

This is wrong for two separate reasons
1) The documentation says chunkname should either be `@` plus the filename or the Lua source code itself. But mpv does **neither**, it sets the chunkname to the bare filename.
2) That aside, mpv not using the same convention Lua would ordinarily use when loading files cannot be called "as best as we can". We can do better, trivially.

**Comment by avih** [comment]
> avih, there is nothing to lose, IMHO, trying this change.

There is. My integrity.

It's likely to work, but personally I think it's a wrong thing to do, therefore I won't do it.

If some other developer, like @sfan5 wants to do that despite what's been said so far, I'm not going to stop them.

**Comment by sumneko** [comment]
I would like to join the discussion because I like MPV very much, this is the only player on my computer.

> We describe it as best we can, using the correct chunkname as the file path, and that's how it appears at the `source` member.

As @sfan5 said, `source` should be `@filename` or code itself. 
In both case `filepath` should not be used as  `source`.

> The reason I'm against adding the @ prefix is because I don't think we should fake it. We use the string load API, and that's it.

We should follow the semantics to determine the program, not what API is used.
The purpose of your code is to achieve a better "dofile", our purpose is to resolve the problem of filename encoding, not some of Lua's agreement.
In fact, Lua built-in `luaL_dofile` is also implemented by calling` lua_load`, `luaL_dofile` has been working for us to set up `@filename`.
Now that since you intend to implement a similar function by a more basic API, we should respect it from specifications and details..

> Lua does not have an official debugger, mpv does not have a builtin lua debugger, and mpv does not have any support for such functionality. The most reliable method it can offer is to add `print` statements to your lua code to figure out what the code does.

The problem with `chunkname` is not only related to the debugger.
When Lua has a runtime error, Lua will output an stack traceback and need to use `chunkname` in traceback.
According to the MPV current implementation, weird content will appear in the output because Lua misunderstands that the file name is the file content.

**Comment by stax76** [comment]
I probably crossed a boundary or two, because I was too stressed that day, sorry about it, I hope we can continue where we were before this @avih .

The code compiles now with these three lines added:

```C
char name[500];
strcpy(name, "@");
strcat(name, fname);
```

It did not compile before, I think because I had forgotten a build step.

I confirm everything working now, it breaks when the script first runs and also when handling input keys.

I will submit a PR.
