### ISSUE TITLE
Why mpv load the whole peertube video before actually play it ?

### ISSUE THREAD

**Issue by stacyharper** [mpv-player/mpv#10029]
Hey there,

`mpv -v --no-config https://framatube.org/w/dHBrnMQeEt8Mq82KxV4zKm`

If I run this command it looks like mpv (or yt-dlp, or ffmpeg ?) try to fetch the whole video before actually run the player. It can take a very long time before that happen (depending on the video duration).

The log continues to output :

```
[ffmpeg] stream level seek from 7698 to 215354720
[ffmpeg] stream level seek from 215354724 to 1385
[ffmpeg] stream level seek from 9080 to 492809
[ffmpeg] stream level seek from 500502 to 742446
[ffmpeg] stream level seek from 754454 to 1014302
[ffmpeg] stream level seek from 1032982 to 1304285
[ffmpeg] stream level seek from 1311510 to 1597202
[ffmpeg] stream level seek from 1606422 to 1885403
…
```

What is going on ? Is it the expected behavior ?

**Comment by garoto** [comment]
Disabling ffmpeg's seekability HTTP probing seems to be a workaround:

`mpv --stream-lavf-o=seekable=0 https://framatube.org/w/dHBrnMQeEt8Mq82KxV4zKm`

**Comment by stacyharper** [comment]
> Disabling ffmpeg's seekability HTTP probing seems to be a workaround:
> 
> `mpv --stream-lavf-o=seekable=0 https://framatube.org/w/dHBrnMQeEt8Mq82KxV4zKm`

What is the purpose of seekable ? Shouldnt this be disabled by default
in the mpv context ?

**Comment by garoto** [comment]
To make sure the HTTP server it's talking to supports `Range:` requests would be my best guess.

**Comment by Hello71** [comment]
i think ffmpeg is looking for duration metadata. first it reads the start; it isn't there. then it checks the end; it isn't there either. nothing else to try but reading the whole file and adding up the time. i guess probably peertube js player communicates duration out-of-band somehow. possibly yt-dlp can send the duration to mpv which might be able to send it to ffmpeg, but i don't know how that would work.

**Comment by mhershberger** [comment]
Thanks for posting that workaround!

While the --stream-lavf-o=seekable=0 workaround does allow videos to begin playing immediately, the video duration is not exposed in mpv; instead, the duration will continue increasing as the file is downloaded. This makes it impossible to seek past what has already loaded, like you can with e.g. YouTube. I'm not sure if this is a limitation of PeerTube's API, mpv, or yt-dlp.

By running mpv with the "--msg-level=all=trace" option, I was able to find the exact yt-dlp command mpv uses to handle URLs, then compare the output in isolation. For both YouTube and PeerTube, the yt-dlp command that mpv executes is the same:

yt-dlp --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist -- <url>

This returns a JSON object with a ton of metadata on the video, including URLs for various formats.

I found that the result from PeerTube contains both the "duration" and "duration_string" top-level properties. e.g.:

  "duration_string": "1:22:25"
  "duration": 4945

It also has a "URL" property which contains the video URL for the best format. This URL also exists in the "formats" and "requested_downloads" arrays. Interestingly, duration data does not exist in either of those arrays, even though it exists at the top level. Perhaps this is why mpv is unaware of the duration?

It looks like PeerTube only provides a single video URL per available format, whereas YouTube returns fragments, with each fragment having its own duration included in the JSON metadata. Perhaps this also makes it difficult to enable seeking for PeerTube? 

Of course, PeerTube's web UI does allow seeking, so it seems like this should be possible in theory. The PeerTube video URLs end in "-fragmented.mp4" and I can see using Firefox's inspector that the web player is loading that same URL from different ranges to handle buffering and seeking.

Again, I'm not sure if the fix for this lies in mpv or yt-dlp.

**Comment by b4zz4** [comment]
mpv $(yt-dlp https://framatube.org/w/dHBrnMQeEt8Mq82KxV4zKm -g)

**Comment by b4zz4** [comment]
mpv $(yt-dlp -g https://framatube.org/w/dHBrnMQeEt8Mq82KxV4zKm | sed 's/-fragmented.mp4/.m3u8/')
