### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by ayghub** [mpv-player/mpv#10077]

**Comment by hooke007** [comment]
You ignored the much too messages that devs need. Though I think it should be report to [libass](https://github.com/libass/libass).

**Comment by ValZapod** [comment]
Sample and what do you mean "when I click"?

**Comment by ayghub** [comment]
> Sample and what do you mean "when I click"?

like that "3 cycle sub-spacing +0.05" or just sub-spacing=00.5 in the mpv.conf file.

**Comment by ayghub** [comment]
> Sample and what do you mean "when I click"?

i mean "3 cycle sub-spacing +0.05" this, or just "sub-spacing=0.05" in the mpv.conf file

**Comment by ayghub** [comment]
> > Sample and what do you mean "when I click"?
> 
> i mean "3 cycle sub-spacing +0.05" this, or just "sub-spacing=0.05" in the mpv.conf file

**Comment by Mikasa-san** [comment]
I have the same problem mpv doesn't load subtitle style.

**Comment by MegaXMan** [comment]
you have to delete sub-spacing and sub-margin if this doesn't work use this conf :

 # === Subtitle === 
--sub-visibility=yes
--sub-font="your font"
--sub-font-size=70
--sub-color="#FFFFFFFF"
--sub-border-color="#FF262626"
# Subtitle Language Priority
slang=eng,en,enUS,en-US,English
# Load external subtitles with (almost) the same name as the video

**Comment by ayghub** [comment]
>

**Comment by ayghub** [comment]
the problem is with arabic subtitle not english

**Comment by MegaXMan** [comment]
it's my bad use this
# Change subtitle encoding. For Arabic subtitles use 'cp1256'.

**Comment by MegaXMan** [comment]
![Screenshot (233)](https://user-images.githubusercontent.com/108504977/236977116-4a550e6f-318e-43f7-b3f0-6915512ff181.png)

**Comment by MegaXMan** [comment]
this is what I use in mpv.conf
`# === General and Video ===
 
# Keeps player open after file has finished playing.
keep-open=yes
save-position-on-quit=no
# Title bar naming
title='${filename}'
# Displays file name instead of title name in On Screen Controller [OSC]
script-opts='osc-title=${filename}'
# Hide Cursor in ms
cursor-autohide=500

# === On Screen Display [OSD] ===
 
# Don't show a huge volume box on screen when turning the volume up/down or while seeking.
osd-bar=no
osd-font-size=50
osd-font='Orbitron'
osd-color='#CCCCFF'
autofit=85%x85%

# === Subtitle ===

--sub-font="Cairo SemiBold"
--sub-font-size=55
--sub-scale=1.100
--sub-border-size=2
--sub-shadow-color="#33000000"
--sub-shadow-offset=2
--sub-blur=3
--sub-use-margins=no
--sub-auto=fuzzy
--blend-subtitles=no
--sub-ass-vsfilter-blur-compat=yes		# Backward compatibility for vsfilter fansubs
--sub-ass-scale-with-window=no			# May have undesired effects with signs being misplaced.
--sub-auto=fuzzy                         		# external subs don't have to match the file name exactly to autoload
# sub-gauss=0.6					# Some settings fixing VOB/PGS subtitles (creating blur & changing yellow subs to gray)
--sub-file-paths-append=ass               	# search for external subs in these relative subdirectories
--sub-file-paths-append=srt
--sub-file-paths-append=sub
--sub-file-paths-append=subs
--sub-file-paths-append=subtitles
--demuxer-mkv-subtitle-preroll=yes       		# try to correctly show embedded subs when seeking
--embeddedfonts=yes				# use embedded fonts for SSA/ASS subs
--sub-fix-timing=no                       	# do not try to fix gaps (which might make it worse in some cases). Enable if there are scenebleeds.

# Change subtitle encoding. For Arabic subtitles use 'cp1256'.
# Load external subtitles with (almost) the same name as the video 
alang=Japanese,jpn,ja,English,eng,en
slang=Arabic,ara,ar,arabia,English,eng,en`

**Comment by ayghub** [comment]
i tried that a long time ago didn't work. thank you man.

here is a video of what happens every time i change sub-spacing 

https://github.com/mpv-player/mpv/assets/91691648/8b730e35-197e-458e-877f-c7735e436cf4
