### ISSUE TITLE
Dolby Vision: is metadata used for dynamic target nits?

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#10091]
I'm not that familiar with Dolby Vision, but as far as I understand it has several features. Beside the 12 Bit per component there is metadata for the brightness of a frame. Is this already used for MPV's tone mapping algorithms? Or will it be used in future?

**Comment by quietvoid** [comment]
That metadata is not parsed at all by FFmpeg, so it's not used either in the algorithms.

**Comment by ValZapod** [comment]
No, of course not! That can be verified by https://drive.google.com/file/d/1-8C0ZYnIhEqOVJQ532hIJobP5XR6A7gj/view?usp=drivesdk

That is simple metadata, while dynamic target nits will require knowing nits of the display and many other stuff! Also, not display implements this fully, since it is not like you can connect second display tomWebOS LG C9 ;) That can be a problem too, if we are going to reverse ingeener the code in WebOS...

**Comment by pillepalle1234** [comment]
I have files with supposedly the full enhancement layer, so it is possible to extract it it seems.
