### ISSUE TITLE
The video playing has a faded washed out color.

### ISSUE THREAD

**Issue by Horuyuki** [mpv-player/mpv#10094]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1
```
- Linux Distribution and Version
Fedora 35 KDE
- Source of the mpv binary
DNF
- Window Manager and version
X11
- GPU driver and version
Nvdia 510.47.03
- Possible screenshot or video of visual glitches
https://i.imgur.com/ZMqIhrs.jpg

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Just clicked on the file to play it.

### Expected behavior
Play with a white instead of grey progress control bar.
### Actual behavior
https://i.imgur.com/ZMqIhrs.jpg
### Log file
https://pastebin.com/V9ch05rD

**Comment by LaserEyess** [comment]
You're using a VO that is explicitly low quality, from your log:

> `[vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.`

Use `--vo=gpu --hwdec=nvdec`

**Comment by LaserEyess** [comment]
You can just put those lines in your config without the leading dashes
```
vo=gpu
hwdec=nvdec # or auto-safe
```
But I think the bigger issue here is that your GPU isn't being used and is falling back to software rendering. Is this a machine with an integrated GPU?

**Comment by LaserEyess** [comment]
Well, however you installed your GPU drivers, mpv cannot find them. It only thinks mesa llvmpipe (a software renderer) exists. By default, mpv doesn't let `--vo=gpu` work with a software renderer, so it's falling back to progressively worse and worse options for you. In order to get around that you can add `--gpu-sw=yes`, which will fix the washed out colors, but not your GPU drivers. Performance will be very low since it is rendering on your CPU and it will likely not work reliably for 4k video.
