### ISSUE TITLE
Opening files over sftp with %20 in file names does not work

### ISSUE THREAD

**Issue by rantlivelintkale** [mpv-player/mpv#10103]
### Important Information

Provide following Information:
- mpv version - 0.34.1
- Platform and Version - Alpine Linux edge
- Source of the mpv binary - alpine repositories

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Open a file via sftp with a file manager e.g. nautilus or pcmanfm

```
pcmanfm sftp://<hostname>
```

Find a video file with spaces in the file name -> Open with mpv.

I get the following output in my terminal:
```
mpv --player-operation-mode=pseudo-gui -- 'sftp://<hostname>/path/to/video%20with%20spaces.mkv'
```

### Expected behavior

Video starts playing.

### Actual behavior

Video does not start playing.

Running the command without `--player-operation-mode=pseudo-gui` reveals that there's an error in parsing the filename with %20s in it:

```
[ffmpeg] libssh: Error opening sftp file: SFTP server: No such file
Failed to open sftp://<hostname>/path/to/video%20with%20spaces.mkv.
```

Using the following wrapper fixes the behaviour:

```
#!/bin/sh
file="$(echo "$@" | sed s/%20/\\\\\ /g)"
cmd="exec /usr/bin/mpv $file"
eval "$cmd"

```

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/8500337/output.txt)

**Comment by garoto** [comment]
Related: https://github.com/mpv-player/mpv/issues/1495, https://github.com/mpv-player/mpv/issues/6024

**Comment by thebombzen** [comment]
According to the RFC specification for URI syntax, [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986),

> the URI generic syntax is a superset of the syntax of all URI
   schemes

This means that anything that is disallowed by the generic URI syntax is also disallowed by all schemes. In particular, this is a *requirement* of the URI syntax:

> If data for a URI component would conflict with a reserved
   character's purpose as a delimiter, then the conflicting data must be
   percent-encoded before the URI is formed.

This means that in certain circumstances, percent-encoded characters are is *required* by the URI spec, or rather, un-percent-encoded reserved characters are *disallowed.* In order to properly interpret a URI, percent-decoding *must* be supported if any of those reserved characters could appear in the corresponding URI. (If none of those characters could occur in the legal URI, then percent-decoding is not necessary.)

In the case of the SFTP scheme, reserved characters like `(` and ` ` definitely can occur, so it's required to support percent-decoding by the URI spec in order to support this scheme's syntax. 

Whether this is *our* responsibility or whether it's avformat's responsibility is a different question.

**Comment by rantlivelintkale** [comment]
Looking at the previous issues I feel like this is more of an issue with avformat and working around their problem in mpv should not be the solution.

Thanks for the help.
