### ISSUE TITLE
Smooth scrubbing / seeking like Quicktime

### ISSUE THREAD

**Issue by ahrib** [mpv-player/mpv#10185]
### Expected behavior of the wanted feature
Currently scrubbing occurs either via keyframe or in fixed time intervals.

Ideally increase the smoothness and precision of scrubbing / seeking to be comparable to that of Quicktime for MacOS during the following actions:
* using a trackpad (swipe) 
* moving the pointer via playback controls (mouse)

Additionally, when using the trackpad to scrub / seek varying the scrubbing speed to match user input speed (i.e. faster swipe = faster scrubbing speed, slower swipe = slower scrubbing speed)

Silky smooth scrubbing allows navigation and finding a particular frame in a scene in an intuitive manner.

### Alternative behavior of the wanted feature
variable scrubbing speed matching user input would be a good first step

### Log file
n/a - it is a known limitation

**Comment by Akemi** [comment]
look into the --hr-seek(-*) options (https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst) and the input command seek flag exact (https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst).

for the OSC set the seekbarkeyframes option to false (https://github.com/mpv-player/mpv/blob/bb5b4b1ba61b67da40c85c34376aced9383fc366/player/lua/osc.lua#L39).

you are requesting two different things in one issue. since the main request has been answered, i will close this.
