### ISSUE TITLE
configure fails with waf 2.0.24, must downgrade to 2.0.23

### ISSUE THREAD

**Issue by jamespharvey20** [mpv-player/mpv#10234]
### mpv version and platform versions

mpv 0.34.1.  Up to date Arch system, so was on maf 2.0.24.  Downgrading to maf 2.0.23 succeeds.

### Reproduction steps

$ waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date --disable-caca

### Expected behavior

The package to be configured, so I can proceed to build it.

### Actual behavior

 Error: run waf-light from a folder containing waflib

### Log file

There isn't a log.  It fails with the single line of output -- the error quoted above.

**Comment by CounterPillow** [comment]
Waf is not supposed to be forwards-compatible like that, generally you use the version of waf the project ships.

**Comment by jamespharvey20** [comment]
> Waf is not supposed to be forwards-compatible like that, generally you use the version of waf the project ships.

OK.  On Arch, waf is installed system-wide to build mpv.  If waf doesn't keep itself forward-compatible, that makes things fun for people who build multiple projects each compatible with different waf versions.  I noted to the mpv maintainer the possibility of building using meson.

**Comment by Dudemanguy** [comment]
>On Arch, waf is installed system-wide to build mpv.

It seems like they actually do. It should probably just use the bootstrap.py script in the repo though. Well meson builds won't be until the next release anyways (0.34 predates this).

**Comment by eli-schwartz** [comment]
> On Arch, waf is installed system-wide to build mpv. If waf doesn't keep itself forward-compatible, that makes things fun for people who build multiple projects each compatible with different waf versions.

Distros tend to want to install waf properly, yes.

This is hindered by the fact that the waf author doesn't want you to do that, and wants you to check the waf program into git in every project that uses it, or download it from the internet in your build recipes. Failing to be forward-compatible is a *feature*, not a bug. For extra pain, the waf author also played hostile games with the licensing of parts of the project (specifically the documentation) with the explicit intention of making waf itself violate Debian's distribution guidelines and forcing waf to be removed from Debian. This is how badly the waf author doesn't like distros to install it system-wide. It partially worked: there are distros that package waf, but Debian isn't one of them any more.

Of course, it needs to be anyway. :shrug: But it can be assumed to be unreliable. Ultimately the solution here is just don't use waf for anything ever.

IIRC mpv introduced Meson support in large part because waf was frustrating to work with, and generally intends to drop waf once the Meson support becomes battle-tested in real-world usage. This means it is *probably* a good idea to try using it sooner rather than later.

**Comment by CoelacanthusHex** [comment]
Sounds like a good idea to use Meson. Once we release a new version, like https://github.com/mpv-player/mpv/issues/10226 says.
I use meson to build my [mpv-git package](https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/mpv-git) for serval months. mpv-git on AUR use Meson for much time.

**Comment by jamespharvey20** [comment]
> This sounds like user error(?) or some sort of edge case. If I do the following:
> ...

Yep, you were right.  loqs with Arch figured out it's an issue with the way Arch packaged waf 2.0.24.  There's not an mpv issue here.  Sorry about that!
