### ISSUE TITLE
libmpv question regarding event loop and messages

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10236]
To call commands of my frontend, I use the following:

`script-message mpv.net commandname args`

I rewrote this now, creating a named handle with mpv_create_client to be able to send messages only to my frontend:

`script-message-to mpvnet commandname args`

All event related code like calls to mpv_observe_property use the named handle. For the unnamed ('main') handle, I'm not running an event loop at all, might this cause problems? For the main handle, I called mpv_request_log_messages with 'no', non-event related code like mpv_set_property still use the main handle.

Maybe the API could be improved in a way, for instance providing a mpv_create_named as alternative to mpv_create, doing the same as mpv_create but allowing to define a client name other than 'main', or maybe it's not possible or easy to do.

My rewrite seem to work well, I hope it's not buggy or causes name clashes with user scripts or user configuration. It supports both the old and new message method and allows mixing both methods, to ensure backward compatibility with existing configuration.

My command names  are (some are deprecated and re-routed):

add-files-to-playlist
cycle-audio
execute-mpv-command
load-audio
load-sub
open-clipboard
open-conf-folder
open-files
open-optical-media
open-url
play-pause
playlist-add
playlist-first
playlist-last
quick-bookmark
reg-file-assoc
scale-window
select-profile
shell-execute
show-about
show-audio-devices
show-audio-tracks
show-command-palette
show-commands
show-conf-editor
show-decoders
show-demuxers
show-history
show-info
show-input-editor
show-keys
show-media-info
show-menu
show-playlist
show-profiles
show-progress
show-properties
show-protocols
show-recent
show-setup-dialog
show-subtitle-tracks
show-text
window-scale

**Comment by stax76** [comment]
I could run a main handle message loop without doing any work in it, if this is better than letting it congest?

**Comment by avih** [comment]
I don't think it's wise to allow custom name for the main/first handle.

I'm guessing, but don't know for a fact, that the first handle (and possibly its name) could have some significance in some places. Even if that's not the case today, it could be the case tomorrow, so I think it's preferable to keep the name of the first handle controlled by mpv itself.

You didn't state why you rewrite the message form, but assuming it's because you prefer directed messages instead of broadcast ones for no reason other than being slightly tidier design, then you can add a client with whatever name which doesn't do anything other than forwarding all messages to the main client. I highly doubt there would be any measurable performance impact due to this intermediate agent.

This other client could be a C[#] client, but assuming you prefer to have just a single libmpv handle at your code (this is somewhat implied by your post), then this could also be a tiny js/lua script by that name (e.g. `mpvnet.lua`) which the script messages can target, and which then forwards them to your main client.

As for ignoring events - no issue as far as (lib)mpv itself. Once the client queue is full I believe it warns and then simply starts dropping events (I don't recal if it drops old or new events). Obviously the handle would still need to be destroyed at some stage regardless.

**Comment by stax76** [comment]
> It's hard to offer help because you don't actually state the original problems you're trying to solve.

I changed it because I thought it's a better design using direct messages, I didn't have a problem. When I originally designed it, I didn't know there could be multiple handles, the .NET and PowerShell script hosts don't create new handles. There are sync and also async events and the PowerShell script host is based on async events since it's a very slow language. C# users either have to use the async events or be careful not to block as it would block the main event loop... not the best design, but there are not many users, so I won't rewrite it, most things can and should be done with Lua or JS.

> As for ignoring events - no issue as far as (lib)mpv itself.

Ok, I will try this then.

Thanks for the help, I'm now no longer worried that it could cause a problem.
