### ISSUE TITLE
Lags when skipping forward/backward while output is AirPods

### ISSUE THREAD

**Issue by nguyenhimself** [mpv-player/mpv#10270]
### Important Information

- macOS 12.4.
- mpv 0.34.1.
- Source of the mpv binary: From this GitHub's Releases.

### Reproduction steps

- Open a video.
- Set the sound output to a pair of AirPods/AirPods Pro.
- Play the video, then Skip forward or backward.

### Expected behavior

- When skipping backward or forward, the user expect the video to be skipped smoothly to the desired point in time.

### Actual behavior

- When the sound output is a pair of AirPods/AirPods Pro, upon pressing the key to skip forward or backward, the video visibly lags for a few second before resuming.
- This does not happen when the outpuit sound is the computer's speakers.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/8853836/output.txt)

**Comment by LiJChang** [comment]
I got the same issue too. It seems that the issue emerged after Big Sur. I think this issue is related to #9243 or even the same issue. @Akemi mark #9243 as duplicate to #4141 but I don't see those two as exact same issue although  they might be related. I am not that familiar with the mpv call path to CoreAudio, need some inspiration to look into it.

**Comment by LiJChang** [comment]
After some code tracing I found that the cause might be [AudioOutputUnitStart](https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/audio/out/ao_coreaudio.c#L327) in ao_coreaudio.c takes too much time after seeking is done when the output audio is connected to  wireless devices.

My guess is that the way how coreaudio is initialized might be contribute to this issue. 

I suggest reopen #9243 because it's a much detailed description of this issue.

**Comment by Akemi** [comment]
we will keep this one open. since you added some infos here that aren't on the other one and they are linked after all.

**Comment by arthurzqhu** [comment]
Seems like @LiJChang has created a pull request that can potentially solve this issue. Could the maintainer take a look and merge it into the release version if it works? Was trying to build from the source code but ran into some problem probably associated with Apple Silicon Macs.

**Comment by LampPrinter** [comment]
> Seems like @LiJChang has created a pull request that can potentially solve this issue. Could the maintainer take a look and merge it into the release version if it works? Was trying to build from the source code but ran into some problem probably associated with Apple Silicon Macs.

I compiled using this guide for M1 Mac. https://gist.github.com/dbrookman/74b8bcfb37a23452f7137b83bca9580f
https://0x0.st/o50j.dmg

@LiJChang commit does solve the lag issue with bluetooth earbuds.

**Comment by nguyenhimself** [comment]
After compiling mpv on an M1 Mac, I can also confirm that @LiJChang's [commit](https://github.com/mpv-player/mpv/pull/10953) does solve the issue.

Please consider accepting his pull request. Time to close this issue at last.
