### ISSUE TITLE
Support of MP3 star rating tag

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10291]
I would like to request support of the MP3 star rating tag:

https://en.wikipedia.org/wiki/ID3?oldformat=true#ID3v2_star_rating_tag_issue

My files are tagged like so:

1star: POPULARIMETER: MusicBee|1|0
2star: POPULARIMETER: MusicBee|64|0
3star: POPULARIMETER: MusicBee|128|0
4star: POPULARIMETER: MusicBee|196|0
5star: POPULARIMETER: MusicBee|255|0

[sample.zip](https://github.com/Martchus/tageditor/files/8910665/Koan.-.Selena.s.Song.Blue.Mix.zip)

More info:

https://github.com/Martchus/tageditor/issues/84

https://github.com/MediaArea/MediaInfo/issues/620

**Comment by TheAMM** [comment]
This should be directed at ffmpeg, since mpv doesn't deal with ID3 by itself.
It's also unclear how mpv should support this. As usual, my opinion is that writing a script that uses an external tool with support for whatever you want and then using its output somehow, is the quickest way to get what you want in mpv; no waiting on projects to move, especially on something that seems this obsolete.

**Comment by stax76** [comment]
I can request it on the ffmpeg tracker.
