### ISSUE TITLE
playlist-shuffle input command is not random

### ISSUE THREAD

**Issue by gammoray** [mpv-player/mpv#10389]
- mpv version: mpv 0.34.0-365-g369168b9be
- Windows Version: Windows 10
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files

### Reproduction steps

1. Create `input.conf` with a line `<some key> loadlist playlist.txt; playlist-shuffle; playlist-next`, where `playlist.txt` is a newline-separated list of audio files. Please note this is specifically related to `input.conf`. The behavior may be different when shuffle is issued via command line option `--shuffle`.
2. Run mpv.exe.
3. Press the configured key as in `input.conf`.
4. Check the order of files in the current playlist.

### Expected behavior

The playlist order should not be the same each time the above sequence of steps is performed, with high probability.

### Actual behavior

The playlist order is the same each time.

### Log file 
[shuffle_issue.txt](https://github.com/mpv-player/mpv/files/9078144/shuffle_issue.txt)

**Comment by thebombzen** [comment]
The `playlist-shuffle` command calls the C standard library `rand()` which is a pseudo-random number generator. According to the manpages, `rand()` will use a seed of `1` unless `srand()` is called first, which in this case it is not. This gives us deterministic behavior since `srand()` is not called here.

I agree that this is a bug that should be fixed, since this behavior isn't required for `playlist-unshuffle` to work. We could always `srand()` with something non-cryptographic like system wallclock time to make this work.

**Comment by thebombzen** [comment]
See if this is fixed after 52e7269ea633b7ac3d83d7b5cba9b15c5fbcbef9

**Comment by thebombzen** [comment]
Tested it, it is.

**Comment by agguser** [comment]
It seems that without `playlist-next` (i.e. only `loadlist playlist.txt; playlist-shuffle`), the first item played is always the first item in the playlist. Is this a bug?

**Comment by thebombzen** [comment]
I believe what's happening here is that shuffling the playlist at runtime doesn't affect the currently playing index, which after calling loadlist will always be the first entry.
