### ISSUE TITLE
Which VO can support video-output-levels=full on Windows ?

### ISSUE THREAD

**Issue by CCCAUCHY** [mpv-player/mpv#10452]
Which VO can support video-output-levels=full on Windows ?
Will mpv show levels: limited or levels: full if the video only has limited RGB when video-output-levels=full is working ?

**Comment by ZaquL** [comment]
>if the video only has limited RGB 

Mpv does not support limited RGB video, because ffmpeg does not support that.

>Will mpv show levels: limited or levels: full if the video 

That is the metadata on the file, it has nothing to do with output, again only full RGB is supported even if it will be tagged as limited, it will not work.

>Which VO can support video-output-levels=full on Windows 

That is really a debug option. Unless you really did something wrong with your system lmited is selected automatically by the driver if you set in nvidia control panel limited RGB.

**Comment by Isaacx123** [comment]
What about this:
https://kodi.wiki/view/Video_levels_and_color_space
