### ISSUE TITLE
Make `--sub-back-color` to follow the shape of the subtitles

### ISSUE THREAD

**Issue by pcroland** [mpv-player/mpv#10464]
It would be nice if `--sub-back-color` would take into account that not every line has the same length when multiple lines are displayed.
Currently `--sub-back-color` creates a single box that can fit all the lines inside:
![img](https://telegra.ph/file/e3e104f07620092d8e0ff.png)
And this is how it should look like:
![img](https://telegra.ph/file/e4fb394d047ae842eba49.png)
In my opinion the current solution doesn't look that great, especially because there seems to be no way to add opacity to the background color.

**Comment by hooke007** [comment]
> no way to add opacity to the background color.

https://mpv.io/manual/master/#options-sub-color
Why not?
![Snipaste_2022-07-29_06-39-48](https://user-images.githubusercontent.com/41094733/181690258-a62f23fc-3cc3-4473-8b63-6a0778557b62.jpg)
`"#641C1C1C"`

**Comment by pcroland** [comment]
Oh, thanks. I tried some wrong values then. I'm still curious about the box shape though.

**Comment by idiotpatrol** [comment]
>  Why not?

Its much easier to read the text when there's background color (contrast). Especially when watching something with a different audio language than the actual text.  The less effort to read it, the better (imo).

**Comment by estrogently** [comment]
I would also prefer each line having its own background width. Digging back, this actually used to be the default a decade ago but was changed because it didn't play well with semi-transparent backgrounds (#822).

Hopefully it's been fixed on the libass side by now. If not, I'd still enjoy seeing it as an option—less need for background opacity when the background covers less of the screen to begin with.

**Comment by Dudemanguy** [comment]
Fixed by https://github.com/mpv-player/mpv/pull/14195
