### ISSUE TITLE
Color management with --vo=gpu-next, difference between --lut --image-lut and --target-lut plus type? 

### ISSUE THREAD

**Issue by Isaacx123** [mpv-player/mpv#10465]
I have various questions about color management with --vo=gpu-next.
My goal is to simply color correct the videos to my calibrated monitor.
I calibrated the display using DisplayCAL with a ColorMunki Display colorimeter.
Previously with --vo=gpu what I did was to load the icc profile with --icc-profile=<file> but now that mpv can use 
user generated 3dluts with gpu-next I need some help.
First question, what is the difference between --lut --image-lut and --target-lut? Which one should I use to color managed videos a la --icc-profile?
What is the difference between lut types? native, normalized and conversion? 
And lastly, what would be the correct settings for creating the 3dlut with 3DLUT Maker? Which rendering intent? Should I apply vcgt even thought the DisplayCAL profile loader is working?
![Capture](https://user-images.githubusercontent.com/75648063/181661573-f8b92af0-1f7a-4662-be2b-6f92f82ef6a0.PNG)

99% percent of the content I watch is SDR bt.709/bt.1886
My monitor uses a WCG panel with 89% DCI-P3/100% sRGB. 

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/9215161/mpv.log)

**Comment by haasn** [comment]
I am not familiar with the 3D LUT generator you are using, so I can only speculate myself. But from what it looks like, it's generating a *conversion* LUT from one colorspace (e.g. Rec709) to another? In this case, you have two options:

1. Use `--target-prim=bt.709 --target-trc=bt.1886 --target-lut=<generated lut>`. If the content is not BT.709/BT.1886, **mpv will perform a conversion to BT.709/BT.1886 internally**. In this case, it really only is replacing the ICC profile step (which shouldn't really give you an advantage in practice over the built-in ICC 3DLUT generator).
2. Use `--lut-type=conversion --lut=<generated lut>`. In this case, mpv does no internal conversions at all - giving you complete control over the conversion. But if the content is not BT.709/BT.1886, the output will simply look wrong. (Of course, you can choose a different source profile for different types of content)

In theory these two methods should produce the same results on BT.709/BT.1886 content (and they should also be identical to the ICC profile output), but no guarantees given.

Also, you almost surely want to set both input and output encoding to Full range RGB.

**Comment by Isaacx123** [comment]
The second method looks good, I wonder if I should disable DisplayCAL's profile loader if I applied the vcgt to the 3dlut or I should restart the gamma ramps like with madVR.

**Comment by bodayw** [comment]
> The second method looks good, I wonder if I should disable DisplayCAL's profile loader if I applied the vcgt to the 3dlut or I should restart the gamma ramps like with madVR.

Not sure if you already figured this out, but just in case: if you applied VCGT to the 3DLUT, you'll _have to_ reset the gamma ramps (i.e. add an exception to the DisplayCAL loader for mpv.exe and choose "reset VCGT"), otherwise the VCGT is effectively applied twice, so the colors would be wrong.

Or, you can choose not to apply VCGT to your 3DLUT, and then you need to make sure the VCGT is always loaded.

The former is the default and recommended by DisplayCAL & madVR, but personally I've always use the latter approach, because I don't like the color tint suddenly appeared upon starting my video player right before the video starts playing, and I do sometimes play the video in window mode instead of full screen, and resetting the VCGT would make everything else except the video player window to have "wrong" colors.

**Comment by Isaacx123** [comment]
Thank you for the clarification @bodayw

**Comment by Isaacx123** [comment]
Hey @bodayw, do you know if I also have to reset the gamma ramps with the --icc-profile settings? 
I am using a XYZLUT+MTX profile.

**Comment by bodayw** [comment]
> Hey @bodayw, do you know if I also have to reset the gamma ramps with the --icc-profile settings? I am using a XYZLUT+MTX profile.

No, because mpv's `--icc-profile` doesn't read the VCGT in the .icc/.icm file (if it does have it), and assumes you already take care of that yourself. Just make sure VCGT is loaded (i.e. using DisplayCAL's profile loader), and use `--icc-profile` to take care of the rest.

I would recommend add an exception to the DisplayCAL loader for mpv.exe in this case as well, but choose "disable" instead of "reset", so the profile loader is temporarily disabled (but the VCGT is still loaded) while mpv is running. Reason being that re-applying VCGT while mpv playing videos could cause stuttering kind of glitches on lower spec machines.

**Comment by Isaacx123** [comment]
Thank you very much @bodayw
