### ISSUE TITLE
mpv dosent cover up whole screen in fullscreen mode

### ISSUE THREAD

**Issue by MathiasDevelopes** [mpv-player/mpv#10474]
### Important Information

Provide following Information:
- mpv version
0.34.1-dirty 
- Linux Distribution and Version
EndeavourOS Artemis 22.6
- Source of the mpv binary
Pacman 
- If known which version of mpv introduced the problem
Not known
- Window Manager and version
KDE Plasma 5.25.3
- GPU driver and version
Nvidia Proprietary 515.57
- Possible screenshot or video of visual glitches
https://i.imgur.com/pN9LuL4.jpg

### Reproduction steps

When i open a video file with mpv, if i try to fullscreen the window, it only covers about 80% of my screen.
NOTE: This issue is not related to the fullscreen button in mpv, that works.

### Expected behavior

The window goes into fullscreen like every other app i use.

### Actual behavior

The mpv window only covers about 80% of my screen

### Log file

http://0x0.st/oeTq.txt

**Comment by CounterPillow** [comment]
your log file does not show the player actually playing anything, so we can't see anything about the window geometry in it.

**Comment by MathiasDevelopes** [comment]
@CounterPillow sorry about that. I will play something then run the log again.

**Comment by MathiasDevelopes** [comment]
@CounterPillow I fixed it now. The updated link is http://0x0.st/oeTq.txt

**Comment by MathiasDevelopes** [comment]
Hmm. That is weird. I use a fresh install of endeavours, so i will search what could be causing it.

**Comment by MathiasDevelopes** [comment]
I have searched it up, and i dont seem to be getting any clear answer as to what could be causing this,

**Comment by MathiasDevelopes** [comment]
I found out the issue. The aspect ratio is different when it is not in fullscreen mode in mpv, so the window dosent go all the way to the sides. I would rather prefer that the video had black bars, but whatever.

**Comment by qmega** [comment]
You probably want to add `no-keepaspect-window` ([documentation](https://mpv.io/manual/stable/#options-no-keepaspect-window)) to your config file. That will allow maximizing to fill the whole screen (with black bars where necessary) and will also allow you to tell kwin to fullscreen mpv in the same way mpv fullscreens itself.

(Probably you're maximizing rather than fullscreening (kwin usually won't let you fullscreen an aspect-locked window that doesn't match the display) and aspect ratio prevents filling the whole screen.)

**Comment by MathiasDevelopes** [comment]
@qmega Wow thanks for the help! I appreciate it very much
