### ISSUE TITLE
Significantly Less GPU Usage Using Vulkan API?

### ISSUE THREAD

**Issue by JacobF-dev** [mpv-player/mpv#10490]
The title says it all: Using the `Vulkan` backend results in a GPU usage of ~4%, while other APIs (`D3D11` and `OpenGL`) result in ~30% usage. The CPU usage is unaffected.

I'm running a Nvidia GTX 1070 with latest drivers, and this issue can be observed on both `gpu` and `gpu-next` video outputs.

Is there any reason `gpu-api=vulkan` results in massively lower GPU usage? Is it due to better optimization? Is the GPU skipping steps to achieve this?

**Comment by haasn** [comment]
Maybe it's not being measured properly 😉

**Comment by aufkrawall** [comment]
Indeed Vulkan async compute load isn't mirrored by Windows D3D GPU usage value. Can't recall if this is what's seen in Task Manager metrics. But I guess it's more likely that it's about clocks, it tends to report higher GPU usage when the card runs with lower clocks due to lower loads. Setting to maximum performance for mpv in the Nvidia driver should make the results more comparable, in case they weren't before due to this.
