### ISSUE TITLE
What exactly do the tscale-window, tscale-clamp and tscale-radius options do?

### ISSUE THREAD

**Issue by fighuass** [mpv-player/mpv#10508]
I've read the docs but I don't really get it.

**Comment by thebombzen** [comment]
`--tscale-window` lets you specify a custom windowing function for the tscale's kernel. If you aren't really sure what a "windowing function" is then you should probably leave these alone as as the defaults are very good. `--tscale-radius` likewise fine-tunes the scale radius in the temporal domain.

`--tscale-clamp=1.0` (the default) prevents negative values from being used as weights in the scaling convolution kernel, which is particularly useful to prevent temporal ringing (i.e. you might see quick flashes otherwise).

**Comment by Hrxn** [comment]
> I've read the docs but I don't really get it.

https://en.wikipedia.org/wiki/Window_function
https://en.wikipedia.org/wiki/Clamping_(graphics)

Well, what do you expect, that the mpv manual should explain the entire DSP terminology? It's already long enough, you can't fit in *everything*..
