### ISSUE TITLE
1 question for HDR, 1 question for libplacebo.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#10507]
1. Although it is not a MPV specific question, but I'm really curious that if there is any video player can fully decode Dolby Vision Profile 7 on PC?
2. MPV uses libplacebo now, does it mean MPV is working with VLC development team now?

**Comment by ZaquL** [comment]
> 1. player can fully decode Dolby Vision Profile 7 on PC

MEL, everything except dynamic metadata.

FEL (no NLQ, no EL merge), no, but there other options: https://github.com/quietvoid/vs-nlq and https://github.com/erazortt/DoViBaker

quietvoid submitted nlq patches of FEL. https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=7164

**Comment by thebombzen** [comment]
> The opposite, I think, mpv team is working for ffmpeg and videolan now.

No? libplacebo is essentially haasn's rewrite of mpv's rendering abstraction layer as a separate library, that has since been adopted by VLC.

**Comment by haasn** [comment]
> The opposite, I think, mpv team is working for ffmpeg and videolan now.

The "mpv team" consists of many people, many of whom are not me.

**Comment by danbezerra** [comment]
@ZaquL please help with a clarification - does doViBaker merges FEL data with the RPU - in other words, would I take advantage of FEL improvements to poorly authored base layers even on DV players that don't consume FEL as of today?

In my scenario, I need to tonemap/convert HDR to SDR (keeping BT.2020) as I use a JVC projector with ~100 nits. Any advice on what config options I should use? I think I need to set both -target-prim and --target-trc to BT.2020 as my JVC is configured to Gamma 2.4 and BT.2020 when handling the same HDR->SDR scenario with MadVR today.

**Comment by ZaquL** [comment]
> does doViBaker merges FEL data with the RPU -

How can you merge text, which is ehat RPU really is, binary XML, with video, that is FEL? No, FEL is merged with BL.

>would I take advantage of FEL improvements to poorly authored base layers even on DV players that don't consume FEL as of today?

Well, sure? What is your question? Of course applying FEL will be better.

>I need to tonemap/convert HDR to SDR (keeping BT.2020) as I use a JVC projector with ~100 nits. 

It will be done automcatically if you set --target-trc, since it is trc that defines SDR or HDR it is. Is your projector HW calibrated to P3 or BT.2020? Or SW? I.e do you have icc profile, for rel calibration, HW that is, there i no any ICC profile, 3DLUT is inside the projector itself. In that case, if you are sure it is accepting bt.2020 (in SDR) correctly then you are right --target-prim will do the job. Do not forget to use lastest HEAD of master, there was a recent fix.

**Comment by danbezerra** [comment]
Thanks @ZaquL! It's even better that the FEL is merged wit BL - opens the possibility of also using/comparing with  MadVR.

Yes, my projector can handle SDR on BT.2020 - that's how I use it with MadVR today. Will give it a try with MPV.

Cheers

**Comment by ZaquL** [comment]
> projector can handle SDR on BT.2020

Does it do it by default, I hope not? Do you have to set it like in LG CX override menu?

**Comment by danbezerra** [comment]
No, not by default. With the JVC I can select what color space & gamma I want independently of the resolution or SDR/HDR input. So I have profiles (picture modes) for SDR+709 (Blu-rays), SDR2020 (for HDR movies tone mapped to SDR 2020 with MadVR) and regular HDR (for streaming content). 

The proposal of DoViBaker is really interesting - because it would allow me to take advantage of FEL for titles that have a really poor authored base layer such as Total Recall by applying the FEL improvements to the Base Layer. I looked again at DoViBaker and it seems I need to compile it and then use it as part of AvSynth (which I also never used...).  Ideally this would be integrated with the Dolby Vision tools by Quietvoid... One can dream!

**Comment by thebombzen** [comment]
Don't have discussions on unrelated issues.
