### ISSUE TITLE
Mpv ignores keepaspect argument when resizing with AltSnap (Fork of AltDrag)

### ISSUE THREAD

**Issue by rp1231** [mpv-player/mpv#10502]
### Important Information

Provide following Information:
- mpv version  0.34.0-396-g2c46ae8ea3
- Windows Version: Windows 11
- Source of the mpv binary: Shinichiro's builds

### Reproduction steps
Resize using Altsnap Hotkey action or scroll action.

### Expected behavior
Resizing the window should respect the `keepaspect` argument

### Actual behavior
Mpv ignores keepaspect argument allowing for blackbars

### Extra description
Potplayer has a similar option and respects the aspect ratio when resizing with AltSnap.
This issue has been mentioned in issue #6588.

**Comment by garoto** [comment]
Welp, my personal counterpoint is that I use AltSnap to resize my mpv windows with this exact purpose in mind, as in to freely resize the player window disregarding any aspect ratio settings inherited from the player or the media.

https://user-images.githubusercontent.com/11768175/183511835-7049c69e-228d-4961-bd53-4c24f8d1b329.mp4

**Comment by thebombzen** [comment]
It means "every change breaks someone's workflow" since it appears people use this behavior intentionally (see garoto's comment above).

**Comment by garoto** [comment]
> thebombzen What does the `spacebar-heating` label mean?

It originates from a xkcd comic: https://xkcd.com/1172/

**Comment by avih** [comment]
The behavior in mpv is that the aspect is enforced only when the user manually reizes the window. Specifically, at the WM_SIZING message handler.

In other cases, like a 3rd party application sets the size, or Windows itself while snapping the window (e.g. with WIN+LEFT etc), mpv does not override the set size, and so the aspect might not match the video.

This is a good behavior from mpv, because otherwise two applications would "fight" over the size, and one of them is guaranteed to lose if they want different sizes. I don't think we should change it in mpv.

If you want mpv to override the size which AltSnap sets, then AntSnap needs to emulate manual user resize, specifically so that mpv sees the WM_SIZING message.

**Comment by avih** [comment]
> So it should be possible from mpv as well?

It's not possible currently, and in my opinion it should not be possible.
