### ISSUE TITLE
Is there any method to get every decoded video frame data(e.x. yuv data) ?

### ISSUE THREAD

**Issue by lovelypp777** [mpv-player/mpv#10519]
Is there any method to get every decoded video frame data(e.x. yuv data) ?
 I want to get decode video data to do object detecting (using deep learning algrothom), then osd some label and rect to data before rendering the video data.

thanks!

**Comment by stax76** [comment]
I don't know it helps, there is this:

https://mpv.io/manual/master/#command-interface-screenshot-raw

**Comment by thebombzen** [comment]
The best way to do this is to use VapourSynth, and write a vapoursynth script to do that, and then use `--vf=vapoursynth=myscript.vpy`.

**Comment by ZaquL** [comment]
extractplanes=y.

**Comment by sfan5** [comment]
mpv is a video player not a decoder library, look into using ffmpeg or FFMS2 and do the rendering yourself in the end. Or just use OpenCV for every part of the chain since it's really meant for your usecase.
If you really want to preserve normal video player functionality while doing object detection then a VapourSynth script is the way to go like @thebombzen suggested.

**Comment by lovelypp777** [comment]
It seems that a video filter is suited for this situation.   Despite of the ojbect detection proecss, it seems just like a intermdiate video process.
Since I have no knowledge about vapoursynth before. I still have the following question:
1. can vapoursynth support get every raw video frame ?
2. can I modified the raw video frame just like osd or labeling on the video frame ?

thanks!

**Comment by sfan5** [comment]
vapoursynth can do both of those, yes.

**Comment by lovelypp777** [comment]
> vapoursynth can do both of those, yes.

I will try it later. thanks very much
