### ISSUE TITLE
Osc visibility - on mouse hover

### ISSUE THREAD

**Issue by grappas** [mpv-player/mpv#10520]
https://mpv.io/manual/master/#on-screen-controller-osc-visibility

There's three options:
- never
- always
- on mouse movement

How about third option:
- on mouse hover

OSC shows up only when mouse pointer is over zone where OSC controls are to be expected (bottom or top).

**Comment by avih** [comment]
> There's three options:
> 
>     * never
>     * always
>     * on mouse movement
> 
> How about third option:

It already has 3, but just in case you meant fourh...

add `--script-opts-add=osc-hidetimeout=3600000` to show the osc on hover for an hour.

Use bigger or smaller numbers as you need. Keep in mind that in fullscreen it's always hovering, so you can't move the mouse out to hide the osc again (unless you have multiple monitors, or you're waiting for an hour so that it hides).

If you want to disable this behavior in fullscreen, you can use a lua script, similar to this:
```lua
mp.observe_property("fullscreen", "native", function(_, fs)
    -- 500 is the default, 3600*1000 is one hour
    local hto = fs and 500 or 3600*1000
    mp.command("change-list script-opts append osc-hidetimeout=" .. hto)
end)
```

Anyway, mpv won't add such feature, because it's quite simple with options or scripting, and the vast vast majority of users don't need it.

**Comment by grappas** [comment]
> add --script-opts-add=osc-hidetimeout=3600000 to show the osc on hover for an hour.

That's not what I meant at all:

> mouse pointer is **over zone where OSC controls are to be expected** (bottom or top).

That if mouse pointer is over middle of the window for example OSC doesn't show up. If i.e. mouse pointer is over time bar or close button only then OSC shows up.

**Comment by Dudemanguy** [comment]
That sounds like the deadzonesize option.

**Comment by grappas** [comment]
Yes, that's it! Thanks mate.
