### ISSUE TITLE
Rewind X amount of seconds whenever mpv is in a "paused" state

### ISSUE THREAD

**Issue by Cananbolt** [mpv-player/mpv#10703]
Is there a lua script, or an mpv.conf prompt that can let you rewind for a couple of seconds when in the paused state?

**Comment by christoph-heinrich** [comment]
``` lua
mp.observe_property('pause', 'bool', function(_, val)
    if val then
        mp.commandv('seek', -2)
    end
end)
```

**Comment by Cananbolt** [comment]
Thank you so much, this is close to exactly what I wanted. However, I don't use hr-seek=yes in mpv.conf. so instead of it seeking 2 seconds backwards it goes back based on the framesteps.

I'm sorry for asking so much, but is there a way for it be an exact amount. I tried doing...

`'seek-exact', -2`

But this didn't work any ideas?

**Comment by christoph-heinrich** [comment]
I've updated it.

**Comment by dnngll** [comment]
Hello @christoph-heinrich ,

just stumbled upon this - this is brilliant! Thank you so much :)

**Comment by dnngll** [comment]
Hey @christoph-heinrich ,

I just realized a minor drawback: Quite often when pausing, I need the frame that was on while I pressed pause. Right now, the media gets rewinded directly after pausing. Would it be possible to adjust this behavior? So that it does the rewind after pressing play again?

It would be great, if that could be adjusted.

Ps.: Alternatively it could be set, so that if pausing via `frame-back-step` or `frame-step` would not trigger the script?

Thank you

**Comment by christoph-heinrich** [comment]
@dnngll replacing the `if val then` with `if not val then` should work, but depending on your needs it might be better to create a keybind.
``` lua
mp.add_key_binding('SPACE', nil, function()
    mp.command('cycle pause')
    if mp.get_property_bool('pause') then
        mp.commandv('seek', -2, 'exact')
    end
end)
```
This will pause/unpause like usual, but also seek backwards on pause for that one specific key instead of in general. If you would rather seek backwards on unpause, simply add a `not` right after the `if` keyword.

**Comment by dnngll** [comment]
Hey @christoph-heinrich ,

thanks for a quick reply. When pausing with the keybind `frame-back-step` or `frame-step`, the video will still rewind after unpausing with space. The perfect solution would be

- pausing with space -> on unpausing with space, video is rewinded
- pausing with keybind `frame-back-step` or `frame-step` -> on unpausing with space, video is not rewinded

I wasn't able to get this to work, so I will go with the addition to your first solution:

```
-- from: https://github.com/mpv-player/mpv/issues/10703

mp.observe_property('pause', 'bool', function(_, val)
    if not val then
        mp.commandv('seek', -4, 'exact')
    end
end)
```

Thank you again :)
