### ISSUE TITLE
OSD/sub overlays corrupted badly when using opengl-pbo on M1M

### ISSUE THREAD

**Issue by rcombs** [mpv-player/mpv#10708]
This happens when using mpv 5463d3eeff0aeff4f9c6d7634ace157ceb2cec57 on macOS 12.6 (21G115) with `opengl-pbo` enabled. I was testing it out to see if it might improve performance, and it does seem to reduce CPU usage substantially, but the output flickers at random between the correct image and… whatever this is:
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/819638/193472524-fb5ebc58-d7b1-468c-ac1a-82c5a4743f1b.png">

I wonder if there's some sort of race condition going on, where the overlay texture data from one frame is used with the position data from another?

Log: https://gist.github.com/8fe69aaf21bfabca10074b8a4ee4fb38

**Comment by gokieks** [comment]
Confirm this is still an issue with mpv 0.36.0 (stolendata build) on a M2 (Pro) Mac, need to disable opengl-pbo to not have OSD and subtitles be rendered malformed.

**Comment by mlindner** [comment]
I also have this issue, closed linked issue has a log file attached to it, if that's useful. I also turned on trace level debug for the osd.

**Comment by mlindner** [comment]
One further note. This started appearing right after upgrading from one of the more recent MacOS 11.x versions to 12.6.1. So it's likely because of a change introduced in Monterey versus Big Sur. The huge piles of deprecation warnings regarding OpenGL calls that I saw in the build may have something to do with it. Might be something worth looking into there.
