### ISSUE TITLE
Some nitpicks about mpv/options/m_config_frontend.c

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#10785]
https://github.com/mpv-player/mpv/blob/b44f522dba55c9e9031328e70209493111eea757/options/m_config_frontend.c#L1044

```diff
-MP_WARN(config, "Profile contains no restore data.\n");
+MP_WARN(config, "Profile '%s' contains no restore data.\n", name);
```

Add the profile name to the warning message to clarify the target. Helpful when there are many unhit restores.

And it would be better to change the script name of the message
from `[cplayer] Profile contains no restore data.`
to `[auto_profiles] Profile contains no restore data.`.

This warning is very frequent and annoying, compared to
`msg-level=auto_profiles=error,cplayer=warn`,
`msg-level=auto_profiles=error,cplayer=error` is less acceptable, that [cplayer] shows a lot of things.

**Comment by Dudemanguy** [comment]
If you want to open an PR for the diff you posted, that would be appreciated. I agree that including the profile name would be good, useful info. Unfortunately doing something like `[auto_profiles] Profile contains no restore data.` would not be a trivial change at all so that part isn't likely to happen.
