### ISSUE TITLE
Feature win32-internal-pthreads cannot be enabled

### ISSUE THREAD

**Issue by xvitaly** [mpv-player/mpv#10855]
### mpv version and platform versions

Version: 0.35.0
OS: Fedora Linux 37

### Reproduction steps

Run the build using meson.

### Expected behavior

Successful build.

### Actual behavior

```
meson.build:363:0: ERROR: Feature win32-internal-pthreads cannot be enabled: the os is not win32!
```

### Log file

[meson-log.txt](https://github.com/mpv-player/mpv/files/9995473/meson-log.txt)

The issue will be closed for ignoring the issue template.

**Comment by Dudemanguy** [comment]
`-Dauto_features=enabled`

Right, don't use this option. It'll enable features that aren't compatible with your OS.

**Comment by xvitaly** [comment]
> Right, don't use this option.

This is a default option from Fedora %meson macro.

**Comment by xvitaly** [comment]
I can't override it `-Dauto_features=disabled` due to an error:

```
ERROR: Got argument auto_features as both -Dauto_features and --auto-features. Pick one.
```

**Comment by Dudemanguy** [comment]
>This is a default option from Fedora %meson macro.

Then don't use the macro? mpv is cross platform, you can't expect to enable literally everything.

**Comment by xvitaly** [comment]
`if sys.OS() is 'Windows'` should be used.

**Comment by Dudemanguy** [comment]
It is being used. You're forcibly trying to enable a feature that's not compatible on your OS so it errors out. The same thing would happen if you passed `--enable-win32-internal-pthreads` on the waf build. Don't do that.

**Comment by SuperSandro2000** [comment]
> > Right, don't use this option.
> 
> This is a default option from Fedora %meson macro.

NixOS does the same and it is working for all packages that use meson except mpd and mpv. 

You are sure the platform check should not have higher priority then the default auto?

**Comment by Dudemanguy** [comment]
This is not the only place where you would have a problem. It just happens to be the first spot in the build. There's a lot of features that can be optionally enabled/disabled and many of them will only work on specific platforms/configurations/etc. (e.g. `d3d11` is never going to work on non-windows). The point is, you can't just blindly enable every feature (which is what that option does) and expect it to work. You either have also disable them explicitly, only enable the ones you actually want and/or let auto take care of it.

**Comment by jtojnar** [comment]
The point of `-Dauto_features=enabled` is to make it harder to forget to add a dependency, which would result in a feature being disabled with `auto` being default.

If a feature is not cross-platform, you can transform the option value with [`disable_auto_if`](https://mesonbuild.com/Reference-manual_returned_feature.html#featuredisable_auto_if) method.

**Comment by Dudemanguy** [comment]
>If a feature is not cross-platform, you can transform the option value with [disable_auto_if](https://mesonbuild.com/Reference-manual_returned_feature.html#featuredisable_auto_if) method.

This won't stop a feature that's set as `enabled` from being evaluated as `enabled`. Look, I get that passing the short `-Dauto_features=enabled` is convenient, but this just isn't going to work. We have too many features. You're more than welcome to pass `-Dx11=enabled -Dwayland=enabled` and so on.

**Comment by eli-schwartz** [comment]
A project can of course choose to ignore the value of the option altogether if it believes that setting it is "a user mistake", for example even if a user passes `-Dwin32-internal-pthreads=enabled` (rather than auto-features) on Linux then don't bother complaining and just silently disable it.

But a project might choose *not* to ignore the value of the option altogether, and mpv appears to have chosen such.

If you're using auto-features 

> to make it harder to forget to add a dependency, which would result in a feature being disabled with `auto` being default.

then that isn't incompatible with the idea of explicitly disabling the options that, as revealed by auto-features, cannot be safely enabled on non-Windows systems. It works with the current `meson.build` file as released, and satisfies the intentions of both NixOS and mpv simultaneously.

And, well, I happen to think that if you're using auto-features you are essentially saying "yes, I want to handhold the build system the whole way". Actually I'm not even sure whether it's really guaranteed to do what people want. Maybe not relevant for NixOS, but on other distros it's easily possible for users to end up in a situation where you test a build and have an unannounced dependency installed, that gets enabled. Maybe defaulting to `=disabled` is safer. :p Maybe what people really want is `-Dauto_features=error`, forcing you to manually add enabled *or* disabled for every option, and having the build error out if you ever forget to *research* a feature, rather than if you forget to *add a build dependency* to the calling build recipe.
