### ISSUE TITLE
mpv: ../sub/draw_bmp.c:174: blend_overlay_with_video: Assertion `x + w <= p->w' failed.

### ISSUE THREAD

**Issue by chrisco23** [mpv-player/mpv#10908]
### Important Information

Provide following Information:
- mpv version
mpv 0.35.0
- Linux Distribution and Version
arch linux 6.0.8-arch1-1
- Source of the mpv binary
/usr/bin/mpv, but maybe you mean the Arch repositories
- If known which version of mpv introduced the problem
I update my arch system daily, so I can't pinpoint the version necessarily as underlying libraries could be involved
- Window Manager and version
i3 version 4.21.1
- GPU driver and version
I really don't know how to find this.(?)
- Possible screenshot or video of visual glitches
The screenshot is a completely blank window.  By going into another i3 workspace, I can sometimes get to that "Oops" popup.

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

I am, 0.35.0

### Reproduction steps

Just run smplayer somevideo.mkv, or double-click the mkv file, as SMPlayer has been selected as my default player for as long as I can remember.

Again, to be clear, running mpv without smplayer so far seems fine.  In fact, the only thing I even need smplayer for is subtitles.  So with that in mind, I installed subliminal etc. earlier today, but at least on first try, with the autosub lua file, I'm not quite sure that will work for me.

My hunch is this must have something to do with interaction with i3, but I've been running this way for a long time, so I don't know what has changed.

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

It is reproducible.

For the past 2 weeks or so, mpv is crashing only when running within smplayer (should I report this someplace else then?).
The crash seems to happen after approximately 1 minute or so of playing fine.

### Expected behavior

It plays fine.

### Actual behavior

It crashes with the popup "Oops, something has gone wrong, exit 6" etc.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

I tried with --log-file=/home/mylinuxuser/output.txt, and no such file was created.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by chrisco23** [comment]
I just wanted that when initially googling this problem, I came across the issue 7791 which sounds somewhat similar, but since that was closed out in 2020, I am asking now in November 2022.  Thanks.

**Comment by qsniyg** [comment]
I assume you mean https://github.com/mpv-player/mpv/issues/7721? This issue seems to only occur on libmpv-based applications (not just SMPlayer), as I can't replicate it under regular mpv. I can easily through libmpv-based programs after a few seconds of playback, especially if I'm quickly scrubbing through the video.

**Comment by qsniyg** [comment]
The issue seems to be related to mpv resizing.

I didn't have much luck bisecting, so I'll share a test program that reproduces a crash:

```py
import mpv
import sys
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import Qt

pausetime = sys.argv[2] # Set this to where a subtitle is present in the video

class TestWindow(QtWidgets.QWidget):
    resized = 0
    def __init__(self, *args, **kwargs):
        super(TestWindow, self).__init__(*args, **kwargs)

        self.resize(100, 100)

        self.setAttribute(Qt.WA_DontCreateNativeAncestors)
        self.setAttribute(Qt.WA_NativeWindow)
        self.setWindowFlags(Qt.Tool)

        self.mpv = mpv.MPV(wid=str(int(self.winId())),
            vo='x11',
            log_handler=print,
            loglevel='info')

        QtCore.QTimer.singleShot(1000, self.settime3) # hack: wait until mpv is loaded

    def settime3(self):
        self.mpv.time_pos = pausetime
        self.mpv.pause = True
        QtCore.QTimer.singleShot(1000, self.resizatron) # hack: wait until the specified portion has loaded

    def resizatron(self):
        if self.resized > 900:
            print("Unable to replicate, try again") # sometimes it fails, you may need to try it more than once
            return
        i = self.resized
        new_geom = QtCore.QRect(
            self.geometry().x(), self.geometry().y(),
            self.geometry().width() + 1, self.geometry().height() + 1
        )
        print(new_geom)
        self.setGeometry(new_geom)
        self.resized += 1
        QtCore.QTimer.singleShot(10, self.resizatron)

app = QtWidgets.QApplication(sys.argv)
player = TestWindow()
player.show()
player.mpv.volume = 0
player.mpv.play(sys.argv[1])
player.mpv.pause = True
app.exec_()
```

Usage: `python test.py path/to/video.mp4 [seconds_until_subtitle_is_visible]`

It will create a floating window and keep increasing its size until it crashes. Each video frame crashes at same place individually (it's not random), but the place will differ depending on the frame. It may need to be run more than once, it will occasionally not crash, but instead fail to keep re-drawing the window after a certain size.

**Comment by Zehkul** [comment]
Not sure if it’s the same issue, but I can reliably crash mpv and force this failed assertion via encoding.

mpv --no-config https://0x0.st/ol7_.32.mkv --sid=1 --o=/tmp/test.mp4

Unsurprisingly the offending commit is e97819f88e451623a397b79d101497205fe849f9 (not like a lot of other stuff happened in that file)

**Comment by Dudemanguy** [comment]
I was not able to reproduce the libmpv assertion failure myself (likely it's the same offending commit anyway), but I am able to reproduce the encoding one. It occurs on my laptop though and not my desktop. The former has a 1920 width (not an integer factor of 256) while the later is 3840 (this does happen to be an integer factor of 256). Now why on earth this matters in encoding mode and why encoding mode apparently gets completely different numbers as opposed to regular playback (where this doesn't occur) is a mystery to me right now.

**Comment by Dudemanguy** [comment]
Okay I figured it out, so this line:
https://github.com/mpv-player/mpv/blob/bca516bd2c282670aa2c92663329e7d5ddf978e0/sub/draw_bmp.c#L273

causes the very last slice to extend beyond the width in the encoding case (still don't know why the numbers come out different when encoding but whatever). The old code didn't cause this because the special case of `256` width always evaluated to some super low width like `2` or something (instead of `256` which is what happens now). So honestly, it just worked by luck. I think just adjusting the last slice to be the correct width is reasonable enough and appears to work. These are the same numbers that mpv gets during just normal playback with a software vo, so it should be more correct hopefully.

**Comment by Dudemanguy** [comment]
If anyone here that can reproduce the libmpv issue can confirm if #10946 fixes it, that would be appreciated. I assume it does given the underlying cause _should_ be the same as the encoding mode assertion failure.

**Comment by homuler** [comment]
@Dudemanguy Thank you! In my case, this error occurs when playing videos using SMPlayer, and I can confirm that this error is gone if I [configure SMPlayer to use the `mpv`](https://www.smplayer.info/en/mpv) built at your branch (#10946).

**Comment by Dudemanguy** [comment]
Thanks! I tried smplayer myself but couldn't trigger that assertion for some reason. I think that commit should be good so I'll just give it a few more days in case anyone wants to comment on it.

**Comment by rado84-github** [comment]
> Thanks! I tried smplayer myself but couldn't trigger that assertion for some reason. I think that commit should be good so I'll just give it a few more days in case anyone wants to comment on it.

I don't think the commit has anything to do with the problem. In the past 7 years (ever since I started using Linux) I've been using output driver named xv and until recently it was working better than fine. But in the past few weeks I was getting these random crashes with this error:
`mpv: ../sub/draw_bmp.c:174: blend_overlay_with_video: Assertion `x + w <= p->w' failed.` which led me to this issue here. Honestly I have no idea what x+w are but I decided to change xv to x11 and suddenly it stopped crashing. Moments ago I was watching the Serbian movie "Black Cat, White Cat" when that random crash happened again. But ever since I changed the output driver to x11, the crash problem disappeared. So apparently that output driver xv is the cause of the problem. Unfortunately I have no idea who's developing xv, otherwise I'd report the problem to them.
