### ISSUE TITLE
Allow hyphen character in script names

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10957]
### Expected behavior of the wanted feature

Allow script names with hyphen character for:

1. script-binding
2. script-message-to
3. conf filename

When a hyphen is found, convert it internally automatically to underscore.

**Comment by Dudemanguy** [comment]
Well it already automatically converts it to an underscore internally. That's why you can use `foo_bar` to refer to a script named `foo-bar.lua`. The way for this feature to work would be to just allow `-` as a valid character as well. The only problem with that is that it would technically be breaking since using `foo_bar` would no longer work (you would now have to use `foo-bar`). As far as I can tell, it's always worked like this although I don't really have a strong opinion either way.

**Comment by stax76** [comment]
I meant to convert it **everywhere** from hyphen to underscore, I would like to use `script-message-to foo-bar` when the script is named `foo-bar.lua`.

**Comment by Dudemanguy** [comment]
I know but the problem is that doing that would break `script-message-to foo_bar` that used to work. Well I guess there could be some hacky workaround for backwards compatibility reasons (dunno how trivial or not that would be).

**Comment by stax76** [comment]
It appears to be simple, the function that handles script-message-to would check if there is a hyphen in the argument, if there is a hyphen it's clear that it needs a conversion from hyphen to underscore, internally it would do this conversion before further processing. Bother hyphen and underscore would work.

**Comment by avih** [comment]
Hyphen/dash in client name would make script opts ambiguous. Currently NAME-OPT (like `ytdl_hook-ytdl_path` can only be interpreted one way, but with dash allowed at the name it becomes ambiguous.

Also, what's the big issue with using only underscore?

**Comment by stax76** [comment]
Thanks for the info.

I think will try the following naming:

GitHub project: mpv-foo-bar
mpv wiki: foo-bar
script file name: foo_bar.lua
