### ISSUE TITLE
massive cpu increase with v0.35 (cause: DR on Intel iGPU)

### ISSUE THREAD

**Issue by tro-oper** [mpv-player/mpv#10972]
### Important Information

Provide following Information:
- mpv version: 0.35.0-2
- Linux Distribution and Version: Arch linux
- Source of the mpv binary: Arch community repo
- If known which version of mpv introduced the problem: 0.35
- Window Manager and version: xfwm4 4.16.1
- GPU driver and version:  xf86-video-intel 2.99.917+916+g31486f40-2
- Possible screenshot or video of visual glitches: N/A
- CPU: Intel core i3-350M (2C/4T) 2.266 GHz max

### Reproduction steps
no-config option has no effect on the problem

### Expected behavior

Before version 0.35 mpv played 1080p30 x264 files with no problem, cpu usage was between 40-60%
This is without hw acceleration. With hw acceleration, problem disappears.

### Actual behavior

After v0.35 1080p30 x264 can no longer play at required fps, cpu usage immediately jumps to 100%

Reverting to v0.34.1-5 fixes the problem.

### Log file

[mpv-log.txt](https://github.com/mpv-player/mpv/files/10169608/mpv-log.txt)

### Sample files

any 1080p (or near) x264 video will do

**Comment by sfan5** [comment]
Do you have a log of 0.34? Does `--vd-lavc-dr=no` fix it?

**Comment by tro-oper** [comment]
Yes, that option fixes it.

0.34 log:
[mpv-0.34-log.txt](https://github.com/mpv-player/mpv/files/10170138/mpv-0.34-log.txt)

**Comment by ghislain-bernard** [comment]
Thank you, I had the same problem !

**Comment by kouider01** [comment]
> Does `--vd-lavc-dr=no` fix it?
this fixed the problem for me too, thank you.

**Comment by moppman** [comment]
I noticed the same performance hit  going from v0.34 to v0.35 on an old [Thinkpad x200](https://www.thinkwiki.org/wiki/Category:X200), which was fine before.
I'm seeing `[vo/gpu] DR enabled: yes` in the v0.35 log, so `--vd-lavc-dr=no` fixes performance.

However, changing `vo` from `gpu` to `gpu-next` also "fixes" it, because with `gpu-next` I'm getting `[vd] DR failed - disabling.`  :sweat_smile:

**Comment by ascii-byte** [comment]
I can confirm this, when I play any video the CPU usage jumps to 100% causing `Audio/Video desynchronisation` but `--vd-lavc-dr=no` seems to fix it.

**Comment by theuserwhoisnotadeveloper** [comment]
@sfan5  you are a life saver! thank you very much. I have a weak pc with intel celeron N2830. mpv 0.34.1 was the best media player for it to play 1080p videos but 0.35 had a terrible performance on my machine. I had to use mplayer with smplayer frontend but it has some problems with playing .ts video formats. after the release of 0.35 I searched for a solutions for weeks but could not find anything. I did not open an issue because I did not want to bother the devs with a problem that seemed like no one else experienced but me. today, I was getting ready to open an issue. I clicked the issues page then saw the pinned post that is this one. long story short, thank you very much.
