### ISSUE TITLE
Poor performance when using ARB_buffer_storage on ARM platforms with GL output

### ISSUE THREAD

**Issue by anarsoul** [mpv-player/mpv#10997]
### Important Information

Provide following Information:
- mpv version: 0.35.0
- Linux Distribution and Version: Archlinux ARM
- Source of the mpv binary: Archlinux ARM packages
- If known which version of mpv introduced the problem: N/A
- Window Manager and version: weston-11.0.0
- GPU driver and version: Mesa-22.2
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

Try playing any video with mpv on a platform with Lima driver (however at least vc4 and panfrost are likely affected as well). Performance is terrible, mpv consumes a lot of CPU cycles.
Disabling ARB_buffer_storage with `MESA_EXTENSION_OVERRIDE=-GL_ARB_buffer_storage` results in significantly lower CPU usage.

I profiled it with perf, and it shows that most of the time is spent in libavcodec.

Apparently mpv uses directly mapped persistent coherent buffers with a decoder and assumes that the buffer is cached, but it isn't always true - it will return write-combined buffer on most ARM platforms (e.g. with vc4, panfrost, lima drivers)

It isn't a driver bug, since GL_ARB_buffer_storage spec doesn't specify whether directly mapped buffer should be cached or uncached.

Please consider adding a command line (and/or config) option to disable GL_ARB_buffer_storage usage. You may want to enable it by default on ARM platforms.

As an alternative, you can try using a staging buffer allocated with malloc for software decoder and memcpy the data into GPU buffer, it will be more efficient than using TexSubImage2D for uploading the data. Keep in mind that VPU-accelerated decoding doesn't need a staging buffer, it's only needed for software decoding.

See https://gitlab.freedesktop.org/mesa/mesa/-/issues/7862 for additional details

### Expected behavior

CPU usage is on par with TexSubImage2D code path.

### Actual behavior

CPU usage is 4x higher

### Log file

Please see https://gitlab.freedesktop.org/mesa/mesa/-/issues/7862 for log files and additional details

**Comment by CounterPillow** [comment]
> As an alternative, you can try using a staging buffer allocated with malloc for software decoder and memcpy the data into GPU buffer, it will be more efficient than using TexSubImage2D for uploading the data.

Does `--vd-lavc-dr=no` fix your issue?

**Comment by anarsoul** [comment]
> Does `--vd-lavc-dr=no` fix your issue?

It does. Is it specific to AVC decoder only?

**Comment by CounterPillow** [comment]
no, lavc stands for libavcodec, i.e. ffmpeg, i.e. any software decoder mpv uses.

Looks like we really need to have an exclusion list for direct rendering. Some low spec Intel stuff runs into this as well.

**Comment by anarsoul** [comment]
@CounterPillow you still may want to measure performance with a staging buffer. TexSubImage2D will go through map/unmap, and it's additional overhead. Copying to a directly mapped buffer should be the same as TexSubImage2D except map/unmap overhead, and memcpy usually deals pretty well with uncached buffers.

**Comment by sfan5** [comment]
FWIW this also cropped up with vendor drivers on Android: https://github.com/mpv-android/mpv-android/issues/508

**Comment by haasn** [comment]
I think it might be a good idea to disable the use of `GL_ARB_buffer_storage` by default, because there are simply too many unreliabilities surrounding it.

> @CounterPillow you still may want to measure performance with a staging buffer. TexSubImage2D will go through map/unmap, and it's additional overhead. Copying to a directly mapped buffer should be the same as TexSubImage2D except map/unmap overhead, and memcpy usually deals pretty well with uncached buffers.

I'm not worried about map/unmap overhead for one texture upload per frame. Unless we hit the slow path where we need to upload per image row. But in that case, in theory it would be equivalent (and simpler) to just write to a PBO first and then do the upload from there.

The point of direct mapping is to avoid the `memcpy`, not avoid the `map/unmap`, if we can't do that efficiently (due to lack of cached host memory), there's IMO no point in using them.

**Comment by haasn** [comment]
@anarsoul do you know if dropping ` GL_MAP_COHERENT_BIT` could get us cached buffers?

**Comment by vasilykh-arista** [comment]
> The point of direct mapping is to avoid the memcpy, not avoid the map/unmap, if we can't do that efficiently (due to lack of cached host memory), there's IMO no point in using them.

I assume the final goal is to get better performance. map/unmap are not free after all, so copying from staging buffer to directly-mapped GPU buffer may be beneficial after all. However I never benchmarked it, so I can't estimate overhead.

**Comment by anarsoul** [comment]
> The point of direct mapping is to avoid the memcpy, not avoid the map/unmap, if we can't do that efficiently (due to lack of cached host memory), there's IMO no point in using them.

I assume the final goal is to get better performance. map/unmap are not free after all, so copying from staging buffer to directly-mapped GPU buffer may be beneficial after all. However I never benchmarked it, so I can't estimate overhead

**Comment by anarsoul** [comment]
> do you know if dropping GL_MAP_COHERENT_BIT could get us cached buffers?

Nope

**Comment by haasn** [comment]
> > do you know if dropping GL_MAP_COHERENT_BIT could get us cached buffers?
> 
> Nope, at least not on Lima. You will get uncached buffer regardless (and will have to call memory_barrier, however it's no-op on Lima)

Oh, that's a shame. For what it's worth I pushed an experimental branch [here](https://code.videolan.org/videolan/libplacebo/-/merge_requests/332). But in this case I don't suspect it to make any difference.

Maybe it helps on some of the other `vd-lavc-dr` problem children, though?

**Comment by CounterPillow** [comment]
AFAIK the reason why we're getting cache incoherent buffers on those systems is because cache coherence takes up a lot of silicon space, which is money, not because the driver decides for whatever reason to give us a buffer that isn't coherent. E.g. PCIe on most ARM systems also isn't cache coherent, which is why dGPU drivers are usually borked on them. This would also explain why the low-end Intel stuff runs into the same issues but "higher" end stuff with the same driver doesn't.

With the advent of RISC-V SoCs that have GPUs, we will probably only get more platforms where our way of doing DR is actually worse than not doing it.

**Comment by anarsoul** [comment]
@haasn on most ARM platforms all the BO (buffer objects, GPU driver term, not GL) are WC, so if you want a direct map of a GPU buffer it will be uncached

**Comment by josch** [comment]
I unfortunately filed a duplicate issue #11073 and wanted to post the notes from the other issue over here so that they may be easier to find for other users who run into the same issue. The commit that broke this was 2fc327f2fdd48f0cd58a4d4382a7aa57f3fabd77. To restore previous behavior, one can either:

 * add option `--vd-lavc-dr=no`
 * add env variable `MESA_EXTENSION_OVERRIDE=-GL_ARB_buffer_storage`
 * or use the following patch:

```patch
--- a/video/out/opengl/ra_gl.c
+++ b/video/out/opengl/ra_gl.c
@@ -590,7 +590,7 @@ static struct ra_buf *gl_buf_create(struct ra *ra,
 {
     GL *gl = ra_gl_get(ra);
 
-    if (params->host_mapped && !gl->BufferStorage)
+    if (params->host_mapped && gl->version < 440)
         return NULL;
 
     struct ra_buf *buf = talloc_zero(NULL, struct ra_buf);
```

In absence of a proper solution that can close this issue, we'll probably carrying above patch against mpv in the [MNT Reform](https://shop.mntre.com/products/mnt-reform) [Debian repository](https://source.mnt.re/reform/reform-debian-packages) to make it easier for users to get their performance from before the 0.35.0 release back.
