### ISSUE TITLE
set resolution on all videos played

### ISSUE THREAD

**Issue by pinckpockett** [mpv-player/mpv#10990]
on different formatted websites that is.

**Comment by pinckpockett** [comment]
I was able to do it by editing the wording.

**Comment by Sophira** [comment]
Hi,

I found this issue after searching on Google for "Requested format is not available. Use --list-formats for a list of available formats", since it turns out I have the same issue as you where my `ytdl-format` option in mpv.conf is optimised only for YouTube.

Can you explain how you solved the issue? I don't know what you did and I'd really like to know so I can fix my own issue, and future searchers may find it useful too!
