### ISSUE TITLE
How to use mpv with Anime4K Shaders on iOS/iPadOS? Is it possible?

### ISSUE THREAD

**Issue by Tama47** [mpv-player/mpv#11017]
I'm not sure if this has been asked before but is it possible to get mpv running on iOS/iPadOS with Shaders? I've seen issues like this one #8470 where mpv is working on iOS? But can't seem to find a clear guide on how to build an iOS app or using Shaders.

**Comment by Akemi** [comment]
mpv itself does not run on iOS, there is no mpv backend for it (eg the OS frontend, window etc). libmpv on the other hand does, though you would need to write your own frontend and render loop using libmpv. otherwise everything is supported within the bounds of the opengl version and feature support on the specific iOS version (eg **compute** shaders probably won't work like on macOS).
