### ISSUE TITLE
#10944 breaks looping videos with `ao=pipewire`

### ISSUE THREAD

**Issue by q234rty** [mpv-player/mpv#11029]
### Important Information

OS: Arch Linux
mpv version: mpv 0.35.0-38-gb5373079f2
Commit which introduced the issue: https://github.com/mpv-player/mpv/commit/b5373079f20aeeba8ac80e773f3cc05692dbb51f
Window Manager and version: sway 1ade0ce7
GPU driver and version: amdgpu

### Reproduction steps

Try to play a video with `ao=pipewire` and press `Shift+L`

### Expected behavior
The video loops fine.
### Actual behavior
The video does not restart after it ends.
### Log file

https://0x0.st/o5ZJ.log

**Comment by t-8ch** [comment]
I'm not sure how this can be fixed with the current aproach.

The offending commit probably needs to be reverted.

I'll try to make #10931 a bit nicer. Explicitly stopping the AO when we definitively know that playback ha ended seems to  the only reliable way to do this.

@philipl could you also reopen #9835

This should not block 0.35.1 as other AOs seem to have the same issue

**Comment by philipl** [comment]
Reverted and reopened.
