### ISSUE TITLE
About alphabetical order

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#11030]
Hello. Why is the alphabetical order different between Windows and mpv?
For example, Windows places files with a hyphen (-) in the filename first, then filenames with ampersand (&) follow, but mpv does the reverse. Which one is correct or is there no standard?

**Comment by avih** [comment]
mpv has its own alphabetical (natural) sorting, and it does not use the OS (Linux/Windows/OSX/whatever), so that's why it's different.

**Comment by mia-0** [comment]
Also, even if mpv used the OS functions, sorting rules depend on the system locale. Since mpv uses an invariant locale internally, sorting may be affected. If you’re curious, grab a cup of tea and see 1e70e82baa9193f6f027338b0fab0f5078971fbe for an explanation of why we do this (warning: coarse language).
