### ISSUE TITLE
How to "unescape" double quotes in Lua subprocess command?

### ISSUE THREAD

**Issue by lzmunch** [mpv-player/mpv#11037]
### MPV Version and Platform
mpv v0.32.0 on windows 10

### Question
I have a question about the Lua string parsing behavior in the subprocess command.
Let's say I have a batch file that takes an argument with double quotes in it. So for example, test.bat contains
```
echo user input was: %1
```
I want to run `test.bat "hello!"` and have it  output 
```
user input was: "hello!"
```

I tried doing this with
```
mp.command_native({
    name="subprocess",
    args={mp.get_script_directory() .. '\\test.bat', '"hello!"'},
    capture_stdout=true,
    capture_stderr=true,
    playback_only=false
})
```
but the stdout is
```
user input was: "\"hello!\""
```
According to this comment (https://github.com/mpv-player/mpv/issues/5147#issuecomment-347001230), that is the expected behavior I believe? But I am wondering what if there is a way to have the double quotes " passed to the command-line without them being escaped like this. If not, what is the reasoning behind that design decision?

### Log File

[mpv_log.txt](https://github.com/mpv-player/mpv/files/10282911/mpv_log.txt)

**Comment by mia-0** [comment]
I believe this assumes POSIX-compatible shells, which Windows’ is not.

**Comment by avih** [comment]
> test.bat contains
> 
> ```
> echo user input was: %1
> ```

The problem here is probably that `echo` does not do what you think it should do.

You think that it should print the value of the first argument, but due to whatever legacy design decisions, `echo` prints the literal rest of the line after `echo ` (note the space after the command). In your case, it's the literal line which mpv constructed from the arguments to subprocess.

In other words, the `echo` command in batch/cmd.exe is broken for standard use cases.

If you replace the `echo` command at the batch with some C program which does what most people expect of `echo`, then it would work as expected, e.g. if your batch file looks like this:
```bat
myecho user input was: %1
```

And `myecho.exe` is compiled from this C program:
```c
#include <stdio.h>

int main(int argc, char **argv) {
    for (int i = 1; i < argc; i++)
        printf("%s%s", i > 1 ? " " : "", argv[i]);
    printf("\n");
    return 0;
}
```

Then the output should be:
```
user input was: "hello!"
```

> that is the expected behavior I believe?

It works as designed and as the developers expected, which is also correctly. The issue is probably that your expectations of `echo` don't match the actual behavior of `echo`.

> mpv v0.32.0 on windows 10

This is quite old. If you have more questions, please update to newer mpv first.

**Comment by avih** [comment]
> I have a question about the Lua string parsing behavior in the subprocess command
> I want to run `test.bat "hello!"` and...

Note that this example is what you'd _type_ at cmd.exe prompt. It's not a C invocation, and it's not a lua invocation, so translating it to "how do I do it from lua" is not obvious.

Assuming the question is actually "from an mpv lua script, how do I run a command as if I typed it into a terminal prompt", then the only answer which covers both Windows cmd.exe prompt, and unix shell prompt is using `os.execute` (and not subprocess), like so:

```lua
local input = 'test.bat "hello!"'
os.execute(input)
```

Using subprocess to run a shell input is possible on unix (`args = {"sh", "-c", input}`), but there's not equivalent on Windows (`args = {"cmd.exe", "/C", input}` is NOT an equivalent due to Windows shenanigans).

Do note that "emulating" shell (prompt) input by constructing it programatically from other values can become a hard problem if the values are complex and need quoting/escaping, especially on Windows.

Therefore, the typical API between programs (C, or mpv subprocess) is using a list of final string values which don't need any escaping/parsing, like `args` in mpv subprocess, where the lua string values typically become directly the `argv` array at the invoked program (or argv equivalent if not C).

The way to include literal quote values in such array is like you already did in your question - just like you include quotes in any lua string, e.g. `value = 'foo"bar'` or `value = "foo\"bar"`.

However, if you try to use this method with your `test.bat` file (like your question demonstrated) then it fails because, as explained above, eventhough the arguments go correctly into the batch file, `echo` itself does not behave like a normal command, and is basically incompatible with standard arguments construction/parsing.
