### ISSUE TITLE
[Question] How to change the shape of the OSC seekbarstyle in osc.lua?

### ISSUE THREAD

**Issue by sun95n** [mpv-player/mpv#11053]
Hi. I have `seekbarstyle=knob` set in my `osc.conf` although I would like the white space (**already traversed**) to be filled? Something like `seekbarstyle=bar` but in the shape of a circle.

Is this possible when editing [osc.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua)? Where should I edit?
![002](https://user-images.githubusercontent.com/120290802/209652214-f5824fe9-4f87-4d4d-8639-feb3270b58eb.jpg) ![001](https://user-images.githubusercontent.com/120290802/209652237-8d4e1a57-6b01-4bfd-abe5-4eabdb2765cc.jpg)

**Comment by avih** [comment]
Please stop opening question issues about how to change this or that at the OSC.

Read the OSC docs - https://mpv.io/manual/master/#on-screen-controller

If it doesn't have an option to change what you want, then mpv doesn't support it.

The only thing you can do, if you want to change something which is not supported, is to modify it yourself by editing the `osc.lua` script and use it, like you did here https://github.com/mpv-player/mpv/issues/10992#issuecomment-1365695101

And if you can't do that because you don't know lua and don't have the time to learn, then we can't help you.

**Comment by avih** [comment]
> I don't see anything wrong in asking about something I "don't know"

It's fine to ask.

> although I would like the white space (already traversed) to be filled

and I replied: it's it's not at the OSC docs then it's unsupported.

Changing the background is not at the docs, hence it's unsupported, unless you re-program the OSC code at `osc.lua`.
