### ISSUE TITLE
Does mpv support AMD AMF hardware acceleration video codec H265 and H264?

### ISSUE THREAD

**Issue by Zesko** [mpv-player/mpv#11056]
Fedora, OpenSUSE and Manjaro removed the proprietary video codec H264 and H265 from `libva-mesa-driver` (mesa) because of patent-problem.

There is the official **[AMDGPU Pro AMF](https://github.com/GPUOpen-LibrariesAndSDKs/AMF)**  that supports the video codecs.

I have already tested that ffmpeg works fine with this AMF by decoding and encoding any video.

```
$ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_pro_icd64.json ffmpeg -i {INPUT}.mp4 -vcodec hevc_amf -rc 0 {OUTPUT}.mkv
```

**My question:** 

Is that possible if mpv supports AMDGPU Pro AMF video codec?

**Comment by CounterPillow** [comment]
FYI these will be covered by precisely the same patents so you gain nothing here, I recommend using a third party mesa package for those distros that doesn't care about the slightest possibility of patent trolls.

**Comment by jeeb** [comment]
First of all, FFmpeg does not have a HWAccel for AMF.

Second of all, I see no reason to utilize AMF for video **decoding** . On linux you have VA-API for AMD and Intel as well as nvdec for nvidia, on Windows you have D3D11 VA, and there will at some point be some sort of Vulkan video decode API.

Everything underneath utilizes the same HW decoding blocks, so you do not gain from using AMD's AMF as far as I can tell.

If the problem is a badly built libva driver, just replace it as it should be fully separate from graphics drivers themselves as a module.
