### ISSUE TITLE
Resizing through KDE window rules does not work

### ISSUE THREAD

**Issue by gudvinr** [mpv-player/mpv#11134]
### Important Information

Provide following Information:
- mpv version: 0.35.0
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: community/mpv package from standard arch repository
- ~~If known which version of mpv introduced the problem~~
- Window Manager and version: kwin 5.26.5 (wayland)
- GPU driver and version: Mesa 22.3.2 (vegam, LLVM 14.0.6, DRM 3.49, 6.1.4-zen2-1-zen)
- ~~Possible screenshot or video of visual glitches~~

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

I am trying to place window at specific place and resize it.

Here's screenshot of window rules I use:
![image](https://user-images.githubusercontent.com/1712806/212116137-7a13e61d-079e-4c9f-a410-15175d21740a.png)

### Expected behavior

Window placed at specified position and has requested size.

### Actual behavior

Window placed in the right place but window size isn't updated.

If I use kwin debug console (`qdbus org.kde.KWin /KWin org.kde.KWin.showDebugConsole`), I see `clientSize 960x540` and `bufferGeometry 2560,1523 960x540` which isn't right.

I filed issue [in KDE bugtracket](https://bugs.kde.org/show_bug.cgi?id=453374#c7) first (don't mind unrelated topic, there's still discussion about MPV) and KDE developer said that this is MPV issue:
> position window rule works, but the size window rule does not. kwin asks mpv to show itself with the given size, but mpv ignores that and attaches a buffer with different size anyway. Can't fix it in kwin, please report this issue to mpv developers.

### Log file

[mpv3.txt](https://github.com/mpv-player/mpv/files/10403536/mpv3.txt) - log with WAYLAND_DEBUG=1
[mpv2.txt](https://github.com/mpv-player/mpv/files/10403548/mpv2.txt) - regular log

### Sample files

~~Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.~~

**Comment by Dudemanguy** [comment]
Does it work if you run mpv with `--no-keepaspect`?

**Comment by gudvinr** [comment]
No, also opens in small window

**Comment by Dudemanguy** [comment]
Okay, I'm 99% sure what this is now and fixing it is probably not likely because there can be bogus compositor events that we ignore and this gets caught by it.

**Comment by gudvinr** [comment]
Thank you for investigating this, all of you: dude, man and guy.

**Comment by gudvinr** [comment]
Is there a bug filed in mutter/kwin/wlroots/whatever that causes issues that force you to implement workarounds like this?

**Comment by Dudemanguy** [comment]
I might have spoken too soon. First, I need to finish up rewriting the geometry handling for fractional scaling.

**Comment by Dudemanguy** [comment]
Hmm yeah, I think I'm going to place a won't fix on this for now. I can reliably distinguish the event that plasma/kde sends to mpv in order to do this particular resize, but modifying the code to actually obey that opens up a huge can of worms. This happens during the initial startup phase where a million different things get negotiated back and forth. The geometry handling code is already really complicated as it is; I really don't want to add yet another variable in here. Looking at KDE's window rules, it's not just initial but you can do it at runtime too. It's scary.

In the meantime, I suggest just using the `--geometry` option. It's meant for exactly this and should give the behavior you want. It's actually supposed to be able to control position too but we can't do that in wayland as a client so you would still need to use the KDE rule for positioning at least.

**Comment by gudvinr** [comment]
With neither `--geometry=1254x706` as CLI parameter nor `geometry=1254x706` in `mpv.conf` I was not able to get desired window size.  It opens in small window that is around quarter of this size but position seem to be right.

I removed resize rule from KDE window rules and tried with "ignore requested geometry" both yes and no.

Here's the log:
[mpv.log](https://github.com/mpv-player/mpv/files/10485710/mpv.log)

**Comment by Dudemanguy** [comment]
Although I actually just tried `0.35` and it worked just fine (also scale = 2). There was just an off by one rounding error. I think you just didn't pass `--no-keepaspect`.

**Comment by gudvinr** [comment]
> Please try the latest commit from master. I just rewrote all of this stuff. Also keep in mind that mpv preserves aspect ratio by default so with a resolution like that, you will likely also want to pass `--no-keepaspect` to get the exact size.

I already have this. Here's my mpv.conf that I used to try this:
```
no-keepaspect-window
script-opts=osc-timetotal=yes
fs-screen=1
geometry=1254x706
```

**Comment by gudvinr** [comment]
Huh, I see that in logs mpv tries to be resized to the right size (1274x706) but in kwin debug console (and can confirm visually) that window size is 627x353, which is exactly 50% of its size.

Nowhere in my configuration I have 0.5 multiplier:
```
no-keepaspect-window
script-opts=osc-timetotal=yes
screen=2
fs-screen=1
geometry=1274x706
```

This obviously made me try to use x2 multiplier, which I did and tried geometry=2508x1412. That stretches window vertically but not horizontally.

Logs (WAYLAND_DEBUG=1)
* With 1274x706: [mpv_wl.log](https://github.com/mpv-player/mpv/files/10504616/mpv_wl.log)
* With 2508x1412: [mpv_wl_2.log](https://github.com/mpv-player/mpv/files/10504617/mpv_wl_2.log)

**Comment by Dudemanguy** [comment]
Master just rewrote all of this stuff so it *should* work but then again this shouldn't have occurred in 0.35 either... I suspect something is weird about the hidpi scaling (seems you have a factor of 2).

**Comment by gudvinr** [comment]
> seems you have a factor of 2

I have 2 displays side by side. Primary screen (1) has scale 150% and secondary (2) is 115%.

Not sure where 2 comes from, but I suspect that either kwin or wayland library or whatever treats anything between 100% and 200% as 2

**Comment by Dudemanguy** [comment]
>I have 2 displays side by side. Primary screen (1) has scale 150% and secondary (2) is 115%.

Oh no wonder. That would explain it. Fractional scaling on wayland was basically a broken mess until very recently. The next KDE release will support fractional scaling and mpv in master currently does.

**Comment by gudvinr** [comment]
It kinda does not explain it:
- Even if there would be multiplier 1.15 somewhere, I'd get window that is 1091x614 instead of 1254x706 that I want
- When I set 2508x1412, I get something like 1254x1412 instead of 1254x706
- Other apps don't do that, although these "virtual" display coordinates are PITA. That wouldn't be exactly fair comparison with most apps using gtk/qt/whatever framework that does all heavy lifting, so I'm not sure what to use as an example. But I use similar rules for firefox pip window and vlc and they kinda work fine in that regard.

**Comment by Dudemanguy** [comment]
According to your wayland logs, mpv is creating buffers at 1254x706 for the first one so that is correct. Anything the compositor does after that fact is completely out of our control because of how fractional scaling works without the fractional scale protocol (i.e. the compositor will scale it down).

For the second one, something bizarre is indeed happening and I did miss it. The created buffer is 1254x1412 instead of 2508x1412. It looks like `configure_bounds` from the compositor screws with it. I don't know why but as you pointed out, `xdg_toplevel@23.configure_bounds(1254, 2229)` happens and mpv obeys that which causes the width to be cut in half but not the height (since the height is much larger). That explains the behavior you see. You can ignore configure bounds with the `--no-wayland-configure-bounds` option.

**Comment by gudvinr** [comment]
That's some workaround galore.

I tried window rules with master branch of mpv, either of 1254x706 nor 2508x1412 don't work (I only removed geometry from mpv.conf for that test). It gets resized to 1920x1080 nonetheless:
[mpv_fix_rules_20.log](https://github.com/mpv-player/mpv/files/10512089/mpv_fix_rules_20.log)

With these options and position rule (no size rule) I am able to position and resize windows as I want:
```
no-keepaspect-window
no-wayland-configure-bounds
geometry=2508x1412
```

So, what you are saying is that after mpv sets buffer size, compositor supposedly scales down said buffer because of display scale=2, resulting in half sized window? Is there a reason why it doesn't happen with other apps too?

I am attaching log file with WAYLAND_DEBUG=1 for firefox where I open PiP window after starting video playback for youtube. I also have same window rule as I had when I captured log for mpv. Same position, same window size (1254x706).

**Comment by Dudemanguy** [comment]
>I tried window rules

Right, kde window rules won't work. It's not implemented.

>compositor supposedly scales down said buffer because of display scale=2, resulting in half sized window?

Without the fractional scale protocol, what happens on wayland is that compositors will send a scale value of the next highest integer (2 in this case) to applications. If an application uses that buffer scale (which mpv does since it tries its best to be hidpi aware), it will render at a scale of 2 which is actually **over** the target that compositor wants. This is because core wayland only supports integers not fixed numbers so there is no way for a client to know that the user actually wants a fractional value. After that, the compositor will then scale the buffer **down** to whatever the target is.

>Is there a reason why it doesn't happen with other apps too?

Those applications might not attempt to be hidpi aware (i.e. leave a buffer scale of 1) so in that case compositor only scales it up.

**Comment by gudvinr** [comment]
I'll probably leave it as is with passing double size to geometry until fractional scaling lands in kde, then I'll revisit that.  
That's not really relevant to this issue anyway but since it's not possible to use window rules, at least I get properly sized window for now.

**Comment by Dudemanguy** [comment]
Maybe I should also add `auto` to `configure_bounds`. It's not really nice if that secretly messes up the geometry/autofit you're trying to set.
