### ISSUE TITLE
Let get_script_name report actual file script name for scripts grouped in a folder

### ISSUE THREAD

**Issue by eugenesvk** [mpv-player/mpv#11172]
### Expected behavior of the wanted feature

When you group several scripts in a folder with a `main.lua` file that just `dofile` all of the sub-scripts, then try to get sub-script name with `mp.get_script_name()`, you get the name of the folder instead of the file name

### Alternative behavior of the wanted feature

Currently `mp.get_script_name()` only works for single file plugins, but for plugins grouped in a folder outputs the folder name instead

### Log file

https://gist.github.com/eugenesvk/aa2406c0442ec04a6d17eeedc54a3585

**Comment by avih** [comment]
> `mp.get_script_name()`, you get the name of the folder instead of the file name

The function name is a bit misleading. It returns the client name of that script thread. The client is the main script together with all the other files it loads/runs (e.g. using `require` or `dofile`).  The client name is unique, so that this script can be targeted e.g. with `script-message-to CLIENT MSG ...`

The client name is usually the script name without file extension if it's a single script, or the dir name if it's a directory-script (and all special chars are replaced with `_` and if two clients end up with the same name then a number is added to the name to make it unique).

So if you want the file name of the "current" script, `mp.get_script_name()` is NOT what you need, and also it should not be modified. The client name can be important and we don't want to change it to return something else.

If your script is javascript (not lua, but it could be added to lua too), then you can use `mp.get_script_file()` which does return the file name - but only of the main script. If other files are `require`-ed or loaded in some other ways then it still returns the name of the main script file - the one which mpv itself loads (in contrast to additional scripts which are loaded later by the main script).

> When you group several scripts in a folder with a `main.lua` file that just `dofile` all of the sub-scripts, then try to get sub-script name with `mp.get_script_name()`

This is not something which mpv keeps track of or even knows. mpv only loads one script (single script, or `main.lua` in a directory), and that's the name which the javascript `mp.get_script_file()` returns. mpv is not aware of all the other files which the script might load, and even if it did, it can't know which source file called some `mp.whatever()` function, because as far as mpv is concerned, the scripting engine (lua/js) is a single VM, and not individual source files which it can identify. That is the same in both lua and javascript.

However, the lua/js engine do keep track of source file names. They show up in exception/errors messages (the file and line where the error happened), and in lua you can also access it using something like this:
```lua
local script_file = debug.getinfo(1,'S').source
print(script_file)
```
