### ISSUE TITLE
`mp.get_property` for playlist file

### ISSUE THREAD

**Issue by Eisa01** [mpv-player/mpv#11269]
I am writing lua scripts for mpv and need a method to get the full path of the playlist file that was opened.

**Example of needed property:** 
`mp.get_property('playlist-path')`  to output: `C:\Users\Eisa01\Desktop\playlist.m3u`

This will enable me to write specific functions for playlist files.

**Comment by avih** [comment]
> need a method to get the full path of the playlist file that was opened.

This can't work because mpv doesn't keep track of that. Also, not all playlists have a platlylist file, e.g. `mpv file1 file2`. Also, sometimes more than one playlist is opened, e.g. `mpv plylist1 playlist2`, or any combination, like `mpv  playlist-file1.m3u  file2  path/to/dir3/`, etc. So a `playlist-path` property could be very ambiguous and inaccurate.

Even if it can work in simple cases (only one item is loaded, and it's a playlis file, and all the items in it don't expand further) then mpv still doesn't keep track because it must be consistent with more complex use cases too.

Bacally, whenever mpv tries to play an item, and that item turns out to expand to several items (e.g. because it's a playlist file, or a directory name, or it's a youtube URL which turns out to be a playlist, etc), then mpv replaces that item at the playlist with the list of items it expanded to, and that's it.

It doesn't keep track of which items were expanded, and it doesn't know in advance which items will be expanded when it's their turn to play.

So mpv doesn't have a `playlist-path` property, and is very unlikely to have one in the future.

However, you might be able to detect playlist files before they're replaced/expanded (e.g. maybe using hooks and detecting playlist file extensions, or comparing playlist [count] before/after, etc), but it won't be 100% reliable. Only you can know whether that would be enough for your needs.

**Comment by Eisa01** [comment]
Noted, thank you for the clarification.

**Comment by guidocella** [comment]
You can get a playlist's path before it is expanded by retrieving the playlist property at the beginning of scripts, rather than in event handlers:

```lua
local first_entry = mp.get_property('playlist/0/filename')
if first_entry:match('%.m3u$') ...
```

Though this doesn't work if you open it by drag and drop after starting mpv, in that case you need to use the `on_load` hook.

**Comment by Eisa01** [comment]
That is very helpful indeed and hopefully will make write the code users are requesting.
I will be testing it out. Thank you!
