### ISSUE TITLE
Invariable crash when quitting mpv

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#11342]
Is this crash pertinent for mpv or macOS? What further tests should be done?
 
```
Identifier:            mpv (mpv-build) 955a07 built on Sun Feb 19 06:47:46 2023
Code Type:             ARM-64 (Native)
OS Version:            macOS 13.2.1 (22D68)
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

libobjc.A.dylib       getMethodNoSuper_nolock(objc_class*, objc_selector*)
libobjc.A.dylib       getMethodNoSuper_nolock(objc_class*, objc_selector*)
libobjc.A.dylib       lookUpImpOrForward
libobjc.A.dylib       _objc_msgSend_uncached
RunningBoardServices  -[RBSXPCMessage _initWithMessage:]
RunningBoardServices  -[RBSXPCMessage init]
RunningBoardServices  +[RBSXPCMessage messageWithEncoder:]
RunningBoardServices  +[RBSXPCMessage messageForMethod:arguments:]
RunningBoardServices  +[RBSXPCMessage messageForMethod:varguments:]
RunningBoardServices  -[RBSConnection invalidateAssertionWithIdentifier:error:]
RunningBoardServices  -[RBSConnection invalidateAssertion:error:]
RunningBoardServices  -[RBSAssertion _clientInvalidateWithError:]
RunningBoardServices  -[RBSAssertion invalidateWithError:]
CoreAudio             invocation function for block in HALSystem::IOHasStopped()
libdispatch.dylib     _dispatch_call_block_and_release
libdispatch.dylib     _dispatch_client_callout
libdispatch.dylib     _dispatch_main_queue_drain
libdispatch.dylib     _dispatch_main_queue_callback_4CF
CoreFoundation        __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
CoreFoundation        __CFRunLoopRun
CoreFoundation        CFRunLoopRunSpecific
HIToolbox             RunCurrentEventLoopInMode
HIToolbox             ReceiveNextEventCommon
HIToolbox             _BlockUntilNextEventMatchingListInModeWithFilter
AppKit                _DPSNextEvent
AppKit                -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
AppKit                -[NSApplication run]
mpv                   cocoa_main
dyld                  start
```

**Comment by forthrin** [comment]
@thebombzen: All the information requested in the template is actually present supplied information. Must things be formatted exactly according to the template? If yes, what is the underlying reason? Are the issues read by scripts?

**Comment by thebombzen** [comment]
You didn't post a log file, for one.

**Comment by Fujiwara-Chika** [comment]
> You didn't post a log file, for one.

another issue: mpv on macOS cannot decode JPEG-XL

**Comment by zenaan** [comment]
Getting similar issue here, debian 12/bookworm default desktop gnome wayland - when mpv finishes, either with "q"uit or video (or gif) ending, the whole (gnome/wayland) desktop crashes and have to log back in. This makes mpv almost unusable at the moment for me.

Can reliably repeat this desktop crash, sometimes with a few runs required. Sometimes zooming the video helps make the (whole desktop) crash repeat more reliably.

Laptop, intel, no gpu, docking station with external monitor.

Initially I assumed it might be an intel video driver problem, and reported here:
https://github.com/intel/media-driver/issues/1743

eventually tried reporting a bug against Debian mpc:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057119

OS: Debian 12/Bookworm
Package: mpv
Version: 0.35.1-4
no gpu
intel cpu
laptop
thunderbolt docking station with external monitor

**Comment by zenaan** [comment]
So I just tested by running gdb per the mpv gdb instructions (inside tmux, since the desktop crashes), and in my case the "end" of the mpv process is as follows:

Exiting... (Quit)
[Thread 0x7fffe4db86c0 (LWP 17783) exited]
[Thread 0x7fffe65bb6c0 (LWP 17778) exited]
[Thread 0x7fffe55b96c0 (LWP 17780) exited]
[Thread 0x7fffe5dba6c0 (LWP 17779) exited]
[Thread 0x7fffe6dbc6c0 (LWP 17777) exited]
[Thread 0x7fff9a7fc6c0 (LWP 17797) exited]
[Thread 0x7fff9affd6c0 (LWP 17796) exited]
[Thread 0x7fff92ffd6c0 (LWP 17795) exited]
[Thread 0x7fff9b7fe6c0 (LWP 17794) exited]
[Thread 0x7fff9bfff6c0 (LWP 17793) exited]
[Thread 0x7fffb8dff6c0 (LWP 17792) exited]
[Thread 0x7fffc4ffc6c0 (LWP 17791) exited]
[Thread 0x7fffc57fd6c0 (LWP 17790) exited]
[Thread 0x7fffc5ffe6c0 (LWP 17789) exited]
[Thread 0x7fffc67ff6c0 (LWP 17788) exited]
[Thread 0x7fffccbff6c0 (LWP 17787) exited]
[Thread 0x7fffcf3fe6c0 (LWP 17786) exited]
[Thread 0x7fffe75bd6c0 (LWP 17776) exited]
[Thread 0x7fffcfbff6c0 (LWP 17784) exited]
[Inferior 1 (process 17775) exited normally]
(gdb) thread apply all backtrace

Which seems to show that mpv at least appears to exit normally, but something upstream (re threads/ process within the terminal or desktop or wayland and graphics driver) is crashing.

If anyone can suggest what else I can do to test this, I would appreciate that very much.

**Comment by zenaan** [comment]
> Literally cannot possibly be the same bug because the OP is
> on macOS and this is debian.

Shall I refile to separate then?

**Comment by zenaan** [comment]
On 12/6/23, Zenaan Harkness ***@***.***> wrote:
>> Literally cannot possibly be the same bug because the OP is
>> on macOS and this is debian.
>
> Shall I refile to separate then?

Given that, according to gdb I got a clean exit of mpv, then I guess
it makes sense to be a different bug. Just let me know what you need
from me... sorry if I've done the wrong thing, I'm not a dev, just a
user.

**Comment by Akemi** [comment]
did this crash ever happen again? do you have a full crash report?

**Comment by forthrin** [comment]
I always post updates if (rare) crashes re-occur. So, no.

**Comment by zenaan** [comment]
> did this crash ever happen again? do you have a full crash report?

This bug never stopped happening for me. I tested just now and it
still happens - complete Wayland or Gnome desktop crash when I exit
mpv.

My workaround is to use vlc.

I was not able to further isolate why this could be happening.

**Comment by Dudemanguy** [comment]
Whatever you are experiencing is not related to the original reporter (macOS).

**Comment by Akemi** [comment]
okay, i will close this for now since it has been over a year. if this happens again just let me know.
