### ISSUE TITLE
Crash when exiting

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#11368]
### Important Information

Provide following Information:
- mpv version: 4f6d7a
- macOS Version: 12.3.1
- Source of the mpv binary or bundle: mpv-build
- If known which version of mpv introduced the problem: ?
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

Unknown. Happens randomly.

### Expected behavior

No crash.

### Actual behavior

Occasional crash

### Log file

[mpv.log.gz](https://github.com/mpv-player/mpv/files/10828725/mpv.log.gz)
[mpv.txt.gz](https://github.com/mpv-player/mpv/files/10828726/mpv.txt.gz)

### Sample files

N/A

**Comment by Akemi** [comment]
this looks like a problem in quartzcore and not a problem on our side.

**Comment by forthrin** [comment]
1. Is a given problem always outside mpv if the stack trace entries for mpv (and libraries) are just general ones like the main loop? (Or do you to prefer to get all crash logs anyway?)
2. Report this (and similar ones) to Apple, then?

**Comment by Akemi** [comment]
1. main thread issues are still our issues. this particular issues comes from a thread we don't manage and is probably only passively initialised by the usage of the CAOpenGLLayer we use. theoretically it can still be an issue on our end where we misuses the API that influences that other thread. it's hard to tell since it seems like a dumb race condition, but for now i am leaning to 'not our problem'.
2. yes, this one i would report to apple.
