### ISSUE TITLE
How to disable a specific script(s)?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#11396]
I actively also use mpv as an audio player, some scripts obviously may cause issues in audio-only playback — for instance [mpv-gnome-inhibit.lua](https://gist.github.com/crazygolem/a7d3a2d3c0cee5d072c0cbbbdee69286) reports to have been loaded when launching mpv with the `--no-video` flag:

>[mpv_gnome_inhibit] GNOME+Wayland idle inhibit workaround enabled. You can ignore the warning from the [vo/gpu/wayland] component.

I've experimented with `--script-opts=mpv-gnome-inhibit-disabled=yes`, no apparent effect.

---

Is this possible without creating another mpv profile?

**Comment by avih** [comment]
There's no built-in option to disable scripts which you placed at a place where scripts are auto-loaded from.

You could either place it elsewhere so that it doesn't load by automatically, and when you do need that script you explicitly load it, e.g. with `--script=/path/to/mpv-gnome-inhibit.lua`,

Or someone adds options support to the script itself (by extending the lua code of the script), so that you can enable/disable it with some script-opt which that script knows how to interpret.

**Comment by 07416** [comment]
I moved the script over: at the time this Bash alias does suffice (I use another one for audio playback):

    alias mpv='mpv --script=/home/user/Documents/mpv/scripts/mpv-gnome-inhibit.lua'
