### ISSUE TITLE
[request] automatic deinterlacing

### ISSUE THREAD

**Issue by fatalhalt** [mpv-player/mpv#1141]
hello,

i was wondering if such feature is plausible, I looked around in man pages and ffmpeg mailing lists, to my knowledge there's no realtime interlaced content detection where in case of interlaced content a deinterlacer would get switched on. vlc seems to have automatic detection, many video players on windows such as mpc-hc do good job applying automatic deint.

**Comment by zmwangx** [comment]
I second this request. Honestly I know little about video programming and just want a good player (on OS X) with a decent CLI. So do the majority of the user base, I suppose. `mpv` so far seems to prevail in all but a few respects, auto deinterlacing being one of those. For me, VLC's auto deinterlacing seems good enough. I would be really happy if mpv can match that. Currently `--deinterlace=auto` is not very intuitive:

> **auto** is a technicality. Strictly speaking, the default for  this
              option is deinterlacing disabled, but the **auto** case is needed if
              **yadif** was added to the filter chain manually with **--vf**. Then the
              core   shouldn't   disable   deinterlacing   just   because  the
              **--deinterlace** was not set.

Hmm.

I tried `idet.sh`, and it's simply too slow — I can't possibly afford running it before launching every video.

@kevmitch Thank you for your script. I got "changing filters failed" for all progressive H.264 videos I tried. I also noticed that for the interlaced MPEG-2 videos I tried, it results in a jump back of a few seconds when `Opening video filter: [lavfi graph=idet]`. I haven't tried this with other videos. (I don't know Lua and didn't read the script in detail — it seems pretty readable, so please excuse me for not providing more insightful details.)

**Comment by kevmitch** [comment]
The changing filters failed is probably because you have hardware decoding enabled. It is not possible to insert the detection filter (or the deinterlacing filter, unless your hwdec has one) with hwdec. Maybe the script should pull out hwdec.

The jumping back is a second pass to detect telecine. This might be avoided by using the new repeated field detection in ffmpeg, although it might not be as robust.

**Comment by zmwangx** [comment]
@kevmitch Thanks for the explanation.

> The changing filters failed is probably because you have hardware decoding enabled. It is not possible to insert the detection filter (or the deinterlacing filter, unless your hwdec has one) with hwdec. Maybe the script should pull out hwdec.

Yes, I do have hardware decoding enabled by default. That explains the problem. In hindsight I never tried to toggle deinterlacing for H.264 videos since 99% of H.264 videos I deal with are progressive, so disabling detection when hwdec is on isn't a big problem for me.

> The jumping back is a second pass to detect telecine. This might be avoided by using the new repeated field detection in ffmpeg, although it might not be as robust.

The jump back thing is more of a deal breaker for me, since ideally I would call `start_detect` at the beginning of every video (not only when I press the keybinding) to emulate real *auto*deint, but having a jump back would be unacceptable. (And after all I seldom deal with telecined videos.)

**Comment by wm4** [comment]
You could also just enable deinterlacing manually at runtime with ``shift+d``. The appeal of kevmitch's filter is mostly that it autodetects interlacing, I think.

**Comment by zmwangx** [comment]
@wm4 Yes, I know that. Auto detection is what I'm looking for.

**Comment by rrooij** [comment]
Automatic deinterlacing is already available as Lua script in TOOLS/lua

This issue should be closed in my opinion.

**Comment by wm4** [comment]
I don't know, this is still a valid point to discuss.

**Comment by wm4** [comment]
All deinterlacers that shift+d can insert now skip frames by default that are not marked as interlaced, which might or might not help with your problem.
