### ISSUE TITLE
Why using BT.1886 with 1/1000 black point for color conversion?

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#11422]
This is inconsistent with davinci resolve's behavior.

Upper: DaVinci Resolve from Rec.709 to linear.
Lower: `mpv --gpu-next --target-trc=linear`.
![image](https://user-images.githubusercontent.com/50797982/223510290-a2ef703f-99ee-418d-869b-4fcdeaf340b4.png)

I did some quick testing and looking, DaVinci Resolve, ACES-ctl, open-DRT all use gamma2.4 (BT.1886 with 0 black point) as tf.

**Comment by haasn** [comment]
For consistency with the behavior when using ICC profiles, which include true black point information, libplacebo internally uses an absolute luminance scale pipeline.

As for why 1000:1 is assumed, it's because it matches the contrast of typical desktop LCD monitors.

**Comment by YomikoR** [comment]
Is there a way to change the 1000:1 contrast guess value?

**Comment by sommio** [comment]
It is considered a [better compromise](https://github.com/mpv-player/mpv/issues/8082#issuecomment-754959919) that vo_gpu still uses zero black level by default

**Comment by sommio** [comment]
> Is there a way to change the 1000:1 contrast guess value?

In vo_gpu_next, if you want zero black level you can use `vf=format:gamma=gamma2.4`, as for[ `icc-force-contrast`](https://github.com/mpv-player/mpv/issues/9752#issuecomment-1441424448) it is still not available

**Comment by YomikoR** [comment]
> It is considered a [better compromise](https://github.com/mpv-player/mpv/issues/8082#issuecomment-754959919) that vo_gpu still uses zero black level by default

Why is asking the player to assume non-standard input making things any better?

**Comment by sommio** [comment]
> monitors

In most LCD monitors it will make dark scenes too dark, you can test [_Yuru Camp Season 2 [02]--start=12:50_](https://nyaa.si/view/1565081)

**Comment by natural-harmonia-gropius** [comment]
Looks like the creator can't output the video in BT.1886 with black point. Shouldn't the black point only be used in the last OETF? 

By default BT.1886 doesn't do anything with BT.709 input/output. But it makes the linear result darker,  Is this the right behavior in RGB to RGB matrix (for example BT.2020 to BT.709)?

**Comment by haasn** [comment]
> Is there a way to change the 1000:1 contrast guess value?

Yes, use an ICC profile

**Comment by YomikoR** [comment]
> > Is there a way to change the 1000:1 contrast guess value?
> 
> Yes, use an ICC profile

The situation is like, I have a monitor with a decent sRGB mode, but if I use Win stock profile instead of profiling by myself, the calculated contrast is inf.

**Comment by bodayw** [comment]
> > > Is there a way to change the 1000:1 contrast guess value?
> > 
> > 
> > Yes, use an ICC profile
> 
> The situation is like, I have a monitor with a decent sRGB mode, but if I use Win stock profile instead of profiling by myself, the calculated contrast is inf.

`--icc-force-contrast` is exactly for this kind of situation (however not supported in `--vo=gpu-next` at the moment).

In fact, contrast ratio cannot be detected in a lot of "measured" ICC profiles as well, e.g. any of those with just "single curve+matrix", not just "stock" (standard) ones like sRGB.

Unfortunately, AFAIK these "single curve+matrix" profiles are the only ones correctly handled by many popular color management systems, including ColorSync on macOS (at least since 10.11), FireFox on Windows (since 78.0), and Chromium ever since they had color management support. Things might have changed in the last couple of years, though, as I'm not fond of checking this all the time.

Therefore I'm using a "single curve+matrix" profile as well, and for mpv I just set `--icc-force-contrast` and specify the number in the report from DisplayCAL (when verifying the calibration).

**Comment by haasn** [comment]
> > > Is there a way to change the 1000:1 contrast guess value?
> > 
> > 
> > Yes, use an ICC profile
> 
> The situation is like, I have a monitor with a decent sRGB mode, but if I use Win stock profile instead of profiling by myself, the calculated contrast is inf.

And what's wrong with using the profiled profile?

> --icc-force-contrast is exactly for this kind of situation (however not supported in --vo=gpu-next at the moment).

The situation in libplacebo is that we cannot support `icc-force-contrast`, by design, since libplacebo uses an absolute scale internal pipeline. If you just naively implement the equivalent of `icc-force-contrast` in `--vo=gpu-next`, it will cause black clipping because libplacebo will target a black point that is not equal to the one used inside the ICC profile.

My understanding is that ICC profiles which map to 0 have a form of perceptual black-point compensation already baked into the curves, so repeating this inside libplacebo would be redundant. So in this instance, it's correct actually to decode with infinite contrast gamma 2.4 and pass it to the ICC profile as-is. (Which is what we do, currently)

`icc-force-contrast` was a hack for `--vo=gpu` which used an entirely different pipeline, and should not need to exist in `gpu-next`. I'm having trouble understanding what issue you're trying to solve here - when I use a BT.1886-calibrated monitor with a BT.1886 input curve, the output looks nearly perfect (easily distinguishable black ramp). When I use a gamma 2.2-calibrated monitor with a BT.1886 input curve, and set `--target-trc=gamma2.2`, it looks identical.

**Comment by bodayw** [comment]
> since libplacebo uses an absolute scale internal pipeline

So if `--icc-force-contrast` cannot be implemented in `--vo=gpu-next`, something functionally equivalent would be in the form of specifying absolute values in cd/m^2 (min & max), similar to `--target-peak`?

> My understanding is that ICC profiles which map to 0 have a form of perceptual black-point compensation already baked into the curves, so repeating this inside libplacebo would be redundant. So in this instance, it's correct actually to decode with infinite contrast gamma 2.4 and pass it to the ICC profile as-is. (Which is what we do, currently)

Do you mean that there is no need to use `--icc-force-contrast` if one is using an ICC profile with infinite contrast?

I just realized that the "detected contrast is too high" warning is gone, even if I remove the `--icc-force-contrast` setting in my `mpv.conf`. I have been using this setting for quite some time and never noticed the change. Is it because the same reason you stated above?

But then I'm a bit confused here: when using an "infinite contrast" ICC profile, there are obvious color discrepancies between `--vo=gpu` and `--vo=gpu-next` with default settings, which is probably not a user would expect.
