### ISSUE TITLE
mpv does not set window title when attached to an existing window

### ISSUE THREAD

**Issue by ivanp7** [mpv-player/mpv#11528]
### Important Information

- mpv version: `mpv 0.35.1-dirty`
- Linux Distribution and Version: `Artix Linux`
- Source of the mpv binary: `mpv package from the official repo`
- Window Manager and version: `bspwm 0.9.10`
- GPU driver and version: `nvidia-dkms 525.89.02-2`

### Reproduction steps

mpv does not set window title when attached to an existing window (tabbed) using `--wid`.

This does not set window title:

`mpv --no-config --wid=$(tabbed -cd) --title='TITLE' video.mp4`

This sets window title:

`mpv --no-config --title='TITLE' video.mp4`

### Expected behavior

This should set window title:

`mpv --no-config --wid=$(tabbed -cd) --title='TITLE' video.mp4`

### Actual behavior

`mpv --no-config --wid=$(tabbed -cd) --title='TITLE' video.mp4`

Window title is empty. Other applications, like nsxiv and st, work with tabbed as expected.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/11114207/output.txt)

**Comment by Dudemanguy** [comment]
So this behavior actually dates back to fbccddb48b4c71c18300b092ef7a3860be2a659a. It's very easy to undo since mpv deliberately doesn't set the title if it's embedded. I guess this might interfere with applications that are using mpv embedded and not expecting the title to change but a quick look at something like smplayer shows that they do their own work anyway to mess with the title. So I think I'd be fine with trying this out.
