### ISSUE TITLE
Increased gamma in screenshots with gpu-next

### ISSUE THREAD

**Issue by BEST8OY** [mpv-player/mpv#11529]
### Important Information

Provide following Information:
- mpv version: 0.35.0-336-gb77f8815
- Windows Version: 11
- Source of the mpv binary: https://github.com/shinchiro/mpv-winbuild-cmake
- If known which version of mpv introduced the problem: ?
- Possible screenshot or video of visual glitches: left is with vo=gpu-next and right is with vo=gpu.
![image](https://user-images.githubusercontent.com/70865987/228236567-2a493181-40ef-4b89-8e8b-451df7790a52.png)

### Reproduction steps & Expected behavior

1- Putting vo=gpu-next in config
2- Taking Screenshot
3- Screenshot image is not as it's seen in player

For comparison

1-Putting vo=gpu in config
2- Taking Screenshot
3- Screenshot image is as it's seen in player (similar to result of a screenshot with a config-less mpv)

### Actual behavior
Shouldn't it be as I perceive the image in player?

**Comment by Traneptora** [comment]
Can you please attach a log file?

**Comment by Traneptora** [comment]
Can you reproduce the issue with `--no-config`? If so, please attach that log file. If not, please try to figure out which config option causes the discrepancy.

**Comment by BEST8OY** [comment]
> Can you reproduce the issue with `--no-config`? If so, please attach that log file. If not, please try to figure out which config option causes the discrepancy.

Ah.
Sorry for not being clear enough.
I took those logs with a config file containing only one line (vo=*)
Either way I assume the default vo is gpu since I took a no-config log too and it says it's using gpu
The thing is gpu-next change the gamma in screenshots
[--no-config.log](https://github.com/mpv-player/mpv/files/11211501/--no-config.log)

**Comment by BEST8OY** [comment]
> However, can you attach the two `.jpg` screenshots? I'd like to look at how they are tagged.

I don't have the original files in my first comment, so I took two new SS.
[mpv-shot0002](https://user-images.githubusercontent.com/70865987/231466339-5e099748-29f6-4937-9c74-d82f00d51100.jpg)
[mpv-shot0001](https://user-images.githubusercontent.com/70865987/231466327-4ebd00b9-6ee2-43f9-806d-a00469005db8.jpg)

**Comment by Traneptora** [comment]
Those screenshots look identical other than the fact that one is slightly taller than the other one. The colors are not different.

**Comment by BEST8OY** [comment]
Closing it because no answer

**Comment by dokur0chan** [comment]
`vo_gpu` saves screenshots with sRGB gamma, and `vo_gpu_next` saves screenshots with bt.1886 gamma (which is more accurate to the rendered source, since mpv assumes bt.1886). The problem is, most applications (such as the Windows 11 Photos app and web browsers) don't know how to parse an image tagged with "BT.1886" gamma, thus they look really washed out. 

If you open the actual image file with mpv, you'll see that the `vo_gpu` image should be tagged as `Transfer: sRGB` and the `vo_gpu_next` image should be tagged as `Transfer: bt.1886`. If you open the image with a program like GIMP or Photoshop, it should respect the tagged gamma as well.
