### ISSUE TITLE
Only Japanese in the file name becomes big

### ISSUE THREAD

**Issue by HubKing** [mpv-player/mpv#11526]
I named a sample file like so in Gnome Files:

![image](https://user-images.githubusercontent.com/10900489/228844618-99f15d56-c517-474a-84f6-17ba8a30f564.png)

If I open the file in MPV, only Japanese characters in the file name become big.

![image](https://user-images.githubusercontent.com/10900489/228844221-ae6a843e-6095-46b9-9aa7-32879c2669a0.png)

![image](https://user-images.githubusercontent.com/10900489/228846124-5ee7dfa4-92eb-4521-8ae4-84105fb6d9ef.png)

There seems to be nothing related to font in `mpv.conf`, so I wonder where it gets the font settings? Does MPV affected by QT6CT?

Gnome font settings
![image](https://user-images.githubusercontent.com/10900489/228845337-4d0c6ccc-a996-40d4-8080-f02c93e26754.png)

QT6CT
![image](https://user-images.githubusercontent.com/10900489/228845546-c99b2e34-ea81-4055-9e13-436e3154a546.png)

**Comment by sfan5** [comment]
I am pretty sure what you are seeing is this: https://github.com/libass/libass/issues/668

Summary: mpv uses libass for font rendering, not only the subtitles but also the OSC. libass does things a bit differently because it wants to be exactly compatible to Windows GDI. Different fonts have different metrics so this can happen with some combinations of CJK/Latin fonts but not others.

Short of using a different font I don't know a fix.

> QT6CT

If the config tool writes to ~/.config/fontconfig/fonts.conf as the labels suggest then this will indeed affect all applications (maybe except GTK).

**Comment by HubKing** [comment]
Well, thanks. So, the linked post mentioned Noto font which I am using too. I guess I will try other fonts.
