### ISSUE TITLE
Question: Is this a good config based on my Hardware Specs?

### ISSUE THREAD

**Issue by 0pLuS0** [mpv-player/mpv#11546]
Hi,

This is my system and hardware specs;

Slackware 15.0
Openbox 3.6.1
nvidia-driver-525.78.01
Monitor 1440p @165hz
Ryzen 5 5600X
EVGA FTW3 Ultra 3080

I wanted to know if the attached config I'm using is good enough for my specs, and I don't really need to add anything else to the config file?

[config.txt](https://github.com/mpv-player/mpv/files/11145503/config.txt)

Should I also leave in the config; ```gpu-api=auto```?

THANKS

**Comment by aicynide** [comment]
> slackware
> openbox

Not hardware specs

**Comment by 0pLuS0** [comment]
> > slackware
> > openbox
> 
> Not hardware specs

I said these are ```my system``` and ```hardware specs```. :)

**Comment by aicynide** [comment]
I would had helped you if you don't had slackware

**Comment by 0pLuS0** [comment]
What does Slackware have to do with anything?

Linux is Linux, what one can do, they all can do.

I've been using Linux 20 years, so I'm not sure what your reply is suppose to mean.

Are you just being a Troll?

**Comment by haasn** [comment]
Some of these options are very weird, e.g. where it says "extra large RAM cache" but then sets options which are significantly *lower* than the defaults.

I would also use "vo=gpu-next" instead of "vo=gpu" personally.

**Comment by 0pLuS0** [comment]
@haasn I just posted my latest config.txt above, I am using ```vo=gpu-next```.

**Comment by Traneptora** [comment]
Personally, I would use this:

```
vo=gpu-next
gpu-api=vulkan
profile=gpu-hq
hwdec=nvdec
temporal-dither=yes
video-sync=display-resample
interpolation=yes
tscale=catmull_rom
scale=ewa_lanczos
cscale=ewa_lanczos
dscale=mitchell
blend-subtitles=yes
fbo-format=rgba32f
```

**Comment by 0pLuS0** [comment]
> Personally, I would use this:
> 
> ```
> vo=gpu-next
> gpu-api=vulkan
> profile=gpu-hq
> hwdec=nvdec
> temporal-dither=yes
> video-sync=display-resample
> interpolation=yes
> tscale=catmull_rom
> scale=ewa_lanczos
> cscale=ewa_lanczos
> dscale=mitchell
> blend-subtitles=yes
> fbo-format=rgba32f
> ```

I have all of these except for for ```tscale=oversample``` and I don't have ```fbo-format=rgba32f```.

What do you notice, or benefit from, by using ```fbo-format=rgba32f```?

THANKS

**Comment by Traneptora** [comment]
fbo-format=rgba32f just increases the precision of all the shaders by using 32-bit float instead of 16-bit float. It will increase accuracy, but whether you can notice the slight changes is sort of up to you.

As for tscale, you can view all the options with `--tscale=help`, but for the most part you're looking at:
`oversample <-> linear <-> catmull_rom <-> mitchell <-> gaussian <-> bicubic`
in increasing order of smoothness/blurriness. I find catmull_rom to be a good middle ground that suits my tastes, if you prefer sharper and less smooth then you'll want to default to triangle or oversample.

**Comment by 0pLuS0** [comment]
THANKS
