### ISSUE TITLE
MPV + G-Sync = True?

### ISSUE THREAD

**Issue by alabrand** [mpv-player/mpv#1158]
Hi! Do you know if MPV supports G-Sync in that it dials down the Hz to 24/23.976 when watching a movie?

**Comment by Cybolic** [comment]
It works just fine by default, but motion-interpolation needs a fixed --display-fps (I recommend 60), otherwise the frame-rate drops to <20 for me. Unfortunately with those settings it doesn't actually enable G-Sync, but a G-Sync enabled monitor should be able to follow along at 60FPS without tearing anyway.
