### ISSUE TITLE
Crash when using vulkan api (rtss & driver up to date)

### ISSUE THREAD

**Issue by NatsuDzn** [mpv-player/mpv#11636]
### Important Information

Provide following Information:
- mpv `0.35.0-364-gc7a8e715`
- Windows 11
- [Source of the mpv binary](https://sourceforge.net/projects/mpv-player-windows/files/64bit/)
- mpv `0.35.0-364-gc7a8e715` introduced the problem

### Reproduction steps

`mpv --no-config --gpu-api=vulkan`

### Expected behavior

It should launch fine but since mpv `0.35.0-364-gc7a8e715`, it doesn't open when using vulkan api

### Actual behavior

Seems to crash

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/11352259/output.txt)

### Notes

I'm using latest nvidia driver, and I also made a clean install but it doesn't seem to solve the issue
I have seen that some user had the same problem, but it only seems to be related to RTSS but my RTSS Rivatuner Statistics Server is up to date (v1.3.224)

**Comment by kasper93** [comment]
> but my RTSS Rivatuner Statistics Server is up to date (v1.3.224)

Are you sure? This exact layer version were crashing in the other issue. What are your RTTS version? Latest one is 7.3.4 build 27560

**Comment by NatsuDzn** [comment]
> > but my RTSS Rivatuner Statistics Server is up to date (v1.3.224)
> 
> Are you sure? This exact layer version were crashing in the other issue. What are your RTTS version? Latest one is 7.3.4 build 27560

I'm using the latest RTSS version and the VK_LAYER_RTSS is using v1.3.224

**Comment by kasper93** [comment]
Please upload minidump form `%LOCALAPPDATA%\CrashDumps`.

**Comment by NatsuDzn** [comment]
> Please upload minidump from `%LOCALAPPDATA%\CrashDumps`.

[mpv.exe.19280.dmp](https://drive.google.com/file/d/1MKqt9DgLp-AYf0XnKHev8uFIEaFYANAn/view)

**Comment by kasper93** [comment]
> [mpv.exe.19280.dmp](https://drive.google.com/file/d/1MKqt9DgLp-AYf0XnKHev8uFIEaFYANAn/view)

It is crashing in OBS vulkan layer. Update/uninstall OBS.

**Comment by NatsuDzn** [comment]
> > [mpv.exe.19280.dmp](https://drive.google.com/file/d/1MKqt9DgLp-AYf0XnKHev8uFIEaFYANAn/view)
> 
> It is crashing in OBS vulkan layer. Update/uninstall OBS.

It's weird because I don't have OBS installed on my computer, installing it fixed it but after the reboot it doesn't work anymore even with obs installed

[dump with obs installed](https://drive.google.com/file/d/1MmAEoP-q3yy8p9X8CwJx2lLbtBx7G1CA/view?usp=sharing)

**Comment by kasper93** [comment]
> It's weird because I don't have OBS installed on my computer

Yes. I had the same, OBS leftover layers installed. At least some time ago it did. And since those are added to implicit layers, they are loaded always to any Vulkan application. Anyway not important how you got them :)

> installing it fixed it but after a reboot it doesn't work anymore even with obs installed

Ok, I see. Let's make a step back and figure out what we can do.

If you don't use OBS, uninstall it and make sure their layer is not in log `VK_LAYER_OBS_HOOK`. No need to add unneeded layers to the mix.

it crashes in `RTSSVkLayer64` now, so we are back to the same issue as others had. Question is why it doesn't work for you after updating. 

Just for sanity could you reinstall latest version? I see in dump
```
Image name: RTSSVkLayer64.dll
Timestamp:  Tue Mar 14 16:57:59 2023 (64109987)
```
while the latest that I just downloaded is from Mar 30 2023.

After that if it still crashes, you can try with `DISABLE_RTSS_LAYER` environment variable. Just to validate there are no other issues present.

**Comment by NatsuDzn** [comment]
> If you don't use OBS, uninstall it and make sure their layer is not in log `VK_LAYER_OBS_HOOK`. No need to add unneeded layers to the mix.

I've uninstalled OBS, then `VK_LAYER_OBS_HOOK ` wasn't present in the log file but it wasn't still working

> it crashes in `RTSSVkLayer64` now, so we are back to the same issue as others had. Question is why it doesn't work for you after updating.
> 
> Just for sanity could you reinstall latest version? I see in dump
> 
> ```
> Image name: RTSSVkLayer64.dll
> Timestamp:  Tue Mar 14 16:57:59 2023 (64109987)
> ```
> 
> while the latest that I just downloaded is from Mar 30 2023.

It's weird because when I check the dll file (from the file explorer) the date seems to match yours

> After that if it still crashes, you can try with `DISABLE_RTSS_LAYER` environment variable. Just to validate there are no other issues present.

I've tried it and it works

**Comment by kasper93** [comment]
I came to realization that shinchiro's mpv build is using own Vulkan loader build from the main branch. They frankly shouldn't build every single things and use GPU driver provided loader which is stable.

Crashes were not caused by any mpv or libplacebo change, but Vulkan loader.

Regressed by: https://github.com/KhronosGroup/Vulkan-Loader/commit/4be91725abb01e8004be966203b95a181c06e1a0
Workaround by: https://github.com/KhronosGroup/Vulkan-Loader/commit/23d4caea0d450b94fd96fa380307d755379df5a2

While ultimately this is a bug in RTSS (out of spec call and not checking for nullptr), developer refuses to fix it. Link for posterity: https://forums.guru3d.com/threads/vk_layer_rtss-crashes-on-vkcreateinstance.447674 (you can find more related discussion and links inside)

Current shinchiro's mpv on SF is from 23.04, which has the problematic Vulkan loader linked. You can use newer build which is not affected form: https://github.com/shinchiro/mpv-winbuild-cmake/releases 

Should any similar issue arise in the future you also have mentioned `DISABLE_RTSS_LAYER` environmental variable to exclude RTSS layer.

**Comment by mitzsch** [comment]
Just want to add another Vulkan-related error... On my end, mpv with Vulkan would just show a white screen for a second and then would crash. Thanks to the tip with the crashdump (didn´t know something like that exists..) I could debug it and find the problematic dll. => `Mirillis\Action!\vulkan_x64\MirillisActionVulkanLayer.dll`. With the dll renamed/deleted mpv worked fine again. Interestingly this errors out now, I have used Action! and mpv with Vulkan for years without any problems...

Should I also upload my crashdump?
