### ISSUE TITLE
How to get Lua `mp` module to enable autocompletion in IDE

### ISSUE THREAD

**Issue by Andrew15-5** [mpv-player/mpv#11678]
I was looking for the answer for quite a while. I'm interested in getting my IDE to see what is `mp` Lua module actually looks like to be able to have autocompletion (with API documentation, if available). Because it's not convenient to go to the documentation page just to see what arguments to pass to the function or to see what is the name of the function you keep forgetting about. It is a built-in module, but can I un-"built-in" it, so I can have a file named `mp.lua` which I can import and have my autocompletion?

**Comment by Traneptora** [comment]
Does this help? https://github.com/mpv-player/mpv/blob/master/player/lua/defaults.lua

**Comment by Andrew15-5** [comment]
Well, partially, yes. It does contain some functions that I used in my script, but also some functions are missing, or shown as a property, rather than the function with parameters. For example:

`mp.observe_property()` shows up correctly:
![mp.observe_property](https://github.com/mpv-player/mpv/assets/37143421/5c3fd8c5-deb6-4808-92c1-50bee9a7f170)

`mp.get_property()` shows up like a property:
![mp.get_property](https://github.com/mpv-player/mpv/assets/37143421/4f043e33-4e4d-42ab-af4d-9aebc0e54ca8)

`mp.set_property()` doesn't show up at all:

![mp.set_property](https://github.com/mpv-player/mpv/assets/37143421/1c87d87a-49c4-49e8-8fed-78afbe9913c7)

Quick search in repo showed that there is no definition of `mp.set_property()` in Lua:
https://github.com/search?q=repo%3Ampv-player%2Fmpv+set_property+language%3ALua&type=code&l=Lua

But there is one in C:
https://github.com/mpv-player/mpv/blob/5afc0da5304401d3f7f4d3e27402943b63f6cc71/libmpv/client.h#L1030-L1062
https://github.com/mpv-player/mpv/blob/5afc0da5304401d3f7f4d3e27402943b63f6cc71/player/client.c#L1312-L1338

Do I need to make a composite file somehow?

**Comment by Traneptora** [comment]
Yes, and you might need to add some dummy function stubs as well. I'd imagine there's no other real way to accomplish what you're trying to accomplish.

**Comment by avih** [comment]
The best source of available functions and their prototypes is the [mpv lua docs](https://mpv.io/manual/master/#lua-scripting), and the recommendation is to create your syntax file based on the docs only.

> Does https://github.com/mpv-player/mpv/blob/master/libmpv/client.h have all the methods that `mp` module has?

No. that file is for C clients, not lua.

> Does `mp` module change with new versions, or it stays the same?

Internal functions/properties can change without notice and should not be used by user scripts. Public (documented) functions/properties can change sometimes (mostly adding new things), but not very frequently.

If you insist on extracting all the available things at `mp`, you can save this script as `list-mp.lua`:
```lua
function listobj(o, title, indent)
    indent = indent or ""
    print(indent .. title .. ":")
    indent = indent .. "    "

    for k,v in pairs(o) do
       print(indent .. k .. "  (" .. type(v) .. ")")
       if (type(v) == "table") then
           listobj(v, title .. "." .. k, indent)
       end
    end
end

listobj(mp, "mp")
listobj(require("mp.utils"), "require('mp.utils')")
listobj(require("mp.options"), "require('mp.options')")

mp.command("quit")
```

Then run, from a terminal or a command prompt window:
```sh
mpv --no-config --idle --script=list-mp.lua
```

This will print all the properties of `mp` and the available modules, recursively, together with their types.

For the function prototypes you need to check [defaults.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/defaults.lua) which was mentioned earlier, and also [lua.c](https://github.com/mpv-player/mpv/blob/master/player/lua.c) for lua functions which are defined in C code.

To understand what is the prototype of functions (formal arguments and their types) at the C code, you need to understand how lua-c functions work, and read that C file.

But again, the recommendation is to base your syntax file only on the public docs, so that you don't accidentally use internal functions which are subject to change at any time.

**Comment by Andrew15-5** [comment]
Great! Thank you for the information.
Extracting information from the documentation page with "formatted" text would be easy, I believe. But isn't the https://github.com/mpv-player/mpv/blob/master/DOCS/man/lua.rst file identical to this part of the page: https://mpv.io/manual/master/#lua-scripting?
If so, I can further ease the extraction process by using an even easier source code format (Markdown instead of HTML): https://raw.githubusercontent.com/mpv-player/mpv/master/DOCS/man/lua.rst.

**Comment by avih** [comment]
> isn't the https://github.com/mpv-player/mpv/blob/master/DOCS/man/lua.rst file identical to this part of the page: https://mpv.io/manual/master/#lua-scripting?

They should be identical. The first link is the source file of the lua docs, and the second link is this file formatted as html and embedded inside the whole docs page.

> I can further ease the extraction process by using an even easier source code format (Markdown instead of HTML): https://raw.githubusercontent.com/mpv-player/mpv/master/DOCS/man/lua.rst.

Sure, it should be possible to automate the extraction from the markdown file, with some work.

**Comment by Andrew15-5** [comment]
Automation is my second name! I simply cannot live without it (I'm serious, I use it a lot every day). And it probably will work with newer versions of mpv Lua API right away. That way I won't have to track down what has changed at what hasn't. Plus, I will try to get the doc for the currently installed version of Lua to keep my `mp.lua` in sync with my `mpv` program.

Good, now I need some free time and I will try to make the stub `mp.lua` file.

**Comment by avih** [comment]
> Good, now I need some free time and I will try to make the stub `mp.lua` file.

Sure.

I'm closing this issue for now, but I suggest that you post your syntax file and/or automation script with instructions here once you get it working, so that others can benefit too.

**Comment by Andrew15-5** [comment]
Sure thing.

**Comment by abdallahmehiz** [comment]
uhhh, any updates?

**Comment by Andrew15-5** [comment]
Sorry, I'm really busy. I hope to have a spare time in the future.
