### ISSUE TITLE
libpython3.10.so.1.0 not found

### ISSUE THREAD

**Issue by HxxThSwggr** [mpv-player/mpv#11670]
### Important Information

Provide following Information:
- mpv version: **mpv-git 0.35.0_378_ga1580b6424-1**
- Linux Distribution and Version: **Arch**, linux-zen kernel
- Source of the mpv binary: Built on my pc ([AUR](https://aur.archlinux.org/packages/mpv-git))
- If known which version of mpv introduced the problem: -
- Window Manager and version: **KWin** version: 5.27.4
- GPU driver and version: **mesa 23.0.3-1**
- Possible screenshot or video of visual glitches: -

### Reproduction steps

Try to start mpv with any command on python 3.11
Downgrading to 3.10.11 makes it work.
Maybe I'm just stupid and messed up the python upgrade but everything else works ok.

### Expected behavior

Any mpv command works.

### Actual behavior

```
[HexxTheSwagger@OPC-Arch ~]$ mpv --version
mpv: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
[HexxTheSwagger@OPC-Arch ~]$ mpv -v -v
mpv: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
[HexxTheSwagger@OPC-Arch ~]$ 

```
Mpv can't find libpython3.10.so.1.0.
I have updated python to 3.11 so it most likely doesn't exist but why does mpv want an old 3.10 one?

### Log file

Can't.

**Comment by sfan5** [comment]
When you install mpv from the AUR it is your responsibility to rebuild the package when a dependency has a soname bump.

**Comment by CounterPillow** [comment]
Just to elaborate on sfan5's comment with an explanation:

When libraries update their ABI (Application Binary Interface), they usually will (or rather, should) do a "soname bump". This means the updated library is called something else. This ensures nothing built against the old ABI accidentally loads the updated library with its newer ABI at runtime, which would otherwise have catastrophic consequences (application crashes, data corruption, etc.)

Applications need to be recompiled to be compatible with the new ABI. When you use packages from the Arch Linux repositories, this will be done for you by the maintainers. However, when you compile things from e.g. the AUR yourself, it is your responsibility that this is being done. This isn't a thing upstream mpv or anyone else can help you with; you yourself built this binary, and you yourself need to rebuild it.

A simple recompile of the mpv-git package here will fix your problem.

**Comment by HxxThSwggr** [comment]
Thanks, I didn't know that and I was kinda suspecting I had done something wrong myself, but I was actually using the standard (non-AUR) mpv package before I tried to build master and switched because I though it might fix the issue.

But thanks to your info I searched internet and it really looks like it's not related to mpv, so I am sorry for bloating the issue forum.
