### ISSUE TITLE
Allow different decoding and rendering devices to be specified for d3d11 and vulkan

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#11738]

**Comment by philipl** [comment]
It's not impossible, but it's a pain. You have to initialise a vulkan context on each device (and when you use `vulkan-copy`, you do get two contexts, but mpv doesn't expose a way to control which device the `vulkan-copy` context is from) and then you need a dedicated interop codepath that does external export/import of frames between the contexts with a bunch of synchronisation machinery. Can it work? Absolutely - we have the raw building blocks on both the ffmpeg and mpv sides but it's a bunch of tedious code.

It's also not clear what you really win. As I understand it, the general case for Vulkan interop between different GPUs, and especially for different vendors, requires lowest common denominator memory layout and might even require allocation in host memory anyway - which is effectively a glorified host memory copy such as what already happens with `vulkan-copy`. It would be interesting experiment to run, but you'd have to write all that miserable code to test it.

**Comment by philipl** [comment]
(And yes, there's a D3D (maybe only 12) equivalent exercise you can go through)

**Comment by philipl** [comment]
Your CLI example is doing simple host download and then upload, which is exactly the same as what `vulkan-copy` would do if you could control the vulkan devices independently.

My point was that you have to make careful choices about which type of memory allocation to use and which layout (almost certainly must always be linear) for the images to allow the export and import to succeed, and if you satisfy those constraints, is the resulting flow actually any more efficient than copying through system memory? The Vulkan driver is allowed to copy when doing exports and imports and I'd expect it would in these situations.

I've done some brief experiments with VAAPI on Intel exporting to Vulkan on nvidia for display and did not find a compatible configuration, so I would expect the Vulkan -> Vulkan experience to be similar. I know that _something_ exists because it's how nvidia's Prime display offload stuff works (sharing a dmabuf across devices), but it's not documented past however the offload code paths are implemented, which I've never tried to read.
