### ISSUE TITLE
Keybindings work only with a specific locale

### ISSUE THREAD

**Issue by ilihh** [mpv-player/mpv#11758]
### Important Information

mpv version: 0.35.0-407-g959ef843
Windows 10 Pro 22H2 19045.2965
Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/?path=/64bit

### Reproduction steps

1. Install any non-latin keyboard locale: Japanese, Korean, Arabic, etc.
2. input.conf: add keybinding "p cycle pause"
3. change the keyboard locale to the installed non-latin one
4. run mpv
5. press "p" and nothing happens
6. run mpv with "--input-test" and non-latin locale
7. press "p" and will be displayed "Key [non-latin character on p key] is bound to: (nothing)"

### Expected behavior

Keybindings should work with any locale.
Hotkey should be bound to the physical key on the keyboard, not to the character generated by pressing the key.

### Actual behavior

Keybindings work only when using the same locale as the specified characters in the input.conf

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/11644167/output.txt)

**Comment by CounterPillow** [comment]
>  Hotkey should be bound to the physical key on the keyboard, not to the character generated by pressing the key.

disagree, having y be z for me would be insanely confusing

**Comment by N-R-K** [comment]
> Hotkey should be bound to the physical key on the keyboard, not to the character generated by pressing the key.

I'm not aware of any application that works like this (at least not by default). Closest thing I can recall is the [dwm-keycode](https://dwm.suckless.org/patches/keycodes/) patch that modifies dwm to use X11 keycodes instead of keysyms.

**Comment by avih** [comment]
> Hotkey should be bound to the physical key on the keyboard, not to the character generated by pressing the key.

Well, mpv is designed to invoke the command which is bound to the text which the key produces. If you change locale and as a result a key produces different text, then it will no longer invoke the command which is bound to the previous text it produced.

That is by design, and is unlikely to change. See https://mpv.io/manual/master/#key-names

Note that some names are symbolic and should work in any locale, like `LEFT` or `TAB` etc.

So you have few options:
1. Ensure that the locale is English while invoking mpv key bindings.
2. Bind your own in any locale you want, to replicate the default bindings you care about. The default bindings are defined here https://github.com/mpv-player/mpv/blob/master/etc/input.conf
3. If you feel adventurous, write an mpv lua/js script which translates key presses in some locale to English. You'd need to bind the `UNMAPPED` key symbol (which captures all unbound keys/combos), interpret the key name as text and possibly modifiers, map the text to English, re-compose a key string in English, and use the `keypress` command to generate the mapped key.

**Comment by ilihh** [comment]
@N-R-K 
> I'm not aware of any application that works like this (at least not by default). Closest thing I can recall is the [dwm-keycode](https://dwm.suckless.org/patches/keycodes/) patch that modifies dwm to use X11 keycodes instead of keysyms.

Cannot say about *nix soft, but in Windows hotkeys are locale independent.
For example, both Ctrl+p and Ctrl+せ will open a print dialog in the browser, because it is the same physical keys.

@avih 
Ok, then the issue can be closed.

**Comment by garoto** [comment]
Old and busy related issue (most interesting discussion happens around the 2016 time frame imo): https://github.com/mpv-player/mpv/issues/351
