### ISSUE TITLE
please Implement hwdec priority fallback

### ISSUE THREAD

**Issue by StacktraceException** [mpv-player/mpv#11797]
Depending on dedicated GPU being used in OS or lower performance integrated GPU instead, the setting needs to change.

Something like hwdec=nvdec/nvdec-copy/cuda/cuda-copy/d3d11va/d3d11va-copy would be really helpful.

Thanks, regards.

**Comment by sfan5** [comment]
Which usecase would this satisfy that `hwdec=auto-safe` or `auto-cop-y-safe` doesn't?

**Comment by philipl** [comment]
The use-case I have been thinking of implementing is being able to dynamically fallback if the chosen hwdec doesn't support the video format. So that you can prefer `vulkan` but fall back to `nvdec/d3d11va` for the unsupported formats - which is most of them. I don't know if that's what @StacktraceException was imagining. 

If you just care about detection, then yes, `auto` should be good enough.

**Comment by StacktraceException** [comment]
> Which usecase would this satisfy that `hwdec=auto-safe` or `auto-copy-safe` doesn't?

the  "auto-safe" is automatic or random, is it not? nvdec is more preferrable than cuda for example.  The priority list is much more specific with its order than some random or stock/default preprogrammed choice order, which often may offer less fps performance than user's tested choices. This is even more important when wanting to use most demanding/advanced post processing profiles (like for each kind of resolution etc).



(Also in case auto-safe does not work then someone may want auto-copy-safe at least (if this isn't covered by just the "auto" option), but the manual does not make this clear…
