### ISSUE TITLE
MPV cannot be opened

### ISSUE THREAD

**Issue by CNhjx** [mpv-player/mpv#11828]
### Important Information

Provide following Information:
- mpv version: mpv 0.35.0-445-g650c53df
- Windows Version: Windows 10 x64
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/
- If known which version of mpv introduced the problem: mpv 0.35.0-445-g650c53df
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

After updating the software today, MPV cannot be opened when mpvSockets LUA script is enabled. The previous version of MPV can run normally when using this script.

### Expected behavior
MPV can run normally.
### Actual behavior
MPV cannot be opened
### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/11856581/mpv.log)

### Sample files
[mpvSockets.lua.txt](https://github.com/mpv-player/mpv/files/11856584/mpvSockets.lua.txt)

**Comment by Traneptora** [comment]
What do you mean it "can't be opened." What happens when you try?

**Comment by kasper93** [comment]
Use build form https://github.com/zhongfly/mpv-winbuild/releases. Note exact version you are using and upload minidump from `%LOCALAPPDATA%\CrashDumps`.

**Comment by CNhjx** [comment]
> 

Double-click the application icon, no player window pops up, only the cursor turns into a small circle

**Comment by CNhjx** [comment]
> 

 mpv-x86_64-v3-20230625-git-78285e9.7z
[mpv.exe.7540.dmp.txt](https://github.com/mpv-player/mpv/files/11861378/mpv.exe.7540.dmp.txt)

**Comment by CNhjx** [comment]
> 

mpv-x86_64-v3-20230625-git-945d7c1
[mpv.exe.11136.dmp.txt](https://github.com/mpv-player/mpv/files/11861388/mpv.exe.11136.dmp.txt)

**Comment by kasper93** [comment]
Nice, we have destroyed stack. 

This is a bug in mingw-w64, they define L_tmpnam as
`#define L_tmpnam (sizeof(_P_tmpdir) + 12)`
https://github.com/mirror/mingw-w64/blob/eff726c461e09f35eeaed125a3570fa5f807f02b/mingw-w64-headers/crt/stdio.h#L59

Which is then used by LUA as buffer size
`char buf[L_tmpnam];`
https://github.com/LuaJIT/LuaJIT/blob/ff6c496ba1b51ed360065cbc5259f62becd70daa/src/lib_os.c#L93

But this is not correct because UCRT version of `tmpnam()` returns absolute path and the `L_tmpnam` should be defined to `MAX_PATH` at the very least. `stdio.h` from Windows SDK does this:
`#define L_tmpnam   260 // _MAX_PATH`

So there is stack overflow, which was actually reported two years ago https://sourceforge.net/p/mingw-w64/bugs/915/ but as we can see nothing has be changed since then.

And actually it has been already discussed here too... https://github.com/mpv-player/mpv/issues/9644

I will send mingw-w64 a patch for that later, because it is kinda bad to destory stack like that. I'm getting closer to porting everything to Windows SDK clang build with every issue like that.

**Comment by Dudemanguy** [comment]
Allegedly should be fixed.
