### ISSUE TITLE
BUG: mouse scroll wheel sensitivity is too low/slow/laggy: WHEEL_DOWN WHEEL_UP WHEEL_LEFT WHEEL_RIGHT are ignored for 200ms

### ISSUE THREAD

**Issue by allanlaal** [mpv-player/mpv#11851]
by fixing #4613 in the PR https://github.com/mpv-player/mpv/commit/937128697fbbef6b21e2d23a4785f1334f62b9e3 it introduced a deadzone "feature", where the mouse scroll events are ignored for a `isn't noticeable on my slow machine` duration and `fixes my shitty trackpad` distance:
https://github.com/mpv-player/mpv/blob/68f1057d2ef3c24bf2d0dcd37d877e21e2879a65/input/input.c#L651
https://github.com/mpv-player/mpv/blob/68f1057d2ef3c24bf2d0dcd37d877e21e2879a65/input/input.c#L654

the scroll wheel needs over 200ms to register the scroll, thus making mouse seeking very very tedious and seemingly laggy. this is by design from that PR and affects:
 * WHEEL_DOWN   
 * WHEEL_UP
 * WHEEL_LEFT
 * WHEEL_RIGHT

# expected

no input dead zones. they should default to 0 and be user configurable. 200ms is not a sane value as it is considered the threshold of average human cognition for an event in UX.

# affected

current [master](https://github.com/mpv-player/mpv/blob/68f1057d2ef3c24bf2d0dcd37d877e21e2879a65)

**Comment by allanlaal** [comment]
maybe related: #5092

**Comment by allanlaal** [comment]
@philipl is the issue template tag gonna interfere with my PR? :o

**Comment by rossy** [comment]
> the scroll wheel needs over 200ms to register the scroll, thus making mouse seeking very very tedious and seemingly laggy

That's not what this code does. Scroll events are handled as soon as the scroll breaks out of the 0.125 unit dead zone, which is instantly for mice with discrete scroll wheels. The 200ms timer affects the minimum speed you can scroll - if you scroll slower than 0.125 units per 200ms, you'll never break out of the dead zone. It also affects how quickly you can switch between axes - if you send a WHEEL_UP/DOWN, you have to wait 200ms before sending a WHEEL_LEFT/RIGHT. There is no limit to how quickly you can send scroll events on a single axis, however.

If you're only noticing lag when you _start_ scrolling, that can only be because of the dead zone size (the 0.125 unit thing) not the timer, and that only affects touchpads and continuous scroll wheels with scaled commands. If you use a discrete scroll wheel or you bind a non-scalable command, and you're not quickly switching between scroll axes, the dead zone won't delay your input.

> no input dead zones. they should default to 0

That isn't the right priority. A lot of people have "shitty" touchpads (they aren't easily replaced) but not many people need to trigger input bindings at 300 APM on opposing scroll axes. If there really is a problem, the solution shouldn't remove touchpad filtering.

>is the issue template tag gonna interfere with my PR? :o

It will only affect this issue. Not following [contribute.md][1] will affect your PR.

The issue template is handy for a lot of reasons. In this case, it would tell us your OS, which affects how scroll input works. For example, macOS seems to do its own filtering of touchpad scroll events, so it might make sense for us to disable ours there. It also might make sense for us to reset the dead zone when we get a discrete scroll event, but it doesn't seem possible to differentiate between discrete and continuous scrolling in Windows.

Though it's not in the issue template, it would also be handy to know what kind of device you're scrolling with (touchpad, mouse with discrete wheel, [mouse with touch wheel][2], etc.) and what input commands you have bound to each WHEEL_* event.

> by fixing #4613

FWIW, this issue turned out to be unrelated, because the user had a mouse with a discrete wheel (see [comment][3].)

The touchpad filtering was originally done in 937128697fbb as a part of a PR that added support for continuous scrolling in Windows (#4366,) because I noticed that macOS seemed to have some filtering for scroll events and one of the Windows laptops I tested on at the time did not. mpv's default bindings use vertical scrolling for seeking and horizontal scrolling for volume, so it's very annoying to accidentally seek while changing the volume because your fingers deviated by a fraction of a scroll unit.

[1]: https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md
[2]: https://www.microsoft.com/en-au/d/surface-arc-mouse/8mrmszc6vxkc
[3]: https://github.com/mpv-player/mpv/issues/4613#issuecomment-315863877

**Comment by fuggla** [comment]
Hi, I'm having issues related to this topic. Followed the issues template, info below:

### Important Information

- mpv version

```
mpv --version
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
FFmpeg version: 6.0
```

- Linux Distribution and Version

```
Operating System: Fedora Linux 38 (Thirty Eight)    
Kernel: Linux 6.5.8-200.fc38.x86_64
```

- Source of the mpv binary

```
Fedora 38 repos
Name         : mpv
Version      : 0.35.1
Release      : 4.fc38
Architecture : x86_64
Size         : 4.5 M
Source       : mpv-0.35.1-4.fc38.src.rpm
Repository   : @System
From repo    : fedora
```

- If known which version of mpv introduced the problem

The version above. Unfortunately I don't know which version was installed previously.

- Window Manager and version

i3 version 4.22

- GPU driver and version

```
sudo lshw -c video
  *-display                 
       description: VGA compatible controller
       product: GP104 [GeForce GTX 1070]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: /dev/fb0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=nouveau latency=0 resolution=2560,1440
       resources: irq:129 memory:b2000000-b2ffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:4000(size=128) memory:c0000-dffff
```

- Possible screenshot or video of visual glitches

No visual glitches, playback perfect.

- If you're not using git master or the latest release, update.

Using the latest release available in Fedora 38. I'm not sure how to use the master branch.

### Reproduction steps

Open a mp4 video and scroll.

### Expected behavior

Responsive scroll behavior.

### Actual behavior

Significantly less responsive than in the previous version.

### Log file

http://0x0.st/HtUb.log

1. Started playback
2. Scroll in speed that used to work the first 10 seconds. No effect.
3. Scrolled faster. Effect.

**Comment by allanlaal** [comment]
reopen, this is an active issue.
mpv contains code that makes mouse scroll laggy on purpose (because of some edge cases)

**Comment by allanlaal** [comment]
it is not the job of a media player to fix a laptops mouse drift. 

that is exactly what [mousetweaks](https://wiki.gnome.org/Projects/Mousetweaks) is for.
mouse drift always affects the entire system, not just the media player

**Comment by llyyr** [comment]
> reopen, this is an active issue.

Not only did you fail to follow the issue template, but also haven't responded to https://github.com/mpv-player/mpv/issues/11851#issuecomment-1612916999 yet. In particular:

> Scroll events are handled as soon as the scroll breaks out of the 0.125 unit dead zone, which is instantly for mice with discrete scroll wheels.

**Comment by fuggla** [comment]
I have for unrelated reasons replaced the disk in my computer and installed Fedora 39 with the same dotfiles/software, including MPV. I'm not experiencing any scroll problems and have been unable to reproduce with or without **--no-config**.
