### ISSUE TITLE
Default subtitle tracks without a language tag do not get selected

### ISSUE THREAD

**Issue by po5** [mpv-player/mpv#11854]
### Important Information

Provide following Information:
- mpv version: commit a61b784d90148bcd0e8e9c366dcc563c81c74026
- Platform and Version: EndeavourOS Linux x86_64
- Source of the mpv binary: mpv-full-git AUR package

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

- Download this sample file https://0x0.st/HQlI.mkv
- Play it with `mpv --no-config HQlI.mkv`

### Expected behavior

The default subtitle track is selected.

### Actual behavior

The default subtitle track doesn't get selected, with either of `--subs-with-matching-audio=yes`, `--subs-with-matching-audio=no`.  
No `--slang` setting is able to select this track. This is highly underisable.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/11905812/log.txt)

**Comment by hooke007** [comment]
`--subs-fallback=yes`

**Comment by po5** [comment]
Seems `--subs-fallback=default --subs-with-matching-audio=yes` works, is this the same as the old behavior?  
Defaults should be updated, this is what people expect.

**Comment by hooke007** [comment]
Agree, the new behav is terrible.

**Comment by Vernoxvernax** [comment]
I've been relying on the default settings for as long as I can remember because they offered a reliable experience across all devices. That's why I'm feeling a bit puzzled about the recent change that's going to impact almost everyone who play files with subtitles.
What makes it even more confusing, are the default track flags. Audio tracks with the default flag turned on, will be selected by default, but subtitles with the same property, not??

**Comment by Hawaka743** [comment]
I don't like these changes either. Since I'm Hungarian I have the system language set to Hungarian. In practice this currently means that no subtitles get auto selected, unless there happens to be a Hungarian subtitle in the video.Except I don't want to use Hungarian subtitles even when they are available. I prefer to just use English subtitles, unless the audio is in a language that I understand better then English (there are 3 such languages and non of them are common).

Honestly, the previous behavior was better. It was more predictable, if a subtitle was set to default in the video file it would get selected. Exactly the way everyone expected it.

**Comment by mxsrm** [comment]
New configuration options should not change the default behaviour of something as basic as subtitles loading so dramatically...
