### ISSUE TITLE
Slow buffering (much slower than line speed) over network (sftp/http) using local share causing stuttering playback

### ISSUE THREAD

**Issue by tokyovigilante** [mpv-player/mpv#11931]
### Important Information

MPV: master @828dd65 / libplacebo @9855b66 / ffmpeg @374184a4 (all current)
Linux: Fedora rawhide / Sway master
GPU: Mesa 23.2.0 from xxmitsu copr (0.3.20230705.00.59cf370.fc39)

### Reproduction steps

Play any video, initial network buffers a few MB but then cache refills at less than playback speed and slowly dwindles to 0. More noticeable at high-bitrates but happens with all videos. Reproducible with `--no-config`. Occurs on wired desktop (gigabit) and laptop using Wifi. Affects both sftp and http.

### Expected behavior

Smooth playback. Network share can sustain 100MB/sec read with wired connection.
```
rsync -avE --progress "*@*:/*/Media/Film/The Matrix/The Matrix (1999).mkv" .
receiving incremental file list
The Matrix (1999).mkv
    434,143,232   1%  103.59MB/s    0:05:51
```

### Actual behavior

Constant pausing after a few seconds of playback while buffer refills then re-empties.

Have tried some limited reversions to earlier versions of MPV and ffmpeg, but no luck going back as far as 2022 so may be a platform or libssh regression, but does not happen with ffplay with same sftp url:

```
ffplay "sftp://*@*:/*/Media/Film/The Matrix/The Matrix (1999).mkv"
ffplay version N-111432-g374184a4dc Copyright (c) 2003-2023 the FFmpeg developers
  built with gcc 13 (GCC)
  configuration: --enable-openssl --enable-libssh --disable-static --enable-shared --enable-vulkan --enable-libfdk-aac --enable-libmp3lame
...
 2.68 A-V:  0.021 fd=   4 aq= 2657KB vq=12694KB sq=    0B f=0/0
```
Cache size remains steady and playback continues.

### Log file

https://0x0.st/Hjj4.txt

**Comment by jebaum** [comment]
I'm seeing this issue as well, both with files stored on a NAS on my local network and some youtube videos (simply invoked via `mpv https://youtube.com?blahblah`)

Same as in your case, my network speeds both locally to the NAS and to youtube are much faster than what mpv is using. Using mplayer or vlc on the local videos works perfectly as far as stuttering and speed goes.

The issue is more obvious on larger files with higher bitrates. I haven't changed anything in my config, and can reproduce with `--no-config`. It does seem like there was some kind of regression related to network buffering.

**Comment by borqq** [comment]
I have the same issue with 0.36.0. Buffering looks fine at first, then stops pretty much stops working after a while - both on LAN and local drive

**Comment by whitecodes** [comment]
I have the same issue.I try every option in mpv.conf. When set cache-on-disk=yes ,the issue is disappear

**Comment by jebaum** [comment]
@whitecodes that worked for me too. setting `cache-on-disk=yes` along with `cache=yes` seems to solve the stuttering issues. playing video files from my NAS, I can see my network speed getting nearly saturated when starting up a video, and then staying at a much higher rate while watching.

I don't really understand why, especially because when setting `cache-dir` to `$HOME/.cache/mpv`, I can see that the folder gets created, but there's no files in it.

**Comment by jebaum** [comment]
This issue definitely seems related to https://github.com/mpv-player/mpv/issues/12076

Using one of the fixes from that discussion thread to play a video from my NAS over the local network, e.g. `LD_PRELOAD=`jemalloc-config --libdir`/libjemalloc.so.`jemalloc-config --revision` mpv --no-config /nas/some-big-video-file.mkv`, I can see the cache getting rapidly populated up to 15s, and network speeds being fully saturated while that rapidly happens.

**Comment by tokyovigilante** [comment]
Agree this is definitely related to the glibc malloc bug as per #12076 at least on my system, Fedora rawhide has now updated to a glibc 2.38 with the fix and the bug is no longer reproducible (network playback caching back to normal) so closing this. Thanks!
