### ISSUE TITLE
gpu-next: bt.2020-ncl HDR AVIF screenshot colormatrix not as expected (screenshot-sw=no)

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#11965]

**Comment by haasn** [comment]
So, after looking at the code a bit I'm pretty sure the problem here is that screenshots are taken in RGB space, and the internal conversion to YUV that happens inside `image_writer` relies on `mp_image_params_guess_csp` to choose the appropriate colormatrix.

In this case, that means it actually ends up picking the colormatrix to encode as based on the *size* of the screenshot. If my theory is correct, a SD (e.g. 640x480) HDR video would actually get saved in *bt.601* format.

One thing to point out is that, while strange, this should not actually affect the validity of the resulting AVIF - the choice of colormatrix is essentially arbitrary, the actual screenshot is being saved in RGB after all. I think that the proper resolution here is to replace the call to `mp_image_params_guess_csp` by a dedicated function to *choose* a good colorspace for the screenshot.
