### ISSUE TITLE
change default screenshot key

### ISSUE THREAD

**Issue by pirate486743186** [mpv-player/mpv#12014]
I keep taking screenshots by accident. It should be 2 keys to avoid this.
I propose you use "shift+s" or "ctrl+s" as the default keys.

**Comment by CounterPillow** [comment]
skill issue, rebind it for yourself in input.conf if it's a problem for you, but your sausage fingers don't speak for everyone's experience.

**Comment by CounterPillow** [comment]
Why shouldn't it? Why make it less convenient to use the player by default just because of your own personal experience?

**Comment by N-R-K** [comment]
> Why make it less convenient to use the player by default

Pressing an extra modifier isn't as bad as having to go delete an unwanted file.

And most software seems to have multi-key bind (or something not easily press-able like `printscreen`) for screenshots. The default for windows for example is `win+shift+s` and on vlc it seems to be `shift+s`. And even in my own config I have it rebound to `ctrl+s` due to the same reason.

I'd support changing the default to `ctrl+s` or `shift+s` because, as mentioned above, an extra modifier press is much more convenient than finding and deleting file.

**Comment by llyyr** [comment]
I'd argue that having to reopen the video player if you accidentally pressed q is far more annoying, but nobody has ever complained about these things because it's only a problem for very small minority of people that can just rebind the keys in their input.conf instead. Changing defaults would affect far more people that have never once in their life taken a screenshot by accident or closed mpv by accident

**Comment by Dudemanguy** [comment]
`shift+s` obviously is out of the question since that's the default for _another_ screenshot-related option. I think it's fine the way it is.
