### ISSUE TITLE
OSC seems to have a race condition when loading `osc.lua`

### ISSUE THREAD

**Issue by xphoniex** [mpv-player/mpv#12142]
### Important Information

mpv version: `mpv 0.34.1`, cherry-picked https://github.com/mpv-player/mpv/commit/dfbdf7516586427083a868307a77c35bab8bc764
Linux Distribution and Version: `Ubuntu 22.04`
Source of the mpv binary: `sudo apt-get install mpv`

### Reproduction steps

This is a random bug, and not consistently reproducible.

Open a video file, and as fast as you can, press `]` many times.

Also:

```console
$ cat .config/mpv/mpv.conf
sub-font="Proxima Soft"
sub-font-size=36

hr-seek=yes
no-osc=true
script=~/.config/mpv/osc.lua
script-opts=osc-remaining_playtime=no
```

### Expected behavior

- Playback speed to increase

### Actual behavior

- Playback speed indeed increases

but sometimes (10% - 20% of time):

- I can no longer seek to a position by clicking on the timeline (but right/left arrow works)
and / or
- behavior (https://github.com/mpv-player/mpv/commit/dfbdf7516586427083a868307a77c35bab8bc764) set in `osc.lua` using `script=~/.config/mpv/osc.lua` is not loaded/respected

### Log file

Attached two logs, one with the working run, and another with the buggy run.

[working_log.txt](https://github.com/mpv-player/mpv/files/12324203/working_log.txt)
[bug_log.txt](https://github.com/mpv-player/mpv/files/12324204/bug_log.txt)

--

@avih please take a look.

**Comment by Dudemanguy** [comment]
Can you reproduce this on master? 0.34 is way too old.

**Comment by avih** [comment]
Other than first confirming with new mpv, the osc code is indeed very delicate and races can definitely exist (and some have been fixed too), but none that we know of under reasonably regular usage.

Fixing such issues, while not impossible, can be hard due to the complexity of the osc code.

If this becomes an issue and we can reproduce it with latest mpv, then maybe someone can look into this.

Otherwise, I don't know if it's worth the time to pinpoint it. But if someone can pinpoint the source of the issue, it would be a good start.

**Comment by hooke007** [comment]
> `no-osc=true`

Are you sure it work? It would never disable built-in osc (On Windows)

**Comment by po5** [comment]
You're using a custom osc forked from the official osc without `osc=no` in mpv.conf.  
The problem lies in your forked osc's input sections conflicting with defaults, see https://github.com/po5/thumbfast/issues/80#issuecomment-1527643412.  
Either set osc=no or make changes similar to this https://github.com/po5/thumbfast/commit/9eef52f810a4474b98423ad14af02f2f1e590469.

**Comment by Dudemanguy** [comment]
Evidently an obscure configuration problem.

**Comment by xphoniex** [comment]
`osc=no` seems to have fixed the issue! 

Thank you all.
