### ISSUE TITLE
hwdec : spam msg in console

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#12173]
### Important Information

Provide following Information:
- mpv version
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230814
- Windows Version
win10 22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230814
- If known which version of mpv introduced the problem
N/a
- Possible screenshot or video of visual glitches
![2023-08-15 015817](https://github.com/mpv-player/mpv/assets/41094733/a6abe027-b0dc-4256-b540-7f2a7e4e1179)

### Reproduction steps

1. mpv --hwdec=auto
2. load some video

### Expected behavior

No error msg

### Actual behavior

See the screenshot

### Log file

[test.log](https://github.com/mpv-player/mpv/files/12340456/test.log)

### Sample files

https://github.com/mpv-player/mpv/assets/41094733/835e5e52-7b7b-4dca-8b56-f4b3ffcbbbf6

**Comment by philipl** [comment]
It's not ideal, but it's what happens when you use `auto` with a file that cannot be decoded by any hardware (Hi10P h.264 in this case). It will try all the different hwdecs down the list and some of them spam errors from inside ffmpeg where we aren't easily able to indicate that we're probing for hwdecs and to lower the log level.

The simplest solution is to set `hwdec` to what you actually care about - presumably you just need `d3d11va`, but you can set it a comma delimited list of values if you're actually in a situation where you want to try more than one.
