### ISSUE TITLE
gpu-next: If dscale is switched repeatedly, the peak detection brightness will either continuously increase or continuously decrease.

### ISSUE THREAD

**Issue by arm64-v9a** [mpv-player/mpv#12188]
### Important Information

Provide following Information:
- mpv version master
- Windows Version 23H2
- Source of the mpv binary [mpv-winbuild](https://github.com/zhongfly/mpv-winbuild/suites/15186795730/artifacts/867907072)
- If known which version of mpv introduced the problem N/A
- Possible screenshot or video of visual glitches
  
![image](https://github.com/mpv-player/mpv/assets/58792941/2df26293-34d4-4e80-95c5-d1c0d53aef1d)

### Reproduction steps

```
mpv --no-config --vo=gpu-next --dscale=mitchell --hdr-compute-peak=yes --target-peak=203
script-binding display-stats-toggle 
script-binding stats/display-page-2     
set dscale bicubic
set dscale mitchell
set dscale bicubic
set dscale mitchell
set dscale bicubic
set dscale mitchell
set dscale bicubic
set dscale mitchell
.......
```
### Expected behavior
Peak detection brightness should be kept within a fixed range
### Actual behavior
Peak detection brightness increases or decreases with changing dscale.
### Log file
[log.txt](https://github.com/mpv-player/mpv/files/12370012/log.txt)

### Sample files
https://github.com/arm64-v9a/temp/releases/download/HDR/HDRTEST.webm

**Comment by haasn** [comment]
This is actually an expected result. Keep in mind that there are three different factors at play here:

1. After https://github.com/haasn/libplacebo/commit/fcf81635df58489f33e2d8521f56eb876dbf666e, peak detection happens after downscaling, so downscaling with a different scaler will change the detected peak values.
2. The default values of `hdr-peak-decay-rate` will put a low-pass filter on the detected peak values. Because of how it's implemented internally, there's no real way for this filter to distinguish between separate input frames and re-draws of the same frame. So while the image is paused, if you do something (e.g. changing a setting) that forces a re-draw, it will essentially advance the low pass filter state by 1 frame, eventually converging on the 'true' peak value.
3. The `hdr-scene-threshold-low` may also be kicking in and muddling things up further, in particular if the peak suddenly changes as a result of the downscaler being significantly different (such as may be the case when you're testing with `--no-correct-downscaling`, as in your reproduction steps)
4. On top of all this, the default value of `--allow-delayed-peak-detect=yes` will mean that all measured peak values are actually delayed by one frame on top of all of the above considerations.

To isolate these factors, you should test with `--hdr-scene-threshold-high=0 --hdr-peak-decay-rate=1 --allow-delayed-peak-detect=no`.

And actually, doing that made me realize that even at `--hdr-peak-decay-rate=1`, there is some smoothing going on - the IIR coefficient seems to be miscalculated slightly. Let me investigate further.

**Comment by haasn** [comment]
@arm64-v9a if you test with https://github.com/mpv-player/mpv/pull/12194 you can set `--hdr-peak-decay-rate=0` thus completely disabling the smoothing logic.

If I do that locally, then I always get consistent results - the same `dscale` setting gives me the same detected peak, no matter what. (Testing on a paused frame)

And if I also set `--correct-downscaling=yes`, I get the basically the same peak value from any non-ringing filter.
