### ISSUE TITLE
how to use upscalers like FSRCNNX/ravu-zoom at native resolution?

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12245]
Hi,
I want to ask how to trigger these shaders (FSRCNNX/ravu-zoom). My source is 1080p and my TV is 1080p but I still want to up and downscale to improve the image quality. But they seem to kick in only when the source is like 720p.

**Comment by Traneptora** [comment]
Why would you want to do that? Upscaling and then downscaling does not improve quality.

**Comment by geextahslex** [comment]
It does. Watch 1080p and then 4K on 1080p. Night and day difference

**Comment by Traneptora** [comment]
I think you're confusing the fact that YouTube and other sites throw extra bitrate at videos uploaded in 4k. If you upscale a native 1080p video to 4k and then downscale it you haven't accomplished anything.

**Comment by christoph-heinrich** [comment]
The shader has a line that checks when the shader should run.
Here is what it looks like in FSRCNNX:
```
//!WHEN OUTPUT.w LUMA.w / 1.300 > OUTPUT.h LUMA.h / 1.300 > *
```
It's written in reverse polish notation. This one roughly works out to "run only if the output is more then 30% bigger then the input". Numbers < 1 also allow the shader to run if the output is smaller then the input.

But like was already said, in theory upscaling and then downscaling again won't gain you any quality. Although that makes me wonder that maybe neural network based scalers might actually add some information that makes it look better?
I've never tried it.

**Comment by Traneptora** [comment]
Upscaling with a neural net upscaler and downscaling with mitchell will create a softening effect that can be mistaken for an increase in quality.

**Comment by dokur0chan** [comment]
Movies aren't video games. You don't really gain much from "supersampling" videos if they already fit your native resolution. Video games gain more from supersampling because the visual information in a video game is (theoretically) infinitely scalable. With a video, you're only constrained to the visual information that you're given.

If anything, you're more at risk of reducing visual quality, because not only are you adding visual artifacts from whatever upscaling kernel/shader you're using, but now you're also adding artifacts from whatever downscaling kernel/shader you're using. 

That being said, it's not like "supersampling" is never done on video files... But this kind of pre-filtering is only done during the encoding process to repair aliasing artifacts in something like a badly mastered BD. And usually, the process for doing this is more meticulous, and more complicated than just "double with NNEDI3, downscale with Bicubic".

In general, I would not touch native sources if they don't need any scaling.

**Comment by christoph-heinrich** [comment]
I've now tested it with NN scalers, and most of the time it makes absolutely no difference. At least when looking at the output. Calculating the difference between screenshots might have revealed some slight differences, but if the difference is not noticable, does it even matter?

In one video there was a slight difference in one spot, but it was softer then the original, like Traneptora predicted.

**Comment by geextahslex** [comment]
1080p
![1km](https://github.com/mpv-player/mpv/assets/139760266/85825a47-d323-424a-b6d9-056d0ae9f06f)
4k
![4km](https://github.com/mpv-player/mpv/assets/139760266/05af2ac7-9d81-42e8-a1ce-8654fe0f3500)

look at the left eye, no difference? lol

**Comment by Artoriuz** [comment]
@geextahslex In general, what you're suggesting makes little sense because it can only ever accomplish anything positive when one of the steps is doing more than just resampling. Otherwise you're just making the image blurrier/sharper, and you can easily do that without resampling at all.

Also, the shaders you mentioned aren't exactly creating realistic details out of thin air, so they're unlikely to make a meaningful difference in this use-case. The story would be different if we were talking about something trained on perceptual metrics and/or with a degradation model that includes learning how to clean compression artifacts, but that's just not the case and these models are usually too large to be used in real time anyway. And, even in this case, you could still just remove the pixel-shuffling / transposed convolution layer to output at the target resolution directly, there's no need to upsample if you're going to downsample it back anyway.
