### ISSUE TITLE
What's the [F] ?

### ISSUE THREAD

**Issue by Piber0** [mpv-player/mpv#12288]
Hello, when using subtitles in PGS format, an [F] appears at the bottom right, what is it for? Thanks in advance.

![1](https://github.com/mpv-player/mpv/assets/95138823/ffc1d716-c276-4cc8-a438-439d94ec89e0)

**Comment by llyyr** [comment]
DVD/PGS subs can have forced subpictures within a subtitle track. Turning this on ([F]) basically makes it so that no other subpictures/bitmaps are shown besides the ones with the forced flag.

Actually finding a subtitle file that makes use of these flags is incredibly rare, so most of the time turning it on will just hide the subs entirely.
