### ISSUE TITLE
Add `libplacebo-opts=preset=high_quality` to `profile=gpu-hq`

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12317]
The current `profile=gpu-hq` values:
https://github.com/mpv-player/mpv/blob/0652a0b545a1c11627e153d187292d905be15bb0/etc/builtin.conf#L49-L60

The requested `profile=gpu-hq` values:
```
[gpu-hq]
scale=spline36
cscale=spline36
dscale=mitchell
dither-depth=auto
hdr-peak-percentile=99.995
hdr-contrast-recovery=0.30
allow-delayed-peak-detect=no
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes
deband=yes
libplacebo-opts=preset=high_quality
```

Reasons:
1. Any changes or additions to `high_quality` preset on `libplacebo` ([example 1](https://code.videolan.org/videolan/libplacebo/-/merge_requests/560)) will be carried over to mpv, ensuring always up-to-date high quality settings.
2. Solving the "settings issue" (where users will copy-paste values from different sources without knowing what each value is doing.) This way a simple command such as `profile=gpu-hq` will result in the highest quality values for mpv and for `libplacebo`.
3. I believe that `vo=gpu-next` will replace `vo=gpu` so it's important to simplify the integration between mpv and `libplacebo`.

**Comment by haasn** [comment]
This is not a good idea. `libplacebo-opts` applies after all other mpv options, so loading a `preset` here will effectively *prevent* all other options from working.

I think a better path forwards is to:

1. Require `libplacebo` in mpv by default
2. Move the gpu/gpu_next shared options to some shared location (out of `gpu/video.c`)
3. Initialize these options from their corresponding `pl_*_default_params` values, instead of hard-coding values

The most annoying consequence of this change is that the man page would no longer be able to list default values and would instead have to defer users to `--list-options`, but I think this is a compromise I can live with.
