### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [mpv-player/mpv#12330]
Does this work with Win 7?

Thanks

**Comment by CounterPillow** [comment]
god I hope not

**Comment by sfan5** [comment]
![readme](https://github.com/mpv-player/mpv/assets/1042418/3d86acb2-879f-498e-88cd-9791029ec13d)

**Comment by jimmy-1000** [comment]
It worked good, but the last version 20230924 doesn't work.

https://github.com/shinchiro/mpv-winbuild-cmake/issues/445

**Comment by Dudemanguy** [comment]
>GetSystemTimePreciseAsFileTime is not found at Kernel32.dll

We don't actually use this API in mpv directly so not sure where this is from?

**Comment by kasper93** [comment]
> We don't actually use this API in mpv directly so not sure where this is from?

We set `_WIN32_WINNT` to `0x0602` which is Windows 8. In this case headers can pull any function that is available on this platform, even if not used directly. Also apparently it happens only with clang build.

Anyway, we cannot be half way, either we support fully Windows 7 and set `_WIN32_WINNT` properly or we don't.

**Comment by Dudemanguy** [comment]
Yeah looks like nothing we can do about.

**Comment by avih** [comment]
> Targeting Windows 7 is just getting harder, because most toolchain like MSVC doesn't support building for it anymore. And apparently clang too

I don't know about msvc, but that's also irrelevant because mpv doesn't support msvc.

Clang definitely supports XP in at the latest version, which is 17, and you can even target windows XP with UCRT, by invoking e.g.

```sh
clang -DWINVER=0x501 \
      -D_WIN32_WINNT=0x501 \
      foo.c -o foo.exe \
      -Wl,--major-subsystem-version=5
```

(and installing the appropriate UCRT runtime, which exists for windows XP and later).

I'm quite sure all versions of gcc also support win 7 (and XP, if one insists).

So I don't thinki compiler support can be stated as a reason for dropping windows 7.

**Comment by kasper93** [comment]
> So I don't thinki compiler support can be stated as a reason for dropping windows 7.

Never was stated like that, we have a lot more reasons to not support Windows 7. And the main being that there is not developers to work on it. Patches welcome. Feel free to keep supporting it if you are interested in it.

**Comment by avih** [comment]
I simply pointed as an absolutely incorrect statement and argument which you made.

Nothing less, nothing more.

**Comment by kasper93** [comment]
What statement is incorrect? My statement is backed up by the fact that default installation of llvm **does not** support Windows 7, as pointed by others

> GetSystemTimePreciseAsFileTime is not found at Kernel32.dll

The fact that you can patch build to support older version is quite obvious, but that's not the case currently.

**Comment by DeadSix27** [comment]
Various things in w32_common are at minimum supporting **updated** Windows 10, so in the best case it just noops the functions otherwise it crashes.. I don't know why anyone would use Windows 7 anyway, unless it's running on an outdated industrial platform, which would be crazy for other reasons.

**Comment by kasper93** [comment]
> Various things in w32_common are at minimum supporting updated Windows 10, so in the best case it just noops the functions otherwise it crashes.

All of them are either dispatched with getprocaddr or would just fail silently if not supported. Don't make the issue bigger than it really is ;)

**Comment by DeadSix27** [comment]
> All of them are either dispatched with getprocaddr or would just fail silently if not supported. Don't make the issue bigger than it really is ;)

Fine, my point still stands though 🙃. A little skepticism is never bad.. and upon re-checking I think the newest function we use is vista+.

**Comment by kasper93** [comment]
Yes, I recently removed some Windows XP dispatch, but we try to keep it sane. Not really breaking anything Win 7+ intentionally.

> I simply pointed as an absolutely incorrect statement and argument which you made.

Just for the visibility, since we are arguing over this one thing.

mingw-w64-headers since this commit https://github.com/mingw-w64/mingw-w64/commit/f3c53a51df5c08f181e13a39b1cd6fd1d41edb96 uses Windows 10 as default _WIN32_WINNT value.

mpv's itself sets Windows 8, but the offending function does not come from mpv. It comes from `std::chrono` which does dispatch only for < Win8. https://github.com/llvm/llvm-project/blob/e39727d41fcdcdae2906ae0c982a6ebd19f442ad/libcxx/src/chrono.cpp#L70

And since libc++ is also build by this toolchain it will be build for Win10.

**Comment by zubrRB** [comment]
Windows 7 x64 is updated with monthly updates for Windows Server 2008 R2 until January 2026.
https://www.catalog.update.microsoft.com/Search.aspx?q=2025-04+Windows+Server+2008+R2
