### ISSUE TITLE
User Scripts: A few with error 404

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12350]
I was using https://github.com/po5/trackselect and https://github.com/po5/mpv_sponsorblock
and it appears to not be working now, I actually liked those two,
it's not entirely related directly to mpv, but maybe the user just changed his username and the links are not updated?

**Comment by llyyr** [comment]
They appear to have deleted their account, along with all repos. You can probably still find those scripts in various forks or `dotfiles` repos. Not a mpv issue either way

**Comment by dexeonify** [comment]
According to a quick google search, they probably deleted their account in protest of GitHub's For You page. (Or maybe for another reason, the search result doesn't make it clear and it only happened recently)
So sad to see another script author go :(
Hopefully, their scripts can be found in one of the many "friendlier" GitHub alternatives; otherwise, there's always archive.org.

**Comment by Hrxn** [comment]
Do I should know what GitHub's "For You" page is? I have absolutely no idea..

**Comment by l-jared** [comment]
A copy of everything is available on this account @l-jared

**Comment by iTzHard** [comment]
> A copy of everything is available on this account @l-jared

This is po5 btw.

**Comment by Hrxn** [comment]
Seems sketchy tbh

**Comment by NO-ob** [comment]
it is i know her

**Comment by po5** [comment]
Resolved (:
