### ISSUE TITLE
Subtitles frozen on first caption if mkv container contains audio + png thumbnail

### ISSUE THREAD

**Issue by mqudsi** [mpv-player/mpv#12387]
### Important Information

- mpv version: v0.36.0-274-gbe922231
- Windows Version: mpv-x86_64-v3-20230910-git-be92223
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/

### Reproduction steps

Create an mkv container with an audio payload (any supported codec/format) and a video payload that consists of a static png image to serve as a thumbnail or background image. Embed an srt and attempt to play.

### Expected behavior

The srt subtitle is decoded, displayed, and updated as the media player progresses through the file.

### Actual behavior

The first line/caption from the srt resource is shown, frozen & superimposed on the static png thumbnail/background. The text never updates.

### Log file

Log file: 
[sample.mkv.log](https://github.com/mpv-player/mpv/files/12600548/sample.mkv.log)

### Sample files

The following three files are the same audio + subtitle track. The first two also contain the same static png thumbnail as a video track.

* [MP4 w/ audio, subs, and png](https://0x0.st/Hfkv.mp4): works great. Background/thumbnail image is shown and subtitles play normally.
* [MKV w/ audio, subs, and png](https://0x0.st/Hfkw.mkv): buggy. Background/thumbnail image is shown but subtitles freeze and never update.
* [MKV w/ audio, subs, and no png](https://0x0.st/Hfkx.mkv): works great. No background/thumbnail, obviously, but subtitles play and update correctly.

**Comment by magnilens** [comment]
I use *.ass subs and jpg covers instead of srt and png. In my case, the subs _do_ update, but the thumbnail is still shown. I actually started from the mpv.net player, but poking around showed that the problem originated from mpv itself.
mpv.net does shed additional light on the bug. mpv.net has a right-click menu on the video window that allows the user to select which track to play. On a video without thumbnails, the video track is properly selected. On a video with thumbnails, the video track _isn't_ selected, but an "edition 0" instead. In mpv.net, the user can select the video track via the menu and continue viewing. This doesn't work in mpv itself, neither the keys to change video track nor edition will switch from the thumbnail to playing the video track. As mpv seems to be concerned, there is no other edition or video track, which is correct, but it isn't playing that video track.
Here is [my sample](https://drive.google.com/file/d/1B8HdrRZfz2lEHCX-dECf0aSp2IesLFpb/view?usp=sharing). It is similar to the second example above, but with *.ass subs and jpg thumbnail. You can play it in mpv, mpv.net and mpc-hc to see the different results. I was actually preparing it for another bug report which I will make a bit later.

**Comment by mqudsi** [comment]
Thanks for sharing the similarities with your situation. To be clear, I don't believe the issue is specific to the format of the image or the subtitles - rather an issue with mkv (possibly an incorrect optimization) that happens with static images selected as the video stream (correctly or incorrectly) and in the presence of subtitles. The specifics in the original report are just the reproducer.

**Comment by guidocella** [comment]
That mkv was generated incorrectly, thumbnails must be added like described in https://video.stackexchange.com/questions/35598/is-it-possible-to-embed-a-thumbnail-in-a-mkv-file.

**Comment by mqudsi** [comment]
@guidocella that would be an ffmpeg bug, then. The mkv was generated by converting an mp3 and the thumbnail came from the mp3.
