### ISSUE TITLE
OSC does not show when playing audio with dmabuf-wayland

### ISSUE THREAD

**Issue by linux40** [mpv-player/mpv#12516]
### Important Information

Provide following Information:
- mpv 0.36.0
- Artixlinux
- From the official world repo
- Sway 1.8.1
- i915 (details in the log)

### Reproduction steps

`mpv --no-config --force-window=yes --vo=dmabuf-wayland foo.flac`

### Expected behavior

OSC, lyrics (lrc file) and embedded images show properly like `mpv --no-config --force-window=yes --vo=gpu-next foo.flac`

### Actual behavior

- If foo.flac does not include an image, OSC and lyrics will not show.
- If foo.flac includes an image, OSC and lyrics could show, but the image shows improperly like this:
![2023_09_29_16_49_55_grim](https://github.com/mpv-player/mpv/assets/31679941/e2f64674-deb7-45d4-9782-bd6300b894b1)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12762746/output.txt)

### Sample files

https://0x0.st/HVEg.flac

**Comment by Dudemanguy** [comment]
The osc not being shown was fixed by e125da2096d97ec7e64701bf6289705a24c31729.

As for the image being all messed up, that's hard to say (the attached sample has no image). Could be a driver issue or something else. Could you actually provide a sample of the image in question? Or just try mpv on master and see if it still occurs.
