### ISSUE TITLE
Starting video and getting flashbanged by white background for a split second

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12549]
### Important Information

Provide following Information:
- mpv version:
```
[   0.003][v][cplayer] mpv v0.36.0-465-g0a1e3d86 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[   0.003][v][cplayer]  built on Oct  2 2023 00:22:06
[   0.003][v][cplayer] libplacebo version: v6.338.0-16-gcb6be98-dirty
[   0.003][v][cplayer] FFmpeg version: N-112255-g9e531370b
[   0.004][v][cplayer] FFmpeg library versions:
[   0.004][v][cplayer]    libavutil       58.27.100
[   0.004][v][cplayer]    libavcodec      60.27.100
[   0.004][v][cplayer]    libavformat     60.13.100
[   0.007][v][cplayer]    libswscale      7.4.100
[   0.008][v][cplayer]    libavfilter     9.11.100
[   0.008][v][cplayer]    libswresample   4.11.100
```
- Windows Version:
```
Edition	Windows 10 Pro
Version	22H2
Installed on	‎28/‎04/‎2023
OS build	19045.3516
Experience	Windows Feature Experience Pack 1000.19052.1000.0
```
- Source of the mpv binary:
https://github.com/shinchiro/mpv-winbuild-cmake/releases
- If known which version of mpv introduced the problem: Yes
Issue wasn't present on mpv-x86_64-v3-20231001-git-e969072
Issues present on mpv-x86_64-v3-20231002-git-0a1e3d8
- Possible screenshot or video of visual glitches: No

### Reproduction steps
Command line options: '--no-config' 'test.mp4' '-v' '-v' '-log-file=mpv.txt'

### Expected behavior
White background will no appear for a split second on startup of mpv

### Actual behavior
White background appear for a split second on startup of mpv

### Log file
[mpv.txt](https://github.com/mpv-player/mpv/files/12790303/mpv.txt)

### Sample files
Any file.

**Comment by kasper93** [comment]
It may sound weird, but that's not really related to recent changes. It does that on Windows 11 regardless. I will take a look after work, when I get a second.

**Comment by dokur0chan** [comment]
`--border=no` works around this.

**Comment by kasper93** [comment]
Can you test if latest build from 3rd of October, behaves the same? Because on this build there is not difference in window style when border is enabled, so I want to know if we are looking at the same regression?

**Comment by kasper93** [comment]
Please test the one from https://github.com/mpv-player/mpv/actions/runs/6399627222 (at the bottom there are packages)

**Comment by dokur0chan** [comment]
Oh, just to be clear, I don't believe this is a regression, mpv has always flashbanged me if I open a file from the File Explorer. This is just how it normally behaves without `--border=no`. I don't think there's necessarily an issue here, because the "flashbang" is a shader compilation, and Windows doesn't respect dark mode for stuff like this. Related: https://github.com/mpv-player/mpv/issues/8880 https://github.com/mpv-player/mpv/issues/8520

And yes, the new build still exhibits this.

**Comment by dokur0chan** [comment]
Well considering the fact that opening a new tab in the File Explorer causes one of these "flashbangs", I'm not too surprised that mpv experiences them as well. It's unrelated to whether or not you set dark mode.

**Comment by dokur0chan** [comment]
I'm on Windows 11. I don't really remember if this happened with Windows 10 since I always used `--no-border` anyways.

**Comment by kasper93** [comment]
> Oh, just to be clear, I don't believe this is a regression, mpv has always flashbanged me if I open a file from the File Explorer. This is just how it normally behaves without --border=no.

Ok, that's what I wanted to know. Because OP reported that this is a regression, so I wanted to make sure we are on the same page.

So regression that we had for one day is fixed, by https://github.com/mpv-player/mpv/commit/01c5346d1ada7185710963628012a5c3dcf1ce74 and is unrelated to the other issue. Which I can reproduce.

**Comment by kasper93** [comment]
We can keep it. I will send small patch for this and hijack this issue.

**Comment by dokur0chan** [comment]
@Obegg 
I'm on AMD. 

Anyways, like I said, this is just an unavoidable shader compilation thing. It could be manufacturer related, I dunno. Using a faster backend like `--gpu-api=vulkan` and `--profile=fast` doesn't make the white screen disappear.

@kasper93 
Right, what I'm describing is probably unrelated to what is going on here if that fixes it.

**Comment by dokur0chan** [comment]
@Sneakpeakcss 
Can't reproduce on Windows 11. Tested with
```
--no-config --vo=gpu-next --profile=high-quality --gpu-api=vulkan
```
and `vo_gpu`.

**Comment by Sneakpeakcss** [comment]
@dokur0chan 
I'm getting it with a default install (from sourceforge) and just `gpu-api=vulkan` in mpv.conf, but i can also reproduce it on my end with the same commands you provided. 


https://github.com/mpv-player/mpv/assets/77424331/aa98fd9a-f9e0-40aa-a465-9f14709b4278

It behaves like previously (without issues) when border is turned off.

**Comment by Sneakpeakcss** [comment]
@Obegg 

This doesn't seem to have anything to do with any hardware usage so technically you don't even need to play a video. 
With a clean download and without any additional changes to the config, put mpv player on fullscreen on your **secondary** monitor and then start opening/minimizing->maximizing folders (it can be any window really) from desktop on your **primary**, in case of browsing the web that would be the mentioned "magic", if we assume that your browser is in maximized state, here's a short example on my end:


https://github.com/mpv-player/mpv/assets/77424331/7c62c557-4ff1-4596-bfc8-3309226c43c1

Surprisingly shareX didn't catch the stutter on maximizing of the notepad window, but you can still see what happens when i circle it around close to the border between the monitor that has mpv (without anything playing) on fullscreen, the stutter stops the moment it crosses on top of the mpv player, and then a moment later when another window is maximized on primary there's no stutter at all no matter what i do.

This is the only reason why i even used vulkan over the default d3d11.
