### ISSUE TITLE
Changing --video-crop runtime causes temporary window jumping

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#12589]
### Important Information

Provide following Information:
- mpv version 84fa7ea
- macOS Version 14.0
- Source of the mpv binary or bundle: Git
- Version of mpv introduced the problem: #12222
- Possible screenshot or video of visual glitches: [Video or it did not happen.mp4](https://github.com/mpv-player/mpv/assets/1167421/5983d4a9-37f1-4e05-b2bf-941bc8ab47fe)

### Reproduction steps

Add this script:

```
local x = 0

function test()
  x = x + 8
  local width  = mp.get_property('width') - x
  local height = mp.get_property('height')
  local crop = width .. 'x' .. height
  mp.set_property('video-crop', crop)
  mp.osd_message(crop)
end

mp.add_key_binding('@', nil, test, {repeatable = true})

```

Run this command line.

`$ mpv https://v3.cdnpk.net/videvo_files/video/free/2015-08/originalContent/cornfield_2.mp4`

Hold / tap `@` while watching the video.

### Expected behavior

Window should shrink instantly.

### Actual behavior

Window jumps for several frames before settling on the correct size.

### Log file

N/A

**Comment by kasper93** [comment]
> Window jumps for several frames before settling on the correct size.

Not sure what exactly "window jumps" means, but in general window resize and next frame draw is not fully synchronized, so you may see the process of resizing happen, for say next frame.

It works as expected for me on Windows and Linux (Wayland), visible, but nothing too distracting.

From your report I would expect there is some macOS issue when resizing window? If you describe it as "Window jumps", but I do not have hardware to test that, so someone else will need to help you here.

**Comment by forthrin** [comment]
@kasper93: See video added to OP

**Comment by kasper93** [comment]
I missed the video. Yes, so probably can be improved in mac windowing code. For me it just shrinks the window first and then once new (cropped) frame arrives it redraw. Not fully seamless, but better than on your video.

**Comment by Akemi** [comment]
that's most likely not possible with how the CAOpenGLLayer and libmpv render loop is working, without breaking something else.

it's not possible the get the window resize and rendering completely in sync. it will most likely be better with --video-sync=display-resample, that way the render loop renders/updates at the frequency of the display.

otherwise this is a won't fix with cocoa-cb. it should be considerably better with https://github.com/mpv-player/mpv/pull/7482.

**Comment by forthrin** [comment]
Thanks for commenting!

1. Glitches are indeed a lot prettier with `--video-sync=display-resample`. Any downsides to using this as a default?
2. Git instructions for trying Vulkan with mpv-build? How mature/complete (%) is this project?

**Comment by Akemi** [comment]
1. since it renders at display refresh rate instead of video refresh rate/timing it might use some more gpu, uses more battery etc
2. instruction are on the PR (you need libplacebo and moltenvk/vulkan sdk https://vulkan.lunarg.com/sdk/home). i would call it experimental, there still some minor problems, general responses to it seem very positiv though. i hope to finish up the remaining major blockers this weekend and we might get it merged this or next week.

**Comment by forthrin** [comment]
If it's just a couple of weeks away, I'll wait for the merge. Great momentum on the project these days!
