### ISSUE TITLE
How to specifically letter "sub-font" value to match given font

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#12691]
If I, for example, want to use font “PublikSemiBoldItalic.ttf” (or other examplesbelow), what do I set `sub-font` do?

More specfically, what combination of ...

- font filename
- font metadata (title, style, etc.)
- space characters

... do I use, and by which logic do I concatenate them into `sub-font` for mpv to find and apply a font?

And is bold font achieved by including “Bold” in `sub-font`, or by setting `sub-bold=yes`? Or either?

The manual didn't seem to go into detail, and lots of trial goes into getting the string exactly right for the font to take.

```
PublikBlack.ttf
PublikBold.ttf
PublikBoldItalic.ttf
PublikItalic.ttf
PublikLight.ttf
PublikLightItalic.ttf
PublikRegular.ttf
PublikSemiBold.ttf
PublikSemiBoldItalic.ttf
```

**Comment by mia-0** [comment]
How exactly fonts are selected depends on which font provider libass was built with, which means that it usually depends on the OS. In general, using the full font name (e.g. “Publik Semibold Italic” if I guessed it right) should work, but choosing a specific variant (“Semibold Italic” in this case) means subtitle files won’t be able to override it properly (like switching to non-italic or other weights). There are [examples](https://mpv.io/manual/master/#options-sub-font) in the manual.

It doesn’t go into more detail because the way font selection by name works is loosely defined and messy: The exact name to use for a given font variant depends on font metadata, which with some fonts may also be inconsistent and yield different behavior with each font provider.

**Comment by mia-0** [comment]
Let me know if anything is still unclear so I can try and make that manual section a little more explicit about how this works.

**Comment by forthrin** [comment]
Thanks for commenting.

Even if naming is inconsistent, the code **does** have a logic to find the font, and so as a user, you want to know this logic: "How do I refer to font X with style Y to get what I want" **without trial and error**?

Whether it's filename, metadata, or a combination or order, there -is- always a logic, so what must the user do, *step by step*, to determine the correct string

- Open Finder at `~/Library/Fonts`?
- Open Font Book?
- Run some obscure command line utility
- Examine the file binary with `xxd`, etc.

Since `mpv` already has its logic by which it operates, maybe the most helpful thing would be to make a command line option in mpv that lists all strings for a particular font.

`mpv --list-font ~/Library/Fonts/Flakey.ttf`

Or make the font finding code so fuzzy/smart/forgiving that the user is practically guaranteed to get it right regardless of spaces, casing, word order, even typos.

**Comment by Akemi** [comment]
on a side note. it's not an mpv logic, it's libass and its used font provider. the logic itself is/can be internal to the framework used, eg CoreText on macOS (if nothing changed). this question is sadly none trivial and big mess.

though an 'easy' way to find the proper font is most likely using Aegisub and looking which font name it is using when selecting a font.
