### ISSUE TITLE
How to play back 150hz video?

### ISSUE THREAD

**Issue by johannesCmayer** [mpv-player/mpv#12781]
Maybe this is a dumb question but how to I play back videos above 60fps? When I try to playback, it seems like all the frames above 60fps get dropped. When I play back a 75fps video, then already some frames are dropped, while at 60fps no frames are dropped. Therefore I think it is unlikely that my CPU is the issue here.

Some possibly relevant details:
- I have a setup with monitors, only one of them supports 144hz.
- The info overlay shows that mpv correctly recognizes the framerate.
- The videos are usually not exactly 144 fps, but rather e.g. 150fps, as I generate them with an AI frame interpolation tool.
- I tried `--overwrite-display-fps=144` but it did not change anything. I also don't really understand this option.

Thank you for any help.

**Comment by Dudemanguy** [comment]
If the video in question has an fps higher than the refresh rate of your monitor, frames will always be dropped. This is because your monitor is physically incapable of displaying frames fast enough thus frames get dropped. You could attempt to playback at slower speeds or use filters to change the video's fps, but fundamentally you can't watch the video as intended because your hardware isn't capable of it.

**Comment by johannesCmayer** [comment]
I have a 144 Hz display. The same number of frames is always dropped, no matter on which monitor it is played. Probably this is not an mpv issue though, because VLC also does this. I would still like to know how to prevent this though. 75Hz video definitely should not have frames dropped on a 144Hz monitor. I can run games on 144Hz and that works fine.

**Comment by Dudemanguy** [comment]
The original question was about a 150 fps video. This is, of course, higher than your 144hz display so everything I just said still applies. You are going to drop drop frames because your hardware is not capable of showing every frame. Nothing we can do about that.

>75Hz video definitely should not have frames dropped on a 144Hz monitor

Indeed it should not. But I don't have a crystal ball to understand what is happening on your machine.

**Comment by llyyr** [comment]
Open a new issue and don't ignore the template this time
