### ISSUE TITLE
problems with 6-channel jack audio output

### ISSUE THREAD

**Issue by kalle-del-haye** [mpv-player/mpv#128]
Hi,
i'm using mpv (git-49fb242) on a minimal ubuntu linux (3.8.0-26-generic) and there are two problems with the audio output to jack.
1. distored sound
   channels=2 - sound OK
   channels=6 - stottering distored sound on all channels
   I had the same 2-ch/6-ch problem with mplayer2 and used this patch (http://devel.mplayer2.org/ticket/246) to get it work. So I changed the CHUNK_SIZE from (16 \* 1024) to (24 \* 1024) in /audio/out/ao_jack.c that fixed the 6-channel playback.
2. wrong channelmapping/missing channels
   The mpv-output shows "AO: [jack] 48000Hz 5.1(side) 6ch floatle" this means that 5.1(side)=(fl-fr-fc-lfe-sl-sr) is used by default. But jack uses the alsa driver for audio output to the soundcard. So 5.1(alsa)=(fl-fr-bl-br-fc-lfe) would be the right default.
   The option af=force=out-channels="5.1(alsa)" fixes the 6-channel playback for me, but with 2-channel sources I have no sound and mpv shows:
   [af_force] Forced input/output format are incompatible.
   [libaf] Reinitialization did not work, audio filter 'force' returned error code -2
   Audio filter chain:
   [in] 48000Hz stereo 2ch s16le
   [force] 48000Hz 5.1(alsa) 6ch s16le <-
   [out] 0Hz empty 0ch ??
   [ao] 0Hz empty 0ch ??
   Error at audio filter chain pre-init!
   Audio: no audio

Is it possible to fix the channelmapping problem without changing the options for every source-file?

Let me know if i can do some mpv/jack/5.1 tests to help you!

kalle

**Comment by v-fox** [comment]
> No reaction after a week? So I assume it works.

And then you've gone and [removed it in 2015](https://github.com/mpv-player/mpv/commit/a7f51f8fd48df7f04f47b515180338f8b9b78fed) because "waveext is cool, though !" in some kind of anti-ALSA crusade :/
Hopefully, I don't have non-stereo setups but that certainly doesn't bode well for package maintenance.

**Comment by wm4** [comment]
Complain to Jack and the impossibility to do multichannel audio correctly with it.

**Comment by v-fox** [comment]
> Complain to Jack and the impossibility to do multichannel audio correctly with it.

And you couldn't just let it be mildly broken with those 4 lines of code and had to make it completely broken ? Then why have this waveext thing which doesn't work even more ? Remove it all !

You KNOW that:
1) JACK is mostly used on Linux and with pure ALSA.
2) JACK uses default backend order.
3) Most audio setups are 2.0 (2), 2.1 (3), 5.1 (6) and 7.1 (8) which is pretty unambiguous.

So, ALSA order by default would be a safe bet for almost all use-cases of JACK. And yet you do the opposite with which no one benefits.

For me, the real problem with mpv's JACK support is:
1) Inability to write full input port names instead of just input client name. I redirect mpv in Calf which has a bunch of ports that mpv has no business connecting. That is especially important after mpv's volume normalization got cryptic and unusable in late versions.
2) Weird mpv's behaviour which often results in JACK error of mpv automatic patchbay port  redirection "fail", usually on mpv's startup. And I think I saw something about "inability to redirect inactive client" or something like that. mpv really doesn't like being forcibly redirected.

With all that might as well use Pulse as JACK shim despite the overhead. That thing seems to find its ports just fine somehow.

**Comment by wm4** [comment]
That removal was to get rid of the last parts of ALSA legacy channel map support (removed in the commit after that). You're not trying to argue that this should have been left in, because it happens to work by coincidence for some people on Linux, or are you.

If pulse works for you, that's great.

**Comment by v-fox** [comment]
> You're not trying to argue that this should have been left in, because it happens to work by coincidence for some people on Linux, or are you.

I'm trying to argue that it should have been left alone or replaced with something better because that's what works best for most people using JACK in general and pretty much all people using it on Linux.
Do you have any guarantees that situation described above (outputs changing order per file / >=5.1 channel defaults being always unusable) will not happen now ?

> If pulse works for you, that's great.

It works with big overhead that increases the chance of xruns significantly. I'm using mpv->PA->JACK->ALSA setup as benchmark of stability for JACK's settings in general. Not sure if mpv calculates its latencies right like this.
But current mpv's JACK code craps in JACK's logs often on mpv startup. And then there is this whole deal. This surely can't be right.

**Comment by wm4** [comment]
Not sure why you think chaining N audio APIs increases stability over M audio APIs where N > M.

**Comment by v-fox** [comment]
> Not sure why you think chaining N audio APIs increases stability over M audio APIs where N > M.

It doesn't, on the opposite. Putting PA (running realtime too) between mpv and JACK increases strain on realtime scheduling, so if the system then can handle it fine, it could handle most situations. That's why I only benchmark with that and not using it this way. Although PA<->JACK is necessary for PA-only application (like most stable SIP clients and games) and those with broken JACK support (like Firefox).
But PA also seem to properly find its JACK output ports and doesn't spit error on selective patchbay redirection for some of them.
