### ISSUE TITLE
demuxer-lavf-o key option license_key not working for widevine video

### ISSUE THREAD

**Issue by aicynide** [mpv-player/mpv#12805]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by kasper93** [comment]
> license url, how to play the video in mpv?

Obviously, not in mpv. mpv is not a DRM player... You need to have decryption key and how to get decryption key is not a topic related to mpv.

**Comment by kasper93** [comment]
Having licence url is nothing, you need to have decryption key.

> How to supply license url for mpd url?

MPV is a free, open-source multimedia player that can play a variety of formats. However, MPV does not have built-in support for Digital Rights Management (DRM) protected content, such as videos encrypted with Widevine. This is because handling DRM typically requires licensing agreements and adherence to strict content protection standards that are not in the scope of most open-source projects.

To play Widevine-protected content, you would generally need a player that specifically supports Widevine DRM. Popular browsers like Chrome, Firefox, and Edge have built-in support for Widevine, as do many commercial media players and platforms.

For software like MPV, there would need to be an integration with a DRM solution that can handle the license exchange and decryption process. Since MPV and similar open-source projects do not support Widevine natively, you would typically not be able to play Widevine-encrypted files directly in MPV using a license URL.

However, if you are dealing with Widevine DRM and you have legal access to the content and rights to play it, you might have to use a different player that is capable of handling DRM-protected content. Services like Netflix, Hulu, and others that use Widevine DRM will generally require you to use their own apps or supported browsers for playback.

If you're developing an application and you need to support Widevine DRM, you would generally use a library or a service like Google's Shaka Player or Dash.js for web applications, which are designed to handle the complexities of license acquisition and content decryption.

Always ensure that you are complying with all relevant copyright laws and terms of service when attempting to play back DRM-protected content.

~ChatGPT
