### ISSUE TITLE
Default deinterlace

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12835]
[A while ago](https://github.com/mpv-player/mpv/issues/12478) I asked about deinterlace options and I got my answer,
there's `yadif` and there's `bwdif`,
I've tested both and it seems like `bwdif` is better (from my testing),
my question is - why isn't `bwdif` the default when using `deinterlace=yes`?

This question might be unrelated to mpv because it's ffmpeg options,
but regardless, from what I can see there's a clear winner here.

**Comment by kasper93** [comment]
I agree it should be `bwdif` as a fallback, but for historical reasons it is `yadif`, simply because `bwdif` did not exist before. 

By default we try to use deinterlacing filter that is compatible with hw frame format. It looks mostly like this.

| FMT | DEINT |
|----------|-----------|
| vdpau | vdpaupp|
| d3d11 | d3d11vpp|
| cuda | yadif_cuda|
| vulkan | bwdif_vulkan|
| vaapi | vavpp|
| other/fallback | yadif|

Patches welcome, it need a change here:
https://github.com/mpv-player/mpv/blob/468b9bede7f01dd27dff070c89ad21c765e51e00/filters/f_auto_filters.c#L124

**Comment by Dudemanguy** [comment]
For future generations, the fallback is now `bwdif` not `yadif`.

**Comment by kasper93** [comment]
@Dudemanguy Looking at my table, we could also switch to `bwdif_cuda` for consistency. Vulkan already uses it.

**Comment by Dudemanguy** [comment]
Ah yeah didn't consider that.
