### ISSUE TITLE
Shrink window width/height -only- by dragging respective window edges

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#12909]
Before requesting a new feature make sure it hasn't been requested yet.
[**Couldn't find none**](https://github.com/mpv-player/mpv/issues?q=label%3Ameta%3Afeature-request+drag+window)

### Purpose

Quick and elegant way to ...

- Hide hard-coded black bars (or crop the top-bottom of a portrait aspect video)
- Hide the not-so-important left/right perimeter of a widescreen video (ie. crop a 16:9 video to 4:3 or whatever smaller width), to make the window take up less screen estate.

### Expected behavior of the wanted feature

- Drag left/right window edge: Shrink window width only
- Drag top/bottom window edge: Shrink window height only
- Drag window corners: Shrink window width/height (current behavior)

### Alternative behavior of the wanted feature

Wouldn't mind having to hold `Cmd` or `Alt`, if a default implementation drove some people nuts.

**Comment by Akemi** [comment]
so you mean the behaviour with `--no-keepaspect-window`?

holding `shift` while resizing the window with that option keeps the current window aspect ration (current default behaviour).

**Comment by forthrin** [comment]
The requested feature should not change aspect ratio ("stretch" video), but rather imitate `object-fit: cover` in CSS.

When narrowing window -width- by dragging left/right window edge, the left/right sides of the video should disappear outside/behind the window edges, whereas the window -height- is completely unchanged.

And vice versa when dragging top/bottom edge.

PS! The referenced `--no-keepaspect-window` behaves curiously like so here: If holding `Cmd` and enlarging window edges , black bars are added in that direction. Reducing window below video size simply shrinks the video like usually.

**Comment by Akemi** [comment]
so it's `--no-keepaspect-window --panscan=1`?

**Comment by forthrin** [comment]
Your references seem to do something completely different. See "Purpose" in OP. I haven't explained this *that* badly.

The requested feature is something like movie theaters pulling the red curtains towards the center of the screen to hide the edges of the video content. Some TVs in the 60s even had wooden panels you could pull to cover up the CRT.

**Comment by Akemi** [comment]
to me your explanation is very ambiguous. you did neither specify wether it should crop or add black bars in the various cases. you are speaking of two different purposes with 3 different variations, which could be interpreted in different ways way. hence why i am asking.

> - Hide soft-coded black bars
> - Narrow down a (very) wide video

maybe start by explaining what you mean by 'soft-coded black bars'?

> - Drag left/right window edge: Shrink window width only
> - Drag top/bottom window edge: Shrink window height only
> - Drag window corners: Shrink window width/height (current behaviour)

either something is completely different on your end, something is broken, or your testcase is different from mine. because `--no-keepaspect-window --panscan=1` behaves exactly like i expect `cover` to work. `panscan` is basically just cropping, and panscan=1 just crops so the whole video is contained in the rendering surface.

**Comment by forthrin** [comment]
Oh, the hardship of concise and efficient communication on the Internet... Let's try a practical example:

1. Let's say we open a 1920x1080 video in a window, displayed 1:1 (window-scale: 1.000).
2. Now, if I drag the left or right edge of the window 10 pixels towards the center, I want the window -- and the video -- to be 1900 pixels wide, ie. the outermost 10 left and right pixels are hidden. The height -- and aspect ratio -- is exactly the same as before. `mpv --video-crop=1900x1080` would accomplish this.

Is this supposed to happen with your suggestion? If so, something is really broken on my end, because I have quite an up-to-date Git version, and prepended with `--config-no` and everything.

"Soft-coded black bars" are eg. videos that are 1920x960 in actual content, but encoded as 1920x1080, eg. 60 pixels of encoded black pixels on the top and bottom.

I hope the intention will be clear now, or else I'll get a headache.

**Comment by hooke007** [comment]
> "Soft-coded black bars" are eg. videos that are 1920x960 in actual content, but encoded as 1920x1080, eg. 60 pixels of encoded black pixels on the top and bottom.

LOL. I never heard about the strange word. You probably want to say https://en.wikipedia.org/wiki/Letterboxing_(filming) or "**hardcoded** black bars"

**Comment by forthrin** [comment]
*facepalm*. Yes, hard-coded is the correct term.

**Comment by hooke007** [comment]
Not perfect but you could do the similar work now.
```
mpv --no-config --idle=yes --force-window --hidpi-window-scale=no --video-unscaled=yes --keepaspect-window=no
```

**Comment by forthrin** [comment]
Doesn't crop the video like expected, with any tried key modifiers (None, Cmd, Alt).

**Comment by forthrin** [comment]
I think the pseudo-code would be something along the lines of:

```
if drag window left/right
  video crop x = min(video width, window width)
elsif drag window top/bottom
  video crop y = min(video height, window height)
else # drag window corner
  # simply scale video within window (current behavior)
end
```

**Comment by po5** [comment]
Try autocrop.lua.

**Comment by forthrin** [comment]
That removes black bars automatically, but does not handle other needs (now further detailed in OP).

**Comment by Akemi** [comment]
> 2. Now, if I drag the left or right edge of the window 10 pixels towards the center, I want the window -- and the video -- to be 1900 pixels wide, ie. the outermost 10 left and right pixels are hidden. The height is exactly the same as before. And DAR is 1:1 (no stretching in any direction). `mpv --video-crop=1900x1080` would accomplish this.

i think there is a small typo. you mean if you drag 20 pixels you want 10 pixels be cropped on the left and right? you want that cropping to be applied on both sides evenly, eg the video is cropped `centered`.

you don't want to crop X pixels on the side you drag the window and leave the opposite side untouched?

i will look into that again if i have a bit more time and get back to you.

**Comment by Akemi** [comment]
> Oh, the hardship of concise and efficient communication on the Internet... Let's try a practical example:
> 
> 1. Let's say we open a 1920x1080 video in a window, displayed 1:1 (window-scale: 1.000).
> 2. Now, if I drag the left or right edge of the window 10 pixels towards the center, I want the window -- and the video -- to be 1900 pixels wide, ie. the outermost 10 left and right pixels are hidden. The height is exactly the same as before. And DAR is 1:1 (no stretching in any direction). `mpv --video-crop=1900x1080` would accomplish this.
> 
> Is this supposed to happen if dragging window edges with your suggestion? If so, something is really broken on my end, because I have quite an up-to-date Git version, and prepended with `--config-no` and everything.

i think that's exactly what happens with the new macvk backend. the libmpv/cocoa-cb backend behaves a bit differently, at least on live resize because of how the rendering works, but the outcome is the same.

original:
![Screenshot 2023-11-21 at 01 21 06](https://github.com/mpv-player/mpv/assets/680386/95bc77c2-eb85-4221-a9fa-bf93ef78d19a)
dragged from the left:
![Screenshot 2023-11-21 at 01 21 41](https://github.com/mpv-player/mpv/assets/680386/91a41581-338a-44a1-a750-2dc9e9dbd3c5)
dragged from bottom
![Screenshot 2023-11-21 at 01 22 04](https://github.com/mpv-player/mpv/assets/680386/75eb6598-2ac0-4f2a-9ec6-161b504a0d06)

video:

https://github.com/mpv-player/mpv/assets/680386/14ec256c-6bd2-4a33-a889-857605469f7a

**Comment by forthrin** [comment]
😀❤️😭 Some times your dreams come true before your very eyes. This is one of those times.

So this is part of "Vulkan"? When can it be built with `mpv-build` and run for everyday use with negligible friction?

**Comment by Akemi** [comment]
lets say it's part of the lot better rendering pipeline of metal and the fucked up opengl rendering on macOS. i probably can change the cocoa-cb backend in a way that both work the same way, though it will have a big performance impact and it might have other side effects, eg the current behaviour is like that to fix the those side effects.

if you install the vulkan sdk/moltenvk `mpv-build` should be able to build a binary with vulkan support.

**Comment by forthrin** [comment]
```
$ brew install molten-vk
==> molten-vk: stable 1.2.6 (bottled), HEAD
$ cd mpv-build && clean && build
...
Run-time dependency vulkan found: NO (tried pkgconfig and system)
Header "vulkan/vulkan_core.h" has symbol "VK_VERSION_1_3" : YES 
...
$ brew info pkg-config
==> pkg-config: stable 0.29.2 (bottled)
$ mpv --vo=gpu-next --gpu-api=vulkan --hwdec=vulkan
Error parsing option gpu-api (option parameter could not be parsed)
Setting commandline option --gpu-api=vulkan failed.
```

**Comment by Akemi** [comment]
that's completely a problem of brew. i never got it to work either and instead just used the sdk installer (https://vulkan.lunarg.com/sdk/home#mac).

**Comment by forthrin** [comment]
1. The installer asks for Rosetta, which I don't have nor want.
ETA for a Silicon installer? Or working Brew? Other ways to install?

2. Window dragging should snap to multiples of 8, and like "Terminal", display helpful information in the window title, either *window size*, eg. "1280x720", or *aspect ratio* when hitting common standards, eg.

```
    2.39 => 'CinemaScope', 1.85 => 'US widescreen',
    2.00 => 'Univisium', 1.78 => 'Widescreen', 1.33 => 'Fullscreen',
    0.56 => 'Portrait'
```

**Comment by Akemi** [comment]
so how is it? since we have nightly bundle builds now it shouldn't be a problem testing it.

**Comment by forthrin** [comment]
These nightly builds are where, exactly? Only old stuff [here](https://mpv.io/installation/).

**Comment by Akemi** [comment]
a short explanation where to find them here https://github.com/mpv-player/mpv/issues/13085#issuecomment-1962940210 or the comment underneath for direct links.

**Comment by forthrin** [comment]
Installed the nightly build, and added the three vulkan settings in mpv.conf, but no cropping like the video above.

- Edge-dragging just resizes the window normally.
- Holding Cmd or Alt while dragging changes gravity from north to center, but still only resizes.

Says `Unsupported hwdec: vulkan` so I guess that's it.

Is Vulkan supposed to be embedded in the nightly builds? If no, what methods of installation exist? (Without Rosetta)

**Comment by Akemi** [comment]
it says hwdec (hardware decoding), that's not a video output.

sure it is supposed to be bundled, otherwise i wouldn't have suggested it. it also already has been tested to work.

**Comment by forthrin** [comment]
```
$ /Applications/mpv.app/Contents/MacOS/mpv --version
mpv 78447c4 built on Mar  7 2024 22:09:22
$ /Applications/mpv.app/Contents/MacOS/mpv --pause https://camo.githubusercontent.com/c8745ccd6686c6538ae8e3869e413c7579633b716e8298d550e0434594f7cb34/68747470733a2f2f7777772e636869702e64652f69692f342f372f322f382f352f352f342f663863336266303834653038363538622e6a7067

```
On edge drag with(out) shift/alt/cmd: Does not crop, only scale. What could be wrong? Do you need video proof?

**Comment by Akemi** [comment]
the as always a log would be a start. the bits of information you are feeding me are kinda useless without proper context. be a more specific about what you are doing. "added the three vulkan settings" > it's not clear what 'vulkan settings' you mean, since i only suggested 2 options (eg `--no-keepaspect-window --panscan=1`) that are not vulkan specific.

**Comment by Akemi** [comment]
can we please keep it at one problem/feature request/etc per issue. otherwise this is getting out of hand and there is no reasonable way to keep track of such things.

changing title is already possible. just properly read the manual, about [property expansion](https://github.com/mpv-player/mpv/blob/a56d8ff18470e4612cbb23e35e7849b8e522ba7e/DOCS/man/input.rst#L3669-L3730), the [title option](https://github.com/mpv-player/mpv/blob/a56d8ff18470e4612cbb23e35e7849b8e522ba7e/DOCS/man/options.rst#L3051-L3061) and the [right property](https://github.com/mpv-player/mpv/blob/a56d8ff18470e4612cbb23e35e7849b8e522ba7e/DOCS/man/input.rst#L2521C7-L2523
). even without property expansion this could be easily done by a script.
```
title="aspect-name: ${video-params/aspect-name}"
```

snapping the size to multiple of 8 will most likely not happen as a feature. just use a keybinding or a script to set the geometry property to an appropriate size (they update on playback now) and you the keep aspect ratio window sizing (via shift).

i can only repeat myself. it's already possible to build with vulkan and mpv-build. you are just unable or unwilling to install the vulkan sdk. the nightly builds use homebrew to install the sdk too. so it's definitely possible and works.

also i am not a notification centre or a convenient way to get how-tos, especially not on completely unrelated issues. this is getting ridiculously out of hand. a bit of self-research and self-initiative wouldn't be so bad.

closing since feature was implemented.

**Comment by forthrin** [comment]
Snapping seemed related and low-hanging, but I hear you once more to really keep issues separate. A script should do the trick, bar possible glitching. Thanks for the feature and the patience.
