### ISSUE TITLE
Real-time SDR to HDR conversion

### ISSUE THREAD

**Issue by jan-kleks** [mpv-player/mpv#12950]
### Expected behavior of the wanted feature

Could any SDR to HDR real-time conversion techniques be adapted for mpv? Or is it not worth it? 

See for instance:

- [Style Aware Tone Expansion for HDR Displays](https://web.archive.org/web/20230912091926/https://graphicsinterface.org/wp-content/uploads/gi2016-8.pdf) by b-com

- [b-com Sublima tech](https://b-com.com/en/process/sublima)

- [HDR-X Video Converter by TEKNO3D Labs](https://www.youtube.com/watch?v=_s13irv_zLk) - supposedly has "on-the-fly" mode

**Comment by llyyr** [comment]
See https://mpv.io/manual/master/#options-inverse-tone-mapping

**Comment by jeeb** [comment]
As an example, the following works for me on Windows while using gpu-next and the gpu-hq profile

```
mpv --vo=gpu-next --profile=gpu-hq --inverse-tone-mapping --target-colorspace-hint --target-prim=bt.2020 --target-trc=pq --msg-level=vo=v FILE
```

* inverse tone mapping will enable that feature
* target colorspace hint will affect the output swap chain configuration based on your target (or otherwise input)
* target configuration tells that you want to override the output to BT.2020+PQ
* message level bumping means you should see the win32 VO logging which should say `[vo/gpu-next/libplacebo] New swap chain configuration received from hint: format: R10G10B10A2_UNORM, color space: RGB_FULL_G2084_NONE_P2020.` which tells Windows the swap chain is HDR.

**Comment by Traneptora** [comment]
Does this answer your question?

**Comment by jan-kleks** [comment]
@Traneptora Thank you everyone for all the replies! There is some criticism of the inverse tone mapping in mpv here: https://old.reddit.com/r/mpv/comments/11r5pkq/inverse_tone_mapping_any_benefits/

Shouldn't the algorithm take into account more info about a given SDR frame for better conversion results? Check out, for example, the first link at the top of this GitHub feature request for an article with more context.

**Comment by Dudemanguy** [comment]
Original question seems answered. Feel free to open a new issue about anything more concrete.
