### ISSUE TITLE
regression: --term-status-msg missing from --log-file since 2fd34889

### ISSUE THREAD

**Issue by josch** [mpv-player/mpv#13038]
Hi,

the mpv test of the phoronix test suite prints the FPS using --term-status-msg and tries to find those in the resulting log file:

https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/ob-cache/test-profiles/system/mpv-1.0.1/results-definition.xml

To this end, it starts mpv like this:

    mpv --no-audio --untimed --opengl-swapinterval=0 --video-sync=display-desync -v -v \
        --osd-msg1="FPS: \${estimated-display-fps}" --term-status-msg="FPS: \${estimated-display-fps}" \
        --term-osd-bar --length=300 --log-file=log bbb.mp4

This functionality broke with commit 2fd34889fe7732eafc60e4acaf20c4fced9a4a81. Since then, the `[statusline]` messages that are still written to the terminal do not anymore end up in the log file.

Was this change intentional?

Can/should the phoronix test suite change something so that it can capture the FPS values with modern mpv?

Thanks!

**Comment by kasper93** [comment]
> To this end, it starts mpv like this:

This command is wrong for generic benchmarking. The `estimated-display-fps` doesn't mean what you think it means.
Imagine "benchmarking" 24fps video on 60Hz display. mpv will render frame once and redraw twice. Now change display to 144Hz, you will render 1 and redraw 5 times. redraw is cheap, it will inflate the number 2.5 times compared to the 60Hz display, while doing almost exactly the same work, except few more redraws.

> Was this change intentional?

Hard to say, it is not mentioned in commit message. Looks like it was side-loaded, but frankly this is good change, log file should not be polluted with status messages, that are spammed few times per play loop (which is basically per vsync or video frame, depending on settings). So yes, status messages are not logged into log file intentionally.

> Can/should the phoronix test suite change something so that it can capture the FPS values with modern mpv?

Use proper lua script to gather data instead of parsing status line.
