### ISSUE TITLE
Upmix 2.0 to 5.1

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#13030]
I've noticed that many of the video and audio files I play are 2.0 but I use surround sound system of 5.1.
I was thinking if it was possible to upmix from 2.0 to 5.1 in mpv settings or user script?
All I could find about it is [this](https://github.com/mpv-player/mpv/wiki/ALSA-Surround-Sound-and-Upmixing), but this is for Linux and not for WIndows.

Edit: I also want it to ONLY upmix when the audio file has 2 channels, no need to upmix when the audio source is 5.1.

Note: I have no issues playing DTS-HD MA or Dolby TrueHD files that have 6 or 8 channels, those are working fine,
mpv and Windows recognize I have surround sound system.

**Comment by hooke007** [comment]
`audio-params/channel-count` is not reliable.

**Comment by richardpl** [comment]
surround filter uses RDFT transforms and tries to extract soundfield from stereo audio, there are non-default options for this filter that give a better quality at cost of higher CPU usage. Other alternatives for upmix are simple one with pan filter, but that is just different linear mixes. Thats all that is currently available within mpv, unless you use LV2 plugins but that is mainly for Linux.

**Comment by Doofussy2** [comment]
> > there are non-default options for this filter that give a better quality at cost of higher CPU usage
> 
> Throw it at me, I have a good CPU, let me use it to it max usage. Give me the commands to use.
> 
> > You should set windows to 5.1 and the filter to correspond with the windows configuration.
> 
> Then why my AV Receiver says it supports 8 channels? ![image](https://private-user-images.githubusercontent.com/13978119/287545638-b49b9154-c67e-406c-829e-54dca1b650d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MzQzNjQsIm5iZiI6MTcwMTYzNDA2NCwicGF0aCI6Ii8xMzk3ODExOS8yODc1NDU2MzgtYjQ5YjkxNTQtYzY3ZS00MDZjLTgyOWUtNTRkY2ExYjY1MGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDIwMDc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MjgyNDc3YWQwMTIyMTMwODdhNDI3ZTFkMDdiMDJmYzQzM2RlZGUxY2MyNTFiMmZiYzYwODIxY2RjMmIyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sIVpiE63X5S4l0nbWsEuzFtJy3mk1Y7gCT3CrMoGjOk) Does this mean that if I choose 7.1 even if physically my system is 5.1 then the "missing channels" (Rear Right/Left) are duplicated to the surround speakers (Side Right/Left)?
> 
> > If you don't have a 7.1 system, then you shouldn't pick a 7.1 layout. You're physically missing two channels.
> 
> Yes, but as I said above - they are getting duplicated, right? so I'm not "missing" them if my AV Receiver supports that, right?

You may be confusing all channel audio with surround sound. They are not the same. Surround sound does not duplicate audio fields, it analyzes the audio and tries its best to create discrete audio channels. Try listening to a music video with the surround filter, and you'll see what I mean. The main vocal will come from the center and the orchestral audio will be sent to the surrounding speakers. All channel audio is simply the same sound in every speaker.is that what you want? If yes, you should use the pan filter.

**Comment by richardpl** [comment]
> > there are non-default options for this filter that give a better quality at cost of higher CPU usage
> 
> Throw it at me, I have a good CPU, let me use it to it max usage. Give me the commands to use.
> 

Something like this with maxed focus:

surround=5.1:focus=1:overlap=0.875:win_size=16384:win_func=hann

Caveat: keep win_size power of 2 number (2048, 4096, 8192, 16384), and make overlap [1.0-(1.0/(2^n))] where n is small number (1-4) gives overlaps: (0.5, 0.75, 0.875, 0.9375)

bigger win_size means more detailed extractions of various cues.
bigger win_size means you also need to increase overlap too otherwise you will get worse quality.
By increasing overlap, needed CPU power for filter increases non-linearly.

Note that you need relatively recent ffmpeg version used by mpv for overlap=X option as previous version would give suboptimal results with non-default values.

**Comment by richardpl** [comment]
That huge overlap and huge win_size are not very useful, Just use parameters that I mentioned above. This is not toy product for average joe.

**Comment by richardpl** [comment]
How big is audio delay you are experiencing? MPV should automatically fix this...

**Comment by richardpl** [comment]
Ah, the delay is introduced by filter itself, fixed it in my fork.

**Comment by llyyr** [comment]
> I never heard of librempeg.

Because it didn't exist until 48 hours ago. It's a ffmpeg fork by one of the currently former ffmpeg dev

> how can I do it in the most simple way? (

Patch ffmpeg with https://github.com/librempeg/librempeg/commit/5d2a66861ef6c736545b80ca05732dcb72e84925

**Comment by tramchamploo** [comment]
Anyone knows what the angle parameter is about? Why is it default to 90? I'm using hrtf to sofalize upmixed content. Some hrtf is measured at 270 degree. Is it related?

**Comment by richardpl** [comment]
Not really, angle option makes x/y polar coordinates more distorted (inward (< 90) or outward (>90)) so when angle > 90 it will make more content from stereo channels present in surround channels, back and side left/right and back center channels. Default 90 deg is normal mapping which will make differences normally propagated to all surround channels relatively equally. But default 90 deg is not gonna make big surround channels happy if mixing stereo image is very weak/boring (like almost mono mixing in stereo sound) so that is why this option exist.

**Comment by tramchamploo** [comment]
Thanks for reply. Now I know what the consequence this param has. Can you elaborate more on exact mean of this param and implementation detail? I tried to read source code but dsp is not something I'm good at.

**Comment by richardpl** [comment]
It does not dictate angle for BL/BR from center FC channel. Stereo audio have no angles for BL/BR channels, it just have two source channels.
And this filter just maps stereo field that is created by FL and FR channel so that it copies/scales certain samples in frequency domain to other surround (SL/SR/BL/BR/BC...) channels.
The _angle_ and _focus_ option are there to control how this transform from 2d stereo box is done to other channels, so kind of re-projection.
Also please use _smooth_ option value set to > 0 as it helps get rid of FFT related artifacts like noise tones or other unpleasant distortions.

You can not get from sofalizer/hrtf/binarural back to surround channels or reverse direction without some loss of data at all, this is always lossy process.
