### ISSUE TITLE
where can I download the release version 0.37?

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#13041]
can someone share the release version of mpv 0.37 for windows in the exe? 
otherwise, Shinichiro still won't post a release build, he only has all sorts of builds

**Comment by llyyr** [comment]
The official mpv org doesn't distribute any binaries. You can build it yourself by following https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md

**Comment by kasper93** [comment]
There are CI artifacts here https://github.com/mpv-player/mpv/actions/runs/6948273318 if that is something you want. Else build it yourself. You can fork one of https://github.com/zhongfly/mpv-winbuild or https://github.com/shinchiro/mpv-winbuild-cmake and run it on GHA to create custom build.

Since we don't really provide official stable binaries, you can use whatever is the newest. Proper stable build would require using stable dependencies and in fact no one provides build like that.

**Comment by Dudemanguy** [comment]
The commits that caused the bug you are referring to were not merged until after 0.37.

**Comment by Raza-0007** [comment]
@AdventurerRussia 

You can download shinchiro's 20231122 build. It was released only a few hours after mpv 0.37, and should only have minimal changes from the release build.

https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231122

**Comment by hooke007** [comment]
No, because it contains the bug mentioned above https://github.com/tomasklaen/uosc/issues/811

**Comment by kasper93** [comment]
> No, because it contains the bug mentioned above #12964

False. It doesn't contain the change. It is pure https://github.com/mpv-player/mpv/commit/2a57a6e release tab. Why are you spreading FUD?

**Comment by AdventurerRussia** [comment]
It's a big problem to download the compiled stable version of the new program. ¯\_(ツ)_/¯

**Comment by Tsuchimikado** [comment]
> Shinichiro still won't post a release build

shinchiro released new 0.37.0 version https://sourceforge.net/projects/mpv-player-windows/files/release/

> if you insist on using obsolete software, just switch to any LTS Linux distribution, everything is so "stable" and obsolete

LTS is fine for most people. They do not do programming, software testing, and do not posses critical files which leakage can cause harm in scale of government or industry. You do not need latest software&OS in order to just post kittens in sns and watch movies and listen to music.

**Comment by hooke007** [comment]
shin always uses git deps to build release mpv.
It could be unstable.

**Comment by Raza-0007** [comment]
@Tsuchimikado 

I agree with you and I also prefer a stable build over daily builds, but I found out after some research, that with how mpv is compiled, it is impossible to get a release build, unless someone complies it immediately after release. 

The reason is that even if mpv's code is fixed at that point in time, the various packages that make up the release are still updating. So for example, the Sourceforge link you posted of shinchiro's release build of 0.37, that he compiled on the 2023-12-10, will have the mpv 0.37's source code from its release date of 2023-11-22, but all the other packages that make up the Window's build will have a more recent build version. 

See the list of packages that make up shinchiro's Window's build and their most recent updates here: https://github.com/zhongfly/mpv-winbuild#information-about-packages

So, if you are looking for a close-to-real release build of mpv 0.37, where the dependent packages are also more or less the same as on the release date, then use shinchiro's 2023-11-22 release, that I linked in my previous post. It was complied only a few hours after mpv 0.37 was released.

~Raza

**Comment by kasper93** [comment]
> LTS is fine for most people.

There is no mpv LTS. Only latest stable version is supported. LTS means a version that is long lived and possibly have backported fixes to it while new stable releases are introducing new features.

> shinchiro released new 0.37.0 version

Like others pointed out. Those builds use all dependencies versions from repository HEAD at the time of build. Even the toolchain that is used to build everything is not stable version. The mpv code in this case is the least of a problem if you want "stable" build.

You have to options:
A) build yourself everything with selected stable revisions of each dependency. At least mpv/ffmpeg/libass/libplacebo.
B) use MSYS version which has most packages build at stable versions (with exceptions), just like your ordinary linux distribution.

Frankly I wouldn't stress much about that, just get a current version (this stable build is fine) and call it stable. It is only mpv, it is not like you are hosting mission critical services on it. No one is forcing you to update, use whatever works for you. There is nothing magic about mpv stable version, it is just some point in time.

**Comment by AdventurerRussia** [comment]
> > Shinichiro still won't post a release build
> 
> shinchiro released new 0.37.0 version https://sourceforge.net/projects/mpv-player-windows/files/release/
> 
> > if you insist on using obsolete software, just switch to any LTS Linux distribution, everything is so "stable" and obsolete
> 
> LTS is fine for most people. They do not do programming, software testing, and do not posses critical files which leakage can cause harm in scale of government or industry. You do not need latest software&OS in order to just post kittens in sns and watch movies and listen to music.

yes, I've already updated to it, I've just been using the player for a couple of years and noticed all sorts of bugs on weekly builds many times, so I choose the stable version, I'm not interested in the package versions, since the bugs were not related to them.

**Comment by hooke007** [comment]
>I'm not interested in the package versions, since the bugs were not related to them.

A one-sided view.
The tag of issues of upstream is not a liar.
