### ISSUE TITLE
Which mpv builds are most stable?

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#13054]
I released a stable mpv.net version mid August, packaging and submitting an app to the MS store is complicated and difficult, I've not automated this task and don't know how well it can be automated. I didn't have much luck because I used a new random libmpv build which had a serious bug, because of that I need to make a new stable release soon, should have done so much earlier. How can I choose a build that is relative stable?

**Comment by kasper93** [comment]
> How can I choose a build that is relative stable?

It is in the name, the most stable release is stable release. It undergoes extensive adaptation and testing because it is used in packages and as a dependency in projects like yours. However, depending on the release cycle, even a stable build can have bugs or limitations. Remember, mpv is provided 'as-is' without any warranty. As an integrator, it's your responsibility to ensure that the build works well in your specific use case. If there are critical issues that necessitate a point release, this can be arranged. In all other cases, I would recommend using the current stable version, possibly with backported patches if necessary.

Using a random HEAD version is feasible only if you can update it rapidly. This approach is currently used on Windows, where there isn't even a stable release build provided by anyone. Instead, there are daily/weekly builds that users can choose from.

The  mpv-player org does not provide packages for any platform; it's a community effort.

**Comment by stax76** [comment]
@kasper93 Thank you for this helpful answer.
