### ISSUE TITLE
Regression: don't clear the timestamp when exiting

### ISSUE THREAD

**Issue by markozajc** [mpv-player/mpv#13092]
### Important Information

Provide following Information:
- mpv version: 0.37.0
- Linux Distribution and Version: Debian Trixie
- Source of the mpv binary: Debian Trixie's main repository and built from source
- If known which version of mpv introduced the problem: 0.37.0, first bad commit is 24270b8587ab466598cc351a85e219e59ff05561
- Window Manager and version: N/A
- GPU model, driver and version: N/A
- Possible screenshot or video of visual glitches
- Terminal emulator: Konsole (yakuake), xterm

### Reproduction steps
1) Open a media file. Both AO, VO, and AV files cause the issue. mpv must be run from the terminal
2) Quit mpv either through ^C, by closing the window, by pressing q, or by waiting for playback to finish - it doesn't seem to matter
3) Observe mpv's output on the terminal

### Expected behavior
mpv leaves the timestamp line (`AV: **:**:** / **:**:** (**%)`) intact and writes the exit message (`Exiting... (Quit)`) on a separate line.

```
$ mpv file.mp4
 (+) Video --vid=1 (*) (...)
 (+) Audio --aid=1 (*) (...)
AO: [pulse] ...
VO: [gpu] ...
AV: 00:00:00 / 00:00:00 (0%) A-V:  0.000

Exiting... (Quit)
$
```
This makes it much easier to resume playback at the exact position in case of a crash (I do use a nvidia gpu after all) or if I close mpv.

### Actual behavior
mpv replaces the timestamp line with the exit message.
```
$ mpv file.mp4
 (+) Video --vid=1 (*) (...)
 (+) Audio --aid=1 (*) (...)
AO: [pulse] ...
VO: [gpu] ...
Exiting... (Quit)
$
```

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/13666590/output.txt)

**Comment by guidocella** [comment]
mpv already has `quit-watch-later` / `--save-position-for-quit` for remembering the position without manual intervention. If your mpv crashes often, just fix your system or use https://gist.github.com/CyberShadow/2f71a97fb85ed42146f6d9f522bc34ef to periodically save the position.

**Comment by markozajc** [comment]
Would it be possible to re-add this feature anyways? I don't suppose leaving the timestamp intact causes any issues, and I've found it very useful and straightforward.

**Comment by guidocella** [comment]
According to https://github.com/mpv-player/mpv/pull/12604#issuecomment-1776087074 it doesn't fit the new msg.c code.

**Comment by markozajc** [comment]
That's a shame.

**Comment by markozajc** [comment]
While trying to write a script to print the position, I accidentally managed to get mpv to preserve the playback position line by writing a newline to stdout:
```lua
local mp = require 'mp'

local function end_file(data)
	io.write("\n")
end
mp.register_event("end-file", end_file)
```
I suppose this is mostly a fluke, but I'll take it for now. It'd still be great if mpv supported that officially, though.

**Comment by kasper93** [comment]
> According to https://github.com/mpv-player/mpv/pull/12604#issuecomment-1776087074 it doesn't fit the new msg.c code.

Just to explain myself, there is nothing limiting about the code itself. It is a design decision to keep the status line only at the bottom of the terminal scrollback and clear it whenever there is new data to be printed. This fixes spam that was previously made as each statusline were kept, short example of per each frame statusline https://0x0.st/H4tF.txt

You have to remember that statusline is not only a timestamp. It can contain subtitles, stats.lua, console.lua, other things... it can be quite a few lines and leaving it persistent is not a good idea.

The status line had already been cleared upon exit, and the one (or multiple ones) that was present was an artifact of keeping all of them in the scrollback.

The status line is not a good tool for what you want to achieve. We can of course add a events when status line would leak, but it is not consistent and I would rather add `--exit-msg=...` if that's what users want. 

> This makes it much easier to resume playback at the exact position in case of a crash (I do use a nvidia gpu after all) 

If mpv crashes the status line will not be cleared, because we already crashed.

> or if I close mpv.

If you close mpv already has automatic way to restore playback position/state. `quit-watch-later` / `--save-position-for-quit` like @guidocella said. Do you really manually seek to position from terminal after reopening mpv? Seems tedious and unnecessary.

Do you have some better use-case that would warrant keeping status line or timestamp on exit?

**Comment by markozajc** [comment]
Thanks for taking time to explain the rationale behind this.

> If mpv crashes the status line will not be cleared, because we already crashed.

It doesn't crash per-se, but after resuming from sleep while using hardware decode it prints a few NVDEC errors and exits. Sleeping also breaks network streams sometimes, in which case mpv thinks it's EOF and exits. None of these are really problematic to me because resuming playback is fast.

> Do you really manually seek to position from terminal after reopening mpv? Seems tedious and unnecessary.

My current workflow is binding `ctrl+t script-message-to console type "set time-pos "` and then typing in the timestamp if I want to resume. I've found this to be efficient enough for me, and I'd still rather handle the seeking part myself.

> Do you have some better use-case that would warrant keeping status line or timestamp on exit?

Nope, this is the only reason I need it, but it's important enough that I've noticed it within days of getting the update.
