### ISSUE TITLE
The reddish screen in mpv with --vo=dmabuf-wayland  --hwdec=vaapi on AMD Radeon RX560

### ISSUE THREAD

**Issue by mixmid** [mpv-player/mpv#13098]
### Important Information

Provide following Information:
- mpv version: mpv 0.37.0
- Linux Distribution and Version: Fedora Rawhide(pre-40)
- Source of the mpv binary: from Fedora's repository
- Window Manager and version: Sway-1.8.1
- GPU model, driver and version: AMD Radeon RX560, Mesa 23.3.0 -- last version
- Possible screenshot or video of visual glitches

![screen](https://github.com/mpv-player/mpv/assets/10143940/c8e1f0ee-7c0d-460f-8e67-d5c5a25e4ed7)

### Reproduction steps
The issue is only on AMD, possibly on RX560/580 series. I have seen simular issues, but not in Wayland context.

```
$ mpv --vo=dmabuf-wayland  --hwdec=vaapi Samsung-and-RedBull-See-the-Unexpected-HDR-UHD-4K-\(www.demolandia.net\).ts\ \[712764913\].mp4 
 (+) Video --vid=1 (*) (hevc 3840x2160 59.940fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
Cannot load libcuda.so.1
Using hardware decoding (vaapi).
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [dmabuf-wayland] 3840x2160 vaapi[p010]
(Paused) AV: 00:00:05 / 00:03:17 (3%) A-V:  0.000
```
### Expected behavor
Normal video output

### Actual behavior
Reddish video output

### Log file
[red_dmabuf.txt](https://github.com/mpv-player/mpv/files/13682709/red_dmabuf.txt)

Probably useful output from drm_info
[drminfo.txt](https://github.com/mpv-player/mpv/files/13682766/drminfo.txt)

### Sample files
The reddish output happens on both HDR and SDR files with --vo=dmabuf-wayland --hwdec=vaapi.

**Comment by mixmid** [comment]
I guess so. --vf=format=fmt=bgra also kills picture colors and hardware acceleration goes off. But the way, thanks.

**Comment by Dudemanguy** [comment]
Yeah because of the additional format conversions hardware decoding won't work. I typed `--hwdec=vaapi` out of habit but you don't really need it since all that happens is that the format gets downloaded from vaapi before getting converted. As for the colors thing, it's just because your file is HDR. The compositor supports p010 which is what you want here, but none of the formats your gpu supports are suitable so the conversion is probably not great. You could maybe in theory insert an additional libplacebo filter or such but I'm not sure.

**Comment by mixmid** [comment]
Close the ticket.

**Comment by philipl** [comment]
On Intel hardware you can use the `tonemap_vaapi` filter to get the hardware to do the conversion for you. But, of course, AMD don't implement this part of vaapi.
