### ISSUE TITLE
JS script support assdraw

### ISSUE THREAD

**Issue by ahaoboy** [mpv-player/mpv#13100]
### Expected behavior of the wanted feature
The current JavaScript script doesn't support 'assdraw'. I hope it can also be used in JavaScript like in Lua. 
```js
var assdraw = mp.assdraw
var ass = assdraw.ass_new()
```

**Comment by avih** [comment]
`assdraw` is an unofficial and undocumented module, written for and used by the OSC, and is subject to change at any time. Your lua scripts should not rely on it, unless you vendor your own copy which is guaranteed to not change over time.

A JS implementation in mpv doesn't exist because there's no other JS code which needs it. There are no plans to implement it either.

That being said, `assdraw` is fairly simple, and I'm sure you can come up with a similar or identical module which you'd write yourself in JS, maybe based on the lua code, and then you can add it to the [user scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) wiki page, so that others can use it too.

If you do, you can add a comment here.

**Comment by Kagami** [comment]
I ported it: https://github.com/Kagami/mpv-assdraw

**Comment by ahaoboy** [comment]
Another assdraw library [@mpv-easy/assdraw](https://github.com/mpv-easy/mpv-easy/tree/main/mpv-assdraw), with chainable and some common color utility functions.
```ts
import { AssDraw } from '@mpv-easy/assdraw'

new AssDraw().blueText("hello ").redText("world").toString()
```
