### ISSUE TITLE
Script function create_osd_overlay's return value lacks two properties: compute_bounds and hidden.

### ISSUE THREAD

**Issue by ahaoboy** [mpv-player/mpv#13116]
## The object returned by the JS and Lua script function create_osd_overlay lacks two properties: compute_bounds and hidden.

```js
format: format || "ass-events",
id: next_assid++,
data: "",
res_x: 0,
res_y: 720,
z: 0,

```
The complete definition is as follows, perhaps the script code was forgotten to be updated after adding them?

```lua
{"id", OPT_INT64(v.i64)},
{"format", OPT_CHOICE(v.i, {"none", 0}, {"ass-events", 1})},
{"data", OPT_STRING(v.s)},
{"res_x", OPT_INT(v.i), OPTDEF_INT(0)},
{"res_y", OPT_INT(v.i), OPTDEF_INT(720)},
{"z", OPT_INT(v.i), OPTDEF_INT(0)},
{"hidden", OPT_BOOL(v.b), OPTDEF_INT(0)},
{"compute_bounds", OPT_BOOL(v.b), OPTDEF_INT(0)},
```

**Comment by CogentRedTester** [comment]
Does this actually cause any issues? Presumably it's falling back to the defaults since those fields aren't being explicitly set, I assume you can manually set a value for those properties and they work?

**Comment by ahaoboy** [comment]
> Does this actually cause any issues? Presumably it's falling back to the defaults since those fields aren't being explicitly set, I assume you can manually set a value for those properties and they work?


 
This will require special handling of these two properties when using TypeScript, such as having to check for their existence before usage. This is unnecessary and, while not a major issue, it seems a bit odd.
 
```ts 
export interface OSDOverlay {
  data: string
  res_x: number
  res_y: number
  z: number
  hidden?: boolean
  compute_bounds?: boolean
  update(): {} | { x0: number; y0: number; x1: number; y1: number }
  remove(): any
}
```

**Comment by avih** [comment]
> seems a bit odd.

The philosophy here is minimalism, so it only sets fields which are otherwise non trivial. This also reduces the maintenance effort of `defaults.js`.

The user can add any fields which are documented for the wrapped mpv command.

Discoverability, while useful, is not an explicit goal.

Also, it's been 3 years and many mpv versions since compute bounds was added, so it can probably be assumed to exist, and if an older mpv is used, then an appropriate error is indicated for unsupported field.

Closing also #13127 for the same reason.
