### ISSUE TITLE
print chapter title once reached

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#13118]
I've noticed that there's no visual indication in mpv when the video reached a new chapter,
this feature could be useful for users who want to know when a new chapter started and what the title of this chapter is,
an example would be when playing a YouTube video in which there are ordered chapters,
users normally play a video and won't touch the keyboard and mouse,
and in order to view the chapter name the users would have to interact with the UI,
I believe this feature request is achievable using `lua` scripts, in which I would prefer it to be an option inside `osc.lua` rather then creating a custom user script for this specific request.

**Comment by N-R-K** [comment]
> there's no visual indication in mpv when the video reached a new chapter

That seems pretty normal. Do you have any player in mind that does otherwise?

> this feature could be useful for users who want to know when a new chapter started and what the title of this chapter is

I don't think I remember the last time I wanted to be "alerted" when a new chapter started. You give youtube videos as an example, but even the youtube UI (afaik) doesn't do anything like this.

Seems like an intrusive (mis)feature. So if it is added, it should be disabled by default.

**Comment by sfan5** [comment]
Use a script:
```lua
mp.observe_property("chapter", "native", function(_, n)
	local title = mp.get_property_native("chapter-list/"..tostring(n).."/title")
	if title == nil or string.find(title, "://") ~= nil then return end
	mp.commandv("show-text", string.format("Chapter: (%d) %s", n+1, title))
end)
```
