### ISSUE TITLE
How to read and write binary files in a JS script

### ISSUE THREAD

**Issue by ahaoboy** [mpv-player/mpv#13149]
The write_file and read_file provided by mpv are both in string format. However, some scenarios require the ability to read and write binary files, such as preventing users from missing fonts. During runtime detection, if fonts are absent, it's necessary to write uint8 number arrays into the 'fonts' directory. Additionally, for some cross-platform enhanced capabilities like clipboard operations and use command_native for invocation.
How to do this?
```js
var bytes = [1, 2, 3]

mp.utils.write_binary("test.ttf")
```

**Comment by avih** [comment]
ES5.1 doesn't support byte arrays, and so mujs doesn't support it either. There are no workarounds to use binary blobs in JS scripts in mpv.

As documented, the interactions of JS scripts with the system, other than via mpv commands, is limited to few additional utils (like `write_file` etc), and there's no standard libray, neither in ES5.1 nor in mujs, nor in JS scripts in mpv.

There is more missing system integration functionality (like copying files, or deleting files, and much more), but there are no plans currently to add more system integration support for JS scripts.

If one needs better system integration, then they should use lua, which does have builtin modules to work with the system, and is outside the control of mpv.

That being said, for things mentioned like binary clipboard integration, even if there was binary blob support in JS - it wouldn't work either without external utils which work with the clipboard. Such utils (possibly combined with some more utils) could be used to encode/decode binary blobs, e.g. using base64 or some such, which can then be processed in JS scripts, though it's probably better to work directly with files at this stage (e.g. by running temporary shell scripts) rather than using binary blobs in scripts.

**Comment by ahaoboy** [comment]
> ES5.1 doesn't support byte arrays

Just need support for regular number arrays, At runtime, ensure that all numbers in the array range from 0 to 255.

> If one needs better system integration, then they should use lua

Compared to JavaScript, Lua indeed has more functionality, which might be one of the reasons why Lua scripts are far more prevalent than JavaScript scripts.

> e.g. by running temporary shell scripts

Currently, this seems to be the most feasible solution, requiring only adaptation of shell scripts for different platforms.


> but there are no plans currently to add more system integration support for JS scripts.

We might want to actively embrace JS developers as the web remains more popular than Lua, with excellent tooling and library support. As a web developer myself, I've been experimenting with introducing React into MPV. Compared to JS-ES5 and Lua, TSX seems better suited for expressing interfaces. There are many mature solutions and libraries available as references. For instance, using chained operations to draw basic graphics seems more semantically appropriate than Lua.

Currently, I'm developing with TypeScript. It's a common practice to transpile to JavaScript after packaging, and modular support is excellent. It's easy to encapsulate some commonly used libraries:

For example, drawing a rectangle:

```js
export function drawRect({ x, y, color = COLORS.black, width, height, alpha = 0 }) {
    return new AssDraw().color(color).alpha(alpha).drawStart().pos(x, y).rectCw(0, 0, width, height).toString();
}

```
And implementing a play button using TSX:
![动画1](https://github.com/mpv-player/mpv/assets/19884146/20af929e-9b3a-48a2-af91-e932f19437a2)

```tsx
function PlayButton() {
  const [pause, setPause] = usePause();
  return <Icon
    color={COLORS.white}
    bgColor={COLORS.black}
    text={
      new AssDraw().font('FiraCode Nerd Font Reg').append(pause ? ICON.play : ICON.pause)
    }
    onMouseDown={() => {
      setPause(!pause);

    }}
  ></Icon>
}

```
