### ISSUE TITLE
Click the right mouse button on Windows Terminal will automatically trigger many keys

### ISSUE THREAD

**Issue by verygoodlee** [mpv-player/mpv#13199]
### Important Information
Provide following Information:
- mpv version
```
mpv v0.37.0-135-gabc2a748 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Dec 30 2023 00:56:22
libplacebo version: v6.338.0-62-g52314e0-dirty
FFmpeg version: N-113168-gb95ee2ec5
FFmpeg library versions:
   libavutil       58.36.100
   libavcodec      60.36.100
   libavformat     60.20.100
   libswscale      7.6.100
   libavfilter     9.16.100
   libswresample   4.13.100
```
- Windows Version
Win10 22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240101

### Reproduction steps
1. Run `mpv "any.mp4" --no-config --log-file=log.txt` in Windows Terminal
2. Wait for the mpv window to appear
3. Click the right mouse button on Windows Terminal

### Expected behavior
N/A

### Actual behavior
Automatically trigger many keys
![test.gif](https://github.com/mpv-player/mpv/assets/45035465/486b0942-396a-408a-9937-88018b5af550)

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/13802803/log.txt)

**Comment by natural-harmonia-gropius** [comment]
right click is paste.

**Comment by verygoodlee** [comment]
> right click is paste.

Yes, that's the reason, but it is very easy to accidentally trigger, it's best to have a way to avoid it.

**Comment by butterw** [comment]
This is actually quite annoying, if there is any way to fix it it would be welcome.
It also happens if you press CTRL+V (Paste), when the terminal has focus.

**Comment by llyyr** [comment]
`--no-terminal`

**Comment by butterw** [comment]
The terminal output including the term-status-msg line is wanted (otherwise just use mpv.exe on windows). What is not wanted is automatic execution when you accidentally paste.

**Comment by llyyr** [comment]
> you accidentally paste

Don't accidentally paste, instead remap your terminal bindings so that right click is not bound to paste.

**Comment by Hrxn** [comment]
Well, this is expected behavior, I'd say.

Because is basically works like this:
Any key input is first received* by the terminal (Windows Terminal in this case), and if it finds a bound action in its config, it will execute that. You'd need to disable the specific key bind, so the input gets "forwarded" to the application.

*: By the OS first, actually. Hence why you cannot modify the common Windows key shortcuts (`Win+E`, etc. ..)

Easy enough to change/disable keybindings in the `settings.conf`:
https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#unbind-keys-disable-keybindings

Caveat: I don't know if this actually applies to the right mouse button as well.

Better not actually paste, I don't even know how this is a thing, to be honest.

>This is actually quite annoying, if there is any way to fix it it would be welcome.
It also happens if you press CTRL+V (Paste), when the terminal has focus.

I mean, no way around that. `Ctrl+V` is paste when the terminal has focus, as it should be.

> The terminal output including the term-status-msg line is wanted (otherwise just use mpv.exe on windows). What is not wanted is automatic execution when you accidentally paste.

I see what you mean, though. A trailing `CRLF` or even just `LF` triggers execution of what has been pasted from Clipboard. But I think this is an issue of the "new" Windows Terminal. Definitely not an mpv issue.

If you want, try the same paste/clipboard content with the classic `conhost.exe`, this should not be an issue there, as far as I know!

**Comment by butterw** [comment]
`--no-input-terminal`
should solve the problem. It prevents the player from reading key events from standard input.

**Comment by verygoodlee** [comment]
> `--no-input-terminal` should solve the problem. It prevents the player from reading key events from standard input.

Nice, perfect solution
