### ISSUE TITLE
Change default value of --ytdl-format to include DASH

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#1321]
I would like to suggest switching the default value of --ytdl-format from what we use currently (nothing, which falls back to youtube-dl's default of “best” - which might be worth documenting, incidentally) to the value “bestvideo+bestaudio/best”.

The reason youtube-dl ignores stuff like DASH by default is because it's a tool designed to download the files, and using bestvideo+bestaudio forces it to download first the entire video, then the entire audio, then mux them together using ffmpeg. This problem does not apply to us since we just directly stream either way.

The difference this would make is that it would effectively enable DASH video/audio for youtube, giving casual users of mpv easy access to 1080p videos by default, which would be an actual serious advantage over quvi.

The drawbacks are that DASH support is currently suboptimal w.r.t duration due to bugs in ffmpeg, so I would expect at least a quick client-side workaround that lets us display, if nothing else, an accurate progress bar on the OSD.

Whether this specific proposal gets granted or denied, it would be a good idea to add more documentation about this parameter. For example, it doesn't mention the special formats “bestvideo” and “bestaudio” (which will include DASH formats), nor the operator “a+b” for effectively playing two streams at the same time, nor the operator “/” for falling back to different versions.

**Comment by wiiaboo** [comment]
You could add an additional option to be able to use youtube-dl's "--max-quality" and set that to 137  (1080p30).
As I have limited bandwidth, I can barely handle 1080p30 streamed, but I like watching some gameplay at 1080p60 if available so I set youtube-dl.conf with "--max-quality 137" and whenever I want to download something to watch later, I use "--max-quality 299" as arg so I get 1080p60 to watch at leisure.

**Comment by ChrisK2** [comment]
Just put ``ytdl-format=137/best`` in your mpv.conf

**Comment by haasn** [comment]
Wouldn't that need to be 137+bestaudio/best? Also, that's not fully the same thing as --max-quality, because this wouldn't pick up 720p60 for instance.

**Comment by wiiaboo** [comment]
Like with this [video](https://www.youtube.com/watch?v=byoLvAo9qjs), for example.

**Comment by zsero** [comment]
A couple of points:
- For a strange reason video inside 22 is higher quality version then 136
```
  Duration: 00:04:13.92, start: 0.033000, bitrate: 1934 kb/s
    Stream #0:0(und): Video: h264 (Main), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc (default)
```
vs.
```
  Duration: 00:04:13.89, start: 0.000000, bitrate: 2675 kb/s
    Stream #0:0(und): Video: h264 (High), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc (default)
```

- I am using the following DASH quality string (as in https://github.com/mpv-player/mpv/issues/1450), and it works perfectly with youtube-dl (it automatically picks the best one):
```
youtube_dash_video_formats="138/266/264/137/136/22/135/134/133"
youtube_dash_audio_formats="141/172/140/171/139"
```

- I guess 298 should be inserted between 137 and 136 for 720p/60.

- I guess there is no point of downloading a higher quality stream then the display's resolution, so the best possible solution would be to limit youtube_dash_video_formats to start with the current resolution's format (like 137 for FullHD displays).

**Comment by wiiaboo** [comment]
I personally went with using
```
-f 299+bestaudio/137+bestaudio/298+bestaudio/22/135+bestaudio/18/best
```
on youtube-dl.conf (for downloads) and
```
ytdl-format=137+bestaudio/298+bestaudio/22/135+bestaudio/18/best
```
on mpv/config

**Comment by zsero** [comment]
Here is a list of all youtube-dl formats:
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py

So far I believe this is the most complete list of video formats in descending resolution order:
"138/266/264/299/137/298/22/136/135/134/133"

**Comment by rrooij** [comment]
Isn't DASH enabled by default now in youtube-dl with 'best' as format?

**Comment by wiiaboo** [comment]
youtube-dl changed defaults to "bestvideo+bestaudio/best". Since mp4 dash videos still aren't fully supported, the defaults in mpv were changed to just "best".

**Comment by wm4** [comment]
At least the ffmpeg mp4 demuxer needs to be fixed before we can do this.

**Comment by SteveJobzniak** [comment]
Nonono. Don't specify YouTube format codecs individually!

This is a more advanced way: It picks the best format up to 1080p, chooses 30fps or lower (since 60fps just leads to dropped frames and stutter on my computer), and lastly it also ignores the stupid VP9 codec.

`ytdl-format=bestvideo[height<=?1080][fps<=?30][vcodec!=vp9]+bestaudio/best`

**Comment by tp0** [comment]
That's a pretty good config for most people, except for that fps part (you have to pretty old computer or your GPU acceleration isn't working properly if you can't play 60 fps even in H264?).

Also, at least for me H264 is preferred, so that `[vcodec!=vp9]` is not needed. Or then depends on GPU decoding features.

For _live_ stream videos, 60 fps isn't supported by youtube-dl and Youtube itself doesn't support higher than 1080p for live streaming.

**Comment by SteveJobzniak** [comment]
@tp0 Yeah I run with software-based CPU decoding on a 6-year old Core i7, where 60 fps @ 1080p leads to dropped frames and stutter. I could use GPU decoding but then I'd miss out on many mpv filters.

Many people with older computers would want the fps options. Others would want to remove it. Just take out the [fps<=?30] part.

As for H264 being preferred by default: Nope. Look at https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py (search for the word "vp9"). The "preference" strength of vp9 and h264 is identical, so it might possibly pick a vp9 stream if one is listed earlier in the metadata for a video. I don't know if they've got any more code to prefer h264 over vp9 in there, but it really doesn't look like it to me. So that is why I blocked out vp9 just to be sure. Because I hate that dumb, CPU-inefficient and ugly-looking codec. All the best looking encoders and most efficient software decoders are written for H264.

**Comment by lachs0r** [comment]
> I run with software-based CPU decoding on a 6-year old Core i7, where 60 fps @ 1080p leads to dropped frames and stutter.

I really don’t believe this is your CPU’s fault, especially not with YouTube’s streams, unless you’re doing some sort of unreasonable filtering. After all, a Phenom II manages fine, at least for H.264 (never tried VP9 on that particular machine, but I agree that it’s pretty crappy). Also, you can use GPU decoding with filters by using one of the `-copy` hwdecs. I wonder why you would use “many” filters though.

**Comment by MingMingNYC** [comment]
In my case vp9 was picked by default. SteveJobzniak's solution solved the problem.

**Comment by prog-amateur** [comment]
Hello, thanks to all for sharing the solution. I have a similar issue but the phenomenon is different : 
My current config is : 
`ytdl-format=bestvideo[height<=?1080]+bestaudio/best`
When I check the below movie, it works very well : 
https://www.youtube.com/watch?v=1Oku4KXWnuI

But with this movie, the video is lagging a lot and the audio is totally not synchronized : 
https://www.youtube.com/watch?v=42qZTdwY1eM

So I have changed my config file into : 
`ytdl-format=bestvideo[height<=?1080][vcodec!=?vp9]+bestaudio/best`

After this setting, the second video runs better, but is still lagging a bit with no sync between audio/video. 

So I have changed my config file into : 
`ytdl-format=bestvideo[height<=?1080][fps<=?30][vcodec!=?vp9]+bestaudio/best`

Now, both video run perfectly. I guess the solution was to pass the vp9 codec into 30fps. 
My question is, I would like to set up 2 parameters : 

1. When the movie is not vp9, I want to keep 60 fps : 
`ytdl-format=bestvideo[height<=?1080]+bestaudio/best`
2. And when it is vp9, I want : 
`ytdl-format=bestvideo[height<=?1080][fps<=?30][vcodec!=?vp9]+bestaudio/best`

How to set up such condition please ? Thank you !

**Comment by mrkapqa** [comment]
Hello ,

i would like to prefer vp9 over mp4, how could i achieve that (withouth excluding mp4)?
