### ISSUE TITLE
[ffmpeg/video] libopenh264: [OpenH264] this = 0x0x55a455193380, Warning:SPS ID can not be supported!

### ISSUE THREAD

**Issue by philiprhoades** [mpv-player/mpv#13236]
- mpv version
mpv-0.36.0-3.fc39.x86_64

- Linux Distribution and Version
Fedora 39

- Source of the mpv binary
-Fedora

- If known which version of mpv introduced the problem
- Window Manager and version
Sway

### Reproduction steps
mpv 

### Log file
Attached.
[t.log](https://github.com/mpv-player/mpv/files/13848778/t.log)

### Sample files
https://github.com/mpv-player/mpv/assets/1153703/e34f19ef-4b4f-45fa-a184-e9144e7bf73c

**Comment by CounterPillow** [comment]
The error is from libopenh264, this doesn't look like an mpv issue at all.

The only reason why your build uses libopenh264 in the first place is for legal reasons. I recommend compiling an up-to-date mpv against an up-to-date ffmpeg from source without using the openh264 patent workaround library but just the regular H.264 decoder, using e.g. [mpv-build](https://github.com/mpv-player/mpv-build/).

Alternatively, ask Red Hat's legal department to fix this bug since they're the ones who exposed you to it.

**Comment by philiprhoades** [comment]
@CounterPillow ,

Thanks for that! - I will check out mpv-build.
