### ISSUE TITLE
A current list of whats inside each mpv profile for reference

### ISSUE THREAD

**Issue by Raza-0007** [mpv-player/mpv#13257]
I was recently helping someone with an issue with video playback and I suggested they use `profile=fast`. I was going to reference the differences between the fast, default and high-quality profiles, when I could not find any link where the current options for each profile are listed. 

This [builtin.conf](https://github.com/mpv-player/mpv/blob/master/etc/builtin.conf) lists the options contained within the fast profile only. The high-quality profile is not complete, and only lists the differences from the default profile. The default profile options are completely missing.  

The command `--show-profile` also does not list whats inside the default profile. But in any case, one cannot ask someone who lets say is a non tech newbie to run such commands. 

Shouldn't there be a page or link that one can use for reference that contains the current details of each profile? Maybe this [builtin.conf](https://github.com/mpv-player/mpv/blob/master/etc/builtin.conf) should be modified to include whats in each profile?

Thanks,

~Raza

**Comment by hooke007** [comment]
> The default profile options are completely missing.

default profile is empty

**Comment by Raza-0007** [comment]
But my question was that shouldn't there be a page (mpv manual) or link where whats contained within each profile is listed, so one can use that as a reference, to compare and choose between profiles? 

Since the options within each profile change periodically, depending on community consensus, that page and link should be updated periodically as well to reflect these changes, so one can use it as a reference source.

**Comment by hooke007** [comment]
But you have checked builtin.conf, what else do you need?

**Comment by Raza-0007** [comment]
And how would you compare, contrast and choose between the fast, default and high-quality profiles based on the information provided on that page?

**Comment by hooke007** [comment]
Read the manual first and know what each option would do.
I do not understand the issue here.

**Comment by Raza-0007** [comment]
I was asking for something like [this](https://github.com/mpv-player/mpv/commit/703f1588803eaa428e09c0e5547b26c0fff476a7)

Here you can clearly see and compare whats inside each profile and choose accordingly. But this information is out-of-date. I was asking for something similar that is kept up-to-date for reference.

**Comment by hooke007** [comment]
But that is not accurate. You were mislead. As I said, "default profile is empty"

**Comment by CounterPillow** [comment]
> The command `--show-profile` also does not list whats inside the default profile. But in any case, one cannot ask someone who lets say is a non tech newbie to run such commands.

Windows support was a mistake.

**Comment by butterw** [comment]
As stated the default profile is empty, what you want to know is what mpv default option values are. You'll find most listed in the manual and for non tech newbies with --list-options, but ultimately the answer is in the code. Because sometimes the values themselves are not all that helpful (ex: the default cscale value is empty, meaning scale is used for cscale by default).
vo default is empty, but the manual states in #video-output-drivers: "The recommended output driver is --vo=gpu, which is the default." You would also need to check out what ```auto``` actually means for each individual option.

main defaults in mpv v0.37 (AFAIK)
scale/cscale/dscale: lanczos/lanczos/hermite
dither-depth=auto
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes

from [builtin.conf](https://github.com/mpv-player/mpv/blob/master/etc/builtin.conf)
[fast]
scale=bilinear
dscale=bilinear
dither=no
correct-downscaling=no
linear-downscaling=no
sigmoid-upscaling=no
hdr-compute-peak=no
allow-delayed-peak-detect=yes

[high-quality]
scale=ewa_lanczossharp
hdr-peak-percentile=99.995
hdr-contrast-recovery=0.30
deband=yes

**Comment by Raza-0007** [comment]
I am well aware that default is not a profile, it is whats on by default. But when you have two established profiles and the defaults, there should be a document listing the differences between them; so it can be used as a reference, and help somebody like me, who does not use profiles, but uses the individual parameters in their config. But I guess I am in a minority here.

So from the information provided by @butterw above and from [here](https://github.com/mpv-player/mpv/blob/master/etc/builtin.conf) and [here](https://github.com/mpv-player/mpv/commit/703f1588803eaa428e09c0e5547b26c0fff476a7)

And I am assuming that [this](https://github.com/mpv-player/mpv/pull/13172) has not been merged yet but will soon be.

As of January 10, 2024. The main differences between the three profiles are as follows: Am I correct?

**Fast Profile**

scale=bilinear
dscale=bilinear
dither=no
correct-downscaling=no
linear-downscaling=no
sigmoid-upscaling=no
hdr-compute-peak=no
allow-delayed-peak-detect=yes

**On by Default**

scale=lanczos
cscale=lanczos
dscale=hermite
dither-depth=auto
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes
hdr-compute-peak=yes

**High Quality profile**

scale=ewa_lanczossharp
cscale=ewa_lanczossharp 
dscale=hermite
dither-depth=auto
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes
hdr-compute-peak=yes
hdr-peak-percentile=99.995
hdr-contrast-recovery=0.30
allow-delayed-peak-detect=no
deband=yes
