### ISSUE TITLE
Wayland scale with pixels

### ISSUE THREAD

**Issue by plitter** [mpv-player/mpv#13316]
### Important Information

Provide following Information:
- mpv version
```
mpv v0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Dec 19 2023 21:54:02
libplacebo version: v6.338.1
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```
- Linux Distribution and Version
```
 6.7.0-arch3-1 #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000 x86_64 GNU/Linux
```
Arch Linux
- Source of the mpv binary
- If known which version of mpv introduced the problem
- Window Manager and version
```
sway version 1.8.1
```
- GPU model, driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Set monitor to scale 1.5 ala this in `.config/sway/config`
```
output DP-7 {
	scale 1.5
}
```
Then run 
```
mpv --geometry=910 "https://www.
youtube.com/watch?v=K17df81RL9Y&list=RDn2RGleYl5e0&index=27"
```
### Expected behavior
Not to crash because it can't scale. Maybe just choose the closest smaller size? Or closest larger?

### Actual behavior
Crashes.

### Log file
Log file was missing this which I'm assuming is from sway.
```
wl_surface@8: error 2: Buffer size (910x603) is not divisible by scale (2)
[vo/gpu/wayland] Error occurred on the display fd
```
[output.txt](https://github.com/mpv-player/mpv/files/13989946/output.txt)

### Sample files

Sample files needed to reproduce this issue can be attached to the issue
(preferred), or be uploaded to https://0x0.st/ or similar sites.
(Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by llyyr** [comment]
This is a known issue with the Wayland core integer scaling. See discussion here: https://github.com/mpv-player/mpv/issues/10263#issuecomment-1820014666

**Comment by plitter** [comment]
Ok. Thank you :)

**Comment by plitter** [comment]
Ok. Thank you :)

**Comment by llyyr** [comment]
You should reopen this because this is a bug with mpv. I realize now that my initial sentence could be interpreted as it being an issue elsewhere, not with mpv.

In fact, integer scaling worked on mpv but was broken by this commit in preparation for fractional scaling https://github.com/mpv-player/mpv/commit/006ec9ce4357cd198955bc2e56caec34943db52d

**Comment by Dudemanguy** [comment]
In this particular case, the 603 value arises because of truncation (the actual size is 603.8 or something like that). However, there are cases where odd values like this *are* the correct size (such as in #10263) which makes this rather unfortunate.

Before that commit, mpv worked entirely in wayland's logical coordinates so it was able to avoid this particular error mostly by accident since sizes would get silently changed from what the user actually inputted based on however the math worked out. For example, `mpv --no-config --geometry=1215x2160 'av://lavfi:testsrc=duration=2:size=720x1280'` before that commit would actually spawn a window with a size of 1214x2158.

The best solution for this is the fractional scaling protocol which we already use, but I guess a crappy fallback of some sort needs to be added since the wayland protocol does technically have this limitation (although most compositors ignore it I think).

**Comment by llyyr** [comment]
> I guess a crappy fallback of some sort

Can't we just make a 910x604 window for a 910x603 video? Or is this too complicated to do?

**Comment by Dudemanguy** [comment]
>Can't we just make a 910x604 window for a 910x603 video? Or is this too complicated to do?

Yes that was what I had in mind. The only annoying thing is that it needs to be done everywhere where mpv change its size on its own.

>I think at this point it's better to just use viewport for all scaling, whether integer or fractional, and leave the core buffer scale to 1.

The problem with using viewport scaling and a buffer scale of 1 is that it will always use compositor-side scaling if you aren't using the fractional scale trick.

**Comment by Dudemanguy** [comment]
When using the fractional scale protocol, the viewport usage **undos** the compositor side scaling. That's why I called it a "trick". The purpose is to cancel out all compositor mangling of the client's dimensions so that the client can scale everything completely by itself. Using core integer scaling with buffer_scale is also meant to cancel out compositor-side scaling, but of course that has many limitations as everyone knows (hence the fractional scale protocol).

**Comment by Dudemanguy** [comment]
On second thought, I guess maybe I'm wrong the viewport trick works even if the compositor doesn't advertise fractional scaling support. Would need investigation I suppose.

**Comment by plitter** [comment]
Thank you all for the help! I built it and it doesn't crash. There is one thing though, when I run the command above I'm expecting a 910 width window, but what I get is
```
              "rect": {
                "x": 2173,
                "y": 751,
                "width": 455,
                "height": 302
              },
              "deco_rect": {
                "x": 0,
                "y": 0,
                "width": 0,
                "height": 0
              },
              "window_rect": {
                "x": 0,
                "y": 0,
                "width": 455,
                "height": 302
              },
              "geometry": {
                "x": 0,
                "y": 0,
                "width": 455,
                "height": 301
              },
```
I can double my width to get the width I want on my 4k monitor. Which would be 1820. Interestingly it becomes this size when I move it to my fullhd monitor.
```
              "rect": {
                "x": 794,
                "y": 409,
                "width": 910,
                "height": 604
              },
              "deco_rect": {
                "x": 0,
                "y": 0,
                "width": 0,
                "height": 0
              },
              "window_rect": {
                "x": 0,
                "y": 0,
                "width": 910,
                "height": 604
              },
              "geometry": {
                "x": 0,
                "y": 0,
                "width": 910,
                "height": 603
              },
```
I feel like a valid answer here would be that I have to deal with my sizes myself, but is it possible to make mpv disregard scaling? F.ex. if I open a 4k video in floating mode on my 4k screen it is larger than the screen. But I can't imagine that this is wanted behaviour.

**Comment by Dudemanguy** [comment]
What tool is that? I think it's possibly working in logical coordinates since 455 is exactly half of 910. If you look at the stats screen on the mpv window, it will tell you the actual physical resolution.

>is it possible to make mpv disregard scaling?

Depends on what you mean exactly, but there's a `--no-hidpi-window-scale` option which does that.

>F.ex. if I open a 4k video in floating mode on my 4k screen it is larger than the screen. But I can't imagine that this is wanted behaviour.

This is up to the compositor. They usually send us a configure_bounds in this event to lower the size of the window so it stays constrained in the monitor.

**Comment by plitter** [comment]
The tool is what sway is reporting.
```
swaymsg -t get_tree | jq -r 'recurse(.nodes[])' | vim -
```
The `--no-hidpi-window-scale` seems to be working, but it doesn't give the correct size. 1820 should be close to half the screen width,  Another interesting thing happens when it crosses the border to the other screen with the `--no-hidpi-window-scale`

[output-no-hidpi-window-scale.txt](https://github.com/mpv-player/mpv/files/14016137/output-no-hidpi-window-scale.txt)

https://github.com/mpv-player/mpv/assets/904920/78c1b074-259b-4b2a-a2ad-3fc5f13bcfc1

When I search for scale it says 2 and 1, which is weird since my scale is 1.5 in the log output.

**Comment by Dudemanguy** [comment]
Well I guess I should be clear. You were using #13325 right? I just now closed the other PR.

Anyways doing a quick check with that, the swaymsg output indeed doesn't include the scale values in its geometry coordinates so what you are getting is not the actual physical size of the window.

>When I search for scale it says 2 and 1, which is weird since my scale is 1.5 in the log output.

That is because your version of sway doesn't support the fractional scaling protocol. Without it, the compositor can only communicate integer scale values to us. The scale values and coordinates you are going to get will be weird and unintuitive because of this. As far as I can tell, everything is working as intended in your case.
