### ISSUE TITLE
How to control a player through IPC using JS scripts?

### ISSUE THREAD

**Issue by ahaoboy** [mpv-player/mpv#13412]
I have started the server according to the [doc](https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst), and I can control the player to take screenshots through the command line.
```bash
 ./mpv.com ./t.mp4 --log-file=./log.txt --input-ipc-server=mpv_test_001
```

```cmd
echo screenshot-to-file ./tmp.png >\\.\pipe\mpv_test_001  
```

However, how can this be achieved in a js script? I found the mpv-ipc library, which utilizes the node/net module to read and write through sockets, similar to the file read and write operations used by thumbfast.

I tried using mp.utils.write_file, but nothing happened. The screenshot command was not executed, and the mpv_test_001 file was not found either.

```js
setInterval(function cb() {
  print('start')
  mp.utils.write_file("file://\\\\.\\pipe\\mpv_test_001", 'screenshot-to-file ./tmp.png')
  print('end')
}, 1000)

```

Finally, I attempted to use a command_native call the echo command, but the parameters passed were recognized as strings and redirection did not occur.

```js
setInterval(function cb() {
  var r = mp.command_native({
    name: "subprocess",
    args: ['echo', 'aa', '>', './t.txt'],
    playback_only: true,
    capture_stdout: true,
    capture_stderr: true,
  })
  print('txt: ', r.stdout)
}, 1000)

```

Perhaps using command_native to invoke other scripts could work, for example, by first writing the command to a file and then executing it using PowerShell or Bash. However, this might not be the most efficient solution.

**Comment by avih** [comment]
> ```js
> mp.utils.write_file("file://\\\\.\\pipe\\mpv_test_001", 'screenshot-to-file ./tmp.png')
> ```

The input command (or JSON) string needs to end in a newline (so that mpv knows where the command ends, and which is what the `echo` command does), so you need `\n` at the end, and then it would work.

I don't know whether `mp.utils.write_file` also works on a unix socket (e.g. with mpv IPC server on linux).

Also, here, like most other places which work with file names on Windows, forward slash can replace backslash, so it would need less escaping, like so:
```js
mp.utils.write_file("file:////./pipe/mpv_test_001", 'screenshot-to-file ./tmp.png\n')
```

> ```js
>   var r = mp.command_native({
>     name: "subprocess",
>     args: ['echo', 'aa', '>', './t.txt'],
>     ...
>   })
> ```

Here you try to use (cmd.exe) shell syntax, but without targetting cmd.exe - the subprocess command looks for a command to execute, not a shell input elements.

So this would work:
```js
args: ["cmd.exe", "/c", "echo", "screenshot-to-file ./tmp.png", ">", "//./pipe/mpv_test_001"]
```

However, this can get tricky quickly, because cmd.exe quoting is notoriously hard and broken.

However, if you have [busybox-w32](https://github.com/rmyorston/busybox-w32) in your path, then you can use a unix shell syntax like so, which is more consistent and well documented than windows shell syntax:
```js
args: ["busybox.exe", "sh", "-c", "echo whatever > //./pipe/mpv_test_001"]
```

And as for your next question which would have been "great, thanks, so now, how can I read back from that socket? because `mp.utils.read_file` doesn't work"

The answer is probably "you can't" (I'm guessing it doesn't work, I didn't test).

And the reason is, as documented, that there's no standard library and no system access at the JS backend except using `subprocess` and whatever other mpv commands, and additionally the `mp.utils` read/write/append_file API, which is plain interface for the libc `fopen`, `fwrite`/`fread`, `fclose`.

So it `read_file` works, great, else, tough luck.

If you want system interaction, switch to lua, because this has relatively extensive native system interface (which is part of lua itself), while the ES5.1 JS standard doesn't have such specification or implementation, and so anything which is additional to the spec has to be implemented in mpv specifically for the JS backend - which we don't want to do, except the interface which already exists as mpv commands.

**Comment by ahaoboy** [comment]
Thank you.
This approach can successfully invoke the command.

```js

setInterval(function cb() {
  var r = mp.command_native({
    name: "subprocess",
    args: ['cmd', '/c', 'echo screenshot-to-file ./tmp.png > \\\\.\\pipe\\mpv_test_001'],
    playback_only: true,
    capture_stdout: true,
    capture_stderr: true,
  })
  print('txt: ', r.stdout)
}, 1000)

```
