### ISSUE TITLE
mpv doesn't seem to use the correct video dimensions.

### ISSUE THREAD

**Issue by Spider-Jerusalem** [mpv-player/mpv#1343]
When trying to view the mp4 in Firefox, the correct dimensions (or ratio?) are used, but mpv scales a little bit the video, and it's pretty visible with the bitmap fonts used in the video.

Picture of the problem: http://a.pomf.se/wkiwrd.png
Problematic video: http://a.pomf.se/letbae.mp4

**Comment by wm4** [comment]
No new information; we didn't even get to know with what WM this happens. But ti's probably Gnome. Closing.

**Comment by Gusar321** [comment]
It is actually mentioned in one of the comments, the WM is Openbox. For some reason mpv (and mplayer2 too) windows are created with height being one pixel off. The distortion, and black bars at the sides, then happens because mpv scales width to maintain aspect - here an example when I was playing around with this:
```
[vo/vaapi] Window size: 640x359
[vo/vaapi] Video source: 640x360 (640x360)
[vo/vaapi] Video display: (0, 0) 640x360 -> (1, 0) 638x359
[vo/vaapi] Video scale: 0.996875/0.997222
[vo/vaapi] OSD borders: l=1 t=0 r=1 b=0
[vo/vaapi] Video borders: l=1 t=0 r=1 b=0
```
When I was discussing this at the Arch forums, I said "I'll try a hack, add +1 somewhere in mpv's code". And well...
```
diff --git a/video/out/x11_common.c b/video/out/x11_common.c
index ce2111a..1a05443 100644
--- a/video/out/x11_common.c
+++ b/video/out/x11_common.c
@@ -1005,7 +1005,7 @@ static void vo_x11_sizehint(struct vo *vo, struct mp_rect rc, bool override_pos)
     hint->x = rc.x0;
     hint->y = rc.y0;
     hint->width = RC_W(rc);
-    hint->height = RC_H(rc);
+    hint->height = RC_H(rc) + 1;
     hint->max_width = 0;
     hint->max_height = 0;
```
To my complete surprise, this actually does the trick, Openbox creates the window with correct size. It's probably an Openbox bug, but it is interesting that it only happens with mpv and mplayer2.

**Comment by wm4** [comment]
>It is actually mentioned in one of the comments, the WM is Openbox. 

OK.

> It's probably an Openbox bug, 

Yes, it is. Some kind of rounding error. Can you report the bug upstream?

**Comment by Gusar321** [comment]
Done: https://bugzilla.icculus.org/show_bug.cgi?id=6367

Openbox doesn't exactly have active development, so we'll see if there's any reaction.
