### ISSUE TITLE
Redraw cached frame on paused video + RAM steadily increasing 

### ISSUE THREAD

**Issue by Raza-0007** [mpv-player/mpv#13502]
mpv v0.37.0-337-gbd5b80ba (latest 64-v3 build from Zhongfly)
Windows 11
Config in use attached below

Issue and steps to reproduce:

I don't know if this is a bug or it is by design. When a video is paused on full screen or windowed mpv, and the mouse is moved, mpv keeps on "redrawing cached frame" and "drawing osd". The bottom two item in the attached pic under "Redraw" (shift+I, 2).

I am guessing this is what results in the RAM steadily increasing. When the video is paused, note down the current memory consumed by mpv in Windows task manager. Leave mpv open and video paused, do something else, or just move the mouse on the screen, the memory consumption keeps on increasing steadily. In 5 minutes I recorded about a 100 MB increase in memory footprint. 

Since the video is paused mpv's RAM consumption should be more or less constant and not increasing.  

Is this a bug or normal behavior for a paused video?

.
~Raza

[mpv config.txt](https://github.com/mpv-player/mpv/files/14320756/mpv.config.txt)

![Screenshot 2024-02-17 192316](https://github.com/mpv-player/mpv/assets/131807929/76318316-c633-489d-957c-8872897a9b22)

**Comment by Dudemanguy** [comment]
Multiple things here. First of all you have the stats open with (shift + i). This updates automatically by itself on a timer so of course you will have constant redraw. How else would the OSD update itself? If you move the mouse over it, this can trigger additional redraws has osc may pop up/disappear. That's all normal.

As for the memory usage, that is just the libass glyph cache. All of the OSD is drawn in libass which has an internal cache. The memory will indeed increase because you are constantly redrawing, but not forever since it is bounded. So in short, this is all expected.
