### ISSUE TITLE
With gpu-next / macvk switching from / to fullscreen sometimes glitches the video

### ISSUE THREAD

**Issue by bsolar17** [mpv-player/mpv#13505]
### Important Information

Provide following Information:
- mpv 0.37.0 and current master g3fd840f85d (brew formula and brew --HEAD)
- Sonoma 14.3.1 (23D60)
- Homebrew
- [Video of visual glitches](https://github.com/mpv-player/mpv/assets/7414158/b9bcaf78-5c3a-44e0-a9b5-155adf2b2367)

Note: video shows the issue using the bundle but issue is present even when starting the video from command line.

### Reproduction steps

1. Play video with `vo=gpu-next`, `gpu-context=macvk`
2. Switch from / to fullscreen or vice-versa.

The switch from / to fullscreen makes the video flicker black. Sometimes the video gets glitched either full black or with changing colors. Video attached above demostrates the issue.

The issue does not appear with `vo=gpu`, `gpu-context=macvk`
It also does not appear if playing the video with `-v -v` or `--log-file=output.txt`. Issue does appear with only `-v`.

### Expected behavior

- No glitching of the video during windowed / fullscreen transitions when using `gpu-next`.
- No glitched video after the windowed / fullscreen transition when using `gpu-next`.

### Actual behavior

- The windowed / fullscreen transition is glitchy if using `gpu-next`.
- The video after the windowed / fullscreen transition sometimes remains in a glitched state if using `gpu-next`.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/14322334/output.txt)

### Sample files

Issue should be reproducible regardless of video.

**Comment by Akemi** [comment]
i can only reproduce this with `player-operation-mode=pseudo-gui`, when starting without any video and only then when loading certain video files.

i can also reproduce this with `-v -v` or `--log-file=output.txt`.
i can also reproduce this with `vo=gpu` though there it is always just a black screen instead of flickering colours.

i couldn't reproduce this with VulkanSDK 1.3.261.1 and it started when i updated to VulkanSDK 1.3.275.0. VulkanSDK 1.3.261.1 is the last, i believe, version without direct synchronization2 support from MoltenVK. mentioning this since when i originally tested all this, when gpu-next wasn't a thing yet (#7482), i had to use `--vulkan-disable-events` to make it properly work. maybe it is related, though we don't have such an option anymore?

**Comment by quietvoid** [comment]
I've seen similar flickering when when maximizing the window as well.
I don't think it's a super recent issue but not sure it happened in 0.36.0.

**Comment by zhhxiang05** [comment]
the new version --fullscreen got a bug. My bash script runs mp4 videos automatically in fullscreen. In recent half month, the mpv start to auto stopped. It cannot run. But if remove out --fullscreen option, everything works fine. The bug only occurs in recent debian edition. The macbook homebrew edition works fine. Althongh the two version have a same version number.

**Comment by Akemi** [comment]
@zhhxiang05 i am not sure how your linux problem is related to macOS? you should open a new issue, if it wasn't already reported.

**Comment by zhhxiang05** [comment]
Sorry for misunderstanding. My macbook have two OS on the same hardware , macOS and debian. The macOS mpv works well. The debian mpv started to fail recently. And the two version have the same version number. I guess it is the same to the existing issue. It is no need to open a new one.

On Mar 4, 2024, at 09:09, der richter ***@***.***> wrote:



@zhhxiang05<https://github.com/zhhxiang05> i am not sure how your linux problem is related to macOS? you should open a new issue, if it wasn't already reported.

**Comment by Akemi** [comment]
i think you still totally misunderstand something here. those issues can't be related. different backend, different driver, different underlying render API, etc. also this issue is not really about fullscreening, even if the title mentions it.

please open a new issue.

**Comment by zhhxiang05** [comment]
oh. got it . I need days to recheck this bug. Because my code changed mpv to another player right now. I need to turn back and check the platform too. I guess it shall be done in 2 days.

On Mar 4, 2024, at 10:00, der richter ***@***.***> wrote:



i think you still totally misunderstand something here. those issues can't be related. different backend, different driver, different underlying render API, etc. also this issue is not really about fullscreening, even if the title mentions it.

please open a new issue.

**Comment by zhhxiang05** [comment]
@Akemi I have raised a new issue in #13636 now. Although I think they r the same issue.

**Comment by Akemi** [comment]
a fix or rather a workaround for this problem can be found in the PR #13651.

**Comment by bsolar17** [comment]
I tested the artifact for Sonoma provided in PR #13651 and I can confirm it fixes the issue.
