### ISSUE TITLE
Is it possible to put MPV player like embet into ios Swiftui and Android Java application and make rtsp video player

### ISSUE THREAD

**Issue by uguraltinsoy** [mpv-player/mpv#13516]
Is it possible to put MPV player like embet into ios Swiftui and Android Java application and make rtsp video player. FFMPeg or VLCKit lags a lot, mpv runs perfectly smoothly

**Comment by CounterPillow** [comment]
Yes

https://github.com/mpv-player/mpv-examples/tree/master/libmpv

**Comment by uguraltinsoy** [comment]
> Yes
> 
> https://github.com/mpv-player/mpv-examples/tree/master/libmpv

Do you know any sample projects for Android (Java | Kotlin) and Ios (Swift | Swiftui)

**Comment by Akemi** [comment]
for android probably https://github.com/mpv-android/mpv-android
as a macOS swift example you can take cocoa-cb from mpv itself, it uses libmpv internally. with some adaption this could be used on iOS.

or a rather old example from me that is swift/macOS https://github.com/Akemi/libmpv-objc-swift. otherwise i don't know of any specific iOS examples.

we probably need something like this https://github.com/mpv-player/mpv/pull/7857 to make libmpv viable under iOS though, since libmpv only supports opengl via the render API.
