### ISSUE TITLE
Intention behind vo_dmabuf_wayland

### ISSUE THREAD

**Issue by mahkoh** [mpv-player/mpv#13532]
AIUI, vo_dmabuf_wayland uses subsurfaces and viewports to scale the video inside the compositor. However, compositors don't necessarily use the best scaling algorithms and might do blending in srgb space. Doing scaling and compositing inside mpv should never result in a worse output than doing it in the compositor.

Since the video surface is currently a subsurface, there are always two buffers present when mpv is fullscreen and this might make compositors not do direct scanout unless they have a way to detect that the lower buffer is not visible.

Could you explain in which situations one would want to use vo_dmabuf_wayland?

**Comment by llyyr** [comment]
> Could you explain in which situations one would want to use vo_dmabuf_wayland?

It uses lower power (testing in more environments needed but true in my case) than using vo_gpu(-next) with `profile=fast` because Mutter/Kwin/wlroots are capable of offloading composition to the hardware. There was actually a FOSDEM talk about this in fact https://fosdem.org/2024/schedule/event/fosdem-2024-3557-the-state-of-video-offloading-on-the-linux-desktop/

**Comment by Dudemanguy** [comment]
>unless they have a way to detect that the lower buffer is not visible

Pretty sure mutter does. At least, when rmader came by, he only wanted to optimize the osd surface and not the black bar one.

**Comment by Hobbyist11** [comment]
Hi, sorry to but in but does --vo=dmbuf-wayland use the dGPU on a laptop with dGPU? and is it possible not to, in order to save power? Thanks
