### ISSUE TITLE
video.js within browser ?

### ISSUE THREAD

**Issue by foxjaw** [mpv-player/mpv#13542]
Is there any project that uses video.js from the browser with mpv as a backend ?  
Would be great if it exists, so that I can play media directly through browser, with mpv like capabilities.

**Comment by Dudemanguy** [comment]
IIRC there was some plugins on firefox for this back when NPAPI addons were a thing. I don't believe anyone has been able to do anything like that since then. Most solutions now are essentially opening the url in mpv so it opens a separate window.

**Comment by po5** [comment]
While supporting all mpv rendering options in the browser would be a pain and likely perform very poorly, if all you need is the Lua scripting and UI aspects it's doable.  
I was working on reimplementing the event loop and mpv core functions/properties a year ago with [fengari](https://github.com/fengari-lua/fengari-web) for js/lua interop and [jassub](https://github.com/ThaUnknown/jassub) for UI, in a way that it could mpv-ify any video element through a browser extension or userscript.  
Didn't get far enough for anything useful to work since it's all stubbed out, but at least [mfpbar](https://codeberg.org/NRK/mpv-toolbox/src/branch/master/mfpbar) gets through init without crashing. If you want the code: [mpv-web.zip](https://github.com/mpv-player/mpv/files/14402405/mpv-web.zip)
