### ISSUE TITLE
Respect fish shell's private mode when saving watch_later files

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#13618]
As documented in https://fishshell.com/docs/current/interactive.html#private-mode

> You can query the variable `fish_private_mode` (`if test -n "$fish_private_mode" ...`) if you would like to respect the user’s wish for privacy and alter the behavior of your own fish scripts.

Fish shell's private mode can be entered by running "fish -P"

### Expected behavior of the wanted feature
MPV should check if the shell is operating in a non-state preserving mode and not save any state-preserving files while operating in this state. This includes not saving any watch_later files as well as possibly other things as well.

### Alternative behavior of the wanted feature
Alternatively an option should be added to enable this.

There are possibly other private shell modes in other shells (I'm not very familiar with them) that this can also be applied to.

**Comment by guidocella** [comment]
mpv is not a shell script, it doesn't have access to shell variables. You can write a fish script that wraps the mpv executable and sets different options based on `fish_private_mode`.

**Comment by Traneptora** [comment]
This is outside the scope of what mpv can accomplish. Even if a shell exports a variable as an environment variable rather than a shell local, it does not make sense for mpv to check every random shell's variables. As guido said above, you can always wrap mpv with a fish-shell script that sets the appropriate options on the mpv CLI.
