### ISSUE TITLE
[Philosophical Considerations] The future of mpv (or "how I started a diet against random bloat")

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#13611]
So, the title is big, but the content is not so big, so ... apologies for that. I wanted a catchy title so that a few mpv devs may read this; but also the "general public".

Before I explain why I wrote this issue request, let me preface a few things as introduction, if only to explain the rationale I am using here.

I have been using Linux since 2003 or so, give or take. I also found mplayer very early on and loved it.

Lateron I noticed mplayer's development kind of stalled ... I think there was mplayer2 too? But anyway, I eventually found mpv, and mpv in many ways was "the better mplayer". mpv is really great. I know other folks who use vlc, but I loved that I could use mpv from the commandline. I have it integrated into commandline things, e. g. using ruby and mpv as a kind of jukebox and playlist. It literally plays all my audio, video, it wakes me up in the early morning (like an alarm clock) - you name it. Thanks to ffmpeg in combination I also use the two (ffmpeg + mpv) as multimedia conversion kit.

Anyway, this was the intro and background.

Now to the issue I am having with mpv lately.

I am trying to compile mpv but it complains "libplacebo" is missing. I should also state that I compile everything from source, so compiling is almost second nature to me - but I don't really know C and C++ that well, only the basics. (I am quite ok with both ruby and python).

So I am trying to compile libplacebo, but it now complains:

src/opengl/include/glad/meson.build:11:2: ERROR: Problem encountered: glad (required: >= 2.0, found: 0.1.36) was not found in PYTHONPATH or `3rdparty`. Please run `git submodule update --init` followed by `meson --wipe`.

Ok so I need glad.

Now ... I can install/compile these things ... but these are new requirements, and I am wondering lately, why such new requirements of some miniscule library are suddenly required for mpv. Do I really need these to play videos? I didn't need these in the past, so clearly some mpv dev thinks they are necessary.

Ok, I can understand SOME of that - new shiny libraries make things easier to use, may add new features some people like, I get it. But at the same time I can't help but wonder what the goal of mpv really is. Should it be huge? Should it be small? Should it have 50000 features? Do we really need all those tiny libraries that creep into mpv now?

So, I am not necessarily wanting to start a debate about this or that library. People can always reason in favour of against it.

Instead I am wondering whether we could not make mpv in itself more modular, like "ok, you don't have libplacebo, you don't have glad, that's still ok, mpv will work but you can't watch hentai as a result" - or whatever libplacebo, glad, or xyz in the future may need. I'd ideally want just a small mpv really, something that can still play things as-is, without needing to keep up with tons of new feature changes that some developer wants to have. In an ideal world, perhaps we could have mpv be structured more like busybox or the linux kernel - not as complex, mind you, but more like a swiss army knife where we can more easily decide what gets into it, and what does not.

Perhaps I can disable this via meson, but I have no idea how to use meson - that thing is more complicated to use than GNU configure. In GNU configure I could try --disable-libplacebo --disable-glad and that's it (unless they are mandatory, of course, but then this brings me back to the rationale explained above).

I tried to check the homepage at: https://mpv.io/ for information in this regard, but, boy, that's one shiny homepage that is sooooooooooo utterly useless. It seems to cater to some random passerby. Can you people point me to the detailed explanation how to customize mpv from source? Or is that thing not existing? Ok, in that case this is fine, nobody gets paid to do so, so that's the fate of open source. But the point remains that the homepage is next to useless in such a case too.

Anyway. My point is not so much to rant or complain, but to try to get the mpv team to think about this, whether all these libraries are necessary, and if not, how to make it more easily possible to make mpv modular. As it is I am now using mplayer, because I don't want to constantly have to install random libraries only mpv needs, whereas mplayer is just fine and plays what I need it to play. I'd much prefeer to use mpv, but mplayer "just works" if only due to being so slow and snail-like when it comes to updates.

As that is not a good open issue, I would suggest this to be kept open for, say, two or three weeks maximum before it is closed. Please, if possible, keep it open for a few days, though, to allow other people to chime in pro/con, both developers but also "mere mortal users". Thanks for reading nonetheless.

**Comment by haasn** [comment]
To clarify, when you say "bloat", you mean "external dependencies"? I think this is a very particular interpretation of the word which is obscuring another relevant metric by which it could be judged: the amount of code/logic directly contained in a program.

Ask yourself this philosophical question - would mpv become more or less bloated if it stopped depending on libavcodec and reimplemented all demuxers, decoders, etc. from scratch? Because that's more-or-less what MPlayer used to be. It was a million SLOC megaproject. In fact, part of mpv's history was deleting all of MPlayer's bloat by instead relying on third party libraries such as FFmpeg, which is probably the most substantial mandatory build-time dependency at this point.

By outsourcing things like video rendering (libplacebo) or OpenGL context loading (glad) to third party libraries you are *reducing* the amount of code that needs to be maintained inside mpv. The entirety of `vo_gpu_next` (based on libplacebo) is about 10% of the size of `vo_gpu`, *while also having more features*. The commit that actually made libplacebo a required dependency even mentions that doing this will allow us to reduce the size of the mpv codebase, and already thousands of lines of code has been deleted as a result. In the unix philosophy, the goal for any piece of software is to do one thing and do it well, and it would be hard to argue that this is not a different type of "dieting". Ultimately, mpv sits somewhere in between the extremes of "reinventing everything from scratch" and "depending on an external library just to reverse a linked list".

It seems that what you are really complaining about here isn't bloat, but rather the number of steps required to build mpv from source. If so, have you considered using https://github.com/mpv-player/mpv-build? It seems like it would help you solve your immediate problem of not wanting to build all dependencies from source just to build mpv from source. Furthermore, most package managers on conventional distros will allow you to install all of the build-time dependencies for a software in one go. For example, on SuSE-based distros, `zypper source-install mpv` will install everything you need to build mpv, out of the box.

(Finally, the last error you quoted literally told you what exact command to run to make the error go away..)

**Comment by stax76** [comment]
@rubyFeedback

What you can do to overcome such obstacles with building mpv from source is using the popular newbie friendly Linux distro Ubuntu. If you can't get it with [mpv-build](https://github.com/mpv-player/mpv-build) simply ask the mpv community here on GitHub or reddit for help on how to build mpv, and request [mpv-build](https://github.com/mpv-player/mpv-build) documentation to be improved/updated.

I had my problems too building mpv due to a new missing x11 dependency, IIRC what worked for me was:

`apt-rdepends --build-depends --follow=DEPENDS mpv`

**Comment by gsarkardev** [comment]
To put it mildly, [mpv-build ](https://github.com/mpv-player/mpv-build) is hot trash.
