### ISSUE TITLE
setup secondary subtitle, problems

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13623]
Hi I was trying to take advantage of the secondary subtitle `secondary-sid=2` but I have problems setting it up.
I need a negative delay on this stream but there is no effect on the subtitles. I tried `secondary-sub-delay=-4` which should translate to 4 seconds like in the first subtitle.
I also want to change the position but there seem to be no effect on the position with `secondary-sub-pos=10`

Thanks for any advice

**Comment by llyyr** [comment]
Fill out the issue template

**Comment by low-batt** [comment]
Did not reproduce for me.

I tested `mpv` as of commit 1bf821ebdc5c4775fe4bdbba994259c53463fc69 playing the YouTube video [10 Minute Timer (count-up stopwatch)](https://www.youtube.com/watch?v=pHvP71rwYAc) with subtitles I created that merely count seconds.

```bash
mpv --no-config --pause --sub-files=sub-1.srt:sub-2.srt --secondary-sid=auto --secondary-sub-delay=-4 --secondary-sub-pos=10 --start=4 https://www.youtube.com/watch?v=pHvP71rwYAc
```

From this screenshot you can see the secondary subtitle is running 4 seconds ahead of normal due to `--secondary-sub-delay=-4`:
![mpv-shot0001](https://github.com/mpv-player/mpv/assets/86170219/837e7e54-b0fc-45ab-90aa-cffac3f4fa31)

This is the subtitle file I used in the test:
[sub-1.srt.txt](https://github.com/mpv-player/mpv/files/14563847/sub-1.srt.txt)

I used a copy of the file for the second subtitle file.

I tested `--secondary-sub-pos` and that seemed to be working as well.
