### ISSUE TITLE
Questions related to judder, scalers, and color management.

### ISSUE THREAD

**Issue by averagePedestrian** [mpv-player/mpv#13658]
Hi, could someone please review my MPV configuration? I would appreciate any input. Here are my system specs:

CPU - Intel Core i7 9750H,
GPU - NVIDIA GTX 1660 Ti,
RAM - 24GB,
OS - Windows 10.

I mainly watch 1080p content, including anime and live-action, on a 1080p SDR monitor with a refresh rate of 143.981Hz. I am very new to all of these and need help with a couple of things.

1. I’m experiencing judder when watching 23.976fps content, even with motion interpolation enabled. After 10 minutes of playing a 1080p video, I experience approximately 50 delayed frames and only a few mistimed frames. Logs are attached below.

2. What scalers should I be using on my system? I looked at the scaler comparison by artoriuz here (https://artoriuz.github.io/blog/mpv_upscaling.html) and based on the results I chose to use Chroma from Luma Prediction scaler as the chrome scaler. I want to know if his testing methodology is correct and if should I continue to use that scaler or does the default one when using the high-quality profile makes more sense.

3. I have an ICC profile installed and have icc-profile-auto set to yes in my config. I also use displaycal profile loader. Do I need to modify any settings in the nvidia control panel app or am I set?

mpv.conf: https://pst.moe/paste/dpaldz
mpv log:  [mpvlog.txt](https://github.com/mpv-player/mpv/files/14525048/mpvlog.txt)

**Comment by Artoriuz** [comment]
This is not the correct issue tracker to be asking questions about an unaffiliated blog post.

About your first question though, 144 is a multiple of 24 so you don't need to do anything to have a mostly judder-free playback. A 1660 Ti should not be dropping frames on 1080p content so if you're having performance issues it might be a good idea to start removing memes from your config.

You might also want to enable hwdec if your CPU isn't keeping up, but that's unlikely on 1080 content.

**Comment by averagePedestrian** [comment]
> About your first question though, 144 is a multiple of 24 so you don't need to do anything to have a mostly judder-free playback. A 1660 Ti should not be dropping frames on 1080p content so if you're having performance issues it might be a good idea to start removing memes from your config.

I experienced 0 dropped frames, and only a few mistimed frames during the playback of a 23-minute episode. The delayed frames numbered around 120 at the end of the episode.

> You might also want to enable hwdec if your CPU isn't keeping up, but that's unlikely on 1080 content.

It's enabled as mentioned in my mpv.conf file

**Comment by Raza-0007** [comment]
Sometimes judder is caused by a poorly encoded video. On such videos you tend to notice the judder when the scene pans vertically or horizontally, or when the scene zooms in or out. You can test this by playing the video on a couple of different players like vlc, or mpc-hc/be, on default settings; if the judder is still there, then its the video and not mpv or your config.

If you determined that the video is fine and its something in your config then I would recommend starting by not using any external shaders or scalers. When I tested these external shaders and scalers I found that they either did not improve the video quality at all, or the quality improvements were not worth the extra processing power, or chance of a conflict with some other settings etc. mpv's built in shader/scalers when using high-quality profile and gpu-next are more then good enough to output an excellent video.

~Raza

**Comment by netExtra** [comment]
Wow! That's some mpv.conf!

Ok start with this. On Windows, the defaults work best. So:

Remove nvdec-copy
Don't use any -copy
Remove gpu-api
Remove gpu-context
Remove fscrnnx

There's more but I don't even want to go there.
