### ISSUE TITLE
Videos with mkv ProjectionPoseRoll element are rotated in the wrong direction

### ISSUE THREAD

**Issue by ls-2037** [mpv-player/mpv#13830]
### Important Information

Provide following Information:
- mpv version: 0.37.0 or 2024-03-31 daily build
- Platform and Version: Windows 10 or 11
- Source of the mpv binary: builds on the mpv website
- If known which version of mpv introduced the problem: I think support for ProjectionPoseRoll was introduced in 0.37.0
- GPU model, driver and version: various inted iGPUs
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

1. Use ffmpeg to rotate any video file and store it in an mkv container (ffmpeg -display_rotation 90 -i inputfilename -c copy output.mkv).
2. The ProjectionPoseRoll element will be set to 90.
3. Play the output file using ffplay. It will be rotated 90 degrees counter-clockwise, which is correct.
4. Play the output file using mpv. It will be rotated 90 degrees clockwise, which is incorrect.

### Expected behavior

Positive ProjectionPoseRoll values should rotate counter-clockwise and negative values should rotate clockwise. Matroska element documentation for this is somewhat confusing, but it is clarified well in the technical notes linked below.

https://www.matroska.org/technical/notes.html#rotation

### Actual behavior

The video is rotated in the wrong direction by mpv during playback.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/14897715/output.txt)

### Sample files

Any video file rotated using ffmpeg (ffmpeg -display_rotation 90 -i inputfilename -c copy output.mkv).

**Comment by llyyr** [comment]
Are you sure positive values should be counterclockwise? The actual specification is ambiguous since it doesn't specify what the "forward vector" is. https://www.matroska.org/technical/elements.html#ProjectionPoseRoll

Moreover, it seems like lavf is the odd one out here. mkvtoolnix/mpv/LAVFilters agree on positive values meaning clockwise rotation. You should probably open an issue on the specification repo first to get clarification

**Comment by ls-2037** [comment]
The actual specification is ambiguous, but the notes on matroska.org state direction that positive should be counter-clockwise. https://www.matroska.org/technical/notes.html#rotation

**Comment by kasper93** [comment]
Another case of ambiguous Matroska spec?

Since we don't know which coordinate system author was referring when saying "forward vector", certain assumption has been made.

MPC-BE[1], MPC-HC, LAV Filters[2], ExoPlayer [3] and mpv [4] all agree on the current behavior. While as you rightfully pointed out libavcodec [5] is not agreeing with the rest of the world. 

Also hubblec4 [6] and other similar texts follow what is done by the players, probably because he mentions MPC-BE and follow behavior of it.

I personally kinda agree that notes [7] makes strong argument against the current behavior. And I'll be honest mpv implementation is guilty of following all other players, simply because it works the same... 

[1] https://github.com/Aleksoid1978/MPC-BE/commit/4521f079fe63d655dd5b5add9991a8e2eccb67f8
[2] https://gitea.1f0.de/LAV/FFmpeg/commit/cf4386d4426223de6e70e144e16038998bbecefd
[3] https://github.com/google/ExoPlayer/commit/fc6a1ea52264a5f2972602b3bbc90ad1fabba16c
[4] https://github.com/kasper93/mpv/commit/a4bf0bd695da7ac0fea561342c60d954d485af0a
[5] https://github.com/FFmpeg/FFmpeg/commit/937bb6bbc1e8654633737e69e403e95a37113058
[6] https://github.com/hubblec4/Matroska-Playback/blob/611828239502e96e9e160c939ef39a089ea5ec97/src/Rotate.md
[7] https://www.matroska.org/technical/notes.html#rotation

**Comment by ls-2037** [comment]
Yes, "forward vector" was very unclear to me as well, and there are also forum threads I've read online where people are confused. Hopefully the specification can be clarified.

**Comment by ls-2037** [comment]
Ah, you're right, I accidentally reversed the direction in my head. So either "forward vector" must mean a vector normal to the plane of the screen pointing towards the viewer, otherwise the notes on the Matroska website are incorrect, because they themselves state CCW.

**Comment by ls-2037** [comment]
Steve Lhomme has confirmed that the rotation should be counter-clockwise (https://github.com/ietf-wg-cellar/matroska-specification/issues/822).

**Comment by kasper93** [comment]
I pinged interested parties in the above ticket, just to synchronize the change.
