### ISSUE TITLE
Show AAC audio type in info panel

### ISSUE THREAD

**Issue by Ciancy28** [mpv-player/mpv#13839]
### Expected behavior of the wanted feature
When the user opens the info panel (by pressing the "I" key when using default mappings), AAC audio should show up as AAC-LC/AAC-HE/AAC-HEv2/AAC-xHE instead of just "AAC" (which is the current behaviour no matter which type of AAC audio stream is being played)

### Alternative behavior of the wanted feature
might also be shown as a separate "stream type" field under channels/sample rate, but would be extra clutter for no good reason imo

### Log file
This log has been taken during playback of an HE-AACv2 demo file in an mp4 container
[log.txt](https://github.com/mpv-player/mpv/files/14908707/log.txt)
here, it also just shows up as "AAC" without any mention of which kind of AAC it is (in this case HE-AACv2)

**Comment by kasper93** [comment]
The value is stats is a decoder name, which is common for all AAC (except LATM) and is provided directly by lavc https://github.com/FFmpeg/FFmpeg/blob/b0ef9e35e80990b0ba03dd724a6d41cccba100b1/libavcodec/aacdec.c#L555-L556

Not sure we can extract the specific variant of it easily and even though it would create precedence, because we don't do it for any other codec.
