### ISSUE TITLE
Windows Official Support

### ISSUE THREAD

**Issue by zookeeper76** [mpv-player/mpv#13847]
Hello to you all.

First off, thank you very much for providing MPV to the masses! I use it every day, many time a day on my Fedora workstation. In regards to Windows support, would it be possible to consider having an "Official" MPV build, one that could perhaps even be published on the Microsoft App store? As of now, I'm using an unofficial build that is not up to date.

Thank you one more time for this great app!

Regards,

Zoo

**Comment by kasper93** [comment]
> I'm using an unofficial build that is not up to date.

Why not use unofficial build that is up to date?

I think general consensus is that mpv-player org doesn't want to provide official builds, mostly because there is no one willing to maintain it. But if someone wants to volunteer and make some kind of pipeline that would build official builds for macOS and Windows, let's say once per day if there were changes. Keep an eye on it and track/update dependencies. I think it could be done. For now though main builds for Windows are https://github.com/shinchiro/mpv-winbuild-cmake/releases and https://github.com/zhongfly/mpv-winbuild/releases Note that they are third-party effort and not monitored by mpv developers, so use at your own risk.

**Comment by zookeeper76** [comment]
Where may I find such test builds for Windows? By the way, are these test builds compiled and ready to exe execute?

**Comment by llyyr** [comment]
> I see the links. Many files available... Which one do I choose? I'm looking for the exe...

https://github.com/mpv-player/mpv/actions/workflows/build.yml?query=branch%3Amaster+event%3Apush

Click on the latest commit there then download the `mpv-x86_64-w64-mingw32` artifact.

**Comment by zookeeper76** [comment]
> > I see the links. Many files available... Which one do I choose? I'm looking for the exe...
> 
> https://github.com/mpv-player/mpv/actions/workflows/build.yml?query=branch%3Amaster+event%3Apush
> 
> Click on the latest commit there then download the `mpv-x86_64-w64-mingw32` artifact.

Ok thank for the help. I have it up and running with the latest build. Is this build official or is it also compiled by volunteers?

**Comment by kasper93** [comment]
> Is this build official or is it also compiled by volunteers?

Those are official builds form mpv CI. They are not signed and distributed only through CI artifact, but they are first-part builds.

**Comment by zookeeper76** [comment]
Well I been "torture" testing my system and so far it seems rock solid!!! This is great. These builds are produced every week or so for Windows?

**Comment by kasper93** [comment]
They are produce after every push to master.

**Comment by Hrxn** [comment]
@zookeeper76 
What's wrong with using
https://github.com/shinchiro/mpv-winbuild-cmake/releases
https://github.com/zhongfly/mpv-winbuild/releases

They are not considered first party, as explained earlier herein, but I think this is what most (if not all) Windows users actually use?

Might be the best option, because as Andarwinux mentioned, they do not lack any features etc.

> > Is this build official or is it also compiled by volunteers?
> 
> Those are official builds form mpv CI. They are not signed and distributed only through CI artifact, but they are first-part builds.

One more thing to keep in mind: the automatic CI pipeline builds might trigger false positives with your virus scanner or Windows Defender, etc.

Also, it might be a bit more than just some fancy features that are not working, for example, I'm getting this error/warning right now with [this recent build](https://github.com/mpv-player/mpv/actions/runs/8676262425):

```
[vo/gpu-next/libplacebo] libplacebo compiled without LittleCMS 2 support!
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu-next] 1920x1080 yuv420p
AV: 01:00:09 / 01:00:10 (100%) A-V:  0.000

```

**Comment by kasper93** [comment]
> One more thing to keep in mind: the automatic CI pipeline builds might trigger false positives with your virus scanner or Windows Defender, etc.

The same apply to shinchiro's or zhongfly's builds.

**Comment by Hrxn** [comment]
Not to the same amount... the more are binary file gets "seen" by Windows Defender, the more "trustworthy" it gets, basically.
