### ISSUE TITLE
The new version doesn't load OSC scripts

### ISSUE THREAD

**Issue by ang3lo-azevedo** [mpv-player/mpv#13941]
### Important Information

Provide following Information:
- 0.38.0-2
- 6.8.7-arch1-1
- Arch Official Repositories (extra)
- This version, when downgraded to 0.37.0-3 the problem disapears
- KWin (Wayland)
- NVIDIA GeForce RTX 2060 Mobile, 550.67
- ![image](https://github.com/mpv-player/mpv/assets/66081804/bbcca167-9029-4c02-bf4d-2c7c2c4f3338)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

When using the version 0.38.0-2 mpv and having the osc = no option on mpv.conf any osc added through a script won't show up.

![image](https://github.com/mpv-player/mpv/assets/66081804/bbcca167-9029-4c02-bf4d-2c7c2c4f3338)

When downgraded to the last version 0.37.0-3 everything works fine

![image](https://github.com/mpv-player/mpv/assets/66081804/83ab2bd5-232a-4ef4-8bf0-f7e08272d699)

**Comment by christoph-heinrich** [comment]
I bet the custom osc script uses `shared-script-properties` and crashes.

**Comment by christoph-heinrich** [comment]
It tries to call one of the helper functions and crashes because they don't exist anymore.
Here is one of such cases https://github.com/Zren/mpv-osc-tethys/blob/ac054282a32abd6fa7fd2c9fd01e559537905a32/osc_tethys.lua#L4796

Use the lua file from this PR instead https://github.com/Zren/mpv-osc-tethys/pull/36
