### ISSUE TITLE
VP9 version hdr10+ video not decoding by mpv and ffprobe giving errors

### ISSUE THREAD

**Issue by aaaatheone** [mpv-player/mpv#14018]
I already been open an issue about that problem and its bugs in here `https://github.com/mpv-player/mpv/issues/14012`

but it closed by kasper93 and did not provide much more information why it closed!!. I am guessing that it not related to MPV rather then ffmpeg ? or this issue is in under bug fixing development on going process or that issue already reported to bug related discussion ? or any other related 

It also showing "**mpv-player locked as resolved**" at the bottom of this topic, so that problem already resolved?

I have open this issue again for wanting to know if there is any way available to play VP9 version hdr10+ metadata video via mpv

**Comment by low-batt** [comment]
Many open source projects are layered on top of other open source projects. When a defect is found it may prove to be code that comes from another project. When that happens the problem needs to be reported to that project.

In the case at hand, mpv uses libraries from the [FFmpeg](https://ffmpeg.org/) project. If [ffplay](https://ffmpeg.org/ffplay.html) exhibits errors then the problem needs to be reported to `FFmpeg`.

Read [Bug Reports](https://ffmpeg.org/bugreports.html) and enter a report with the `FFmpeg` project.

mpv closed #14012 because mpv can not fix this problem, the `FFmpeg` project has to fix the problem.

**Comment by kasper93** [comment]
> I think ffmpeg and mpv both need to add vp9 (youtube)version hdr10+ support. I can't believe it was not developed before lol.

I can't believe you ignored issue template again lol.
