### ISSUE TITLE
[question] is there a limit to entries for m3u playlist files in mpv?

### ISSUE THREAD

**Issue by masterofobzene** [mpv-player/mpv#14149]
I'm on windows 10.

Quick question: Is there a limit to entries for m3u playlist files in mpv? I'm trying to play a playlist with 137253 items and mpv fails to play it, no error shown.

**Comment by CounterPillow** [comment]
> Give 1 reason why the template was needed for anything in this simple question (no support asked) to justify this, I dare you.

Sure, I'll bite.

It appears you are encountering an issue where mpv does not recognise all files in a playlist. To see what's going on, since we are not you on your own computer, we need to know what version of mpv you're using, a sample file, and a log file which would show mpv loading those entries.

Hope that helps, you lazy piece of shit.

**Comment by Hrxn** [comment]
https://github.com/mpv-player/mpv/discussions

**Comment by MoSal** [comment]
@masterofobzene 
Is the playlist a simple one, or does it contain stuff like inline data/base64 logos, etc (sometimes nominally referred to as m3u plus)?

**Comment by CounterPillow** [comment]
> UPDATE: I think MPV doesn't like "-" in filenames on playlists.

Wow would you look at that, something we could've noticed had you filled out the issue template, which you refused to do and then got pissy about.

> I just wanted to know if MPV has a limit in playlist files with too many files.

You seem to be under the impression that people have a complete view of the entire software stack. They don't. Someone would actually have to go digging into the code to prove the absence of a thing you hypothesize, which is way more work than reproducing a case in which something doesn't work.

> Your player can't handle such playlists it seems; while MPC-HC had no problems, still I use features of your player, that is why I wasted my time asking a simple short question.

The issue tracker is not a forum, it is for reporting issues. (Which is also why it's funny you mentioned things like "If you didn't want to answer a simple question, just delete it", as if that's a function of GitHub issues; no, you can't delete them) Discussions is for questions. And your question, as stated, is not simple: the answer depends on somebody knowing the entirety of mpv's m3u playlist reading code which probably comes from FFmpeg.

**Comment by MoSal** [comment]
> This is an example line of one playlist redacted for privacy, just to give an idea:
> 
> `Sxxxxxxxxxx\[xxxxxxxxxx]\xxxx xxxxx xxxx xxxx xxxx xxxxx xxxxxxx xxx xxxxxxx xxxxx xxxx xxxx_xxxxxxxxx_xxxx -xxxx02 [H265].mp4`
> 
>

If your playlist doesn't look something like this:

```
#EXTM3U
#EXTINF:-1, Title 1
PATH1
#EXTINF:-1, Title 2
PATH2
#EXTINF:-1, Title 3
PATH3
#EXTINF:-1, Title 4
PATH4
```

Then it's not an M3U playlist at all!

It would be really helpful (for you) if you pasted the full content of a playlist that causes problems. Copy and rename stuff if needed to protect your privacy.

You still didn't even give a detailed description of how it fails.
"no error shown" where?
Did you try to run it from a console/terminal?
Because if you did then....

> UPDATE: I think MPV doesn't like "-" in filenames on playlists.

^ Because if you did then.... you would probably have noticed that without careful quoting, '-' coming after a space can be parsed as a CLI option, which is maybe what's happening here. Maybe other stuff is happening too. No one can possibly know if you don't provide actual relevant details.
