### ISSUE TITLE
dvdnav: --ao=pcm --no-video --chapter=1-1 stalls

### ISSUE THREAD

**Issue by billll** [mpv-player/mpv#1432]
Using the following command, mpv stalls after a few seconds of encoding:
$ mpv --no-video --ao=pcm --aid=2 --chapter=1-1 --dvd-device=/path/to/dvd dvd://0

This seems to work if a remove either --no-video or --chapter=1-1.

**Comment by wm4** [comment]
The problem is that with dvdnav (activated by ``dvd://``) the player stops the file only if the DVD VM gives the command to stop playback. This doesn't happen here, because the DVD VM doesn't know about stopping playback at an arbitrary time (it happens in a higher level in the player). So it never actually quits.

It might be possible to explicitly quit if playback ends e.g. due to --chapter, but then I'm afraid of the opposite situation: the player could quit during menu interaction, even if it's not supposed to quite yet. The DVD code is already messy enough, so I don't want to touch it.

Workaround for now: use ``dvdread://`` instead.

(This also happens without --no-video - but then it actually skips data, until the rest of the DVD is decoded, and the DVD VM thinks the actual end of playback was reached.)

**Comment by wm4** [comment]
DVD menu removal most likely makes this impossible to happen.
