### ISSUE TITLE
Add an option to enable ontop only when video is playing

### ISSUE THREAD

**Issue by pxia** [mpv-player/mpv#14447]
### Expected behavior of the wanted feature

Add an option `--ontop-when-playing`. When this option and `--ontop` are both set, window only stays on top when video is playing. I think this would be a good QOL change because when you pause in ontop mode, you probably want to do something else without mpv blocking the screen.

### Alternative behavior of the wanted feature

make current ontop as a tri-state option. And pressing T cycles through them.

**Comment by avih** [comment]
While it's probably possible to add such feature, it's not worth adding, because a tiny lua or JS script can do that for you.

The [lua scripting docs](https://mpv.io/manual/master/#lua-scripting) has this example at the very begining:
```lua
function on_pause_change(name, value)
    if value == true then
        mp.set_property("fullscreen", "no")
    end
end
mp.observe_property("pause", "bool", on_pause_change)
```
which you can trivially modify to control the `ontop` property instead of the `fullscreen` property.

**Comment by hooke007** [comment]
It can be done only by a auto-profile.

**Comment by Dudemanguy** [comment]
Yeah this is just an auto-profile, so there's no need to add another option.
