### ISSUE TITLE
`play_current_file` called twice for the first file when using --autocreate-playlist

### ISSUE THREAD

**Issue by llyyr** [mpv-player/mpv#14675]
### mpv Information

```bash
mpv v0.38.0-701-gacc69e082fff Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 15 2024 12:27:17
libplacebo version: v7.349.0
FFmpeg version: git-2024-08-13-66592e8b100f
FFmpeg library versions:
   libavcodec      61.11.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.34.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Important Information

- Platform version: Tumbleweed
- GPU model, driver and version: 6600 XT
- Source: git
- Introduced in version: bb9b862f0c7fdc98a5a82a116770d09ba1d4d152

### Reproduction Steps

`mpv --no-config --autocreate-playlist=same --script=foo.lua <some file>`

foo.lua: `mp.add_hook("on_load", 50, function (event) require"mp.msg".fatal("on_load hook called") end)`

Here, the on_load hook will be called twice on the same file. Along with every other hooks and events that exist inside [this highlighted region](https://github.com/mpv-player/mpv/blob/acc69e082fff67398834de3045ef48d33d2f4d54/player/loadfile.c#L1569-L1698), as well as other hooks and events [after `goto terminate_playback`](https://github.com/mpv-player/mpv/blob/acc69e082fff67398834de3045ef48d33d2f4d54/player/loadfile.c#L1867-L1953).

auto profiles are also processed twice because of this, since the script [listens for these hooks](https://github.com/mpv-player/mpv/blob/master/player/lua/auto_profiles.lua#L206).

This only happens on the first file on our "fake" playlist, because the playlist must be populated first before the actual file can be played and the function doesn't know in advance whether it is a playlist or a real file.

### Expected Behavior

Only receive `on_load` once

### Actual Behavior

`on_load` hook is processed twice.

### Log File

[mpvsucks.log](https://github.com/user-attachments/files/16622473/mpvsucks.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
I forgot to respond here. I think @llyyr's concern is valid, but it is not as high-impact an issue as it is made out to be.

> Not really. It clearly says "as if the parent directory is opened", not "as if the file is a (fake) playlist". It means that the directory is loaded as a playlist, then the file is loaded, so the file should not be loaded twice.

I was thinking about this issue since the auto playlist feature has been merged, because I'm constantly reminded of it. The behavior of first hook is in direct conflict of this issue concert and the ability to control autocreate-playlist in the profile on per-file basis.

I've been thinking about this issue since the auto-playlist feature was merged because I'm constantly reminded of it. The behavior of the first hook directly conflicts with this issue's concept and the ability to control the autocreate-playlist in the profile on a per-file basis.

Imagine you want to create a configuration that generates a playlist only for jpg files and excludes everything else. Something like this:
```
autocreate-playlist=no

[img]
profile-cond=get('path', ''):find('.jpg$')
profile-restore=copy-equal
autocreate-playlist=filter
```

To make this work, the first hook must be a real open target, and the second one is a byproduct of creating and opening a playlist. After looking into it, I found that I could overwrite `stream-open-filename` similarly to how a ytdl hook does. The unfortunate thing is that I would need to stat() the file not from the opener thread, which is probably acceptable, but I wanted to avoid that. I'm still not sure this resolves the original issue reported here, as the main claim is that the `on_load hook is processed twice`.  This is exactly how any playlist works, whether it's a normal playlist, a directory, or a "fake" one, as you nicely call it. I also think people use `path` in profiles rather than `stream-open-filename`, which is more appropriate if you want real open-after hooks.

I didn't envision that this relatively simple feature will backfire at me.
