### ISSUE TITLE
Problems setting `sub-langs` for ytdl

### ISSUE THREAD

**Issue by FichteFoll** [mpv-player/mpv#14818]
### mpv Information

```bash
mpv v0.38.0-750-ge169302e2d Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep  8 2024 10:46:16
libplacebo version: v7.349.0
FFmpeg version: n7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```
(fresh build from e169302e2d but also 0.38.0)

### Important Information

```text
- Platform version: Arch Linux
- GPU model, driver and version: not relevant
- Source: `mpv-git` from AUR and `mpv` from arch repos
- Introduced in version: 0.38 or earlier
```

### Reproduction Steps

Trying to set a list of subtitle languages for ytdl seems to fail because ytdl simply provides no subtitles when `sub-langs` is set. The following commands reproduce the issue:

```
command mpv --no-config --ytdl-raw-options-append="sub-langs=en.*,de.*" 'https://youtu.be/i6kLabq7RyE?lang=en&plat_type=pc'
command mpv --no-config --ytdl-raw-options-append="sub-langs=en.*" 'https://youtu.be/i6kLabq7RyE?lang=en&plat_type=pc'
command mpv --no-config --ytdl-raw-options="sub-langs=en.*" 'https://youtu.be/i6kLabq7RyE?lang=en&plat_type=pc'
```

Omitting the ytdl args completely results in all 13 available subtitles to be downloaded and provided to mpv. 

When additionally setting `write-subs` (a yt-dlp default), the subtitles show up again, but then you cannot set multiple sub-langs in a single ytdl-raw-options because of the comma and have to use ytdl-raw-options-append for both:

```
command mpv --no-config --ytdl-raw-options-append=write-subs= --ytdl-raw-options-append="sub-langs=en.*,de.*" 'https://youtu.be/i6kLabq7RyE?lang=en&plat_type=pc'
```

### Expected Behavior

Setting `--ytdl-raw-options-append="sub-langs=en.*,de.*" ` should not require also setting `--write-args` for the ytdl options

### Actual Behavior

Setting `--ytdl-raw-options-append="sub-langs=en.*,de.*" ` causes no subtitles to be fetched unless also setting `--write-args` for the ytdl options.

### Log File

[ytdl-sub-langs.txt](https://github.com/user-attachments/files/16921910/ytdl-sub-langs.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by CrendKing** [comment]
First of all, your last command works for me:
```
mpv --no-config --ytdl-raw-options-append=write-subs= --ytdl-raw-options-append="sub-langs=en.*,de.*" 'https://youtu.be/i6kLabq7RyE?lang=en&plat_type=pc'
● Video  --vid=1               (vp9 1920x1080 24 fps) [default]
● Audio  --aid=1  --alang=eng  (opus 2ch 48000 Hz) [default]
○ Subs   --sid=1  --slang=de   'German' (webvtt) [external]
○ Subs   --sid=2  --slang=en   'English' (webvtt) [external]
```
You can see both English and German subtitle tracks are added here.

Second, according to the [doc](https://mpv.io/manual/master/#options-ytdl-raw-options), a simpler syntax for the option can be
```
mpv --no-config --ytdl-raw-options=sub-langs="en.*,de.*",write-subs= 'https://youtu.be/i6kLabq7RyE?lang=en&plat_type=pc'
```

Lastly, I think we should fix the requirement of extra `--write-subs` when `sub-langs` is used.

**Comment by CrendKing** [comment]
Here is what happens:

mpv calls yt-dlp with `-J` to get the JSON information for the URL. In the returned object, there is the key-value pair called `requested_subtitles` that mpv uses to add subtitle tracks. yt-dlp only populates this value [if either `--write-subs` or `--write-auto-subs` is specified](https://github.com/yt-dlp/yt-dlp/blob/e59c82a74cda5139eb3928c75b0bd45484dbe7f0/yt_dlp/YoutubeDL.py#L3051). Otherwise it is left null.

Since `--all-subs` sets `--write-subs`, and mpv by default sets `--all-subs`, everything works out of the box. The moment user sets `--sub-langs` in `--ytdl-raw-options`, [mpv no longer sets `--all-subs`](https://github.com/mpv-player/mpv/blob/216abbc12149668c71e400c19d1f60a507fb68c8/player/lua/ytdl_hook.lua#L938), thus losing all subtitle tracks. User must explicitly also sets `--write-subs` to restore the tracks, like OP does here.

I don't understand why yt-dlp requires `--write-subs` to populate `requested_subtitles` in the first place. I suppose it has some history. In order to improve user experience, I think mpv should always set `--write-subs` regardless. And since `--all-subs` is **not recommended** by yt-dlp doc, maybe we should shift to explicitly use the expanded `--sub-langs all --write-subs`. Who knows if yt-dlp would deprecate and remove `--all-subs` tomorrow?

**Comment by FichteFoll** [comment]
> First of all, your last command works for me:

Yes, it was supposed to work and served as an example of how to work around the limitation.

Thanks for taking a look at the issue and already implementing a solution. Since the issue was easy to reproduce, I'll trust that the fix will work on my side (and will adjust my config on the next release since I cba to build from git regularly).
