### ISSUE TITLE
build mpv with libbluray

### ISSUE THREAD

**Issue by jsdfhasuh** [mpv-player/mpv#15173]
### Important Information

```text
- mpv version:0.39
- Platform version:windows
- Meson version:1.51
```

### Reproduction Steps

meson setup -Ddefault_library=static -Dprefer_static=true  -Dc_link_args='-static'  -Dcpp_link_args='-static'  -Dffmpeg:default_library=static -Dcplugins=enabled -Dlua=luajit -Dlibmpv=true  -Dlibbluray=enabled  --cross-file cross-file.txt build --force-fallback-for=zlib

### Expected Behavior

success

### Actual Behavior

Run-time dependency libbluray found: NO 

meson.build:680:12: ERROR: Dependency lookup for libbluray with method 'pkgconfig' failed: Pkg-config for machine host machine not found. Giving up.

### Log File

[meson-log.txt](https://github.com/user-attachments/files/17520580/meson-log.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of parameters, and conditions used in "Reproduction Steps".
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.

**Comment by kasper93** [comment]
You need to build libbluray and let Meson know where to find it. I'm happy to answer questions if you have any specific ones, but I won't do your job for you by detailing how to build and link every single dependency required to build mpv. Please refer to the Meson documentation, read about pkg-config, and understand the C build workflow. You will find all the information needed to accomplish your goal.

I'm closing this issue because it is not related to MPV itself.
