### ISSUE TITLE
Wrong colors when rendering paletted PNG

### ISSUE THREAD

**Issue by quilloss** [mpv-player/mpv#1530]
mpv renders paletted PNG wrongly when the option vo=opengl:srgb is used.

Sample PNG:
![basn3p08](https://cloud.githubusercontent.com/assets/8151080/5928029/748b17cc-a6b2-11e4-9802-4967a0672de6.png)

mpv output:
![screenshot](https://cloud.githubusercontent.com/assets/8151080/5928034/82564eb2-a6b2-11e4-9ac4-27ae9c925552.png)

Tested on lachs0r's 2015-01-27 Windows build (git-f6e05b1)

**Comment by haasn** [comment]
This is triggered by https://github.com/mpv-player/mpv/blob/master/video/out/gl_video.c#L1720

For some reason GL_SRGB does not play well with paletted PNG files, it seems. No idea what the root cause is. We can safely delete that entire if block if you want, at the expensive of a slight(?) performance loss. I'm not sure if anybody would care.

Would also allow us to remove is_linear_rgb completely, which makes the code a bit simpler.

**Comment by quilloss** [comment]
Would anyone even notice the difference performance?
Not that anyone opens PNGs in mpv in the first place.

**Comment by haasn** [comment]
It makes a (meaningful?) difference for RGB video as well. I haven't tested the performance.

**Comment by wm4** [comment]
@haasn: but why is it failing? This makes no sense to me. Unless the ``is_linear_rgb`` code path was broken in the meantime.

**Comment by wm4** [comment]
One thing is clear: it's a regression and works with 0.7.2.

I'm not opposed to removing the extra codepath, once we know we know why it fails.

**Comment by wm4** [comment]
OK, it's simple: srgb textures don't touch the alpha channel. But we have the red color component in the alpha channel, which we later move to the red channel. So the red component is broken. (This is done because PNG uses a component order order than RGBA - we fix this in the shader.)

So I guess I'll just remove this code.

**Comment by wm4** [comment]
Actually, it's the blue channel, not red.

**Comment by wm4** [comment]
Done.

>Would also allow us to remove is_linear_rgb completely, which makes the code a bit simpler.

It looked like it still has to be there, but maybe I didn't look closely enough when simplifying the code.
