### ISSUE TITLE
Cannot run latest mpv on windows 10 machine

### ISSUE THREAD

**Issue by dbojan** [mpv-player/mpv#15526]
### mpv Information

```bash
mpv-x86_64-20241217-git-e52f975.7z downloaded from https://github.com/shinchiro/mpv-winbuild-cmake/releases, tried some other releases, too.
```

### Other Information

```text
- Windows version: Microsoft Windows [Version 10.0.10586]
- GPU model, driver and version: Intel(R) HD Graphics 4400 , Intel driver, version 20.19.15.4326
- Source of mpv: https://github.com/shinchiro/mpv-winbuild-cmake/releases
- Latest known working version:
mpv 0.35.0-79-gc8a90001f2 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jan 08 12:30:07 2023
libplacebo version: v5.234.0
FFmpeg version: git-2023-01-06-fcd557a2c
FFmpeg library versions:
   libavutil       57.43.100
   libavcodec      59.56.100
   libavformat     59.34.102
   libswscale      6.8.112
   libavfilter     8.53.100
   libswresample   4.9.100

- Issue started after the following happened:
When I start mpv.exe

perhaps unrelated, latest ffmpeg build from https://www.gyan.dev/ffmpeg/builds/ works fine.
```

### Reproduction Steps

- download mpv-x86_64-20241217-git-e52f975.7z from https://github.com/shinchiro/mpv-winbuild-cmake/releases
- unzip
- try to run mpv.exe
- got message: The procedure entry point AdjustWindowRectExForDpi could not be located in the dynamic link

### Expected Behavior

running the mpv, without the error message

### Actual Behavior

error message

### Log File

it does not work, so there is no log file.

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by sfan5** [comment]
please try the mingw build from here and check if it also happens: https://nightly.link/mpv-player/mpv/workflows/build/master

**Comment by zhongfly** [comment]
note:AdjustWindowRectExForDpi
Minimum supported client:Windows 10, version 1607
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-adjustwindowrectexfordpi

**Comment by sfan5** [comment]
Nevermind. Your OS is just too old then and it's no longer supported.

**Comment by avih** [comment]
> Your OS is just too old then and it's no longer supported.

They claim to use win10.

Commit 1a3e3a0c98d41899481908de6362bb0fafc7cf8f says:
- w32_common: remove backward compatibility code No longer needed after 9f8b4b38c97f0697fbc3a9b30e4e856337cd6dcf.

Commit 9f8b4b38c97f0697fbc3a9b30e4e856337cd6dcf says:
- ci/mingw: use Ubuntu 24.04. This effectively bumps minimal MinGW-w64 requirement to v11.0.1. As it is available in the latest Ubuntu LTS. While at it clean installed packages list.

At no place it looks to me like a decition to drop some windows 10 happens visibly.

I don't think bumping to mingw 11 encapsulates "drop old win10 versions" (surely it can still be used to build for win7, for instance, not mpv, but in general).

At least the commit messages don't acknowledge explicitly that we're dropping support for some win10 versions.

Is this intentional or accidental?

@kasper93 ?

**Comment by avih** [comment]
Well, looks intentional according to ab3d0b73f799bfaaa018a3350a246a11c6a52feb , but it's an ugly move.

Claiming at the commit title/message "build: bump minimal Windows version to 10", but actually not even support all windows 10 versions.

And also that apparently it was raised at https://github.com/mpv-player/mpv/pull/14320 that there are systems before 1607 which are still supported till October 2025 (nearly a year from now), which was dismissed as "I can add a note to the readme, but frankly, I don't care that much about those."

This is really not nice.

**Comment by kasper93** [comment]
> Your OS is just too old then and it's no longer supported.

Correct. See the clarification on the supported OS versions here: https://github.com/mpv-player/mpv/blob/96bebf09354200fe2d89cc2e48089c542f63aeac/README.md?plain=1#L39-L40

> At no place it looks to me like a decition to drop some windows 10 happens visibly.

Yes, because the changes you are quoting are unrelated to the change in the minimum supported version. They are merely cleanup changes, mostly for the build process, and are more related to the use of newer MinGW than anything else. Note that mpv has never supported older versions of Windows on MinGW. See: https://github.com/mpv-player/mpv/blob/00cfe1e1fd9d4268d3d37bac3b3f49c4fd79c24e/DOCS/compile-windows.md?plain=1#L11-L12 I updated it here: https://github.com/mpv-player/mpv/blob/112fa549beb52ab3d75999c8d8a82936e13001c4/DOCS/compile-windows.md?plain=1#L13-L14 to make it less abrasive while still conveying the message.

> And also that it was raised at https://github.com/mpv-player/mpv/pull/14320 that there are systems before 1607 which are still supported till October 2025 (nearly a year from now), which was dismissed as "I can add a note to the readme, but frankly, I don't care that much about those."

Check the timeline and focus on the relevant aspects. Pull request #14320 was merged on September 24, two months after Windows 10 support was restricted to version 1607.

The actual version bump was made in https://github.com/mpv-player/mpv/pull/14338 (ab3d0b73f799bfaaa018a3350a246a11c6a52feb). This decision was based on multiple technical and practical reasons. The initial version of Windows 10 lacked many essential APIs that were included in subsequent updates, most notably support for long paths, high-DPI displays, and significant multimedia improvements.

> that there are systems before 1607 which are still supported till October 2025

I'm happy to provide security support for older mpv releases if required. For other upgrades, we can discuss pricing based on the features needed and the target platform.

As for Windows LTSC 1507, mainstream support ended a long time ago [2], and extended support lasts only until next year. This extended support is limited to critical security updates and enterprise-paid support. It is not intended for home or multimedia use.

Regarding older LTSC versions, even Microsoft acknowledges that legacy support may not be guaranteed [1]:
> The LTSC edition of Windows provides a deployment option for special-purpose devices and environments. These devices typically do a single important task and don't need feature updates as frequently as other devices in the organization. These devices are also typically not heavily dependent on support from external apps and tools. Since the feature set for LTSC doesn't change for the lifetime of the release, over time there might be some external tools that don't continue to provide legacy support. 

Furthermore, devices that cannot be upgraded to newer LTSC versions are unlikely to be intended for use with mpv. Of course, nothing prevents users from using older mpv versions that fully support such operating systems.

> it's an ugly move.

If you say so... Supporting Windows 10 1507 is akin to supporting Ubuntu 14.04.2 (which includes mpv 0.3.4), not even 14.04.6. I don’t understand why the mpv-player community should shoulder this burden. Surely, if you are deploying devices with a 9-year-old operating system, you don’t need a brand-new mpv release. That said, we can discuss a support contract for older mpv versions.

You also never explained why you consider this move "ugly." May I remind you that upgrading Windows 10 is free? Unlike support for Windows XP, Vista, or Windows 7, no users are being excluded here. This is solely their own decision not to upgrade, and they should adopt the same approach with mpv.

> <avih> wm4, despite being shitty sometimes, cared. rossy too. me too. eventhough none of us had these systems anymore.

(Especially considering the time wm4 removed Win32 support: a20ae0417f2d1e1a2c173f5eaf66a81974df0008)

I have invested thousands of hours of my free time into this project. You may not like me, but I find it deeply disrespectful to imply that I don’t care. I am a single individual maintaining support here. I am not Microsoft, nor do I have any financial backing. Microsoft has infinitely more resources, yet they no longer provide mainstream support for Windows 10 1507.

I would appreciate it if you chose your words more carefully.

[1] https://learn.microsoft.com/en-us/windows/whats-new/ltsc/overview
[2] https://learn.microsoft.com/en-us/windows/release-health/release-information

**Comment by avih** [comment]
> The actual version bump was made in #14338 ([ab3d0b7](https://github.com/mpv-player/mpv/commit/ab3d0b73f799bfaaa018a3350a246a11c6a52feb)).

Yes. I already mentioned where it was bumbed. I didn't say anything about the win10 bump - which this commit does. Only about also excluding versions before 1607.

Specifically, that it's not nice ("ugly move") to say "bump to win10" but in practice bump to win10 1607 (as evident from the readme and later commits).

And, judging by this issue, it broke in practice at commit 1a3e3a0c98d41899481908de6362bb0fafc7cf8f . Obviously the decision was made earlier.

I'm sure there are good reasons (you mentioned few), but I couldn't find them at the commit messages which I could dig up related to this, and the only thing I could find (which someone referred me to) was the discussion at #14320 , which explicitly discusses win10 before 1607.

> I have invested thousands of hours of my free time into this project. You may not like me, but I find it deeply disrespectful to imply that I don’t care.

I'm well aware of that, and I never said I don't like you. I think you do amazing work on mpv and you obviously care about it, but please keep your imagination in check, and don't put words into my mouth.

But about win10 before 1607 - which is the sole subject of my rant, you said just that. Here https://github.com/mpv-player/mpv/pull/14320 :

> I can add a note to the readme, but frankly, I don't care that much about those.

As for this:
> I would appreciate it if you chose your words more carefully.

Other than your own quote, I don't see where I was uncareful, but feel free to point to something specific.

**Comment by dbojan** [comment]
anyways ...
latest version that will work can be found here: https://www.videohelp.com/software/mpv-media-player/old-versions

either one of these:
https://www.videohelp.com/download/mpv-0.39.0-x86_64.7z
https://www.videohelp.com/download/mpv-0.39.0-x86_64-v3.7z
https://www.videohelp.com/download/mpv-x86_64-20240922-git-71f2220.7z

this one and newer will NOT work.
https://www.videohelp.com/download/mpv-x86_64-20240929-git-c3d9243.7z
