### ISSUE TITLE
cdda:// slow to react to volume changes and -af export troubles

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1558]
While playing cdda:// i noticed that mpv reacts very slowly to volume changes commands (it takes even 1.5 seconds till mpv change the volume since i give the command).
Possibly related, when i try to do some basic meter visualization through -af export filter:
```
-af export=/home/koko/.config/gambas3/Xt7-Player-mpv/.ExportFiles/export_2167:512
```
...the visualization meter updates itself one time at second, more or less; changing audio driver to jack doesn't make a difference; playing other media such as mp3 or ogg or flac works fine and the meter is updated even at 60fps.

Using --softvol=no makes mpv reacts fast to volume change commands, but the export filter problem is still present.

**Comment by kokoko3k** [comment]
Thanks, 
volume reacts better, but still, the visualization meters are choppy (8fps at most)

**Comment by wm4** [comment]
> but still, the visualization meters are choppy (8fps at most)

It's probably exactly 8 fps, because it filters 8 packets per second.

This is a problem with the ``export`` filter and the application reading it. The wrong way is writing some audio data without context to a shared memory area. The correct way is adding the data with a timestamp, and then trying to synchronize it to the actual playback time.

**Comment by kokoko3k** [comment]
Sorry, i'm not sure i understood completely.
Are you saying there is something i can do right now to parse more than 8 series of samples per second with the current implementation of export filter in mpv?

**Comment by wm4** [comment]
You could say the protocol makes no sense.

I'm not sure what your visualizer actually needs. Currently, af_exports writes only 512 samples per frame to the buffer, and throws the rest away. What it'd really need to do is passing _all_ data plus the samplerate plus a timestamp to the application - then _maybe_ it'd have a chance to render something close to correct.

If your visualizer updates only 8 times a second because the buffer got updated 8 times, it's probably broken as well. You'd really need to account for the fact that a buffer has a duration (i.e. the samples are played over the time), instead of assuming it's instant.

**Comment by wm4** [comment]
Or put in a simpler way: even if the buffer would contain 10 seconds of data, and updated once every 10 seconds, your visualizer should and can obviously update more often.

Just that the buffer exported by the mpv filter is too small, has no samplerate (you can't know how long it is), and has no timestamp (you can't know when it's played).

**Comment by kokoko3k** [comment]
Well, til now i blindly grabbed all of the available data at fixed intervals, and made a mean to visualize the current signal level (i even throwed away the "sync" field).
Of course this worked because the buffers were low.
