### ISSUE TITLE
How to encode to 10-bit x264 Hi10p using mpv?

### ISSUE THREAD

**Issue by Divetoxx** [mpv-player/mpv#1640]
It's a feature request. Please, couldn't You add such possibility? 8-bit is ugly!

**Comment by lachs0r** [comment]
Link FFmpeg with a 10-bit version of libx264. Yes, this generally means building your own.
I haven’t done this for my Windows builds because I was under the impression that this feature is mostly being used to transcode videos for devices (which generally do not support 10-bit video).

8-bit isn’t necessarily ugly either—just use a lower CRF.

**Comment by Divetoxx** [comment]
Are there any Linux mpv builds with 10-bit version of libx264? Binary builds, I mean. I'm not familiar with building my own, but I started to use Debian Jessie.

**Comment by ghedo** [comment]
The official Debian package for libx264 provides a 10bit version build as well. For example on the amd64 architecture the library is `/usr/lib/x86_64-linux-gnu/x264-10bit/libx264.so.142`, while on i286 it's `/usr/lib/i386-linux-gnu/x264-10bit/libx264.so.142`.

To make mpv use it, you need to preload it like so:

```
$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/x264-10bit/libx264.so.142 mpv ...
```

**Comment by Divetoxx** [comment]
I got it! Many, many thanks!
