### ISSUE TITLE
A press-release/news/blogpost for the v1.0 release

### ISSUE THREAD

**Issue by ChrisK2** [mpv-player/mpv#171]
As we know, press likes to copy&paste, so we should have something ready that outlines the features of mpv and its benefits over MPlayer/mplayer2 and VLC.

**Comment by wm4** [comment]
Seems like nobody is actually interested in writing/managing/whatever this either.

**Comment by hyiltiz** [comment]
Pity. Still, I enjoyed reading it and read it from first to the last sentence. Can imagine there are much more new features (like js scripting etc.) since, and there are some technical details that can be trimmed and summarized by (optimized decoding performance on modern hardware for all three major desktop platforms).
