### ISSUE TITLE
Feature request: Allow changing of profile flags from config file

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#1758]
I don't like mpv staying open after reaching EOF (83bd1280166117cd7aa40fc91a0e5e227fa68aef), but that is *not* the problem.

Apparently flags given on the command line have higher priority than flags in the config file, which makes any settings in the config competly useless for controlling this behaviour.
```
[cplayer] Setting option 'idle' = 'no' (flags = 4)
[cplayer] Setting option 'keep-open' = 'no' (flags = 4)
[...]
[cplayer] Setting option 'idle' = 'yes' (flags = 12)
[cplayer] Setting option 'keep-open' = 'yes' (flags = 12)
```

Would be nice if you could control which flags a profile sets or disable a profile.

**Comment by wm4** [comment]
You can define a ``pseudo-gui`` profile in your own config file. I don't remember if it overwrites the existing section or enhances it, but in any case you should be able to force your own options with it.

Something like:
```
[pseudo-gui]
keep-open=no
```

But I agree that this is a bit inconvenient. Possibly it would be better to do some magic so that the user's global config options are always preferred. I don't know.

**Comment by sarnex** [comment]
`````[pseudo-gui]
keep-open=no
idle=no`````
restored previous behavior for me.

**Comment by wm4** [comment]
I decided against it, and just documented how to override it: http://mpv.io/manual/master/#pseudo-gui-mode

(I also removed --keep-open.)
