### ISSUE TITLE
Occasional crash on OS X, how to debug?

### ISSUE THREAD

**Issue by WoLpH** [mpv-player/mpv#1768]
I've seen several random crashes, which mostly occur when exiting and/or going to the next file in rapid succession. The errors appear to be completely random and I've seen similar errors on 2 systems so I can most likely rule out hardware issues.

Version (installed through homebrew, updated yesterday):
```
mpv 0.8.3 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-04-03T11:32:41
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100
```

The actual crash reports:
https://gist.github.com/WoLpH/088f3795d94307c14682

**Comment by wm4** [comment]
We've had some problems with cocoa object lifetime. In the crash report you posted, it looks like cocoa outlived ``struct input_ctx``, so it probably happened on exit (because the player creates a single input_ctx on start end destroys it on exit). Normally, ``player/main.c`` unsets the input_ctx before destruction with ``cocoa_set_input_context(NULL);``. So this should certainly not happen.

I'd try again with git master, and see if it still happens. If it does, I'd probably sprinkle the code with printfs to see when input_ctx is unset/destroyed/still used from cocoa, or so.

**Comment by WoLpH** [comment]
Ok, I've been able to reproduce this with the latest revision of mpv :)

Most likely these are the steps to reproduce:
 - play a video or multiple videos and go to the end of the video (must be end of the playlist) until you get the white screen
 - press up/right to scroll forward, the result seems to be (had 2 cases) a crash

See the last two items in the gist:
```
mpv git-ab2a27a (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-04-12T17:38:46
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100
```

**Comment by wm4** [comment]
Don't know, must be yet another cocoa bug.

**Comment by wm4** [comment]
There have been some cleanups regarding synchronization in cocoa/OSX code, so please retry with master and open a new issue if you have problems.
