### ISSUE TITLE
vo_opengl: Better variable name for *p 

### ISSUE THREAD

**Issue by robin007bond** [mpv-player/mpv#1769]
When looking at the vo_opengl.c source code, I found that instances of the gl_priv struct are always declared in a variable called 'p'. Isn't there a better variable name for this? 

For example here:

``` 
struct gl_priv *p = vo->priv;
```

**Comment by haasn** [comment]
The only better name I could come up with is ```*s``` for ```state```.

**Comment by robin007bond** [comment]
>The only better name I could come up with is *s for state.
Wouldn't it be better to name it *state then? 

I'm not used to programming in C. Are one letter variables a best practice?

**Comment by wm4** [comment]
>Are one letter variables a best practice?

No, variable names should tell you what it is. But for something that often used, I'm perfectly fine with p, because everything longer would require a lot of typing and would just introduce noise to the code. Since it's used so often in the code, ``p`` changes into an easily to recognize convention.

**Comment by robin007bond** [comment]
Thanks for the clarification.
