### ISSUE TITLE
Should mpv take care of those corner issues?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1780]
Lately i've been facing some issues i think mpv should take care:

* --af=lavcac3enc + --audio-channels=n (solution: disable --audio-channels)
* --af=something + --ad=spdif:something (solution: disable audio filters)

All of them makes playback fail for obvious reasons, and since i can't see a single case where those options could coexist, i'm asking if the indicated solutions could be done internally by mpv itself

**Comment by wm4** [comment]
>--af=lavcac3enc + --audio-channels=n (solution: disable --audio-channels)

This doesn't make any sense.

**Comment by wm4** [comment]
To expand on this: ``--audio-channels`` also forces the demuxer to decode to the given number of channels (if possible - decoders like ac3 or dts support this, others don't).

Also, lavcac3enc only makes sense for audio over 2 channels (because 2 channels can go through toslink just fine), so there aren't really any useful values ``--audio-channels`` could be set to.

When the decoder is initialized, we can't know yet whether spdif is going to be used, because the filter chain is pretty opaque, and needs to be initialized with the decoder's output format, which in turn requires decoder init.

(This mess is mostly caused by lavcac3enc being too low level for this kind of stuff, but OTOH I don't care about spdif enough to make it more sophisticated. Just use HDMI and PCM.)

**Comment by kokoko3k** [comment]
Understood, thanks for the explaination.
However, if i'm not mistaken, for some reason mplayer was able to play (and encode the ac3 stream) even if -channels and -af lavcac3enc were called togheter.

**Comment by wm4** [comment]
Second point should be taken care of now.

**Comment by wm4** [comment]
I won't bother with improving the behavior with the transcoding filter.
