### ISSUE TITLE
Render ASS subtitle to video resolution and not to desktop res by default

### ISSUE THREAD

**Issue by Varshnyar** [mpv-player/mpv#1789]
I think this is very important because styled subtitles have very ellaborate signs that looks good at video resolution, but when a HD video is in fullscreen mode on a FullHD monitor, the subtitles looks anormally sharp, as if they were not part of the video. And this problem is aggravated when the video is 480p.

People that uses ASS subtitles usually recomend players that can use xy-vsfilter over VLC and other players whit libass (In Windows), just because that. So it would be amasing to see this corrected in mpv. 

I tried to open an Issue directly to the libass project, but they said that depends of the video player.

**Comment by wm4** [comment]
Rejected.

>People that uses ASS subtitles usually recomend players that can use xy-vsfilter over VLC and other players whit libass (In Windows), just because that.

Fuck them.

>So it would be amasing to see this corrected in mpv. 

Correct.

**Comment by haasn** [comment]
What about ```--vf=sub```?

**Comment by wm4** [comment]
This would emulate it, but is slower than necessary.

**Comment by wm4** [comment]
Also see https://github.com/libass/libass/issues/172

**Comment by haasn** [comment]
I have thought about providing a way to do this directly, it would be very easy with the existing ```blend-subtitles``` code - just run the blending function before upscaling instead of upscaling.

The main reason I decided not to add it already is because ```--vf=sub``` was a thing. Maybe this should be revisited?

Personally, my vision for this would be being able to distinguish between “typesetting” and “normal” subtitles (ie. text at the bottom of the screen). I'd only want typesetting to be drawn at the video's res, ideally. But there's no existing mechanism for this in mpv (there's some stuff related to ass style overrides, but as far as I can tell it's not exported).

Either way, as long as the user is content with all subtitles being at a lower resolution, this is an easy change.

**Comment by wm4** [comment]
>Personally, my vision for this would be being able to distinguish between “typesetting” and “normal” subtitles (ie. text at the bottom of the screen). I'd only want typesetting to be drawn at the video's res, ideally. 

That's what someone on #libass was thinking too. But with the current format, you can't distinguish them. (Although the style override stuff tries to apply a heuristic.)

**Comment by haasn** [comment]
Do you think there's value in exporting this heuristic? (In the sense of making it available in ```struct osd_object``` somehow)

Could add an option like ```blend-subtitles-res=<video|display|video-ts>``` or whatever, which would switch between “blend all at video res”, “blend all at display res” and “blend TS at video res and rest at display res”.

**Comment by wm4** [comment]
I don't think there's much sense in it if the heuristic is far from perfect, and also it would add tons of complexity. Does xy-vsfilter (or whatever is the most popular variant these days) do anything into this direction?

**Comment by haasn** [comment]
> Either way, as long as the user is content with all subtitles being at a lower resolution, this is an easy change.

Done in https://github.com/mpv-player/mpv/commit/6f46bafbd06e6a107e55f35860744ed66c1b8426

This also addresses https://github.com/libass/libass/issues/172 at least as far as mpv is concerned.

**Comment by wm4** [comment]
The option which enables this was changed in 2b679020f7b7ba957f92bcaabacf38d50b856810.
