### ISSUE TITLE
--no-terminal changed on Windows

### ISSUE THREAD

**Issue by ponyo** [mpv-player/mpv#1793]
I am used to putting --no-terminal on the command line so that mpv keeps on running even if you close the console.

After upgrading from 2015-02-03 to 2015-03-28 this no longer works.

Can you please restore this feature some how. It is great.

**Comment by wm4** [comment]
This wasn't a "feature" known to developers, and it was not explicitly removed. Rather, it's probably random behavior that accidentally changed due to an unrelated change. Maybe.

If you want to start mpv without console, start mpv.exe, if you want a console, start mpv.com. Isn't that enough?

**Comment by wm4** [comment]
There's a new build now, which changes all the behavior anyway.

**Comment by rossy** [comment]
> There's a new build now, which changes all the behavior anyway.

Yep. The new behaviour should be easier to use. Now mpv.com will always attach to the console and close when the console is closed, and mpv.exe will never attach to the console, so it stays open when the console is closed. The --terminal flag changes whether mpv calls SetConsoleMode and writes to the console, but it no longer affects whether it attaches or not.

**Comment by ponyo** [comment]
Thanks rossy.

Is it possible to make --terminal work with mpv.exe again? Now mpv.exe never writes to the console.

**Comment by rossy** [comment]
You have to launch mpv.com if you want mpv to attach to the console. mpv.exe behaves like a real GUI application now.

The reason for this change is that in Windows, you can't really have a program that's both a GUI program and a command-line program. There is a field in the program's header that determines whether it creates/attaches to a console on startup or not. cmd.exe and PowerShell check this field to decide whether to write the next prompt immediately after starting the program or to wait for the program to finish (because the program is going to attach to the console and write stuff.) Because those shells never expected the old mpv.exe to attach to the terminal, they'd always wrote a prompt over mpv's output, which was kind of ugly.

More information here: http://blogs.msdn.com/b/oldnewthing/archive/2009/01/01/9259142.aspx

mpv.com and mpv.exe now work pretty much exactly like devenv.com and devenv.exe from Visual Studio with regards to how they attach to the console.

**Comment by ponyo** [comment]
That is interesting about the header. So all you have to do is change that value to make any executable behave how you wish.

**Comment by rossy** [comment]
Yep. objcopy from binutils can change that field. I think the commands are ``objcopy --subsystem=console myexe.exe`` and ``objcopy --subsystem=windows myexe.exe`` for changing a program to console mode and GUI mode. editbin from Visual Studio can also do this.

As mentioned on that blog, programs like cmd.exe read that field and alter their behaviour when launching each type of program, which is why mpv has both mpv.exe and mpv.com, so users who want GUI behaviour can launch the former, and users who want console behaviour can launch the latter.

**Comment by wm4** [comment]
>So all you have to do is change that value to make any executable behave how you wish.

Or just use mpv.com. Or use a unix, if you want proper behavior. But even on unix, closing the terminal will by default kill the application (because that's how things work), unless you detached it explicitly.

So I'm closing this.

**Comment by ponyo** [comment]
> Yep. objcopy from binutils can change that field.

Nice, I didnt know about objcopy.
