### ISSUE TITLE
--no-pseudo-gui

### ISSUE THREAD

**Issue by ponyo** [mpv-player/mpv#1803]
Is there room for an option to disable automatically loading the pseudo-gui profile.

**Comment by rossy** [comment]
You can effectively disable it by overriding its options in your config:

```
[pseudo-gui]
terminal=yes
force-window=no
idle=no
```

Though, I'm not sure why you'd want to do this. On Windows, the pseudo-gui profile should only be enabled under specific circumstances: when mpv has no console and no stdio handles. In this case, mpv would close immediately if it didn't have a file, and if it had an audio file, it wouldn't have any interface and it would have to be killed by the Task Manager. --idle=once and --force-window are added to prevent this situation. If the pseudo-gui profile is being enabled when it isn't needed, that's probably a bug.

**Comment by wm4** [comment]
A profile just sets a list of options, this it's not possible to unset it. (Because then you'd either have to know and store the previous option values, or somehow invert them, both for which no mechanism exists.)

The intention is that you don't cause pseudo-gui to be set in the first place by e.g. using mpv.com.

**Comment by ponyo** [comment]
Cant you stop the profile from loading in the first place.

--force-window is OK but I dont need an empty mpv window if there is nothing to play.

Or if you want mpv to always use --idle=yes then you have to add it to [default] as well as [pseudo-gui] which is lame.

**Comment by rossy** [comment]
> I dont need an empty mpv window if there is nothing to play.

This only happens when mpv would otherwise do nothing and close immediately. I'm not sure why someone would want to preserve this behaviour. It's not normal for an .exe to do absolutely nothing when double-clicked on, so instead of that it shows a window (that files can be dropped on.) If mpv can write a help message to the console or a pipe, it does that instead and doesn't show the window.

> Or if you want mpv to always use --idle=yes then you have to add it to [default] as well as [pseudo-gui] which is lame.

Agreed. This is admittedly a bit more lame than it was before. Still, I'm not sure what your use-case is. If you want to opt-out of the pseudo-gui stuff entirely, as wm4 said, just launch mpv.com instead of mpv.exe. What you are asking for is a way to disable pseudo-gui while still using mpv.exe, and I'm not sure why someone would want to do this (when mpv.com is right there, and never uses pseudo-gui mode.)

**Comment by ponyo** [comment]
> What you are asking for is a way to disable pseudo-gui while still using mpv.exe, and I'm not sure why someone would want to do this (when mpv.com is right there, and never uses pseudo-gui mode.)

Thats exactly what I want to do.

So that I can use mpv.exe instead of mpv.com when I want to close the console.

**Comment by wm4** [comment]
Closing the console without killing the program was never supported.

**Comment by ponyo** [comment]
How is it not supported. Thats how it works on Windows. mpv.exe.
