### ISSUE TITLE
Config sections based on decode-acceleration status not working

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [mpv-player/mpv#1813]
I would like to have MPV exhibit this behavior:

 * If the video CAN be hardware-accelerated:  
Decode it in an accelerated manner, and display the output via `vo_opengl` with high-quality presets. (If `vo_opengl` fails, use `vo_vdpau`.)
 * If the video CANNOT (for whatever reason) be hardware-accelerated:  
Use `vo_vdpau` if possible, otherwise use `vo_opengl` (NON-HQ preset) to display video.

This behavior is needed since `opengl-hq` is unusably laggy with software decoding of HD video, but it looks better than `vdpau` or `xv` and so should be used where possible.

The way I tried to do this was:
````
hwdec=auto
vo=vdpau,opengl,xv

[hwdec.vdpau]
vo=opengl-hq,vdpau
````

But it seems that *either* **`vo` cannot be set with config-sections**, or that **`[hwdec.*]` config sections are ignored** (or possibly both?)

Either way, this behavior is somewhat important, and MPV cannot be made to use it, and so I am registering this bug in the hopes that it will be fixed.

**Comment by rr-** [comment]
Is it really this important? You can set renderer manually once per machine and problem solved.

**Comment by wm4** [comment]
These profiles are loaded when a file is loaded, but before the file is even opened. It can't take any action on things that are determined later, like what codec it uses. There's no profile auto loading for anything related to hwdec either. Only a few specific things have such a mechanism. (They're basically inherited from MPlayer, and there was never an attempt to improve them in mpv. And there probably won't be - a much better auto-profile mechanism could be written as a Lua script.)

Due to mpv's architecture, the VO can't be changed while video is decoded, and no video can be decoded while there's no VO (and in fact, most forms of hw decoding require a VO to be active, so the decoding/rendering-interop can be setup at all). So it's not possible to make a decision about which VO to use based on which form of decoding is used.

So what you want is not possible (except maybe with a major redesign). In theory it would be possible to implement a simpler but similar solution by using vo_opengl's vdpau interop by rendering not only hw-decoded data with it, but also sw-decoded data, but I'd rather not.

I'd just try if you can reduce your settings a bit, so it gets faster. For example, hardware decoding with vdpau disables vo_opengl's chroma sampling, so surely you can just switch the chroma scaler to bilinear for sw decoding too.

**Comment by JamesTheAwesomeDude** [comment]
@rr- It's not a machine-specific thing. On my main desktop, I have some H.264 files which will properly get hardware-decoded, and some which don't.

For example, [Commie] Steins;Gate subs get hardware-decoded perfectly, but with [WhyNot] Steins;Gate subs - same container (MKV), same codec (H.264), on the same machine (MPV x86_64 on Linux on a Pentium 4 with a Radeon HD 4350), it doesn't work. (The error being related to a slight anomaly in [WhyNot]'s video encoding which the hardware decoder chokes on - something about a certain type of frame not being early enough in the video.)

Now, when viewing the [Commie] subs, since the video is hardware-decoded, my CPU usage is like 5-8% and so I can use the pretty `opengl_hq` output. But when watching things from [WhyNot], my CPU is maxed out and so I have to use `vdpau` output, else watch unwatchably laggy video.

It would be nice if MPV could automatically select the "pretty" VO when it's feasible to use it, and use the fast VO when stuck with software decoding.
