### ISSUE TITLE
2-pass encoding for HQ GIF?

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1836]
From FFmpeg 2.6, it's possible to generate high quality gif using palettegen filter: 

```
#!/bin/sh

palette="/tmp/palette.png"

filters="fps=15,scale=320:-1:flags=lanczos"

ffmpeg -v warning -i $1 -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2
```

It's two pass, first pass for palette generation and second pass for generation of gif with generated palette from first pass.
Can this be acomplished using mpv's encoding options?

I've tried `mpv -v -o palette.png -ofps 25 -vf lavfi=palettegen input.mkv` at first for test purpose,  but it does not output anything and stalls, with next log:
```
...
[vf] Video filter chain:
[vf]   [vd] 1280x720 yuv420p10 BT.709 (HD)/TV CL=mpeg2/4/h264
[vf]   [in] 1280x720 yuv420p10 BT.709 (HD)/TV CL=mpeg2/4/h264
[vf]   [lavfi] 16x16 rgba RGB/PC CL=mpeg2/4/h264
[vf]   [out] 16x16 rgba RGB/PC CL=mpeg2/4/h264
```

Any advice would be helpful. Thank you.

**Comment by wm4** [comment]
There's no way to open the palette a separate video stream and to feed it to the paletteuse filter. Although possibly it could be done within the filter graph.

I don't know why generating the palette stalls.

**Comment by xylosper** [comment]
Thank you for saving me from hopeless tries.

**Comment by wm4** [comment]
Actually it works for me. I had to change the mpv option parser to allow full lavfi graph strings, though.

This command of yours works:
``mpv -v -o palette.png -ofps 25 -vf lavfi=palettegen input.mkv``

But it takes a while to complete, and it will decode the whole file. ``--length`` or ``--end`` do not work. This is because these are applied after libavfilter output. With palettegen, libavfilter only outputs one frame; the one that is output once no more input frames are available. ``--start`` might be broken too, because seeking is again applied after libavfilter output. Basically, this filter breaks everything for mpv, but it was probably "convenient" for ffmpeg.c (cc @ubitux).

This command can use the palette: ``mpv -v -o test.gif -length 2 -ofps 25 -vf lavfi="[movie=palette.png [b] ,  [in] [b] paletteuse]" input.mkv``

I had to change the option parser (8e0cf9d878cd25977d0de312c5746117fe33c6a9) to allow nesting the ``[`` and ``]`` (though you could also use ``"`` for quoting).

**Comment by wm4** [comment]
It's a bit faster when skipping most frames when generating the paltte: ``--vd-lavc-skipframe=nonkey``

**Comment by xylosper** [comment]
Thank you for instruction. I could create gif following your explanation.
So, basically, this requires 3-pass encoding to clip some range.. maybe I have to handle this special case. Thanks alot!
