### ISSUE TITLE
Can't run show_progress from Lua

### ISSUE THREAD

**Issue by Kagami** [mpv-player/mpv#1844]
Hi. For some reason I can't run command "show_progress" from the Lua script. It works for the input.conf (i.e. it shows on "P" press) and other commands like "show_text" are working correctly.

Looks like it runs without errors (note the console log) but does nothing.

```bash
$ cat 1.lua 
function show_progress()
    print("Inside fn")
    mp.commandv("show_progress")
end

mp.add_key_binding("a", show_progress)

$ mpv --no-config --script 1.lua --quiet 1.webm
Playing: 1.webm
 (+) Video --vid=1 (vp9)
 (+) Audio --aid=1 (*) (opus)
[vo/opengl/x11] Disabling screensaver failed.
AO: [alsa] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
[1] Inside fn 


Exiting... (Quit)

$ mpv --version                                
mpv git-88d3058 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.22.101
   libavcodec      56.34.100
   libavformat     56.30.100
   libswscale      3.1.101
   libavfilter     5.14.100
   libswresample   1.1.100
```

**Comment by wm4** [comment]
``mp.commandv()`` by default disables OSD display for all commands. (Except ``show_text``, which is special as in it always displays things on OSD regardless of settings.) So, for ``show_progress`` you have to explicitly enable OSD, like with ``mp.commandv("osd-msg-bar", "show_progress")``. You can also just do ``mp.command("show_progress")``, because ``mp.command()`` is pretty much exactly the same input.conf does, and has OSD enabled by default.
