### ISSUE TITLE
mpv + avs-scripts: linking mpv with ffmpeg

### ISSUE THREAD

**Issue by hollysheep** [mpv-player/mpv#1861]
hi,

i've installed ffmpeg on ubuntu with enabled avisynth-support (i use avxsynth) and i can pipe avs-script with ffmpeg to mplayer. ffmpeg isn't compiled by me, it's installed with apt-get. now i build mpv using this guide https://github.com/mpv-player/mpv-build for some times (the "normal" instructions and the debian/ubuntu instructions). but i can't play avs with mpv. i just complied program from source for a few times. i have a working ffmpeg, so i think the best way is to link mpv with ffmpeg. how can i do this? to i need to compile it with some secial settings or start mpv (installed via apt-get) with some special commands?

the other way is to build mpv and ffmpeg from source. i assumed this i done with the guide i've linked above - but this seems to be wrong. is there any guide to build ffmpeg with avs-support and link mpv to ffmpeg?

hollysheep

**Comment by wm4** [comment]
mpv-build is a helper to compile ffmpeg, libass, and mpv in one go. If you want to use system ffmpeg, you can compile mpv standalone. The instructions slightly change; it's described in the README in the main repo. Just make sure you actually have a new enough libass.

**Comment by hollysheep** [comment]
it's enough to build mpv from source and the system ffmpeg is used without any extra option? then it should work with mpv installed with apt-get or not?

what readme do you mean? i can find the one i've linked.

the libass is just for decoding ass subtitles? but this should not have anything to do with playing an avs script?

**Comment by wm4** [comment]
>it's enough to build mpv from source and the system ffmpeg is used without any extra option? then it should work with mpv installed with apt-get or not?

Yes.

>what readme do you mean? i can find the one i've linked.

https://github.com/mpv-player/mpv#compilation

>the libass is just for decoding ass subtitles? but this should not have anything to do with playing an avs script?

It's a required dependency and not only used for ass subtitles.

**Comment by hollysheep** [comment]
hmm, doesn't when i install mpv with apt-get. can i check mpv uses the system ffmpeg? ffmpeg can pipe an avs with 'ffmpeg -i script.avs -f avi | mpv -" but mpv can't play the avs directly ("mpv script.avs").

which version of libass is required?

**Comment by hollysheep** [comment]
the guide you've linked links to the guide i've linked above :-) this should be the same, or not?

i can enable a lot of features with waf configure, but there is no --enable-avisynth in './waf configure --help'

**Comment by wm4** [comment]
Right, now I remember that the ffmpeg avisynth wrapper can't use custom IO, so it won't work with mpv. You should be able to use ``mpv av://avisynth:script.avs`` though, which works around rhe custom IO.

I recommend not using avisynth (especially on Linux it's almost 100% useless), and using Vapoursynth instead.

**Comment by wm4** [comment]
>the guide you've linked links to the guide i've linked above :-) this should be the same, or not?

No, the one you linked is mpv-build, which is a set of scripts.

**Comment by mc4man** [comment]
@hollysheep  What you may want to decide if using Vapoursynth is  - 
does mpv only use a shared Vapoursynth?
If so then I'd be inclined to build both Vapoursynth & mpv off of same ffmpeg or libav shared rather than Vs from a shared ffmpeg/libav & mpv from a static ffmpeg/libav. (though maybe that's possible, feels wrong here.

**Comment by hollysheep** [comment]
mpv av://avisynth:script.avs doesn't work

"[lavf] Unknown lavf format avisynth
Failed to recognize file format."

i use avxsynth, not avisynth, but should be the same.

**Comment by qyot27** [comment]
You didn't specify *which* release of Ubuntu you're using.  If it's prior to [the just released yesterday] 15.04, then the repo version of FFmpeg isn't actually FFmpeg, it's Libav, and it's not built with --enable-avisynth.  Thus, linking mpv against it won't do that.  15.04 reintroduces the new FFmpeg package from Debian unstable, which should be built with --enable-avisynth from what I read on the mailing list.  You'd need to pull in the -dev packages first, though.

And there shouldn't be any issues with a plain ```mpv script-name.avs```.  The issue is just whether the FFmpeg you think you're linking against really has AviSynth support enabled.

If you compiled FFmpeg yourself make sure that PKG_CONFIG_PATH is pointing to the right directory when you run mpv's ```./waf configure```.

**Comment by hollysheep** [comment]
yes. i'm sure my ffmpeg is build with --enable-avisynth. when i pipe an avs to mpv with 'ffmpeg script.avs -f avi pipe: | mpv -' i see all features ffmpeg was build and there is --enable-avisynth.

you're writing that the new ffmpeg in ubuntu 15.04 is build with --enable-avisynth and it should work with mpv. my ffmpeg is also build with --enable-avisynth, but it doesn't work (version 2.6.2). whats the difference between the ffmpeg in 15.04 and mine?

wm4 has written "ffmpeg avisynth wrapper can't use custom IO, so it won't work with mpv". you say it should work. sorry, but i'm confused.

i use ubuntu 14.10.

**Comment by hollysheep** [comment]
other question: i read in the libav documentation, that only avisynth 2.6 (and i think avxsynth based on avisynth 2.6) is supported, not 2.58. i use avxsynth 4.0 based on avisynth 2.58. does ffmpeg support avisynth 2.58? maybe

**Comment by wm4** [comment]
>wm4 has written "ffmpeg avisynth wrapper can't use custom IO, so it won't work with mpv". you say it should work. sorry, but i'm confused.

Hm, maybe it could work after all. I never tested it, but it's pretty clear that avisynth can't use the custom IO.

**Comment by qyot27** [comment]
AvxSynth is based on 2.5.8, with some backports from 2.6.  The reason it's exempt from the restriction on Windows AviSynth builds is because it's A) a separate library with a separate header, and B) it's currently the only version of AviSynth natively available on Linux and OSX, so there is no version confusion at this time (and the thing that could cause version confusion in the future won't, because when AviSynth+'s non-Windows support is complete, it'll use 'libavisynth' as a library name).

>Hm, maybe it could work after all. I never tested it, but it's pretty clear that avisynth can't use the custom IO.

I test scripts on Windows all the time and also use mpv as a quick transcoder to ffvhuff in my DVD authoring workflow, I've never had to use the av:// tactic.

But some evidence with a freshly built AvxSynth-git, FFMS2-git ([from my non-autotools/C-plugin staging branch, since the recent total de-Haali-fication of FFMS2 won't let AvxSynth-git compile libavxffms2 until that gets updated - you have to build the plugin from the FFMS2 sources themselves for right now](https://github.com/qyot27/ffms2/commits/patches)), FFmpeg-git, and mpv-git on Ubuntu 15.04 (the versioning looks weird because it's from my 'extra-new' branch...which is mostly bikeshedding and the tedious cross-compile guide):
```
[~:$] mpv
mpv r41118 git-45c5cf6 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Sat Apr 25 13:26:05 EDT 2015
ffmpeg library versions:
   libavutil       54.23.101
   libavcodec      56.35.101
   libavformat     56.31.100
   libswscale      3.1.101
   libavfilter     5.14.100
   libswresample   1.1.100

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options

[~:$] cd Videos/avxsynth/
[avxsynth:$] ls
daybreak_test.avs
[avxsynth:$] mpv daybreak_test.avs 
Playing: daybreak_test.avs
 (+) Video --vid=1 (rawvideo)
 (+) Audio --aid=1 (pcm_f32le)
AO: [alsa] 44100Hz stereo 2ch float
VO: [xv] 848x480 yuv420p
AV: 00:00:00 / 00:05:00 (0%) A-V:  0.000
[vo/xv] X11 can't keep up! Waiting for XShm completion events...
AV: 00:01:35 / 00:05:00 (31%) A-V:  0.497

[snip out the 'too slow, use framedrop' message]

Exiting... (Quit)
```

And it was also working just fine like that on 14.10 before I did my usual 6-month fresh install.  There is clearly a breakdown somewhere; AvxSynth's wiki is a prime source for the confusion because the build instructions there haven't been updated practically since they moved to Github...nearly 3 years ago.  Up-to-date instructions are in the Doom9 thread - jump to the end of the thread and then track backwards until you find them.

Can x264 see and use AvxSynth?  If it also can't, the problem isn't in FFmpeg or mpv, it's probably because AvxSynth wasn't installed correctly or you didn't run ```sudo ldconfig```.  Unlike FFmpeg, x264 has its AviSynth support enabled by default, and while it uses the same dlopen method FFmpeg does, it's a different codebase.
