### ISSUE TITLE
set stream-pos property

### ISSUE THREAD

**Issue by v-control** [mpv-player/mpv#1862]
If I set the time-pos property, playback continues at the given time. If I set the stream-pos property, playback stops. If I read the stream-pos property after that, I get the correct value (the one I used to set the stream-pos property), but in the video mpv is still at the position where it stops. The displayed frame is not updated.

Maybe this is not an issue and I misunderstood the functionality of the stream-pos property? I thought it points to the start of the next chunk of data that is buffered.

**Comment by wm4** [comment]
``stream-pos`` (both reading and writing) is a pretty obscure property; I'm not even sure why it exists. It's not recommended to be used, because it forced the demuxer thread to stop temporarily.

I'm not sure why playback stops in your case. It probably depends on the demuxer - the demuxer will usually not appreciate if you change the stream position without its knowledge. In what case are you trying to use it and why?

**Comment by v-control** [comment]
Hi wm4, thanks for your reply.
The main idea was to archive a seamless looping. I mean really seamless (or gaples). On a rotating object in a movie, the rotation continues with no frame delay if the file loops. My approach is to wait for `stream-end` and then set the next data to read to stream start position.
I'm using the client API in a Qt environment.

**Comment by wm4** [comment]
This will not work, or even if, only for some very primitive formats (like uncompressed raw formats without timestamps). Try to use the A-B loop facility instead. I can't guarantee it will be gapless, but should work pretty well, at least as long as the "A" point is on a key frame. (Look for the ``ab-loop-...`` properties.)

**Comment by wm4** [comment]
Well, I delivered an explanation. Closing.
