### ISSUE TITLE
Have cache settings changed?

### ISSUE THREAD

**Issue by jashandeep-sohi** [mpv-player/mpv#1870]
In version ``0.9.0``, has the default caching behaviour been changed?
For instance, when playing ``f4m`` streams now, the entire video is "cached".
Is this expected, or a bug?

Edit:
For example, if I try to play this test youtube video (using the ytdl plugin), the cache keeps on increasing until the entire video is loaded (into memory!!):

```$ mpv --ytdl 'https://www.youtube.com/watch?v=Eho8HDtkCiU'```

**Comment by jashandeep-sohi** [comment]
Okay, to answer my own question, yes it was changed by this commit:
https://github.com/mpv-player/mpv/commit/1eeeab2e1490d99b41d3585b4082f8bd404a4da6

Now, the obvious question is, why is the default 150MB?
Isn't that a bit too much?

**Comment by wm4** [comment]
Why is it much?

**Comment by jashandeep-sohi** [comment]
I suppose it's personal preference, but in my case I end up wasting more bandwidth.
For instance, if I'm 30 sec into a youtube video and decide I don't want to watch it anymore, by that time a significant chunk of the video has been downloaded for which I have no need.

IMHO, a cache should be as little as possible. Was there a particular reason why it was increased to 150 mb?

**Comment by spaghetti2514** [comment]
>I end up wasting more bandwidth

If you have a cap of some kind, you can always limit your cache in the config file. Most people as far as I know tend not to have one, so why would the defaults be configured towards a minority of users?

>a cache should be as little as possible

I'd disagree. I've had my cache set to 200MB since well before the commit that changed the default. I think it a fair assumption to make if a user opens a video, they are more likely to want to actually watch that video than not, so why configure towards a less common event?

I could see this being an issue on say, a mobile media player, where data caps and lesser hardware are a major concern, but this is not that, and those less frequent use cases should be handled through configuration.

**Comment by jashandeep-sohi** [comment]
>If you have a cap of some kind, you can always limit your cache in the config file.

I am now.
But I don't have a cap,  I just don't want pointless transfers. 

>Most people as far as I know tend not to have one, so why would the defaults be configured towards a minority of users?

Fair enough. If most users want the defaults increased, I have no problems with that. Although, I wasn't aware this was a request.

>I'd disagree. I've had my cache set to 200MB since well before the commit that changed the default.

Why?

>I think it a fair assumption to make if a user opens a video, they are more likely to want to actually watch that video than not, so why configure towards a less common event?

Even if that is the case, what's the harm in downloading as little as possible?

**Comment by spaghetti2514** [comment]
>Why?

Personally, so I can seek back and forth a decent amount of time without having to deal with buffering
>what's the harm in downloading as little as possible?

What's the harm in downloading more?

**Comment by jashandeep-sohi** [comment]
> What's the harm in downloading more?

Like I said, the whole bandwidth issue.

**Comment by spaghetti2514** [comment]
I'm not seeing what part of this is an issue so long as you don't have a cap.

**Comment by haasn** [comment]
I think there are two separate issues here. There is a difference between the cache size, and the lookahead distance.

Even with a 200 MB cache, if you only ever download 10 MB in advance, you would get the best of both worlds, bandwidth-wise: the ability to seek backwards at will, *and* the ability to avoid unnecessary data transfer.

For me, the cache mostly fulfills the latter role - it's rare that I'm able to download significantly in advance; but I still want to use a huge cache so that I can seek backwards at will.

From the mpv manual
```
Note that half the cache size will be used to allow fast seeking back. This is also the reason why a full cache is usually reported as 50% full. The cache fill display does not include the part of the cache reserved for seeking back. Likewise, when starting a file the cache will be at 100%, because no space is reserved for seeking back yet.```

Maybe it would be for the better to make this “50%” figure configurable? So I could reserve, say, 95% of the cache for backwards seeking, and only 5% for buffering in advance.

(Also, as for the lookahead size, I think it should be at least long enough to be able to lose your connection to the server, reconnect, and continue downloading without any interruptions to playback)

**Comment by kevmitch** [comment]
For what it's worth, the YouTube web app itself appears to download the entire file as fast as possible to ensure smoothest possible playback and fastest seeking. I think this is a good design decision. You're going to download the whole file eventually (except in the rare case you don't actually watch the whole thing), so why not get it done as soon as possible? That way if the available download speed is unreliable, you minimize the likelihood of under-runs. This also allows your wireless card to enter any power saving  mode it has sooner, which is generally a net win.

**Comment by jashandeep-sohi** [comment]
I like @haasn 's idea, but I'm not sure if it's worth the effort/time if only few users need it.
@kevmitch also brings up some good reasons one might want larger caches.

Version 0.9.x has been out for couple of days now, and since I'm the only one who seems to be complaining about this, most users probably don't mind the new defaults.
In lieu of this and because I've resolved my problems by reducing the cache settings, I'll close this issue now.
