### ISSUE TITLE
Allow user-defined aliases for command-line options

### ISSUE THREAD

**Issue by sbraz** [mpv-player/mpv#1875]
With some options getting longer like `-start` instead of `-ss` or  `-sub-file` instead of `-sub`, It would be nice to allow users to map custom switches (or legacy mplayer ones) to known options.
A simple config file with each line binding an `alias` to an `option` would probably be enough. This file could probably be system-wide and overridden by each user, like `input.conf` or `mpv.conf`.

**Comment by wm4** [comment]
Specific suggestions how this should be implemented would be helpful. (I don't consider this a priority, so I prefer not to think too hard about it myself.)

**Comment by sbraz** [comment]
Well, I never looked at the code but what I'm thinking about would be a file in this format: 
```
sub sub-file
ss start
```
Parsing the file would return a mapping like `{'ss': 'start', 'sub': 'sub-file'}`
Then, at runtime you would do something like this before parsing the options (wrote it in Python because I'm familiar with it):
```python
for a in argv:
  if a == "--": # stop handling options
    break
  if a.startswith("-") and a.lstrip("-") in aliases: # starts with an hyphen and is a known alias
    a = "-" + aliases[a.lstrip("-")] # replace the current argument with the real option
```
Of course, this does not prevent an user from creating a mapping to a non-existent option but that would be handled afterwards when the real options are parsed so it's probably not an issue.

**Comment by qmega** [comment]
Maybe there should be some more generic, pluggable system for transforming command line arguments, so mpv wouldn't have to implement them all itself. There are other cases where you might want to change the arguments mpv gets, such as #1512, and this which I personally use:
```python
#!/usr/bin/env python

# Wrapper for mpv to decode SFTP URLs, because KDE gives them to us
# encoded but ffmpeg wants them plain.

from sys import argv
from urllib.parse import unquote
from os import execv

MPV = '/usr/bin/mpv'

execv(MPV, [MPV] + [
    unquote(url) if url.startswith('sftp://') else url for url in argv[1:]
])
```
Not sure what the best way to have mpv connect to that kind of thing would be, though. The first thing that comes to mind is an option with a list of external scripts/programs, where each one would take a json-encoded list of arguments on stdin and output the same on stdout.

**Comment by wm4** [comment]
>Maybe there should be some more generic, pluggable system for transforming command line arguments

Maybe there shouldn't. So what's wrong with a wrapper script?

**Comment by qmega** [comment]
The wrapper works fine for me. I was just responding to your request for implementation suggestions for this issue, thinking that maybe some others could be solved at the same time. Since this is at least the third situation I know of where transforming command line arguments is desired, it stands to reason there may be more, and some people may want more than one. Implementing all of them directly in mpv could get pretty bloated, especially in specific cases like #1512 where you'd probably have to link against a bunch of KDE stuff. Making the system pluggable frees mpv from the dependencies and maintenance responsibility of each individual thing, and lets users implement special cases themselves, kind of like the lua scripting interface currently does.

A wrapper is in an ideal position to do this job (and I'm fine with it, like I said), but it does have disadvantages compared to a built-in solution, particularly for less technical users:
* You have to either make sure it's in your path before mpv or set up shell aliases and modify the desktop file.
* If you want to do multiple transforms, you can't just use two scripts that other people have written, you have to put them together somehow or get one to call the other. (Unless the wrapper itself is modular, but I don't see this being used enough that anything like that would get standardized.)

Now that I think about it, though, if an option were used, there'd be a pretty big problem in terms of figuring out when such an option would be parsed, since it could change other ones. Maybe a better way would be an environment variable that would be handled very early. But in any case, the more I think about it, the less useful it seems, so if you're rejecting it as too complicated, I'm totally fine with that.

**Comment by haasn** [comment]
My main use case for this feature was for ```-f ID``` instead of ```--ytdl-format ID```.

@lachs0r suggested using zsh to accomplish this, although I haven't looked into it.

**Comment by qmega** [comment]
Well, you could use a shell function such as:
```zsh
function mpv {
  local -a args
  for arg in $@; do
    if [[ $arg == '-f' ]]; then
      arg='--ytdl-format'
    fi
    args=($args $arg)
  done
  command mpv $args
}
```
Similar to a wrapper script.

**Comment by wm4** [comment]
I wouldn't mind adding simple argument aliases, but generic frameworks are too much.

**Comment by wm4** [comment]
I guess I'm rejecting this. There wasn't much activity after all.
