### ISSUE TITLE
LUA: mp.register_event(): Is there an event "before file was unloaded"?

### ISSUE THREAD

**Issue by limelime** [mpv-player/mpv#1889]
LUA: mp.register_event(): Is there an event "before file was unloaded"?
I would like to get the time position before the next file is loaded(e.g. before Shift+>).
```lua
function save_time_position()
  print(mp.get_property_number("time-pos"))
end

mp.register_event("????", save_time_position )

```

**Comment by wm4** [comment]
No. And it wouldn't be useful at all, because events are not synchronously handled (the player will already start the next file when Lua scripts handle it). But you can use the ``on_unload`` hook, which was made for situations like these. (See ytdl-hook.lua for how to use it - this script uses the ``on_load`` hook.)
