### ISSUE TITLE
Is it possible to build libmpv without the rest of the player?

### ISSUE THREAD

**Issue by kozross** [mpv-player/mpv#1911]
I'm a little uncertain about this, and would appreciate clarification.

**Comment by pigoz** [comment]
Yes, `./waf configure --disable-cplayer`

**Comment by wm4** [comment]
I'm not sure what you mean by this... libmpv _is_ the player, just that instead of being a command line program, it's a library wth an API. The mpv binary is not needed, just libmpv, if you mean this. Also, by default, libmpv tries not to interfere with the command line player and e.g. doesn't load its config files.
