### ISSUE TITLE
Double clicking and dragging on Windows 8.1 removes the window border but doesn't maximize

### ISSUE THREAD

**Issue by cparadis6191** [mpv-player/mpv#1921]
Steps to reproduce:
- Open a video on Windows 8.1
- Double click and on the second click don't let go
- Drag the window to a new position
- Release the mouse button

The window will now have no border and can't be moved. Double-clicking again will return to normal windowed mode.

**Comment by wm4** [comment]
Seems impossible to fix properly. It's caused by this "hack" for dragging the window. This somehow causes the window to be forced out of fullscreen. mpv doesn't really know about this (because windows has no real concept of fullscreen, yep), and attempts to detect this situation fail due to race conditions between window server and client state.

@rossy: maybe you have an idea? Would it be better to reimplement window dragging in another way?

**Comment by rossy** [comment]
Ah, sorry. I'm not sure how I missed that notification.

I think the window dragging hack is good. The advantage of getting the window manager to handle dragging for us is that Aero Snap works and the window moves with the mouse cursor instead of lagging slightly behind it. The problem is that it enters a nested message loop and I think it sets the final window position before returning, which means that attempts to detect this situation happen too soon (inside the nested loop) and the window gets moved anyway when the loop exits (before  GetMessage(WM_NCLBUTTONDOWN) returns.)

I'll try to think of a way around this, but I haven't found anything so far. In the meantime, I think the window dragging hack should definitely be kept.

**Comment by avih** [comment]
Maybe it's possible to disable VO dragging for some ms after a click or mouse up is registered?

**Comment by garoto** [comment]
Kinda glad this old issue was brought to the top, reporting it was in my todo list. OP reproduction steps are spot on, but is this really specific to Win 8.1? Seems odd if true.

**Comment by tactidact** [comment]
@garoto If you look at the duplicate that was submitted by be, then you'll see I've faced this issue on Windows 10 CU(1703). So this seems to be an issue with Windows overall.

**Comment by avih** [comment]
> Maybe it's possible to disable VO dragging for some ms after a click or mouse up is registered?

I experimented a bit with that and roughly it seems to be working - fixing both double click with spatially distant clicks and/or double click while holding the 2nd click, but it already "hanged" for me after several consecutive/alternating double clicks and drags (symptom - double click no longer exits fullscreen and ctrl-c is required to quit mpv).

**Comment by garoto** [comment]
> double click with spatially distant clicks

This was my way to trigger the buggy behavior described. Your patch fix this specific trigger mechanism?

**Comment by aufkrawall** [comment]
Is there still hope for a fix or at least good workaround?

**Comment by aufkrawall** [comment]
Well, one possible workaround seems to be to use smplayer as UI frontend, at least it doesn't introduce any apparent issues afaict.

**Comment by garoto** [comment]
> good workaround?

Bind `MBTN_LEFT_DBL` to something else other than `cycle fullscreen`.

**Comment by dix1mon** [comment]
FYI. Was also able to repro the issue on Manjaro Linux x86_64, DE: Xfce 4.16. Same STR, but a bit lower repro rate.

⚠️ Please note, that issue occurs only when video is in playing state (i.e. not paused). For easy repro it's also better to drag window from its lower right corner in lower right direction (as triggering fullscreen mode via double-click makes window to snap briefly to upper left corner, not giving enough time to reproduce the issue).

**Comment by pbaykalov** [comment]
Is it possible to let the autohiding taskbar pixel row show? I used this "bug" to maximize MPV while still being able to use autohiding taskbar. Is it possible to re-enable this "bug"?

**Comment by pbaykalov** [comment]
nvm did it in AHK: 

```
$<#\::
	WinMove A, , 1, 0
	return

```
