### ISSUE TITLE
feature request: keep JSON key order in Lua

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#1953]
When we serialize Lua tables with `mputils.format_json`, it shuffles the keys randomly each time. It would be nice if it behaved more consistently.

My use case is this: upon finished playback, I serialize some information into a JSON string, which I then append to some file. When opening that file, instead of having the information neatly ordered, the "columns" are scrambled which makes them look unattractive.

I understand if this is impossible due to limitation of Lua parser.

**Comment by wm4** [comment]
It's (probably) impossible because Lua (that's the name of the language, not LUA) doesn't have a guaranteed order on table entries.

**Comment by atomnuker** [comment]
Yep, when I wrote a parser (Lua->C) I looked into it and it's impossible to keep the final table's order (e.g. when recursing through an array of tables containing variables the variables get shuffled). The only guarantee you have is that an array of tables will remain in the order it's populated (1,2,3...N), so I guess that's an option.

**Comment by rr-** [comment]
Thanks; closing the issue, then. I think "wontfix" label  would be fitting.

**Comment by wm4** [comment]
Potentially, the json writer could still attempt to sort the keys. This would bring them into a deterministic order, and doesn't matter otherwise as the order isn't supposed to matter.

For now I'd suggest you write your own JSON formatter and do this. (It shouldn't be hard; the C code for this is only about 50 lines too, though it'd be much more with sorting.)
