### ISSUE TITLE
I wrote a linux script, can I run it with mpv in GUI?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2014]
#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
n=$(mediainfo --Inform="Video;%FrameRate%" $1)
int=${n%.*}
if [ $int == 59 ] || [ $int == 60 ] || [ $int == 29 ] || [ $int == 30 ];then 
	mpv --vo=opengl-hq:icc-profile-auto --sub-auto=fuzzy $1
else
	mpv --vo=opengl-hq:interpolation:icc-profile-auto --sub-auto=fuzzy $1	
fi
exit 0
-------------------------------------------------------------------------------------------------
Can I run it just like normal GUI applications do?
Just like I open the Video and run this script automatically.

**Comment by Idlusen** [comment]
I would say this is only up to your desktop environment settings. You’d have to associate your script to video file types (eg in MIME Type Editor for Xfce or File Associations in for KDE).

**Comment by kevmitch** [comment]
I think it should work of you put the script path in the ```Exec``` line of the ```mpv.desktop``` file.

In any case, this should be theoretically unnecessary with the default tscale=oversample. This algorithm is a no-op when the display refresh rate matches the video frame rate.

**Comment by Argon-** [comment]
Also, this script breaks for videos with wrong fps tag (not as rare as you might think) and variable fps stuff.

**Comment by laichiaheng** [comment]
@Argon- What do you mean? I convert the 59.94/60.0/29.97/30.0 to integer 59/60/29/30, and with no interpolation when the video in 59.94/60.0/29.97/30.0 fps.

@kevmitch Thanks, I will try it.

**Comment by kevmitch** [comment]
Regarding your first question. The problem is that reading the framerate with mediainfo is only pulling a tag out of the file metadata and that tag is very often completely wrong "in the wild". For example many DVDs typically identify as 30fps when they are actually 24fps or even change framerate multiple times throughout the file.

Regarding your second question, that %U is important. It is not an mpv option. It's part of the .desktop file syntax. According to the [specification](http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) it is the URL of the file you are trying to open.

**Comment by laichiaheng** [comment]
@kevmitch So, what should I use to get the correct framerate and resolution?

And I found some error too when I was running the script with mediainfo --Inform="Video;%Width%" and mediainfo --Inform="Video;%Height%" command, It wouldn't tell me their height and width when the resolution was not 1920*1080, but it worked fine in terminal.

**Comment by Argon-** [comment]
> Isn't a movie always in 23.976fps, and video in 29.97fps?

Unfortunately no.
Why don't you just use `interpolation` all the time?

**Comment by laichiaheng** [comment]
@Argon- Because it looked bad when I was playing a 60fps video.

**Comment by wm4** [comment]
>The problem is that reading the framerate with mediainfo is only pulling a tag out of the file metadata and that tag is very often completely wrong "in the wild".

Offtopic, do you have samples for such files?

**Comment by Argon-** [comment]
> @Argon- Because it looked bad when I was playing a 60fps video.

This shouldn't happen. Maybe it's a bug?

**Comment by laichiaheng** [comment]
@Argon- I don't know, maybe it's my illusion!
And I know where I was wrong!! The $1 should change to "$1", because my filename include some commands.

**Comment by kevmitch** [comment]
>Offtopic, do you have samples for such files?

These were both ripped from DVD with makemkv with no encoding:
[24p tagged as 30i](https://dl.dropboxusercontent.com/u/60598588/criterion_logo_24p_tagged30i.mkv)
[30i -> 24p transition tagged as 30i](https://dl.dropboxusercontent.com/u/60598588/cosmos_30i-24p_transition_tagged30i.mkv)

vlc also reports them as 30i when playing the actual disc. mpv says fps=0 when playing the actual discs. Maybe DVDs are just assumed 30i because they don't actually have this information?

**Comment by wm4** [comment]
I guess everything was answered.
