### ISSUE TITLE
mpv exits successfully when Ctrl^C'ed

### ISSUE THREAD

**Issue by postmodern** [mpv-player/mpv#2029]
mpv exits with status code 0 (success) when Ctrl^C'ed. This causes issues in shell scripts. Instead, mpv should exit with [status code 130](http://www.tldp.org/LDP/abs/html/exitcodes.html).

**Comment by wm4** [comment]
What issues does it cause?

**Comment by postmodern** [comment]
It causes scripts to coninue running after the mpv command was `Ctrl^C`ed, instead of halting execution.

    function test_mpv() {
      mpv ... -o output.mkv || return $? # would normally catch the error code and immediately return
      mv output.mkv ../actual_video.mkv # but mpv exits with 0, so we hit this line
    }

**Comment by wm4** [comment]
Since the code is shared between multiple signal handlers, and actually sending the exact value (128+signalno) would require slightly more effort, I made it return 3 instead - on all kinds of quits.

I hope this is ok, otherwise please complain.

**Comment by postmodern** [comment]
You may still want to return 0 on legitimate exits. Definitely return a non-0 error code when encoding is interrupted.

**Comment by qmega** [comment]
I think for the default input.conf, `q` should exit 0 and ctrl-c should be non-zero.

**Comment by kaihendry** [comment]
+1 for https://github.com/mpv-player/mpv/issues/2029#issuecomment-110969803 suggestion

I need this so I don't have to fight with a while loop. e.g. `while mpv IMG_6349.MOV; do true; done`

**Comment by wm4** [comment]
ctrl+c already returns a non-0 exit code.

**Comment by wm4** [comment]
Actually, it doesn't it still returns 0. I'm confused as to what the heck you want anyway.

**Comment by wm4** [comment]
Actually it does. All quits now return exit code 4 by default - except quit_watch_later, which still returns 0, but that's an oversight and I'll change it to 4.

**Comment by qmega** [comment]
My suggestion was basically that https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L70 should be `#q quit 0`. Though actually, it might make more sense if 0 were the default exit code and `ctrl+c` was special (`quit 4` or whatever). (But in that case all of the quit bindings in encoding mode should probably exit non-zero too.)

**Comment by trizen** [comment]
I agree with @qmega; `q` and `Q` should exit with code 0, because now there is no way to tell the difference between `q` and `Ctrl^C` as the they both exit with code 4.

This broke the proper support for `mpv` on `youtube-viewer`.

**Comment by wm4** [comment]
But ctrl+c _is_ quit. Why would there be a difference? The user instructs mpv to quit.

**Comment by trizen** [comment]
Let me give you an example where the difference is important.

Let's assume a loop where `mpv` is executed at each iteration. The loop does the following checks: when the exit code of `mpv` is zero, it goes to the next iteration, but a non-zero exit code, the loop is exited.

Currently, this is no longer possible, but it was possible a while ago. An alternative would be to keep exit code 4 for `q` and `Q`, but make `Ctrl^C` to exit with a different exit code, because `Ctrl^C` is a special type of quit compared to a simple `q`.

**Comment by wm4** [comment]
>Let's assume a loop where mpv is executed at each iteration. The loop does the following checks: when the exit code of mpv is zero, it goes to the next iteration, but a non-zero exit code, the loop is exited.

Why not?

**Comment by trizen** [comment]
Because mpv exists with a non-zero exit code when the user presses `q`, breaking the loop. The next loop iteration is reached only when mpv exists normally, at the end of the current playing file.

**Comment by haasn** [comment]
I agree that SIGINT should not signal “I want the program to quit normally” but “something unexpected happened and I want it to fail and halt ASAP”. Receiving SIGINT *should* be treated like an error, IMO.

(As for ctrl+c as a keybinding (eg. via input.conf), then I think it should mimic SIGINT, even if it isn't using SIGINT under the hood. Because that's what I, as a user, expect to happen when I hit ^C)

**Comment by wm4** [comment]
Anyway, feel free to propose a patch.
