### ISSUE TITLE
Re: ffmpeg resample

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#2036]
Probably not an appropriate place to ask but anyway - 
For myself use mpv off of a shared ffmpeg & happened to notice ldd's to both resample's. (because I happened to include libavresample-ffmpeg-dev as a dep. 
So decided to take a look at Debian experimental & see the same thing, eg. 
$ ldd '/home/doug/Downloads/mpv_0.9.2-1+ffmpeg_amd64/usr/bin/mpv'  |grep resample
	libswresample-ffmpeg.so.1 => /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1 (0x00007f07c0b4a000)
	libavresample-ffmpeg.so.2 => /usr/lib/x86_64-linux-gnu/libavresample-ffmpeg.so.2 (0x00007f07b7286000)
Is this an issue?
(- am growing tired of having both around, wonder if it's ok to disable swresample in ffmpeg & just use avresample, thoughts?

**Comment by wm4** [comment]
You can check the mpv version output (``mpv --version``). The resample lib that is listed will be used by mpv for normal resampling/conversion. The "other" resample lib still might be linked in. This is because libavfilter has filters using both. This is a consequence of FFmpeg merging all Libav work, and not even deleting pointless redundant code, so libavfilter has 2 resampling filters.
