### ISSUE TITLE
Dropping frames with opengl-hq

### ISSUE THREAD

**Issue by Shzzu** [mpv-player/mpv#2076]
I was watching videos with opengl-hq (perfectly fine) and later rebooted. When I tried playing the same files again, I was dropping frames. When I switched from opengl-hq to opengl, it played flawlessly again. I've tried rebooting multiple times since then and it still drops frames during playback.

**Comment by kevmitch** [comment]
Are the dropped frames reported by mpv, or are you just observing them visually? 

What is your graphics hardware?

**Comment by Shzzu** [comment]
They're reported by mpv.

My GPU is an AMD Radeon HD 7520G

**Comment by wm4** [comment]
Some other application using OpenGL (e.g. chrome) could cause this as well. Otherwise, make sure you're using the same software and driver versions as before.

**Comment by Shzzu** [comment]
I have no other applications open that use OpenGL.

Driver version is the same, and so is mpv.

**Comment by Shzzu** [comment]
I left my computer on for a day or two and mpv was able to run opengl-hq without dropping frames. After rebooting again, it was dropping frames again.

**Comment by ledufff** [comment]
>I left my computer on for a day or two and mpv was able to run opengl-hq without dropping frames. After rebooting, it was dropping frames again.


I can confirm that too, in Fedora 22.

**Comment by kevmitch** [comment]
> I can confirm this too, in Fedora 22. (Intel HD Graphics 3000)

To clarify, you are seeing the same "not working after boot" / "working after a period of uptime"?

**Comment by ledufff** [comment]
>To clarify, you are seeing the same "not working after boot" / "working after a period of uptime"?

Hmm, Both, but mostly "not working after boot", since mpv starts dropping frames after 20~ minutes using my laptop. 
Casually I left my laptop on for almost 16 hours, and I ran mpv and it dropped frames too, but not as bad after boot (unwatchable), but this can be just a causality. 
I also tried running mpv in a LMDE 2 live-usb (since I use Cinnamon), with the same video file, and it worked smooth, I though it had something to do with Fedora's kernel, intel drivers, mesa (since we are in 10.6 now), or &c, so I made a Fedora 22 live-usb and it also worked fine.
Every massive frame dropping was followed with some kind of noise in my laptop, like a fast twist, I though it was my HDD, so I defragged an  old windows partition that I have, and I ran "e2fsck -c && e2fsck -f" in root and home, now it work smooth now:
AV: 00:22:39 / 00:23:08 (97%) A-V:  0.000
AV: 00:07:00 / 02:12:22 (5%) A-V:  0.000
before it were over 200 dropped frames in 7 minutes, and not even talk about 22 minutes, I couldn't even watch anything.


Anyway, to be concrete I advice  @Shzzu to check your disk, or try keep an "eye" on any noise followed by the frame dropping, or something like that.

I'll watch a movie tonight, guess it'll be the last test to see if it was some kind of root filesystem error. (it cannot be /home, I mean, test files that I used with the live cd's are stored there).

**Comment by ledufff** [comment]
It got kinda better but still frame dropping (from 10 to 25 frames after 10 minutes), and mpv reported desynchronization after this one:
AV: 00:19:26 / 01:56:57 (16%) A-V:  0.000 Dropped: 66

I closed mpv, but then again, after 55 minutes of having my laptop on, I decided to test and this is all I got after 45 minutes:
AV: 00:45:29 / 01:56:57 (38%) A-V:  0.000 Dropped: 8

some frames dropped. but not an audio/video desynchronization disaster.

After remember the noise thing I rebooted my laptop and realize that:
AV: 00:17:05 / 01:56:57 (14%) A-V:  0.000
no noises, no dropping.
So, I can confirm too, that this noise is still present, and stills followed by the aggressive frame dropping, this happens only with mpv, I tested with totem reproduced for over an hour, and I didn't had that noise and/or frame dropping so far (also a few minutes with YouTube).


After e2fsck episode, my distro works better, but I don't see any mpv several improvement, except for less frames dropped, for example, before that I didn't got 66 at maximium but 80 or 100~.

(this time, I decided to test all this using opengl and not opengl-hq)

**Comment by Shzzu** [comment]
@ledufff I've checked my disk and there was no issues with it. Sorry for the late response.

**Comment by laichiaheng** [comment]
It dropped frames when I used opengl-hq in 4K resolution (intel HD4600)
Is that normal????

**Comment by brunogm0** [comment]
Try enabling  DRI3.  Option "DRI3" "on" on xorg
