### ISSUE TITLE
x11: Handle external fullscreen toggles

### ISSUE THREAD

**Issue by eduardosm** [mpv-player/mpv#2078]
Some windows managers let you change the fullscreen state of any window using a key combination. For example, on XFWM you can use Alt+F11 and on Compiz you can configure a key combination with the "Extra WM actions" plugin. When you toggle the fullscreen state this way, mpv does not realize it.

If you enter fullscreen using the WM's shortcut and then you try to go back again to window mode through mpv's ui, mpv will believe it is was on window mode and stay in fullscreen mode.

To handle this, each time we get a PropertyNotify for _NET_WM_STATE, we can look for _NET_WM_STATE_FULLSCREEN and check if WM's state and mpv's state match.

I wrote a function [1] to handle to handle this (called from vo_x11_check_events after a _NET_WM_STATE PropertyNotify event) that seems to work well. However, I'm not sure if this is the best way to handle and there is a small issue: OSD's fullscreen icon does not change when using WM's shortcut, so I believe that changing vo->opts->fullscreen is not enough to notify a fullscreen toggle.

Any suggestion to handle this better? Please note that I'm not acquainted with mpv's code base.

[1] http://pastebin.com/kQCTPMGt

**Comment by wm4** [comment]
These variables were never meant to be updated on the VO side, so there's no notification mechanism yet. And in fact, ``opts->fullscreen`` barely manages to be thread-safe as it is: during the fullscreen set command both player frontend and VO are synchronized, but this is not the case with asynchronous changes.

For now it seems like a pain to get this perfectly right. For now you could flag a VO_EVENT_WIN_STATE event, and add the fullscreen property to the list of properties changed by it (see MP_EVENT_WIN_STATE). The result will not be correctly synchronized from a multithreading point of view, but maybe it doesn't matter in practice.

Eventually, I want to introduce a new settings system which is actually thread-safe. Then the x11 code could just update the setting directly, and update notification and synchronization would be automatically taken care of. But since I'm kind of stuck on this, I don't know how long it'll take.

**Comment by eduardosm** [comment]
Thanks for your explanation. I got it working and I've created a pull request [1]. I created a new event type, but I've just realized that it could be better to just use the VO_EVENT_WIN_STATE event.

[1] https://github.com/mpv-player/mpv/pull/2081

**Comment by wm4** [comment]
Oh, right, I've already looked over it.

**Comment by philopaterwaheed** [comment]
hi there sorry for calling you from the future but does my window manager need to do anything other than setting the state ??

**Comment by eduardosm** [comment]
The window manager has to update the state and move and resize the window to make it fullscreen.

**Comment by philopaterwaheed** [comment]
ok thanks what I was missing is telling the server that I can do that by atoms ; so mpv wasn't sending events ; totally my fault but thank you
