### ISSUE TITLE
mpv ignores MP4Box PAR adjustment

### ISSUE THREAD

**Issue by nyuszika7h** [mpv-player/mpv#2105]
I'm using this to fix the aspect ratio of some videos: http://tools.rodrigopolo.com/mp4box_aspect_fix/

VLC, and even my TV, display the video correctly after the fix. However, mpv starts out with the correct aspect ratio and then stretches back to the original (wrong) one.

**Comment by wm4** [comment]
Sample file...

**Comment by nyuszika7h** [comment]
http://a.uguu.se/iiooim.mp4 (link expires in 24 hours)

**Comment by wm4** [comment]
The bitstream aspect ratio changes after a few frames. It's not really clear what should happen then:  continue to use the container aspect ratio, or switch to the bitstream one? mpv does the latter, because it seems convenient if you have video which changes resolution or aspect ratio at some point-

Can you point out where in the mp4 standard it says that the container aspect ratio is always preferred? Otherwise I don't care.

**Comment by nyuszika7h** [comment]
Well, I found a way to change the aspect ratio with FFmpeg, and it plays fine in mpv, so it doesn't matter.
