### ISSUE TITLE
Certain Twitch vods (with youtube-dl) buffer (nearly) endlessly

### ISSUE THREAD

**Issue by TheRyuu** [mpv-player/mpv#2112]
Certain twitch vods specifically (but possibly not limited to) the ones which are split up into 30 minute segments seem to buffer endlessly.  Although this is not strictly true since it will eventually play after the cache grows to much larger size that should otherwise be nessasary.  With these vods I have to set the cache to a smaller value (e.g. 10000) so playback actually starts in a reasonable amount of time.  Furthermore mpv warns about the cache being stuck:
```
mpv.com --ytdl http://www.twitch.tv/ggmontecristo/c/6622562
Playing: http://www.twitch.tv/ggmontecristo/c/6622562
[cache] Cache is not responding - slow/stuck network connection?
[cache] Cache is not responding - slow/stuck network connection?
[cache] Cache is not responding - slow/stuck network connection?
[cache] Cache is not responding - slow/stuck network connection?
```
The above message repeats while it's downloading at my maximum download speed.  I am not entirely certain if this is an mpv issue or if youtube-dl is at fault here.  I'm starting here since it may be some kind of cache issue considering the warning messages.  With these types of vods I would expect it to handle it gracefully and have playback start in a reasonable amount of time.

Relevant mpv options to reproduce it taken from my mpv.conf file:
```
mpv.exe --ytdl --ytdl-format=live --vo=opengl-hq --cache=auto http://www.twitch.tv/ggmontecristo/c/6622562
```
Contrast that startup time with one where cache=auto is replaced with cache=10000.  I'm using the 2015-06-28 64-bit Windows build and the 2015.07.04 youtube-dl Windows exe.

**Comment by haasn** [comment]
I get this often but I feel like simply restarting mpv and trying again fixes it.

**Comment by wm4** [comment]
It builds a giant EDL. Then mpv proceeds to open every file in that EDL, which of course takes long. Reducing the cache size will lower the amount of data that is downloaded in parallel, which is why you see an improvement. (The cache is enabled for every reference file.)

I'm surprised it's working at all.

@ChrisK2: ping

**Comment by wm4** [comment]
To expand on this, EDL can be used to play ranges of multiple files as if it was one file. The ytdl script uses that to emulate popular network protocols which use segments, but the EDL code was never made for this case.

**Comment by ChrisK2** [comment]
I'll look into it, but it will probably come down to "tell the youtube-dl guys to finally use the ``multi_video`` ``_type`` in the extractors" (see rg3/youtube-dl/issues/4254) so that we can ditch the shitty EDL heuristic.

**Comment by wm4** [comment]
What's the consequence? We _could_ add proper handling of segments, so that EDL would become a suitable way to handle such network protocols, but of course that'd also be additional effort.

**Comment by ChrisK2** [comment]
The current EDL code in the hook script has nothing to do with network protocols. Some sites (notably viacom stuff) simply breaks up episodes into a few multiple parts (usually where commercials are), the EDL should just glue them back together. Since that's usually four or so parts this works fine.

Since youtube-dl doesn't tell us what is a "multi-part" episode, we currently have to guess, which sometimes goes wrong. However it seems like in this case it's actually the right thing to do.

I still haven't looked into it, but from this issue it sounds like Twitch serves VODs as a LOT small segments, similar to HLS. EDLs aren't made for this, and this needs special treatment of some sort. Possibly some "lazy loading" mode for EDLs where it only loads ``n`` segments ahead instead of all. We may also have to fake the duration then (if this is note yet possible with EDLs).

**Comment by ChrisK2** [comment]
Okay, I now took a look and it seems like the segments are rather long (28:30 m:s) and not that many (9 in this case), which is apparently still too much to load at once.

**Comment by wm4** [comment]
>similar to HLS. EDLs aren't made for this, and this needs special treatment of some sort. Possibly some "lazy loading" mode for EDLs 

Yes, that's what I was talking about. (Hm, adding duration info to EDLs would also make it possible to force a duration with youtube DASH mp4s?)

**Comment by ChrisK2** [comment]
> (Hm, adding duration info to EDLs would also make it possible to force a duration with youtube DASH mp4s?)

(my thoughts ...)

**Comment by wm4** [comment]
Actually, you can set the duration already. It will print a warning on opening, but it won't clamp it to the demuxer-reported duration.

**Comment by wm4** [comment]
Your thoughts, but you don't care anyway? Sigh... I guess nobody cares about this.
