### ISSUE TITLE
Add autoupdate

### ISSUE THREAD

**Issue by gsklee** [mpv-player/mpv#2129]
Please add autoupdate ability into mpv, thanks!

**Comment by wm4** [comment]
mpv prides itself on not doing crap like phoning home, so this won't happen. Also, we expect either that you compile from source or use a package manager, and in neither cases autoupdate makes sense.

For some semi-automatic binary builds like lachs0r's or ChrisK2's it might make sense, but then it should be a separate script, especially since "proper" mpv can't/shouldn't somehow know about these builds.

**Comment by asoksevil** [comment]
@ChrisK2 @wm4 

Would it be possible to add it for ChrisK2´s build? Most Mac users aren´t tech savvy enough to compile their own versions... 

Also, is there any list of available commands, shaders, filters for mpv?

Thanks!

**Comment by wm4** [comment]
Possible yes, but someone would need to do it. It's not entirely trivial.

>Also, is there any list of available commands, shaders, filters for mpv?

See website.
