### ISSUE TITLE
Retina Macbook Fullscreen

### ISSUE THREAD

**Issue by Argon-** [mpv-player/mpv#2132]
Tbh I don't really know how all of this HighDPI stuff works, so the following might be blatantly stupid.

It appears mpv is using everywhere *2 the size so it looks like "normal" (a 1280x720 video is resized to 2560x1440). I noticed the same is done when going into fullscreen: mpv resizes to the double of the selected "scaled"/looks-like/HighDPI resolution (1280x800, 1440x900, 1680x1050, etc.). Therefore, when using a looks-like resolution of 1440x900, going into fullscreen creates a window of size 2880x1800 which is even above the display's native resolution of 2560x1600.
Wouldn't it be more economical to always use the native display resolution of 2560x1600 when fullscreened? I have no idea what is done with the 2880x1800 video to get it back to the native resolution (downscaling by the window manager?).

**Comment by pigoz** [comment]
This is quite strange, the intended behaviour would be to use 2560x1600 in fullscreen mode.

**Comment by ChrisK2** [comment]
Yes, if you use other resolutions than 2x of your display, your desktop gets rendered in 2x of whatever you choose and THEN scaled to the display resolution. Scaling to native display resolution when your desktop does not use it will probably need some magic to bypass the compositor/scaling process.
(OpenGL exclusive mode maybe?)

**Comment by Cpuroast** [comment]
All "retina" resolutions get doubled by the compositor, 1280x800 doubles to 2560x1600, which fits nicely.
However, this is not the case when using 1440x900 instead, it gets rendered at twice that or 2880x1800 then gets scaled down to, in your case, the display's native 2560x1600.
Same with 1680x1050, that gets rendered to 3360x2100 then scaled back down to 2560x1600.

That's why the higher non-default "retina" resolutions can start taxing the GPU quite a bit.

**Comment by Argon-** [comment]
This sounds unnecessarily wasteful imo.

>Scaling to native display resolution when your desktop does not use it will probably need some magic to bypass the compositor/scaling process.
>(OpenGL exclusive mode maybe?)

In the worst case one would probably have to change the resolution.
