### ISSUE TITLE
video streaming on National Geographic with mpv+ytdl

### ISSUE THREAD

**Issue by beew** [mpv-player/mpv#2156]
Hi,
Using the latest youtube-dl I am able to download videos from national geographic and once downloaded (.flv files) mpv is able to play them without problem. But if I try to watch the stream without downloading using mpv with youtube-dl hook mpv complains that the format is not recognized.

example
http://video.nationalgeographic.com/video/news/150210-news-crab-mating-vin?source=featuredvideo  

```
youtube-dl -F http://video.nationalgeographic.com/video/news/150210-news-crab-mating-vin?source=featuredvideo
[NationalGeographic] 150210-news-crab-mating-vin: Downloading webpage
[NationalGeographic] 150210-news-crab-mating-vin: Downloading XML
[ThePlatform] 4DmDACA6Qtk_: Downloading XML
[ThePlatform] 4DmDACA6Qtk_: Downloading webpage
[ThePlatform] 4DmDACA6Qtk_: Downloading f4m manifest
[info] Available formats for 4DmDACA6Qtk_:
format code  extension  resolution note
1322         flv        unknown    1322k
```

```
youtube-dl http://video.nationalgeographic.com/video/news/150210-news-crab-mating-vin?source=featuredvideo
[NationalGeographic] 150210-news-crab-mating-vin: Downloading webpage
[NationalGeographic] 150210-news-crab-mating-vin: Downloading XML
[ThePlatform] 4DmDACA6Qtk_: Downloading XML
[ThePlatform] 4DmDACA6Qtk_: Downloading webpage
[ThePlatform] 4DmDACA6Qtk_: Downloading f4m manifest
[download] Downloading f4m manifest
[download] Destination: Mating Crabs Busted by Sharks-4DmDACA6Qtk_.flv
[download] 100% of 9.97MiB in 00:21
```

```
mpv --ytdl-format=best http://video.nationalgeographic.com/video/news/150210-news-crab-mating-vin?source=featuredvideo
Auto-loading profile 'vo.vaapi'
Playing: http://video.nationalgeographic.com/video/news/150210-news-crab-mating-vin?source=featuredvideo
Failed to recognize file format.
```

Thanks

P.S. the test requires the latest youtube-dl from master. There was a youtube-dl bug for extracting video information from that site which was fixed just yesterday.

**Comment by wm4** [comment]
It's because this stream uses Adobe Smooth Streaming ("f4m"), which FFmpeg doesn't implement. (I'm not perfectly sure whether I got the name of this protocol right.)

A basic implementation would probably not be all that hard, although the fact that it requires parsing XML while FFmpeg has no XML parser complicates it a bit.

**Comment by mc4man** [comment]
ongoing/notgoing for some time, don't think 15.00 will improve it's chances
http://trac.ffmpeg.org/ticket/1964

**Comment by remitamine** [comment]
i send a pull request to the youtube-dl to make theplatform extractor make use of m3u8 manifest instead of f4m https://github.com/rg3/youtube-dl/pull/6267.
it will solve this problem for National geographic and other sites that use theplatform extractor but it still there are other sites that only support f4m for this it should be implemented the f4m in ffmpeg.
