### ISSUE TITLE
Swap the order of "mpv" and filename in the window title

### ISSUE THREAD

**Issue by DerpMcDerp** [mpv-player/mpv#2188]
If no `--title` is set, the window title displays as "mpv - $name". It should display as "$name - mpv" instead.

Or even better, don't display the " - mpv" part at all.

**Comment by wiiaboo** [comment]
`--title="${?media-title:${media-title}}${!media-title:No file.}"`
You can do this yourself in mpv.conf.

**Comment by RandyRanderson** [comment]
I set it up to be "$media-title - mpv" a long time ago, but I agree with @DerpMcDerp that it should be the default, if only for consistency's sake.
Apart from mpv, I've never encountered any program whose title bar displayed something in the "Program - Document" format, and everything has a "Document - Program" format.

**Comment by lvml** [comment]
The "Program - Document" format makes it most easy to match the window title in configuration files of window managers, where you e.g. might want to configure that "Program*" windows are always kept "above" other windows or window manager elements (except for screen locks, of course).

Thus I'd vote for keeping the current default.

**Comment by RandyRanderson** [comment]
>The "Program - Document" format makes it most easy to match the window title in configuration files of window managers, where you e.g. might want to configure that "Program*" windows are always kept "above" other windows or window manager elements (except for screen locks, of course).

If your WM supports "Program * ", it likely supports " * Program" as well.

I think the reason almost every program favors a "Document - Program" window title is that in a win95-esque taskbar (or any kind of task switcher where there's limited amount of space), in some cases, a "Program - Document" title would only show the program's name (information that is always conveyed typically by the icon, ergo redundant) plus too little of the document's name to distinguish between two windows of the same program.
That doesn't happen often with mpv because 1. mpv's a pretty short name and 2. you usually don't have two open windows of mpv at the same time, but it happened to me once or twice (which was a factor in changing mpv's window title on my config).

In any case it's a low effort change (I assume), for a low reward (the only win here would be consistency, which to be fair is a pretty important usability factor)

**Comment by lachs0r** [comment]
If you want to match mpv with your WM, use the class (which is “mpv” unless you change `x11-name`), not its title.

I don’t really care about the window title format, but it can’t hurt to bring it in line with other software.
