### ISSUE TITLE
Video stutters on wayland

### ISSUE THREAD

**Issue by SirCmpwn** [mpv-player/mpv#2227]
Hey there. Using vo=opengl under wayland and the video stutters quite a bit.

**Comment by wm4** [comment]
This is caused by a bug fix we did earlier. Essentially, Wayland does not allow blocking on drawing like all other OpenGL implementations do. Instead, we need to do something extremely complicated to conform to Wayland's protocol.

**Comment by SirCmpwn** [comment]
Which bug fix? Would it be reasonable to patch it out in my own copy of mpv as a temporary solution?

**Comment by wm4** [comment]
I think it was 3a6ade7a848f5213525430d9049e96e642638fc8. This probably can't be cleanly reverted anymore, but you can probably find out how to disable the "fix".

If mpv queues up too many draw calls, the wayland client lib will ``abort()`` mpv.

**Comment by SirCmpwn** [comment]
I see. Hard one to undo.

**Comment by Cloudef** [comment]
I'm willing to take this issue. The way mpv's rendering loop works though may need to change. Was there any work towards the OS X VideoCore's render loop (or w/e it was called)?

**Comment by wm4** [comment]
>The way mpv's rendering loop works though may need to change.

Maybe. I'm still not too fond of doing this just for wayland. But maybe the result will be better in general.

>Was there any work towards the OS X VideoCore's render loop (or w/e it was called)?

No. And the API is called DisplayLink. Nobody actually uses it the way it's intended; all other software I've seen uses it only to retrieve timings (while doing the actual rendering in a thread). I don't know where this will lead, but it seems the OSX thing won't be happening in this form. Not sure.

But there's still vo_opengl_cb, which is very weird because it's mostly asynchronous. The Wayland windowing code would probably like having such an API, and the opengl-cb code should really be cleaned up because it duplicates what vo_opengl does, except for a different rendering loop structure. So what I plan to do is

1. allow every VO to run its own event loop, either in the VO thread or its own thread
2. let the VO fetch from a thread-safe "queue" (where the queue will actually have only 1 element in the beginning, just like it is now)

This will would serve to turn the rendering loop inside-out. The main question is, how to do all the weird stuff the vo.c rendering loop does with such a design. Lastly, throwing the needs of vo_opengl_cb into the mix doesn't make it simpler. It can't handle blocking VOCTRLs for example. It's a big mess.

The alternative to this is making the wayland code behave like the other backends: before a frame is started, make it do a blocking wait on the event loop, which is unblocked either once the frame callback arrives, or a timeout passes. This would probably be easier, but also hackier.

**Comment by Cloudef** [comment]
Yeah, refactoring synchronous code base to asynchronous is never fun.

>But there's still vo_opengl_cb, which is very weird because it's mostly asynchronous. 

I'll look at what that is.

>allow every VO to run its own event loop, either in the VO thread or its own thread

Another thread may be overkill. Having own event loop would allow more flexibility to vo for other stuff than just rendering. For Wayland, the timing code in VO's main loop is mostly useless I think, as in Wayland you have those frame callbacks, and even presentation extension for querying higher precision timing(?). I'm not familiar with the latter though.

>The alternative to this is making the wayland code behave like the other backends: before a frame is started, make it do a blocking wait on the event loop, which is unblocked either once the frame callback arrives, or a timeout passes. This would probably be easier, but also hackier.

This might be a good start, at least it solves a "problem".

**Comment by wm4** [comment]
>I'll look at what that is.

It uses the same OpenGL renderer as vo_opengl (in gl_video.c). But instead of rendering video through the vo.c draw loop, it does so by having the API user call a function from a different thread. (There are some examples in DOCS/client_api_examples.) The weird thing is that it has to have its own frame queue.

>Another thread may be overkill. 

Well, yes, the VO could just reuse the thread created by vo.c. I meant that in general, the VO could create its own thread for handling this, and there should be nothing that forces the VO to run on an existing thread.

>For Wayland, the timing code in VO's main loop is mostly useless I think, 

Kind of, but it still has to do some timing. For example, what would wait until the display time is reached, what would drop frames, etc.?

> and even presentation extension for querying higher precision timing(?). I'm not familiar with the latter though.

This was still in flux, I'm not sure if they decided on a stable API yet.

**Comment by Cloudef** [comment]
> Kind of, but it still has to do some timing. For example, what would wait until the display time is reached, what would drop frames, etc.?

AV needs to be kept sync still. What is display time? If this is "when to draw next frame", if so it's the frame callback of course. Frame dropping would just ignore (or keep? not sure which is correct convention to be friendly to compositor) the frame callbacks until reaching target framerate.

**Comment by wm4** [comment]
>What is display time?

Currently, the main synchronization mode is waiting until the absolute system time ``vo_frame.pts`` is reached, and then show the frame. Then it waits for the next frame.

There's lots of complexity for frame dropping, other sync modes (display timed, and "vsync timed"), redraw handling (you don't want to redraw if the next frame is coming anyway, unless you're paused, etc.). Most of this is in ``render_frame()`` in vo.c. This needs to be turned inside-out... somehow.

I imagine we'd have a ``struct vo_frame *vo_get_next_frame(struct vo *vo);`` function. It would return the next frame. This function would either have to block, or we'd have to provide a way to wait for new frame. This waiting mechanism could also take care of waiting for the display time.

And then there's a need to handle other events, like reconfiguring the video format, sending VOCTRLs, and vo termination. And the vo_opengl backend mechanism has to be changed to this (gl_common.c).

(Sorry, this is probably too much information; I'm mostly thinking loudly.)

**Comment by wm4** [comment]
Btw. would allowing it to render 1 frame ahead fix it? (So it'd render 1 frame before the frame callback arrives.)

**Comment by Cloudef** [comment]
I'm not sure, what did you have in mind?

**Comment by wm4** [comment]
currently, ``start_frame`` in gl_wayland.c will check whether the frame callback was called once since the last ``swapGlBuffers_wayland`` call. We could instead make ``start_frame`` allow 1 frame to be rendered even if no frame callback happened yet. Basically, we try to allow it to render 1 frame ahead of what the compositor wants. This is probably not enough to trigger a protocol buffer overflow, but would give us good vsync behavior.

**Comment by Cloudef** [comment]
I could test how that works in practice.

**Comment by diegoviola** [comment]
I think I'm having the same problem, I've tried mpv on weston with a mkv file and the video is always slower than on X.

I also tried `mpv --really-quiet` and same result, slower video output.

**Comment by SirCmpwn** [comment]
@diegoviola I get tolerable playback by using `-vo=opengl-hq:interpolate`

**Comment by diegoviola** [comment]
@SirCmpwn I tried both `-vo opengl` and `-vo wayland`, same results. I'll give that a try and report back. Thanks.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/mpv/tree/fix/wayland Can you try how things are working with the code in this branch.

**Comment by diegoviola** [comment]
Does `-vo=opengl-hq:interpolate` needs anything special? Because that fails on my system, I'm using mpv from Arch Linux.

**Comment by SirCmpwn** [comment]
It's actually `interpolation`, my bad.

**Comment by diegoviola** [comment]
Yes, I get better results with `-vo=opengl-hq:interpolation`. Video is smoother now.

**Comment by diegoviola** [comment]
@Cloudef I've tried your branch, I get better results with your branch as well with both `-vo opengl` and `-vo wayland`.

Thanks.

**Comment by SirCmpwn** [comment]
I get much better performance with @Cloudef's changes.

**Comment by Cloudef** [comment]
Should be fixed in #2232
