### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by rupeshs** [mpv-player/mpv#2272]

**Comment by lachs0r** [comment]
No.

**Comment by rupeshs** [comment]
hi lachs0r ,
MPlayer android port is available ...libmpv in Android?

**Comment by lachs0r** [comment]
No.

**Comment by rupeshs** [comment]
So ARM builds not possible?

**Comment by wm4** [comment]
This MPlayer android port probably supports software decoding only. And I don't know how it supports audio. I know that mplayer has a tiny hack to enable video output on android though.

Where's the source of that port? (Just curious. As long as I don't have a smartphone, Android support seems extremely unlikely, and even if mpv gets support, it'll most likely be on a toy level.)

**Comment by rupeshs** [comment]
One strange thing is that that code is not compilable or usable just a crap
check this https://github.com/ajeet17181/mplayer-android

**Comment by wm4** [comment]
Attempt to extract a patch from this chaotic repository: http://sprunge.us/dYdI

But yeah, not useful for us.

**Comment by rupeshs** [comment]
Cool..this is the java code https://mplayer-andorid.googlecode.com/git/mplayer-java.tar.gz
@Google play https://play.google.com/store/apps/details?id=com.vnd.mplayer.neon&hl=en

**Comment by andreygursky** [comment]
@wm4:
> This MPlayer android port probably supports software decoding only.

I haven't looked into this, but since mpv is linked against ffmpeg/libav on my GNU/Linux box, one shouldn't care about this, doesn't it? Hardware decoding for h264 (I believe the most important one) is made in ffmpeg through Android's libstagefright. The mpv should be able to build under NDK (regardless of using libmpv on Android or not, it's a good thing towards portability) and it should provide a picture (with subtitles) and audio, that could be queried through JNI, I think. The second part would be some Android App, utilizing libmpv, which allows to choose a file and provides play/stop and so on.

**Comment by rupeshs** [comment]
Exactly libmpv should be able to build under NDK...anyone tried?

**Comment by wm4** [comment]
I haven't heard anything good about libstagefright. The way to go forward is via MediaCodec (but which requires Java in slightly older Android versions).

**Comment by chaoskagami** [comment]
For the curious, since I actually tried to mess with that "port" a while back:

That port of mplayer was originally "closed-source." The dev refused to release the code until it was made clear he was in violation of the GPL, he made a messy, nigh-uncompilable code dump which sated the GPL requirements, and then he quit development because he didn't want to put his source out there. It's all on XDA if you want to look into it. Not pretty. Just for some background on why that code is a mess.

Anyways, in that code, there's two files that contain the major changes: android-mplayer.c contains the JNI bridge code, and mplayer.c contains some alterations. Besides that, all the files are pre-generated, and the oddly named shell scripts are used to compile mplayer. There's also seeming miscellaneous changes; I suspect this was cloned off a live version of mplayer since I couldn't find an exact source match.

FYI, Android's framework doesn't even support plaintext subtitles right, never mind ass (read: no support whatsoever.) There's a reason VLC renders subs so crappily and that it lags so bad when they're enabled. It has to basically do software rendering with subs.

I'd be very interested in MPV on android, though. (Even if it isn't likely, due to a large list of issues I can think of immediately.)

**Comment by wm4** [comment]
>I'd be very interested in MPV on android, though. (Even if it isn't likely, due to a large list of issues I can think of immediately.)

I wouldn't mind either, if it can be implemented in a way that isn't too intrusive. Newer Android versions at least provide a MediaCodec C (or C++?) API. But I suspect we'd still need a Java UI wrapper, which then probably uses libmpv or so.

Anyway, progress is unlikely at the current time, because I don't even have a single Android device. (I'm not very eager to get one, because they're all closed off and designed to take control over the device from its owner. I don't understand why people buy this horseshit.)

**Comment by chaoskagami** [comment]
Take control in default configuration, yes. So does Windows. You can fix that with some effort. Luckily most of android is open source.

The software on most phones can be replaced with AOSP, CyanogenMod, or Omnirom and built from source. You can use FDroid (all open source apps, like a package manager) and just never touch anything Google. My phone runs all libre software, except for some kernel firmware. I'm confident it does only what I configured it for. I also have a linux system on my SD that I bind to /, so I have a complete gentoo system at my disposal.

On December 16, 2015 11:30:03 AM EST, "V. Lang" <notifications@github.com> wrote:
>>I'd be very interested in MPV on android, though. (Even if it isn't
>likely, due to a large list of issues I can think of immediately.)
>
>I wouldn't mind either, if it can be implemented in a way that isn't
>too intrusive. Newer Android versions at least provide a MediaCodec C
>(or C++?) API. But I suspect we'd still need a Java UI wrapper, which
>then probably uses libmpv or so.
>
>Anyway, progress is unlikely at the current time, because I don't even
>have a single Android device. (I'm not very eager to get one, because
>they're all closed off and designed to take control over the device
>from its owner. I don't understand why people buy this horseshit.)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mpv-player/mpv/issues/2272#issuecomment-165164955

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lvml** [comment]
Just to mention it here since I stumbled upon it: https://github.com/mpv-android/mpv-android

**Comment by wm4** [comment]
(Known to the devs. That thing uses libmpv.)

**Comment by rupeshs** [comment]
why kotlin used for mpv-android developement ?any advantage ?

**Comment by chaoskagami** [comment]
I built it out of curiousity and it doesn't really work on my Xperia Z2. It sort of plays, but there's this horrid tiling video corruption.

**Comment by jeeb** [comment]
@rupeshs , it's 100% compatible with Java, is less verbose and has a lot of very useful things in the compiler/editor integration. It also can be added to a Java code base bit by bit, which is great if you already have existing code around. It was picked randomly at first, but it most definitely seems like a good language to go with for Android development and otherwise if JVM is/has to be used for whatever reason.

@chaoskagami , that sounds like the issue with the OpenGL ES stuff not getting re-init between opening files. That was supposed to be fixed some time ago, so if you can try the latest build or build the current master it could be better. That, or your OpenGL ES drivers just suck since the re-init stuff was IIRC fixed around the end of April :/ . Unfortunately `opengl-cb` seems to be relatively picky and while many Android 5 devices work, we also have a whole lot of devices which seem to not be able to run it around 4.4+. And since we most definitely don't want to lose the advantages of using mpv's `opengl-cb` (correct colorimetry etc), we will not create a simpler renderer for additional compatibility. It's a knowingly made design choice.

**Comment by chaoskagami** [comment]
Unfortunately, the current test build doesn't even run on my device. I get an immediate 'Stopped' error from the system.

Even worse is there being nothing on logcat of note.

I run a custom build of CM11 (with a bunch of security backports, and using uG) but I doubt that's the issue here. My phone is an Xperia Z2.

**Comment by jeeb** [comment]
The current configuration for the application is:
```
    compileSdkVersion 24
    buildToolsVersion "23.0.3"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 24
    }
```
...and this should mean that it should work on Android 4.4.4, which I presume CM11 is. Also I just tested with the ass-slow API level 19 ARM emulator, and while the compatibility library did bring around a lot of warnings, the file picker did start and thus the application as well. So I'm actually not fully sure why it would just fail without saying anything in your case.

I would have also tested this with a physical device but unfortunately I think the only 4.x device I have is stuck somewhere pre-4.4.x. That said, I'm surprised the Z2 doesn't have 5+ support... 4.4.x tends to be very iffy OpenGL ES driver-wise so I'm thinking of just disabling support for 4.4.x unless we actually find some working devices (so far your initial tests seem to have been the least failed ones, we've had zero positive results from various 4.4.x-stuck devices until now).

**Comment by chaoskagami** [comment]
There actual is support for 5.x, as well as 6.x on my device - but the initial version of CM12 was so broken I ended up on my current setup instead.

I should probably update, but the newer versions of Android seem to have become far less power user friendly, and it's the first time I've seen features removed from the OS.

Nothing yet has required me to update, so I've not done so (aside from manually fixing security bugs on my local source tree)

**Comment by chaoskagami** [comment]
Also, I'm willing to do a git-bisect if need be to figure out which was the last commit to show the file picker.

I can say that the opengl drivers seem quite sane; I've never had issues with anything before.
