### ISSUE TITLE
16:9

### ISSUE THREAD

**Issue by c384mb** [mpv-player/mpv#2277]
Is it just me so? --monitoraspect=
1 scr. 16:9
2 scr. 16:16
MPV git-3c86bd2
![16_9](https://cloud.githubusercontent.com/assets/10123577/9644092/08b9d764-51ce-11e5-8d6a-26a652ad5dda.png)
![16_16](https://cloud.githubusercontent.com/assets/10123577/9644095/0d8a442c-51ce-11e5-9dfb-c04f7f1f2992.png)

**Comment by lachs0r** [comment]
--monitoraspect is most likely not the option you want.

If your goal is to enforce a video aspect ratio, use --video-aspect.

**Comment by c384mb** [comment]
If I'm not using this option I get a picture on the entire screen. Which option to use to get the correct 16:9?

**Comment by lachs0r** [comment]
--video-aspect=16:9

**Comment by c384mb** [comment]
--monitoraspect=16:9 is not working properly. If I use this setting only with mpv you get the image in full screen. If I don't use this and this setting --monitoraspect= , --video-aspect= , the image is displayed at 16:9.

**Comment by paulguy** [comment]
--monitoraspect and the related --monitorpixelaspect are only for the very rare case where your monitor is a different aspect ratio than the output resolution.  I can't really think of a modern example, but one example is the old VGA modes.  320x200 and 640x200.  Both were intended to be displayed on a 4:3 monitor display scaled to fit the screen, so when graphics were made, their actual data if displayed with square pixels would look stretched and wrong.  mpv can set that up for you if you require it, but you probably won't if you have some rather special setup.
What it does depends on your display resolution and display aspect ratio.

**Comment by c384mb** [comment]
Such details are not specified in the manual file pdf. Understanding more complicated if English is not my lang.

**Comment by c384mb** [comment]
Updated version of the mpv to MPV git-82ff32f now --monitoraspect=4:3 = 16:9 or ~16:9, --monitoraspect=16:3 = full screen, it would be more logical to reverse. Monitor LCD real 21.5 inch size resolution of 1152x872 max 1920x1080. 

It is not for me to judge as it should be, I don't have enough knowledge as it should be.

**Comment by paulguy** [comment]
If I understand you correctly, you're using a 1920x1080 display but have your desktop set to 1152x872?

Is your monitor displaying in a stretch to fill mode or a scale to fit but preserve aspect ratio (letterbox) mode?

If your monitor is set to a letterbox mode, you don't need to do anything.  Your monitor is already doing the compensation.  Otherwise, the --monitoraspect option seems to be doing what is correct.  It is taking a mode that is being stretched and compensating inversely to cancel out the deformation, which should result in a correct image, and based on your screenshots, it seems to be more or less working as it should be, and it seems to work as expected for me.  Something else to try would be calculating the compensation with a function that I determined should work, which is native_h / (native_h / displaymode_w * displaymode_h), which I determined to be approximately 0.750521, then applying that using --monitorpixelaspect.  Not really sure if mine is correct though, but if it is, and mpv's is, the result should be basically the same.

Recreating what you're trying to do would be tricky for me since my monitor isn't 16:9.  Anyway you might have better luck either using your monitor's native display mode or using some other 16:9 mode like 1280x720

**Comment by c384mb** [comment]
Yes I use the display resolution of the monitor 1152x872. Оn 1920x1020 for me the display resolution small. You can, I can use 1920x1080 and increase of 100-150% (Windows Vista - 
10 zoom). I prefer to lower the resolution and not use the zoom.
![trfrgftrfrhyuiui897897876](https://cloud.githubusercontent.com/assets/10123577/9687629/0a636b14-5333-11e5-8a37-c36cb99f0c6b.png).

If I do not use configure --monitoraspect= , mpv shows image in the video that I watch is 16:9. As for my monitor and I think for all modern monitors is better to use --video-aspect= for to change the size of the video image. Perhaps in the instructions need to add explanation it is better to use --video-aspect= ,  for modern monitors (16:9).
