### ISSUE TITLE
Missing the good old vo_x11

### ISSUE THREAD

**Issue by fmang** [mpv-player/mpv#2283]
You wouldn't imagine how poor my GPU's performance is. I thought playing 720p videos was hopeless until I tried vo_x11, a gift from the sky.

Then commit d11184a “vo_x11: remove this video output” happened.

I tried the alternatives, but without luck. Accelerated video outputs just won't open a window. SDL2 video output is way too slow. Xv output is quite good, but prints glitchy horizontal bars on high resolutions.

I wish you would reintroduce vo_x11. See also issue #2270.

**Comment by rr-** [comment]
Seconded, removing features always feels bad.

**Comment by lachs0r** [comment]
File a bug with the people who wrote your drivers instead. This is not an mpv issue. Especially

**Comment by fmang** [comment]
Poor performance is not a bug, it's just how some hardware is.

vo_x11 is the perfect balance between CPU and GPU load, the only way for poor hardware to play video efficiently, and what made mpv superior on such hardware. This is what it's needed for, and it's still relevant today.

**Comment by lachs0r** [comment]
Not supporting Xv properly is a driver bug though.

**Comment by fmang** [comment]
You have a point. However, perfecting a driver takes time and the vo_x11 fallback is a lifesaver until the drivers work well.

I guess it's time I dive back into X.org's conf and see the current state of things. I gotta admit it's been years I last tried to fix this.

**Comment by Veyrdite** [comment]
mpv -vo X11 was has been the best way for me to watch videos on my hardware (directfb/mali on Samsung ARM Chromebook, snow).  Through bilinear filtering I was able to obtain zero framedrop on fullscreen video and watch electronics youtube videos without tearing my soul out.  

All of the other video players I have tried have not worked very well in my environment.  They all either cannot find a supported output mode, crash or perform horribly due to the poor graphics implementation the Linux kernel has for my hardware.  I'm not a kernel dev, so I don't have another option unless I try and buy another laptop.  

 Is it a bug that my graphics drivers don't have xv support?  I don't know -- I'm glad they exist at all.  They also don't have opengl, vaapi, xv, vdpau or drm support.  Opengl sort-of-works, but there seems to be big fillrate bottlenecks and it's all sw/llvmpipe.

I can completely understand not wanting to maintain code and I support you if you think it's best for the project.  In an ideal world my kernel drivers would be fixed, but I can't exactly coerce anyone to do work for me, whether they be kernel devs or mpv devs alike :)

What's the code like lachs0r?  Was it getting in your way when you were making changes to other things, or was it something to cleanup/remove in general?

**Comment by Veyrdite** [comment]
My graphics drivers do not support xv.  Is this a bug?  I don't know -- I'm happy the drivers work and exist at all.  They also don't support xv, vaapi, drm or vdpau.  Opengl with sw rendering sort of works, but is a soulless experience of framedrop :)

I'm on an ARM based platform (Samsung Chromebook snow) and X11 support for mpv has been the only way I've been able to support fullscreen video without framedrops.  All other software and render methods I have tried either performs very poorly or does not work at all because the desired output method is not support.

What doe raspi users currently use?

SDL is not listed in my -vo list.  I'll try compiling from source and see if I can get it to work, else I'll checkout a revision before the removal of the X11 code.

If the removal was for the project's good or the sanity of the devs I'm completely behind you.  I'm in no position to coerce kernel devs to add features to my drivers, nor can I coerce mpv devs to my will :) 

Was the code in the way of changes that were being made, or did it disappear as a general cleanup?

**Comment by kevmitch** [comment]
>SDL is not listed in my -vo list. I'll try compiling from source and see if I can get it to work, else I'll checkout a revision before the removal of the X11 code.

You'll need to ``` --enable-sdl2``` as it is disabled by default.

**Comment by wm4** [comment]
>What doe raspi users currently use?

X11 is so slow there that even small video wouldn't play at realtime. There's vo_rpi on RPI.

**Comment by Veyrdite** [comment]
I've just confirmed that SDL performs very slowly on my platform.

**Comment by penduin** [comment]
X11 was my best option too.  Guess I'll just use an old version of mpv for now.

**Comment by fmang** [comment]
This issue is actually fixed, no need to downgrade.

See issue #2300 and commit ebb43f5.

mpv team, you have my gratitude.

**Comment by penduin** [comment]
Oh, excellent!  Thanks for pointing that out @fmang and thanks @wm4 for bringing x11 back in!
