### ISSUE TITLE
waf option --disable-build-date

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#2306]
That produces for ex. - 
mpv 0.10.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
Seems more logical that there should be no 'built on ' line at all.

**Comment by wm4** [comment]
Not really worth the trouble.

**Comment by qyot27** [comment]
FWIW, I went ahead and did this anyway:
https://github.com/qyot27/mpv/commit/fb8faa1f5088fcc01bd6c4260aa3f8b16cc30eb4

Do with it what you will.

**Comment by wm4** [comment]
So what's the advantage of replacing the "unknown" with an empty line?

**Comment by qyot27** [comment]
It being blanked was just a precaution because I didn't know whether a macro would allow the newline to expand properly.

I revised it a little:
https://github.com/qyot27/mpv/commit/6620f80380b9e35bbe02a525a7ba3d8e7becf41c

Now it does away with the line entirely if the build date is disabled.


I honestly don't care whether disabling the feature makes it read 'built on UNKNOWN' or the line isn't there, since I use the build date and have no reason to disable it.

**Comment by mc4man** [comment]
Don't care here either, was just noticing Debian now uses that waf option. I would assume that it was to try to remove the line, whether an actual date or UNKNOWN, both are build dates.
(If I was changing it & had to have a line then 'built on Who Cares' would be more appropiate
