### ISSUE TITLE
Replace OSD "total time" with OSC "remaining time"

### ISSUE THREAD

**Issue by octos** [mpv-player/mpv#2326]
The type of time displayed on the right-hand side is inconsistent between the OSD (on-screen-display activated by pressing **o** or **P**), and the OSC (on-screen-controller activated by moving the mouse):

    OSD: [seek time]/[TOTAL time] (n%)
    OSC: [seek time] [REMAINING time]

Personally, I find the remaining time more useful than the total time. I suggest replacing the OSD's _total time_ with _remaining time_, which should also be recalculated according to the playback speed (as it is already done with the OSC)

I am using mpv 0.10.0

**Comment by ChrisK2** [comment]
You can configure it to your likening using the [``--osd-msg3``](http://mpv.io/manual/master/#options-osd-msg3) option.

**Comment by octos** [comment]
But that doesn't explain the rationale behind the inconsistency. In other words, if you watch at speed 2x, the OSD's total time is not halved, but it should. Instead, the theoretical total time is displayed, although the actual total time would make much more sense, especially since the OSC already fixed that.

**Comment by octos** [comment]
Also, what is `--osd-msg3` for, if O toggles between 2 states only since [v0.10.0](https://github.com/mpv-player/mpv/releases/tag/v0.10.0)?

**Comment by ChrisK2** [comment]
There are still three states, the hotkey just toggles between 1 and 3 now by default. The "rationale" behind the inconsistency is simply: The OSD has always been like this and changing defaults tends to upset some people. When the OSC was designed independently and displaying the  remaining time was chosen as the default there, since that's more common in GUIs which the OSC tries to mimic.

**Comment by octos** [comment]
Fair enough. I put thee following in my config file:

`osd-msg3='${time-pos} -${playtime-remaining}'`

Thanks for your help.
