### ISSUE TITLE
rtmp handshake issue...

### ISSUE THREAD

**Issue by deanone-github** [mpv-player/mpv#2355]
it would seem that as of the mpv-x86_64-20150714 windows build there is a ffmpeg handshake issue
with rtmp...

**Comment by lachs0r** [comment]
Uh yeah, my crystal ball is broken so I can’t figure out which stream you were trying to play. In general, RTMP(E) works fine, though, with some exceptions. Not all types of streams are supported by either ffmpeg or rtmpdump.

**Comment by wm4** [comment]
We've found a rtmp problem with ffmpeg. It stops playback after the first frame or so. Maybe the same issue?

**Comment by lachs0r** [comment]
“rtmp handshake issue” sounds more like playback completely fails, as is the 
case with streams from certain CDNs which appear to do this in a way neither 
ffmpeg nor librtmp supports.

Also, I think the build mentioned in this issue is the one that enabled 
librtmp. I did not confirm whether this really fixed or caused more issues, 
but I kept it around because in the case I was trying to investigate at the 
time, librtmp had more descriptive errors than ffmpeg’s internal thing, which 
looked like it was copied from an older version of that lib.

@deanone-github just in case, here’s a build without librtmp—could you try 
playing the stream in question with that?

http://tmp.srsfckn.biz/mpv-x86_64-20151001-no-librtmp.7z

**Comment by deanone-github** [comment]
@lachs0r the librtmp-free build seems to have nailed it Martin, thanks for that.

@wm4 it may well be the same issue however all builds post and including 20150714 fail from start (no frames).

**Comment by lachs0r** [comment]
Okay, then it’s a librtmp issue that is not present in FFmpeg. Since I don’t know of any cases where librtmp works and FFmpeg doesn’t, I’ll just remove it from my build config.
