### ISSUE TITLE
DVB playback broken

### ISSUE THREAD

**Issue by wm4** [mpv-player/mpv#239]
Someone told me that someone told him that dvb playback was far worse than with mplayer/mplayer2. I don't know details, and I can't test the DVB code, so more information would be nice.

If anyone actually wants to use DVB, and experiences problems, please tell.

This is probably in part caused by dropping the internal TS demuxer, which was default for DVB.

**Comment by olifre** [comment]
Interesting bug report... 
I have one card with extremely good reception (DVB-S only, DVB-S2 does not work with that device on linux, due to a firmware bug, probably). With this card, I do not see the issues described here. I also do not see the strange mp_seeks, this is with ffmpeg 2.5.2 though. 

It is also interesting to note that `--demuxer-lavf-analyzeduration=1` alone has no effect at all for me, UNLESS also the PMT is available (this will soon be the case with my linked PR, I am just adding it - you need a VDR-style channel.conf though, as the classic mplayer channels.conf files do not contain the service_id). Probably the timing estimation does not work without PMT. 

One more interesting finding, which I cannot explain: If I run mpv without any cache, the playback "hiccups" after a few seconds (5-10 seconds) once, then AV is desynchronized. 
If I use, say, `--cache 200000`, this does not happen. 

Using both the large cache, the PMT-patch and the limited analyzeduration, playback start about 1 second after the tuning, which I consider almost instantaneous. I will add a gist sometime later when the PMT-patch is finished, maybe this can help to find out the reason why ffmpeg still uses the full analyzeduration. Maybe also a small mpv-cache should be default for stream_dvb (I think mplayer had that)? 

Another change I did in my PR was to set the DMX-buffers (as also szap-s2 does it): 
https://github.com/olifre/mpv/commit/efcf6b1b68e9201a68f414165c71313113bfa14d#diff-928685972258d9895c12623b263b91fbR174
Does this change anything for somebody with problems? 

I have a second DVB-S/S2 receiver card which probably has some hardware-defect. It generates bad packets every second on both Windows (original drivers) and Linux. With this, basically nothing helps, still I have the feeling that the demuxer in Windows handles the hiccups more gracefully. 

I have also ordered a new DVB-S/S2 card which has native Linux support. I expect more bad packets even with good reception for DVB-S2 channels, so maybe I can reproduce some of the issues here then...

**Comment by olifre** [comment]
Here the gist, as promised: 
https://gist.github.com/olifre/ef52e947e97a2ecf8a8f
This is with the patches from my PR #1409 applied. I let ffmpeg take the full analyzeduration. 

Notice the AV-desynchronization after about 10 seconds of playback (on some audio-decoding error). This reproducibly happens for me after about 10-15 seconds. 

Once I patch stream_dvb.c and add
`stream->streaming = true;`
thus activating mpv's cache, getting the following gist: 
https://gist.github.com/olifre/dd33eea08f0529f22bf6
that problem is gone. I see no desynchronizations or other playback issues after minutes.

**Comment by wm4** [comment]
>One more interesting finding, which I cannot explain: If I run mpv without any cache, the playback "hiccups" after a few seconds (5-10 seconds) once, then AV is desynchronized.
>If I use, say, --cache 200000, this does not happen. 

I don't have an explanation either. Maybe it somehow happens because ffmpeg probing makes us read and buffer lots of data, which is then played without reading new data from the device, which could lead to a buffer overrun in the device/kernel? It's possible that the cache smoothes that out because it will keep reading from the device.

>Maybe also a small mpv-cache should be default for stream_dvb (I think mplayer had that)? 

I'm not opposed to this. I'm not sure if mplayer enabled the cache, but I'm pretty sure enabling the cache makes the dvb controls useless or even broken (or maybe not - the mplayer cache is forked, and I _think_ the code for the DVB controls ignores this fact, which leads to interesting interactions).

**Comment by olifre** [comment]
> I'm pretty sure enabling the cache makes the dvb controls useless or even broken (or maybe not - the mplayer cache is forked, and I think the code for the DVB controls ignores this fact, which leads to interesting interactions).

With DVB controls, you relate to the channel-switching (the dvb_channel property)? 
These act up very much in mpv without PMT indeed, I just tested it. On a channel-switch, it seemed that ffmpeg could not analyze any data successfully anymore... 
The fun-fact is that, with PMT being present and ` stream->streaming = true;` it seems to work fine, also if I then set `--no-cache`. 
I will have a closer look tomorrow, but I think there is stream-emptying in stream_dvb (there is this funny line ` while(dvb_streaming_read(stream, buf, 4096) > 0);` ). 

Note that the "hiccup" also vanishes with `--demuxer-lavf-analyzeduration=0.5`, which matches your explanation quite well...

**Comment by olifre** [comment]
Seeing all this, it seems to me that enabling the cache in general helps with everything. 
However, even if the cache is enabled, it takes 5 seconds to switch from one channel to another / to initially show something. This is fully spent in the `--demuxer-lavf-analyzeduration` which is 5 by default. 

I tried to find out which streams are causing this. It seems that, in addition to the Audio+Video+Teletext+Subtitle-streams, ffmpeg learns about more streams from PMT, an example: 
`
Stream #0:0[0x54], 0, 1/90000: Unknown: none ([6][0][0][0] / 0x0006)
    Stream #0:1[0x65], 125, 1/90000: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, left), 720x576 [SAR 64:45 DAR 16:9], 1/50, max. 15000 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:2[0x66](deu), 208, 1/90000: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 256 kb/s
    Stream #0:3[0x67](mis), 208, 1/90000: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 192 kb/s
    Stream #0:4[0x68](deu), 127, 1/90000: Subtitle: dvb_teletext ([6][0][0][0] / 0x0006), 492x250
    Stream #0:5[0x69](deu), 5, 1/90000: Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
    Stream #0:6[0x6a](deu), 152, 1/90000: Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 448 kb/s
    Stream #0:7[0x816], 0, 1/90000: Unknown: none ([5][0][0][0] / 0x0005)
    Stream #0:8[0x87b], 0, 1/90000: Unknown: none ([11][0][0][0] / 0x000B)
`
The time it spents to find out it can not identify the "none" streams is giving us this large delay. This is even though we do not open demuxer-FDs for them, so ffmpeg does not get any data there, but it still keeps looking in the stream of course. 

I am not sure what is the best fix: Somehow, ffmpeg should be made aware that these streams are not interesting already when it probes the data (they might be EPG, some Smart-TV HTML-stuff, etc.). Is there a way to pass a "whitelist" of stream-ids to probe to ffmpeg? I am not aware of one (yet)... 
Of course lowering the analyzeduration for DVB by default could also work, but is not so nice (even 0.5 worked fine for me, but reception here is very good...).

**Comment by wm4** [comment]
>Is there a way to pass a "whitelist" of stream-ids to probe to ffmpeg?

Not that I know of...

**Comment by wm4** [comment]
Also, are you sure that's what's slowing it down?

**Comment by olifre** [comment]
> Also, are you sure that's what's slowing it down?

I assume from this: 
https://gist.github.com/olifre/38da6096ab04bd88026b#file-gistfile1-txt-L1570
After taking the full analyzeduration, these three streams are the only streams ffmpeg complains about. 
Reducing analyzeduration to 0.5 still allows the "good" streams to be detected just fine (with good reception...). 
That gist (from a version with `stream->streaming = true;`) also contains one channel-switch, the tuning takes about 1-2 seconds here (this is still the DVB device with not-so-well drivers / unknown quality firmware, normally switching is faster), then ffmpeg takes 5 s analyzeduration, so overall switching time is something like 6-7 seconds.

**Comment by wm4** [comment]
So, I know nothing about dvb. Is the ts stream remuxed? By the kernel or by the hardware? How does the PMT get into the stream? (ffmpeg needs it; I hear .ts streams without PMT should be considered broken and unplayable, and the hacks in ffmpeg which allow it anyway are nothing but pure evil.) If the stream is remuxed at some point, why can't the "unwanted" streams not be dropped at this point? Could ffmpeg be made to recognize and ignore the unwanted streams properly?

**Comment by olifre** [comment]
> So, I know nothing about dvb. Is the ts stream remuxed? By the kernel or by the hardware? 

I am afraid I am also no expert, but I believe this depends - at least for the "cheap" budget-type hardware, I think everything is done in the kernel, while full-featured hardware (which became more rare nowadays) the hardware handles almost everything, sometimes even including the decoding. 

From the client-application point of view: For each PID to look at, a demuxer-fd is opened and a filter set up. Then, magically, a multiplexed TS appears on the logical /dev/dvb/adapter0/dvr0 device. In principle, one could also get the streams separately from the demux-FDs, but I never saw an application doing that. 

Due to this logic, it also works to use an external application (e.g. szap-s2) to zap to a channel, keep it tuned, and then just call
`mpv /dev/dvb/adapter0/dvr0`
to play back the TV stream. 

> How does the PMT get into the stream? (ffmpeg needs it; I hear .ts streams without PMT should be considered broken and unplayable, and the hacks in ffmpeg which allow it anyway are nothing but pure evil.) 

The fun part is that the old code could not even get the PMT, since the PID of the PMT is not listed in the channels.conf (neither classic mplayer-style configs not vdr-vonfigs). The VDR-config contains a service_id, though. With the service_id, one can parse the PAT (which always has PID 0), look for the part corresponding to the service_id, from there find the PID for the PMT, and then also filter that one out. From this I am a bit confused as to how mplayer did / does that - the channels.conf does not contain the service-id, so apparently that only worked due to the ugly hacks... 

As another fun fact, szap-s2 does add a filter for the PMT PID by default. So also the default with szap-s2 will be a stream without PMT. 

> If the stream is remuxed at some point, why can't the "unwanted" streams not be dropped at this point?

I believe they are already. I do not add filters for those PIDs, so their data should not be in the stream at all. 
If I use szap-s2 and do not add filters for the teletext-PIDs nor further audio tracks, ffmpeg still "knows" they should be there, but mis-recognizes them (e.g. real audio tracks as audio with 0 channels). I assume it reads some kind of header information (even without PMT / PAT being there) and from that deduces the stream-ids which should be there. Then it does not receive any data for those streams (since there is no filter letting them through), and as such can not guess the real format. 

> Could ffmpeg be made to recognize and ignore the unwanted streams properly?

I just had a look in some public channel-list for this channel, it seems these PIDs are really for HbbTV data (i.e. some HTML and control commands for Smart TVs to provide channel-specific Web-like content). Maybe ffmpeg could be made to recognize them, but the first problem is that I do not even know how it learns about their existence (I do not know too much about raw DVB streams to know which other header information there can be...).

**Comment by olifre** [comment]
> Also, are you sure that's what's slowing it down?

Apparently I am wrong. 
I just disabled all filters, so the full stream arrives to ffmpeg (this is implemented via the pseudo-PID 8192). Then, it does NOT make use of the full analyzeduration, playback starts almost instantaneously. 
As "full stream" includes all programs on that transponder (5 video, 13 audio tracks...) this is not what one should really use. Still, it shows I must be missing something which ffmpeg expects to be present in the data. Let's see whether I can find out what that is....

**Comment by olifre** [comment]
> Then, it does NOT make use of the full analyzeduration, playback starts almost instantaneously.

Let me revert that statement - it just exceeded the probesize VERY fast. Increasing probesize to something large, it runs into the maximum analyzeduration again. 
This at least clears up that I am not missing any important PID in the filtering (there are also some metadata-pids, e.g. the NIT (network information table), but they should not be needed in the decoding). 

I guess the fastest way then is to ask the ffmpeg-DVB-experts as to how ffmpeg learns about these stream-ids, and how to tell ffmpeg to not try to probe unwanted ones...

**Comment by olifre** [comment]
Right now, I believe it is a good idea to read through the mpeg-ts parser (and stream-info finding) in ffmpeg code. I will play a bit with this to learn more about the gory details, and as to why ffmpeg uses the full analyzeduration. My last commits in #1409 are already a result of this (ffmpeg can parse the SDT, so we should give it to ffmpeg). 

There also seems to be code to ignore PIDs, and also code to continue analysis until all programs are matched with a PMT. I might take until tomorrow or so to have a larger understanding.

**Comment by olifre** [comment]
I read through the code, it was more readable than I expected. 
ffmpeg really learns the stream-IDs from PAT, so it also looks for streams even if they are not muxed into the TS. I mis-assumed it can do that without PAT before, since szap-s2 has a bug (it also adds the PAT to the TS even if told not to do so). I confirmed that, using a stream without PAT and PMT, ffmpeg only sees the streams which we give to it (but is unable to decode dvbsub and teletext due to missing PAT / PMT). 

The expected, but not-really-present streams seem to cause it to use the full analyzeduration. 
I have opened a ticket here: https://trac.ffmpeg.org/ticket/4228 with the proposal to add a whitelist. 

As mpv does not know these other PIDs, all other solutions are more complicated; we would have to parse the PAT ourselves more completely (to extract these PIDs) to add them to the TS, too. Even then, ffmpeg would need to learn to detect and ignore these formats. Of course this is also a good solution, I'll wait for the answer to the ticket and follow their suggestion. 

I guess you already saw that current git HEAD of ffmpeg has dvbsub-detection now with all the hacks (i.e. also without PMT)? Only teletext still needs the PMT, but of course as we have the PMT now, this is the much cleaner solution.

**Comment by wm4** [comment]
>The expected, but not-really-present streams seem to cause it to use the full analyzeduration.
I have opened a ticket here: https://trac.ffmpeg.org/ticket/4228 with the proposal to add a whitelist. 

You should probably bring this up on the ffmpeg-devel mailing list or IRC channel. Trac is mostly used for bug reports only. While ffmpeg-devel is for developers and not users, and user question are unwanted, this topic is already close enough to ffmpeg internals and development.

>I guess you already saw that current git HEAD of ffmpeg has dvbsub-detection now with all the hacks (i.e. also without PMT)?

No.

> Only teletext still needs the PMT, but of course as we have the PMT now, this is the much cleaner solution. 

Yes. Also, ideally mpv (especially --stream-dump) should produce valid streams, not streams ffmpeg happens to handle.

**Comment by wm4** [comment]
Looks like we never found the cause. I still blame libavformat though.
