### ISSUE TITLE
support touchscreen devices?

### ISSUE THREAD

**Issue by coderafei** [mpv-player/mpv#2396]
like surface pro

**Comment by ChrisK2** [comment]
Please elaborate on your question.

**Comment by Pacoup** [comment]
I feel like I can answer this.

My mom uses a Surface Pro with Windows 10 and mpv and the thing is, the OSD only appears over the playing media when the mouse is moving.

This is nice because as soon as you stop moving your mouse, the OSD disappears.

But on a touch device, when you have no keyboard to control playback, this can be quite finicky as the OSD only appears for a brief moment after you've touched the screen and then disappears and deactivates, making controlling mpv solely from a touch screen quite the challenging affair.

So that's the problem, now as for a solution, I'm not sure. Maybe add a "show/hide OSD on click (touch)" option for touch screen users?

**Comment by haasn** [comment]
> So that's the problem, now as for a solution, I'm not sure. Maybe add a "show/hide OSD on click (touch)" option for touch screen users?

Seems reasonable enough to me. The way I would probably like to see this
implemented is with a (new?) setting to show the OSD. That way you could
simply add a mapping for “left mouse button” that toggles this state.

**Comment by paulguy** [comment]
Could the input differentiate between a touch and a click?  I imagine there's a way to do this.

**Comment by ChrisK2** [comment]
The OSC offers some (http://mpv.io/manual/master/#on-screen-controller-hidetimeout)[options] to change the hide delay, maybe increasing it helps already?

I have some Windows touchscreen devices accessible at work, I'll try to test how mpv behaves there.

**Comment by RussianNeuroMancer** [comment]
I just find that mpv doesn't support touch events under Wayland.

**Comment by Akemi** [comment]
please open a new issue and exactly specify what is wanted.

**Comment by hiiamboris** [comment]
For those coming from google: what works on W10 is getting [GestureSign](https://www.microsoft.com/en-us/p/gesturesign/9n45wqvk2qqw) and configuring a bunch of screen gestures for `mpv.exe` (everything except rotation has to be configured as "continuous" so it keeps sending hotkeys as long as you move your fingers):
| ![](https://i.gyazo.com/a26972658bdd95fa6a31d1ecb13b80e2.png) | ![](https://i.gyazo.com/9f726567d458a5eebf8f0ab564be8cab.png) |
|-|-|
Then in `input.conf`:
```
Right seek  5
Left  seek -5

w no-osd add video-pan-y +0.02
s no-osd add video-pan-y -0.02
a no-osd add video-pan-x +0.02
d no-osd add video-pan-x -0.02

Alt+RIGHT no-osd cycle video-rotate 90
Alt+LEFT  no-osd cycle video-rotate -90

Ctrl+MOUSE_BTN3 no-osd add video-zoom  0.1
Ctrl+MOUSE_BTN4 no-osd add video-zoom -0.1
```
Last 2 hotkeys get converted by W10 natively into Ctrl+MWheel, so pinch gestures trigger zoom. The rest allows to get: 3-finger back/forward skip, 2-finger shift of the video in all directions.

**Comment by kocoman2** [comment]
is there support for this in chromebook/linux? thx
