### ISSUE TITLE
File type icon with white background.

### ISSUE THREAD

**Issue by hkenneth** [mpv-player/mpv#2454]
It's related to issue #2050 which has been closed. Not sure if I should open a new ticket. So I have created a new file type icon with white background.

![screen shot 2015-11-07 at 9 23 31 am](https://cloud.githubusercontent.com/assets/1007754/11015768/4137f436-8531-11e5-9dfb-29c8fadd35c1.png)

https://drive.google.com/file/d/0BxjG-Ea9-dhtd3dJRm8tVkRJWGs/view?usp=sharing

I found different versions of the app icon in the repository. The SVG version is slightly different from the ICN file. I used the ICN file to make this icon.

**Comment by kevmitch** [comment]
https://raw.githubusercontent.com/rossy/mpv-install/master/mpv-document.ico

**Comment by kevmitch** [comment]
I think I like the one above used in [mpv-install](https://github.com/rossy/mpv-install) for Windows because it features the mpv colour more prominently. I'm sure there are extensive Apple design guidelines, so it's up to MacOS people if this is more appropriate for them. However, I think that we generally want to try and avoid adding thousands of icons to the git repository.

**Comment by Akemi** [comment]
i actually am fine with the current one, though i don't see it any more because i use [QLVideo](https://github.com/Marginal/QLVideo) for preview thumbnails.

**Comment by kevmitch** [comment]
ok, so that's two more or less against. someone can reopen if this is interesting to them.
