### ISSUE TITLE
Handle more (useful) features provided by _NET_WM_BYPASS_COMPOSITOR

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#2582]
I was thinking about the "--x11-bypass-compositor" feature and I think it will be more logical to have the choice to use it only in fullscreen. Maybe by adding a "--x11-bypass-compositor-fs" option to use it only in fullscreen (without removing the current option to always bypass compositor) ?

**Edit 02/03/16**

Useful features provided by _NET_WM_BYPASS_COMPOSITOR that should be implemented :

- No bypass : _NET_WM_BYPASS_COMPOSITOR=0 ([DONE](https://github.com/mpv-player/mpv/commit/ad3f75cc94adac9781fda93cc2a7c0c23ac0a606))
- Compositing always enabled : _NET_WM_BYPASS_COMPOSITOR=2
- Compositing always disabled : _NET_WM_BYPASS_COMPOSITOR=1 ([DONE](https://github.com/mpv-player/mpv/commit/ad3f75cc94adac9781fda93cc2a7c0c23ac0a606))
- Compositing disabled only in Fullscreen : _NET_WM_BYPASS_COMPOSITOR=1 if in Fullscreen

**Comment by wm4** [comment]
This sounds more like something the compositor should implement.

**Comment by Paviluf** [comment]
I don't think so, in the doc they say :
> The compositing manager MAY bypass compositing for both fullscreen
and non-fullscreen windows if bypassing is requested

http://cgit.freedesktop.org/xdg/xdg-specs/tree/wm-spec/wm-spec.xml#n1579

**Comment by wm4** [comment]
I mean the compositor should provide an option to disable composition for windows in fullscreen.

I can't just option for every combination of use cases people come up with. Better fix these compositors.

**Comment by Paviluf** [comment]
That's not what I mean. According to the doc the compositor should always disable compositing when it receive "_NET_WM_BYPASS_COMPOSITOR". But what make more sense is to disable the compositing only in fullscreen. So we should send "_NET_WM_BYPASS_COMPOSITOR" only in fullscreen, if it's the choice of the user.

Maybe it's more simple to modify "--x11-bypass-compositor" to use 3 values : no, always, fullscreen
With "--x11-bypass-compositor=fullscreen" by default.

**Comment by wm4** [comment]
Again, I think the compositor should do this.

But we also can just always enable the bypass hint in fullscreen, without the ability to disable it.

What's the point of adding an option if nobody is going to know about it?

**Comment by Paviluf** [comment]
> I mean the compositor should provide an option to disable composition for windows in fullscreen.
> Again, I think the compositor should do this.

I don't understand why you say that because the purpose of the bypass hint is to override the compositor settings. Some of the available compositors (kwin {I use it now}, xfwm4, compiz, mutter, etc...) already provide an option to disable composition for windows in fullscreen (unredirected windows) but that's not the point.

> But we also can just always enable the bypass hint in fullscreen, without the ability to disable it.

We can but why removing the user choice ?

> What's the point of adding an option if nobody is going to know about it?

I don't understand why you say that because like the others options, the users have to look in the doc to find them.

> I can't just option for every combination of use cases people come up with. Better fix these compositors.

No need to fix the compositors for this feature (even if some really need more features). **The point of "_NET_WM_BYPASS_COMPOSITOR" is to give the control of the compositor to the app**. So for me it's clear that the app have to handle the cases it need, like :

- No bypass
- Always bypass
- Fullscreen bypass

I don't think windowed bypass make sense for MPV, so it's not needed.

I'm really grateful for all your work on MPV and for that I thank you a lot. But I don't understand why we can't agree on this ;-)

**Comment by haasn** [comment]
What I don't understand is what's wrong with always bypassing the compositor.

The compositor is mostly useful for windows that can't vsync themselves. mpv can vsync properly, both in windowed and fullscreen modes. So why not just have it always bypass?

**Comment by Paviluf** [comment]
When you use MPV in windowed mode you can do other things at the same time and want the windows composited.

**Comment by mc4man** [comment]
This doesn't affect compiz one way or the other as in  compiz you can,
Add Mpv to the list to exclude from Fullscreen Unredirect match,  though mpv is fine added or not, doesn't matter.
Same holds true for the mpv x11-bypass-compositor option, whether yes or no  an mpv window is fine, same in mpv fullscreen.

Here the mpv option at "no" doesn't affect other windows so also not an issue.

**Comment by wm4** [comment]
>When you use MPV in windowed mode you can do other things at the same time and want the windows composited.

And what's the use to leave it composited in fullscreen?

**Comment by Paviluf** [comment]
> And what's the use to leave it composited in fullscreen?

Some users can have tearing so an option to leave it composited in fullscreen make sense for me.

**Comment by wm4** [comment]
Again, this sounds like the responsibility of the compositor. This is just a huge clusterfuck.

**Comment by Paviluf** [comment]
No. If MPV disable the compositing with the hint and there is tearing you can't blame the compositor obviously. You just need to be able to disable the hint in MPV for that case.

**Comment by wm4** [comment]
Sounds like setting the hint didn't help with anything and only causes problems.

Really, this is not mpv's business. It's the broken drivers and compositors that should be fixed.

**Comment by Paviluf** [comment]
I really don't see why you react like that :(
The hint is a standard way for giving the control of the compositor to an app. What we did was right (enable it or not). It just need one more case to be handled.

I agree that some fixes have to be made in the drivers and compositors but that don't enter in the equation here because the hint give you the control of the compositor and by this the app should handle the case it need and useful for the users.

It'll probably make you crazy but to be fair an other addition can be useful 

> A value of 2 hints the compositor to not disabling compositing of this window.

- No bypass
- Compositing always enabled
- Compositing always disabled
- Compositing disabled only in Fullscreen

Maybe you should reread the doc:
http://cgit.freedesktop.org/xdg/xdg-specs/tree/wm-spec/wm-spec.xml#n1579

By the way, even if it's not the purpose of this feature, that will probably help some people that deal with half backed drivers and compositor.

As a side note I have no problem at all, I use Kwin that allow me to create a rule to disable the compositing when MPV start and I have no tearing and a perfect fluidity. That said I just try to help for the good of open source that deserve things that work perfectly and that's too rare.

**Comment by Paviluf** [comment]
I still hope that can be implemented. Mutter is compatible and Kwin will be very soon (https://git.reviewboard.kde.org/r/126561/)

To summarize :

- No bypass : _NET_WM_BYPASS_COMPOSITOR=0 ([DONE](https://github.com/mpv-player/mpv/commit/ad3f75cc94adac9781fda93cc2a7c0c23ac0a606))
- Compositing always enabled : _NET_WM_BYPASS_COMPOSITOR=2
- Compositing always disabled : _NET_WM_BYPASS_COMPOSITOR=1 ([DONE](https://github.com/mpv-player/mpv/commit/ad3f75cc94adac9781fda93cc2a7c0c23ac0a606))
- Compositing disabled only in Fullscreen : _NET_WM_BYPASS_COMPOSITOR=1 if in Fullscreen

**Comment by Paviluf** [comment]
Now Mutter and [Kwin](https://bugs.kde.org/show_bug.cgi?id=349910) are compliant !

**Comment by Paviluf** [comment]
Still no interest in this nice little feature ?

**Comment by haasn** [comment]
I don't understand the use case of the value ‘2’. When would you ever need to enable compositing *only* in mpv, but be unable to do so via other means?

**Comment by Paviluf** [comment]
The value "2" simply says to the compositor to keep the compositing active as far as the app is running. It prevent the compositor to disable the compositing by itself.

I can't say it better than the specification :

> A value of 0 indicates no preference. A value of 1 hints the
compositor to disabling compositing of this window. A value of 2 hints
the compositor to not disabling compositing of this window. All other
values are reserved and should be treated the same as a value of
0. The compositing manager MAY bypass compositing for both fullscreen
and non-fullscreen windows if bypassing is requested, but MUST NOT
bypass if it would cause differences from the composited appearance.

**Comment by Paviluf** [comment]
I'm still hoping that a developer will have interest in improving the "--x11-bypass-compositor" option to cover the useful cases and to give the user more control to let him choose what is the best for him.

Something like that will be perfect with all useful cases covered. You set the option to "no" by default, like it is now, and that's the user that decide what behavior he want. 

**--x11-bypass-compositor :** 
- **no** : No bypass like the current "no" setting (DONE) (Default) [_NET_WM_BYPASS_COMPOSITOR=0]

- **always-on** : Compositing always enabled [_NET_WM_BYPASS_COMPOSITOR=2]

- **always-off** : Compositing always disabled like the current "yes" setting (DONE) [_NET_WM_BYPASS_COMPOSITOR=1]

- **fs-off** : Compositing disabled only in Fullscreen [_NET_WM_BYPASS_COMPOSITOR=1 only in fullscreen]

For instance, I would use **fs-off** (Compositing disabled only in Fullscreen).

Thanks !

**Comment by Paviluf** [comment]
It can't be that hard to provide the features I suggest. The "no" and "always-off" is already implemented. The "always-on" (_NET_WM_BYPASS_COMPOSITOR=2) is really really easy. The "hard" thing is to re-apply the hint if the fullscreen state change for "fs-off". But for skilled developers like you guys I'm sure it's not a problem (tell me if I'm wrong) ;)

I write this for fun based on this commit https://github.com/mpv-player/mpv/commit/ad3f75cc94adac9781fda93cc2a7c0c23ac0a606 :)
```
if (vo->opts->x11_bypass_compositor != "no") {
	if (vo->opts->x11_bypass_compositor == "always-on") {
		long bypass_compositor = 2; // request enabling compositor
	}
	else if (vo->opts->x11_bypass_compositor == "always-off") {
		long bypass_compositor = 1; // request disabling compositor
	}
	else if (vo->opts->x11_bypass_compositor == "fs-off" && is_fullscreen) {
		long bypass_compositor = 1; // request disabling compositor for fullscreen
	}
	else {
		long bypass_compositor = 0; // let the compositor handle compositing
	}

	XChangeProperty(x11->display, x11->window,
		XA(x11,_NET_WM_BYPASS_COMPOSITOR), XA_CARDINAL, 32,
		PropModeReplace, (unsigned char *)&bypass_compositor, 1);
}
```

**Comment by Paviluf** [comment]
@wm4 Can't something like this be easily implemented ?

**Comment by qmega** [comment]
I think those names are confusing: The option is called bypass-compositor, but your "on" means *don't* bypass and "off" means the opposite of "no", whereas they're usually synonyms boolean-wise. Also, compositing always enabled doesn't seem useful for mpv. I'd keep the current "yes" and "no", and just add an "fs-only" (instead of "fs-off").

If adding an extra value to the option is really not wanted, a compromise would be to make changing the option at runtime work, so you could implement fs-only with a simple lua script:
```lua
mp.observe_property("fullscreen", "bool", function (name, value)
    mp.set_property_bool('options/x11-bypass-compositor', value)
end)
```
(This script currently "works", but doesn't actually do anything because the option is only applied on window creation.)

**Comment by Paviluf** [comment]
@wm4 Thank you so much !!! You are awesome !

If I may, and I really don't want to bother you, it will be great if you can add "always-on" too (_NET_WM_BYPASS_COMPOSITOR=2) ?
Some people can found it useful to avoid disabling the compositor (bad driver, bad compositor, etc...) and it's a really tiny addition now :D

Thanks !!!

**Comment by Paviluf** [comment]
@wm4 Thanks a lot ! https://github.com/mpv-player/mpv/commit/55846641eac86d55817be20eab00b8256a7e1c9a
