### ISSUE TITLE
Please add help overlay for keyboard shortcuts (triggered with ?) to the overlay UI.

### ISSUE THREAD

**Issue by shmerl** [mpv-player/mpv#2590]
mpv has a lot of handy keyboard shortcuts, but without thoroughly studying man page or experimenting with all kind of combinations it's hard to figure out what does what.

It could be good to make some help overlay UI showing up in the player when user presses ? for example (similar to how Gmail does that). And making it in the form that mimics keyboard layout would be even better.

**Comment by kevinlekiller** [comment]
You can already kind of do this: `mpv --input-test --force-window --idle`

https://mpv.io/manual/master/#options-input-test

https://mpv.io/manual/master/#command-interface

**Comment by shmerl** [comment]
Interesting, but it's not exactly as user friendly as keyboard layout popping up on ? key press.

**Comment by AirPort** [comment]
There also is this official bindings' chart: https://github.com/mpv-player/random-stuff/blob/master/key_bindings_chart/mpbindings.png

**Comment by shmerl** [comment]
@AirPort : Yep, something like that showing up in the UI on ? key press would be good.

**Comment by rrooij** [comment]
Maybe it is a good idea to have a Lua script for this kind of behavior. My suggestions for this:

* Use the default OSD for displaying the keyboard layout
* Bind the keys as specified in the user's input.conf. If the user has other key options, display those instead of the default keys.

The only issue I see with a Lua script is that it will require Lua to display the OSC keyboard. But to be fair, I don't think that this feature will be used by people not having Lua installed

**Comment by wm4** [comment]
That all sounds nice and fun, but who will figure out how to make a nice layout, and a way to map the (sometimes cryptic) commands to a nice help text?

**Comment by wm4** [comment]
> and a way to map the (sometimes cryptic) commands to a nice help text?

On that topic, it might be possible to associate a help text each binding in the default input.conf - maybe. Still leaves the question how to nicely layout it.

**Comment by bricewge** [comment]
It seems to me that the UI of Emacs' [Hydra](https://github.com/abo-abo/hydra) can be a good fit for the help OSD, here are [some](https://camo.githubusercontent.com/2f21935cc3257d3d6dc975481a19d740a07546c4/687474703a2f2f6f72656d6163732e636f6d2f646f776e6c6f61642f68796472612d72656374616e676c652e706e67) [examples](http://oremacs.com/download/hydra-org-global.png) of it.

It is a list all the binded commands, prefixed by the key that trigger it or if the letter of key is part of the command it is highlighted, like this:
- **q**uit 
- subtitle **v**isibility
- **>** previous file
- **3** brightness -
It help in remembering the keys by suggesting a mnemonic.

**Comment by hi2u** [comment]
Something like the screen you see when you hit `?` in Gmail would be awesome (especially if it accounts for your current key config rather than being hard-coded to the defaults)...

![gmail-keyboard-help](https://user-images.githubusercontent.com/9689599/43456730-f82b4db2-9507-11e8-8cd7-05f8e22308d6.png)

I rarely need to use anything aside from seeking, pausing and quitting, but when I do it's a bit annoying having to get off the couch and go up to a computer and search online or read help files to do something that should be as a quick as a single keypress or click.  I've tried remembering the keys, but I don't use any of the functions enough to remember them.  So most of the time I can't be bothered and just open VLC to get it done quickly and get back to watching my video.

I really prefer MPV, but I think these kind of easy-of-use things could make it much better and more popular.  Even some of my friends that run Linux media boxes stick to VLC for these reasons, I haven't been able to sell them on MPV.

Hope I don't sound like a whinger, just want to see MPV come along in this area a bit so that I and others can use it more often.

> There also is this official bindings' chart: https://github.com/mpv-player/random-stuff/blob/master/key_bindings_chart/mpbindings.png

To me these kinds of charts are more useful when you've just accidentally hit a key and want to know what you just did (kind of reverse engineering).  Otherwise when you trying to figure how to do something, you have to basically read through the entire thing every time.

Anyway, thanks for all your work on MPV, it's a great player in general.

**Comment by NightMachinary** [comment]
@AirPort I think that chart should be mentioned in the manpage. It's awesome.

**Comment by wm4** [comment]
> Something like the screen you see when you hit ? in Gmail would be awesome (especially if it accounts for your current key config rather than being hard-coded to the defaults)...

A script could do this. You can get even input.conf comments (after each binding) via script now.

**Comment by Dudemanguy** [comment]
Added by #9013.
