### ISSUE TITLE
youtube-dl default option "--yes-playlist" ignored.

### ISSUE THREAD

**Issue by IlyaIndigo** [mpv-player/mpv#2592]
mpv witout option "ytdl-raw-options=yes-playlist=" does not play a playlist.
Why does he ignore the logical behavior of the default youtube-dl?
Command for example:
mpv https://www.youtube.com/watch?v=-TqYul6LOyQ\&list=PL5FMLPRj1j6IChoB7nBKYNjCNQ-DBnaq7

**Comment by wiiaboo** [comment]
Because ytdl_hook.lua passes `--no-playlist` by default: https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua#L85

**Comment by IlyaIndigo** [comment]
Why is it doing this?

**Comment by wiiaboo** [comment]
I assume because you're using a video link with playlist attached. If you use just the playlist link it should load up the whole playlist.

**Comment by IlyaIndigo** [comment]
Youtube works with playlists only in this format, and provides links only in this format.

**Comment by wiiaboo** [comment]
Not really. You can "Copy link" from the playlist's name to get just the playlist.
I assume the ytdl_hook.lua authors preferred that when using a link to a video and a playlist youtube-dl just retrieves the video.
If you're not OK with that default behavior you can use `ytdl-raw-options=yes-playlist=` in your mpv.conf like you said in the first post.

**Comment by IlyaIndigo** [comment]
Yes, you can get a view of the link https://www.youtube.com/playlist?list=PL5FMLPRj1j6IChoB7nBKYNjCNQ-DBnaq7
But anyway, why change the behavior of youtube-dl?
It's like the default mute, and then offer it to unmute in the configuration file.

**Comment by wiiaboo** [comment]
Because they're different developers with different expectations/tastes. Personally makes more sense to me too.

**Comment by ChrisK2** [comment]
The problem is, you often find the video+playlist links on the internet, posted with the intention to link to a specific video. If the user passed such a URL to mpv without us setting ``--no-playlist``, youtube-dl would fetch the whole playlist for us and then we would start playing with first video in the playlist, not the one specified in the link.

As already suggested, pass an explicit playlist link to mpv or use the ``yes-playlist`` playlist option to override ``--no-playlist``.

**Comment by haasn** [comment]
Personally I can't stand how youtube attaches the playlist to URLs even when I only click on a single video. If I want to view an entire playlist, then I'm going to click on the playlist itself - not on a video *in* that playlist.

So I think mpv's default behavior is justified, as the alternative is more annoying than it's ever beneficial.

**Comment by wiiaboo** [comment]
If youtube-dl exported the index or the video ID it could be usable. As it is, ytdl_hook.lua would have to parse the original url for index/ID and it'd only work with Youtube (until they changed it).

**Comment by SteveJobzniak** [comment]
@wiiaboo True. That being said, YouTube is the most popular service by about a billion, so it would be worth improving the experience. And playing a playlist URL and getting only one video is not intuitive. How about coding this logic: If site == YouTube, pass "yes-playlist", and then scan the returned result for the "watch?v=..." video ID and if found, start the playlist from there.

The YouTube video URL format has stayed the same since YouTube launched.
