### ISSUE TITLE
Please explain; vo_opengl: require --enable-gpl3 for nnedi?

### ISSUE THREAD

**Issue by Geyup** [mpv-player/mpv#2600]
Can someone please explain what this is all about?

 vo_opengl: require --enable-gpl3 for nnedi?

GPL3 I understand as far as the ```GNU General Public License``` is concerned, but not sure what this ```-enable-gpl3``` means and what nnedi is?

Is this  ```vo_opengl``` a new or updated option?

thank you

**Comment by lachs0r** [comment]
The `opengl` video output has a feature called prescaling (which is used for special scaling algorithms that can, for example, only enlarge by factors of 2), and nnedi3 is one of the available prescalers. However, it was found that some of the code may have a license incompatibility with (L)GPLv2, which is why this option was added (so that users may choose whether or not to use mpv under the GPLv3 license). The nnedi3 prescaler will not be available unless the `--enable-gpl3` option is used.

**Comment by Geyup** [comment]
Are these prescalers options that need to be added to the mpv config in order to use?

Sorry I'm not to up on all the goodies, I just play a video, have a few options in my config and that's about it LOL...

thanks

**Comment by lachs0r** [comment]
Yes, they are not enabled by default.

**Comment by Geyup** [comment]
Somwhere I can read about it, personally, even after reading I would really know what is going to be the best way to go about this.

How do you like this prescaler?

And to be honest, not sure I remember the differences between gplv2 and v3? hmm

I have a i7 with a Nvidia GTX660m, this is all I use in my config;

```
vo=opengl-hq
hwdec=vdpau
geometry=50%x50%+50%+50%
ao=alsa
volume=50
terminal=no

**Comment by Geyup** [comment]
Oh wait a second, this is only going to be useful if you want to scale a video bigger? Simply watching a video does nothing?

**Comment by Geyup** [comment]
https://github.com/mpv-player/mpv/wiki/User-Scripts

Hmm double the resolution...

**Comment by dylanaraps** [comment]
You have to add that flag at compile time.

**Comment by Geyup** [comment]
@dylanaraps yes I understand this, I'm a Linux geek, but not the best video geek hehe...

I'm just trying to figure out for what purpose I would want to use a prescaler.

Looking at ```man mpv``` now;

```
 prescale=<filter>
                     This option provides non-convolution-based filters for upscaling. These filters resize the video to multiple of the original size  (all
                     currently supported prescalers can only perform image doubling in a single pass).  Generally another convolution based filter (the main
                     scaler) will be applied after prescaler to match the target display size.
```

**Comment by kevmitch** [comment]
nnedi3 is an ```exotic``` scaler that uses a neural network to increase the image to a size closer to your display. The fact that it is a prescaler comes down to how it works - it will only double the image size. It tends to work well for video games or animation or other sources with sharp sudden contrasts. It also requires significant GPU power.

Normally you would just use ```opengl-hq``` which includes more the conventional scaler ```spline36```, which is pretty good. If you really want the best general purpose scaler you can try ```ewa_lanczossharp```. You can take a look at some comparisons [here](https://github.com/haasn/mpvhq-upscalers/blob/master/Rose.md), unfortunately mpvs internal nnedi3 scaler isn't featured there, but an external implementation that should theoretically be the same is.

**Comment by lachs0r** [comment]
Well, the rule of thumb here is: If you can’t see an improvement, don’t use it.

Based on my opinion, I would not recommend nnedi3.

Pros:
* Can result in smooth, sharp edges with little aliasing depending on content
Cons:
* Prohibitively slow
* Notoriously bad with grainy footage (and basically anything that’s not a line drawing); causes slight warping artifacts

The implementation used by mpv should actually have slightly better quality than the external implementation (AviSynth/VapourSynth plugin) given the same settings, since it doesn’t take some of the performance shortcuts.

Anyway, yes, `ewa_lanczossharp` is the scaler I would recommend, maybe paired with the `scale-antiring` option. And if that’s not enough, you could try disabling `hwdec`, because it means that chroma scaling and color conversion is done by VDPAU instead of mpv’s `opengl` renderer, resulting in worse quality. But, again, see for yourself if it makes a difference to you.

**Comment by Geyup** [comment]
In my ~/.mpv/config?
```
vo=opengl-hq
scale=ewa_lanczossharp
scale-antiring=1
hwdec=vdpau
```

thank you

**Comment by kevmitch** [comment]
```
vo=opengl-hq:scale=ewa_lanczossharp:scale-antiring=1
```

**Comment by Geyup** [comment]
I don't notice a bloody damm bit of difference LOL...
