### ISSUE TITLE
Change wid while mpv is running

### ISSUE THREAD

**Issue by Amaranthes** [mpv-player/mpv#2602]
It woul be great if we could change the wid option during playback.

### The Problem:
Tkinter destroys the window and creates a new one when stwitching from windowed mode to fullscreen and vice versa, resulting in a new window handle.

**Comment by wm4** [comment]
You will have to create another X11 window, whose window ID is passed as wid to mpv, and which is not destroyed when switching fullscreen. Then you can reparent that window as you please.

Making wid changeable during playback would be complex, and you wouldn't be able avoid the race conditions that will occur while the Tk window is recreated. What Tk does here is completely horrible anyway. There is no reason to recreate a window just because it's fullscreened.

**Comment by Amaranthes** [comment]
> Making wid changeable during playback would be complex, and you wouldn't be able avoid the race conditions that will occur while the Tk window is recreated. What Tk does here is completely horrible anyway. There is no reason to recreate a window just because it's fullscreened.

Fair enough.
Anyway, I fixed my problem now by using the Win32 API via PyWin32 to switch to fullscreen.
