### ISSUE TITLE
Mac version should have 'mpv > about', proper fullscreen mode, proper GUI.

### ISSUE THREAD

**Issue by negativeions** [mpv-player/mpv#2607]
There is no mpv > about in mac which does not conform to standards. This should be fixed. A proper fullscreen mode that takes a space is needed, should be fixed. A proper GUI so that the superior player that is mpv -- the future of video playback -- can be used by everyone, not just terminal losers who don't care about other people but just their own nerd needs. Thanks a lot. Keep up the good work.

**Comment by wm4** [comment]
Please don't conflate multiple issues into one. This would just create a confusing discussion and likely no results. Closing as invalid.

**Comment by lachs0r** [comment]
I won’t comment on those OS X things because I have no idea about those (they sound like valid points, though), but the GUI issue applies to all platforms.

The question here is what you’re looking for in a “proper” GUI. I’d like to have a playlist editor, others might want a settings editor, but both things are difficult to implement with our current UI approach. That said, the “proper” way to do this (by using native UI toolkits) is not going to happen in mpv itself. This kind of thing is simply out of scope. I know you won’t like this, but cutting down on extra fluff that has nothing to do with playback and/or only uses up developer resources has helped to make mpv as good and flexible as it is. It doesn’t do a lot of things (actually it does), but it does most of those things well, as you might have noticed. Also, we’re all terminal losers who don’t care about other people but just our own nerd needs.

But that’s where `libmpv` comes in: Grab a toolkit of your choice and use it to build a frontend with all the UI features you want. Or beg someone to do it for you (I’m not interested).
