### ISSUE TITLE
backend=dxinterop does not work on Optimus

### ISSUE THREAD

**Issue by thiagokokada** [mpv-player/mpv#2620]
I am testing the new `backend=dxinterop` option. It seems that nnedi3 does not work with this mode, since I can put anything I want (for example, absurd configurations like `vo=opengl-hq:backend=dxinterop:scale=ewa_lanczossharp:cscale=ewa_lanczossoft:interpolation:tscale=mitchell:temporal-dither:prescale=nnedi3:prescale-passes=5:prescale-downscaling-threshold=32:nnedi3-neurons=128:nnedi3-window=8x6` and it makes no difference at all for playback performance, while using something similar with `backend=win` makes it very slow, like one frame after several seconds). Is this the expect behavior or is there something wrong? Did not find anything in the documentation except that this backend is experimental for now.

Since I am already doing this, is there any other option that is not supposed to work with `backend=dxinterop`, like `interpolation`? It seems the behavior with `interpolation:tscale=mitchell` is different between `backend=dxinterop` and `backend=win`, however I am not sure.

Edit: FYI, I have a GeForce 660M in a Core i7-3610M laptop (a Lenovo Y580). While it does use NVIDIA Optimus, I made sure to force mpv to run in dGPU.

**Comment by rossy** [comment]
It's definitely supposed to work. ``backend=win`` and ``backend=dxinterop`` both use WGL for rendering, so any difference in supported features or visual output between the two of them should be considered a bug. The difference between those backends is that ``backend=win`` presents the rendered frames to a window with the standard SwapBuffers() command, but ``backend=dxinterop`` renders to a texture, which is presented using a Direct3D 9Ex swapchain, the advantage being that Direct3D gives us control over frame latency and seems to be better at syncing with the compositor, so it makes interpolation more accurate and it drops less frames.

So, interpolation should also work with dxinterop, and if anything, it _should_ actually look better than it does with ``backend=win``.

I'm not sure if it will help, but could you post a log (with ``--log-file=log.txt``) for ``backend=dxinterop`` and ``backend=win``.

**Comment by m45t3r** [comment]
@rossy well, it does look better interpolation with ``backend=win``.

Ok, here is the logs (I played the file ``[AnimeRG] Dragon Ball Super - 19 [720p].mkv`` for 10 seconds each), only changing the backends:

[dxinterop](http://pastebin.com/CBFXwKwb)
[win](http://pastebin.com/sRTGCyc5)

It really seems that nnedi3 really does not work with ``backend=dxinterop``. For example, lines 322, 362, 365, etc. does not exist in the dxinterop logfile.

**Comment by bjin** [comment]
> `[   0.285][v][vo/opengl] No advanced processing required. Enabling dumb mode.`

It seems to be the cause, dumb mode somehow enabled for `backend=dxinterop`

**Comment by rossy** [comment]
It seems like the dxinterop backend is failing to initialize and mpv is falling back to ``vo=opengl`` because of the trailing comma on the vo= line.

dxinterop fails here:
```
[   0.189][f][vo/opengl-hq] Couldn't share rendertarget with GL: 0xc007006e
```

I'm just guessing, but maybe this is to do with switchable graphics. If the Direct3D device is created on the iGPU and the OpenGL context is created on the dGPU, I don't think they will be able to share resources. I'm not sure how to force them to both be created on the same adapter.

**Comment by m45t3r** [comment]
@rossy well, this does make sense. So this is why I thought that ``tscale=mitchell`` was very different with ``backend=dxinterop``. It is simple not working at all.

So this issue should be something like: backend=dxinterop fails with NVIDIA Optimus.

**Comment by Cpuroast** [comment]
I'd like to quickly point out that "tscale=mitchell:tscale-clamp" is actually the default tscale method since 0.14, so having it or not in you vo line should have no impact whatsoever, as it's getting used regardless.

Also, you misread rossy's comment, he said that interpolation should look better with backend=dxinterop than it does with backend=win.

He also mentions that you have a trailing comma as in "," at the end of your vo line which might be causing some problems with the backend init.

**Comment by m45t3r** [comment]
@Cpuroast yeah, I know, however I like to test different `tscale` options (I still prefer oversample over mitchell, btw), so it is easier to maintain this line there to remove and readd every time I change the `tscale` filter.

No, I did not missed rossy comment, with `backend=dxinterop` my system was really going back to `vo=opengl`` thanks to the trailling comma, so it does not matter if interpolation looks better with `backend=dxinterop`` because dxinterop simple does not work in my system.

And even if my laptop could not handle it, it is not like I can't test this option, nor the fact that `backend=dxinterop` does not work with NVIDIA Optimus is not a bug. Anyway, it isn't like my GeForce GTX 660M does not work at all with NNEDI3, I can get the majority of videos running with it using more reasonable options (and `backend=win`, where it does work). I used the options in the OP exactly because I found it strange that I did not get any frame drop at all even using the most absurd configuration for NNEDI3.
