### ISSUE TITLE
dxinterop doesn't work with nnedi3 in fullscreen?

### ISSUE THREAD

**Issue by alabrand** [mpv-player/mpv#2671]
I tried enabling dxinterop together with nnedi3 and it works in windowed mode. But as soon as I enter fullscreen mode it starts stutter-flickering. What I mean by that is the video stutters intermittently while it also flickers, almost like there is screen tearing, but it isn't screen tearing. This only happens in fullscreen, windowed mode is fine.

Is this maybe a bug because I have a G-Sync monitor and it doesn't play well with dxinterop? Or is this maybe a bug with dxinterop and nnedi3?

FWIW OpenGL works perfectly as it always has been in both windowed and fullscreen.

**Comment by wm4** [comment]
I don't see any reason why this would happen. Are there any errors on the terminal? Log with -v?

>Is this maybe a bug because I have a G-Sync monitor and it doesn't play well with dxinterop? Or is this maybe a bug with dxinterop and nnedi3?

I don't see why g-sync would break it either.

**Comment by wm4** [comment]
CC @rossy

**Comment by alabrand** [comment]
Hope this helps. It's more visible on some videos/scenes than others, so it seems very irregular. Action scenes have it the most.

[output.txt](https://github.com/mpv-player/mpv/files/77445/output.txt)

**Comment by bjin** [comment]
Could you test with following performance related changes, to see if it's a performance issue or not?

* add `nnedi3-upload=shader`
* remove `interpolation`
* add `nnedi3-neurons=16`

**Comment by alabrand** [comment]
Following bjin's suggestions worked. The stutter flickering has dissapeared. I wouldn't say for sure that this is a matter of optimization or not because the stutter flickering doesn't happen with OpenGL backend even if I use 128+ neurons. Maybe nnedi3 simply doesn't play well with DirectX layers?

Either way, feel free to mark this issue as solved.

**Comment by bjin** [comment]
Could you try those three changes one by one? I somehow suspect it's mostly caused by the use of `interpolation`, which might behave differently with `dxinterop`.

**Comment by alabrand** [comment]
Alright, seems like the problem was still there, albet less so. The only way to fully get rid of it is to set neurons to 8. Neither Interpolation or nnedi3-upload=shader seems to matter. So it's probably an optimization issue then, specifically to do with the DirectX Layer maybe?

**Comment by quilloss** [comment]
mpv seems to only support 16, 32, 64, and 128 neurons. Using 8 or 128+ neurons should result in an error. I suspect that mpv ignore your entire nnedi3 configuration due to that error and you just do not get the performance loss due to nnedi3 scaling.

**Comment by rossy** [comment]
It's possible that the dxinterop backend performs worse than the WGL one. It does the same amount of work as the WGL backend, in that it renders to the backbuffer using WGL and does a single copy from the backbuffer to the window surface, but when using WGL, some GL drivers might give extra performance in exchange for worse latency by buffering frames. The dxinterop backend tries to prevent this by calling SetMaximumFrameLatency(1). If I understand correctly, that means with dxinterop, both the GPU and CPU will waste time waiting for the next VSync instead of rendering. The advantage of this is that the timing for display-sync and interpolation should be more accurate.

**Comment by wm4** [comment]
Note that latency is no problem if A/V sync can know about it. I've considered doing this in a generic way with GL_ARB_timer_query, but I'm not sure if the results would be good enough. (I don't know if it can be done in a way the timer times the completion of a vsync, instead of potentially getting slightly before or after it.)

**Comment by rossy** [comment]
Interestingly enough, a quick and dirty benchmark (with ``time``) says performance isn't a problem on my machine.

For rendering 1080p video with 64 neurons:
backend=win: 5.48fps
backend=dxinterop: 5.67fps

Though I did things like disabling framedrop for testing. Maybe the behaviour is different with framedrop and display-sync on. I'm not sure how to test this.
