### ISSUE TITLE
Is it possible to fetch several videos sequentially with --merge-files option?

### ISSUE THREAD

**Issue by guopm** [mpv-player/mpv#2692]
We are embarrassed that mpv always perform parallel download. It works fine without this option.
mpv version: 0.14 release
platform: Mac OS X, Debian and Windows 10

related issue:[Is it possible to add a '--no-merge-files' option?](https://github.com/m13253/BiliDan/issues/47)

**Comment by wm4** [comment]
At some point, maybe yes. For now, it absolutely has to open all files at the start, and it has at least to read the file headers for all files. (But it would be possible to prevent downloading larger quantities of files which are not needed yet.)

Supporting this would be nice, because our ytdl wrapper uses the same underlying functionality to concat some segmented videos. But I don't see any quick solution, so there won't be one.

**Comment by wm4** [comment]
PS: I've read something about using HLS - this would work, but of course needs a mpeg-ts input. I'm not sure how much control over the input you have, so whatever.

**Comment by m13253** [comment]
> but of course needs a mpeg-ts input

Thank you for pointing out why my attempt on HLS failed. Because I've got MP4s and FLVs.

What possibility will this feature be implemented? (i.e. Shall I rely on this to be fixed or try to find another solution? Maybe I can add a layer of HTTP proxy on the frontend, to force pause the first attempt to download?)

**Comment by wm4** [comment]
Well, do you really need mpv not to open the other files? Or is it ok if it opens them, but then doesn't try to fill the cache for them?

For a more extensive solution I wouldn't wait.

**Comment by m13253** [comment]
> Or is it ok if it opens them, but then doesn't try to fill the cache for them?

It is OK to open them, but don't try to fill the cache.
I understand fetching metadata is important. But it is unnecessary to fetch more than metadata (at least until a previous segment is fully buffered).

**Comment by wm4** [comment]
Implemented the simple half-solution. I hope it works.

It's possible that a proper solution will be implemented in the far future; but if so, a simple `--merge-files` won't be enough, and an EDL with duration and start points would have to be used. (Or else there'd be no choice but to open each file explicitly to check its duration.)

**Comment by m13253** [comment]
Thank you a lot!
I will check if it solves the problem.
