### ISSUE TITLE
[Feature request][Client] Window

### ISSUE THREAD

**Issue by tokiclover** [mpv-player/mpv#2721]
I was in the course of writing a plugin for [emotion_generic_players](https://git.enlightenment.org/core/emotion_generic_players.git) for [EFL](https://enlightenment.org) and I am stuck on the way to pass the window reference to libmpv/emotion because _--wid=ID_ does not permit to do it.

Is it possible to schedule something on the curse of the rapid development of the client API?

Former user of MPlayer[2] and then MPV, I'd like to get something in a neat and simple GUI like [Rage](https://git.enlightenment.org/apps/rage.git) because I will not go to SMPlayer[2] way because of the current development of GTK. And having a simple and neat GUI to MPV on EFL wouldn't hurt at all.

The ARCH/Enlightenment community use python everywhere and even to a video GUI! I don't like the python everywhere(TM) thing because I'd rather use a KISS C code variant.

The VLC interface to pass the window and video format looks neat in a user-friendly fashion (ref. emotion_generic_players/src/vlc/emotion_generic_vlc:_player_setup().)

Thanks.

**Comment by wm4** [comment]
From what I can see, this emotion VLC backend lets VLC decode to memory surfaces, which emotion then will render. To make it even worse, it forces VLC to convert to RGB, which pretty much means it likely doesn't make use of any GPU acceleration at all (or only inefficiently).

What this backend does is not possible with libmpv. We haven't bothered to provide such an API because it's going to be inefficient (no hw acceleration path, not even GPU colorspace conversion), and likely will affect the correctness and quality of video rendering.

libmpv instead provides 2 other ways, which are pretty much described here: https://github.com/mpv-player/mpv/blob/master/DOCS/client_api_examples/README.md#methods-of-embedding-the-video-window

**Comment by lachs0r** [comment]
Not going to happen in the way emotion_generic_players requires it.
And isn’t the OSC good enough?
