### ISSUE TITLE
inconsistency in downmixing ac-3?

### ISSUE THREAD

**Issue by tomty89** [mpv-player/mpv#2724]
[ffmpeg/audio] ac3: Channel layout '5.1(side)' with 6 channels does not match specified number of channels 2: ignoring specified channel layout

So if I play some 5.1 ac-3 stream with --audio-channels=stereo (or --audio-channels=2.0), I can see the above warning.

And I can see the following filter chain with -v:
[af] Audio filter chain:
[af]   [in] 48000Hz stereo 2ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch s32
[af]   [out] 48000Hz stereo 2ch s32
[af]   [ao] 48000Hz stereo 2ch s32

So does this mean that the ac3 decoder in ffmpeg can downmix 5.1 ac3 stream to stereo? FWIW I CAN hear all six (well, or maybe only five) channels' signal from my stereo speakers in such situation.

Isn't it good to have it downmixed this way? Why is there such a warning?

However, if my output device reports a stereo channel map (or not reporting any so mpv falls back to stereo), I won't be seeing the warning. And with -v, I can see the following filter chain instead:
[af] Audio filter chain:
[af]   [in] 48000Hz 5.1(side) 6ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch s32
[af]   [out] 48000Hz stereo 2ch s32
[af]   [ao] 48000Hz stereo 2ch s32

**Comment by wm4** [comment]
I don't know why there#s this warning. FFmpeg prints it.

mpv tells the decoder to downmix if you force stereo with ``--audio-channels=2`` (or equivalent). In other cases, like when the audio device reports that it supports stereo only, the downmix is done by mpv itself. (Mainly because reinitializing the audio decoder in order to force it to downmix would be messy.) You can control the behavior with some obscure ``--ad-lavc-...`` option.

**Comment by tomty89** [comment]
Apparently it comes from here:
https://github.com/FFmpeg/FFmpeg/blob/release/2.8/libavcodec/utils.c#L1680
