### ISSUE TITLE
windows (wasapi): audio dissapears after long pause

### ISSUE THREAD

**Issue by avih** [mpv-player/mpv#2738]
Happened to me at least twice, after several hours where the clip is paused, there's no audio when un-pausing (wasapi).

Also, the mpv mixer item at the windows mixer doesn't show up at this state.

Displaying audio properties such as `${audio-format}` shows `(unavailable)`.

The audio doesn't return after skip, or after issuing the command `audio-reload` or after issuing `ao-reload`, but does return if cycling audio tracks twice using `#` (when it happened to me there was a single audio track).

@kevmitch , @lachs0r found out that audio sessions can expire after some time, so maybe it's a case where it expires and mpv is unaware of that.

From here: https://msdn.microsoft.com/en-us/library/windows/desktop/dd370796%28v=vs.85%29.aspx :
> After a session has been inactive for a period of time, the system changes the state of the session from inactive to expired. Sndvol displays volume and mute controls for all active and inactive rendering sessions. Sndvol removes the volume and mute controls for a session when the state of the session changes from inactive to expired...

**Comment by wm4** [comment]
>Displaying audio properties such as ${audio-format} shows (unavailable).

This indicates the audio output was indeed closed (maybe a reload was issued, which then failed).

**Comment by kevmitch** [comment]
Would be useful to see the output from --msg-level=ao=debug. or even the default message level should give some message about failing to reload the device.

**Comment by kevmitch** [comment]
Also what in windows version(s) is this observed?

**Comment by avih** [comment]
> Also what in windows version(s) is this observed?

Windows 8.1 64 bit, mpv 32 bit.

**Comment by kevmitch** [comment]
For the record from IRC, in at least one instance, the problem is that changing the default device triggers a reload during which GetDefaultAudioEndpoint returns E_PROP_ID_UNSUPPORTED (0x80070490) for mysterious reasons (possibly a race condition in the API).

I can't seem to reproduce this after ~15 hours in windows 7 or 10. Does it only happen when changing the device configuration?

I tried plugging in a new device and switching it to default on windows 7 after mpv had been paused this long. mpv switched to it without a problem and switched back when i unplugged it again.

Wasn't able to change the device configuration on win10 since it's a vm and virtualbox's usb passthrough is finicky with recognizing newly plugged in devices.

**Comment by kevmitch** [comment]
There is also the outstanding question of whether the audio session really does expire - i.e. whether the slider disappears from sndvol.exe before the device configuration is changed and the reinit fails.

That it disappears after the failed reinit is no surprise since there truly is no longer any audioclient attached to the session anymore.

Basically the question is whether GetDefaultAudioEndpoint failing is the whole problem or if there are problems before the device change.

**Comment by avih** [comment]
> the problem is that changing the default device triggers a reload during which GetDefaultAudioEndpoint returns E_PROP_ID_UNSUPPORTED

This is the error indeed, but I don't recall concluding that the device switch was the cause.

The full sequence where it happens is:
- clip plays and audible via device A (device B is disabled).
- pause the clip.
- enable device B and disable A (in this order)
- wait for some hours while playback is paused.
- enable device A and disable B (in this order)
- unpause --> no audio.

- skip, change volume, etc -> no audio.
- Press `#` -> audio comes back.

However, the exact same sequence with only seconds or minutes of pause -> the audio plays just fine when unpausing.

> There is also the outstanding question of whether the audio session really does expire...

So what experiment would you suggest here?

**Comment by kevmitch** [comment]
If I'm reading the timecodes on your [pastebin](http://pastebin.com/raw/eEGuB8qk) correctly, they suggests that device A is disabled *after* waiting some hours, not before. OnDeviceStateChanged is triggered at 5012.924 seconds when you unplug or disable the currently used device. It is the failure of this reinit to find the default device (E_PROP_ID_UNSUPPORTED) that breaks everything in this particular instance.

I am also confused, because this failure mode is inconsistent with the statement that unpausing immediately after changing devices results in playing audio. Since PROP_ID_UNSUPPORTED failure happens immediately, audio should break immediately. 

Furthermore, I can confirm that if I disable all my playback devices, then GetDefaultDevice will indeed return PROP_ID_UNSUPPORTED. This leads me to wonder whether the problem demonstrated in the above pastebin is distinct from the long time out problem.

It would be interesting if it was confirmed that there is a problem in the absence of any device switching. 

> >    There is also the outstanding question of whether the audio session really does expire...

> So what experiment would you suggest here?

At what stage exactly does mpv's slider in sndvol.exe dissapear?

**Comment by kevmitch** [comment]
#2747 will give a better error message than PROP_ID_UNSUPPORTED if no devices are available. It would be interesting if you can still trigger PROP_ID_UNSUPPORTED with those commits.

**Comment by avih** [comment]
> If I'm reading the timecodes on your pastebin correctly, they suggests that device A is disabled after waiting some hours, not before.

There were 4 device changes overall: two (enable B, disable A) right after pausing, and then several hours later, still while paused, two more (enable A, disable B).

> I am also confused, because this failure mode is inconsistent with the statement that unpausing immediately after changing devices results in playing audio

I did not state this. unpausing immediately after changing device (the latter two above) after several hours it was paused results in _no_ audio.

Also, I reproduced the issue today with a shorter sequence:
- clip plays and audible via device A (device B is disabled).
- pause the clip.
- enable device B and disable A (in this order)
- wait for some hours while playback is paused.

--> icon has disappeared from the windows mixer
--> unpausing results in no sound.

#2747 will give a better error message than PROP_ID_UNSUPPORTED if no devices are available. It would be interesting if you can still trigger PROP_ID_UNSUPPORTED with those commits.

Travis does not seem to approve this commit...

**Comment by avih** [comment]
We analyzed it further, turns out this happens when the only enabled audio device is HDMI, and then windows turns the display off after some idle time -> there's no available audio device at the system, and mpv decides to drop AO and doesn't try to reinstate it later (e.g. after the display -> + audio come back).

One possible solution is that whenever any wasapi "event" happens at the system, try to fully re-init the audio.

**Comment by kevmitch** [comment]
> One possible solution is that whenever any wasapi "event" happens at the system, try to fully re-init the audio.

There are no wasapi events once it has failed to init any audio device and falls back to ao=null or "No Audio"  wasapi is totally uninted at this point.

**Comment by wm4** [comment]
Except the thing that watches for audio device list changes.

**Comment by avih** [comment]
For the record, the simplest STR:
1. make sure the system has only one enabled audio device.
2. play a clip.
3. disabled the audio device
4. re-enable the audio device

-> no audio.

(in this exact scenario both MPC and VLC with default audio config do resume the audio, but not mpv)

**Comment by kevmitch** [comment]
> Except the thing that watches for audio device list changes.

yes, ao_hotplug. could/should we initiate an ao_reload from there?

**Comment by wm4** [comment]
No, but a lua script could do it.

**Comment by avih** [comment]
> No, but a lua script could do it.

ao-reload doesn't work after the AO was already dropped...

**Comment by avih** [comment]
So, when using `--audio-fallback-to-null=yes`:
- reading the property `options/ao` always returns `wasapi` regardless if currently it fallbacks to null.
- reading the property `audio-device` always returns `auto` also regardless of the state.
- Reading the native property `audio-device-list` always has two objects: `auto` and `wasapi`. The `auto` object never changes, but the wasapi one does change its name and description slightly, e.g. when there is an audio device: `{ "name": "wasapi/{740ad544-9151-4e43-af61-cdb3fa4c50c1}",  "description": "Speakers / Headphones (Realtek High Definition Audio)" }`, and when there isn't an audio device: `{"name": "wasapi", "description": "Default" }`, but IMO this would be too fragile for a script to count on this kind of change.

What would be the best way for a script to test/observe that the audio has changed to `null`? (while using `--audio-fallback-to-null=yes` in order for `ao-reload` to work)

**Comment by kevmitch** [comment]
observing ```audio-device-list``` is exactly the intended method. That's what wm4 was saying plex does.

**Comment by avih** [comment]
> when there is an audio device: { "name": "wasapi/{740ad544-9151-4e43-af61-cdb3fa4c50c1}", "description": "Speakers / Headphones (Realtek High Definition Audio)" }, and when there isn't an audio device: {"name": "wasapi", "description": "Default" }, but IMO this would be too fragile for a script to count on this kind of change.

Should a script really rely on _that_ kind of change to deduce that a device disappeared/appeared??

**Comment by avih** [comment]
Anyway, this kind of script seems to work as expected:

```lua
-- observe-audio.lua
mp.set_property("options/audio-fallback-to-null", "yes")
mp.observe_property("audio-device-list", "native", function()
  mp.msg.warn ("reloading AO")
  mp.commandv("ao-reload")
end)

```

**Comment by kevmitch** [comment]
so should we put this in TOOLS/lua? should probably add the checking for ao=null to make it a little less trigger happy.

**Comment by avih** [comment]
It's been working for me since, but I also added an exception to execute it only `if (mp.get_property("current-ao") ~= "null")` since otherwise there's no need to reload it. Also, maybe change the message to something more informative.
