### ISSUE TITLE
Smplayer + MPV subtitle size issue

### ISSUE THREAD

**Issue by psychok7** [mpv-player/mpv#2746]
I started using `Smplayer 16.1.10 + MPV (git-9a2a0b0)`
on Ubuntu 14.04 LTS and i realized that i cannot set my subtitle font size by default.

I go to preferences and subtitle and i set it to different sizes but the size never changes in reality. Only if i manually choose `Size+` or `Size-` it will change for the current movie/session i am using.

This was working well before when i used Mplayer and the default Smplayer version that comes with Ubuntu.

Any ideas?

**Comment by lachs0r** [comment]
Either it’s a subtitle format that uses bitmaps (therefore the options do not work; examples include DVD, Blu-ray/PGS and DVB subtitles) or SMPlayer does this incorrectly.

In general, we do not recommend SMPlayer because it does not use the correct interface for mpv (which would be libmpv) and instead has hacks in place to treat mpv as if it were MPlayer (from which it is very different). If you can’t live without a frontend (you should try, it’s actually not that bad), maybe give Baka MPlayer a try.
