### ISSUE TITLE
"af=drc" causes sudden jumps in audio volume

### ISSUE THREAD

**Issue by mpvOWNZ** [mpv-player/mpv#2759]
I just recently discovered the benefits drc brings for my stereo speakers.
It is way better at making the voices audible than 'ad-lavc-ac3drc=1' (which hardly makes any difference).
However, it also leads to noticeable jumps in audio volume, especially in the beginning of many films.
I already tried the second method drc offers (multiple samples instead of only one), but this actually made the jumps even worse and way more noticeable!
Is there something that can be done about this problem, or is this just the way drc works and I have to learn to live with it?

**Comment by paulguy** [comment]
The built in drc filter isn't great and is basically unadjustable.  I've been using lavfi compand which is more adjustable.

This is what I use in my mpv config in a preset.  It's mostly intended for night time TV watching.  I've noticed it's not very good at keeping the file-to-file volume consistent though, since you can't define specifically a target volume, or rather, you can specify an "initial volume" but that doesn't seem to make any real difference for me.  Might just help to avoid that immediate boom you can occasionally get at the start of a particularly loud file.
`af-pre=lavfi="compand=attacks=1.5:decays=0.2:gain=-18"`

**Comment by sda89ha9** [comment]
you could try dynaudnorm
af=lavfi=[dynaudnorm=f=100:m=5]

https://ffmpeg.org/ffmpeg-filters.html#dynaudnorm

**Comment by wm4** [comment]
Yeah, these are the choices you have. The `drc` filter itself doesn't do any lookahead, so it will always have this "jumping".

**Comment by avih** [comment]
> you could try af=lavfi=dynaudnorm
> I use [dynaudnorm=f=100:p=0.6]

Just make sure you don't use that with softvol in mpv or else currently they conflict. This might be true for the other suggestion as well (didn't test).

This patch allows it to work with softvol though, if you build mpv yourself: https://github.com/avih/mpv/commit/304bfd42
