### ISSUE TITLE
Integrate SSimDownscaler

### ISSUE THREAD

**Issue by lanzorg** [mpv-player/mpv#2772]
Here is the hlsl source from MPDN:
https://github.com/zachsaw/MPDN_Extensions/tree/master/Extensions/RenderScripts/SSimDownscaler

Here is a demo:
http://screenshotcomparison.com/comparison/158879

**Comment by kevmitch** [comment]
This is another gpl3 scaler. Although, there is now an ```--enable-gpl3``` configure flag, I'm not sure what the policy is on coming up with new uses for it.

Is there a more abstract specification somewhere?

**Comment by wm4** [comment]
Yeah, linking gpl3 code actually reduces the chance of this being integrated heavily.

> Although, there is now an --enable-gpl3 configure flag, I'm not sure what the policy is on coming up with new uses for it.

I'm waiting for @bjin to relicense it, then the flag will be removed.

**Comment by fhlfibh** [comment]
@kevmitch 
>This is another gpl3 scaler.
Could you please explain what is the matter with GPLv3 in mpv?

**Comment by lachs0r** [comment]
The default downscaler (mitchell) was chosen to avoid aliasing, but it might 
look a little blurry.

@lanzorg: Try something like
vo=opengl-hq:dscale=spline36:dscale-antiring=0.75

That should have much better sharpness than the default, but potentially 
introduces more aliasing. Experiment with other scalers and their options;
mpv has got a lot of them.

I don’t really like the idea of copypasting every single shader into mpv just 
because some other player’s community is hyping it. Let’s first see if mpv can 
achieve the desired result by other means.

**Comment by lamarpavel** [comment]
@fhlfibh take a look at: https://github.com/mpv-player/mpv/issues/2033

**Comment by wm4** [comment]
Makes me wonder if we could support external mpdn shaders; unfortunately they're not declarative, but written in C#.

**Comment by avih** [comment]
There's already lua support... add c# too ;)

**Comment by lachs0r** [comment]
Use shader hooks.
