### ISSUE TITLE
Question about 4K to FHD downscaling

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#2773]
Hi!

The question is not related to mpv directly, but still...

There're "rumours" on the internet about downscaling 4K YUV 420 to FHD YUV 444. E.g. here http://www.personal-view.com/talks/discussion/10637/4k-downscaling-progress-topic/p2 a user offered an ffmpeg filter, which (as I see it) upscales 4K's U and V planes to 4K-size, then merges them with 4K's original Y plane, and then downscales the result to FHD thus getting 444 YUV, i.e. of better quality than "standard" FHD.

I'd like to ask mpv people whether that whole idea has any reason behind it at all, and if mpv can perform similar downscaling "on the fly".

Regards,
Alex

**Comment by lachs0r** [comment]
That’s pretty much what mpv does with the opengl video output. You can configure the scaler that is used for the chroma planes with the cscale sub-option. For opengl-hq, this is spline36 by default.

**Comment by haasn** [comment]
As for whether or not it has “better quality” or not depends mostly on the encoding quality of either source than it does on the resolution itself.

If you're dealing with, say, 50 Mbps 4K versus 5 Mbps 1080p (and otherwise identical encoder settings) then the 4K version downscaled to 1080p is going to handily beat the 1080p version.

But if you're dealing with, say, 10 Mbps 4K versus 10 Mbps 1080p then the latter will almost always be better (even upscaled) then the former.

Suggestion: Open both in ``mpv -vo opengl-hq --fullscreen``, take a screenshot of each and blind ABX test them. See which one you prefer.

**Comment by fhlfibh** [comment]
Thanks!

@lachs0r 
Is it correct that `cscale` upscaling of chroma planes with OpenGL vo works only if there's no h/w decoding (i.e. with VDPAU)?

**Comment by wm4** [comment]
Works with vaapi (not the GLX method) and dxva, doesn't work with vdpau (unless you use vf_vdpaurb).

**Comment by fhlfibh** [comment]
@wm4 
My Nvidia GTX 660 and linux seems not working with vaapi or dxva...
So, VDPAU h/w decodes compressed video, then vdpaurb filter reads resulting YCbCr 420 frame back to main memory, where the frame can be processed with `cscale` option, right?

**Comment by Hrxn** [comment]
> My Nvidia GTX 660 and linux seems not working with vaapi or dxva

I would be concerned if you would get dxva to work under Linux, since this is Windows-only.
`DirectX Video Acceleration (DXVA) `

**Comment by wm4** [comment]
Yes, don't use vaapi with nvidia either.

**Comment by Hrxn** [comment]
So, you are basically screwed as a Linux user with nvidia GPU?

**Comment by haasn** [comment]
Not really. Hardware decoding is a gimmick that only works on content that's super easy to decode on your CPU either way.

**Comment by wm4** [comment]
We also could directly map vdpau textures, but it's annoying (progressive frames are mapped as fields, thanks nvidia).

**Comment by Hrxn** [comment]
> Hardware decoding is a gimmick that only works on content that's super easy to decode 
You could get a different impression from reading the majority of Video/AV/DVD forums on the web.
On the other hand, most stuff there is myths and legends anyway..

**Comment by fhlfibh** [comment]
So, for Linux users with any GPU there're only 2 options to get `cscale` working properly and without multiply RGB-YUV conversions: `opengl` VO either with completely software decoding or with `vaapi-copy` on Intel's IGP?

From my experience, software decoding might be rather CPU consuming, especially with complex tasks like downscaling 4K HEVC to FHD with quality processing...

**Comment by wm4** [comment]
``vaapi`` also works, as long as the GLX method is not selected.

>From my experience, software decoding might be rather CPU consuming, especially with complex tasks like downscaling 4K HEVC to FHD with quality processing...

Scaling is done on the GPU, though. (Unless you explicitly set up ``--vf=scale=....``.)

**Comment by fhlfibh** [comment]
@wm4 
GLX method that is `--vo=opengl:backend=x11`?

**Comment by wm4** [comment]
Yes.

**Comment by fhlfibh** [comment]
Thanks!
I tried "VDPAU backend to VAAPI". With my GTX 660 it seems to work (at least, technically, i.e. I can see a picture). E3-1230v2 CPU load (26.2Mbps average, no scaling et al.) with h/w vaapi or vdpau is way under 10%, with s/w decoding -- over 30%. Hope, `cscale` also works as expected.

**Comment by wm4** [comment]
I made a change to git master that logs the actually used interop backend with -v.

**Comment by fhlfibh** [comment]
Thanks!

**Comment by haasn** [comment]
To be perfectly clear, *decoding* here only means decompressing the HEVC (or H.264 etc.) stream.

The decompressed source data is, with -vo opengl, still uploaded to the GPU and all further processing is done there (via OpenGL - hence the name).

How much CPU time this decompression needs basically only depends on the source bitrate and the compression algorithm used (H.264 and VP8/VP9 are all very well-optimized in ffmpeg. Last I checked, HEVC was still a bit sluggish but only because the code was barely optimized).

Hardware decoding in this context means that the compressed video is uploaded to the GPU and the decompression is performed there, using a special hardware module. Saves some upload bandwidth and CPU time, but the drawback, apart from the APIs being terrible, is that these hardware modules are only compatible with a small subset of algorithms - the ones they're explicitly designed to support (which is also why none of them can decode, say, 10-bit H.264 aka Hi10P).

**Comment by fhlfibh** [comment]
@haasn 
So, as I understand, GPU h/w  decoding (i.e. vdpau, vaapi, hevc) has less CPU usage, but also has some limitations that actually hurt "quality playback"? For "better playback" with s/w decoding Is it better to have a more capable GPU (maybe Quadro or FireGL?) for OpenGL processing?

**Comment by Hrxn** [comment]
Yes, the main benefit of hw decoding (in general, not just for Linux et al.) is saving some CPU cycles, that can then be used otherwise - in theory. On top of that, since the video stream is sent to the GPU in its compressed format, you save some bandwidth on the GPU interface, although I've never heard that the transfer capacity of the PCIe bus is the limiting factor, ever.

But it does neither increase nor decrease the quality. And, as haasn explained, it only works with some specific encoding formats.

A powerful GPU can help with improving the quality, because it makes the use of fancy and demanding stuff like [upscaling with nnedi3](https://mpv.io/manual/master/#video-output-drivers-nnedi3) possible.

If quality benefits from using the 'pro' GPUs (Quadro, Fire) instead of of their 'normal' counterparts (GeForce, Radeon), I really don't know. The GPUs are basically the same, they should not really differ in terms of raw processing power, the advantage of the professional cards is supposed to be the better drivers. But I can't speak from own experience here..

**Comment by kevmitch** [comment]
> But it does neither increase nor decrease the quality. And, as haasn explained, it only works with some specific encoding formats.

As wm4 said, with vdpau and the old vaapi glx, you loose control of the chroma upscaling, which can reduce quality. Otherwise, for the new vaapi egl, vaapi-copy, vf_vdpaurb, and dxva copy, the decoded results *should* be identical.

The main benefit of hwdec is that is uses less power.

**Comment by wm4** [comment]
The vaapi glx API is actually even worse: it doesn't give any control over RGB conversion.
