### ISSUE TITLE
Client API: error setting mute property

### ISSUE THREAD

**Issue by dw-vsn** [mpv-player/mpv#2780]
When I receive a MPV_EVENT_FILE_LOADED, I try to set the mute property like this:

    int flag;
    flag = 1;
    ret = mpv_set_property(m_internal->m_ctx, "mute", MPV_FORMAT_FLAG, &flag);

But I get back an error "error accessing property". MPV continues on to play the audio, so the media does have a valid audio track and the audio has not been disabled via another means.

Any thoughts why the `mpv_set_property` call fails?

Also, how does on match the property (such as mute) with the proper `MPV_FORMAT_XX` values? The best I can come up with is reading the code, which can be a bit tedious. Is there a table anywhere or perhaps some client code example that already has then all figured out?

**Comment by wm4** [comment]
>But I get back an error "error accessing property". MPV continues on to play the audio, so the media does have a valid audio track and the audio has not been disabled via another means.

At this time audio is not necessarily initialized. In the current release, trying to change the mute or volume properties will fail if audio isn't initialized.

The next release (current git master) relaxes this a bit, and allows you to set mute/volume even if audio is not initialized, but then has an effect only if `softvol=yes` or `softvol=auto`. It also adds a property named `mixer-active`, which lets you know if the volume control is fully initialized. There is no good solution if you want to force the system mixer (because the system mixer can change asynchronously, and mpv system mixer volume control also requires audio output initialized).

For versions before that, you might be able to use the `current-ao` property instead of `mixer-active`.

>Also, how does on match the property (such as mute) with the proper MPV_FORMAT_XX values? The best I can come up with is reading the code, which can be a bit tedious. Is there a table anywhere or perhaps some client code example that already has then all figured out?

That's a good question. Setting it as string will almost always work, except in special cases. Other than that, you can typically write the property using the same format as `mpv_node.format` has if the property is read as `MPV_FORMAT_NODE`. Maybe extensive documentation of which types a property supports should be added.

**Comment by dw-vsn** [comment]
Thank you for quick response. An event to indicate if/when the audio is initialized would be nice, but I don't know how practical that would be. For the time being, I will go straight to ALSA.

I realize docs for the format types is time consuming and tedious, but it sure would make things easier to use from a client perspective. That being said, MPV is the best video/audio library I have used, thanks for the excellent work.
