### ISSUE TITLE
(fullscreen) “intelligent” behavior when launched by double click

### ISSUE THREAD

**Issue by UliZappe** [mpv-player/mpv#2809]
I see that in recent (?) **mpv** builds for OS X, double-clicking **mpv.app** launches **mpv**, opens the **mpv** main window and asks the user to drag’n’drop a movie file there.

That’s a great usability addition _except_ when you’ve added `fullscreen` to your config file, in which case **mpv** will directly go into fullscreen mode and there’s no way to drag’n’drop a movie file.

Would it be possible to disregard the `fullscreen` option only for the case that **mpv** is launched by double-click, cache this option, and go into fullscreen mode automatically once the user has dropped a movie file on the **mpv** window? That would be a nice usability enhancement.

In the same vein, what do you think of an option that prevents **mpv** from quitting automatically in the very second the movie ends (instead of just staying black)? It can be quite disruptive to immediately see the prosaic Mac desktop after an absorbing movie …

**Comment by ChrisK2** [comment]
> prevents mpv from quitting automatically

see ``--keep-open`` or ``--idle`` options

**Comment by rossy** [comment]
```
[pseudo-gui]
keep-open
```
is always the first thing I put in a new config. It seems like a reasonable default, since it's what users would expect from a GUI.

**Comment by wm4** [comment]
> It seems like a reasonable default, 

One that was once set, but removed because there were too many complaints.

**Comment by UliZappe** [comment]
>see ```--keep-open``` or ```--idle options```

Ooops, sorry! I have no idea why I overlooked these …

**Comment by UliZappe** [comment]
> ```--idle options```

BTW, is there an option (that I’m again too blind to see) to disable the “Drop files to play here.” message in this case (so that just a black screen remains at the end)?

**Comment by ChrisK2** [comment]
> is there an option [..] to disable the “Drop files to play here.” message in this case (so that just a black screen remains at the end)?

No.

**Comment by wm4** [comment]
The OSC is drawing this, so you could disable the OSC completely. But then it wouldn't show up during playback either.

**Comment by Frechdachs** [comment]
If you use ``keep-open`` instead of ``idle``, mpv will keep displaying the last frame, which happens to be a black frame for most movies.

**Comment by UliZappe** [comment]
>If you use keep-open instead of idle, mpv will keep displaying the last frame, which happens to be a black frame for most movies.

Yep, thanks, I’m aware of that. Some of my movies are an exception from that rule, which is why I asked, but it’s not a big deal, really.

**Comment by UliZappe** [comment]
@wm4

Exactly why is this closed now?

My original issue/feature request wasn’t even discussed (only my appended remark in the last paragraph which maybe I better would have omittted).

I’m not saying it’s a very important feature, but I’m surprised it’s closed without any comment.

**Comment by wm4** [comment]
I think all questions have been answered?

**Comment by UliZappe** [comment]
Nope, the main request was not discussed at all:

>Would it be possible to disregard the ```fullscreen``` option only for the case that **mpv** is launched by double-click, cache this option, and go into fullscreen mode automatically once the user has dropped a movie file on the **mpv** window? That would be a nice usability enhancement.

**Comment by Frechdachs** [comment]
You could omit the ``fullscreen`` option and write a lua script instead, that makes mpv switch to fullscreen whenever there is a ``start-file`` event. Don't know if this fulfills all your needs.

**Comment by UliZappe** [comment]
>You could omit the fullscreen option and write a lua script instead, that makes mpv switch to fullscreen whenever there is a start-file event. Don't know if this fulfills all your needs.

I’m sure it can be done, but my suggestion was to make this the default behavior for the precompiled OS X version. **:–)** My point is that at least Mac users expect applications to “just work”, and it simply makes no sense to open an application fullscreen and then display the message “Drag something here”.

It’s not so much a feature for me but rather a suggestion how to make **mpv** more popular on the Mac platform.

**Comment by Cpuroast** [comment]
On OSX, set your file type associations correctly with mpv, then you never have to launch mpv on it's own and drag/drop a file.
You simply double click on a video file and it automatically starts playback, and in your case, in full screen mode.

Or if you don't have fullscreen=yes in your config file, how hard is it to just hit: f.

**Comment by UliZappe** [comment]
I don’t say it’s hard. I say it feels non-sensical, and this is something that makes applications easily unpopular on OS X.

I really don’t feel like defending this feature request. It’s not that important. It’s one of these tiny little details that make an application feel appealing. If you don’t agree, forget it. I thought it would be a good idea.

**Comment by Cpuroast** [comment]
I'm just saying, if you use a GUI the way it was meant to be used, as in the file opens the application associated with it, and not the reverse as in opening the application and then open the file.
It makes the discussion moot.

Do you open word first to open a word document, or do you simply double click on the word document to open word.

**Comment by UliZappe** [comment]
>I'm just saying, if you use a GUI the way it was meant to be used, as in the file opens the application associated with it, and not the reverse as in opening the application and then open the file.

Yep. _If_. But if not – and it’s not that unusual to open an application by a double-click, especially on OS X, where the application typically opens with all open documents from the last session – you’ll find yourself in a paradoxical situation – a fullscreen app saying _Drop something here_.

IMHO, you think too much from a techie POV: Yes, it can be avoided. I think from the opposite POV: Yes, it _could_ happen, if only by chance. And that’s bad enough. Because I know many OS X users who will experience this once, by chance, and never touch this application again because of that paradoxical experience. Their bad, you might think, and if you do, I cannot argue against it. My request was to handle this differently.

But this whole thing is running out of proportion, so this will _really_ be my last post to defend my tiny suggestion.

**Comment by haasn** [comment]
When in doubt, go for the simpler behavior instead of trying to be “smart”.

**Comment by dn3s** [comment]
If an OSX user can edit their MPV config file, they are probably a Power User and will understand right away what went wrong, so it's probably not a deal breaker. However, the fact remains that when using the app with a non-obscure config, it displays obviously broken behavior, and the user will be disappointed.

IMO, the simplest solution would be: instead of disregarding the fullscreen option when launched by double-click, simply treat the video playback and the drag-and-drop interface separately. Have the drag-and-drop interface NEVER be fullscreen, and apply fullscreen to any loaded file according to config. So if the user explicitly sets fullscreen in their config, they get a windowed drag-and-drop, drop their file in, and it starts playing back fullscreen. When the file's done playing, it exits fullscreen.

This would deal with any concerns about unintuitive "smart" solutions overriding explicitly set user configs and complicating behavior. While this is arguably more complicated from a programming perspective, it appears to be simplest behavior from the UX perspective.

**Comment by haasn** [comment]
> If an OSX user can edit their MPV config file, they are probably a Power User and will understand right away what went wrong,

I'm not exactly sure what's supposed to be wrong to begin with. You get a window displaying “drag things here”, you drag things there, it works. What am I missing?

**Comment by UliZappe** [comment]
>What am I missing?

That it also says “drag things here” in _fullscreen_ mode, where you do not get a window at the beginning and therefore cannot do this, so it’s a nonsensical invitation.

**Comment by dn3s** [comment]
it is impossible to drag things onto a fullscreen window because any windows one could drag things from are obscured. In OSX a fullscreen window basically gets its own desktop and all other windows are left behind (except for in multi-monitor setups I suppose)

**Comment by haasn** [comment]
> That it also says “drag things here” in fullscreen mode, where you do not get a window at the beginning and therefore cannot do this, so it’s a nonsensical invitation.

Do OS X users get confused by a window being behind another window too, and having to move it by dragging on the title bar?

As far as I can tell, it's both easy and intuitive to either

1. alt tab to a file browser and drag stuff from the file browser to the mpv window
2. double click the mpv window to leave fullscreen mode, drag a file there, double click again to re-enter fullscreen mode

**Comment by UliZappe** [comment]
>Do OS X users get confused by a window being behind another window too, and having to move it by dragging on the title bar?

Fullscreen mode works differently in OS X. It’s not implemented as a full-size window, so you there is no title bar, you cannot drag it, and you cannot access the **Finder** (file browser) while being in fullscreen mode. You’re completely cut off everything else until you exit fullscreen mode.

**Comment by haasn** [comment]
Oh, so it's like fullscreen games on Windows? I can see how this complaint makes sense, then.

Since `fullscreen` is not the default I imagine this is not much of a problem for most users. When you think about it from another perspective, you don't really want the `fullscreen` option, at least not in your default config - since you *want* mpv to start in windowed mode.

It sounds like what you want instead is an option to say “automatically enter fullscreen mode after dragging a file onto the mpv window”, for which the cleanest interface would probably be a custom lua script that responds to the event in question.

I don't think it's worth optimizing for the small number of people who
1. Are proficient enough to manually write `fullscreen` into their configs
2. Are annoyed by this quirk in the result of that
3. Are not able to install a lua script to do it instead
4. Are unwilling to deal with simply having to double click after dragging their files instead

**Comment by UliZappe** [comment]
If you often launch **mpv** by double-clicking a video of a type for which you made **mpv** the default application, then ```fullscreen``` is really a nice option.

However, then it gets annoying if sometimes you also launch **mpv** itself via double-click.

Basically I’m simply saying that an application that cares about its users should under no circumstances get into some kind of _Keyboard not connected. Press F1 to continue._ mode, however easy to prevent or escape.

I’m not against a lua script as a solution for this problem. My only request would be to include this lua script in the precompiled OS X package by default.

**Comment by ChrisK2** [comment]
Feel free to add the script our [Wiki](https://github.com/mpv-player/mpv/wiki/User-Scripts). We will not include any taste-specific scripts on specific platforms by default.

**Comment by UliZappe** [comment]
>We will not include any taste-specific scripts on specific platforms by default.

It is _taste-specific_ to prevent an application from getting into an inconsistent state?!?

I give up …

**Comment by haasn** [comment]
Having the `fullscreen` option sometimes work and sometimes not is inconsistent, too.

**Comment by UliZappe** [comment]
>Having the ```fullscreen``` option sometimes work and sometimes not is inconsistent, too.

Not at all.

_Fullscreen_ means _Play movies (always, consistently) fullscreen_.

It does _not_ mean _Display the Drag Target GUI (to open movies) fullscreen_ – which would obviously be contradictory in itself.

The confusion stems from the very rudimentary GUI of **mpv** which makes it seem as if the drag target and the movie screen would be one and the same thing. But semantically they are not, of course.

This is completely familiar to Mac users: **iTunes** plays movies fullscreen, but switches to a window GUI before and after the movie.

**Comment by kevmitch** [comment]
I hate to add fuel to the fire here, but the problem described is one of the reasons that ```fullscreen``` is not the default. I'm sure it is possible to get mpv into all sorts of even even more insane states using the right combination of options. That's the price of allowing the user to customize however they want. The flip side is that the customization is sufficiently powerful as to allow you to mitigate negative behavior to whatever your taste (i.e., write a simple lua script), which you take responsibility for by modifying the defaults.

> The confusion stems from the very rudimentary GUI of mpv

Yes, this is exactly it. mpv has a rudimentary GUI - one window multiple functions. This is by design. More complex behavior can be achieved using libmpv or lua scripting where achieving whatever behaviour is desired is made easier by keeping the individual options simple and atomic so that it is not necessary to out-think mpv trying to be smart. The way it works now is simple and expected (if the ```fullscreen```option is set, the window will cover the full screen).

**Comment by dn3s** [comment]
> I'm sure it is possible to get mpv into all sorts of even even more insane states using the right combination of options. That's the price of allowing the user to customize however they want.

This makes perfect sense. My only concern is that this is not an obscure configuration, but one that many users are likely to apply.

Perhaps a middle ground solution would be to add a third value for `fullscreen`: `yes`, `no`, and `auto`. This way there is no "smart" behavior unless one explicitly wants it. `auto` would be self explanatory; it would be an attractive option to peopole writing basic configs, while people writing scripts etc would naturally opt for the more explicit `yes` or `no`.

Another option would be, instead of `yes|no|auto`, one could follow in the footsteps of `ls` (the man page lists the option `--color=[WHEN]`). So fullscreen options would be `always|auto|never`, with the possibility of adding more options like `video-only` etc, although that would be less semantically clean from the scripting side.

I should clarify, I use ArchLinux with Ratpoison, where the concept of launching by double-click, or even fullscreen for that matter basically don't exist lol. It's just that as a former OSX user myself I feel for poor @UliZappe

**Comment by Hrxn** [comment]
I agree with the notion suggested about another fullscreen option.

Important point: Don't change the existing `--fullscreen` flag, it works as it should and is the expected behaviour.

Add a new option --fullscreen-smart, or -alt or whatever. Because from a usability standpoint, this really makes sense. Only have fullscreen while you actually get an output, i.e. something is currently playing, and don't show fullscreen otherwise. 

I don't use OS X regularly, but that was something that is directly obvious to me. And as stated here before, this is how iTunes behaves, for example.

I have no idea if or how you can make a program aware of how it has been started under OS X, but I know that this is actually not that trivial as it seems, in some circumstances. I can remember that I had to deal with something similar a couple of years ago, not with OS X, though.

I don't know the internal control flow of mpv, but I think that all is necessary is differentiating between mpv running with and without the '[file|URL|PLAYLIST|-]' arg provided. And I think that mpv does that already. So you only need those states, and if a file is given, then apply fullscreen mode.

**Comment by UliZappe** [comment]
@wm4

Why is this labelled _question_? It’s a feature request/bug report (as far as inconsistencies are bugs).

**Comment by Akemi** [comment]
can i get a summary of what is being requested here, the reasons why current behaviour is no good, what use case it should fix and the arguments that speak for changing it? pls

**Comment by UliZappe** [comment]
@Akemi

The request is relevant only for Mac users who want fullscreen viewing as their default and therefore have set the `fullscreen` option in the config file.

If this is the case and you launch **mpv** by dragging a movie file onto its icon, everything works as expected: **mpv** launches and the movie begins to play fullscreen.

If, however, you launch **mpv** by double-clicking on it in the **Finder** (intending to specify the movie you want to see in a second step), you’ll end up in a non-sensical state: **mpv** launches into fullscreen mode and then tells you to drop a movie file onto it which you cannot do in fullscreen mode. Since there isn’t a _File → Open …_ menu in **mpv** either, you _must_ end fullscreen mode to proceed. So the _consistent_ behavior would be for **mpv** to not launch into fullscreen mode in the first place in this case, i.e. when it is launched via a doube-click in the **Finder**(or any other method such as from Spotlight, for that matter, which implies that no movie is specified at launch time).

Not a big deal, but an annoying inconsistency.

**Comment by ChrisK2** [comment]
> you’ll end up in a non-sensical state: mpv launches into fullscreen mode and then tells you to drop a movie file onto it which you cannot do in fullscreen mode.

... but only if you have only one display.

**Comment by Akemi** [comment]
first of all i asked since i wasn't sure i understood everything correctly and if i should do something about this issue. i've got what you want, what your use case is and acknowledge that there is a case where this can be useful. though i am not quite sure why this is only relevant for mac users? i can see that happen on other platforms too.

i personally won't do anything about this issue, sry. i think it would be the best to just have a script for this that shouldn't be included by default. my reasoning for this:

first of all i disregarded the arguments that are purely subjective, that leaves us with two left overs. "you cannot drop files in fullscreen mode" and "you must end fullscreen mode to proceed". i partially disagree with them since they are plainly untrue. it's possible to drop files from Dock without exiting. it's possible to drop files from a side by side fullscreen, admittedly you can't start mpv like that and the native fullscreen wasn't a thing when this issue was opened. you also can switch the space and drag a file from there, admittedly you need to 'leave' the mpv window. in a multi-monitor setup your arguments completely don't apply.

**Comment by UliZappe** [comment]
@Akemi

> i've got what you want, what your use case is and acknowledge that there is a case where this can be useful.

I’d rather call it _not confusing_ than _useful_ because I think this is the important point. I’ve seen less experienced Mac users being completely stuck at this point, not knowing what to do. If you feel **mpv** is _geeks only_, anyway, then this might not matter much. For other users, it will.

> though i am not quite sure why this is only relevant for mac users?

Knowing only macOS, I cannot judge the issue on the other platforms, that’s all.

> first of all i disregarded the arguments that are purely subjective, that leaves us with two left overs.

I’m wondering what these “purely subjective” arguments are, because I basically never said more than what you call the “two left overs”?

> i partially disagree with them since they are plainly untrue. it's possible to drop files from Dock without exiting.

No, it’s not. You would just remove the movie file from the dock, without specifying it to **mpv**.

Besides, who has all her/his movie files in the Dock?

> it's possible to drop files from a side by side fullscreen, admittedly you can't start mpv like that and the native fullscreen wasn't a thing when this issue was opened. you also can switch the space and drag a file from there, admittedly you need to 'leave' the mpv window. in a multi-monitor setup your arguments completely don't apply.

Without exception, these are “advanced” scenarios. Users who are aware of side-by-side fullscreen or Spaces or even have a second monitor are definitely advanced users who won’t be stuck, anyway.

It’s the “normal” users who are lost, and most probably none of your scenarios applies to them.

What I don’t understand is: What is the detriment of my request for the advanced user? What does he lose if **mpv** stays in a window until a movie file is actually dropped on it, and then goes fullscreen automatically?

I cannot see _any_ loss of comfort for advanced users, while it’s definitely a win for less experienced users. So why not do it?

> i think it would be the best to just have a script for this that shouldn't be included by default.

This comment baffles me the most: This is a feature that foremost addresses the needs of people who have no idea what a script is and will mostly stick with the default behavior, and you say it shouldn’t be the default and should be a script. :open_mouth:

It’s almost funny that a request for such a simple feature which obviously improves GUI consistency without any disadvantage (that I am aware of) makes for such a lengthy thread …

**Comment by Akemi** [comment]
i am not really here to discuss this any further since everything that needed saying was already said, anything else is just repeating the same things again. since i am the most likely person atm to add new features to the macOS side of mpv i thought it was common courtesy to ask what this is about and my reasoning for not spending any time on this, instead of a plain 'No'. though since you asked some question i am going to answer them. hoping for this not to end in the pointlessness of arguing.

imho purely subjective arguments are: "you’ll end up in a non-sensical state" or "an annoying inconsistency". if you didn't mean for those to be arguments for your case, just leave them out.

yes it is possible to drag files from the Dock if you have a folder on it. yes i have a folder there with files files i want to watch.

no point in arguing if the cases i named are for 'advanced' user or whatever. my point is, when i asked you claimed it's not possible, whereas i am saying it's possible. 

i dunno why you even argue. like i said i acknowledge the use case and see your point(s), i just don't want to spend my time on it.

i will not comment on the rest since i can see how this will end.

if you haven't seen it before, [iina](https://lhc70000.github.io/iina/) a libmpv based player for macOS. there target group is the 'normal user' and they are more likely to add such features.

**Comment by dn3s** [comment]
> i am not really here to discuss this any further since everything that needed saying was already said...

that's usually not something one can claim by themselves. anyways, to address an earlier point, I don't understand dismissing "subjective" arguments. this is a UX problem. UX is subjective. If this is your view, maybe you should be working on internals.

> i dunno why you even argue. like i said i acknowledge the use case and see your point(s), i just don't want to spend my time on it.

This has not been the impression you have given at all! _"i think it would be the best to just have a script for this that shouldn't be included by default"_ does not sound like merely not wanting to spend time on it. This sounds like you would go out of your way to prevent this (eg. rejecting a PR). Is this the case? It would be useful to clarify this, otherwise nobody will be motivated to work on a PR.

**Comment by wm4** [comment]
> If this is your view, maybe you should be working on internals.

Or maybe you should get to work and stop annoying him? That's no way to talk to someone who's trying to fix your bugs.

**Comment by Dudemanguy** [comment]
Old issue and feature request that probably won't be implemented based on the discussion.
