### ISSUE TITLE
sdl video output plugin only uses opengl, cannot use x11

### ISSUE THREAD

**Issue by aworan** [mpv-player/mpv#2811]
SDL supports a few different strategies for getting video onto a display. One of these is to use OpenGL. This performs very poorly if there is no actual hardware OpenGL support. Another is to use the X11 protocol. This typically works better when there is no hardware acceleration available.

Using `mpv --vo sdl` there is no way to ask SDL to use X11 instead of OpenGL (which is selected by default).

It would be great if there were a way. This is a reason it might be difficult to switch from mplayer to mpv - in the case where, mplayer's SDL usage results in X11 being used and video playback operating reasonably and mpv's SDL usage results in OpenGL being used and video playback performing too poorly to tolerate.

**Comment by wm4** [comment]
So why would you use this if there's vo_x11.

**Comment by wm4** [comment]
Also, mplayer uses SDL 1, while mpv uses SDL 2.

**Comment by wm4** [comment]
Actually it turns out we explicitly only accept accelerated rendering, which ``--vo=sdl:sw`` can override.

**Comment by Gusar321** [comment]
aworan is on a RPi and wants to play video in an X window. The problem is, even specifying --vo=sdl:sw will give you opengl and thus mesa's software renderer. Something like a "force-sw" option would be needed.

The only way I could get sdl's software renderer was to compile it without any opengl support and hack the configure script to not activate native rpi support (there's no configure option to disable the rpi renderer). However, the video then looked like this: http://i.imgur.com/nhk1xOb.png, instead of what it should look like: http://i.imgur.com/ytcmU0G.png. So it seems vo_sdl is a no-go on the RPi.

@aworan: I provided instructions at the end of issue #2532 to switch the framebuffer to 32bit, which will make --vo=x11 work.

However, two things:
What's discussed in that issue, geometry support for vo_rpi, is now available. Try something like ```mpv --vo=rpi --no-fs --geometry=-60+60 --autofit=35%x35% yourvideo.mkv```, this will give you a window near the top-right corner. Adjust the options to your liking.

Also, it was quite easy to add 16bit support to vo_x11, I'll make a pull request.
