### ISSUE TITLE
Some configuration tags do not work

### ISSUE THREAD

**Issue by ccqpein** [mpv-player/mpv#2813]
It is my mpv.conf file in `~/.config/mpv` 

```
#for intel HD4000 above
vo=opengl
hwdec=auto

#osd message, you can press o to display the osd message
osd-status-msg="${time-pos} / ${length} (${percent-pos}%)"

#always save the current playback position on quit
save-position-on-quit=yes

#cache
cache=auto

#subtitles
sub-codepage=enca:zh:utf8

#Start the player in paused state.
pause=yes

#volume when start
volume=50

```
1. `pause` cannot work, I remember it should work in last version.
2. `osd message` cannot work, but if I use 

```
osd-level=3
osd-status-msg="${time-pos} / ${length} (${percent-pos}%)"
```

it workd as I thought. (BTW, if `osd-level=1`, it cannot work neither)

Could anyone give me some help for fixing that?

**Comment by wm4** [comment]
I have no idea what you're trying to report.

**Comment by ccqpein** [comment]
Ok, I am sorry.

In the last version, this config file works well, but I notice some setting in this version cannot work anymore.

1. `pause` does not work.
2. `osd message` does not work.

Then I change `osd message` label to 

```
osd-level=3
osd-status-msg="${time-pos} / ${length} (${percent-pos}%)"
```

It does work, but the message shows all the time. I remember the message show in interactive in the last version even does not use `osd-level=1`.

If you have some questions of my report, let me know.

Thank you very much.

**Comment by wm4** [comment]
Putting `pause` into the config file works just fine for me. Not sure whatever you mean by the osd message thing.

**Comment by ccqpein** [comment]
I am sorry. 

Before the last version, osd setting is `osd-status-msg="${time-pos} / ${length} (${percent-pos}%)"`. The message will show when I active mpv. But now it does not work anymore.

**Comment by ccqpein** [comment]
I update to 0.16 with brew (uninstall the 0.14 version with brew-cask), and the `pause` and `osd-status-msg` still cannot work.

**Comment by bodayw** [comment]
`pause` works for me. Actually you only need to put `pause` in the config file, but `pause=yes` works as well.

If you just want to see the playback progress while playing, you don't need that line in your config file, because mpv already has that as the preset default behavior when you press `o` or `P` (and obviously you shouldn't change the key binding for `o` or `P` in your `input.conf` for it to work). But again, I think even with that line you put there, it should work nonetheless, meaning, it will still show the information you defined when you press `o`.

How exactly did you build your mpv in the beginning and how did you uninstall it and update it to the new version (maybe something went wrong during compilation)? Also, are you using any front end software for mpv (that might be outdated and not compatible with mpv anymore)?

**Comment by kevmitch** [comment]
It is probably not possible to "miscompile" mpv so it doesn't obey the pause property, but works otherwise. It is much more likely that this config file is just misnamed or in the wrong place. @ccqpein says it "works well" otherwise, but I'm not convinced anything in this config file is working at all if ```pause``` isn't recognized. 

There was a mention of brew above which is the first indication that this is on OSX. My understanding is that the config file locations on OSX are somewhat confusing depending on whether you use the command line or the .app. Unfortunately, there doesn't appear to be a ```FILES ON OSX``` section to the manpage, so someone with an actual running OSX will need to fill you in on where the config file is supposed to go in various circumstances.

**Comment by bodayw** [comment]
https://github.com/mpv-player/mpv/blob/master/DOCS/man/mpv.rst#configuration-files

Those locations also apply on OS X. Typically `mpv.conf` and `input.conf` should be under `~/.config/mpv/mpv.conf` no matter you use the build from @ChrisK2 or build it on your own with homebrew.

But I remember the default location used to be `~/.mpv/` and was changed quite a while ago. Maybe this is not supported anymore?

**Comment by ccqpein** [comment]
This is my config file:

    #for intel HD4000 above
    vo=opengl
    hwdec=auto
    
    #osd message, you can press o to display the osd message
    osd-status-msg="${time-pos/full}/${length/full} (${percent-pos}%)"
    
    #always save the current playback position on quit
    save-position-on-quit=yes
    
    #cache
    cache=auto
    
    #subtitles
    sub-codepage=enca:zh:utf8
    
    #Start the player in paused state.
    pause=yes
    
    #volume when start
    volume=50

My config file in `~/.config/mpv/mpv.conf`, and 

* `osd-status-msg` not work
* `pause` not work

**Comment by bodayw** [comment]
Can you verify whether your config file is actually being recognized and working? You can test it with other commands you have, like `save-position-on-quit=yes` or `volume=50` (open a file and press `9` or `0` to turn the volume up/down and see if it changes based on the 50% value), which are very easy to test.

If not, then the config file might not be recognized and loaded at all.

I'm not a homebrew expert, and I can't tell if anything is wrong with your homebrew command building mpv. Maybe you can try remove mpv with `brew rm mpv` and then follow the tutorial here:
http://coalgirls.wakku.to/faq/playback/compiling-mpv-on-mac-os-x

Or just try use the latest compiled mpv builds here:
http://sva.wakku.to/~chris/mpv_builds/

**Comment by ccqpein** [comment]
`volume = 50` and `save-position-on-quit=yes` work well.
