### ISSUE TITLE
Where to find the keyboard shortcuts?

### ISSUE THREAD

**Issue by vivekkumar27june88** [mpv-player/mpv#2849]

**Comment by wm4** [comment]
See documentation.

**Comment by Hrxn** [comment]
Here:
https://mpv.io/manual/master/#keyboard-control

Or here:
https://github.com/mpv-player/mpv/blob/master/etc/input.conf

**Comment by equalsfive** [comment]
It's honestly disgusting that this is what you're pointed to when looking for something as simple as shortcuts.

**Comment by CounterPillow** [comment]
It is honestly disgusting you dig up a 3 year old issue to take offence in at being directed to the appropriate documentation, but "0 contributions in 2018" says enough about you as a person I guess.

**Comment by gim-** [comment]
https://www.cheatography.com/someone/cheat-sheets/mpv-media-player/

**Comment by x1024** [comment]
Thanks, the cheat sheet was actually what I needed.  

The original documentation had a host of problems - for example, using un-searchable language.  
My use-case was that I wanted to use the next subtitle track. However, searching for "Next Subtitle" only showed a shortcut that didn't work on my OS, whereas the real shortcut was "J". But it's not really practical to go through all 240+ occurrences of "Subtitle" in the document in order to find the one that I needed. Just my 2c.

**Comment by CounterPillow** [comment]
It's the seventh hit for "subtitle". Pro tip, documentation for keyboard controls is in the keyboard controls section.

**Comment by wm4** [comment]
It's quite interesting that I got 60 "downvotes" for mentioning the documentation, which, you know, documents this.

Feel free to contribute patches to improve the documentation, so you too can feel pissed off at stupid users giving you shit for sinking time into this project.

Fuck users, they don't deserve better.

**Comment by wm4** [comment]
Also on a slightly more productive note, here's an old hand-edited chart (there's an editable svg file in the same directory): https://github.com/mpv-player/random-stuff/blob/master/key_bindings_chart/mpbindings.png
Of course this is outdated. So if anyone wants to update it, you're welcome (so that it gets called disgusting by users who never did anything productive).

**Comment by CounterPillow** [comment]
The only reason why this issue has so many reactions is because this is somehow the second Google result for "mpv keyboard shortcuts", so users are actually stupid enough to downvote wm4 because *Google didn't give them the right result.*

**Comment by x1024** [comment]
I have zero incentive to contribute to a project where the first time anyone on the project talks to me they use "fuck", "shit", "piss", and "stupid" in the same post.

If you feel that when a user searches for "subtitle" and sees "1/244", the appropriate action is "try to go through the results, see if you find anything", then I don't know what to tell you.

In the future, just give users the cheat sheet and don't call them names. In fact, please delete every other comment on this thread other than the one that actually solves the issue.

**Comment by CounterPillow** [comment]
>I have zero incentive to contribute to a project

"13 contributions in the last year"

You were never gonna contribute anyway, bud.

**Comment by x1024** [comment]
Do you seriously think I would risk talking to people like you from an important account with a lot of stuff on it?

**Comment by CounterPillow** [comment]
From GitHub's terms of service:

>One person or legal entity may maintain no more than one free Account (if you choose to control a machine account as well, that's fine, but it can only be used for running a machine).

Time to report you I guess. :slightly_smiling_face: :+1:

**Comment by x1024** [comment]
Or you can read more carefully what you just wrote, realize what it really says and why reporting my only free account won't work.  

Have a nice day, "person whose main contribution to the project is fixing typos in log messages".

**Comment by CounterPillow** [comment]
So you have a second account to defraud the developer programme with, nice!

**Comment by x1024** [comment]
Look, you're obviously disturbed. I wrote what needs to be done in order to make the MPV documentation usable, it's up to the people who actually do work in the project to decide whether they want to move forward with the suggested changes.  

You don't seem to be in any position of authority on this issue, so I don't plan to continue writing or reading here.

**Comment by CounterPillow** [comment]
Nah actually you were just being an idiot, so I corrected you by saying that yeah maybe the keyboard shortcuts are in the section titled keyboard controls, and you decided to instead be a shitty asshole after wm4 explained that you can be the change you want to see.

>Look, you're obviously disturbed.

Yes, your very presence on this issue tracker is disturbing me. Please fix.
