### ISSUE TITLE
There is no sound when playing some of the videos

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2864]
Failed to initialize an audio decoder for codec 'aac'.
ffmpeg has been installed

System: openSUSE LEAP 42.1

**Comment by lachs0r** [comment]
Make sure to switch *all* FFmpeg packages over to Packman.

**Comment by laichiaheng** [comment]
It needs libavcodec57, libavdevice57, libformat57, libavfilter6, but packman doesn't have them.

**Comment by lachs0r** [comment]
Make sure the mpv package comes from there, too.

**Comment by laichiaheng** [comment]
Yes, it comes from packman repository

**Comment by lachs0r** [comment]
Report the issue to Packman. I think they disabled package publishing for now because FFmpeg 3 broke a few things and someone didn’t pay attention, so it’s possible the mpv package can’t be installed right now. Someone mentioned re-enabling it earlier today, so a little pressure might help ;)

(Also, I recommend using Tumbleweed for desktop unless you need your version numbers to be stable for years for some reason.)

**Comment by wm4** [comment]
> I think they disabled package publishing for now because FFmpeg 3 broke a few things and someone didn’t pay attention, 

Is it because of vlc?

**Comment by laichiaheng** [comment]
How do I report bugs to them?

**Comment by laichiaheng** [comment]
Failed to initialize a video decoder for codec 'wmv3'
Failed to recognize file format. (avi format)
I can't load any of the subtitles either.

**Comment by lachs0r** [comment]
Well yes, the version of FFmpeg that comes with openSUSE is crippled and only 
supports free formats.

Try the mailing list or their IRC channel.

**Comment by laichiaheng** [comment]
I have sent them an email with my poor English.
Hope that they understand what I'm trying to tell them.
