### ISSUE TITLE
mpv 0.16.0 when?

### ISSUE THREAD

**Issue by uid313** [mpv-player/mpv#2876]
There have now been more than 250 commits since the last release.
Any reason for the long delay?
I think a new release is important for downstream packagers & distros.

@lachs0r?

**Comment by wm4** [comment]
> I think a new release is important for downstream packagers & distros.

Debian still packages 0.14.0, so I have a hard time believing in this statement.

**Comment by ismail** [comment]
At least we (openSUSE) care about a new release :-)

**Comment by haasn** [comment]
> Any reason for the long delay?

To be clear, the reason mpv ‘releases’ stopped being a thing is because we stopped having a release manager.

If somebody cares about making and testing high-quality stable releases (and maybe even cherry-picking later fixes onto the release branch), we would be honored to have you - but as it stands nobody is really willing to take on that burden.

“Releases” right now are basically “Well, it's been X commits since the last release, let's just take the latest git master commit and tag it with a number that is the previous number plus 1”.

**Comment by Hrxn** [comment]
For Linux/Unix:
https://github.com/mpv-player/mpv#compilation
For OS X:
With Homebrew: `brew install --HEAD mpv`
For Windows:
https://bitbucket.org/rorgoroth/mpv-for-windows/downloads

**Comment by lachs0r** [comment]
Why so impatient? :V

**Comment by uid313** [comment]
@lachs0r 
Thanks for the release!
I was mostly concerned about you having to write a huge changelog the longer a new release would be stretched out... ;--]

@wm4 
Yes, Debian Sid is officially still at 0.14 (don't know why), but rest assured that your work is still being appreciated by the Debianers (if they know where to look at, that is):
[http://deb-multimedia.org/dists/unstable/main/binary-amd64/package/mpv](url)

**Comment by lachs0r** [comment]
Don’t worry; I just look at https://git.srsfckn.biz/mpv/log/?qt=range&q=release/current..master and pick the commits that look interesting, maybe change a few words to clarify things here and there. Then I poke the Windows build stuff and fix everything that broke in the meantime, do a test build to see if it works, and only then I publish a release.

It really helps that commit message guidelines are enforced here :)
I don’t think it’s going to be necessary to add any annotations to commits to help me find them either. That’s too easily forgotten anyway.
