### ISSUE TITLE
mpv Audio Normalization: play all files at equal volume

### ISSUE THREAD

**Issue by octos** [mpv-player/mpv#2883]
When I play a list of audio/video files, some files can be much louder than others. The usual solution is to use a program like MP3Gain to normalize the playback volume in batch, but I'd like to know if it would be possible to have mpv do this automatically at playback, either with or without modifications to the original files.

**Comment by kevmitch** [comment]
It would not be possible to do as good a job as mp3gain, which scans the whole file/album and sets a constant overall attenuation factor. The best you can do in real time is some sort of dynamic range compression like ```af_drc``` (see [mpv audio filters](https://github.com/mpv-player/mpv/blob/master/DOCS/man/af.rst)),  [```lavfi=dynaudnorm```](https://ffmpeg.org/ffmpeg-filters.html#dynaudnorm), or [```lavfi=acompressor```](https://ffmpeg.org/ffmpeg-filters.html#acompressor). All of these however will distort the original audio to adapt to the loudness at the current time.

**Comment by kevmitch** [comment]
Well, actually I think the best you could do is write an audio filter that calculates the appropriate gain for a file and returns it at the end of playback like mp3gain. You could then use a lua script to actually write that new value to the file. So it will only work after the second time the file is played.

**Comment by wm4** [comment]
Pretty sure lavfi has such a gain scanner filter.

**Comment by kevmitch** [comment]
As a matter of fact it does (replaygain)[https://ffmpeg.org/ffmpeg-filters.html#replaygain]. Looks like it only outputs the results on stdout though. It could be patched to add filter metadata.

**Comment by kevmitch** [comment]
actually could be tricky since the data would disappear when the file ends.

**Comment by richardpl** [comment]
there is also volumedetect

**Comment by haasn** [comment]
Keep in mind that any technique that scans the whole file would be very bad when watching a networked source (e.g. a livestream).

On the other hand, any technique that *doesn't* scan the whole file would be very bad because it would remove any dynamic range the audio file has.

The simplest, most effective and most supported solution is to scan your local files in advance (e.g. with mp3gain, flacgain, vorbisgain, etc.) and tag their RG information into the files.

Note that this does not require modification of the audio data itself, i.e. your MP3 files won't be recompressed - and no waveform information will be “lost”. ReplayGain works by adding a tag to the *header* of the file, which simply tells the media player how much louder or quieter to play the file.

**Comment by wm4** [comment]
The dynaudnorm filter might be the best bet here, because it does very excessive lookahead (15 seconds or so).

**Comment by kokoko3k** [comment]
even try alimiter with an high release time:
mpv <somefile> --af=lavfi=[alimiter=10:1:1:5:8000],volume=softclip=yes
