### ISSUE TITLE
Same issue again with vo=opengl in windows

### ISSUE THREAD

**Issue by man0000** [mpv-player/mpv#2893]
Again I have to comment the issue of disappearing window (though the process starts) when vo=opengl or vo=opengl-hq exists in config file.

This time the issue affects both with/wo '-hq'.

I have tried to use backend to solve it but none of the backend options solves the problem.

Any idea?.
THANKS...

Windows10 x64 core i7-2600...

**Comment by kevmitch** [comment]
"same issue" refers to #2736

Was that resolved? If so, how?

Please post the log obtained with ```log-file=log.txt```.

**Comment by man0000** [comment]
The solution was :
vo=opengl[-hq]:backend=angle

This way all worked.

What log do you need?. January or February release?.

**Comment by kevmitch** [comment]
> vo=opengl[-hq]:backend=angle

angle has been (hopefully) temporarily disabled

> What log do you need?

The current release if that is  failing.

**Comment by man0000** [comment]
Yes, I have read it but is the only option that works with vo=opengl.
I made a mistake before when I said any backend option worked.
With vo=opengl[-hq]:backend=angle I have mpv window and all work as expected.

log.txt = file played witth vo=opengl-hq  >>> No mpv window
[log.txt](https://github.com/mpv-player/mpv/files/153540/log.txt)

log_w_angle.txt = file played with vo=opengl-hq:backend=angle >>> mpv window as expected
[log_with_angle.txt](https://github.com/mpv-player/mpv/files/153543/log_with_angle.txt)

Let me know if something else is needed...

**Comment by kevmitch** [comment]
Well it seems that we're back to the original issue of ```backend=win``` using the Microsoft software renderer instead of the Intel hardware renderer. I guess that problem never had anything to do with angle other than the fact that using angle was a workaround.

Just to be sure, do you have the latest [HD 2000 drivers](https://downloadcenter.intel.com/product/81502/Intel-HD-Graphics-2000-for-2nd-Generation-Intel-Core-Processors) installed? Also have you disabled Aero (i.e. are you using a "Basic" theme)? I think the Intel drivers require Aero - at least they tend not to work very well without it.

Setting ```backend=angle``` in the current build makes no sense, since it is not built in. The reason it "works" is that it causes ```vo=opengl``` to fail earlier and fallback to ```vo=direct3d_shaders``` (which I have a feeling is not long for this world).

**Comment by lachs0r** [comment]
Your system is broken and there’s nothing we can do to fix it on our side. It doesn’t support hardware-accelerated OpenGL, and the ANGLE backend just failed and it ended up using direct3d_shaders instead of opengl-hq.

Since this is Windows 10, the compositor is mandatory (so you cannot disable Aero by using a different theme). Make sure you got the drivers from Intel, and if that doesn’t work, then sorry, but your hardware is unsupported. If you’ve upgraded from a previous version of Windows, maybe try a clean reinstall.

Closing since this really isn’t our problem and there’s no further advice to give. If you want someone to help you getting OpenGL acceleration to work, try contacting Intel (good luck with that).

**Comment by lachs0r** [comment]
Also, FYI, HD 2000 is too weak for opengl-hq anyway.
