### ISSUE TITLE
Chroma doubling?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#2910]
Hi!

Following the latest commit about luma-only pre-scaling https://github.com/mpv-player/mpv/commit/b81036524a834ebf33d7ae520153be0062d3dae5

I wonder what about chroma-only doubling/pre-scaling then? Is it implemented in other way (say, `cscale`) , or such operation is simply unnecessary at all?

Regards,
Alex

**Comment by haasn** [comment]
1. To perhaps clarify, `prescale` has never affected the chroma plane, since the option existed. (Hence the rename in b810365)

2. Chroma doubling is possible in principle but note that it would be slower (since you'd be doubling two planes instead of just one) and an extra `cscale` pass will always be required on top of it (to align chroma with luma).
