### ISSUE TITLE
A/V desync when switching audio tracks

### ISSUE THREAD

**Issue by mathstuf** [mpv-player/mpv#294]
I'm seeing an A/V desync when switching audio tracks. Is there a way to avoid this (maybe seeking in the audio track when a switch happens)?

**Comment by wm4** [comment]
Fixed.

**Comment by mathstuf** [comment]
Fixed how? @kevmitch's suggestion? Also, yes I use pulse.

**Comment by wm4** [comment]
If an audio track is enabled, the code for initial audio sync is run, which means no desync can happen (unless such a desync also happens on normal playback start, which means the audio output is behaving strangely/buggy). mpv has been doing this for a while, not sure when.

Also, a recent change makes audio stream switching relatively instant because it gets audio packets earlier.

**Comment by wm4** [comment]
>Also, a recent change makes audio stream switching relatively instant because it gets audio packets earlier.

That was f9f2e1cc4e80a66793249651b74d83c1c8f3a8d4. Isn't done for most file formats.
