### ISSUE TITLE
Fully support mkv linked segments

### ISSUE THREAD

**Issue by 00000000000001** [mpv-player/mpv#2966]
Since it seems you want to know how they should work with ordered chapters:

On the principles that the manual/deliberate should trump the automatic and that the obvious should override the hidden, ordered chapters should negate segment linking. mkvmerge has a checkbox to automatically link segments and the complete sequence of links is going to be buried in the individual mkvs, while ordered chapters have to be manually created and they have the appearance of a full ledger of the playback, so the ordered chapters are simply more obvious and would be a manual, later addition.
If I were to link mkvs and then write ordered chapters expecting the links to work, and those links didn't work, it would be immediately obvious to me that the reason they're not working is that the ordered chapters overwrote them and that I need to write things into the chapters if I want them to work. If, on the other hand, I accidentally linked mkvs by checking the wrong box in mkvmerge, wrote ordered chapters for one of the mkvs, and was suddenly having the player pull up a series of segments that are nowhere in the chapters I just wrote, I'd be pretty clueless as to why, and I wouldn't have anything obvious to clue me in on the reason for the unexpected result, either.

In the real world, segment linking is used in lieu of ordered chapters, so it's pretty much academic. When an opening and ending occur at the very beginning and end of a show you can mux the episodes with links, and that's just faster than writing 25 sets of chapters with the episode lengths entered to the tenth of a second. You never use ordered chapters along with links.
Having chapters trump links makes sense, though.

Ordered chapters overriding links is how things work in MPC-HC if the UID for the current segment is listed.  If it's left blank... well... let's just say there's a bug report to make.  (It still overrides the links and no links are recognized, the chapters are just now all out of order)

**Comment by wm4** [comment]
OK

**Comment by 00000000000001** [comment]
Someone's mad.
Seems there's a reason that everyone (including myself) uses MPC-HC with madVR.

**Comment by wm4** [comment]
> Seems there's a reason that everyone (including myself) uses MPC-HC with madVR.

Then why are you so obnoxious about requesting mpv features? Next time try asking nicely. (After registering a new github account, I suppose.)

**Comment by 00000000000010** [comment]
Because I am obnoxious, you twit.  Welcome to the internet, where not everyone is out to be your lifelong friend.
My brusque attitude has nothing to do with the deficiencies of your "free as in worth $0" player.  I'm an encoder and active on several trackers and this issue with mpv pops up somewhat regularly from people who can't afford a real OS.  "WAAAAH, WHY ISN'T THIS SERIES PLAYING RIGHT ON MUH LEEENUX!"  I tell them to get VLC, but apparently someone has gotten it into their heads that you've actually come close to successfully ripping off madshi.  Their delusion on that count is not my problem, but I'm still left with the fact that they don't have a good solution.

I may be an ass, but I like to be a helpful ass.   Right now there's only a solution for Windows users:  "Replace mpv with MPC-HC with madVR."  I'd like for the problem to simply disappear.  There's no player worth mentioning after MPC-HC, VLC, and mpv, and mpv is the only one that has an issue here.

**Comment by kevmitch** [comment]
> I may be an ass, but I like to be a helpful ass.

I'd hardly say so. If you were more civil / sane, there's a small chance someone would take an interest in implementing this feature. As it stands, there is now a strong disincentive.

**Comment by wm4** [comment]
> but I'm still left with the fact that they don't have a good solution.

The way I see it they should just download other files. If it bothers assholes like you (indirectly), then there's even a positive effect of not implementing this feature. I'm really not sure what you're trying to do here, but you're not making your life easier.

**Comment by 00000000000010** [comment]
> I'd hardly say so

My only job here should've been to point out the problem:  "Yo, your player is shit.  Maybe you should think about fixing it."  I think I went a little above and beyond to explain how, in a real-world human workflow, it makes sense for ordered chapters to trump linking, since wm4 couldn't figure that part out for himself.
You needed a place to start?  There it is.

> The way I see it they should just download other files.
Why would anyone let their player determine what they can watch when they can download a better player?  You probably stream so "quality" is a foreign concept to you, but some people are concerned with watching the best encode.  They tend to complain when the 30GB series that they just snatched and are required to re-seed won't play right.

"MPC-HC with madVR"
"MPC-HC with madVR"
"MPC-HC with madVR"
"MPC-HC with madVR"
"MPC-HC with madVR"

I use it.  I love it.  But it does get tiring saying the same thing over and over again.

**Comment by wm4** [comment]
Well, your attitude makes this extremely hard. Now I'm at a point where I'd even reject a pull request adding this feature. Please piss off.
