### ISSUE TITLE
support for secondary subtitle streams not forced to top | Make secondary subtitle track style editable

### ISSUE THREAD

**Issue by delroth** [mpv-player/mpv#3022]
MPV is one of the rare video players on Linux that supports reading several subtitle streams natively. I have some videos with several non-overlapping ASS subtitle tracks, and I would like to be able to display two of these tracks at the same time.

However, --secondary-sid is currently hardcoded to put the second track at the top of the video. Manually commenting out [this one line](https://github.com/mpv-player/mpv/blob/master/player/sub.c#L185) is enough to get rid of that behavior.

Would it be possible to have this be configurable? I'd like to avoid keeping local patches for my software. If you think it's worth it, I can volunteer my time to implement it.

**Comment by nutinshell** [comment]
This is a very useful feature!

**Comment by wm4** [comment]
Feel free to attempt to implement it.

**Comment by elFua** [comment]
I workaround which is more flexible and works on other players/platforms is to merge the subtitle files into a single file using any of the available online or [offline tools](https://www.videohelp.com/software/sections/subtitle). I've got good results with both https://subtitletools.com/merge-subtitles-online and https://pas-bien.net/2srt2ass/ which had to be manually tweaked for styling and positioning (had to create a post-processing script for that). 

But most importantly, you can join more than two subtitles in a player-independent way. For example, in my case I needed to have four sets of subtitles and using the SSA/ASS format turned out to be the best solution, since the subtitles will work with every player that supports the SSA format.

**Comment by bufemc** [comment]
Any progress in this? Is there a command option where I can say: show first selected subtitle e.g. at position Y1 and second one at position Y2? This would be very fine for learning languages by watching movies with several subtitles.

**Comment by Akemi** [comment]
nope.

**Comment by volkoff** [comment]
As a workaround, you can use VLC 4 (currently in beta)

Copied from [Askubuntu.com](https://askubuntu.com/a/1203146):

> When playing a video, you need to "Toggle secondary subtitle control" with the default shortcut `Ctrl+Shift+V`. (This means that the normal subtitle control shortcuts like `v` or `Alt+v`, for cycling between subtitles backwards and forwards, will now apply to the secondary subtitles, rather than the main subtitles. Pressing `Ctrl+Shift+V` again will toggle back to having these apply to the main subtitles.) Then, press `v` the right number of times to switch to the (secondary) subtitles that you want.

**Comment by weiweihuanghuang** [comment]
+1

**Comment by thecoachchen** [comment]
Any progress on implementing second subtitle positioning?

**Comment by kasper93** [comment]
Fixed by #13073
