### ISSUE TITLE
[feature request]Start caching the next file on the playlist once the current one playing has fully cached

### ISSUE THREAD

**Issue by noijzyotiar** [mpv-player/mpv#3029]

**Comment by wm4** [comment]
Could be done in theory, but only if the file isn't a URL that needs to be resolved by the ytdl script.

**Comment by noijzyotiar** [comment]
Can this be done using lua?

**Comment by maletor** [comment]
This sounds idea. The playlist could easily be files that have slow I/O for whatever reason (network), but they should be preloaded into the cache (and demuxer).

**Comment by haasn** [comment]
FWIW I also think that youtube-dl metadata fetching could/should be done in advance - because the extra pass needed to request the metadata, plus the wasted time due to a double-connect, is a big part of the overhead for watching youtube videos.

I think efforts to optimize the time between “mpv ytdl//URL starts” and “video starts playing” would also not be wasted, so maybe it would be better if youtube-dl could somehow reuse its connection to youtube by passing it over to mpv?

**Comment by wm4** [comment]
Well, in theory, the ytdl script could asynchronously go through the playlist, and resolve entries in advance. But keep in mind that the resolved links don't stay valid forever, so this might not help. It's also complex.

Since the ytdl script has its own (essentially global) state, we couldn't prefetch it transparently like we do for demuxers.

**Comment by wm4** [comment]
This was fixed with the `--prefetch-playlist` option. No support for ytdl.

**Comment by 00SteinsGate00** [comment]
Just curious, why is there no support for ytdl? It's the only way I use urls to play with MPV. Iis it not possible? Does it take too much effort to accomplish it?

I think having support for ytdl with that feature would be highly appreciated by a lot of people, including me

**Comment by wm4** [comment]
Because it's done by a Lua script that sets tons of options, so it can't work this way. It would require changing the wrapper and the interface to mpv.

**Comment by 00SteinsGate00** [comment]
Thanks for the response.

Okay I see, that's too bad, would've been a great feature. Are there plans to do this differently in the future? I read something about running demuxer in a different thread, but that it takes time until that is fully implemented.

**Comment by wm4** [comment]
> I read something about running demuxer in a different thread, but that it takes time until that is fully implemented.

No, it's all just a question of wiring up the ytdl lua script in a way prefetching can work.

**Comment by 07416** [comment]
this script hasn't yet been mentioned: https://gist.github.com/bitingsock/17d90e3deeb35b5f75e55adb19098f58

also listed on https://github.com/stax76/awesome-mpv
