### ISSUE TITLE
--no-input-default-bindings breaks lua key bindings

### ISSUE THREAD

**Issue by jdoe0** [mpv-player/mpv#3037]
With `--no-input-default-bindings`, key bindings added via `mp.add_key_binding()` doesn't work unless the user defines a new key binding manually in `input.conf` or replace the function with `mp.add_forced_key_binding()`. This is the case regardless of whether it conflicts with other user-defined key bindings in `input.conf`. 

Based on `--input-test`, it appears that `--no-input-default-bindings` make mpv ignore key bindings that are 'tagged' as default. Since key bindings added with `mp.add_key_binding()` are also 'tagged' as default, they get ignored too. It might be better not to add the default key bindings at all when `--no-input-default-bindings` is set to allow lua keybindings to work normally in this situation.

**Comment by wm4** [comment]
It works exactly as advertised.

**Comment by blue-sky-r** [comment]
FYI: I can confirm this issue is present as described in this (not recent) mpv version on ubuntu:

`[cplayer] mpv git-ad2d10a (C) 2000-2016 mpv/MPlayer/mplayer2 projects`
`[cplayer]  built on Mon Feb 29 03:19:28 UTC 2016`
`[cplayer] ffmpeg library versions:`
`[cplayer]    libavutil       55.19.100`
`[cplayer]    libavcodec      57.27.101`
`[cplayer]    libavformat     57.26.100`
`[cplayer]    libswscale      4.0.100`
`[cplayer]    libavfilter     6.37.100`
`[cplayer]    libswresample   2.0.101`
`[cplayer] ffmpeg version: N-78780-g1c9215e`

Hope this helps others using this mpv version ...
