### ISSUE TITLE
mpv prioritizes external audio tracks and subtitle files

### ISSUE THREAD

**Issue by GeneralFailer** [mpv-player/mpv#3062]
I'm using version 0.17.0 on Arch Linux.
Basically, mpv prioritizes audio tracks and subtitle files with similar names from the same directory when opening MKV files over the embedded ones even when their language is set to be low-priority.

**Comment by wm4** [comment]
feature not bug

**Comment by GeneralFailer** [comment]
I'm sorry, but in what way can this ever be beneficial? VLC seems to ignore them completely which I'd agree is at least an equally bad solution. After setting up a language priority list in the settings I really expect the external files to be treated equally to the embedded ones, not be played by default.

**Comment by wm4** [comment]
Acknowledged, but others expect the external tracks to be selected by default. The situation gets worse with "raw" files, which don't have a language attached and thus would never be selected if language prefs were to be respected. You can just disable external file loading with ``--audio-file-auto=no --sub-auto=no``.

**Comment by animefreak2** [comment]
@GeneralFailer Needing to jump through an additional hoop to configure a specific language selection which may be completely different from your general preference would vastly diminish the utility of this feature.  
External tracks are used when the internal ones are insufficient.  The only reason to put them in that directory and rename them is because you specifically want to use them.  External overriding all else is godly because it gives you a powerful feature with no additional configuration caveats: you put them in and it works.
If you have externals and don't want them to autoplay, just delete/move/rename them.

**Comment by GeneralFailer** [comment]
@animefreak2, I, like I imagine a large portion of mpv users, mostly use it to watch torrented videos. Some BitTorrent clients like Deluge don't have an option to change the extension of or move unselected files (which sometimes happen to be audio tracks). It's inconvenient to rename them if I want to seed so sometimes mpv ends up playing external files that aren't even fully downloaded. Some unfortunate release structures end up making me switch subtitles every time for a series of videos.

**Comment by GeneralFailer** [comment]
@wm4 So I've [tried](https://www.reddit.com/r/Piracy/comments/4hbv1v/how_do_you_think_video_players_should_treat/) to collect some opinions on the matter, but didn't get any strong ones. Maybe you can reopen the issue to open it up to wider discussion?
Mpv notifying about detected external files somewhere in the corner might be a good compromise. Autoplaying them can still stay as a setting obviously.
