### ISSUE TITLE
I can't open mpv after I upgrade my OS from Ubuntu 14.04 to 16.04

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#3071]
error message:
mpv: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

I installed mpv from here: https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests

**Comment by wm4** [comment]
This is not anything related to mpv itself but has to do with basic system administration. You need to rebuild/reinstall mpv.

**Comment by laichiaheng** [comment]
I have reinstalled it, but still the same.

**Comment by whatot** [comment]
You should install libgbm1 for the missing depend, libgbm.so.1.
Maybe more packages need to install if similar problems happen.

**Comment by laichiaheng** [comment]
libgbm1 had already been installed.

**Comment by mc4man** [comment]
You certainly seem to have issues all the time, likely  most are self-inflicted. Your best bet would be to build your own mpv or whatnot so maybe they'll work with whatever collection of libs you acquire.  As it may had occasion to test an 14.04.4 > to 16.04 in place upgrade so installed mpv before the action. Can say that the previously installed 14.04 mpv (ppa) worked fine after the upgrade to 16.04, no reason it shouldn't.
(-  as it's a higher version then 16.04's  it stayed installed. 
After that an upgrade to the 16.04 mpv (ppa) also works without issue. 
You should probably check your version of libgbm1 rather than ck. if it's installed.

After upgrade - 
doug@doug-Lenovo-IdeaPad-Y510P:~$ mpv
mpv git-da34893 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Wed Apr  6 03:01:01 UTC 2016
ffmpeg library versions:
   libavutil       55.20.100
   libavcodec      57.33.100
   libavformat     57.29.101
   libswscale      4.1.100
   libavfilter     6.40.102
   libswresample   2.0.101
ffmpeg version: N-79246-ga07934d
$ mpv '/home/doug/Videos/amostviolentyear-clip1_h1080p.mov' 
Playing: /home/doug/Videos/amostviolentyear-clip1_h1080p.mov
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 1920x816 yuv420p
AV: 00:00:06 / 00:01:00 (10%) A-V:  0.000

Then updated  - 
$ mpv
mpv git-834a236 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Wed Apr 20 19:20:12 UTC 2016
ffmpeg library versions:
   libavutil       55.22.101
   libavcodec      57.35.100
   libavformat     57.34.103
   libswscale      4.1.100
   libavfilter     6.44.100
   libswresample   2.0.101
ffmpeg version: N-79554-g9a6ae7f
ect.

**Comment by laichiaheng** [comment]
They have fixed the bug, thanks.

**Comment by calidion** [comment]
encountered the same problem.

fixed by:
```sh
sudo dpkg --force-all -P libgbm1
sudo apt-get -f install
```
