### ISSUE TITLE
Change OSC title in input.conf?

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#3093]
Hi,

I will probably look silly because I'm sure there is an easy way to fix my problem but I can't find it. 
I'm on Windows 7, can you tell me what can I do to have the filename and not the media title as OSC title? It would be very helpful.

**Comment by shinchiro** [comment]
not really a solution but you can right-click the title on osc to see the filename

**Comment by Hrxn** [comment]
Does this work?

`mpv --title=${filename} XXX YYY FILE etc.`

**Comment by ChrisK2** [comment]
Probably not possible currently.

**Comment by Movunh** [comment]
I found this issue: https://github.com/mpv-player/mpv/issues/1037
I put media-title="${filename}" in my input.conf. It changes the OSC title but I have not managed to get the filename, now I only have the "$" for all videos. I was so close...

**Comment by Hrxn** [comment]
Okay, so you meant to change the title inside of the OSC UI, and not the application window title, got it..

What are you actually trying to achieve? If you right-click on the title section on the OSC, you will get the filename, do you want to switch the defaults of this element?

If you just want to know the name of the current file, put something like this in your `input.conf`:

`KEY show-text "<string>" [ <duration> ]` 
Like, for example:
`F12 show-text "Filename: ${filename}" 4000`

This should also be part of the default settings, afaik. Just try `I (Shift+i)`

Otherwise, the manual also mentions a `--force-media-title=<string>` setting, maybe that is what you're looking for..

**Comment by Movunh** [comment]
Sorry, I can clarify that if I haven't been clear. You understood me, I want to switch the defaults of the title section on the OSC.
I already have title="${filename}" in my conf and that bothers my autism to see two different names haha. 
If there is an option to see filename in place of mediatitle without rightclick, I'm in!

**Comment by wiiaboo** [comment]
> If there is an option to see filename in place of mediatitle without rightclick, I'm in!

Implemented in https://github.com/mpv-player/mpv/commit/6573b73462e336da0daca845ba4df02782afc2b6
