### ISSUE TITLE
Aegisub crashes when using using mpv

### ISSUE THREAD

**Issue by Varshnyar** [mpv-player/mpv#3161]
When I try to save changes to a subtible that is loaded on mpv, Aegisub always crashes.

Using: Windows 10 64 bits, Aegisub 32 bits and mpv 32 bits

**Comment by haasn** [comment]
And why is this an mpv bug report and not an aegisub bug report?

**Comment by Varshnyar** [comment]
This doesn't happen with MPC-HC. Maybe the player blocks the access to the subtitle, so any other program can't use it.

**Comment by lachs0r** [comment]
This is clearly an Aegisub bug. Report it there.

**Comment by wm4** [comment]
mpv keeps the file open, which on windows apparently implies some sort of exclusive mode.

**Comment by rossy** [comment]
Yeah, while the Aegisub crash is probably an Aegisub bug, the difference in behaviour between MPC-HC and mpv can probably be explained by a use of different FILE_SHARE_* flags.

MPC-HC seems to hook CreateFile so all files in the process are opened with FILE_SHARE_WRITE: https://github.com/mpc-hc/mpc-hc/blob/3099a098932227d0c875e1dac7eb1a32d1dcf229/src/mpc-hc/mplayerc.cpp#L1366

We shouldn't have to install a global hook, but we could modify mp_open to do the same thing.

**Comment by rossy** [comment]
So I just tried to reproduce this with Aegisub. Mine didn't crash, though I definitely remember that older versions of Aegisub would crash when saving a file that was open in mpv, so maybe they fixed that bug since then.

Saving still doesn't work, however. Aegisub shows an error message instead. Changing the share mode used by mpv doesn't seem to help, so I guess just keeping the file handle open is what's causing the error.
