### ISSUE TITLE
watch_later corrupted after ungraceful quit

### ISSUE THREAD

**Issue by weedy** [mpv-player/mpv#3169]
Since you locked #336 I'll have to make a new one.
I switched to the next playlist item and mpv crashed. 
```
$ mpv --save-position-on-quit ytdl://ytuser:techmoan
Auto-loading profile 'protocol.ytdl'
Auto-loading profile 'vo.opengl-hq'
Auto-loading profile 'ao.pulse'
Resuming playback. This behavior can be disabled with --no-resume-playback.
Loading config '/home/weedy/.mpv/watch_later/E2BC5F9CFF31EEBD23AACA219C492B10'
Playing: ytdl://ytuser:techmoan
Cache fill:  0.01% (6183 bytes)   

Auto-loading profile 'protocol.ytdl'
Auto-loading profile 'vo.opengl-hq'
Auto-loading profile 'ao.pulse'
Resuming playback. This behavior can be disabled with --no-resume-playback.
Loading config '/home/weedy/.mpv/watch_later/4900A6F39B4A87F9C8F206ECF4A4FFAD'
...
Cache fill:  5.46% (4204544 bytes)   
[file-cache] unexpected EOF
*** Error in `mpv': free(): invalid pointer: 0x00007f39b0000138 ***
======= Backtrace: =========
Aborted
```
This ate the watch_later data after this ungraceful quit. Because of the way mpv deals with ytdl it can be hard to get back to where you want in a longer playlist.
```
$ mpv --save-position-on-quit ytdl://ytuser:techmoan
Auto-loading profile 'protocol.ytdl'
Auto-loading profile 'vo.opengl-hq'
Auto-loading profile 'ao.pulse'
Playing: ytdl://ytuser:techmoan
Cache fill:  0.01% (6183 bytes)   

Auto-loading profile 'protocol.ytdl'
Auto-loading profile 'vo.opengl-hq'
Auto-loading profile 'ao.pulse'
Playing: ytdl://57cUS9pWTXI
```
I have an idea why it crashed but I don't care about that now or I would have opened a bug for that. I was trying to discus the watch_later problem in #336.

Like I mentioned, I think mpv should only touch the watch_later on file end and not on file start. mpv seems to have a much larger possibility of shit hitting the fan when setting up all the things cache/GL.

Since it looks like we keep multiple files (E2BC5F9CFF31EEBD23AACA219C492B10 and 4900A6F39B4A87F9C8F206ECF4A4FFAD) can we save the last completed file on top of current file position?

**Comment by wm4** [comment]
mpv is not a database. I'll fix any crash that has enough information, but wanting mpv to spam disk writes because you most likely have a broken build is rejected. You can write a Lua script that achieves the same (completely dumb and ridiculous) functionality.

Hope that is clear enough.

**Comment by weedy** [comment]
Fair enough.

**Comment by ticalc-travis** [comment]
I feel that the fact that mpv **deletes** the resume data while the video is playing is what makes this issue so egregious. If something happens, the user cannot at least resume from the previous resume point that was saved; it's *totally* lost. Although there is a write-watch-later-config command, which is very welcome, it has the rather unexpected (to me, anyway) side effect of causing mpv to try to resume at *every* file where the config was written during a session rather than just the latest point. This implementation also potentially causes problems like Issue #3427, and I've had a resume point lost once merely by accidentally specifying an invalid video filter option which caused a failure upon playback.

Why couldn't mpv defer the deletion of the old resume point until the time when the new one is to be written? Or, say, temporarily mark the old data as “about to be deleted” in some way so that mpv can still recover it in case the new resume point somehow didn't make it to disk. Sure, a system failure at a bad time just as the write happens could still cause the loss of data, but the time window for this to happen would be relatively narrow. mpv's current implementation, on the other hand, **arbitrarily extends** this window to last the entire viewing session, which could easily be hours.

No one is asking mpv to “be a database”. We're just talking about reasonable, best-effort practices when writing and updating user data in regular disk files. It doesn't matter how stable and bug-free the OS and player are, there will always sooner or later be things totally out of the user's control, whether it be an unexpected power loss, hardware glitch, or the like. “If your system crashes often, just fix it” is missing the point. Neither of these arguments are any excuse for handling persistent user data carelessly.

**Comment by haasn** [comment]
I'm not sure if I understood the actual request. Do you want,

- `watch_later` to be deleted only when writing the new one (or clearing it at the end of playback)?
- `watch_later` config being written periodically during playback (VLC style)?

**Comment by Argon-** [comment]
I suppos either would be an improvement to the current situation.

**Comment by Hrxn** [comment]
I'm reading this as asking for `watch_later` to be ACID-compliant, at least to some extent?

**Comment by ticalc-travis** [comment]
@haasn Speaking for myself, I think both (as a user option, at least) would in principle be ideal. The first would prevent the previous resume point from being lost if an unclean shutdown happens (which would at least be better than losing it entirely). The second would be nice because it would make it easier for one to locate their place just before it happened.

I disagree with wm4's description of the latter behavior as being “completely dumb and ridiculous”. Updating the watch_later config at a *reasonable* interval (not every single second, but something like every five minutes or so) is perfectly reasonable and mirrors the behavior of productivity software with auto-save functionality and the like. It's what HDDs and SDDs are there for, after all. In case one doesn't want much writing to be happening on their disk for some reason, the behavior doesn't have to be enabled by default. Just an option (with maybe a configurable save interval) would be nice.

There is currently a Lua script for doing this, but there are a couple of caveats. One is that when resuming I have to skip through all of the tracks that I've already viewed in the last session because their auto-saved resumes don't get automatically cleared when playback of each finishes (and there doesn't seem to be an API for doing this). The second is that there is still a window upon resume, before the first resume point gets rewritten by the script, that a crash could occur and the resume point could still be lost. So it's an improvement, but could still be better.

To solve this, maybe mpv could wait until the next resume is about to be written before deleting the old one, and upon a manual save, the newly written resume would then become the “old” one, so that on each subsequent write it effectively replaces the last resume config written during that same viewing session. Would doing this break any known use cases?

The mpv resume function is pretty clever, but I'd love to see it improved for a bit more peace of mind. :)

**Comment by garoto** [comment]
Deleting `watch_later` entries created by `write-watch-later-config` when the user issues a `quit` at the end of playback would be a nice improvement IMO.
