### ISSUE TITLE
Is there a command for upscaling only, not for downscaling?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#3182]
I usually do --vo=opengl:scale=lanczos for playing videos which resolution is lower than 1080p, but I don't want to do it when the resolution is higher than 1080p, it will drop frames.

Is there a command for upscaling only?

**Comment by kevmitch** [comment]
If you want an arbitrary source resolution cutoff, I don't think that exists currently. However, if you specify `dscale=mitchell`, that will apply only in the case the output resolution is lower than the source, otherwise the scaler specified in `scale` will be used. This feature is used in  `opengl-hq`, which is really just what you should use unless that gives performance problems or you really know you want something different.

**Comment by laichiaheng** [comment]
@kevmitch My intel HD4600 can't handle the opengl-hq, so I choose the opengl as well.

**Comment by Hrxn** [comment]
Well, if the HD4600 has problems with `opengl-hq` video output, for whatever reasons, then maybe using `icc-profile-auto` may be too much as well.

Could be a driver issue, or maybe something is not configurated properly within the OS?

**Comment by kevmitch** [comment]
You might have better luck with `--vo=opengl-hq:deband=no`. The debanding is probably the single biggest resource use of the opengl-hq enhancements. That said, my hd4400 seems to handle opengl-hq pretty ok even at 1080p60.

**Comment by laichiaheng** [comment]
@Hrxn It only happens to the VP9 4K video, but it is barely to see after I add the dscale=bilinear to --vo.
@kevmitch It still drops frames, although I can't notice it. LOL
--vo=opengl:scale:lanczos:dscale=bilinear should be the best setting for me.
