### ISSUE TITLE
Cursor changes size and shape in Wayland

### ISSUE THREAD

**Issue by mypetbirdrules** [mpv-player/mpv#3199]
For some reason, when I hover over the MPV window in GNOME Wayland, the cursor becomes enlarged. I am also unable to resize the window with the cursor, and I am forced to use keyboard shortcuts. The window also doesn't seem to resize with the video's aspect ratio like it did in X11, creating black boxes to the left and right of the video.

**Comment by atomnuker** [comment]
All of those are known bugs. Currently mpv picks the default cursor theme and size which doesn't match the non-gnome default. Resizing with the mouse won't work because there is no border (wontfix, we'd have to include the entire GTK). The black border strangely happens only on 1920x1080 (or probably the monitor's apect ratio) after a fullscreen mode exit, so it might be a compositor bug. mutter has some wayland problems right now.

**Comment by haasn** [comment]
> I am also unable to resize the window with the cursor

Isn't client-side decoration great?

**Comment by mypetbirdrules** [comment]
Why not break mpv into a Wayland/GNOME/GTK branch to fix client side decoration problems? GTK can be included easily without annoying others with dependencies.

**Comment by wm4** [comment]
May as well leave this to a frontend instead.

**Comment by rossy** [comment]
@mypetbirdrules You should take a look at [gnome-mpv][1], which is pretty much just that, but implemented on top of the client API. (I don't know if it works on Wayland.)

[1]: https://github.com/gnome-mpv/gnome-mpv

**Comment by atomnuker** [comment]
Its not our bug, the wayland code requests the "default" cursor which is usually the system one, not the toolking one (e.g. libgtk). Gnome doesn't set the system cursor theme but kde does hence it works fine in kde.
