### ISSUE TITLE
[question] strange option parser

### ISSUE THREAD

**Issue by for-MUssi** [mpv-player/mpv#3259]
I want to use mpv in a script to run:
	mpv video.mp4 --media-title="forced media-title: -1"

I tried:
	mpv video.mp4 --media-title=`echo "forced media-title: -1"`
which failed with:
	Error parsing option 1 (option not found)
	Setting commandline option --1= failed.

but this is working:
	mpv video.mp4 --media-title=`echo "forced media-title: +1"`

**Comment by haasn** [comment]
The " in the first command line you gave are merely escaping the parameter to `echo`, so it expands to:

`mpv video.mp4 --media-title=forced media-title: -1`

That it parses with +1 but not -1 is a sheer coincidence, because mpv thinks `+1` is simply the filename of the next file you want to play (after `video.mp4`, `media` and `title:`)

You need to escape the result of `echo` a second time:

`mpv video.mp4 --media-title="`echo "forced-media-title: -1"`"`

**Comment by wm4** [comment]
Those are just simple shell rules and conventions, and have almost nothing to do with mpv.
