### ISSUE TITLE
MPV crashes if you click the CMD window while playing.

### ISSUE THREAD

**Issue by dragons4life** [mpv-player/mpv#3296]
#### bitbucket.org/rorgoroth/mpv-for-windows (latest)  |  Windows 10
Correct me If I am wrong, but MPV shouldn't crash because of that?

### Log files
https://upload.teknik.io/aeIpg.txt (local video file input)

[mpv.conf](https://i.lithi.io/u9oG.conf)
https://i.lithi.io/r7JL.webm

Tried getting around it by using `--no-config` but it crashed either way.

**Comment by Hrxn** [comment]
Also happening with non-elevated `cmd.exe`?

**Comment by rossy** [comment]
Does it crash or just hang? It looks like it's hanging (the window becomes unresponsive and the error reporting dialog pops up when it is interacted with.)

When you mark text in the windows console, it stops updating the screen and a call to WriteConsole from a client application will hang until the text is deselected. Clearing the selection with Esc should make mpv start responding again. Alternative Windows consoles like ConEmu shouldn't have this problem.

It might be possible to fix this on mpv's side by writing log messages to a pipe and doing the WriteConsole calls in a separate thread, but I guess it depends on whether it's worth the effort. Also, even that method will hang eventually when the pipe buffer fills up. The user could mark text in the console and forget about it, so console output may be blocked for a long time.

**Comment by haasn** [comment]
FWIW, this is not strictly an ms-windows bug. mpv also freezes if you suspend the process (using ^S) on a linux terminal.

I'd call it expected behavior. If you don't want mpv to freeze, don't freeze the mpv process. (And if you don't want selecting text to freeze the process, use a better terminal emulator)

**Comment by wm4** [comment]
Reminds me that we bothered to put the windows and OSX GUI code on their own threads to prevent that dragging the window freezes video playback.

But in this case, I agree that we shouldn't care.

**Comment by dragons4life** [comment]
so tl;dr:
We won't fix it, find another terminal(cmd)?

Kinda wish I had proof that this didn't happen before, because I am pretty sure it didn't, but it is what it is.

**Comment by rossy** [comment]
Yeah, it's just a quirk of the Windows console. For example, if I start downloading a file with ``wget`` and I select text in the console, the file won't be downloaded until the text is deselected. Any console program that blocks on console output at some point will be affected, including older versions of mpv (you can test with builds from https://mpv.srsfckn.biz/).

**Comment by dragons4life** [comment]
Yeah it's fine I am liking the new cmd, thanks.

@rossy do you mind telling me if this is a bug or "intentional" as well? https://i.lithi.io/F0ip.webm
normally the AV doesn't replicate so many times, for example;  https://i.lithi.io/HTDz.webm

Maybe it's because it's local, but I somehow doubt that, here is log: https://upload.teknik.io/XIMxj.txt

**Comment by rossy** [comment]
That happens when the status line is longer than the terminal width. mpv doesn't check the width of the terminal when it writes the status line, so it will wrap to the next line and the command to erase the current line won't erase the whole status. In that case, mpv dropped a frame and added "Dropped: 1" to the status line, which made it too long for the terminal. Both Windows and Linux should behave the same in this case.

Maybe this could be changed in mpv somehow (by cutting off the end of the status line when it's too long?) That might cut off important information though. The easy solution is to change your default terminal size to one that's large enough to fit the full line. ~100 chars instead of 80 should be enough.

By the way, which console did you decide on? I'm not sure I recognize the icon on that one.

**Comment by dragons4life** [comment]
It's fine and yes, that fixed it, thanks.

I went with ConEmu, the terminal on Linux still probably the best one.
