### ISSUE TITLE
Window display change/regression in GUI mode with no-osc

### ISSUE THREAD

**Issue by Hrxn** [mpv-player/mpv#3301]
### mpv version and platform affected
Windows 10 Pro x64:
mpv 'release' v0.18.0
mpv git-c57304a
(Tested on two machines)

Windows 10 Pro x32:
mpv 'release' v0.18.0

### Reproduction steps
Put in `mpv.conf`:
`no-osc`

(Can be completely empty otherwise)

### Expected behavior
Earlier versions of mpv showed an window (same size, same position) as with OSC enabled, only the window content was empty, i.e. completely black. That is, no mpv logo and 'Drop files to play here'

__Standard display, launched via shortcut, taskbar, etc. and without `no-osc`:__
![standard](https://cloud.githubusercontent.com/assets/12064918/16540523/721dee64-4068-11e6-9610-0d89c178dbe1.jpg)
(Yes, I'm aware the text looks not as usual, but this is an older screenshot with changed text setting in the config, i.e. `osd-color`.. etc.)

__With 'no-osc':__
As stated, not working as before. Imagine the screenshot above but just black inside the window.

### Actual behavior
`no-osc`
![no-osc](https://cloud.githubusercontent.com/assets/12064918/16540541/df533dae-4068-11e6-865d-b93064c66985.jpg)

`no-osc` and `no-border`
![no-border](https://cloud.githubusercontent.com/assets/12064918/16540546/e93a2968-4068-11e6-8942-6b70d0f3484f.jpg)

I think this should be labeled as _ms-windows_ and probably as _low priority_ as well..

**Comment by rossy** [comment]
Yep, I can reproduce this. I think it's to do with ANGLE becoming the new default OpenGL backend. ANGLE doesn't currently receive any notification when the window is resized. Instead, it checks for changes in the window size in eglSwapBuffers after IDXGISwapChain::Present is called. This means that the size of the backbuffer will be wrong on the first call to eglSwapBuffers after the window is resized. mpv resizes the window on startup, so the backbuffer size will be wrong there too.

You should find that this issue doesn't show up with the other OpenGL backends, so ``mpv --no-osc --vo=opengl:backend=dxinterop`` and ``mpv --no-osc --vo=opengl:backend=win`` should still work. Also, with the ANGLE backend, there should be visual corruption if the OSC is disabled and you quickly change the window size (for example by snapping the window to the side of the monitor with Win+Left.)

The reason why this is only reproducible with the OSC disabled is because the OSC seems to redraw the screen an extra time, so the backbuffer size will be correct.

**Comment by rossy** [comment]
I'm not sure how this can be solved, but I reported it to the ANGLE project in http://anglebug.com/1438

**Comment by Hrxn** [comment]
Yes, you're right. Can confirm that using, for example
`vo=opengl-hq:backend=dxinterop`
results in the old behaviour.

I wasn't aware that Angle became the new default backend for OpenGL. But I see that there were some updates in the commit log, so I guess these enhancements earned Angle the promotion as new default ;-)
 
Otherwise, according to the manual, `dxinterop` is still marked as 'experimental', so I guess I'll try the `win` backend for a while.

**Comment by Hrxn** [comment]
A suggestion, for a possible workaround, maybe:

When starting mpv in GUI mode as described above, always display some kind of splash screen, regardless of the OSC setting. Might turn out useful in the future if that is decoupled.

Just something simple, like with OSC on, some text and and maybe the mpv logo.

**Comment by rossy** [comment]
Hopefully that won't be necessary. Even then, mpv could probably present a black frame twice instead of a splash screen. The above PR should fix this without an additional Present().
