### ISSUE TITLE
[not sure if bug] MPV does not minimize in no-border mode.

### ISSUE THREAD

**Issue by dragons4life** [mpv-player/mpv#3334]
## Windows  10 l https://sourceforge.net/projects/mpv-player-windows/

> https://i.lithi.io/HUQz.webm
> https://upload.teknik.io/N5wMp.txt   - log
> https://i.lithi.io/EvS5.conf - conf

**Comment by garoto** [comment]
Not sure if it's a hack or something else, but mpc-hc can still show the window context menu on **alt-spc** when in borderless mode ("view>presets>minimal mode" ). While I don't really use borderless mode, this sounds like a desirable feature to be present in the Windows builds.

**Comment by rossy** [comment]
It's not really a bug, as such. This is the default behaviour of windows without a caption or border in Windows. There are a few other things that don't work in this mode, like the window menu and the cascade windows command.

FWIW, It's possible to get windows without a border to behave like normal windows, but it requires about 200-300 lines of boilerplate/hacks to work around various quirks that happen when a normal (overlapped) window has no non-client area. For example, Windows will constantly try to redraw the title bar over the client area. I've tried to document all the quirks here: https://github.com/rossy/borderless-window

I guess the question is whether the above code is a good fit for mpv and if we want to add these hacks in order to solve problems like this.

**Comment by dragons4life** [comment]
It's fine, it's not that huge and if it needs a work around like that I doubt the others would approve of it, and neither do I see the point of going trough the trouble/hacks for this, than again I don't have experience on coding.

Simply making a keybind to restore border and pressing winkey+down is sufficient enough for me in case I do need it, imo.

**Comment by rossy** [comment]
So it turns out this wasn't as complicated to fix as I thought it would be. Adding WS_MINIMIZEBOX to the window styles should fix it. Thanks @pavelxdd for the fix.
