### ISSUE TITLE
If opening .avs files, playback starts automatically only with audio=no, with audio I need to seek forward

### ISSUE THREAD

**Issue by Divetoxx** [mpv-player/mpv#3343]
This has occured since version 2016-07-10 and still remaining in version 2016-06-25 for Windows.
When I try to open avisynth scripts in mpv.
If first line in these scripts is:
DirectShowSource("name.mp4",audio=no)
then playing begins normally.
If first line is:
DirectShowSource("name.mp4")
then playing doesn't start until I do seek video forward. After seek playback begins.
Sorry, sprunge.us say: This application is temporarily over its serving quota. Please try again later. 
I'd made log.
Thanks!
[output_avshell.txt](https://github.com/mpv-player/mpv/files/367676/output_avshell.txt)

**Comment by qyot27** [comment]
AviSynth version?

This is an AviSynth issue, not an mpv issue.  I've only noticed this on recent versions of AviSynth+, but it could be something brought in during a merge from classic, so if it can be reproduced under 2.6.1a1 too, report it to both projects.

**Comment by qyot27** [comment]
Okay, I take that back.  Both 2.6.0 and 2.6.1a1 exhibit this problem too, when I know that 2.6 did not previously.

2016-06-25 is the *older* of those two mpv builds, so it can't 'still remain' there in comparison to 2016-07-10.  I'm going to take a wild guess that https://github.com/mpv-player/mpv/commit/aeb3df0e2c7f8e86f7b550f876dc24ae1c4686f6 might have something to do with this because it has to do with seeking and fully read files (which a script probably counts as, maybe?), although it's probably something where that commit intersects with --ao handling and probably affects more than just AviSynth scripts.

**Comment by avih** [comment]
FWIW, I haven't updated avisynth for quite a while (probably almost a year), and I also noticed recently that avisynth scripts don't play anymore with mpv. I didn't try to bisect it yet and it's been a while since i tried avs files with mpv (so it's possible it hasn't been working for some months), but I've been building ffmpeg and mpv with the same options for a long time now, so I don't think it's due to modified build options.

**Comment by wm4** [comment]
I'll assume it has to do something with the ffmpeg avs wrapper.

**Comment by avih** [comment]
Just adding some info:
I have few archived binaries which I built myself.

The last good build I have (where mpv plays avs scripts without needing to seek first) is mpv d797f7d (build April 16th) with ffmpeg 9cb1ed5 .

The following build which I have, and which doesn't work (i.e. avs scripts hang unless manually seeked) is mpv b1a8e8d (built on April 23rd) with ffmpeg 2063f3e .

**Comment by avih** [comment]
I just built mpv d797f7d (the archived build which worked correctly) with a recent ffmpeg (git-244d224) and avs seems broken.

So it seems the issue is with ffmpeg between 9cb1ed5 (good) and 2063f3e (bad).

**Comment by Divetoxx** [comment]
I just have downloaded zeranoe windows ffmpeg build 2b14204 and took ffplay from it. This ffplay plays avs good!

**Comment by avih** [comment]
Interesting. I can also play my avs correctly with zeranoe ffplay N-81036-g2b14204, but my own ffplay (git-244d224 - which got built together with the ffmpeg exe/lib which I use for mpv) crashes with the same avs.

So it might be affected by some build options, although I haven't changed my ffmpeg build config for a very long time.

**Comment by avih** [comment]
If I run `mpv --no-config path/to/script.avs` then it hangs.
But this plays correctly: `mpv --no-config --start=0 path/to/script.avs`

**Comment by qyot27** [comment]
``no-config`` isn't necessary.  Just setting ``start`` to 0:00 makes it work.  I'm actually kind of surprised that's not the default anyway (I'd have thought ``--start=0:00`` would be treated as a NOP, except in this case it clearly isn't).

**Comment by avih** [comment]
> no-config isn't necessary

No, but is makes sure there are no other configs applied via `mpv.conf` etc, i.e. that `--start` is enough to affect the behavior with all other configs at default.

**Comment by Divetoxx** [comment]
Maybe --start emulates seeking in this case?...

**Comment by qyot27** [comment]
FWIW, it appears that this issue has since resolved itself.  My current builds of mpv from git (built against similarly current FFmpeg git) don't exhibit it anymore.  No more needing to force --start or seek in the player window to make video+audio-bearing scripts play.
