### ISSUE TITLE
Window border missing under Gnome on Wayland session

### ISSUE THREAD

**Issue by glaubersm** [mpv-player/mpv#3350]
### mpv version and platform
mpv 0.18.1, Arch linux

### Reproduction steps
play any video under Gnome on Wayland session
### Expected behavior
window border visible
### Actual behavior
window border missing, see the screenshots to compare wayland vs xorg.
http://imgbox.com/Ai9hjCWr
http://imgbox.com/nS38wsj6

**Comment by atomnuker** [comment]
How many times do I have to tell people: to support this we'd need to support client side decorations with GTK, which means we'd have to include and compile and make GTK a dependency. Now the GTK is a huge dependency and it would only ever be useful to just add a border under Gnome so it really isn't justifiable. Distributions would have to compile mpv with the GTK which would make the life of a KDE user or someone who doesn't want useless junk on their system difficult since they'd have to download hundreds of megabytes of dependencies which mpv doesn't really actually depend on (be thankful it's not KDE/Qt that has CSD rather than Gnome since then under Debian you'd have to install VLC which is a very hard dependency for KDE/Qt stuff just to install mpv).
There's a package that Debian (probably other too) ship called gtk3-nocsd, which strips CSDs and as far as I understand it forces the server/compositor to add decorations by itself. AFAIK it doesn't work under Wayland yet but you're welcome to give it a try and report back whether it works.
There are other options for adding borders too but those are pretty desparate and will definitely not fit in any DE.

**Comment by wm4** [comment]
You could add an entry for this in the FAQ on the wiki. People would still report this, but you could just link them the FAQ entry.

>There's a package that Debian (probably other too) ship called gtk3-nocsd, which strips CSDs and as far as I understand it forces the server/compositor to add decorations by itself. AFAIK it doesn't work under Wayland yet but you're welcome to give it a try and report back whether it works.

I doubt it, the situation is so very different...

**Comment by wm4** [comment]
Also, for mitigation, we could draw our own very primitive window borders. They'll look different from the rest of the desktop, but that's obviously unavoidable in general with CSDs.
