### ISSUE TITLE
Run VO uninit before libav decoder close?

### ISSUE THREAD

**Issue by duyhotan2000** [mpv-player/mpv#3354]
Hello,

I was porting the MPV player into an embedded board, using its decoding hardware. The ported MPV works well now, but I want Wayland video out run **uninit** function before the decoder in libav run **close** function. The reason is if the decoder clean up memory before the Wayland closed, the kernel will throw many exceptions because the memories are still in use. Note that I am using direct memory transfer method from libav decoder to Wayland.

If anyone has any idea, please help me!

**Comment by wm4** [comment]
That's not possible. The other hwaccel support in mpv was written with the strict requirement that the VO outlives the decoder (because the decoder accesses parts of the VO state).

There are the following ways around:
- Let decoded frames reference the decoder state. This means the decoder state is part of a refcounted struct, which in turn is referenced by each frame. It will be freed once all frames are unreferenced. This is the preferred solution. AVHWFramesContext in ffmpeg provides an abstraction to deal with this, although it doesn't have to be used.
- "Invalidate" all still referenced frames by setting a shared flag of some  sort on decoder destruction. Sounds very messy, if it even works. Not recommended.
- Add something that forcibly flushes all still queued or in-use frames in mpv on decoder destruction. Would work, but is not recommended because it breaks some features.
