### ISSUE TITLE
The `--network-timeout` flag stops rtsp streams from playing

### ISSUE THREAD

**Issue by WoLpH** [mpv-player/mpv#3361]
### Versions

os: OS X 10.105
mpv git-99d9921 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Jul 23 00:35:13 CEST 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.1
### Reproduction steps

Start mpv with the `--network-timeout` option on an rtsp stream:

```
mpv --network-timeout=6 rtsp://
```
### Expected behavior

A playing video. Without the `--network-timeout` flag everything works as expected
### Actual behavior

```
Playing: rtsp://camera/play3.sdp
[ffmpeg/demuxer] rtsp: Unable to open RTSP for listening
[lavf] avformat_open_input() failed
Failed to recognize file format.

Exiting... (Errors when loading file)
```
### Log files

http://sprunge.us/VeSN

**Comment by eintw1ck** [comment]
Does this still happen?

**Comment by WoLpH** [comment]
It does with 0.27.0_3, so far I haven't had any luck compiling the latest version using homebrew yet.

I think I'll have to recompile libav and ffmpeg as well

**Comment by WoLpH** [comment]
I've tried the latest build on [laboratory.stolendata.net](https://laboratory.stolendata.net/~djinn/mpv_osx/), no change as far as I can detect. It still exits immediately.
I've run a test on Cygwin as well, same result.

To reproduce yourself:
```
mpv --network-timeout=6 rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov
```

**Comment by wm4** [comment]
As I've said many times before, this is due to ffmpeg's garbage API, that makes rtsp as only protocol behave different if the "timeout" option is set. Not only does it use a different unit (seconds instead of microseconds, which means mpv passes in a very high value that can overflow ffmpeg's internal bullshit calculations), but it also sets rtsp into listening mode, which is probably not what you want, and which is the reason why this fails.

So I can't improve this because of ffmpeg's garbage API. Just don't use this option with rtsp. You can still set the AVOptions directly, if you know which. I'll send a patch to ffmpeg, if accepted, it might help resolving this.

**Comment by wm4** [comment]
Actually I won't send a patch. Why should I spend my life on this garbage? It's not even my fault.

**Comment by WoLpH** [comment]
I understand completely, I've looked through the ffmpeg source before and ... I suppose garbage covers it :P

**Comment by wm4** [comment]
I PR'ed a manpage warning just to reduce the confusion. (This issue was reported multiple times.)

**Comment by WoLpH** [comment]
Regardless, it's an upstream bug so I'll close this. Thanks for the help everyone :)
