### ISSUE TITLE
How to make mpv consider a changed output mode size for fullscreen while running?

### ISSUE THREAD

**Issue by lvml** [mpv-player/mpv#3372]
Hi,

I just implemented an extension for issue https://github.com/lvml/mpv-plugin-xrandr/issues/6 - but one minor remaining issue with this is that when using xrandr to change to an output mode with different resolution, the notion of "what (size) fullscreen is" seems to differ in mpv from that mode I switch to while mpv is running - probably because mpv detects the screen size at an earlier point in time?

Is there a way to make mpv re-consider a changed output mode size while running, such that "fullscreen" fills the then active mode?
### Reproduction steps

```
mpv --script=xrandr.lua --script-opts=xrandr-output-mode=640x480 some_1080p_video.mpv -fs
```
### Expected behavior

Video fills the (by then) 640x480 pixel sized "fullscreen"
### Actual behavior

Video does not "fill" the (by then) 640x480 "fullscreen".

**Comment by lachs0r** [comment]
mpv tells your window manager to fullscreen its window if it supports EWMH, so that’s definitely a window manager bug. I don’t think mpv should have to care about crappy WMs that don’t support the fullscreen EWMH at all, either.

Example of a buggy WM: i3 supports the fullscreen EWMH but can’t handle display layout changes at all, and mpv will not be able to work around that either. Restarting i3 in-place will resize mpv’s fullscreen window to the proper size, though.

**Comment by lvml** [comment]
Hmm. The fvwm 2.6.6 window manager I tested this on supported Extended Window Manager Hints [since version 2.5 in 2002](http://fvwm.org/documentation/manpages/fvwm.html#lbAQ).

Can you name a positive example of a window manager that will adjust the full-screen window size to the new display resolution when an output is changed with xrandr?

**Comment by Coacher** [comment]
> Can you name a positive example of a window manager that will adjust the full-screen window size to the new display resolution when an output is changed with xrandr?

openbox-3.6.1

**Comment by lvml** [comment]
@Coacher: Thanks for the hint. openbox looks like some window manager I could like (should I get tired of fvwm) :-)
