### ISSUE TITLE
Regression when maximizing/snapping window to edge of screen on Wayland

### ISSUE THREAD

**Issue by ignisf** [mpv-player/mpv#3390]
### mpv version and platform

mpv git efa9fe8edfb2260359aa468a11c0df521862fb0c
Wayland session of Gnome 3.20 on Arch
### Reproduction steps
1. Checkout 2f986a598039b23862eaa870076c0c8fc2e9f86a (#3381) or a later commit (cc @atomnuker @wm4)
2. Play a 16:9 video on a 16:9 screen
3. Maximize or snap the window to the left or right edges of the screen. (By dragging the window until the mouse touches the desired edge, or using Win+Left/Right/Up)
### Expected behavior
- When the window is snapped to the left or the right edge of the screen, the width of the window is half the width of the screen and the height of the window is equal to the height of the screen minus the height of the header bar. The width of the video is equal to the width of the window and there are black bars above and below the video.
- When the window is maximized, its height and width are equal to the height of the screen - height of the top bar and the width of the screen. The height of the video is equal to the height of the screen and there are black bars to the left and right of the video.

![Expected](https://cloud.githubusercontent.com/assets/1153188/17411244/3b41854a-5a80-11e6-8f62-89b329173495.gif)
### Actual behavior
- When the window is snapped to the left, the height of the window is equal to the height of the screen minus the height of the top bar. The height of the video _is equal to the height of the window_ and its width is proportional to its height and aspect ratio. The width of the window is the same as the width of the video. This leaves an empty space to the right of the window.
- When the window is snapped to the right, the behaviour is similar to when it's snapped to the left, except that the window's top left corner is positioned in the top middle of the screan which leads to half the video being off-screen and half the screen being empty.
- When the window is maximized, the behaviour is similar to when it's snapped to the left.

![Actual](https://cloud.githubusercontent.com/assets/1153188/17410557/eacc1088-5a7c-11e6-95c0-1b79f865efba.gif)
### Log files

_Not applicable_

_Edit: express behaviours in words_

**Comment by atomnuker** [comment]
Can't replicate, also that commit is old.
Do a git pull, compile, try again and report back.

**Comment by ignisf** [comment]
The behaviour was observed on the current master as stated in issue:

> ### mpv version and platform
> 
> mpv git efa9fe8edfb2260359aa468a11c0df521862fb0c

The git bisection I made to track down the commit that introduced the issue lead me to 2f986a5

**Comment by atomnuker** [comment]
Maybe that code should respect the edges, but if mutter doesn't flag them upon these operations I can't do anything.
I'll have time to test tonight.

**Comment by atomnuker** [comment]
Fixing this doesn't seem likely.
Basically, the compositor can send out hints such that the program resizes itself upon asked. This is how those screen snapping actions are dealt with - as hints for the application to resize itself such that it takes up e.g. half the screen space, with the compositor doing the actual snapping.
Mutter also sends out a hint after a fullscreen toggle which asks the application to resize itself to a given size but the new sizes almost never have the same aspect ratio and leave black bars around.
This is not entirely insane given that the hints can be ignored by programs and the specs mention that programs should stay within a given aspect ratio. What is insane however is why the compositor doesn't keep the same aspect ratio as before fullscreen, or at least keep the screen aspect ratio if there wasn't any before that.
So the fix for the second problem interferes with the screen snapping and there really isn't a clear way to differentiate between them. IMO having arbitrary black bars around windowed images is way more annoying than not being able to snap the player to half the screen.
Mutter also has other bigger window management problems, so working around them like now hopefully won't last long.

**Comment by ignisf** [comment]
Do I understand correctly that 2f986a5's purpose is to remove black bars around plain static images opened with MPV that have *non-standard* aspect ratios/sizes:

![screenshot from 2016-08-05 05-54-39](https://cloud.githubusercontent.com/assets/1153188/17424953/48062c80-5ad1-11e6-842d-ff33de7f0e4d.png)
*(the correlation seems somewhat random as for example a 1024x768 image doesn't have black bars but an image with 4 times longer sides does)*

which causes a regression in the maximization & snapping of *all* videos and images?

And you consider your use case (using MPV as an image viewer) to be more widespread than playing a video on one half of your screen while for example using a browser in the other?

**Comment by ignisf** [comment]
(could this issue get a "wayland" tag please?)

**Comment by atomnuker** [comment]
Fixed in commit 68f9ee7e0b3fd

**Comment by ignisf** [comment]
<3
