### ISSUE TITLE
video-sync = display-resample framedrops

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#3418]
### mpv version and platform
mpv git-b9ba9a8, OS X El Capitan 10.11.6
Core2Duo P8600, Geforce 320M

### Reproduction steps
Running mpv with any of the display- modes causes excessive framedrops in some hevc files and some of the heavier scenes, while the autospeed lua script, which apparently does the same thing as video-sync=display-resample, causes almost none.

### Expected behavior
Little to no framedrops.

### Actual behavior
Moderate to excessive framedrops.

### Log files
With video-sync set : http://sprunge.us/OOGT
With autospeed.lua only : http://sprunge.us/LEhR

**Comment by kkanungo17** [comment]
then why does autospeed work fine?

**Comment by kevmitch** [comment]
> then why does autospeed work fine?

Because fpsadjust.lua (I assume this is what you mean by "autospeed" ) is a hack that only adjusts speed at the beginning of playback based on crude estimates that may not be all that accurate. video-sync=display-resample does constant dynamic adjustment to actulally measured frame timings. The latter is a much better approch provided the timing measurement and adjustment actually work, which they do on Windows and Linux.

**Comment by wm4** [comment]
It also uses a completely different method to time the video. autospeed uses the system timer to time videom frames, while display-sync attempts to use the driver's vsync blocking behavior as timer.

**Comment by kevinlekiller** [comment]
No autospeed is a script I wrote, it can adjust the monitor mode and the mpv speed (if the estfps changes), although I recommend to use `video-sync=display-resample` and just use the script for changing the monitor mode, since  `video-sync=display-resample` is better.

My guess as to why  `video-sync=display-resample` is hard to process, it probably does what it does on every monitor refresh, which means the time span it has to work with is short.

**Comment by wm4** [comment]
> it probably does what it does on every monitor refresh, which means the time span it has to work with is short.

Shouldn't matter, because the driver has to do the same work anyway. But I guess the opposite is also possible, depending on driver behavior.

Though there'll be a real difference if video fps isn't close to display fps - then mpv could manually repeat frames to reach the framerate, instead of just not rendering frames.

Anyway, the reporter seems to use El Capitan, which is known to be broken, even without displaysync.

**Comment by kkanungo17** [comment]
okay, so nothing much to do other than wait for sierra to fix things or keep using autospeed.
