### ISSUE TITLE
MPV stops responding to multiple loadfile commands over ipc if pipe is not closed/opened between commands

### ISSUE THREAD

**Issue by drojf** [mpv-player/mpv#3422]
Hi, I believe I have a similar issue to #3416 when using ipc.
### mpv version and platform

mpv 0.18.1-git-1e00bcc  (32 bit)
Platform: **Windows 10 64 bit** 
### Reproduction steps

Start mpv in console mode 

> mpv --idle --input-ipc-server=\.\pipe\mpvsocket

Repeatedly pipe `loadfile filename.mp3\n` into mpv **without** closing/opening the pipe in-between writes. You also must insert a short delay between each command (I've tried 100ms - 10s) so that the file has time to start playing. [See attached example program](http://pastebin.com/AW8UagEL) for an implementation.

If you do try and [open, write, close] the pipe repeatedly, everything will work with no problems. This means you can't use echo or socat to test for this issue (I haven't used socat before, but I assume it opens, then writes, then closes the pipe every time it's used). I tried echoing multiple lines at once to mpv but since there is no delay it doesn't cause the issue.

Even if the file to be loaded does not exist, MPV will eventually stop responding (but it will take longer).
### Expected behavior

MPV will respond to commands indefinitely
### Actual behavior

MPV will not respond to commands over the pipe after about 14 commands. If you `loadfile` with a file which doesn't exist, it takes about 50 commands before MPV stops responding. You can still interact with MPV using the command line (eg if you press 'a' it will say 'no key binding found for 'a').

If the process writing to the pipe is killed (eg pipe is forced closed), then MPV sometimes resumes operation as normal, and will display all the backed-up commands at once.

If you issue incorrect commands, MPV responds correctly, no matter how many or often. I think it's an issue specific to loadfile.
### Log files
- if you kill mpv when it stops responding to ipc commands: http://pastebin.com/raw/gjZXz5US
- if you kill the process writing to the pipe when mpv stops responding:  http://pastebin.com/raw/ZTCEJQXF
### Extra files

Here's the c program I'm using to test the issue: http://pastebin.com/AW8UagEL

My test program should be OK because issuing huge amounts of garbage commands to MPC does not cause the same issue.

**Comment by rossy** [comment]
Thanks for the test program. I think this is happening because the write buffer for the pipe is being filled up. When you run a ``loadfile`` command, successful or not, mpv will write a few JSON-formatted events back to the pipe. For me it writes these:
```
{"event":"start-file"}
{"event":"tracks-changed"}
{"event":"end-file"}
{"event":"idle"}
```
If you only run a few commands with a single pipe instance, this is harmless. The events will be written into the pipe's write buffer, (which is at least 4096 bytes long, possibly much longer,) and discarded when the IPC client disconnects. If you run a lot of commands without reading events, the pipe buffer will fill up, mpv will block when writing events and the IPC thread will deadlock. mpv will still respond to keyboard input and other IPC clients, but the client with full buffers will not be able to execute commands until it drains the pipe.

This means that a minimal IPC client must both read and write from the pipe, even if it discards what it reads.

Here's a minimal IPC client that sends a ``loadfile`` command every 300ms. (It also does the proper retry logic when opening the pipe, though that's unrelated to the issue):
https://gist.github.com/rossy/4e2a588d4703d93b531ce9d544a11dde

I've had that client running in the background for a few minutes with no deadlocks. Hopefully it's helpful.

I'm tentatively flagging this issue with "not our bug" because I don't think there's anything that can be done about it on mpv's side. mpv could queue unsent reply messages in an internal list, but that just means programs that don't read from the IPC pipe will cause mpv to consume unbounded memory instead of deadlocking. Maybe if it were possible to tell if the client opened the pipe with GENERIC_WRITE access (rather than GENERIC_READ | GENERIC_WRITE,) mpv could know if it's safe to write to the pipe or not.

**Comment by drojf** [comment]
Thanks so much for the response (and the fixed example program). I was afraid I was doing something wrong on my end, but it ended up being in a way I never imagined....

I agree it's not something you should fix. The only thing I could think of is to write in the documentation that the pipe will stop working if you don't read the data out of the pipe / you must always read out of the pipe regardless of the type of command. I guess this is a standard thing with pipes (which I'm new at using) so it may not have to be mentioned, but I think it's possible for other people to issue commands thinking there will be no reply, especially for a remote connection to a media player. 

I also thought that you only got JSON back after issuing JSON formatted commands, and 'normal' commands were treated like console commands and only showed results on the console on which they were being run. 

EDIT: just noticed this from the documentation under "Socat Example":
> It's also possible to send input.conf style text-only commands:
> 
> `echo 'show-text ${playback-time}' | socat - /tmp/mpvsocket`
> 
> **But you won't get a reply over the socket.** (This particular command shows the playback time on the player's OSD.)

While it is true that `show-text` doesn't give a reply, it's particularly deceptive since it implies all non JSON commands do not reply (which is exactly this issue). This might have been what confused me in the first place, now that I think about it.

**Comment by rossy** [comment]
Yeah, this confused me too.  It's not the commands themselves that are sending replies, but rather the side effects of the commands are causing events to be sent. Maybe this could be fixed on mpv's end by disabling events by default, or it could be fixed by the IPC user by disabling all events after opening the pipe (with the disable_event command.) By default, all events except for MPV_EVENT_TICK are enabled.

**Comment by drojf** [comment]
I think you could keep the default behavior of outputting all events, if it was more clear in the documentation. For example, just adding something like this to the documentation would make me happy:

----

#### IPC Client Implementation

MPV will occasionally write events to the pipe/socket, even if the client does not issue any commands (such as `{"event":"end-file"} `when a file finishes). If too many events are written by MPV without being read by the client, MPV's write buffer will become full, causing the IPC thread to deadlock. Therefore a minimal IPC client must both read and write from the pipe, even if it discards what it reads. It should also expect to read data at any time, not just after each issued command. 

----

Also, if there is no chance MPV will ever output anything if `{ "command": ["disable_event", "all"] }` is used, you could also add:

> Alternatively, the user can disable MPV from showing events by `{ "command": ["disable_event", "all"] }` . Then a write-only implementation can be used.

I would be hesitant to write that part as a non-mpv developer because I'm imagining some error code or something leaking into the pipe, or a user issuing a 'read' type command by accident (if that's even possible).

----
Of course, if you choose to disable events by default then you wouldn't need the above.

**Comment by rossy** [comment]
Agreed. It might make sense to mention this in the docs. @wm4 opinions?

**Comment by wm4** [comment]
Sure, go ahead.

**Comment by marnunez** [comment]
Thanks everyone for your help. This post helped me to write an AHK script controling mpv with a named pipe under Windows. 

````ahk
mpvConnect(){
   hnd:=DllCall("CreateFile", "str","\\.\pipe\mpvsocket", "int",0x80000000 | 0x40000000,"int", 0, "ptr", 0, "int", 0x3, "int", 0, "ptr", 0, "ptr")
   fn := Func("mpvPurge").bind(hnd)
   SetTimer,%fn%, 200, On
   return hnd
}

mpvPurge(hnd){
   FileOpen(hnd,"h").Read()
}

mpvCommand(command,hnd) {
FileOpen(hnd,"h").Write(command)
}
````
then I can write commands to the pipe like:
````ahk
mpvHnd := mpvConnect()
mpvCommand("set_property video-zoom 1.4`n",mpvHnd)
````

It lacks checks, but it works.

**Comment by acely** [comment]
Run into similar problem.After some searching I found that the pipe can be configured using "O_NONBLOCK" flag, which may prevent it from being full or blocking.

See [https://linux.die.net/man/7/pipe](url)
