### ISSUE TITLE
Problems with command line output.

### ISSUE THREAD

**Issue by mzso** [mpv-player/mpv#3426]
Hi!

In #524 I was instructed to use mpv.com if I want a the CLI output to be visible. 

However that brought up more issues for me. Specifically with the interaction with total commander. Which assumes it's a 16 bit app and sends it a broken command line.

I think a CLI switch is needed to force the cmd window to appear with the output text with mpv.exe

**Comment by lachs0r** [comment]
That’s not possible for technical reasons (which is why mpv.com exists in the first place). Also, that’s a Total Commander bug.

**Comment by rossy** [comment]
I'm not sure how Total Commander is invoking mpv.com, but maybe there's a workaround for this issue.

If you're launching mpv with file associations, you could try running mpv-install.bat from here: https://github.com/rossy/mpv-install

To create associations for mpv.com instead of mpv.exe, replace:
```
set mpv_path=%~dp0mpv.exe
```
with:
```
set mpv_path=%~dp0mpv.com
```

File associations created with mpv-install.bat should never result in mangled command-lines, even if the associations are against a .com file.

If it's not file associations that are the problem, you could also try using a batch file to launch mpv. Try making a ``mpv.bat`` containing something like this:
```
@echo off
mpv.com %*
```
This should launch mpv without mangling the command-line.

**Comment by mzso** [comment]
@rossy 
Thanks. Using a bat file was also recommended on TC's forum as a workaround, since the author decided the what TC does is alright...

Anyway the batch file works alright.

**Comment by garoto** [comment]
OT: I can't see the appeal of Total Commander at all. Almost sure QTTabBar can emulate pretty much all of its features (and more).

**Comment by mzso** [comment]
[**@garoto**](https://github.com/garoto) commented on [2016. aug. 17. 18:01 CEST](https://github.com/mpv-player/mpv/issues/3426#issuecomment-240459601 "2016-08-17T16:01:03Z - Replied by Github Reply Comments"):
> OT: I can't see the appeal of Total Commander at all. Almost sure QTTabBar can emulate pretty much all of its features (and more).

Wow. Boy that's wrong. By the looks of it, it's not even a two pane file manager. Just some explorer enhancer. (BTW TC has many features)
