### ISSUE TITLE
How to select a certain language track out of multiple possible?

### ISSUE THREAD

**Issue by bsto** [mpv-player/mpv#3444]
Assume I load a *.mkv or *.mp4 video file which contains multiple audio language tracks (e.g. english, german, spanish).

How do I select a non-default language track?

Ben

**Comment by rossy** [comment]
Use the # key to cycle through audio tracks. Default key bindings are documented here: https://mpv.io/manual/master/#keyboard-control

You can also specify a language on the command line (``--alang=spa`` for Spanish) or in your config file (``alang=spa,es,eng,en`` to select Spanish if available or English otherwise.)

And you can use the OSC to change audio tracks. Click on the speech-bubble icon to cycle tracks and shift-click it to see a list of all tracks.

**Comment by maliayas** [comment]
> and shift-click it to see a list of all tracks.

I know this is old but, how do I move on that list? Up/Down buttons don't do it (they just seek in the video and ignore the opened list).

**Comment by bhumit070** [comment]
> > and shift-click it to see a list of all tracks.
> 
> I know this is old but, how do I move on that list? Up/Down buttons don't do it (they just seek in the video and ignore the opened list).

Shirt + 3 worked for me
