### ISSUE TITLE
Control+ <+> not working on OSX

### ISSUE THREAD

**Issue by sarkdavidson** [mpv-player/mpv#3450]
### mpv version and platform

latest
### Reproduction steps

`Ctrl + and Ctrl -
Adjust audio delay by +/- 0.1 seconds.`
### Actual behavior

Control - works
Control + wasn't, but unexpeactly, control+shift+<+> works
### Log files

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without log it might not be
possible to analyze and fix certain bugs.
### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by OtoriTakeo** [comment]
I can confirm this, but I do believe this the correct behavior. 

Every QWERTY Keyboard has '+' as secondary output of the character key '='. So in order to invoke a '+', you have to press 'shift' + '='. 
Thus trying to invoke 'control' + '+', you have to press the following key combination: 'control' + 'shift' + '='.

Due to the fact that '-' is the primary output of the character key '-', the use of 'shift' is not needed here. 

In order to streamline inputs, I suggest to remap "Adjust audio delay by +/- 0.1 seconds" to 'control' + '-' (as before) and 'control' + '='.

**Comment by garoto** [comment]
Hmm, interesting. That reminds me why I have a `Ctrl+= add audio-delay 0.050` in my input.conf for quite some time now.

The `#ctrl++ add audio-delay 0.100` line in https://raw.githubusercontent.com/mpv-player/mpv/master/etc/input.conf never worked for me out of the box. I'm on Windows 8.1 (7 previously).

**Comment by Akemi** [comment]
this isn't a bug, that's just how the keyboard bindings work. if you bind a key to a secondary character you obviously have to press the key combination for this.

in the case of QWERTY and "<" and" >", you have to press "SHIFT + ," and "SHIFT + ."
