### ISSUE TITLE
Segmentation fault with mp4 and flv files

### ISSUE THREAD

**Issue by fjordson** [mpv-player/mpv#3463]
### mpv version and platform
0.18.1-1 
Debian Testing

If you're not using git master or the latest release, update.

### Reproduction steps
enter command: mpv [mp4 or flv file] 
double click on .mp4 or flv file

### Expected behavior
It should play the video

### Actual behavior
Video does not play.  I receive a segmentation fault error.

### Log files

http://pastebin.com/D33K2yk8

It's worth noting that I can play .mkv and .webm files.

**Comment by wm4** [comment]
> [cplayer]    libavformat     57.41.100 (runtime 57.25.100)

Broken build, complain to debian.

**Comment by jcowgill** [comment]
@fjordson I've filed this as https://bugs.debian.org/835645. I'm fairly sure it's an ffmpeg packaging bug.

**Comment by wm4** [comment]
The main issue, which you seemed to have overlooked, is that the runtime lib is older than the version mpv was built against. This case is not even supported by upstream FFmpeg (which mistakenly believes FFmpeg ABI compatibility works). This is completely and horrible broken and could have prevented by our own ABI check, which Debian in its infinite wisdom patched out. (The check would have errored out on start with a useful error messages, instead of randomly crashing.)

Also, we don't support old releases anyway.

**Comment by jcowgill** [comment]
I don't think I've overlooked anything, the bug is all about preventing the runtime lib from being older than the build library by ensuring the Debian dependencies are tight enough. The reason why I removed your runtime check is that it doesn't really fix anything (it would still make make mpv unusable), and because doing minor ffmpeg updates in Debian would require rebuilding mpv which is quite annoying and should not be necessary.

**Comment by wm4** [comment]
The Debian bug goes into depth about specific ffmpeg changes.

This is wrong.

In no situation or circumstances must the runtime version be lower than the compile time one.

**Comment by jcowgill** [comment]
Well in the end that is what's going to happen (ie Debian dependencies will gaurentee the runtime lib is >= the build lib). In theory we could have done more fine grained dependencies but it didn't work out because it requires lots of effort to maintain the symbols files and check ABI changes etc. This particular bug was caused by missing various ABI changes.

Anyway I think it's all fixed now, and should be for the future.
