### ISSUE TITLE
Expose sub-speed as an adjustable property

### ISSUE THREAD

**Issue by CyberShadow** [mpv-player/mpv#3516]
Would be nice to expose `sub-speed` in the same way as `sub-delay`, so it's possible to adjust it during playback.

I've [taken a stab](https://dump.thecybershadow.net/4602537d26df5e55b56c6e1cda096b64/10%3A13%3A05-stdin.txt) at it, but it seems that `sub-speed` is taken into account in very different ways than `sub-delay` (at least, the two variables are used in completely different files, never together).

**Comment by wm4** [comment]
As of git master (since a week ago or so), all options are already mapped as properties. However, in this case you need to make sd_ass.c re-read the value from the options.  This means you'd have to make it call `update_subtitle_speed` after the option has been set. A new `SD_CTRL_` could probably be used for this for now. It's trivial, but a bit messy - I can take a look later if you prefer.

**Comment by CyberShadow** [comment]
Thanks, with your advice I think I figured it out. #3519
