### ISSUE TITLE
mpv failing to play directories on macOS Sierra

### ISSUE THREAD

**Issue by JaKXz** [mpv-player/mpv#3530]
### mpv version and platform

mpv 0.20.0 installed via Homebrew *edit:* with the `--with-bundle` flag enabled.

### Reproduction steps
```
cd ~/folder/with/videos
mpv .
```

### Expected behavior
On El Capitan, this worked fine, and you could even pass `--shuffle` to go through the videos randomly.

### Actual behavior
`mpv` hangs and never plays the videos.

### Log files

https://gist.github.com/anonymous/0c75db6fd8b1429236d8e4532b487020

**Comment by Forcer78** [comment]
The hang is because the `poll()` in stream_file.c's `fill_buffer()` is blocking forever when it is eventually called from `demux_open()`. `poll()` is watching two file descriptors, the played directory and a cancel pipe. If the call is temporarily modified to only wait on the first descriptor, execution will continue.

_Why_ `poll()` is failing when called with both descriptors is a mystery to me at the moment.

**Comment by wm4** [comment]
Does this still fail with the "official" OSX Sierra?

**Comment by maletor** [comment]
Yup.

**Comment by Argon-** [comment]
> Why poll() is failing when called with both descriptors is a mystery to me at the moment.

Even though it's a different problem, poll() seems to have more problems on 10.12: https://daniel.haxx.se/blog/2016/10/11/poll-on-mac-10-12-is-broken/
