### ISSUE TITLE
No video with git master on macOS

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#3627]
### mpv version and platform
git-e629169
macOS Sierra 10.12

### Reproduction steps
Open any video file.

### Expected behavior
The video plays.

### Actual behavior
The player windows is just all black in windowed mode, all white in fullscreen. The audio plays normally, and the OSC seems to work even if it's actually invisible. Using --opengl-early-flush=yes everything works fine.

P.S. I once tested the no-flush branch and this issue didn't show up. Maybe it's due to the combination between no flush and the recent changes regarding macOS?

### Log files
http://sprunge.us/DNbJ

**Comment by wm4** [comment]
That's definitely very unexpected...

**Comment by wm4** [comment]
CC @Akemi

**Comment by Akemi** [comment]
yep i encountered the same behaviour in my test when i tried to find the fullscreen regression. when not using kCGLPFADoubleBuffer the flush call is needed. i don't have any experience with opengl but if i would guess it's probably because CGLFlushDrawable (tbh i have no idea what it actually does and the apple docs are kinda vague) is actually only swapping the buffers and not flushing without kCGLPFADoubleBuffer, it might not do anything at all without kCGLPFADoubleBuffer. i believe we could just add a flushBuffer call on the NSOpenGLContext in its place.

**Comment by Hamuko** [comment]
I get the same issue with `git-e629169` on Sierra (10.12) with the exception that `--opengl-early-flush=yes` does nothing for me.

**Comment by Akemi** [comment]
@Hamuko I am wondering does 9f30cd8292b4b7bfe5d7db29fe31a07cc76dec2c work for you and if not does f0ab9f05f1709ccda63e7e695031e1030dee6626 work?

**Comment by Hamuko** [comment]
9f30cd8292b4b7bfe5d7db29fe31a07cc76dec2c seems to work fine.

I noticed that while `--opengl-early-flush=yes` doesn't work, `--opengl-early-flush=yes --profile=opengl-hq` works. I'm currently only running Sierra on my old early-2011 MacBook Pro, so I use toaster settings.

**Comment by vitorgalvao** [comment]
Can confirm this also happens on El Capitan, it isn’t Sierra-specific.

**Comment by bersrkr** [comment]
Using `--opengl-early-flush=yes` also makes the system overlays flicker when fading out on macOS Sierra

**Comment by Akemi** [comment]
the flickering overlay is a separate issue, so feel free to open another issue for it. though i don't think we can fix that atm. i also can't reproduce it here on intel and nvidia gpu.
