### ISSUE TITLE
Frame skipping whenever you switch audio? [maybe a bug]

### ISSUE THREAD

**Issue by dragons4life** [mpv-player/mpv#3648]
### mpv version and platform

Latest sourceforge
### Reproduction steps

Audio switch script - https://9.lithi.io/Jzx4C.lua
### Expected behavior

No frame skipping while switching the audio output?
### Log files

Does it happen without display-resync/interpolation? Yes.
https://7.lithi.io/tdXOU.txt
### Sample files

https://2.lithi.io/HxRVW.webm
https://7.lithi.io/4KwIF.conf - conf

Now I am not saying I am gonna be a madman and switch the audio like in the video sample, I am just reporting it because I think this is a bug.

**Comment by wm4** [comment]
That seems like a bug.

**Comment by haasn** [comment]
> Does it happen without display-resync/interpolation? Yes.

For stuffl ike this, it's usually a good idea to also test with `--video-sync=display-desync`, because that mode almost completely isolates audio from video. Also, if you could record a stats dump of it happening (`--dump-stats=FILENAME`), it would potentially allow for a much easier examination than the log file.

**Comment by wm4** [comment]
Oh, it's about audio-device, not the audio track. I don't have too much interest in changing this, then.

**Comment by Dudemanguy** [comment]
Wasn't able to reproduce (I think?). Please open a new issue if this is still a bug.
