### ISSUE TITLE
Trouble applying video filters

### ISSUE THREAD

**Issue by tsoernes** [mpv-player/mpv#3656]
mpv 0.14.0 on Linux Mint X64

I'm trying to run with
-vf=vdpaupp=temporal-spatial:hqscaling=9
but I get errors.

Another question: is this the best possible setting for Nvidia on linux with regards to quality?
Log attached 

[mpv log.txt](https://github.com/mpv-player/mpv/files/523223/mpv.log.txt)

**Comment by qmega** [comment]
Your log makes it look like you're using a frontend. If that's the case, it probably be helpful if you explained that. Also the log looks very incomplete. Add `-v` at least.

But AFAIK, vdpau's hqscaling option is an algorithm, not a quality level, and only 1 is defined / implemented. They're just leaving it open so they can implement other ones, I guess, but no currently existing GPU / driver knows anything other than 1. It's not clear to me from your log if that's the issue or not, but it might be. Try with `hqscaling=1`. Also it should be `deint-mode=temporal-spatial`, not just "temporal-spatial" by itself.

**Comment by tsoernes** [comment]
I use the newest SMPlayer as frontend.

Strange thing: If I add the -v flag (either manually or by ticking 'verbose' in Logs in SMPlayer), the video disappears and only sound is playing. 

In any case, I attached two logs:
one with corrected -vf settings and no -v, which seem to be working,
[mpv log.txt](https://github.com/mpv-player/mpv/files/523406/mpv.log.txt)
and one log with the -v flag (no video).
[mpv log v.txt](https://github.com/mpv-player/mpv/files/523407/mpv.log.v.txt)

Does hqscaling only with when deinterlacing? Am I right that most videos (eg torrent movies) are not interlaced, and so deinterlacing should not be used?  What other settings can I apply to MPV for best quality?

**Comment by qmega** [comment]
It may be that smplayer breaks with -v because it doesn't get the output it's expecting. One of the problems with parsing command line output intended for humans. If you're not particularly attached to smplayer, I'd suggest trying some alternatives. There are some better ones these days using mpv's client API. Someone else will have to tell you about those because I just use bare mpv. I think there's some info on the wiki here, though.

> Does hqscaling only with when deinterlacing?

No, it should be active regardless of deinterlacing. And yeah, interlacing isn't very common these days. Depends on whether you're watching old stuff, I guess? Do you know what interlacing looks like? It's generally pretty obvious when watching if something is interlaced or not.

> What other settings can I apply to MPV for best quality?

Start with `--vo=opengl --profile=opengl-hq`. Or with your version, I guess it'd be `--vo=opengl-hq`. And then go from there if you want, customizing scaler or adding temporal interpolation for example. You could look at the video-sync modes too. But you'll have to read the manual for that stuff.

Also, your version of mpv is pretty old. You'll get a lot better support here if you use a more recent version, and of course the program has improved.

**Comment by wm4** [comment]
Too old version, so I'll just assume it was somehow resolved rather than reading all that text. Reopen if you disagree.
