### ISSUE TITLE
Feature request: please add preset "opengl-veryhq"

### ISSUE THREAD

**Issue by eeehhh** [mpv-player/mpv#3659]
Hello!
Please add  a preset "opengl-veryhq" or "opengl-hq2" or something like that. Opengl-hq is very nice, but with more powerful computers we newbies that need presets could use something that is more resource demanding.

**Comment by Cpuroast** [comment]
Feel free to use the following
vo=opengl-hq:scale=ewa_lanczossharp:cscale=ewa_lanczossharp

Should be much harder on your GPU and it should be better quality than the stock opengl-hq preset.

I doubt an opengl-vhq profile will ever be made, because after spline36 used in opengl-hq, the scaler quality becomes quite subjective.

**Comment by wm4** [comment]
Depends on @haasn whether we implement this or go WONTFIX.

**Comment by haasn** [comment]
I don't know what I would add to `opengl-vhq` that isn't already covered by `opengl-hq` these days.

The only thing that comes to mind is the `scale` settings, and it's hardly worth making an entire profile just for one or two settings.

**Comment by lachs0r** [comment]
Agreed. Also, IMO users who are not satisfied with `opengl-hq` tend to have very specific preferences anyway, so WONTFIX here as well.
