### ISSUE TITLE
The menu bar in mpv 0.21

### ISSUE THREAD

**Issue by IlyaIndigo** [mpv-player/mpv#3715]
mpv 0.21 openSUSE Tumbleweed (hwdec=no, vo=xv, nouveau, KDE4)

The menu bar is not attached to the bottom of the screen, and to the bottom of the video stream.
The problem is not visible in a window, as the window size is automatically adjusted to the size of the video stream, or when playing DVD / BR, where the black bars are part of the stream.
The problem appears when playing DVD-Rip / BR-Rip full screen big screen (2.35:1), which, it turns out that the menu bar is not at the very bottom of the screen, and is attached to the bottom of the video.
![mpv](https://cloud.githubusercontent.com/assets/2612812/19630773/012868a2-999a-11e6-9030-2efe2d131cef.png)

**Comment by lachs0r** [comment]
This problem is inherent to the xv output. While there are workarounds like using the expand filter, I strongly recommend using opengl or vdpau instead. Both should work with nouveau. If not then I suggest installing NVIDIA’s proprietary drivers. The xv driver should only be used if nothing else works.

**Comment by wm4** [comment]
And we won't add a hack just so you can use mpv with a 20 year old API.
