### ISSUE TITLE
mpv crashing xterm

### ISSUE THREAD

**Issue by compassnet** [mpv-player/mpv#3726]
### mpv version and platform

mpv git-082340b on Slackware Linux 14.2 64bit.
### Reproduction steps

Open xterm.
$ mpv
### Expected behavior

mpv should not alter xterm settings on exit.
### Actual behavior

All xterm keyboard output is registered but not displayed (use "reset" or "stty sane" to restore screen output).
On playback this issue doesn't happen.
### Log file

http://pastebin.ca/3732902

**Comment by yzisyz** [comment]
I met the same issue on ubuntu-mate 16.04.1, mpv 0.21

I also did some initial analysis, this issue seems a timing sequence issue. A wrong function enable_kx in osdep/terminal-unix.c calling sequence cause this issue. If we run "mpv" with any argument such as "mpv -h or mpv somefile.mkv" , the calling sequence will be **enable_kx(true)** then **enable_kx(false)**; but if we run "mpv" without any argument, the calling sequence will be **enable_kx(false)** then **enable_kx(true)**. 

I didn't find out what cause the different. But I found a simple work-around solution to fix this issue: 
modify function terminal_uninit in osdep/terminal-unix.c , move up the following line:
   read_terminal = false;
make sure this statement before calling pthread_join.

I pasted my modification for your reference.
[mpv-linux-terminal-issue-fix.diff.txt](https://github.com/mpv-player/mpv/files/559015/mpv-linux-terminal-issue-fix.diff.txt)

**Comment by compassnet** [comment]
As of mpv 0.25.0-44-ge2b9551 this issue no longer exists.

Thanks development team!

Compass.

**Comment by compassnet** [comment]
I spoke too soon. The issue remains.

At the console this issue doesn't happen, but with xterm/rxvt it does occur.

Compass.

**Comment by lachs0r** [comment]
Can’t reproduce.
