### ISSUE TITLE
Is it possible to take screenshots from the command line?

### ISSUE THREAD

**Issue by for-coursera** [mpv-player/mpv#3735]
As I see from the manual, the answer is No :) But may be I'm missing something? Something like `mpv ./file.mp4 --take-screenshot --screenshot-time=540 --quit` would be perfect.

Ideally would be the possibility to take a screenshot every %H:%M:%S but that can be wrapped in a shell script, I presume...

**Comment by Hamuko** [comment]
`ffmpeg -ss 540 -i file.mp4 -vframes 1 out.png`

**Comment by for-coursera** [comment]
Thanks!

**Comment by lachs0r** [comment]
`mpv file.mp4 --start=540 --frames=1 -o out.png`
Note that `--start` also takes a percentage in case you want to use it like that.

Or, to take a screenshot every 60 seconds:
`mpv file.mp4 --no-audio '--vf=lavfi=[fps=1/60]' -o out%04d.png`

Similar things should work with ffmpeg.

**Comment by for-coursera** [comment]
Brilliant, thank you!

**Comment by wm4** [comment]
Or just use --vo=image?

**Comment by garoto** [comment]
Damn, both lachs0r's and wm4's tips/suggestions are great. I'm sure to bookmark this issue for future reference. Wiki material perhaps?

**Comment by Gfurst** [comment]
Just wanted to say, I could see improving the screenshot to be pretty useful, specifically, using its naming pattern thingy, since neither image output or ffmpeg have it. I've came up with a little function to take comparison screenshots:
```sh
function mpv-shot () {
	for time in 22 44 66 88; do 
		for video in $*; do
			mpv $video --quiet --aid=no --sid=no --frames=1 --start=$time% --o=$time\_$video.png
		done
	done
}
```
While this does works, it has some downfalls, for example files can't be nested in a sub-folder, otherwise naming gets forbidden `/` character. Previously I was just using image output and passing multiple files to mpv, but again this is a more time consuming method and doesn't have proper naming.
```sh
function mpv-shot () {
	mpv --quiet --vo=image --aid=no --frames=1 --start=$1 $2 $3 $4 $5 $6 $7 $8 $9
}
```
So I would to suggest, either the screenshot at time function, or to enable name formatting for image output, as something that could be pretty useful.

**Comment by haasn** [comment]
@Gfurst Use `--input-ipc-server`

See [this example](https://github.com/haasn/mpv-unit)

**Comment by Gfurst** [comment]
Excuse me, but I didn't quite understood what you suggested.

**Comment by Akemi** [comment]
you can read more about it [here](https://mpv.io/manual/master/#json-ipc). also [another](https://github.com/Akemi/mpv-scaler-test) example were it actually takes screenshots. to be more specific with the JSON IPC you can tell mpv to jump to a given time and make a regular screenshot. that way you can just use the screenshot template. the way screenshots are taken in in the linked example is actually better than via `vo=image` or `-o`, since it actually takes advantage of the our gpu backend's scaling, color conversion etc. for comparison that should be rather essential.

**Comment by palacinka** [comment]
lachs0r advice works as described, but would it be possible to pass multiple seek positions in the future?
like --start=10%,20%,30%,40%
That would be really helpful and useful.  

Right now I need to run mpv multiple times to achieve this since I need fast seek times without wasting time and  network bandwidth

**Comment by DeadNews** [comment]
> @Gfurst Use `--input-ipc-server`
> 
> See [this example](https://github.com/haasn/mpv-unit)

In the above example, the mpv window opens when each new file is opened.
Can JSON IPC work without opening the mpv window (fully in command-line mode)?

**Comment by snowman** [comment]
what's the difference between option `-o` and `--o`?

In [mpv reference manual](https://mpv.io/manual/stable/), I can't find the option `-o` except `--o`

```
Encoding
You can encode files from one format/codec to another using this facility.

--o=<filename>

  Enables encoding mode and specifies the output file name.

--of=<format>

  Specifies the output format
  (overrides autodetection by the file name extension of the file specified by -o).
  See --of=help for a full list of supported formats.
```

1. In the document, `--of=` overrides file format specified by option `-o`
   isn't `--o`?
2. should I change this in latest version mpv, use `--o` instead?
   > `mpv file.mp4 --start=540 --frames=1 -o out.png`
