### ISSUE TITLE
Weird performance with ANGLE (and some stats for d3d11va-copy, dxva2, dxva2-copy with dxinterop)

### ISSUE THREAD

**Issue by xnoreq** [mpv-player/mpv#3744]
mpv git-90b968a
on Windows 10, 64-bit with an older AMD HD7000 series graphics card

I have tested a video with the follow format:
x264 encoded High@L4.1, bit rate 11.5 Mbps, 23.976 fps, yuv 4:2:0, 8 bits, 1920x1080p

Config:
opengl-hq
video-sync=display-resample
interpolation
# display-fps=60 (resulting in a VSync Ratio of 2.5)

To display the stats I used [stats.lua.](https://github.com/Argon-/mpv-stats/blob/master/stats.lua)
### d3d11va-copy + ANGLE

Render: 7250 us
Present: **16600** us
Upload: 1880 us
VSync Jitter: **0.315**
### d3d11va-copy + ANGLE + opengl-dcomposition=no

Render: 7250 us
Present: **340** us
Upload: 1880 us
Jitter: **0.005**

So DirectComposition (on by _default_) completely destroys the performance ... at least on my system.
### d3d11va + ANGLE  + opengl-dcomposition=no

Broken, e.g. see #3255, but still:
Render: 7700 us
Present: 340 us
Upload: 0 us with a 16k peak every ~2 seconds
Jitter: 0.005
### dxva2 + ANGLE + opengl-dcomposition=no

Render: 1240 us
Present: 440 us
Upload: 0 us
Jitter: 0.005

Nice, except that seeks take a longer time and the video is jerky for a moment after a seek. This is especially noticeable when dragging the seekbar. Also, with ANGLE there's still this annoying white flashing of some part of the window when going into/leaving fullscreen mode.
### dxva2 + dxinterop

Render: 1240 us
Present: 440 us
Upload: **5200** us
Jitter: 0.005

Why are 5ms spent on uploading here? Other than that dxinterop gives the best experience. No window flashing when going fullscreen, fast and clean seeks.
### dxva2-copy + dxinterop

Render: **5140** us
Present: 320 us
Upload: **320** us
Jitter: 0.005

I'm not sure what's going on here, but overall performance seems better with dxva2-copy than dxva2? (Assuming that the stats are actually correct.)

**Comment by rossy** [comment]
Maybe we really should switch DirectComposition off by default. It improves performance and reduces jitter for me, but it seems like it makes things worse for a lot of people (or just for older AMD cards?) I don't mind if it's off by default as long as there's an option for me to switch it back on.

**Comment by igv** [comment]
Can confirm, works better for me too with opengl-dcomposition=no.

**Comment by xnoreq** [comment]
@rossy What is that improvement in numbers, if I may ask?

I don't think optimizations that can totally ruin performance should be enabled by default.

**Comment by rossy** [comment]
@xnoreq It's like this for me (config: ``--no-config --profile=opengl-hq --video-sync=display-resample --fs``):

**--opengl-dcomposition=yes**

upload-last=962
upload-avg=993
upload-peak=1112
render-last=3785
render-avg=3813
render-peak=5595
present-last=1260
present-avg=1260
present-peak=1456
vsync-jitter=0.014

**--opengl-dcomposition=no**

upload-last=14594
upload-avg=9437
upload-peak=15263
render-last=3787
render-avg=7716
**render-peak=16337**
present-last=1257
present-avg=1368
present-peak=11094
vsync-jitter=0.012

Actually, vsync-jitter wasn't very different between the two of them (both hovered around 0.014 during playback.) Those huge peak rendering times are the problem for me. It's not so noticable with ``--profile-opengl-hq``, but if I add ``--scale=ewa_lanczos``, it will start noticably dropping frames with ``--opengl-dcomposition=no``.

That said, I'm still leaning towards setting opengl-dcomposition=no by default, since I think your case, where it ruins performance, is more common than my case where it actually improves it. If I had to guess why it was working badly for me, I think it's because ANGLE uses a relatively short swapchain length, so when running without flip-mode present, it will spend too much time synchronising with the DWM.

I also think it's strange that opengl-dcomposition is causing problems for so many people. In theory, it should be more efficient, since it avoids a full-screen copy of the video image. Also, all DX12 and UWP apps must use flip-mode present, so you'd think Microsoft and driver devs would have ironed out any bugs. Only DX11 desktop apps like mpv get to use legacy presentation modes (with opengl-dcomposition=no.)

**Comment by xnoreq** [comment]
I don't understand why your render times would change at all when just switching dcomposition on/off.

**Comment by rossy** [comment]
Me neither, but they do. Like I said, it's noticeable when using ``--scale=ewa_lanczos``. Whether it performs well without glitches depends on whether opengl-dcomposition is on or off.

**Comment by haasn** [comment]
Vaulues of ~16ms are usually a pretty good indicator of some sort of “block until next vsync”-type behavior

Btw, instead of posting these graphs it can also really help to post a stats dump (`--dump-stats=FILE`)

**Comment by kevmitch** [comment]
See #3194 for more discussion on direct composition from a few months back. On Intel at the time, I found it allowed me to use angle with `display-resample` on a 24hz TV, which was otherwise problematic. I also found that direct composition improved power performance. I'll have to repeat some experiments to see if things have changed since then.

I'm pretty sure the long upload time for **dxva2 -> dxinterop** looks is spent  in `video/out/opengl/hwdec_dxva2gldx.c:map_image`. It's not only "uploading". There's a StretchRect disorderly colour conversion going on in there and the `glDXUnlockObjectsNV` / `glDXLockObjectsNV` should force it to finish before the function exits.

I'm a little surprised you aren't seeing the same thing with **dxva2 -> angle**. It should also wait for the StretchRect to complete, and it may take up to 8ms to execute the same thing before it times out.

Note, neither of these options should be used if you care about video quality and colour accuracy. On the other hand, they probably use less power during playback. Last time I measured **dxva2 -> angle** (direct composition) was a tiny bit more power efficient than **dxva2 -> dxinterop** . Without direct composition ANGLEs power use shot up drastically.

**Comment by xnoreq** [comment]
Dcomposition just doesn't work for me. In window mode jitter is better but still multiple times that of dx, present times jump wildly from 7-8k to 16k. In fullscreen mode jitter goes up to .3 and present still jump but at a slightly higher average (~12.8k).

I can create dump-stats for any combinations if anyone is interested and can make use of them.

**Comment by xnoreq** [comment]
Any ideas how I could debug Dcomposition to find out why it doesn't work on my system?

**Comment by rossy** [comment]
Closing since we on longer support ``--opengl-dcomposition``. ``--angle-flip`` might have a similar effect, but ANGLE is no longer recommended now that the native d3d11 backend exists.
