### ISSUE TITLE
audio-stream-silence works only for short pause

### ISSUE THREAD

**Issue by arvidjaar** [mpv-player/mpv#3754]
### mpv version and platform
0.21.0, Ubuntu 16.04, kernel 4.8.0-25, 
00:1b.0 Audio device [0403]: Intel Corporation Wildcat Point-LP High Definition Audio Controller [8086:9ca0] (rev 03)
	Subsystem: Dell Wildcat Point-LP High Definition Audio Controller [1028:062b]
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

 0 [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xf733c000 irq 52
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7338000 irq 51

### Reproduction steps
Set

audio-stream-silence=yes

Start video playback on HDMI connected TV. Pause playback. Wait several minutes and resume. 

### Expected behavior
There is no silence when playback starts.

### Actual behavior
There is initial silence when playback starts, especially annoying when some dialogue is going on. This does not happen for short pause (several seconds) where audio resumes instantly.

### Log file

https://gist.github.com/arvidjaar/0a06e2394d8e4f76918255f998185631

### Sample files

Any normal video stream

**Comment by wm4** [comment]
> There is no silence when playback starts.

You'd need to combine it with `--audio-wait-open=`. ``--audio-stream-silence`` merely streams silence when no audio is playing, while adding ``--audio-wait-open`` would "prime" the audio device with silence before sending real audio data to it.

Unfortunately, ``--audio-stream-silence`` is not implemented for Pulse, only alsa/wasapi/coreaudio/jack/sdl. ao_alsa implements it by special API usage (makes it stream silence on underflow), so this is not necessarily easy to add to Pulse.

But in general I'd expect Pulse server to handle this, due to its aspiration of "doing the right thing" and managing audio devices directly, rather than leaving it to applications.

**Comment by wm4** [comment]
(Actually looking again you enable ``--audio-wait-open``.)

**Comment by arvidjaar** [comment]
> Unfortunately, `--audio-stream-silence` is not implemented for Pulse

Well, would be helpful if it also said so, at least in verbose mode :) I'll try to raise it up with PA.

**Comment by wm4** [comment]
Well, the manpage says `Not all AOs support this.`.

**Comment by wm4** [comment]
Pushed a change that will cause ao_pulse.c to explicitly play silence as well. Also will probably lead to new problems.

**Comment by arvidjaar** [comment]
Thanks! Will have to wait until next release to test and report.

**Comment by wm4** [comment]
The next release is probably in a few months.

**Comment by arvidjaar** [comment]
I tried mpv at commit 51fd8f6 - as far as I understand it should include this change. It did not help, I still see the same lack of sound after resuming from pause with PA. With ALSA there is no gap.
