### ISSUE TITLE
Yet another 10-bit color question...

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3789]
Hi,

Recenly found this quote:

>  In brief, NVIDIA has traditionally used 10bit+ color support under OpenGL as a feature differentiator between GeForce and Quadro. GeForce cards can use 10bit color with Direct3D, but only Quadro cards supported 10bit color under OpenGL, and professional applications like Photoshop are usually OpenGL based. For Pascal, NVIDIA is opening things up a bit more, but they are still going to keep the most important aspect of that feature differentiation in place. 10bit color is being enabled for fullscreen exclusive OpenGL applications – so your typical OpenGL game would be able to tap into deeper colors and HDR – however 10bit OpenGL windowed support is still limited to the Quadro cards. So professional users will still need Quadro cards for 10bit support in their common applications.
http://www.anandtech.com/show/10325/the-nvidia-geforce-gtx-1080-and-1070-founders-edition-review/12

Is it in any way relevant to mpv's video output? Is mpv (at least, on Linux) _a fullscreen exclusive OpenGL application_? Or these Nvidia's tricks doesn't matter at all?

Regards,

**Comment by lachs0r** [comment]
Doesn’t matter on Linux. NVIDIA simply enabled it for all GeForce 8 and newer GPUs in 2012, windowed applications or not. In fact, Xorg running with Depth 30 doesn’t even expose visuals with lower bit depth, as far as I recall. There were problems with more recent cards because they didn’t expose the full LUT depth in the driver, but that’s been fixed. This can be verified with a simple OpenGL application (should produce a smooth gradient): http://sprunge.us/PQAX

**Comment by haasn** [comment]
There's no such thing as a “fullscreen exclusive mode” on Linux. There's not even such a thing as “fullscreen” on Linux. Every windows is simply a window, and a fullscreen window is just one that your WM decides to resize to the dimensions of your screen.
