### ISSUE TITLE
Is there any way to play movies with virtual surround sound on a headset?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#3885]
### mpv version and platform

```
mpv 0.21.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Wed Nov  2 00:00:15 UTC 2016
ffmpeg library versions:
   libavutil       55.35.100
   libavcodec      57.65.100
   libavformat     57.57.100
   libswscale      4.3.100
   libavfilter     6.66.100
   libswresample   2.4.100
ffmpeg version: 3.2.git
```

Is there any way to play it like how Razer Surround Sound does?

**Comment by lachs0r** [comment]
No idea what exactly that does but you can use the [`sofalizer`](https://ffmpeg.org/ffmpeg-filters.html#sofalizer) filter [through libavfilter](https://mpv.io/manual/master/#audio-filters-lavfi). I recommend using one of the [ClubFritz files](https://www.sofaconventions.org/data/database/clubfritz/) with it.

**Comment by JulianLai** [comment]
What is the difference between ClubFritz1.sofa ~ClubFritz12.sofa?

**Comment by JulianLai** [comment]
@lachs0r 
```
Error parsing option sofalizer (option not found)
Option af: Error while parsing lavfi parameter sofalizer (sofa)
Error parsing option af (option could not be parsed)
/home/laichiaheng/.config/mpv/mpv.conf:9: setting option af='lavfi:sofalizer=sofa=/home/laichiaheng/.config/mpv/ClubFritz6.sofa:type=freq:radius=1' failed.
```

What does it mean?

**Comment by lachs0r** [comment]
It means you didn’t understand what the manual says.

af=lavfi=[sofalizer=optiona:optionb]

**Comment by JulianLai** [comment]
@lachs0r 
af=lavfi=[sofalizer=sofa=/home/laichiaheng/.config/mpv/ClubFritz6.sofa:type=freq:radius=1]
```
[ffmpeg] No such filter: 'sofalizer'
[lavfi] Can't configure libavfilter graph.
Reinitialization did not work, audio filter 'lavfi' returned error code -2
Audio filter chain:
  [in] 48000Hz 5.1(side) 6ch s32
  [lavfi] 0Hz empty 0ch ?? <-
  [out] 0Hz empty 0ch ??
  [ao] 0Hz empty 0ch ??
Could not create audio filter chain.
Error at audio filter chain pre-init!

```

**Comment by lachs0r** [comment]
According to the documentation I just linked, FFmpeg needs to be built with `--enable-netcdf`.

**Comment by richardpl** [comment]
From another user, he reported 4 is balanced, 6 have more bass and 12 if you want more treble.
Note that 6 is slower because its not optimized case off fft processing, very big fft window.

**Comment by kevmitch** [comment]
presumably their properties are described in this [paywalled paper](http://ieeexplore.ieee.org/document/7031925/?reload=true)

**Comment by Argon-** [comment]
I'm not sure if they are described as you might expect it. Additionally, there is no explicitly stated mapping from their descriptions to a number of the 12 files. Quotes:

---
The “Club Fritz” database HRTFs have been converted to the open standard SOFA file format for HRTFs to enable ease of data navigation. 12 HRTF sets were selected from the full database according to the following criteria:
* a) existence of measurement positions within the range of +-30° in elevation,
* b) minimum azimuthal resolution within the above men- tioned range of <= 15°, and
* c) existence of measurements on the horizontal plane.

Table I offers an overview of the selected contributions.
![screen shot 2016-12-12 at 14 30 33](https://cloud.githubusercontent.com/assets/540920/21101060/a5059fd6-c077-11e6-8417-a28747027c7c.png)

“Club Fritz” is an on-going project for HRTF measurement system comparisons containing over 60 datasets from 14 research labs around the world. The uniqueness of this collection lies in that by controlling for several variables like head geometry and binaural microphone type and placement, emphasis in the analysis can be given to differences due to factors particular to every participating institution. The current study offers a global comparison of a subset from the “Club Fritz” database consisting of 12 KU-100 HRTF datasets from 10 laboratories. Only the built-in microphone responses were considered in an attempt to focus on inter-database variations independent of microphone-related variations. The analysis focused on spectral and interaural time difference comparisons as well as left/right symmetry assessments between datasets.  
The spectral variation overview between the 12 HRTF datasets was based on the two common points measured across all institutions: 0° and 180° azimuth on the horizontal plane. The results were compared to two HRTF subsets measured in the same physical space over the span of a week and 10 years.

---

Maybe some of the references contain what you desire, dunno.

**Comment by JulianLai** [comment]
What are the short names of these channels?
FR (front right), FL (front left), RR (rear right), RL (rear left), how about the others? Front Left Height? Left Surround?

**Comment by richardpl** [comment]
See http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavutil/channel_layout.c

**Comment by JulianLai** [comment]
@richardpl I can't find RR in the channel names, but it appears in FFmpeg's example.

**Comment by richardpl** [comment]
It is BR and BL...
