### ISSUE TITLE
Create an option to make osd fixed size (disable scaling)

### ISSUE THREAD

**Issue by oakkitten** [mpv-player/mpv#393]
At the moment, sometimes text is either too small when the window is small or too big when the window is big, or even both.

**Comment by felagund** [comment]
Though it would be really nice for subtitles too.

**Comment by haasn** [comment]
Update from 2 years later: The codepath already used by ``blend-subs`` would make it pretty easy to simply render subtitles at their native resolution (and draw them 1:1), although that means stuff like softsubbed signs would be in wrong places, and subtitles would also not be capable of filling the entire screen width.

**Comment by wm4** [comment]
>Though it would be really nice for subtitles too.

I think there's something similar for subtitles.

**Comment by felagund** [comment]
Yes, apparently, either sub-scale-by-window or sub-scale-with-window was added in the meantime. Although this: ```This option is misnamed. The difference to the confusingly similar sounding option --sub-scale-by-window is that --sub-scale-with-window still scales with the approximate window size, while the other option disables this scaling.``` in the manual is pretty puzzling, I mean, why not rename the function if it is misleading? I read it twice and I am still not sure what the difference is.

**Comment by wm4** [comment]
Because then you have compatibility issues, and everyone would be even more confused. (Also a good examplem why one shouldn't try to add every possible feature that was requested.)

So ``--sub-scale-with-window`` scales the text to the window size, instead of the visible size of the video. This makes a difference only if there are black borders due to aspect ratio mismatch.

``--sub-scale-by-window=no`` tries to keep always the same text size.

**Comment by felagund** [comment]
SUre, I understand, but one of the points of MPV was to clean up mplayers options, no:-)?

**Comment by wm4** [comment]
Yes, and now we have the same problem.

Suggestions welcome. A new set of options with different names would be preferable. There are a lot of subtitle options which could use some naming cleanup, though.

**Comment by felagund** [comment]
1)Well, first, in the man page, it would make sense to group `--sub-text-font-size=<size>` and !--sub-text-font=<pattern>`  with subtitle options, not with OSD (it took me a lot of time to find out how to set the subtitle font size, I did not expect it to find under OSD. The many more options there should be moved to subtitles section too. If somebody wants the osd and subtitles behave the same way, a swtich [new option, yay!] could be introduced like `osd-sub-keep-same` with values osd/sub/no, default not, and osd would mean corresponding options for osd would take precedence and sub would mean corresponding sub options would take precedence if both were present in the config).

2)Second, I think `sub-scale-by-window=no` should make the setting of `sub-scale-with-window` irrelevant, especially if it were renamed as per my suggestion below. This is actually a bug, because the documentation says that changing the window size with this disabled wont change the subtitle size, which is not true when the second option is enabled (docs are true when the window is resized horizontally, but sub size changes when the window is resized vertically).

3) For  `sub-scale-by-window`, I would go along something like `sub-keep-size` (or `sub-keep-size-on-window-resize` if you wanted to be eloquent). - I am not sure if there is a system to option so that "font" and "text" should be added to the options name.

For `sub-scale-with-window`, I would go for `sub-keep-vertical-proportion-to-video` or `sub-scale-with-video`, and I would switch the meaning of yes and no (no would do what yes now does). Because this is what turning this off means - the subtitles always take the same portion of the vertical space of the video regardless of its horizontal dimension. This actually might make sense for people who do not want to have the subtitles in the black margin below video but instead prefer subtitles in the video.

(btw: I might not be super smart, but it took me an hour of experimenting to find out how the options worked together - the bug I discovered puzzled me for a while - and thinking of how to make this clear and writing this took me an hour, so I hope it is good for something)
