### ISSUE TITLE
Broken audio/video sync with ALSA 1.1.3

### ISSUE THREAD

**Issue by bucaneer** [mpv-player/mpv#3938]
### mpv version and platform

```
mpv git-1c761bd6f5 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Dec 24 13:36:35 EET 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2
```

### Reproduction steps

Upgrade ALSA to version 1.1.3 and watch any video with sound using `--ao=alsa`.

### Expected behavior

Normal smooth playback, as with ALSA versions <= 1.1.2.

### Actual behavior

Completely broken playback as audio plays normally while video runs at ~1 fps and mpv complains of desync. If playing an audio-only file, there is a noticeable delay (at least 0.5s) in audio pausing after issuing a pause command.

### Log file

Playing a video for a few seconds:
With ALSA 1.1.2:
```
$ mpv --no-config --ao=alsa --msg-level=ao=v dot.mp4 
Playing: dot.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
[lavf] Edit lists are not correctly supported (FFmpeg issue).
[ao] Trying audio driver 'alsa'
[ao/alsa] requested format: 48000 Hz, stereo channels, floatp
[ao/alsa] using ALSA version: 1.1.2
[ao/alsa] opening device 'default'
[ao/alsa] trying format float
[ao/alsa] Going to set final HW params:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  FLOAT_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: 32
[ao/alsa] FRAME_BITS: 64
[ao/alsa] CHANNELS: 2
[ao/alsa] RATE: 48000
[ao/alsa] PERIOD_TIME: 85000
[ao/alsa] PERIOD_SIZE: 4080
[ao/alsa] PERIOD_BYTES: 32640
[ao/alsa] PERIODS: 3
[ao/alsa] BUFFER_TIME: 255000
[ao/alsa] BUFFER_SIZE: 12240
[ao/alsa] BUFFER_BYTES: 97920
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] channel map reported by ALSA: FL FR
[ao/alsa] which we understand as: stereo
[ao/alsa] which is what we requested.
[ao/alsa] hw pausing supported: no
[ao/alsa] buffersize: 12240 samples
[ao/alsa] period size: 4080 samples
[ao/alsa] device buffer: 12240 samples.
[ao/alsa] using soft-buffer of 12240 samples.
AO: [alsa] 48000Hz stereo 2ch float
VO: [opengl] 1920x1080 yuv420p
AV: 00:00:02 / 00:01:40 (2%) A-V: -0.000


Exiting... (Quit)
[ao/alsa] draining...
```

With ALSA 1.1.3:
```
$ mpv --no-config --ao=alsa --msg-level=ao=v dot.mp4 
Playing: dot.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
[lavf] Edit lists are not correctly supported (FFmpeg issue).
[ao] Trying audio driver 'alsa'
[ao/alsa] requested format: 48000 Hz, stereo channels, floatp
[ao/alsa] using ALSA version: 1.1.3
[ao/alsa] opening device 'default'
[ao/alsa] trying format float
[ao/alsa] Going to set final HW params:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  FLOAT_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: 32
[ao/alsa] FRAME_BITS: 64
[ao/alsa] CHANNELS: 2
[ao/alsa] RATE: 48000
[ao/alsa] PERIOD_TIME: 85000
[ao/alsa] PERIOD_SIZE: 4080
[ao/alsa] PERIOD_BYTES: 32640
[ao/alsa] PERIODS: 3
[ao/alsa] BUFFER_TIME: 255000
[ao/alsa] BUFFER_SIZE: 12240
[ao/alsa] BUFFER_BYTES: 97920
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] channel map reported by ALSA: FL FR
[ao/alsa] which we understand as: stereo
[ao/alsa] which is what we requested.
[ao/alsa] hw pausing supported: no
[ao/alsa] buffersize: 12240 samples
[ao/alsa] period size: 4080 samples
[ao/alsa] device buffer: 12240 samples.
[ao/alsa] using soft-buffer of 12240 samples.
AO: [alsa] 48000Hz stereo 2ch float
VO: [opengl] 1920x1080 yuv420p

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:00 / 00:01:40 (0%) A-V:  3.067


Exiting... (Quit)
[ao/alsa] draining...
```

### Notes

No regression is seen with VLC (2.2.4) set to ALSA output, so presumably not (entirely) an ALSA bug.

**Comment by lachs0r** [comment]
Cannot reproduce this on openSUSE. It currently has 1.1.2 in the repos but backported most of the changes from 1.1.3 before it got released. Just in case, I’ve also built a 1.1.3 package to test, but I have not been able to reproduce it with that. There’s nothing in the ALSA changelog that looks suspicious either.

**Comment by bucaneer** [comment]
I'm using Arch, and it provides a vanilla build of the package: see the [build script](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/alsa-lib). Just tried compiling it myself, same result. The bug appears or disappears when upgrading or downgrading the alsa-lib package and making no other changes, so that must be the cause.

**Comment by lachs0r** [comment]
And what if you recompile mpv?

**Comment by lachs0r** [comment]
Also, did you make sure to install a matching version of alsa-plugins as well?

**Comment by lachs0r** [comment]
And you might actually have to restart your session or even reboot to get a consistent ALSA/libasound state.

**Comment by bucaneer** [comment]
alsa-lib and alsa-utils at 1.1.3, alsa-plugins at 1.1.1 (which appears to be the latest), mpv recompiled and rebooted. No change.

**Comment by lachs0r** [comment]
So now I’ve tried just about everything from ancient AC’97 (two laptops and an old AMD64 board) to crappy USB sound hardware (generic DJ controller) to modern HDA (AD1988B, ALC1150, Lynx Point laptop) with 1.1.3 over 5 different kernel versions (up to 4.8.14) and some really wonky ALSA configs involving LADSPA, and I can’t reproduce this problem at all. Only thing I haven’t tried is installing Arch, and I’m starting to think that Arch’s configuration is the problem here, since they never seem to test the system as a whole. GCC bugs? Kernel driver bugs? Broken ALSA defaults? I don’t know. And I don’t believe it could be an mpv bug either; at least 0.22.0 and git master are working fine here.

**Comment by CounterPillow** [comment]
I also can't reproduce this, I'm on Arch Linux with alsa 1.1.3 and a freshly built mpv-git.

**Comment by bucaneer** [comment]
Messed around with my .asoundrc and discovered that the culprit is the `rate` plugin that I use as part of the default device. Removing it from the config fixes mpv issues and doesn't seem to break anything else (though as is always the case with these things, I seem to vaguely remember that I needed it before). Which would make this line from the 1.1.3 changelog relevant: "pcm_rate: Do not discard slave reported delay in status result."

**Comment by qmega** [comment]
I have this problem too (also on Arch). Was planning to bisect alsa but haven't had time yet. It works going directly to a device and I do have a `rate` plugin in my config so that's likely.

**Comment by lachs0r** [comment]
Alright then, just use `plug` instead. I can’t think of a practical reason to ever use `rate` instead.

**Comment by bucaneer** [comment]
Sure, the workaround is easy and painless, but where exactly is the bug? If the change in `rate` plugin caused it to report bad timings, then it should be reported to ALSA, but I imagine it could also be mpv mishandling the new data.

**Comment by qmega** [comment]
As expected, the bad commit is "pcm_rate: Do not discard slave reported delay in status result." ([diff](http://git.alsa-project.org/?p=alsa-lib.git;a=blobdiff;f=src/pcm/pcm_rate.c;h=1f830dd7e339b8d5fe3f66c079bb3f1b49e50c1a;hp=6184defbdde36584f3bc7b6326344b44f0087452;hb=e1e211208ab95f374a580c3c2649a1384b65065b;hpb=5a2bddfc79912d7537a3a43e28481bfefa9db88e))

I can report it to ALSA, but can anyone here who understands the system see if it's an actual bug introduced or it just breaks some assumption that mpv makes? Since other players don't exhibit the problem (tested vlc and ffplay, at least) it could be an issue here.

> I can’t think of a practical reason to ever use `rate`.

The reason I'm using it now is that when I use `plug`, mpv's AO line shows the sample rate of my dmix, whereas with `rate` it shows that of the file, so I thought that in the `plug` case it might be using ffmpeg to resample instead of samplerate_best in alsa. But now that I check with `-v`, the audio filter chain looks identical and only the "final HW params" differ. So I guess it's just a difference in the amount of abstraction the plugins do?

Is the rate plugin just around for backward compatibility and completely obsolete now?

**Comment by lachs0r** [comment]
mpv will always resample using FFmpeg unless you use `--alsa-resample` precisely because ALSA has broken delay reporting with some drivers.

**Comment by qmega** [comment]
Hmm, checking again it does insert a resampler for `plug` and not for `rate`. I didn't see the first time that it reconfigured the af chain later. Using `--alsa-resample` with `plug` seems to work the same as `rate`, including the A/V desync with alsa-lib 1.1.3, but fine with 1.1.2. Though actually it seems to break running a plug->ladspa->dmix in alsa.

But after spending most of the day messing with ALSA, I've come to the conclusion that it's complete garbage, so maybe I'll keep plug and try to make mpv use soxr and
