### ISSUE TITLE
Add Support for Hardware Deinterlacing

### ISSUE THREAD

**Issue by ksm123** [mpv-player/mpv#3939]
Is it possible to achieve iGPU hardware deinterlacing in macOS?

The following links may be useful.

https://developer.apple.com/reference/videotoolbox/decompression_properties/deinterlace_mode_constants?changes=latest_minor

https://mailman.videolan.org/pipermail/vlc-commits/2015-August/031929.html

https://trac.ffmpeg.org/ticket/5361

Thanks!

**Comment by Tatsh** [comment]
FYI you should fix the links there.

Seems like what would need to be done is (simplified):

1) create a file similar to `vf_vdpaupp.c` such as `vf_videotoolboxpp.c`
2) create the relevant struct of callbacks and register in `vf.c`
3) in the `.open` callback, just as with *vdpaupp*, change the callback pointers and decoder flags as seen in the VLC commit (on the `->priv` pointer)
4) Modify `hw_videotoolbox.c`'s `process_image()` (and probably `copy_image()`) function to handle passing the deinterlacing flags

However, it seems that because ffmpeg (libav) is responsible for creating the `VTDecompressionSession`, it would be best to change things there first.

**Comment by ksm123** [comment]
Thanks for your reply. The links are working now.

The third link is the request to support denterlacing. I'm not familiar with the ffmpeg bug tracking system, but it seems this function is still waiting to be developed.  It's been open for almost 1 year.

**Comment by wm4** [comment]
Well this much could be implemented in FFmpeg. It couldn't be enabled by the "deinterlace" option (layering violation), but better than nothing. I won't do it, though, someone else needs to bother with this.

**Comment by Akemi** [comment]
as discussed on IRC, hardware deinterlacing doesn't work or only inconsistent in macOS.
