### ISSUE TITLE
(Feature Request) timeline thumbnail

### ISSUE THREAD

**Issue by mostafaasadi** [mpv-player/mpv#3940]
Hi
It's very good idea , like youtube player or some other players, mpv shows a thumbnail preview on video timeline.
best regards

**Comment by Argon-** [comment]
This was already rejected multiple times.
There is one mpv wrapper (/branch) that does this by having 2 instances of mpv, essentially overlaying one instance with the other. Don't remember the name though.

Web players (e.g. youtube) usually offer this because seeking can take quite long. So you want to minimize the amount of seek operations and these previews help you to select the desired position on the first try. However, for an offline player seeks are ridiculously cheap and instantaneous. In fact, having another instance of mpv rendering the small preview all the time is (very) likely to consume more resources than a few targeted seeks.

**Comment by darkmorpher** [comment]
@wm4 _MPC-BE_ supposedly has that feature

**Comment by Hrxn** [comment]
MPC-BE indeed has

Although I don't think that anything comes close to the original implementation on YouTube.

**Comment by wm4** [comment]
And how is that implemented?

**Comment by Hrxn** [comment]
On YouTube?

Dark Google Magic, probably.

MPC-BE?

Not really sure, but I'd guess it's here somewhere:

https://sourceforge.net/p/mpcbe/code/HEAD/tree/trunk/src/apps/mplayerc/PlayerSeekBar.h
https://sourceforge.net/p/mpcbe/code/HEAD/tree/trunk/src/apps/mplayerc/PlayerSeekBar.cpp
https://sourceforge.net/p/mpcbe/code/HEAD/tree/trunk/src/apps/mplayerc/PlayerPreView.h
https://sourceforge.net/p/mpcbe/code/HEAD/tree/trunk/src/apps/mplayerc/PlayerPreView.cpp

Maybe somewhere else in that dir. Can't read source code, only file names.

**Comment by darkmorpher** [comment]
Also, _QtAV_
https://github.com/wang-bin/QtAV/blob/master/widgets/VideoPreviewWidget.cpp

**Comment by CrisBRM** [comment]
Would be cool if it only triggered during a pause.

**Comment by Hrxn** [comment]
Yeah, pretty sure that YouTube uses a special additional track created just for the previews..

**Comment by wiiaboo** [comment]
It's not really a track, just a thumbnail image map.

**Comment by kevmitch** [comment]
This is not going to happen in mpv core. @TheAMM has a [user script](https://github.com/TheAMM/mpv_thumbnail_script) to do this by replacing the osc.

**Comment by nvcken** [comment]
I tried to setup mpv thumbnail preview script, but doesn't work yet.
https://github.com/TheAMM/mpv_thumbnail_script/issues/61
Have anyone tried it? Pls help
