### ISSUE TITLE
mpv 0.23 fail to compile on OS X 10.9

### ISSUE THREAD

**Issue by Porkepix** [mpv-player/mpv#3946]
### mpv version and platform

mpv 0.23, OS X 10.9

### Reproduction steps

Using an OS X version now unsupported for precompiled binaries by Homebrew, it is now compiling packages. Everything was fine for mpv up to 0.22, but 0.23 failed to compile.

### Log file

Compilation logs can be found there: http://paste.leloop.org/?3e47b728c58e2c81#y26gGdqvqohTj8Ptmbx/FvE8iGdsPxEWHXeuQvOiJAM=

cc @Akemi as requested on IRC.

**Comment by Cpuroast** [comment]
I'd just like to point out that Apple has always usually supported the current version + 2 previous versions. Which means that 10.12, 10.11 and 10.10 are currently supported. 

Since macOS upgrades are free, apps tend to follow Apple's support model, some may be a bit more lenient than others and may support 1 older version for a bit longer.

But all in all, when a version of macOS stops receive Apple support, Apps tend to follow.

To simplify your life, you could simply upgrade to macOS 10.11 or 10.12 depending on what your hardware is.

https://en.wikipedia.org/wiki/MacOS_Sierra#System_requirements
https://en.wikipedia.org/wiki/OS_X_El_Capitan#System_requirements

**Comment by Porkepix** [comment]
Well, I'm aware of that, but if I didn't updated it, I had my reasons to do so.

I have to admit I didn't dive into the sources and look if there was parts using specific APIs/SDK and so on. My reasoning here was that to my knowledge, mpv isn't a specific OS X app, as I'm using it on my Linux machines too, which made me think it was not using OS X specific parts (I was rather thinking about pretty standard C++ and so on).

I obviously can be wrong about this, and if so, the choice may be to not support 10.9 or older anymore… which eventually would lead to WONTFIX the bug I guess.
Well, the choice is yours anyway.

**Comment by pigoz** [comment]
It's not even an important feature that broke support, just file drag and drop. So I guess it should be fixable.

**Comment by Cpuroast** [comment]
mpv may be supported on Linux, Windows and macOS, but it does include OS specifics for every platform it runs on.

It's not the exact same code that runs on all 3.

**Comment by Akemi** [comment]
it was just a matter of using the getter method instead of accessing the property directly. it's just me being a bit unexperienced in deving. sry about that.
