### ISSUE TITLE
There is no prescale-luma in the manual.

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#3992]
### mpv version and platform

```
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Dec 15 21:04:53 UTC 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.68.100
   libavformat     57.60.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: 3.2.git

```
Is this option removed?

**Comment by JulianLai** [comment]
I've found the answer, it is replaced with opengl-shaders, the user script wiki page haven't update it yet.

**Comment by plasmacutter** [comment]
thanks for posting this.

It was useful for someone who recently updated.

For reference for anyone who reads this later:

to set the equivalent of previous versions' prescale-luma=nnedi3:
download these shaders and drop them into a "shaders" directory of your choosing
https://github.com/bjin/mpv-prescalers/tree/master
then add the following to a conf that uses vo=opengl:
opengl-shaders="c:\path\to\shader\directory\nnedi3-nns32-win8x4.hook"

NOTES: 
there are numerous hooks to choose from
8x6 variants are useless (at least on nvidia) because they cause GPUs to choke.  
this filter does impose a brief freeze which dissipates a couple seconds after you re-scale.
the higher you go with your nns bits the more power you need, and the longer the freeze after scaling. 
recommend sticking with 32, though higher-end can handle 64 (I happen to use 64 on my gtx1080)
nns 128 is the point at which things become useless, so don't bother messing with them unless you want a laugh.
Other interesting items to experiment with: https://github.com/mpv-player/mpv/wiki/User-Scripts
