### ISSUE TITLE
Is this normal to see this when I enable icc-profile-auto?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#4001]
### mpv version and platform

```
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Dec 15 21:04:53 UTC 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.68.100
   libavformat     57.60.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: 3.2.git
```
Error message:
`[vo/opengl] ICC profile detected contrast very high (>100000), falling back to contrast 1000 for sanity. Set the icc-contrast option to silence this warning.`

**Comment by haasn** [comment]
There are two possibilities:

1. You're using a device like a CRT or OLED display which has a very high contrast. In that case, this would be the expected behavior, and you can set `icc-contrast` to the contrast of your display (look it up) to silence the warning. The warning exists because this is very rare and therefore unlikely to be the explanation.

2. Your ICC profile does not accurately measure your display. Perhaps you are using a “perceptual”-type ICC profile instead of a “colorimetric” profile, as those are known to contain stuff like gamma or gamut mapping as part of the transfer. Profiles generated by ArgyllCMS / DisplayCal do not have this issue, so I would recommend using that software to generate your ICC profiles.

If generating a new ICC profile is not an option for you, you can look up the expected contrast of your device online and set `icc-contrast` to that value as well. (The default of 1000 is a good guess for most LCD devices, so if you really can't be bothered and just want the warning to no longer show up you can just set `icc-contrast=1000` for a reasonable enough result)
