### ISSUE TITLE
Repeat and prefetch live .ts stream 

### ISSUE THREAD

**Issue by mozbugbox** [mpv-player/mpv#4029]
Some live stream url are in the form of `http://address.com/sample.ts` . It seems that the player is expected to repeatly download from the same URL repeated to play the stream as live stream.

There should be a flag or autodetect that the given URL is live and mpv should prefetch the next session. Like start re-download the same URL after played most of the current session.

currently, mpv can semi-stream this kind of URL by using `--loop=inf` option. But there are always some pause at the end of last session.

sample: http://system.fpiptv.com:8080/live/thierry/thierry/691.ts
It might not last long.

**Comment by ChrisK2** [comment]
This is an "interesting" way to do streaming. I tried to watch the stream using this:

Terminal A: 
```
mkfifo playback
while true; do curl http://system.fpiptv.com:8080/live/thierry/thierry/691.ts >> playback; done
```

Terminal B:
```
mpv playback
```

This ..somewhat.. works. However the segments don't always fit together seamlessly, so it seems like some additional information is needed when exactly the next segment is supposed to be downloaded.

Is this actually just HLS and there is an .m3u8 playlist somewhere that controls streaming? If you feed that instead of the direct TS-link to mpv(ffmpeg), this should work properly.

**Comment by wm4** [comment]
It sure is an exceptionally idiotic way to do streaming. Even dumber than HLS.

**Comment by mozbugbox** [comment]
There are quite a lot of this kind of streaming URL you can find from iptv listing sites. Maybe some iptv are designed to serve it using some specific streaming player.

**Comment by wm4** [comment]
WONTFIX, although `--prefetch-playlist` might happen to help.
