### ISSUE TITLE
Segfaults on TV input

### ISSUE THREAD

**Issue by fbriere** [mpv-player/mpv#4096]
### mpv version and platform

mpv 0.23.0, on Debian sid/amd64 (with a Hauppauge BT878 card)

### Reproduction steps

mpv tv://

### Expected behavior

Doesn't crash.  :smile:

### Actual behavior

Segfaults.

### Log file

- [Output](http://sprunge.us/gaYK)
- [Log file](http://sprunge.us/fheN)
- [Backtrace](http://sprunge.us/IgjF)

Bisecting identified 9f0e7bb as the guilty commit.

Let me know if there's anything I can do to help.  Thanks!

**Comment by wm4** [comment]
The TV code is unmaintained. I don't see anything wrong with the commit that's supposed to cause it, and the backtrace doesn't tell me anything either. A backtrace on a binary compiled without optimization might be slightly more helpful.

I can't even test this code, because I have no tuner. On the other hand, the non-v4l dummy backend works fine.

> Let me know if there's anything I can do to help.

A patch to fix it would be best.

**Comment by fbriere** [comment]
Found it: `tv_new_handle()` does not initialize the `tv_channel_list`
field (among others), potentially causing problems when `open_tv()`
tries to dereference it.

(9f0e7bb was obviously a red herring, merely affecting what remained in
the previously allocated memory chunk.)

> A patch to fix it would be best.

Gladly.  Should I individually add the missing fields to the list, or
would a `memset` on the whole struct be more appropriate?

**Comment by wm4** [comment]
I think switching to calloc would be preferred.
