### ISSUE TITLE
Superseded version of mpv needed

### ISSUE THREAD

**Issue by morphological** [mpv-player/mpv#4100]
Hi!

I desperately need a certain version of mpv from the ppa:djcj/vapoursynth.repository.
https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth
 mpv - 1:0.22.0-1~trusty

Unfortunately, all packages and any built deb files of this version have recently been deleted due to the release of version 0.23 which I have been having some problems with.

Would you know where I could still find this now superseded version 0.22 of mpv compiled with vapoursynth? Otherwise, what steps would I have to take to compile version 0.22 with vapoursynth myself in order to achieve a similar or even identical build? 
https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth/+build/11570553

Thanks

**Comment by mc4man** [comment]
Really not the right place to ask such questions but look in /var/cache/apt/archives, it may be there. Otherwise you are sol & either rebuild yourself or address your issue(s) with 0.23

**Comment by magiruuvelvet** [comment]
This is maybe not the solution you are looking for, but compiling mpv from source yourself is one of them. I have latest git of MPV aswell the latest version of vapoursynth. Everything works great. As reference I use SVP which requires mpv compiled with vapoursynth.

I have no idea how do build a deb package, so I can't help any futher with this.

This is my configuration for mpv
```
./waf configure --prefix=/usr \
        --confdir=/etc/mpv \
        --disable-build-date \
        --enable-zsh-comp \
        --enable-libmpv-shared \
        --enable-vapoursynth \
        --enable-lua \
        --enable-vf-dlopen-filters
./waf -j $(nproc) build
```

Make sure you have all `-dev` packages for vapoursynth installed.

**Comment by morphological** [comment]
@magiruuvelvet: Thank you very much, it looks like I won't have a choice but to build it myself.
Could you maybe share a little more in depth info on how I would have to go about compiling mpv with vapoursynth, since I am a complete noob in this area?

Since I intend to produce a similar or maybe even identical build to the djcj repo's mpv version 0.22 I will use the 0.22 git version as well.
The description on launchpad still contains two files, the build log and a change log.
https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth/+build/11570553
Will any information provided in these documents be helpful or even required to be followed during this process?

**Comment by magiruuvelvet** [comment]
@morphological What are your issues with 0.23? My guess is that those issues have something todo with incompatibility which should be resolved when compiling on your own. Better report a bug rather than forcing yourself to use an old version of mpv. Give the new version compiled from source at least a try :wink: 

I can give you some starting points. You should google for additional help.

I guess you run a debian-based disto. Make sure to install development packages for vapoursynth, lua and several others. Check the README and `waf` output for hints.

1. Clone the repo `git clone https://github.com/mpv-player/mpv`
2. `cd mpv`
3. Execute the 2 commands from above (my last post). But change the `--prefix=/usr` to `--prefix=$HOME/mpv` to install it to your home directory for testing before overriding system files. Change `--confdir=/etc/mpv` aswell - `--confdir=$HOME/mpv/etc/mpv`
4. `./waf install --destdir="$HOME/mpv"`

MPV can be found in your home directory under `mpv` then.

---

If you still have issues and you really wanna go with 0.22, repeat all the steps above, but run `git checkout v0.22.0` after step 2 to compile version 0.22 of mpv.

Regards

**Comment by darealshinji** [comment]
The PPA maintainer here. If the recent git version has no problems I could update the package to that version.

**Comment by morphological** [comment]
@darealshinji Are you Marshall Banana? I have sent you an e-mail to your gmx address regarding the matter. Please clarify what you are going to update? You have recently updated 0.23.0 to 0.1 , 0.2 and 0.3. I am currently testing 0.3

**Comment by ChrisK2** [comment]
Not really an mpv issue, so closing this.
