### ISSUE TITLE
How to delay playback?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4120]
Hi,

When I play a video, for first several seconds mpv calculates shaders, sets refresh rate, recalculates shaders, etc.
As a result, beginning of video gets jammed somehow.
Is it possible to delay playback so that mpv could make all its calculations first, and only then start outputting pictures on screen?

Regards,
Alex

**Comment by ChrisK2** [comment]
Add pause ``pause=yes`` to your config and write a script that resumes playback after X seconds after loading the file.

**Comment by fhlfibh** [comment]
Will try it, thanks!

**Comment by justUmen** [comment]
I have the same problem using the COMMAND INTERFACE with `loadfile`, mpv is muting the sound of the first seconds. (I use a series of very short video files so it is a big problem)
I tried using `append` instead of `replace` and `playlist-next`, thinking it would preload it, but same problem.

Is there a way to "preload" the content and play it only when mpv is ready to do so ?
I really wish to use mpv for my project, thanks !!!

PS: After the file played once, I can go back to it with no sound problem.

**Comment by justUmen** [comment]
I have the same problem using the COMMAND INTERFACE with `loadfile`, mpv is muting the sound of the first seconds. (I use a series of very short video files so it is a big problem)
I tried using `append` instead of `replace` and `playlist-next`, thinking it would preload it, but same problem.

Is there a way to "preload" the content and play it only when mpv is ready to do so ?
I really wish to use mpv for my project, thanks !!!

PS: After the file played once, I can go back to it with no sound problem.

**Comment by lachs0r** [comment]
Please open a separate issue. Your problem is that mpv apparently skips audio samples, and that most likely is an issue of the audio output you are using. Remember to follow the issue template and paste a log file.
