### ISSUE TITLE
mpv@osx - keep afloat ?

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#4159]
### mpv version and platform

mpv 0.24 build - osx mavericks
### Reproduction steps

i have installed afloat window manager together with easysimbl and was expecting to could pass an option to mpv to keep the window above the other - eg. visible - "afloat" 

it works for example with quicktime 7 

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by Akemi** [comment]
you want` --ontop` and maybe the newly added `--ontop-level=` option. latter is not in 0.24 and only in git master. you should really try to read the manual for that first.

you you meant something else let me know.

**Comment by mrkapqa** [comment]
Hello yes and it should be activable from the Window pane that wouuld  
be great thanks

Zitat von Akemi <notifications@github.com>:

**Comment by Akemi** [comment]
i don't quite get the issue and i am not familiar with afloat. i assume with "Window pane" you mean the 'Window' menu from the Menu bar? from a quick glance afloat should add a "Keep afloat" menu item there? so your problem is that aflot can't add that menu item there? or do actually want us to add an On Top options ourselves thee?

you can also just use `Shift+T` to make the window On Top.
