### ISSUE TITLE
Compiling error on Window 7 with MSYS2

### ISSUE THREAD

**Issue by xanadupark** [mpv-player/mpv#4175]
Hello,

I have followed the compiling instruction document for windows with msys2.
Until recently, there was no issue at all.
But my recent a few tries make following error during waf configure:

Writing configuration header:                                        : Could not create the directory C:/msys32/home/~/mpv/build/C:

Is this error of my msys system? or waf script related error?

Thanks in advance.

**Comment by wiiaboo** [comment]
That doesn't seem even remotely related to mpv or waf.

Also, don't ignore the issue template. What're the commands you're using, which shell (msys or mingw), logs for configure, build, etc.

**Comment by rossy** [comment]
Looks like weird MSYS path conversion nonsense. I've found the build only works with MSYS2 Python (rather than mingw-w64 Python,) so try running the following from mpv's source directory:
```
pacman -S python
rm -rf waf {,.}waf{,3}-*
/usr/bin/python3 bootstrap.py
/usr/bin/python3 waf configure CC=gcc.exe --check-c-compiler=gcc --prefix=/mingw64
```
Invoking /usr/bin/python3 directly, rather than just running ``./waf`` should make sure the MSYS2 version of Python is used.

If this doesn't fix it, could you post the log (build\config.log).

**Comment by eugenesvk** [comment]
Thanks @rossy, that workaround worked for me
