### ISSUE TITLE
How to create playlist?

### ISSUE THREAD

**Issue by jevojipi** [mpv-player/mpv#4184]
Hardcore software you got therre. I like it, but it's very confusing. I want to create playlist, how to do that? In moc it was pretty simple.

**Comment by Hrxn** [comment]
For a start, any plain text file with the full path name to the files will work..

**Comment by ChrisK2** [comment]
Or if you just want to play multiple files, put them after each other in the command line, or open them together/drag them onto the window. You can add additional files by holding shift while dropping files onto the window.

**Comment by smolseok** [comment]
> Or if you just want to play multiple files, put them after each other in the command line, or open them together/drag them onto the window. You can add additional files by holding shift while dropping files onto the window.

Can I save this playlist in anyway?

**Comment by qqgg231** [comment]
@smolseok 

create `my_list.txt` file with list of files

then run:
`mpv --playlist=my_list.txt`

**Comment by kristopolous** [comment]
Leaving a comment here for people who get here through google.

There's support for plaintext lists as discussed in https://github.com/mpv-player/mpv/issues/4184#issuecomment-466781988 but there's also support for [M3U](https://en.wikipedia.org/wiki/M3U) and [PLS](https://en.wikipedia.org/wiki/PLS_(file_format)). 

The [M3U parser is here](https://github.com/mpv-player/mpv/blob/5a261507173d28c762ba4f605d7983d928d4bf24/demux/demux_playlist.c#L174) and here's the important part (at least for me)
```c
        if (bstr_eatstart0(&line, "#EXTINF:")) {
            bstr duration, btitle;
            if (bstr_split_tok(line, ",", &duration, &btitle) && btitle.len) {
                talloc_free(title);
                title = bstrto0(NULL, btitle);
            }
```
For people without C knowledge this means that 

> #EXTINF:321,Example Artist - Example title

will be properly parsed

The PLS parser [DOES NOT support any additional meta information](https://github.com/mpv-player/mpv/blob/5a261507173d28c762ba4f605d7983d928d4bf24/demux/demux_playlist.c#L280)

```c
static int parse_pls(struct pl_parser *p)
{
    return parse_ini_thing(p, "[playlist]", "File");
}
```
Essentially there's a basic ini format parser and this one only looks for keys with a "File*" and ignores other things, like "Title" or "Length" ... So yeah, if you want to inject meta info then format it as an M3U file.

I'll probably follow this up with an example since I'm about to write one right after I press this green button below

**Comment by kristopolous** [comment]
actually I take it back, the m3u parser doesn't work. it parses out the title and then just tosses it in the garbage.

**Comment by kristopolous** [comment]
alright I'll fix it then, do the PR stuff, open a ticket and crosslink here I guess

**Comment by kristopolous** [comment]
ok so here's an example. Pretend you want a playlist from youtube-dl:

```bash
$ youtube-dl -g --get-duration --get-filename https://somesite/somepath
```
And want to convert it to an m3u parsable by mpv, here's one way to do it

ytdl2m3u.awk
```awk
{
  switch (NR % 3) {
    case 2: title=$0; break
    case 1: file=$0; break
    case 0: 
      split($0, parts, ":")
      duration = parts[1] * 60 + parts[2]

      print "#EXTINF:" duration "," title "\n" file "\n"
      break
  }
}
```

so now you can do this:
```bash
$ youtube-dl -g --get-duration --get-filename https://somesite/somepath | awk -f ytdl2m3u.awk > something.m3u
```

And then finally

```bash
mpv --term-playing-msg='\n${media-title}' something.m3u
```
and thus preserve the titles.

**Comment by kristopolous** [comment]
As an aside if you want mpv to exit immediately on error there's no simple command line way to do it but it *can* be done in lua. Let's just presume the exit code of 2 for an error here

quit-on-error.lua
```lua
local os = require 'os'
mp.enable_messages('error')

function lg(e) 
  if e.level == "error" then
    print("Exiting...")
    os.exit(2)
  end
end

mp.register_event("log-message", lg)
```

so now you can do 

```bash
 $ mpv --script=quit-on-error.lua --term-playing-msg='\n${media-title}' something.m3u
```

**Comment by abdessamadelhamdany** [comment]
We'll if you're like me have multiple folders you can do this

from the root folder run:

`find ./ -type f | sort > pl.txt`
then
`mpv --playlist=pl.txt`

**Comment by Hrxn** [comment]
This should work as well:
`find ./ -type f | sort | mpv --playlist=-`

**Comment by bitraid** [comment]
> This should work as well:
> `find ./ -type f | sort | mpv --playlist=-`

Which is the same as `mpv ./`

**Comment by Hrxn** [comment]
Because `./` is just an example for `find`

**Comment by wuyudi** [comment]
to have a simple GUI and playlist.

```sh
mpv --player-operation-mode=pseudo-gui ./**/*.m4a
```

**Comment by guidocella** [comment]
The `txt` extension is arbitrary, `--playlist` plays any playlist file, and if you give it the `m3u` extension you don't have to write `--playlist=`.

**Comment by cameronj86** [comment]
Building on the existing solutions, I want to throw `fzf` in there for a good file-picking experience. Works great for playlists (and for individual videos as well):

`fzf -m | mpv --playlist=-`
Where `fzf -m` Search through the present working directory w/ fuzzy finder, and the `-m` option allows you to select multiple files at once to a playlist)

I added an entry to my `.bash_aliases` so that I can reference it more easily: 
`alias mpvplaylistfzf='fzf -m | mpv --playlist=-'`

**Comment by daniel-alegria3** [comment]
@cameronj86 This doesn't work with `mpv --shuffle` as mentioned in [#7922](https://github.com/mpv-player/mpv/issues/7922).
I tried the workaround proposed [there](https://github.com/mpv-player/mpv/issues/7922#issuecomment-2124048029) but I couldn't make it work.
My solution is a bash function that uses `find` and `fzf` to select either directories and files in my ~/Music. Then I use the find command again to 'unfold' the files if I selected a directory. Finally, I pipe the result to `mpv` with `xargs`.
Any suggestions to make it squeaky clean?

`
function play-music {
    local selected
    local processed
    if [[ $# -eq 1 ]]; then
        selected=$1
    else
        selected=$(find ~/Music/ -mindepth 0 -maxdepth 4 -type d,f | fzf --multi --tiebreak=begin --scheme=path --reverse)
    fi

    if [[ -z $selected ]]; then
        return
    fi

    processed=""
    while IFS= read -r line; do
    if test -d "$line"; then
        processed+="$(find $line -type f)\n"
    else
        processed+="$line\n"
    fi
    done <<< "$selected"

    echo -e $processed | xargs -d '\n' mpv --shuffle --no-video --no-resume-playback --af="lavfi=[dynaudnorm=f=75:g=25:p=0.55]"
}
`
