### ISSUE TITLE
macOS High DPI monitor and autofit options

### ISSUE THREAD

**Issue by sCreami** [mpv-player/mpv#4194]
I thought the relative display size with retina displays was fixed but it seems not.

### mpv version and platform

macOS 10.12 Sierra
git master

### Expected behavior

When using a relative % as option, the window should have this % in height.

### Actual behavior

Setting autofix=50% will result in a ±25% window.

[cc @Akemi as always]

**Comment by sCreami** [comment]
Oh I forgot to mention but it's when using `--no-hidpi-window-scale` so maybe it's an expected behavior?

**Comment by Akemi** [comment]
yeah i am kinda aware of this, though i though it was the other way around. i just assumed it's like this but never tested. as a user it's unexpected. as a dev i don't know when autofit was set to a relative metric since i just get the final size in pixel.

maybe @wm4 knows of a way how i can get to know, in the vo backend, when a relative metric was set and i should force `--hidpi-window-scale` appropriately?

**Comment by wm4** [comment]
vo_calc_window_geometry processes the option using the supplied arguments, that's all I know.

**Comment by Akemi** [comment]
this commit should fix it ([branch](https://github.com/Akemi/mpv/commits/cocoa_hdpi)). since @wm4 added a dpi scale aware function to calculate the initial window position and size (a35a5bb), i could get rid of a fair amount of 'duplicate' code.

i tested the cases from #3867 again and they are also still working. maybe @SteveJobzniak wants to have a try too.

**Comment by sCreami** [comment]
Works fine 👍

**Comment by SteveJobzniak** [comment]
@Akemi I have a non-Retina MacBook Pro 2010, so I guess that won't work for testing if this is a retina only patch?

**Comment by Akemi** [comment]
both cases are affected by this change. i was just interested if the cases from #3867 still work for you.

**Comment by SteveJobzniak** [comment]
@Akemi Oh yeah that commit seems to change a lot. I'm building mpv with your new commit now to see if geometry still works.

**Comment by SteveJobzniak** [comment]
@Akemi All geometry test cases from the previous ticket work. I tested 0:0 (top left), 100%:100% (bottom right), 50%:50% (center), +20-20 (bottom left with negative offset). I tested with hidpi-window-scale=yes and =no. But no retina screen here so dunno if that did anything.

Well, the patch works with non-retina displays! 👍  :)
