### ISSUE TITLE
No HW acceleration on Kaby Lake i5-7200U (HD 620)

### ISSUE THREAD

**Issue by muhfreedomss** [mpv-player/mpv#4205]
### mpv 17/2/12 Windows 64bit

Video is 10bit, 30mbit/sec HEVC, 4k 60fps.

I've tried all the HW settings and the videos still have slow playback with mpv.

They play just fine with low CPU usage on Windows video app and MPC-HC.

**Comment by rossy** [comment]
I think mpv should be able to decode HEVC Main10 with DXVA, but there isn't enough information here to solve this issue. Following the [issue template][1] is recommended. Providing a verbose log is especially important, since if there was an error in creating the hardware decoder, it will be in there.

> Windows 64bit

Which version? Windows 7 and Windows 8+ have different hardware decoding APIs.

> I've tried all the HW settings

Which ones specifically? Certain hwdecs only work with certain VOs and OpenGL backends, so if ``vo`` or ``opengl-backend`` are set to non-default settings, it's important to know what they are as well. (Though any non-default settings will appear in a verbose log.)

[1]: https://github.com/mpv-player/mpv/blob/master/.github/ISSUE_TEMPLATE
