### ISSUE TITLE
how to force mpv not to stop streaming

### ISSUE THREAD

**Issue by nedz14** [mpv-player/mpv#4211]
mpv-i686-20170305-git-85c8556ee
win 7
how to force mpv not to stop streaming
I watch videos in YouTube, sometimes i have bad connection and mpv stopping streaming it is not helping in my case.
thx

**Comment by Et0h** [comment]
I've not tested anything, but I expect that what you want can be found within a YouTube-DL (YTDL) configuration option rather than mpv itself.

https://mpv.io/manual/master/#options-ytdl-raw-options explains how to pass options onto YTDL.

https://github.com/rg3/youtube-dl/blob/master/README.md#download-options explains YTDL download options such as --retries, --fragment-retries and --buffer-size which might address your issues.

**Comment by wm4** [comment]
When mpv calls youtube-dl, irt doesn't download any actual media data with it.

**Comment by kevmitch** [comment]
This is probably down to the network conditions between you and youtube servers not providing adequate bandwidth for the content you're streaming. Since by default mpv lets youtube-dl select the highest quality stream, you might be able to avoid this by selecting a smaller bandwidth stream with --ytdl-format. It accepts options as documented [here](https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection). 

If you still want to watch the highest quality, you can increase [--cache](https://mpv.io/manual/master/#options-cache) value and pause the video at the begining until it has buffered some or all of the stream.

**Comment by nedz14** [comment]
Thank you all,
i use --ytdl-format=22/17/18/bestvideo<=136+bestaudio, but sometimes it doesn't work.
Regarding the cache, thanks to kevmitch i found the option "-cache=auto -cache=150000", hope it will work.

**Comment by CounterPillow** [comment]
Don't use format codes directly, instead, use the meta fields of the format to select one with the properties you want.

For example, `bestvideo[height<=?720]+bestaudio` will try to get the best available video below the resolution of 720p, and the best audio.

**Comment by nedz14** [comment]
bestvideo[height<=?720]+bestaudio
exactly what i need, 
i appreciate,
thx
