### ISSUE TITLE
[Question] macOS to fix mpv window on desktop level

### ISSUE THREAD

**Issue by SIDmao** [mpv-player/mpv#4222]
Is it possible to fix the mpv window on the desktop level?
And when I open a new window with Alfred on a macOS native fullscreen workspace, how can I stop the mpv window take me to the workspace which is activated by it? Sometimes I listen some music with mpv, and every time I open it on a fullscreen workspace, it takes me to the workspace which  appears the window. It's a bit annoying.
Thanks for help!

**Comment by Akemi** [comment]
both are probably doable but there is no way to activate such a behaviour atm.

what is your use case for fixing the window to the desktop level? i assume it's like ontop but just always behind windows? do you want to use mpv as a wallpaper?

i don't use alfred so i don't know what exactly you mean or rather what your use case is. so you are bothered by mpv going into fullscreen but that you can't stay on the current space? so you want to mpv to playback something in fullscreen but in 'background'/different space? that doesn't really make sense in the case of videos. for audio you can just not create a (fullscreen) window since it seems pointless. see option `--force-window=no` and maybe `--audio-display=no`. if you need something else, please explain your use case(s) properly.

**Comment by SIDmao** [comment]
Sorry for the confusing description because of my poor English.
I have made a gif so I can make it clearly.

https://transfer.sh/3lf7D/richscornfuldipper.gif

For example, I am using the Safari on fullscreen mode and at the same time I want to listen some music from Internet, so I invoke the Alfredworkflow by shortcut and insert the keyword, through it I can execute a shell script such as `mpv --force-window --on-all-workspaces --really-quiet --external-file=<url/to/cover> --no-border  --sub-file=<path/to/lyric/files> --sub-blur=2.0 --sub-text-font-size=40 --sub-align-x=left --sub-scale-by-window=no --geometry=200+0%+100% <url/to/music>`.
Then the mpv window appears at the bottom-left corner of the main workspace, and it takes me to the main workspace at the same time. But I want to keep at the Safari fullscreen space and fix the mpv window at the corner of desktop level of main workspace so that it would not cover other windows. Is it possible?
Thanks again for your generous help.

**Comment by Akemi** [comment]
i am not sure if it is possible like this. apple doesn't give us much control over spaces. do you know of another app that behaves like this, eg not changing the space when opened from fullscreen but placing the window on the 'main' one?

as a workaround you could always keep mpv open. that way it won't create a new window since there is already one and it won't change the space.

also is this "Is it possible to fix the mpv window on the desktop level?" a separate feature request or just this one badly worded? if it's a separate feature could you explain what you mean pls.

on a side note `--on-all-workspaces` is not available on macOS.

**Comment by SIDmao** [comment]
Thanks for your patient help.
It's seems that I haven't seen a App can create a window on main workspace without changing the workspace. Except those ones who only show up on the menu bar = =
By the way, "Is it possible to fix the mpv window on the desktop level?" is a question badly worded. I want mpv to show up like a window but not the fullscreen, and it will never cover other windows. And when I click the mpv window, it will just be activated without becoming the top most level of all windows. Is it possible to make it happen?

**Comment by Akemi** [comment]
i think we can't do anything about the space changing behaviour. it is up to apple and they already removed APIs that made it possible before. so not much luck sry.

for you second request. more easily worded, you want mpv to always stay behind all other windows even when in focus? try [this branch](https://github.com/Akemi/mpv/commits/cocoa_desktoplevel) and see if it accomplishes what you want. use it with `--ontop-level=desktop --ontop`, or just the first option and toggling ontop with Shift+T.

**Comment by rien333** [comment]
@Akemi I'm pretty sure macOS supports windows being visible on all desktops though, look at [Helium](https://github.com/JadenGeller/Helium) for example. Is the mpv project open for an "--on-all-workspaces" on macOS PR? I think I could maybe make one.

For anyone looking for a bad and quick hack, you can rightclick mpv in the dock and then "assign to all desktops"

**Comment by Akemi** [comment]
> @Akemi I'm pretty sure macOS supports windows being visible on all desktops though...

i never said it wasn't? i was implying the the already available option [--on-all-workspaces](https://mpv.io/manual/master/#options-on-all-workspaces) isn't available/implemented within mpv on macOS. since the option already exists, i don't see a problem with implementing that feature.

**Comment by rien333** [comment]
Yes I understand! I was just saying that it was possible, not trying to imply anything about your knowledge or something you said. I'm sorry if I came of that way.
