### ISSUE TITLE
No audio with aac_at(AudioToolbox) decoder.

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#4224]
### mpv version and platform

mpv git-076116a (C) 2000-2017 mpv/MPlayer/mplayer2 projects
built on Sat Mar 11 08:11:51 IST 2017
ffmpeg library versions:
    libavutil       55.48.100
    libavcodec      57.82.102
    libavformat     57.66.104
    libswscale      4.3.101
    libavfilter     6.74.100
    libswresample   2.4.100
ffmpeg version: N-44096-g6e913f2

macOS 10.12.3

### Reproduction steps

Can't say exactly, happens on CPU intensive videos, I think. E.g. 1080p 10-bit x264 in 4:4:4 colorspace.

### Expected behavior

Using the aac_at(AudioToolbox) decoder, audio should play normally.

### Actual behavior

No audio at all, or audio plays normally from beginning of file, but stops after a seek.

### Log file

http://pastebin.com/vSf2vSBG

**Comment by wm4** [comment]
Not sure why that is happening - maybe some complicated interaction with ordered chapters and draining?

But why would you not use ffmpeg's decoder anyway?

**Comment by kkanungo17** [comment]
I had read somewhere that aac_at and other audiotoolbox decoders would consume less cpu for decoding.

I'm using the Fraunhofer decoder for now.

**Comment by wm4** [comment]
Anyway, do you have some samples?

**Comment by atomnuker** [comment]
The Fraunhofer decoder is about 7 times slower than the FFmpeg one.
I dare you to prove me the AudioToolbox one is faster than the FFmpeg one. Lots of assembly and hard work was put into it. Even if there's a hardware decoder it'll likely be slower (because of badly optimized hardware).
And even if you had some underpowered MIPS thing you could use FFmpeg's fixed point AAC decoder which even on x86 is still 4 times faster than the Fraunhofer one.

To conclude, stop assuming everything you read on the internet is true.
Interesting fact: with low resolution h264 files (e.g. QCIF) the FFmpeg decoder is 4x the speed of a hardware decoder.

**Comment by kkanungo17** [comment]
After reading a comment saying that AudioToolbox decoders are better due to the hardware decoder, I checked some other sites mentioning Fraunhofer and Audiotoolbox libraries being better encoders. So I mistakenly assumed that they would be better decoders. 

My bad, closing issue.

**Comment by wang-bin** [comment]
audiotoolbox is slower in my tests. Audio duration is 00:44:32, format is aac (LC) 48000 Hz stereo  fltp 123 kb/s, audiotoolbox spends at least 7s, ffmpeg only takes 5~5.5s
