### ISSUE TITLE
Please complete "Essential dependencies" in readme.md

### ISSUE THREAD

**Issue by szg0000** [mpv-player/mpv#4251]
Please complete the "Essential dependencies" which is an incomplete list in mpv github README.md
Use Debian development package names.

**Comment by wm4** [comment]
> Please complete the "Essential dependencies" which is an incomplete list in mpv github README.md

What is missing?

>  Use Debian development package names.

No.

**Comment by CounterPillow** [comment]
>Use Debian development package names.

If you're running into trouble compiling mpv on Debian and are opening this issue because you think it might be a dependency issue, consider checking out [mpv-build](https://github.com/mpv-player/mpv-build). It'll make you a mpv build with an up-to-date version of ffmpeg and libass, which is what you most likely will need anyway. (Not sure what your distro ships, but if it's ffmpeg 2.8, it's way too old)

**Comment by wm4** [comment]
mpv-build in particular has a list of debian deps in the debian package files: https://github.com/mpv-player/mpv-build/blob/master/debian/control

**Comment by szg0000** [comment]
Thanks wm4. I am interesting that list, what you linked.
