### ISSUE TITLE
[Proposal] Transparent lavfi handling

### ISSUE THREAD

**Issue by gtm87x** [mpv-player/mpv#4257]
As far as I understand, as of now the vast majority of audio/video filtering in mpv is done by libavfilter via vf_lavfi, with only a small portion of internal filters still standing, and even many of them are actually wrappers to the ffmpeg lib.
So there's an idea I've been thinking about for some time: is it possibile to actually make libavfilter's handling transparent? 
So the user could type eg. af/vf=filter=ecc. without invoking vf_lavfi (and its sometimes weird chain of escaping) first.
Does it seems like a feasible/useful idea?

**Comment by wm4** [comment]
The way forward is to kill the kill the old filter chains. Both have not much use anymore, other than the lavfi wrappers, or things which require interaction with the mpv frontend code (like volume control or deinterlacing). Because of the latter, there will still be the need for some sort of filter abstraction within mpv, but most user-visible parts can be left to libavfilter. So it's entirely possible that the new user interface (as in options and properties) will be completely different. But until then, I'm not going to touch that.

**Comment by wm4** [comment]
After thinking about this for a while, I did it anyway: d4c1ddd6b166ff2d8

I also deprecated most of the builtin filters (which take priority over the "transparent" bridge).
