### ISSUE TITLE
hwdec=cuda not working (cuGLGetDevices), cuda-copy works

### ISSUE THREAD

**Issue by Carl-Robert** [mpv-player/mpv#4262]
### mpv version and platform
mpv-x86_64-20170319-git-03933f356 (from the sourceforge) Windows 10 x64 nvidia 670
(Tried also the few releases from https://mpv.srsfckn.biz/, no difference)
### Reproduction steps
Loading a video file with hwdec=cuda
### Expected behavior
To use cuda and not fall back to software
### Actual behavior
Gives the following error (used -v and is the only error in there, doesn't matter which of my h264 mkv, m2ts or avi files were used):
`[vo/opengl] Loading hwdec driver 'cuda'
[vo/opengl/cuda] cuGLGetDevices(&device_count, &device, 1, CU_GL_DEVICE_LIST_ALL) failed -> CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
[vo/opengl/cuda] cuCtxPopCurrent(&dummy) failed -> CUDA_ERROR_INVALID_CONTEXT: invalid device context
[vo/opengl] Loading failed.`
And falls back to software decoding.

However hwdec=cuda-copy works just fine for some weird reason, so at least cuda should work at some level.
No sample file provided as this didn't seem to be file-specific.

**Comment by wiiaboo** [comment]
hwdec=cuda doesn't work with Angle, only win and dxinterop backends.

**Comment by Carl-Robert** [comment]
Oh! Yeah, it started to work once I manually put dxinterop there, for some reason it must have defaulted to angle even after commenting it out. So, maybe a check should be in place there to force it to use dxinterop if cuda present? The original bug seems to be indeed fixed, user error like usual.

**Comment by wiiaboo** [comment]
If dxinterop works fine in your system (doesn't crash or work slower) and you want to use hwdec=cuda it's OK to always use it.
Any particular reason why you'd prefer cuda to dxva2 or d3d11va? Afaik they're different APIs but use the same part of the hardware and support the same things.

**Comment by Carl-Robert** [comment]
No reason really, other than testing if working better in my case. I seem to get occasional micro stutter which annoys me a lot, and the more I am annoyed by it, the more I stare looking for the stutters. Figured being native and "official" by nvidia it would work more smoothly.

**Comment by philipl** [comment]
For what it's worth, I believe this doesn't work because ANGLE is wrapping Direct3D, so there's no "real" nvidia opengl implementation in play. That means cuGLGetDevices() basically doesn't see any devices (it's trying to find the devices backing the current GL context). If you were to somehow get past this point, the CUDA<->GL interop calls would fail because the behind-the-scenes APIs required to map surfaces wouldn't work.

You'd have to use the Direct3D interop API instead, which would just be a mess and extra confusing.

**Comment by wm4** [comment]
Indeed, the driver can't know about the "emulated" GL by ANGLE, so we'd have to add a cuda-via-d3d backend. I'm not sure if anyone is interested in writing such a backend, but it'd probably be subject to ANGLE's annoying restrictions on d3d texture import, and not worth using over d3d11va anyway. So I'm closing this with WONTFIX, although if someone wants to write such support I'd not reject it.

>  I seem to get occasional micro stutter 

Did you try `--video-sync=display-resample`?

**Comment by Carl-Robert** [comment]
Yes, I'm playing 23p material on 60hz display with interpolation enabled, it stutters occasionally and seemingly randomly during playback (tried almost every tscale), sometimes it is all smooth as well. However went back to the mpc-hc+madvr combo for now, even as the smoothmotion there ain't as smooth as interpolation here, it lacks the randomness of it.

**Comment by aufkrawall** [comment]
Using cuda has advantages over dxva2 and d3d11va:
dxva2 has problems with chroma blur and d3d11va is much slower for me.
copyback-modes introduce additional load on GPU and CPU.
With Nvidia, cuda should be fastest and dxinterop should be used anyway since angle seems to be much slower under heavy load.
cuda works great on Windows and Linux btw., with newest ffmpeg version 3.3 it also works again ootb on Linux.
Only disadvantage of cuda is that it forces GPU to P2 state and you also have to stick to cuda deinterlacing for interlaced content.
