### ISSUE TITLE
4k To 1080p Downscaling Could Be Way More GPU Friendly

### ISSUE THREAD

**Issue by MrOak88** [mpv-player/mpv#4280]
There are some unnecessary calculations going on if you are watching 4k media on a 1080p screen. 

MPV scales the chroma information which already is saved in the 1080p resolution up to 2160p and then back to 1080p. Isn't that probably just a waste of resources and wouldn't it be much better if mpv just could use the "unscaled" chroma  in such a "rendering path" situation?

**Comment by wm4** [comment]
Use ``-opengl-dumb-mode`` if you want that.

**Comment by haasn** [comment]
This is problematic in principle due to chroma offsets, so the net result is that you would end up with an image that's off by a half-pixel unless you include a separate scaling pass to fix the chroma plane. It's also problematic due to color distortions unless scaling in linear light; although I think that could be worked around by treating the luma plane as a grayscale image.

More importantly, it makes the chroma/luma scaling code, which is already the most complicated and error-prone part of mpv, even more complicated, so I'm unwilling to add a significant amount of extra complexity.
