### ISSUE TITLE
Move or delete currently playing file  features suggestion

### ISSUE THREAD

**Issue by TwitchKappa** [mpv-player/mpv#4329]
Hello I have a feature command suggestion for your media player. 

It would be useful to have a keyboard shortcut that moved the actively playing file to the recycle bin or a folder of the user's choice. Ideally this command would also remove the actively playing file from the playlist and move down to the next file in the playlist.

This feature would be useful if the user downloaded a number of videos and would like to sort through the ones they want to keep or discard.

This would be identical to the commands in the media player classic home cinema and the smplayer. Both of these programs allow you to move the actively playing file to the recycle bin.

Alternately you could add a feature that copies the path of the currently playing file or writes the path to a text file, and then moves down to the next file on the playlist. This would allow the user to generate a list of files they would like to keep or delete without the player itself moving or deleting files.

Thank you for your consideration and keep up the good work.

**Comment by nguyenhimself** [comment]
Since each OS has their own Trash folder location, I don't think mpv will get this built-in anytime soon.

Meanwhile, assuming you're using Linux or macOS, you can put [this lua script](https://gist.github.com/nguyenhimself/8844c49f21742a7ee14c08e29e8952a0) in ~/.config/mpv/scripts to get this feature.

Note: The keyboard shortcut is "d". You can change it in the script.

**Comment by wm4** [comment]
Yeah, something this specific is for Lua scripts, not builtin functionality.
