### ISSUE TITLE
macOS: Dock does not unhide if we close mpv too fast after entering full-screen

### ISSUE THREAD

**Issue by vitorgalvao** [mpv-player/mpv#4400]
### mpv version and platform

mpv `1cab4b6`
macOS `10.12.4`

But I’ve had this happen for months, with different versions of `mpv` (and maybe of macOS, even, but am not sure on that front). Haven’t reported it earlier because only today did I realise mpv is the cause.

### Reproduction steps

1. Have your Dock’s auto hiding set to off.
2. Open a video with mpv and make it fullscreen.
3. As soon as the video fills the screen, quit mpv.
4. Your Dock is now hidden, and with auto hiding set to on.

I don’t know why mpv is hiding the Dock. Maybe it’s a remnant of the time when you didn’t use native full-screen on macOS? It seems like you’re using it now, so perhaps that behaviour can be completely removed.

### Expected behavior

Dock’s auto hiding behaviour should be what it was before.

### Actual behavior

Dock’s auto hiding is turned on.

**Comment by Akemi** [comment]
yeah i have seen this before. though if i didn't forget to remove anything we don't do anything special about the dock hiding anymore and everything is handled by the `toggleFullscreen` method from the standard API. so it's most likely an Apple bug. i will see if we can work around that somehow.

**Comment by vitorgalvao** [comment]
Is there a Radar open for that bug? If there is, I’d be glad to duplicate it (supposedly that helps them prioritise fixes).

**Comment by Akemi** [comment]
i just tried to reproduce this issue with an Apple App but couldn't. it simply doesn't work because any standard App is unresponsive to 'any input' during the Fullscreen animation and a short time after it, so it can properly finishing setting up its state. mpv itself is responsive to any input during that time since commit https://github.com/mpv-player/mpv/commit/063ca8f0fe48c281944c5307b1e8bbb11bb22822 to fix one of the issues mentioned on #3944. so yeah assume apple made it that way so they don't have to care about any 'state' recovery when an App quits in that time frame, so they might be reluctant to fix it. i have no idea about an open radar.

so far it's just my assumptions what exactly happens.

**Comment by Akemi** [comment]
just a heads up, i found one way to work around this. basically on quit we need to check if the system wide fullscreen animation is running and then we have to wait till it's done before doing the usual uninit routine.

**Comment by vitorgalvao** [comment]
Thank you for the amazing work (as always), @Akemi.
