### ISSUE TITLE
Is mpv vulnerable to the recent subtitle attack?

### ISSUE THREAD

**Issue by noahbishop** [mpv-player/mpv#4449]
-

**Comment by wiiaboo** [comment]
Who knows? That blog just says "these 4 softwares have fixed vulnerabilities sorta related with subtitles". There's no link to a proof of concept, there's no explanation of what's the attack, just a random video.

**Comment by wm4** [comment]
I also removed the URL as it's essentially advertisement for a "security" company.

**Comment by unic0rn** [comment]
it would help if someone would clarify - since several players are affected, it looks like a vulnerability in a library used by all of them.

"we've contacted them and checked, we're not vulnerable"
"we've contacted them and checked, it's a library we're not using"
"we've contacted them and checked, awaiting for fix in a library"

"NO" and closing the issue without explanation looks like pretending there's no problem - and since it's a security concern, it should be verified. others released patches, so it's not a made up story. "no link to a proof of concept" - would you really like this to go wild when devs are still patching stuff? is it that much of a problem to contact the team that discovered it and ask for the details?

**Comment by rossy** [comment]
> it would help if someone would clarify - since several players are affected, it looks like a vulnerability in a library used by all of them.

This is misleading on the part of the original article. It's actually describing four independent vulnerabilities that they found in each player, for example, the Kodi one is a logic error in their zip decoder and the VLC one is a buffer overflow in their internal subtitle decoder. The only commonality is the attack vector, online subtitle repositories.
