### ISSUE TITLE
MOUSE_BTN5 and MOUSE_BTN6 behaviors on laptop?

### ISSUE THREAD

**Issue by rieje** [mpv-player/mpv#4457]
On my laptop, it seems MOUSE_BTN3 and MOUSE_BTN4 are triggered when I do two-finger scrolling on my laptop (Dell XPS 13). I binded these actions to seek and it works. However, when I two-finger scroll to seek, on occassion, the volume is changed. It seems somehow MOUSE_BTN5 and MOUSE_BTN6 are triggered, causing the volume settings to change. I did a lot of testing and still cannot figure out what triggers MOUSE_BTN5 and MOUSE_BTN6--I see the OSD showing the volume has changed on occassion when I'm seeking. 

How are MOUSE_BTN5 and MOUSE_BTN6 triggerd on a laptop? Any ideas?

 I am on Arch Linux on the latest version of mpv. I can disable the default keybindings of mpv to solve my issue, but it's not ideal and I would like to figure out what's the culprit to perhaps utilize MOUSE_BTN5 and MOUSE_BTN6 my settings.

**Comment by wiiaboo** [comment]
`mpv --input-test --idle --force-window` should show you what keys are triggered when you press them.

**Comment by rieje** [comment]
Yup, that's what I'm using to test. BTN5 and BTN6 when triggered are triggered very briefly. I'm going to use `ignore` as a workaround for the time being.

**Comment by wiiaboo** [comment]
@rossy might know something more about this, he recently did changes to these.

**Comment by rossy** [comment]
My changes shouldn't affect behaviour on X11, but I think I know what's going on here. On X11, BTN3&4 are for vertical scrolling, so moving two fingers up and down. BTN5&6 are horizontal scrolling, so moving two fingers left and right. Depending on the touchpad and the drivers, it can be difficult to scroll up and down without accidentally triggering some left/right events.

I added some logic to prevent this for AXIS events on Windows, macOS and Wayland. On those platforms, when you scroll in one direction, mpv ignores all events in the other direction for 0.2 seconds after the last scroll. Unfortunately it doesn't work for X11 because the X11 backend doesn't generate AXIS events. Maybe this could be fixed by adding support for XInput 2.1 to x11_common?
