### ISSUE TITLE
osc-visibility=always does not work from auto profile (observe scripts-opts)

### ISSUE THREAD

**Issue by ubone** [mpv-player/mpv#4513]
### mpv version and platform
```
mpv --version
mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Jun  8 11:32:00 EEST 2017
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4
```
archlinux (pkg not from repo)

### Reproduction steps
add to ~/.config/mpv/mpv.conf
```
[extension.mp3]
script-opts=osc-visibility=always
```
play mp3 file from file manager

### Expected behavior
osc is always visible

### Actual behavior
osc is auto (default)

### Log file
with mpv.conf [gist log](https://gist.githubusercontent.com/ubone/715f24665beffd4a9fb614b75d6bf778/raw/f175e815079f88d35c104ebfe73bc815d0367a10/mpvlogconf) (does not work)

with `--no-config` and `--script-opts=osc-visibility=always`  [gist log](https://gist.githubusercontent.com/ubone/0cfaa36284e4c4403bce18d8d0beeace/raw/86453de5d46bb2fe85e48d98b39f3a821a3ebf64/mpvlognoconf) (works)

### Sample files
```
# mpv.conf
[extension.mp2]
script-opts=osc-visibility=always
[extension.mp3]
script-opts=osc-visibility=always
[extension.m4a]
script-opts=osc-visibility=always
[extension.ogg]
script-opts=osc-visibility=always
[extension.opus]
script-opts=osc-visibility=always
[extension.flac]
script-opts=osc-visibility=always
[extension.wav]
script-opts=osc-visibility=always
[extension.wma]
script-opts=osc-visibility=always
```

**Comment by avih** [comment]
I understand what happens but not sure how to fix it. mpv loads scripts right when it starts, which includes the osc, and that's the time when the osc also reads its options at script-opts. The file is then loaded and then mpv sets the profile by file extension, but by that time the osc doesn't read scripts-opts anymore (it does respond to script messages though).

You can see at your log that the osc loads before the file-extension profile is set.

The order of first loading the scripts and then the files is unlikely to change, as scripts need to be there when a file loads, and I think it's also unlikely that the osc will be modified to handle changes of script-opts at runtime after it's initialized due to it's relatively delicate code.

IMO your best option for now is to use a script similar to https://github.com/mpv-player/mpv/issues/3500#issuecomment-305646994

**Comment by Argon-** [comment]
> osc will be modified to handle changes of script-opts at runtime

Imo that's the only sane way to fix this. A change to the loading/evaluation-order will only fix this one special case but auto-profiles set during runtime/playback would still have this problem.

**Comment by CogentRedTester** [comment]
Wouldn't something simple like this work:

```
function update_opts()
    opt.read_options(user_opts, 'osc')
    validate_user_opts()
    visibility_mode(user_opts.visibility, true)
    request_init()
end

mp.observe_property("options/script-opts", nil, update_opts)
```

I'm not noticing any problems with this on my computer, but I don't know enough about the osc script to tell if it breaks something.

**Comment by wm4** [comment]
Yes, it would. That still will reinit the OSC any time _any_ script option is changed, though.

**Comment by CogentRedTester** [comment]
True, but it already seems to do that whenever the player is maximised, moved in and out of fullscreen and when the playlist is modified, in comparison script opts are rarely changed during runtime.

The alternative would be to store all the options as a list of strings I guess? And then extract all the strings in script-opts and compare them against the options, and if there are any changes then run updateOpts. Would that actually be more efficient that running renit? I'm asking since I have no idea how renit actually works.

**Comment by CogentRedTester** [comment]
Just in case anyone is interested I modified the function to only reinit when an osc option is changed:

```
local prev_opts = utils.to_string(user_opts)
function update_opts()
    opt.read_options(user_opts, 'osc')

    if utils.to_string(user_opts) == prev_opts then
        return
    end

    prev_opts = utils.to_string(user_opts)
    validate_user_opts()
    visibility_mode(user_opts.visibility, true)
    request_init()
end

mp.observe_property('options/script-opts', nil, update_opts)
```

**Comment by wm4** [comment]
What? This is already in master.

**Comment by CogentRedTester** [comment]
Yes, sorry I wasn't being clear. Using auto profiles such as extension.mp3 does work now on master. But it does not work when using keybinds to apply the profiles throughout playback.

This may be the wrong issue to have posted this on, since the title is talking about the prior functionality. However I noticed that https://github.com/mpv-player/mpv/issues/4669 was closed as a duplicate of this, and that issue is requesting the latter functionality. Therefore, I thought I'd post this for anyone coming from that thread.

**Comment by wm4** [comment]
This should also work.

**Comment by CogentRedTester** [comment]
I've downloaded osc.lua from the git repository and disabled the inbuilt one. The function is successfully changing layout and visibility type when I press a hotkey to apply a profile. It's also returning early when I change other script opts during runtime, so it does seem to be working.

**Comment by CogentRedTester** [comment]
Ok, I did some further testing. The function you added in https://github.com/mpv-player/mpv/commit/b439588172ec97952fb5f9999230f358140f0d14 does run whenever I change options using profiles, however it seems that some settings require reinit to run for them to take effect. Layout is one of those.

**Comment by CogentRedTester** [comment]
You can test this by applying a profile, such as:
```
[profile]
script-opts=osc-layout=box
```

Nothing will initially happen, but when you do something which forces a reinit, such as changing to fullscreen, then the layout changes.

**Comment by wm4** [comment]
I updated master again.

**Comment by CogentRedTester** [comment]
Looks good, I've tested it with around 10 different options and they're all updating immediately.
