### ISSUE TITLE
Cannot change subtitle/audio with DVD menu

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#452]
It is not working to select audio or subtitle languages in DVD menu.
The selection in DVD menu does not affect actual audio track or spu in playback.
Selecting a chapter or other title works well, though.

**Comment by maniacgit** [comment]
I would sign the request to make this also possible using the DVD/Bluray menu in addition to the player controls.

If you use a normal DVD player you have the ability to set this on the remote (mapped to mpv this would be the player controls), but also in the menu. If a normal user will try to switch the language/subtitle he would use the visible DVD menu instead of some key on his remote or command.

**Comment by wm4** [comment]
This would be very complicated (mapping streams, finding sample DVD images for testing...), so I wouldn't count on it any time soon.

**Comment by wm4** [comment]
DVD menu support was removed.
