### ISSUE TITLE
DVD menus

### ISSUE THREAD

**Issue by zyb920** [mpv-player/mpv#4577]
mpv does not support DVD menus ??

Will you add this feature later ?

**Comment by lachs0r** [comment]
No and no.

**Comment by loquesangra** [comment]
You must think you are so clever right? You probably felt like in paradise when you clicked on that "close issue" button. Nothing better than rejecting a request of an useful and cool feature with a passive-aggressive "NYEH HEH, no and NO" and not proposing anything at all. "NOT MY ISSUE! WONTFIX", yet VLC is doing it and you are not, mplayer is doing it and you are not, because it seems you are not competent enough to do so. Fully fledged player? Only when it fits you apparently, all you do is strip features and add typical braindead "fixes" ("muh keybinds were TOO! HARD!"). Is it not super pretty code? It doesn't fricking matter because all you did was take it out because you were obsessing about it being 'unclean'. Your project is useless. Long live mplayer.
