### ISSUE TITLE
Chroma and luma misaligned when using panscan

### ISSUE THREAD

**Issue by Niektory** [mpv-player/mpv#4592]
### mpv version and platform
Versions affected:
mpv-x86_64-20170701-git-69289ae
mpv-x86_64-20170708-git-7c1db05
Versions **not** affected:
mpv-x86_64-20170625-git-7b84a3b and earlier
Using builds from:
https://sourceforge.net/projects/mpv-player-windows/files/64bit/
Platform: Windows 7 64-bit

### Reproduction steps
Play a video (aspect ratio needs to be different from the display's), press `F` for full screen, press `E` for panscan.

### Expected behavior
The video zooms in without artifacts.

### Actual behavior
The video zooms in, but chroma nad luma are misaligned.

### Log file
https://bpaste.net/raw/fe901bf08abc

### Sample files
Happens with every video. Example:
![mpv-panscan1](https://user-images.githubusercontent.com/4470900/27998943-dfb3b368-6516-11e7-9847-9ea84d93959a.jpg)
![mpv-panscan2](https://user-images.githubusercontent.com/4470900/27998946-e9814144-6516-11e7-9869-bfda2151a181.jpg)

**Comment by haasn** [comment]
6eb0bbe312c8422f3180b530126e1dfebb47295e is the first bad commit

**Comment by haasn** [comment]
@wm4 Seems like that commit is fundamentally broken. You replace `xs[n]` by `.chroma_w` on numerous occasions, which is clearly wrong because the multiplier plane-dependent. And it seems like you most likely introduced some sort of other bug in an effort to “fix” the issue where this would make the luma plane half as big (of course, since you were mistakenly applying the chroma multiplier to it).
