### ISSUE TITLE
Hypersensitive mouse controls

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [mpv-player/mpv#4613]
### mpv version and platform

0.24
OS X 10.12.5
Logitech MX Performance mouse

### Reproduction steps

While video is playing, the slightest movement of the scroll wheel forwards/reverses the play position. Even raising the front of the mouse 1/2" and lightly tapping it on the mouse carpet sometimes induces skipping.

### Expected behavior

Should not be so sensitive to unintended movement. Should require deliberate motion of the scroll wheel to change play position. I've not encountered such sensitivity with VLC or Elmedia Player.

### Log file

Log file is blank. I discovered this problem within minutes of installation, while playing the first video.

**Comment by rossy** [comment]
This might be fixed in git master. 937128697fbb adds a small dead-zone to scroll input in order to prevent accidental scrolling.

**Comment by GitTheHellOutaHere** [comment]
Thanks, but I'll have to wait for a release version.
I'm not about to start learning how to compile now.

I had no idea what that page you linked to was talking about - I'd never have known it had anything to do with mouse control. :-)

**Comment by Akemi** [comment]
> This might be fixed in git master. 9371286 adds a small dead-zone to scroll input in order to prevent accidental scrolling.

as far as i know all conventional scroll wheels on macOS are reported as none-precise and the cocoa code handles those as [MP_MOUSE_BTN3/4.](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa/events_view.m#L260). should this be changed to MP_AXIS_* events or are the AXIS events on windows only used because there is no distinction between precise and none-precise scrolling there?

@GitTheHellOutaHere do you use the notched based or the smooth mode for the scroll wheel? when testing the input of the scroll wheel with `mpv --input-test --force-window --idle` what events are reported for it, for both modes (MP_MOUSE_BTN* and/or MP_AXIS_*)?

**Comment by rossy** [comment]
@Akemi 

> as far as i know all conventional scroll wheels on macOS are reported as none-precise and the cocoa code handles those as MP_MOUSE_BTN3/4.

Yeah, that's what I thought as well, so I was surprised to hear that mpv was apparently *more sensitive* than VLC, since with low-precision input, that shouldn't be possible. ``--input-test`` should show what's happening though.

> should this be changed to MP_AXIS_* events or are the AXIS events on windows only used because there is no distinction between precise and none-precise scrolling there?

Actually, I'm not sure what to do with the AXIS/MOUSE_BTN3/4 events. On Windows, I made it only send AXIS events because I couldn't figure out a good way to tell precise and non-precise devices apart (and Windows definitely supports mice with precise scrolling, eg. the Microsoft Touch Mouse.) I'm not sure what it should do on other platforms, since the others all seem to have a way to distinguish precise and non-precise events.

@GitTheHellOutaHere No problem. I understand if you want to wait for the next version (I hope 0.26.0 is out soon,) though compiling on macOS is not too difficult. If you have [Homebrew][1] the following terminal commands will automatically download, compile and install git master:
```
brew install mpv --HEAD --with-bundle
brew linkapps mpv
```

[1]: https://brew.sh/

**Comment by Akemi** [comment]
> Yeah, that's what I thought as well, so I was surprised to hear that mpv was apparently more sensitive than VLC, since with low-precision input, that shouldn't be possible. --input-test should show what's happening though.

indeed i thought the same. lets see what @GitTheHellOutaHere's `--input-test` says.

> Actually, I'm not sure what to do with the AXIS/MOUSE_BTN3/4 events. On Windows, I made it only send AXIS events because I couldn't figure out a good way to tell precise and non-precise devices apart (and Windows definitely supports mice with precise scrolling, eg. the Microsoft Touch Mouse.) I'm not sure what it should do on other platforms, since the others all seem to have a way to distinguish precise and non-precise events.

i see. then i will leave it as is for now. 

@GitTheHellOutaHere if you don't want to compile it yourself you can download [this](https://www.dropbox.com/s/e7unxps9522snz9/mpv.zip?dl=0) for testing. it's build from 18c74f7 and includes @rossy's changes. though i am still interested in what your `--input-test` says about the scroll wheel events.

**Comment by GitTheHellOutaHere** [comment]
When I try **mpv --input-test --force-window --idle** it says *mpv: command not found*

I use smooth-scroll - no clicks.

I downloaded/installed that new version, but it crashes every time. Log is still blank.

Crash report window says

> Process:               mpv [74541]
Path:                  /Applications/mpv.app/Contents/MacOS/mpv
Identifier:            io.mpv
Version:               0.25.0-UNKNOWN (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [74528]
Responsible:           mpv [74541]
User ID:               501

>Date/Time:             2017-07-17 09:38:19.089 -0700
OS Version:            Mac OS X 10.12.5 (16F73)  

>System Integrity Protection: enabled

>Crashed Thread:        10

>Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

>Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]



 
I don't use Homebrew. Installed it once to install an app, but really didn't seem to have any other use for it and uninstalled both.

**Comment by Akemi** [comment]
yeah you have to point to the right binary. in your case `/Applications/mpv.app/Contents/MacOS/mpv --input-test --force-window --idle` should work.

for the new version i would need to see the whole crash report to fix that build.

**Comment by GitTheHellOutaHere** [comment]
**Smooth-scroll mode:**
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] Key MOUSE_ENTER is bound to:
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1



**Click mode:**
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] Key MOUSE_ENTER is bound to:
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1

**Comment by Akemi** [comment]
you should scroll with both modes if possible, pls. since we/i want to know which events the scrolls trigger.

**Comment by GitTheHellOutaHere** [comment]
**Smooth:**

[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] Key MOUSE_BTN3 is bound to:
[input] 1.  'seek 10' in <builtin>:1 (default)
[input] 2.  'script-binding osc/__keybinding6' in section {input} in <api>:4
[input] Key MOUSE_BTN3 is bound to:
[input] 1.  'seek 10' in <builtin>:1 (default)
[input] 2.  'script-binding osc/__keybinding7' in section {input} in <api>:5
[input] Key MOUSE_BTN4 is bound to:
[input] 1.  'seek -10' in <builtin>:1 (default)
[input] 2.  'script-binding osc/__keybinding7' in section {input} in <api>:5

**Click:**

[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] Key MOUSE_BTN3 is bound to:
[input] 1.  'seek 10' in <builtin>:1 (default)
[input] 2.  'script-binding osc/__keybinding6' in section {input} in <api>:4
[input] Key MOUSE_BTN4 is bound to:
[input] 1.  'seek -10' in <builtin>:1 (default)
[input] 2.  'script-binding osc/__keybinding7' in section {input} in <api>:5

**Comment by Akemi** [comment]
okay, as i thought it only reports it as none-precise scroll. so @rossy's patch won't help in that case.
just so i don't misunderstand the issue you are experience. this only occurs when using smooth, not notched, scrolling since the scroll wheel is completely 'free' and easily moves, even when just tapping the mouse slightly?

if yes, we would need to look up what deltas are reported and if those are in any way meaningful. maybe even switch to [scrollingDeltaX/Y](https://developer.apple.com/documentation/appkit/nsevent/1524505-scrollingdeltax?language=objc) instead of deltaX/Y, seems more appropriate anyway. if the deltas are meaningful we could probably just add a threshold for those scroll deltas.

marking this as a macOS issue for now.

**Comment by GitTheHellOutaHere** [comment]
I hadn't tried the player in click-mode before, but it's a problem there too.
The slightest nudge of the wheel - partial clicks, skips the video.
And a decent bump to the mouse can still make it skip.

But I did find that it's comparable to VLC.

The difference being that in order to scroll in VLC the cursor must be over the play position controller, and that's a small area.

In mpv, moving the scroll wheel anywhere over the entire player window scrolls the video.
Scrolling over the controller has no effect, and that's where it should.
Therefore it's MUCH easier to accidentally scroll in mpv.

I guess it's not so much the scroll wheel sensitivity that's the major issue (although less would be better IMO), but where in the window scrolling becomes active. https://goo.gl/bEXeB9

VLC has a setting for the amount of _volume_ steps that occur when scrolling, but apparently not for _video_ back/forward.

**Comment by Akemi** [comment]
you can change the steps for scrolling in mpv too. in your input.conf set `MOUSE_BTN3 seek 5` from the standard `MOUSE_BTN3 seek 10`, to only skip 5 secs of video instead of 10. but yeah that isn't really the problem and unrelated. you can deactivate the video seek on scrolling with `MOUSE_BTN3 ignore` and `MOUSE_BTN4 ignore`.  if you want the scrubber bar on the OSC to be scrollable (video seek), similar to VLC, pls open another issue with a feature request.

tbh if your mouse reports a scroll event in notched mode even though the scroll wheel isn't moved a notch, then the mouse is technically doing something wrong.

 i will see what i can do about it.

**Comment by paulguy** [comment]
Ugh, I have this problem sometimes with my Logitech G9x.  I think it's just a flaw with the mouse.  This happens with pretty much anything that scrolls for me and not just mpv though so maybe it's different?  It goes away and comes back and I can sometimes fix it by quickly scrolling it back and forth.

**Comment by Akemi** [comment]
[this](https://github.com/mpv-player/mpv/files/1167350/scroll.zip) is a little test app that reports the deltas of scrolling in the TextField at the bottom. one notch here is reported as at least ~0.1. @GitTheHellOutaHere could you please test the scrolling again with that app. i am interested in what one notch (in notch mode) and what an 'accidental' scroll reports. depending on your findings we might be able to set an appropriate threshold for the deltas.

for testing it's probably the best to use the test app in fullscreen mode, since only the grey area above the text field reports scroll events.

**Comment by GitTheHellOutaHere** [comment]
Maybe I should have mentioned before that I use Steermouse to increase the cursor acceleration & scrolling speed. I haven't yet tried adjusting the scrolling steps.

I found that this player opens and begins playing faster than VLC and plays videos perfectly that VLC and Elmedia Player have trouble with for the first 30 seconds or so.
But I miss the ⌘+F shortcut for fullscreen.

I've removed the duplicates for you. 🤡

**Scroll**

deltaX: 0.000000 deltaY: 0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.099991
deltaX: 0.000000 deltaY: -0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.09999
deltaX: 0.000000 deltaY: 0.699982 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.699982
deltaX: 0.000000 deltaY: -1.199982 scrollingDeltaX: 0.000000 scrollingDeltaY: -1.199982
deltaX: 0.000000 deltaY: 0.199997 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.199997
deltaX: 0.000000 deltaY: -0.199997 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.199997
deltaX: 0.000000 deltaY: 0.299988 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.299988
deltaX: 0.000000 deltaY: -0.299988 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.299988
deltaX: 0.000000 deltaY: 0.399994 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.399994
deltaX: 0.000000 deltaY: -0.399994 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.399994
deltaX: 0.000000 deltaY: 1.499985 scrollingDeltaX: 0.000000 scrollingDeltaY: 1.499985
deltaX: 0.000000 deltaY: -0.499985 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.499985
deltaX: 0.000000 deltaY: 1.599976 scrollingDeltaX: 0.000000 scrollingDeltaY: 1.599976
deltaX: 0.000000 deltaY: -0.599976 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.599976
deltaX: 0.000000 deltaY: 0.500000 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.500000
deltaX: 0.000000 deltaY: -0.500000 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.500000



**Tilt**

deltaX: 0.000000 deltaY: 0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.099991
deltaX: 0.000000 deltaY: -0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.099991
deltaX: 2.000000 deltaY: 0.000000 scrollingDeltaX: 20.000000 scrollingDeltaY: 0.000000
deltaX: -2.000000 deltaY: 0.000000 scrollingDeltaX: -20.000000 scrollingDeltaY: 0.000000

**Comment by Akemi** [comment]
is the top notched scrolling and the bottom the accidental scrolling from tapping/notching the mouse? if yes the deltas like kinda weird tbh and it won't be possible to tell them apart. reported min of notched scroll is ~0.099, so is the accidental scrolling.

> But I miss the ⌘+F shortcut for fullscreen, as well as a shortcut to skip back/forward 6 second or so. Or maybe it has similar shortcuts I'm just not aware of.

put `Meta+f cycle fullscreen` into your input.conf file, it's in ~/.config/mpv. Shift+UP/Down for 5sec seeks. all standard keyboard shortcuts can be found [here](https://github.com/mpv-player/mpv/blob/master/etc/input.conf)

**Comment by GitTheHellOutaHere** [comment]
The bottom is when you tilt the wheel to scroll sideways.

I haven't touched the config file, nor do I want to.
Guess this app isn't for me since there's no GUI.

**Comment by Akemi** [comment]
though i want to know, like i said, what it reports on an accidental scroll, eg what happens on what you said:

> Even raising the front of the mouse 1/2" and lightly tapping it on the mouse carpet sometimes induces skipping.

> The slightest nudge of the wheel - partial clicks, skips the video.

> And a decent bump to the mouse can still make it skip.

**Comment by GitTheHellOutaHere** [comment]
**Up**

deltaX: 0.000000 deltaY: -0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.099991
deltaX: 0.000000 deltaY: 0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.099991
deltaX: 0.000000 deltaY: -0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.099991
deltaX: 0.000000 deltaY: 0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.099991

**Down**

deltaX: 0.000000 deltaY: 0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.099991
deltaX: 0.000000 deltaY: 0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.099991
deltaX: 0.000000 deltaY: -0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.099991
deltaX: 0.000000 deltaY: -0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.099991

**Bumping**

deltaX: 0.000000 deltaY: 0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.099991
deltaX: 0.000000 deltaY: 0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: 0.099991
deltaX: 0.000000 deltaY: -0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.099991
deltaX: 0.000000 deltaY: -0.099991 scrollingDeltaX: 0.000000 scrollingDeltaY: -0.099991

**Comment by Akemi** [comment]
k, that's kinda bad. even just that reports a completely normal "notched scroll". if i didn't overlook anything, we can't distinguish between a intended scroll and an accidental one.

though what could be changed, since it is a bit sub-optimal, mapping the left and right scroll (tilt) to a different button. so at least those won't trigger a seek.

**Comment by GitTheHellOutaHere** [comment]
Like I said, even making it so the cursor must be over the scrubber instead of the video area would reduce the amount of accidental scrolling.

That's one step in the right direction IMO.

Thanks for looking into this!

**Comment by Akemi** [comment]
> Like I said, even making it so the cursor must be over the scrubber instead of the video area would reduce the amount of accidental scrolling.

to quote myself:
> if you want the scrubber bar on the OSC to be scrollable (video seek), similar to VLC, pls open another issue with a feature request.

**Comment by Akemi** [comment]
with commit b726f1eb9060bf9abbd83a06298c557e25557612 we distinguish between horizontal and vertical scrolls/tilts now, so at least the left and right tilt won't cause unnecessary/accidental seeks anymore.

since the mouse reports an accidental scroll as a normal notched scroll there is no way to solve this problem. so i consider this not our bug.
