### ISSUE TITLE
OpenGL rendering with D3D11VA: interop possible for DX11?

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4629]
### mpv version and platform
0.26 Windows

### Reproduction steps
dxinterop doesn't work with D3D11VA, likely since it's using DX9 for presentation?

### Expected behavior
It would be nice if there was a dxinterop OGL backend which worked with D3D11VA.

### Actual behavior
Currently, we either have to use ANGLE or copyback, which both increase GPU load in comparison to native OGL rendering and decoding. Native DXVA2 has quality problems on Nvidia (and probably also AMD & Intel).
Cuda is ugly too since it suffers more often compatibility issues with certain videos.

**Comment by kevmitch** [comment]
Yes dxinterop uses d3d9 to present the opengl surfaces. I seem to recall @rossy saying something about d3d11 not being as conducive to this method. 

Also, ANGLE is really being pushed as the default, we should probably try and resolve why it is not as efficient for your setup. I know its performance has improved for me on intel such that it is at least at parity with dxinterop. You might want to take a look at some of the angle-related options. Specifically, you might want to check the default --angle-flip=yes and --angle-egl-windowing=no are actually working for you and if so if increase the --angle-swapchain-length beyond 6 helps.

We'd really need to know your windows version and see logs to say more.

**Comment by aufkrawall** [comment]
OS: Windows 10 x64 Redstone 2, GTX 1070 with 384.94

dxinterop (~40% GPU usage, 1.8GHz GPU clock):
http://sprunge.us/INNG

ANGLE (~55% GPU usage, 2GHz clock):
http://sprunge.us/hiVX

Before 384 driver series, performance with ANGLE was even worse. Probably driver still a bit bugged?

However, I've just noticed that DX11 Angle with D3D11VA decoding suffers the same quality penalty as DX9 dxinterop with DXVA2, 10 bit content shows banding which doesn't exist when using software decoding or using hwdec copy mode.
So dx11interop with d3d11va decoding probably wouldn't be any beneficial over the current situation.

-> sticking to dxinterop + dxva2-copy.
dxinterop was btw. also working fine with my Skylake IGP, I can only recommend to make it default setting and don't care about ancient Intel drivers which don't support it.

**Comment by aufkrawall** [comment]
Ok, just realized that the d3d11va quality penalty is only for 10 bit content. But that's bad enough too.

**Comment by haasn** [comment]
> So dx11interop with d3d11va decoding probably wouldn't be any beneficial over the current situation.

That entirely depends on the details of this (hypothetical?) dx11<->opengl interop API. The 8 bit limitation for d3d11va is an ANGLE limitation, they only support NV12 interop.

**Comment by aufkrawall** [comment]
And there is really no way to tell d3d11va to dither down to NV12?
afaik that's what VDPAU with Mesa always does (because Nvidia ceased its further development...). Not optimal to have dithering before the renderer does conversions, but it would probably still show less banding than rounding?

Well, makes a DX11 interop appear more important anyway (but ofc I don't know anything about its possible drawbacks).

**Comment by rossy** [comment]
> Yes dxinterop uses d3d9 to present the opengl surfaces. I seem to recall @rossy saying something about d3d11 not being as conducive to this method.

Back then, Intel didn't support WGL_NV_DX_interop2, so I was worried it would be a lot of work for a less-compatible backend and no tangible benefits. Also, I thought that D3D11 didn't support flip model swap-chains on Windows 7, but I might have been wrong about that. If there are benefits to supporting GL/D3D11 interop, we should definitely look into it.

Also, it might be worthwhile opening multiple GL/DX interop handles on the same GL context. I don't see why presentation and decoding have to use the same interop handle and D3D device. We could probably open a D3D9 interop handle for presentation and a D3D11 handle for hardware decoding.

> Also, ANGLE is really being pushed as the default, we should probably try and resolve why it is not as efficient for your setup. I know its performance has improved for me on intel such that it is at least at parity with dxinterop.

Unfortunately, the angle and dxinterop backends don't have feature parity anymore. ANGLE only supports up to GLES 3.0 (for now,) but recently, mpv got support for things like compute shaders and textureGatherOffset, which require GLES 3.1. The new compute-based EWA kernel gives me a huge performance boost over the old rendering with ANGLE, so there are definitely legit reasons to use dxinterop.

> That entirely depends on the details of this (hypothetical?) dx11<->opengl interop API. The 8 bit limitation for d3d11va is an ANGLE limitation, they only support NV12 interop.

Yep. This is their bizarre NV12-specific EGL streams extension:
https://github.com/google/angle/blob/master/extensions/EGL_ANGLE_stream_producer_d3d_texture_nv12.txt

No idea why they went for that design instead of an extension that could be generalised for multiple texture formats.

**Comment by aufkrawall** [comment]
I think there are definitely benefits which would make it really great to have a dx11 interop, if it allows d3d11va without drawbacks:
-better quality than angle for 10 bit video
-less driver issues than with angle
-likely faster than angle (maybe again because of driver issues)
-better CPU performance than copy modes (allow more heavy CPU work in background when watching a video)
-less RAM consumption than copy modes
-probably also less GPU load than copy modes, since copying lots of data usually doesn't coem for free?
-sums up to likely lowest power consumption for mobile systems
-uncompromised quality, unlike DXVA2 + current dxinterop (DXVA2 increases banding even in 8 bit content and also blurs chroma channel on Nvidia)
-probably much saner than angle for libmpv in ModernUI apps

**Comment by rossy** [comment]
@aufkrawall Agreed for the most apart, though some of those assumptions aren't quite right:

> -less driver issues than with angle
> -likely faster than angle (maybe again because of driver issues)

Actually ANGLE was added because of driver issues. The dxinterop backend works fine with modern non-switchable Intel and NVIDIA graphics, but it can be very buggy with AMD and/or switchable graphics. Bugs include unavoidable BSoDs on startup. ANGLE, on the other hand, works everywhere, which is why it's the default. It can even work on systems without graphics drivers by using WARP for software rendering.

> -uncompromised quality, unlike DXVA2 + current dxinterop (DXVA2 increases banding even in 8 bit content and also blurs chroma channel on Nvidia)

Hopefully, but there are never any guarantees with --hwdec. See the last paragraph of the [Quality reduction with hardware decoding][1] section in the manual. If you don't need --hwdec, eg. for performance or power consumption reasons, it's very strongly recommended not to use it. --hwdec is often the culprit behind subtle decoding errors and it's not as robust as software decoding when dealing with broken files.

> -probably much saner than angle for libmpv in ModernUI apps

I hope you don't mean UWP apps. WGL is deprecated by Microsoft (including WGL contexts created for dxinterop) and not allowed in UWP apps at all. If you want to use OpenGL in UWP, [MSDN recommends ANGLE.][2]

[1]: https://mpv.io/manual/master/#options-hwdec
[2]: https://msdn.microsoft.com/en-us/library/windows/desktop/ee663279.aspx

**Comment by aufkrawall** [comment]
My personal experience with hardware decoding on modern Nvidia GPUs is very good in terms of compatibility with different video files.
At least as long as I don't count cuda, but that's another good reason for d3d11va. :)

My experience with angle and nvidia however is quite different. Actually, it was totally unusable for me with pre 384 drivers.

I admit that I can't judge situation with switchable graphics and AMD.

**Comment by wm4** [comment]
> Ok, just realized that the d3d11va quality penalty is only for 10 bit content. But that's bad enough too.

mpv converts it to 8 bit (depends on the driver what happens and whether there is even dithering and such). This is because ANGLE supports 8 bit mapping only. Of course there's no reason, but good luck trying to get through ANGLE's overcomplicated extensions for this that are all hardcoded to a specific 8 bit format. Maybe if we get native D3D11 support...

**Comment by leavittx** [comment]
Shouldn't this be closed after merging in [Initial ra_d3d11 implementation](https://github.com/mpv-player/mpv/pull/5041) ?

**Comment by aufkrawall** [comment]
I think you're right.

**Comment by Gusar321** [comment]
Well, the actual thing discussed here is not implemented - opengl/d3d11va interop. Which would use the NV_DX_interop2 extension.

The question is, does it make sense to implement it, would it provide any benefits over ra_d3d11? You wouldn't go through the double shader translation (shaderc+crossc), which would possibly provide faster startup and fullscreen transition (and every other scenario where mpv compiles a new shader), but that's it. I don't think runtime performance would be better, as vendors (except maybe Nvidia) generally provide better D3D drivers than Opengl drivers. The only other thing I can think of, is there anything in mpv that works with Opengl, but is not supported by shaderc/crossc?

**Comment by aufkrawall** [comment]
That was the case with HDR peak detection, but this has been addressed recently.
Apart from the shader translation mini-freeze (which can be mitigated a lot with shader chache), I think there are only advantages with D3D11 over OGL with any vendor. :)

**Comment by wm4** [comment]
Don't forget DR.

**Comment by rossy** [comment]
Yeah. I think ra_d3d11 has mostly been an improvement over GL/ANGLE on Windows, but those are the big issues.

> You wouldn't go through the double shader translation (shaderc+crossc), which would possibly provide faster startup and fullscreen transition (and every other scenario where mpv compiles a new shader)

Shader compilation is very slow with ra_d3d11, and it causes delay when starting mpv or resizing the window, but not for the reasons you'd expect.

This is an example of compute shader compilation times:

```
[   2.046][v][vo/gpu/d3d11] Compiled a compute shader in 359709us
[   2.046][v][vo/gpu/d3d11] shaderc: 14153us, SPIRV-Cross: 4352us, D3DCompile: 341204us
```

shaderc and SPIRV-Cross are quite fast. Together, they only take about 19ms. The majority of time (341ms) is spent compiling HLSL to DirectX byte code.

For some reason, compute shader compilation in DirectX is _very_ slow. I have managed to decrease the time by disabling some optimization flags, but it still takes hundreds of milliseconds. It seems like Microsoft expect Direct3D programmers to compile their compute shaders ahead of time. mpv assumes shader compilation is fast enough to be able to dynamically generate shaders at runtime, which is generally true of most OpenGL implementations, but not of Direct3D.

I think this is the most annoying aspect of ra_d3d11, because the stalls can be long enough to break display-sync. Using the shader cache (``--gpu-shader-cache-dir``) makes it better, but there will still be glitches when the cache isn't primed.

> That was the case with HDR peak detection, but this has been addressed recently.

HDR peak detection doesn't work with ra_d3d11 yet. The fixes that have gone in are for automatically _disabling_ peak detection for HDR video on ra_d3d11, because otherwise it errors out when compiling the shader. A real fix is in the works.

Unless I'm forgetting something, peak detection should be the only missing feature in ra_d3d11 that affects picture quality.

> Don't forget DR.

And yeah, this is another big one. DR, as it works in OpenGL and Vulkan, is fundamentally incompatible with D3D11 because there is no persistent texture mapping. D3D11 textures must be unmapped during rendering.

What this means right now is texture uploading in ra_d3d11 is not as efficient as OpenGL with DR, which can be a bottleneck for videos with a large frame size, like 4K. I'm looking for other ways to do asynchronous texture uploading in D3D11, so maybe some day ra_d3d11 will have a DR-like alternative, but that might come with some compromises, like an extra CPU->CPU copy.

> Well, the actual thing discussed here is not implemented - opengl/d3d11va interop. Which would use the NV_DX_interop2 extension.

Yep. I haven't been working on this because ra_d3d11 took priority, but since ra_d3d11 is imperfect for the above reasons, I still think it's valid for people to want to use d3d11va with OpenGL, so adding D3D11 interop with NV_DX_interop2 would be a valid improvement.

**Comment by Hrxn** [comment]
Well, time for D3D12, I guess?
Not that I would really know...but I'm still curious. So consider this a semi-serious question.

**Comment by aufkrawall** [comment]
Thanks for your explanations and clearing out my misunderstanding regarding peak detection, rossy.
I confess I'm also clueless regarding what "DR" could be.

Btw: Zero copy decoding does work really, really great on both Intel and AMD here, it significantly increases performance on both my Atom IGP and also my RX 560.
Just Nvidia seemed to be the odd one when I still had my 1070, it increased CPU load instead of reducing it and GPU load was unchanged instead of reduced.

**Comment by wm4** [comment]
--vd-lavc-dr, which is "zero-copy" (almost) for software mode.

**Comment by Hrxn** [comment]
DR = Direct Rendering?
