### ISSUE TITLE
0.26.0 regression: CUDA doesn't work anymore on Windows

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4630]
### mpv version and platform
0.26.0 on Windows

### Reproduction steps
With 0.26.0, cuda hardware decoding doesn't work anymore on Windows, it uses CPU decoding instead. Codec doesn't seem to matter, happens with both VP9 and H.264. cuda-copy still works.
Only Windows is affected, it still works on Linux.

### Expected behavior
It should work like with 0.25, reverting to this version makes it work again.

### Actual behavior
It doesn't work with 0.26.

**Comment by wm4** [comment]
You don't need cuda on windows.

**Comment by AgnMout** [comment]
Who are you to decide on the other if a feature is needed or not ? Cuda decoding on windows does have advantages upon dxva2 like deinterlacing, better color conversion, best quality of picture...
Cuda worked before and some change in the code broke it, so instead of acting in such an obtuse and rude way, you had better correct the problem and restore the capability.

**Comment by CounterPillow** [comment]
>you had better correct the problem and restore the capability.

jesus fucking christ you entitled cunt

**Comment by wm4** [comment]
>Who are you to decide on the other if a feature is needed or not ?

The lead developer of the project.
