### ISSUE TITLE
save-position-on-quit behaviour

### ISSUE THREAD

**Issue by JonnyThree** [mpv-player/mpv#4641]
### mpv version and platform
mpv 0.26.0 x64
Windows 7 x64
### Reproduction steps
use option: save-position-on-quit
### Expected behavior
do not save audio/video delay (it's "save-position-on quit" not "save-clip-settings-on quit")
### Actual behavior
audio/video delay is saved also

hello, as described, it's possible to discard audio/video delay setting when the player is closed, maintaining the saving of position? sounds strange, but i need this

**Comment by avih** [comment]
> (it's "save-position-on quit" not "save-clip-settings-on quit")

It actually the latter, which includes position and potentially several other settings (if they're different from the default value of your config), seemingly including a-v delay.

**Comment by JonnyThree** [comment]
so, if i use this option, it's forced to save also a/v delay?
no workarounds?

**Comment by avih** [comment]
> no workarounds?

As far as I know, no built in workaround. However, you can map your quit-watch-later key to a script which resets the a-v delay and then issues a quit-watch-later command, for instance.

**Comment by JonnyThree** [comment]
mmh ok, i thought was more simple. i suggest however to correct this setting, and creating another one for the implementation of saving the clip a/v delay and others. 
bye, thanks for the support

**Comment by qoxxxx** [comment]
It's also saving the "paused state", which is annoying .. And there is no setting for just "start playing" AFAIK, right ?

**Comment by qoxxxx** [comment]
I'd prefer an mpv.conf setting, but that will do, thanks.

**Comment by Hrxn** [comment]
?
You can put that into the `.conf`

**Comment by qoxxxx** [comment]
Actually I can't make it work with `pause=no` in _mpv.conf_ . Maybe it's new and isn't supported in 0.26.0 ? I can't find doc anywhere. 
Anyway, the command flag does work.

**Comment by haasn** [comment]
works4me. In fact I put “pause=no” into my config to specifically solve this issue.

**Comment by qoxxxx** [comment]
Well I don't know, "pause=yes" works when I start playing a new file, but it doesn't work again if I quit the video while playing, ie if there's a _watch_later_ config with pause=no inside. So the _watch_later_ config overwrites the _mpv.conf_ config. Maybe I'm doing something wrong..

**Comment by davidde** [comment]
@avih @haasn 
I'd like to echo the request to correct this setting.

`save-position-on-quit` also saves volume, which is really backwards when you set a default volume in mpv.conf; some people happen to listen to way too loud music, forget to put the volume down again, and then get shocked into a heart attack when they open a movie.

**Comment by avih** [comment]
@davidde I don't quite get the issue. The (saved) mpv volume is up to 130 of the maximum, you can't save a value which is 10 times louder than the default - unless your default is very low?

Can you please describe the issue in more details so that someone else can reproduce it?

**Comment by davidde** [comment]
Yes indeed, my default is rather low. I have `volume=20` in my mpv.conf, exactly because it happens often that my system volume is too loud. I find it easier to increase it if necessary, then to think in advance about where the system volume is at, which I will forget to consider anyway.

I understand this isn't the most common use case, but what point is the volume option, if it just gets overwritten by random unrelated options? This kind of puts me in a bind, because I really like `save-position-on-quit`; it is very useful for series and playlists.

I believe the best path forward is either:
-  Fully split these functionalities in two: a `save-everything-on-quit`, and an actual `save-position-on-quit`, that does not save anything else than the position.
- Or provide an exclude list to which users can add exceptions not to be saved.

Regardless, I really love MPV. Keep up the good work.

**Comment by avih** [comment]
> I believe the best path forward is either:

Feel free to submit a PR.

Regardless, personally I think that if this is to be changed, then a better approach would be to have a configuration value which controls which values get saved, other than position.

**Comment by davidde** [comment]
Yes, while I was thinking about it some more, I feel that it would be best to create a general `save-on-quit` option that is fully customizable as to what it saves:
-  `save-position-on-quit` could then possibly be established as a specific case of the former that only saves the position.
- At the same time `save-on-quit` would provide more control to everyone that needs more specific behavior, and neither would anyone depending on current functionality lose features.

Can you point me to the files where this functionality is defined?

**Comment by avih** [comment]
You should start with this https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md .
I don't know where the relevant code is, you'll have to look it up.

**Comment by wm4** [comment]
player/configfiles.c

**Comment by davidde** [comment]
Great, thanks.

**Comment by CrendKing** [comment]
As I understand, this behavior is due to the [`backup_properties`](https://github.com/mpv-player/mpv/blob/master/player/configfiles.c#L240) introduced from https://github.com/mpv-player/mpv/commit/ce9a854d54900d050cf1efcf26081d875223e448. The commit message has this:

> (which is probably not what you would expect, but in general nobody will really care about this)

Since then, some more properties are [added to the list](https://github.com/mpv-player/mpv/commit/b19414f3bf0ae28461ef6d5048e9626e69d45319), some of which can be really confusing, such as the `vf` property.

I understand the original intention why it is there, but having no control over such important behavior is lacking. Am I correct that you guys welcome PR to add more control over this? If so, should it be one general ON/OFF setting (as `load-scripts`) or granular settings that control each individual property plus a "all" option (similar to `reset-on-next-file`)? Being the latter means when `backup_properties` expands in the future, this setting also needs to be maintained to expand.

Is anybody working on this? If not, I might want to give it a try, even though I'm completely new to mpv.

**Comment by CrendKing** [comment]
Just FYI, since there won't be a change of the behavior officially, here's my Lua script to tackle the issue. It's rough solution, which removes all backed properties except "start", so if you want more properties, you need to modify.
```
-- remove all backed up properties in watch_later except "start"

local utils = require "mp.utils"
package.path = utils.join_path(mp.find_config_file("repo"), "md5.lua") .. "/md5.lua;" .. package.path
local md5 = require 'md5'

local watchLaterDir = mp.find_config_file("watch_later")

local function cleanWatchLater(hook)
    local path = mp.get_property_native("path")
    local hash = md5.sumhexa(path)
    local hashFilePath = utils.join_path(watchLaterDir, hash)

    local hashFileIn = io.open(hashFilePath, "r")
    if hashFileIn ~= nil then
        -- relying on the fact that "start" is always at the first line
        local firstLine = hashFileIn:read()
        hashFileIn:close()

        local hashFileOut = io.open(hashFilePath, "w")
        hashFileOut:write(firstLine)
        hashFileOut:close()
    end
end

mp.add_hook("on_unload", 50, cleanWatchLater)
```
