### ISSUE TITLE
Stuttering Audio on Android with bluetooth audio device.

### ISSUE THREAD

**Issue by Neo-Oli** [mpv-player/mpv#4672]
### mpv version and platform
0.26.0 on Android/Termux (also reported in App)

### Reproduction steps

Play any audio file

### Expected behavior

No stuttering.

### Actual behavior

Periodic stuttering. ~every few seconds See 

1. It only happens when connecting to a bluetooth device. It works fine over speakers.
2. It happens with various kinds of bluetooth devices
3. No problem using other audio players. 

See https://github.com/termux/termux-packages/issues/1127 for more information.

Adding `--audio-buffer .5` helps significantly. And per info in the man page, this is my report of that. 

> This option should be used for testing only. If a non-default
> value helps significantly, the mpv developers should be
> contacted.

### Log file
http://sprunge.us/CVVF

**Comment by wm4** [comment]
Missing log.

**Comment by Neo-Oli** [comment]
@wm4 Added a log file. I played a music file and waited for it to stutter.

**Comment by tomty89** [comment]
I am not sure if this is entirely an issue of mpv. Apparently the Android (OpenSL ES) allows really low device buffer (50ms that is). 200ms is apparently the safe guard in mpv.

I tried --audio-buffer=0.05, which is the lowest possible value since the soft buffer cannot be set to lower than the device buffer. It works fine in the wired audio cases, but with Bluetooth the audio pretty much became garbage.

In my test, soft buffer of 250ms (if it matters, 5 times of the reported device buffer, while the safe guard happens to be 4 times) can guarantee a stutter-free Bluetooth playback (again, if it matters, on aptX encoder, not sure about SBC).

I also tested with `-ao openal`. The device buffer is fixed at 32000 samples (regardless of the requested sampling rate).

Interestingly, it works fine if the sampling rate is no higher than 128000 (where 32000 sample will be 0.25ms or more), but if the sampling rate is 160000 or higher (where 32000 samples will be 0.2ms or less), the audio glitches regardless of wired or bluetooth and the soft buffer size (i.e. not even `--audio-buffer=1` would help).

**Comment by tomty89** [comment]
Btw the `Failed to Enqueue: 7` errors are probably irrelevant. It pretty much always occurs when the playback is resumed from a pause (and sometimes in the start of the playback). I do consider it as a separate issue, tho it is relatively trivial.

**Comment by tomty89** [comment]
Oh looks like we may want a higher default (250? 500?):
https://github.com/mpv-player/mpv/blob/1a2319f3e4cc42c680e2fd3ba30022c7a9adf3fe/audio/out/ao_opensles.c#L104

**Comment by Dudemanguy** [comment]
Pre-audio rewrite so it's possible this doesn't exist anymore. If it still occurs, please open a new issue.
