### ISSUE TITLE
Option to autoload relative files only

### ISSUE THREAD

**Issue by unknown--** [mpv-player/mpv#4703]
Would it be possible to add an option that makes the autoload script search for related files rather than every other file in the directory?

**Comment by bitingsock** [comment]
Yes, I've considered doing this myself. Stand by, I'll try it later.

**Comment by haasn** [comment]
Maybe compare based on string edit distance and use a cutoff value

**Comment by bitingsock** [comment]
I was thinking of just using a modifiable percentage match of all the characters in the file name. I'm not sure what OP means by "related" though.

**Comment by avih** [comment]
It's not clear to me what this is about. Is it related to `autoload.lua` - https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua ? or mpv internally? and what are "related files" compared to "every other file in the directory?"

**Comment by bitingsock** [comment]
I assumed it is for the lua script and I assumed it was a use case where all media files are just dumped into one directory with no organization aside from naming.

**Comment by avih** [comment]
Well, in that case, "related" is both quite vague and actually not easy at all to estimate usefully.

I'm talking from experience of having written an even more fuzzy subtitles match using levenstine distance (about 15 LOC for the lev function in c/js/lua - I adapted a C version to JS and lua), but it turned out quite hard to be effective. Sometimes the distance is very big but for a human they're very related.

I ended up with a complex weights and filter functions (which knows to ignore punctuation, give more weight to the beginning of the string or a lot of weight to things which looks like S01E02, and less weight to stuff like 720p or h264 etc). And it's quite all right, but i wouldn't call it perfect by any means, even for the task of finding the best sub. It does find what it considers "best" but then it's hard to define a very effective threshold above which it can be considered "correct". It works, but it's not a trivial task :)

**Comment by bitingsock** [comment]
Ya, I'm going to hold off.

**Comment by v-fox** [comment]
@Akemi Why was this silently closed ?

**Comment by Akemi** [comment]
just issue grooming and seeing if anyone still cares. please open a new issue with an easy to understand explanation of the problem, since it's not clear to me what exactly is wanted here.

**Comment by v-fox** [comment]
> just issue grooming and seeing if anyone still cares. please open a new issue with an easy to understand explanation of the problem, since it's not clear to me what exactly is wanted here.

@Akemi Originally, it was about impracticality of autoload.lua's aggressiveness in just lumping all files together then it switched to general impracticality of auto-loading all files and overly-strict matching of 'fuzzy' options which is the reverse-problem of that. Meaning, that, as it is, both mpv's options (exact/fuzzy & all) for auto-loading files in all situations (playlists, subtitles, audio-tracks) are of little use. @avih outlined problems with trying to make better filename-matching heuristic.

Now, how to "fix" that can range
* from simple "at least match \*\<opened_file_name_minus_extension>* for everything already and integrate autoload.lua stuff in playlist handling code for it to use the same matching code as subtitle and audio loading" to
* "do case-insensitive percent-based 'similarity' checking for \<words_from_opened_file_name>+<words_from_files's_track-names>  for all files in the same directory (+ tunable list of expected subdirectories) that would allow insignificant differences like word order then check if 'related' video-files are video-tracks or playlist-entries" and 
* "use temporary on-disk meta-data (including per-file playback settings, as smplayer does) gathering (in ~/.cache/mpv or something) for all media-files from directory of every opened file and matching "relations" with tunable weighting options to determine how "appropriate" they are to autoload as a audio/video/subtitle stream or a playlist entry" which would also require periodic meta-data cleanup by age and size limits in background that can be shared with cleanup code for shader and network playback caches.

So, I'm not sure what to propose and just continue manually renaming all my files into something mpv can easily digest.

**Comment by unknown--** [comment]
I came up with a flimsy solution a while ago. Upon autoload appending a file to the playlist it checks a few keywords drawn from the currently playing file against the file that is to be added to the playlist. If there's no match then it gets skipped. It works most of the time.
