### ISSUE TITLE
Pulse driver fails to initialize for passthrough audio

### ISSUE THREAD

**Issue by qzdanis** [mpv-player/mpv#4801]
### mpv version and platform

mpv 0.26.0-44-g345bb193fe

### Reproduction steps

Invoke `mpv` on a file with Dolby TrueHD or DTS-HD MA audio with the following options: `--ao=pulse --audio-spdif=truehd,dts-hd`

### Expected behavior

Audio is passed through to external hardware for decoding.

### Actual behavior

Initialization of the pulse driver fails, then mpv falls back to internally decoded audio.

### Log file

http://sprunge.us/MOHC

**Comment by wm4** [comment]
It just gives us PA_STREAM_FAILED, so I declare this a pulse bug. Try ALSA.

**Comment by qzdanis** [comment]
ALSA complains about only finding stereo output. See http://sprunge.us/VIOM

**Comment by lachs0r** [comment]
That’s because it uses your `default` PCM, which only supports 2 channels and likely goes through analog output, with software mixing inbetween. You do have to tell it to use the correct audio device. See `--audio-device=help`.

Also, if you’re using HDMI, you can simply avoid passthrough. Hardware decoding doesn’t really have any advantages. Output is lossless either way.

**Comment by qzdanis** [comment]
Thank you! I found which alsa device corresponded to the right output on my GPU and now passthrough is working. Closing this issue as it's not directly related to mpv anymore.
