### ISSUE TITLE
mpv 0.26.0 fails to build with ZSH option

### ISSUE THREAD

**Issue by cpu82** [mpv-player/mpv#4814]
### mpv version and platform

mpv-0.26.0 on FreeBSD 11.1-RELEASE/amd64

### Reproduction steps

`cd /usr/ports/multimedia/mpv && make install clean`

### Expected behavior

Build and install fine.

### Actual behavior

mpv fails to build with ZSH option enabled.

### Log file

https://bz-attachments.freebsd.org/attachment.cgi?id=185838

### Reference

This bug has been reported via bugzilla:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=221876

**Comment by qmega** [comment]
I'll look at this tonight. I don't have a FreeBSD machine anymore, so if it's not reproducible on Linux I'll need some more information.

You should have gotten a different error if mpv failed to run entirely, so it seems like the format of the options is somehow different than expected. Please run "build/mpv --list-options" and provide the output of that. If you could bisect that would be helpful as well.

**Comment by qmega** [comment]
@cpu82 Can you reproduce this on your own machine or is it only happening to the user that reported it to you? If it's the latter, we need the `--list-options` output from their machine, naturally.

**Comment by qmega** [comment]
Talked to the user on the FreeBSD bug tracker. Turns out they were cross-compiling. The way we currently generate ZSH completion is known not to work in that case, which is exactly why it's disabled by default, IIRC. (I'm not sure why it didn't die with an exit code in this case, though.) I think I'll take a shot at moving the completion generation to runtime somehow this weekend, but anyway this issue can be closed.

**Comment by cpu82** [comment]
I agree. This issue can be closed now.

Thanks for looking at this!
