### ISSUE TITLE
Crash when using "remember time position" of SMPlayer

### ISSUE THREAD

**Issue by omerfarukdogan** [mpv-player/mpv#4816]
mpv version: 0.23.0-git-10a005d (still exists in 0.26)
platform: SMPlayer on Windows 10

When I try to play some video files the second time, SMPlayer freezes and says mpv has crashed (SMPlayer is using mpv as its back-end). I noticed that the problem appears when "remember time position" setting is checked in SMPlayer. Note that MPlayer doesn't crash if used as the back-end of SMPlayer.

I have used --log-file option to get logs.
Log for "remember time position" setting enabled (CRASH): https://pastebin.com/3ih5hD9L
Log for "remember time position" setting disabled: https://pastebin.com/gx594s8t

**Comment by wiiaboo** [comment]
Do the logs with 0.26 at least.

**Comment by avih** [comment]
The log suggests hevc clip with hwdec on Intel gpu.

On my system (Windows 8.1, i7-4500u - hybrid hevc hwdec driver) this combination always crashes or hangs, and has been iirc since forever, and happens also with latest ffmpeg (git) and mpv. It doesn't crash if not resuming watch-later. It sometimes crashes also if seeking repeatedly very quickly (on hevc+hwdec on intel).

The only solution I know of is to disable hwdec (maybe only with hevc? maybe using auto-profiles?), or don't quit-watch-later, and instead seek manually to where you last stopped.

Generally speaking, swdec is recommended due to higher quality and less driver bugs, so you might as well just disable hwdec and be done with it.

FWIW, if you're using 64 bits mpv, then in my experience swdec does not consume more power than hwdec, for neither h264 nor h265. With 32 bits mpv, swdec consumes a bit more than hwdec. Though my observations are only on haswell with hybrid hwdec driver.

So it's probably either intel driver bug, or ffmpeg issue interacting with it.

**Comment by wm4** [comment]
Fairly sure the hevc sometimes crashing bug is a driver issue. All mpv-side code is the same for h264 and hevc, and the ffmpeg-side code is almost the same for both codecs.
