### ISSUE TITLE
freeze when cycling fullscreen (libmpv using wid)

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#4825]
I've build a libmpv based player using dotnet and get a freeze of about one second when I cycle full-screen, it's arbitrary, maybe one out of 4 tries. I use wid and know that opengl is recommended, I don't know if it's possible and easy enough to do with dotnet, are issues like this freeze the reason why opengl is recommended over wid? I've struggled a bit with mouse and keyboard messages but with your help have everything working fine. The freeze is not a big issue but it still would be nice to have it working perfectly. Maybe there are some settings I can try. I could also try to get it working with C++ to see if it has something to do with winforms, I had some linker issues last time I tried it with C++, other then this and one or two other small issues my experience has been very good. So far my project is mostly for personal use, for my app staxrip and maybe to help some dotnet programmers, it's located here:

https://github.com/stax76/mpvnet

**Comment by dreness** [comment]
Does the freeze happen if you are moving the mouse as you press 'f' to enter fullscreen mode? On my (win10) machine, doing this avoids the freeze 100% of the time, and if I don't, the freeze happens almost every time I enter fullscreen. I don't know why this happens, and have played with every relevant setting I can get my hands on.

I'm not sure my problem is the same as yours, so I won't pile on here, but I did want to give a quick shout since this is an easy test. I'll be opening a new ticket for my problem.

**Comment by stax76** [comment]
For me it's gone. Do you have the latest Windows Update and latest driver?

**Comment by dreness** [comment]
@stax76 Yeah. Here's the details on my issue: https://github.com/mpv-player/mpv/issues/5110 (note that I'm not using libmpv with a separate app, just mpv itself)
