### ISSUE TITLE
Incorrect mouse button mapping on latest builds

### ISSUE THREAD

**Issue by kevin-stuart** [mpv-player/mpv#4835]
I updated to the latest version of mpv and to me it seems that somehow the mouse buttons are suddenly shuffled around. See report below for details.

Is this intended? Are button numbers changed permanently? The old numbering made more sense with 0, 1, 2 mapped to left, right, middle. The wheel followed and then the side buttons. Now it seems strange and the output has 7 and 8 as new numbers, but no 3 and 4 (I think). It was confusing to me.

### mpv version and platform

Windows build 20170718.
https://mpv.srsfckn.biz/mpv-x86_64-20170718.7z

### Reproduction steps

Use mouse wheel up and down, use mouse buttons forward and backward.

### Expected behavior

Wheel produces `MOUSE_BTN3` and `MOUSE_BTN4`.
Forward and back mouse buttons procudes `MOUSE_BTN5` and `MOUSE_BTN6`.

### Actual behavior

Wheel produces `MOUSE_BTN5` and `MOUSE_BTN6`.
Forward and back mouse buttons procudes `MOUSE_BTN7` and `MOUSE_BTN8`.

### Log file

N/A

### Sample files

N/A

**Comment by rossy** [comment]
Yeah, the button numbering has changed permanently. mpv's button numbering is based on X11, which has buttons 3, 4, 5 and 6 as the scroll wheel (up, down, left and right) and 7 and 8 as back and forward. On Windows, it was incorrectly using buttons 5 and 6 as back and forward. Now it's the same on all platforms.

> Wheel produces ``MOUSE_BTN5`` and ``MOUSE_BTN6``.

This is strange though. Are you sure it produces these keycodes? mpv 0.26.0 _should_ produce the ``AXIS_UP`` and ``AXIS_DOWN`` keycodes instead.

> Forward and back mouse buttons procudes ``MOUSE_BTN7`` and ``MOUSE_BTN8``.

This is correct, but you're right. I don't like this numbering either. In mpv 0.28.0 you will be able to use button names such as ``MBTN_FORWARD`` and ``MBTN_BACK`` instead of numbers, which might make this less confusing (the numbers will still work, but the names are easier to remember and less likely to change in future.)

**Comment by kevin-stuart** [comment]
According to your explanation, shouldn't 3 and 4 then still be mapped to up and down and listen to events then in the input.conf? I had that in my config before. This was my main gripe, because I don't know what 3 and 4 are used for now. I'm actually OK with 7 and 8 for forward and back.

It's nice that new names for forward and back are coming and if up and down can be done with axis names, then I will use that. If this is renaming is no bug and will at stay stable now, I can update my config files. It's solved for me then.

**Comment by rossy** [comment]
> According to your explanation, shouldn't 3 and 4 then still be mapped to up and down and listen to events then in the input.conf? I had that in my config before. This was my main gripe, because I don't know what 3 and 4 are used for now.

Yep, though this comes down to another issue (which is totally my fault.) mpv 0.26.0 had different keycodes for scroll events that originate from _non-precise_ devices, like a mouse scroll wheel, and scroll events that originate from _precise_ devices like a laptop touchpad. For the former, it was supposed to use ``MOUSE_BTNn`` and for the latter, ``AXIS_UP``, ``AXIS_DOWN``, etc.

But this didn't really work. Unfortunately, on Windows, it's impossible to tell whether an event came from a precise or non-precise device. In mpv 0.25.0, it treated all scrolls as non-precise, so they all generated ``MOUSE_BTNn``. In mpv 0.26.0 it was changed to treat all scrolls as precise, so they all generate  ``AXIS_UP``, ``AXIS_DOWN``. This change was poorly communicated and it broke a lot of users' input.confs.

In mpv 0.27.0 we will scrap the whole idea of _precise_ and _non-precise_ scrolls, so this won't be a problem. All devices on all operating systems will use the new ``WHEEL_UP`` and ``WHEEL_DOWN`` keycodes, and they will all support ``MOUSE_BTNn`` and  ``AXIS_UP``/``AXIS_DOWN`` as aliases, so that existing input.confs will continue to work without modification. Sorry for the inconvenience.
