### ISSUE TITLE
sub-text-back-color generates some artifacts

### ISSUE THREAD

**Issue by alejandro-perez** [mpv-player/mpv#486]
Hello,

I like using sub-text-back-color for better readability of subtitles (i.e. black boxes). However, when using alpha channel for translucent color, these boxes overlap (see image attached).
![captura de pantalla - 160114 - 19 47 14](https://f.cloud.github.com/assets/2082536/1933644/eb56ef5e-7ede-11e3-8a7a-b4289fa0186a.png)

This can be partially improved by decreasing sub-text-border-size to 0.01 (or lower), but then some artifacts appear (see image attached)
![captura de pantalla - 160114 - 19 42 48](https://f.cloud.github.com/assets/2082536/1933661/14bdea78-7edf-11e3-98cd-c267be28a31f.png)

I don't recall this issue using classic mplayer.

Regards

**Comment by vitormathews** [comment]
How do you make the sub-back-color go around the letters instead of forming a rectangle?

I want this:
![image](https://user-images.githubusercontent.com/51209382/208284441-24afb0e4-fcad-412d-b7d4-392f331c76f8.png)

I got this:
![image](https://user-images.githubusercontent.com/51209382/208284489-9d9a2b9f-4115-47cc-ba58-83a7468b1bab.png)

**Comment by rofrol** [comment]
@KonoVitoDa `sub-border-style=opaque-box`

**Comment by rofrol** [comment]
https://github.com/libass/libass/issues/657#issuecomment-1297571043
