### ISSUE TITLE
hwdec=auto broken for vaapi in v0.27.0

### ISSUE THREAD

**Issue by foutrelis** [mpv-player/mpv#4865]
Bisected to commit 96462040ec79b353457b64949f96fad30bd6e988.

On a laptop with Intel HD Graphics 4400 (no discrete GPU), mpv will no longer automatically select vaapi for hardware decoding. Instead it will print the following error and revert to software decoding:

```
[ffmpeg] Cannot load libnvcuvid.so.1
[ffmpeg/video] h264_cuvid: Failed loading nvcuvid.
Could not open codec
```

After installing nvidia-utils, mpv will still use software decoding but print a different error:

```
[ffmpeg] AVHWDeviceContext: Could not initialize the CUDA driver API
Could not open codec.
```

This used to work in versions 0.26.0 and earlier; mpv would automatically use vaapi for hardware acceleration:

```
Failed to open VDPAU backend libvdpau_i965.so: cannot open shared object file: No such file or directory
Using hardware decoding (vaapi).
```

I'm on Arch Linux x86_64 and have the following software installed:

```
mpv 1:0.27.0-1
ffmpeg 1:3.3.3-2
libva 1.8.3-1
libva-intel-driver 1.8.3-1
```

**Comment by mc4man** [comment]
That certainly seems to be the case.
At least here the intent of the commit worked without moving the vaapi section down though did produce a red message about libva/vaapi before going ahead & using cuda-copy.
If just the vaapi-copy part was moved like vdpau-copy then the intent worked without any messages & vaapi worked fine on intel machine with --hwdec=

**Comment by matoro** [comment]
I am not sure why this is closed, this still seems to be a problem without a discrete GPU.  Setting `hwdec=vaapi` will handle it but the the error message still appears with `hwdec=auto`.  This is with the following packages:

```
mpv 1:0.27.0-4
ffmpeg 1:3.4-4
libva 2.0.0-2
libva-intel-driver 2.0.0-2
```

**Comment by CounterPillow** [comment]
@matoro it's closed because it was fixed in git master, there just hasn't been a release version since then.

**Comment by matoro** [comment]
@CounterPillow Great, thanks.

**Comment by zezinho42** [comment]
It is a pity this patch wasn't applied to 0.27 branch : end users in distros can't use the 0.28 as ffmpeg is too recent, and have updated to 0.27.1 for the security fix. Can we hope a 0.27.2 with this small fix that changes completely the mpv experience?

I discovered this bug because suddenly mpv did not played my 1080p movies nicely... after my distro pushed the 0.27.1 update!

**Comment by CounterPillow** [comment]
>mommy can I have a package

no. Use mpv-build if you must.

**Comment by zezinho42** [comment]
You misunderstood me : I am packaging mpv for Mageia distro. I pushed an update from 0.25 version to 0.27.1 because of the security fix, and we ended with a broken vaapi playing. This is why I asked such regressions to be backported in latest packagable mpv (0.28 needs an unrealeased ffmpeg)

**Comment by kevmitch** [comment]
The answer is still no. The fact that we had a point release at all is exceptional. Our usual policy is if you want something in master, use master or backport yourself. Maintaining features or even bug fixes in release branches is not a good use of our developer time since past experience has shown distros just ignore them anyway. 

Also, the current point release is already 0.27.2 / 0.28.2.

**Comment by zezinho42** [comment]
Thank you for the answer. As a distro, we usually upgrade to latest mpv. Here the problem is that it requires an unreleased dependency. You can't expect distros to update to such version, as each distro backporting by itself is much more time consuming. At the end, I think most distros for now ship 0.27.2 with vaapi broken, and it is a pity.

Still, I understand your view, so let's forget this for now. ;-)

**Comment by mc4man** [comment]
On 02/17/2018 06:07 AM, zezinho42 wrote:
>
> Thank you for the answer. As a distro, we usually upgrade to latest 
> mpv. Here the problem is that it requires an unreleased dependency. 
> You can't expect distros to update to such version, as each distro 
> backporting by itself is much more time consuming. At the end, I think 
> most distros for now ship 0.27.2 with vaapi broken, and it is a pity.
>
> Still, I understand your view, so let's forget this for now. ;-)
>

You could simply make a small change to video/decode/vd_lavc.c and 
hwdec= (or hwdec=yes, hwdec=auto) will work fine with a vaapi machine.
As far as --opengl-hwdec-interop=cuda --hwdec=yes that will also still 
work as intended

https://0x0.st/sT4Q.diff
>
