### ISSUE TITLE
mpv playlist pause(s)

### ISSUE THREAD

**Issue by clu--** [mpv-player/mpv#4889]
### mpv version and platform
mpv 0.27.0 from https://mpv.srsfckn.biz/mpv-x86_64-20170913.7z on win7pro64

### Reproduction steps
.> dir /w
  [.]  [..] 49.wav 48.wav 47.wav 46.wav 45.wav a.lst
.> type a.lst
    pauses 5000
    49.wav
    48.wav
    47.wav
    46.wav
    45.wav
.> mpv.exe -v --log-file=C:\tmp\a.log --shuffle  --playlist a.lst 

### Expected behavior
mpv plays .wav files and inserts an interval of 5000ms between consecutive files

### Actual behavior
mpv plays the files as if the line
    pauses 5000
did not exist

rem : same applies for pause -instead of pauses- as seen in http://www.atrise.com/tvp/howto/create-playlist/

### Log file
https://pastebin.com/6CXR3wVU  (with shuffle)
https://pastebin.com/2snxZs16  (w/o shuffle)

### Sample files
any set of audio/video files since playing the content is not the issue here (it works) but the interval between files

**Comment by Dudemanguy** [comment]
I believe this is meant to be a feature request (the ability to insert arbitrary waiting periods between files). While it certainly would not be impossible to implement in mpv itself, I don't think anyone wants to introduce such complexity to the mpv core. This can easily be accomplished with a trivial lua script so that's the right way to go.
