### ISSUE TITLE
Error load script with non-english dir name

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#4903]
### mpv version and platform
mpv 0.27.0 x64 from https://mpv.srsfckn.biz/
windows7 SP1 x64

### Reproduction steps
If mpv is located in a directory and the name is not english,i test in chinese japanese and korean dir name.
mpv can play file but lua script load error and show no such file or dir.

### Log file
It's a sample when i use chinese dir name.
http://i.imgur.com/5L2a6Tp.png

I don't know if it is a bug or not,thanks for watching.

**Comment by Geograph-us** [comment]
I have the same bug in mpv 0.29.0-107

Windows 10 x64 - cyrillic-path to folder "portable_config".
LUA-scripts can't load but JS-scripts load successful.

I think the LUA library which used in MPV can't work correctly with windows paths (in ANSI encoding) and tries to work with UTF-8 paths.

**Comment by Geograph-us** [comment]
Temporary solution load scripts manually in mpv.conf (file must be in ANSI encoding):
`load-scripts=no
script=C:\Плееры\MPV\portable_config\scripts\mines.lua
script=C:\Плееры\MPV\portable_config\scripts\youtube-quality.lua`

**Comment by zc62** [comment]
This is very OS specific. In Linux, even I use `convmv` to rename a lua script to other non-UTF-8 encodings, the lua script still loads. It depends on the Windows open file API the upstream lua uses.

Don't know if mpv could translate the path string so that lua will accept it. It is possible that the lua library does not use a Windows open file API that supports UTF-8 path at all. In this case, even if mpv could translate the path, open file may still fail. And there are several different lua implementations that one can choose to build mpv with. One may work and another may not.

The best solution for now might be, just do not put mpv in a non-English directory. Something like `C:\mpv\` should work just fine. If you insist on organizing portable programs in a non-English directory, probably it's time to change your habit.

**Comment by garoto** [comment]
Computers should be operated in an ASCII mode mindset when naming files and dirs that you have control of, regardless where you are in the world or what your native language is. Saying this as someone whose native language is full of  `çáéúõ`  and useless shit like that.

Surely this approach to all things computing seems like the less painful one IME.

**Comment by Dudemanguy** [comment]
I think this pretty much just OS-dependent. I have no knowledge of what windows does here, but I don't think trying trying to figure out some kind of workaround/hack for this is worth it.
