### ISSUE TITLE
Allow OSC showtext to be use as a keybind

### ISSUE THREAD

**Issue by 1ll3g4l** [mpv-player/mpv#4927]
Shift+Left Click on icons display lists rather well compare to what you can make on input.conf.
 [displaying lists on mpv is rather painful](https://i.imgur.com/93oqS9v.png)
[compared to using shift+Left click on next/prev in the OSC](https://i.imgur.com/UTn7a6w.png)
adding a name like [show-progress](https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L80) to these would be nice.

**Comment by avih** [comment]
If by "rather well" you mean "smaller font size", then you can do that at `input.conf` too:
```
b show-text ${osd-ass-cc/0}{\\fscx50}{\\fscy50}${playlist}
```

**Comment by Argon-** [comment]
@avih this used to work (and I also did it like that) but since the representation returned by `${playlist}` is itself formatted using ASS it breaks when you try to add your own.
@1ll3g4l you can get the OSC representation by using e.g.

    x      script-message osc-chapterlist
    c      script-message osc-playlist
    v      script-message osc-tracklist

This shows the OSC styled lists. However, it does so by asking the OSC script to print them, so it only works when the OSC is enabled (i.e. don't use `--no-osc`).
There are more advantages to the OSC's representation than just a smaller font size by the way, it actually resizes based on a few heuristics to fit more stuff on the screen.

**Comment by 1ll3g4l** [comment]
Thank you @Argon- can I separate osc-tracklist into sub/audio list independently?

**Comment by Argon-** [comment]
No

**Comment by avih** [comment]
> it actually resizes based on a few heuristics to fit more stuff on the screen.

It seems to get it wrong for me. While the normal OSD font size scales with the window size, the OSC lists font size do not, and actually show in huge size (i.e. I can see only 3-4 chars width of them in the window) when the window is very small (think PiP mpv window size).

**Comment by Argon-** [comment]
Well, as I said, it's just a heuristic, nothing "more". But it works well for me.
https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L692
