### ISSUE TITLE
Application (mpv.app) crashes

### ISSUE THREAD

**Issue by wickedsp1d3r** [mpv-player/mpv#4941]
### mpv version and platform

0.27.0
macOS High Sierra 10.13

### Reproduction steps

`brew install mpv --with-bundle`
or
`brew cask install mpv`

Double-click a video file to play it or just double-click `/Applications/mpv.app` to start the application.

### Expected behavior

mpv starts playing a file.

### Actual behavior

mpv crashes.
This happened also with macOS Sierra.
Started happening since 0.27.
Opening video file via command line works without problems.

### Log file

Console.app / system.log says:

`com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000e.mpv-wrapper.sh[6060]): Service exited with abnormal code: 127`

`com.apple.xpc.launchd[1] (io.mpv.2532[6799]): Service exited with abnormal code: 127`

**Comment by Akemi** [comment]
if it really crashes you should get a report of the crash, which would be interesting. otherwise make a log with `--log-file=log.log`, if that doesn't work it's most likely one of the issues below.

if it's the same on 10.12 and 10.13 for you, then you most likely encounter two separate issues. either #4926 or #4866. both will be fixed by #4936. feel free to test that PR.

you can also try older versions 0.24, 0.25 and 0.26. let me know which work and which don't on both 10.12 and 10.13.

**Comment by Akemi** [comment]
fixed via 77021cf6fe6a1813b832c8927c288e958b6f6845.
