### ISSUE TITLE
banding/black crush with HDR + interpolation

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4976]
### mpv version and platform
mpv 0.27 or latest git master
tested on Windows 10 x64 Anniversary Update and Windows 7

### Reproduction steps
Play an HDR video like "The Redwoods" with interpolation.
Simple config which shows the issue (dxinterop shows the same, angle not tested):
opengl-backend=win
dither-depth=8
video-sync=display-resample
interpolation

### Expected behavior
Interpolation shouldn't degrade quality.

### Actual behavior
Interpolation leads to some kind of banding or black crush image corruption.

How it should look like (interpolation off):
https://abload.de/img/nointeks83.png

How it does look with interpolation:
https://abload.de/img/intf5svv.png
(you may need to darken your room and look very closely at the dark forest areas)

The issue has originally been reported by jane1969 in this tracker entry
https://github.com/mpv-player/mpv/issues/4957

### Log file
https://pastebin.com/CsvrvtwY

### Sample files
ftp://helpedia.com/pub/multimedia/testvideos/The%20Redwoods%204k%2024fps%20(VP9%20Profile%202%20HDR).mkv
https://www.youtube.com/watch?v=9WrgRpOJr0I

**Comment by aufkrawall** [comment]
It doesn't seem to happen with fbo-format=rgba16f (instead of default value).
However, that seems to make interpolation stop working for d3d11 and vulkan. OpenGL still looks smooth.

**Comment by haasn** [comment]
> It doesn't seem to happen with fbo-format=rgba16f (instead of default value).

d3d11 and vulkan don't have `rgba16f`, the equivalent 16-bit float format is called `rgba16hf`.

**Comment by aufkrawall** [comment]
rgba16hf works nicely with d3d11 and vulkan, banding is gone and interpolation still works. It also doesn't seem to be any slower/memory hungry than rgba16.
Could it really be that rgba16 is not sufficient enough, just in conjunction with interpolation?

**Comment by wm4** [comment]
rgba16hf has less precision than rgba16, but allows out of range values, and will have more precision for small values towards 0. One of those seems to matter?

**Comment by haasn** [comment]
Yeah it's entirely possible we need to force floating point buffers for HDR.

**Comment by aufkrawall** [comment]
Hm, at least I don't notice additional banding vs. rgba16 in non-HDR videos 8/10 bit.
Less precision of rgba16hf might be just a theoretical drawback?

**Comment by wm4** [comment]
Well, rgba16hf would merely give you 11 bits of precision typically, while rgba16 would give you 16 bits. So it might depend.

**Comment by aufkrawall** [comment]
Ouch, that's much.

**Comment by haasn** [comment]
We could actually recover some of that dynamic range by encoding HDR content in full range instead of compressed to 0-1. i.e. for PQ we'd store a value from 0.0 to 10000.0. This would give you back some of those bits; together with the fact that it also compresses the near-blacks better, that would probably be a win overall. It also simplifies the math, and does a whole lot of other useful things, like allowing us to get some of the hacks on stuff like the OOTF or debanding code.

The downside, of course, is that it would either require float FBOs for all HDR playback, or alternatively keeping those hacks around but making them conditional on the FBO representation... no pretty solution.

**Comment by haasn** [comment]
@wm4 To be fair, the linear light math gets trickier. rgba16hf linear light is basically like encoding the linear light values using a 16-bit logarithmic encoding.

In fact you could argue that the true number of bits you get is equivalent to the number of bits you get for the entire range 0-1, which covers all of the negative exponents. In other words, the only bits that aren't being used are the two sign bits (since positive exponents are never used, and neither is a negative mantissa). So the true precision could be argued to be 14 bits logarithmic, which is a good match for the actual data in the source, considering the original representation is non-linear.

And with the thing I just discussed, we'd recover some of those additional 2 bits as well.

**Comment by wm4** [comment]
I guess automatically choosing a proper FBO format is tricky, because you don't always know whether a more precise format (or just changing to a float format) will impact performance.

**Comment by haasn** [comment]
Where are float textures actually slower than integer textures? Considering the GPU needs to convert to float anyway, and the bit depth is the same

**Comment by wm4** [comment]
I think some "lesser" GL implementation emulate float textures in software or something? I don't know, but I remember that we had a lot of trouble finding a FBO format that reasonably worked for most users.

**Comment by aufkrawall** [comment]
Correct me if I'm wrong, but wouldn't it be better to simply use rgba16hf for HDR for the time being? :)
The banding is still quite visible with current Hable default, while rgba16hf correctly dithered to 8 bit doesn't seem to be a showstopper to my humble vision.

**Comment by wm4** [comment]
There was a lot of talk about changing the default FBO format to a float one, not sure why nobody has made a PR yet.

**Comment by haasn** [comment]
The conclusions I came to while rewriting the renderer are that we should try and use formats in the following preference list:

1. 16-bit float format
2. 16-bit unorm format
3. 8-bit unorm format

If no float formats are available, disable linear light processing (i.e. linear-scaling/sigmoid-upscaling) for **HDR material**.

If no 16-bit formats are available, disable linear light processing for **all material**.

Basically the decision logic looks like this:

```c
static void find_fbo_format(struct pl_renderer *rr)
{
    struct {
        enum pl_fmt_type type;
        int depth;
        enum pl_fmt_caps caps;
    } configs[] = {
        // Prefer floating point formats first
        {PL_FMT_FLOAT, 16, PL_FMT_CAP_LINEAR},
        {PL_FMT_FLOAT, 16, PL_FMT_CAP_SAMPLEABLE},

        // Otherwise, fall back to unorm/snorm, preferring linearly sampleable
        {PL_FMT_UNORM, 16, PL_FMT_CAP_LINEAR},
        {PL_FMT_SNORM, 16, PL_FMT_CAP_LINEAR},
        {PL_FMT_UNORM, 16, PL_FMT_CAP_SAMPLEABLE},
        {PL_FMT_SNORM, 16, PL_FMT_CAP_SAMPLEABLE},

        // As a final fallback, allow 8-bit FBO formats (for UNORM only)
        {PL_FMT_UNORM, 8, PL_FMT_CAP_LINEAR},
        {PL_FMT_UNORM, 8, PL_FMT_CAP_SAMPLEABLE},
    };

    for (int i = 0; i < PL_ARRAY_SIZE(configs); i++) {
        const struct pl_fmt *fmt;
        fmt = pl_find_fmt(rr->gpu, configs[i].type, 4, configs[i].depth, 0,
                          configs[i].caps | PL_FMT_CAP_RENDERABLE);
        if (fmt) {
            rr->fbofmt = fmt;
            break;
        }
    }

    if (!rr->fbofmt) {
        PL_WARN(rr, "Found no renderable FBO format! Most features disabled");
        return;
    }

    if (!(rr->fbofmt->caps & PL_FMT_CAP_STORABLE)) {
        PL_INFO(rr, "Found no storable FBO format; compute shaders disabled");
        rr->disable_compute = true;
    }

    if (rr->fbofmt->type != PL_FMT_FLOAT) {
        PL_INFO(rr, "Found no floating point FBO format; linear light "
                "processing disabled for HDR material");
        rr->disable_linear_hdr = true;
    }

    if (rr->fbofmt->component_depth[0] < 16) {
        PL_WARN(rr, "FBO format precision low (<16 bit); linear light "
                "processing disabled");
        rr->disable_linear_sdr = true;
    }
}
```

On top of this, I make no effort to “renormalize” the light values. That is, 1.0 always means white, *even for HDR*. (So that's why it's crucial to disable linear light processing for HDR without float format)

This way we get to use virtually the full depth of the 16-bit float buffer in a nearly optimal logarithmic encoding. We just waste 2 sign bits (and for HDR, not even that), so we're left with essentially 14 bits of logarithmic precision, which is vastly more than 16-bits of linear precision (which is more like 9 bits for something like PQ, or 13 bits for HLG).

**Comment by haasn** [comment]
Also, even if store a non-linear texel in a 16-bit float, this means your value range is roughly uniformly distributed which means you get something like 11 or maybe 12 bits of flat precision based on the mantissa alone.

**Comment by aluo-x** [comment]
Still seeing this issue, image looks fine windowed, but black crush when full screen.
For some reason using rgb32f or rgba16f with dx11, which enables dumb mode actually causes the black crush to disappear. Using rbga16 still displays black crush

**Comment by aufkrawall** [comment]
Dumb-mode disables interpolation.

**Comment by aluo-x** [comment]
So after a lot of iteration, finally found the flag that caused the banding.
Performance issues still remain for interpolation, but those can be solved.

Turns out the `gpu-hq` flag was causing me issues. Again, banding when full screen, disappears when windowed.

Specifically, going in and disabling each flag, it was `sigmoid-upscaling=yes` that caused this, setting it to no fixed the banding while still on `rgba16 and d3d11va`.

**Comment by haasn** [comment]
In theory, sigmoid should already be disabled for HDR. (Unless my brain suddenly imploded and I'm hallucinating memories). What version of mpv is this?

**Comment by haasn** [comment]
Oh wait, it wasn't disabled for mpv - just linear light downscaling. Maybe we can disable sigmoidization then for HDR content. (My proposal from up above requires doing so anyways, and I do it in libplacebo and haven't noticed any downsides)

**Comment by aufkrawall** [comment]
I can still see banding without sigmoid.

**Comment by aluo-x** [comment]
This is my current working conf file that I do not experience banding with.
Using an intel kaby lake processor with HD 630. Can play 4K 24 fps HDR HEVC content mostly fluidly. If all the gpu-hq flags are disabled then it is completely fluid.

```
vo=gpu
gpu-context=d3d11
hwdec=d3d11va
tone-mapping=reinhard
hdr-compute-peak=no
target-brightness=350
fbo-format=rgba16
video-sync=display-resample
audio-channels=stereo
#GPU_hq w/ sigmoid disabled
scale=spline36
cscale=spline36
dscale=mitchell
dither-depth=auto
correct-downscaling=yes
sigmoid-upscaling=no
deband=yes
# END GPU_hq
#interpolation=yes
#tscale=linear
```

**Comment by aufkrawall** [comment]
You disabled interpolation. The title of this issue ticket clearly states to enable it in order to get undesired corruption.

**Comment by aufkrawall** [comment]
Closing because this got merged:
https://github.com/mpv-player/mpv/pull/5873
