### ISSUE TITLE
Seek with touchpad (again)

### ISSUE THREAD

**Issue by es0phagus** [mpv-player/mpv#4999]
### mpv version and platform
latest mpv release, OSX 10.13 

Hi, I searched the wiki but no luck. I wanted to know if it was possible to reconfig my input.conf file (or similar) to allow me to seek with the touchpad as in previous versions? The latest mpv release seems to have changed to allow the touchpad to alter volume instead.

Thanks

**Comment by ArchangeGabriel** [comment]
For me it has always (?) been both: vertical scrolling for volume and horizontal scrolling for seeking. Making it quite hard to change one without touching the other btw.

**Comment by es0phagus** [comment]
Both horizontal and vertical control volume for me. I didn't even know about the vertical before this, only used the horizontal prior.

**Comment by rossy** [comment]
Yeah, this was originally different between macOS and the other platforms. In mpv 0.27, the macOS bindings were changed to match Windows and X11.

To restore the original macOS bindings, add this to your input.conf:
```
WHEEL_UP    seek 10
WHEEL_DOWN  seek -10
WHEEL_LEFT  seek 5
WHEEL_RIGHT seek -5
```

@ArchangeGabriel Hopefully it's less difficult to use one axis without touching the other in recent releases. We added a dead-zone, so after scrolling on one axis (UP/DOWN or LEFT/RIGHT) mpv will ignore commands on the other axis until you stop scrolling.

**Comment by wm4** [comment]
Could go into `etc/restore-old-bindings.conf`, but I think nobody checks this ever.

**Comment by rossy** [comment]
Well, these are platform specific. I might add them as a comment.

**Comment by rossy** [comment]
Done in 23da3ed21a38

**Comment by cesarandreu** [comment]
I found the sudden change unexpected and was a little frustrated. When I looked at the v0.27.0 release notes, nothing stood out to me as an explanation for why the input behavior had changed.

Could the maintainers please consider updating the release notes to include this change? Otherwise a user had to search through the issues or sift through the release diff in order to figure out what was changed.

Might I also inquire as to the reasoning behind this change? The new default no longer matches the platform conventions on macOS.
