### ISSUE TITLE
[Question] Why don't 'video-sync=display-resample' & 'af=lavfi=dynaudnorm' play well together?

### ISSUE THREAD

**Issue by mpvOWNZ** [mpv-player/mpv#5071]
I ask because I noticed that `dynaudnorm` in combination with `display-resample` was the culprit for all those delayed and dropped frames, which led to slight but still noticeable micro-stutter every once in a while (and sometimes to even completely messed up playback in terms of interpolation).
Also, how do You guys ensure that the voices in films are loud and clearly audible?

**Comment by richardpl** [comment]
Do not use display-resample.

**Comment by wm4** [comment]
Because the audio filter chain sucks, and if too much data is buffered, trying to change audio speed (as the display-resample mode does) completely fucks up the estimation of buffered audio and thus A/V sync. You _could_ use `--lavfi-complex` as workaround (because that doesn't interact with changing speed), but of course that's less convenient.

This might be fixed in the future, but I have to prioritize stupid crap.
