### ISSUE TITLE
Unable to play

### ISSUE THREAD

**Issue by tdiguy** [mpv-player/mpv#5086]
### mpv version and platform
platform is windows 10

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Laptop with discrete and integrated gpu unable to play video's
in my case it is a asus ROG laptop with a ibm graphics card and a nvidia geforce gtx 960m

### Expected behavior
nothing happens and no log is generated
### Log file
none is being generated.
Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by rossy** [comment]
This issue was marked invalid because there is almost no information on how to solve it.

> Without a log it might not be possible to analyze and fix certain bugs, and your bug report will be closed or ignored.

Please provide a log file. It is _essential_ for solving issues like this. To generate a log file, open a Command Prompt, navigate to mpv's directory and type something similar to the following command:
```
mpv --log-file=output.txt path\to\video.mp4
```
In the unlikely event that this doesn't produce a log in ``output.txt``, you should at least see some text on the screen or an error message dialog.

> mpv version and platform

The Windows version is good. Please mention the mpv version as well. Is this a recent problem? Do older versions of mpv work? If so, which versions?

> Reproduction steps

Please provide more detailed steps here. Did you try multiple kinds of videos? Did you play them through file associations or by dropping them onto mpv's window?

> Actual behavior

Please describe what happened in detail. Did you see mpv's window open at all?

If you don't provide this information, we probably won't be able to help. We're not psychic and we don't have access to your hardware to test or debug on.
