### ISSUE TITLE
Add support for midi playback

### ISSUE THREAD

**Issue by shmerl** [mpv-player/mpv#5100]
While midi support was discussed in #91, it's still not playable with mpv (I'm not familiar with libgme and whether it can help with that), but the proper way to add midi is some API to interact with midi synthesizers.

**Comment by yetisyny** [comment]
Fluidsynth is the most popular soft-synthesizer, is cross-platform, and has built-in support for decoding and playing MIDI files. I suggest just using Fluidsynth for MIDI playback.

There are other options including interfacing with OS-native MIDI APIs for Windows, macOS, ALSA (on Linux), and JACK (cross-platform), such as RtMidi (actively developed) or PortMidi (not as active anymore), but those require separately parsing the MIDI files using another library since they are just for sending MIDI commands to the OS native MIDI interface in a cross-platform way.

And the sdl2_mixer library can parse and play MIDI files natively on Windows and macOS while needing an old version of Timidity++ on other OSes such as Linux, but it has a rather simple, dumbed-down API which would not give mpv enough control over things. I do use sdl2_mixer for playing MIDI music in an open-source game I have contributed to, but, given sdl2_mixer’s limitations, I think Fluidsynth would probably be a better option. Then again, if all you want to do is add MIDI playback support, sdl2_mixer is the simplest, easiest way to do a quick and dirty implementation of that. Probably not the best way to do things but it works. Sdl2_mixer is actively developed, the main problem is just an overly simple API without enough control over what happens, and also, it would not be compatible with things such as mpv audio filters, the most it could provide is simple playback of MIDI files, although it does work quite well at that, quite well indeed.

For things like audio filters in mpv to work, OS native MIDI playback must be avoided and a soft-synthesizer such as Fluidsynth or Timidity++ is needed. Fluidsynth has been actively developed for years and is still actively developed whereas Timidity++ appears dead, and some of the problems mentioned with it in the discussion you linked to may have been fixed in the last 2 years. Wildmidi is also an option, it is still actively developed and is more mature than it was in 2015 when the linked discussion occurred. I am guessing mpv will want to use a soft-synth so that the audio filters can work, rather than using OS native MIDI output APIs through one of the solutions such as sdl2_mixer, RtMidi, or PortMidi. Then again the one advantage of OS native MIDI is you do not need a SoundFont, having to use one of those might be a bit of a hassle since they can take up a lot of disk space and configuring which SountFont to use adds to the complexity of the project and if you do not have any SoundFont at all playback does not work, whereas OS native MIDI never has the problem of a missing SoundFont, it just works out of the box without having to do anything. Of course SoundFonts are also considered a good thing by many people since you can pick one that you think sounds better, which is largely a matter of personal taste. Anyway MIDI support is a bit complicated since there are so many different ways to do it, but once you pick which way you are going to do it and settle on it it gets a lot simpler. The only of these options I have personally used to implement MIDI playback is sdl2_mixer because it is very very easy, but it is more something aimed at simple cross-platform computer games, not complex multimedia software like mpv.

**Comment by shmerl** [comment]
I agree that fluidsyth is a good option. And it works with many good sound fonts as well. Such as [this one](http://www.schristiancollins.com/generaluser.php).

**Comment by hyiltiz** [comment]
Can't you add a small fluidsynth backend as a plugin?

**Comment by wm4** [comment]
Well, we certainly could. Just that someone has to do it, and it might get awkward because pretty much everything is hardcoded to ffmpeg (but at this point I don't mind if mpv moves away from this again).

**Comment by rubyFeedback** [comment]
Personally I would like this.

Most of my local files are .mp3, some .ogg, also some .mkv and .avi (xvid codex usually). But I also have a very few .mid files; I don't even recall how I got them. I think I wanted to work with an electronic keyboard once but laziness wins often.

I'd love for mpv to be able to play midi files. Even though in my case it is also not that important really, it's like ... 1:3000 files only in midi format that I keep right now. Perhaps the fluidsynth guys read this and could add a SUPER SIMPLE API that could be used in mpv. I guess nobody feels like investing too much time into this compared to other goals for mpv.

We all seem to sort of depend on ffmpeg. In ruby I also just have wrappers over ffmpeg commands. Convenience is a compelling advantage, despite other disadvantages (for example ... there were older transcoders that seem to all have died with ffmpeg, and sox worked ok for some audio-related manipulations; these days I admittedly also give up and just use ffmpeg. In that regard ffmpeg has succeeded actually.).

**Comment by Mosesofmason** [comment]
The playback quality is horrible...

**Comment by ElonSatoshi** [comment]
> The playback quality is horrible...

Agreed. Is there a way to fix or work around this, or specify the soundfont mpv uses?

**Comment by slashdevslashurandom** [comment]
Was support for MIDI / FluidSynth removed from mpv? Because looking at the current version of the source, I can't find any traces of the commit 4f18e79 that enabled it.

**Comment by llyyr** [comment]
https://github.com/mpv-player/mpv/commit/16b44d93f7014b3abd8f21a4035fd4ebeed1d2c0

It was reverted because it wasn't good

**Comment by ElonSatoshi** [comment]
So should we reopen this issue?

**Comment by slashdevslashurandom** [comment]
It definitely seems like it should be reopened, or at least closed as something other than "completed".

**Comment by TomerGamerTV** [comment]
bruh

**Comment by vivimillin** [comment]
definitely it should be reopened...
