### ISSUE TITLE
Global Hotkeys (without thirdparty scripts)

### ISSUE THREAD

**Issue by refriedfood** [mpv-player/mpv#5109]
I'm currently using 2.0.0.0 on winOS 7u sp1 x64

Like other media players, vlc, mpc, mpchc, foobar, etc you can bind key to have it made global so that regardless if the screen/player itself is active, I can hit ctrl+enter and mute, pause, next file, etc.

Is there any plans or a way to do this within the current .conf files? It seems as though everything requires a command line juke-move or autohotkey or g-hotkey, etc which makes it less worthwhile to even use mpv unless you're a cmdline junkie.

Also, a sub issue, I'd like to configure a command in order to open a stream, i.e. an m3u8 file that you cannot drag and drop into the player because you only have the link and it isn't a shortcut or file. Is this even possible?

**Comment by FunkiPorcini** [comment]
2 years and MPV still doesn't have global hotkey options? You are kidding.

**Comment by Akemi** [comment]
and you still didn't start contributing yourself to the windows mpv codebase after that long? you are kidding!

**Comment by FunkiPorcini** [comment]
@akemi, how about you don't stalk my shit. Thanks, and it's not my job, it's theirs.

**Comment by zc62** [comment]
Who are you referring to when you say "You" and "theirs"? Did you actually pay one cent to them to work for you? Why should the core devs should work for you if they think this feature is uninteresting to them? Why wouldn't you implement this (or pay somebody to implement this) if you feel this feature useful? If you don't want to contribute and don't want to pay anyone to contribute, STFU.

**Comment by Argon-** [comment]
>Thanks, and it's not my job, it's theirs.

It's not the job of anybody here. That's the point. Open source mostly works by "I want this, so I  create this". 
So far, it seems like nobody capable or willing to "create" wanted a global hotkey, so here we are.

**Comment by FunkiPorcini** [comment]
@zc62, You know who I'm referring to. And no, when you release something to the public it doesn't become the publics' job all of a sudden to implement features, dipshit. When you release something for ingestion you don't all of a sudden become immune to obvious improvements or problems. Otherwise you'd be eating lemons and not drinking lemonade because you need money incentive to take off the fucking blinders you have on. No one is entitled to add it, cause I know that's what someone like you is thinking, but no one is entitled to use it either if they only want to stick heads in sand. So fuck off.

**Comment by Argon-** [comment]
Except you didn't point out a flaw. That was done two years ago. You complained about this flaw still not being addressed. Now the point is: obviously nobody cared about this in all this time. Neither a developer, nor a relevant amount of users. So the suggestion of taking matters into your own hands wasn't war-fetched at all.

Your analogies are outright wrong. When someone releases code then there are absolutely no implications or obligations for the authors with respect to fixing bugs or implementing features (unless they promised otherwise). This is not how it works. Don't like it? Sue me. Every open source project could be abandoned today.
To reiterate what was said before: nobody's job here is contributing to mpv. But even more important: nobody here needs you to use mpv. 
And after your tirade of insults I guess we better end this here.
