### ISSUE TITLE
Ver .25 compared to ver .27 - Ver .27 not detecting GPU properly?

### ISSUE THREAD

**Issue by tyeeman** [mpv-player/mpv#5159]
### mpv version and platform
.25 and .27 -- Windows 7, Intel HD4000 gpu, 1080p projector
### Reproduction steps
default playback with only --tone-mapping=reinhard --target-prim=bt.709 in the command line.
### Expected behavior
no blotchy patterns jumping around and sparkling blue hues in certain scenes.
### Actual behavior
blotchy patterns jumping around and sparkling blue hues in certain scenes.
### Log file
http://sprunge.us/hHfG
### Sample files
https://imgur.com/a/nUpIB

**Comment by rossy** [comment]
It looks like ANGLE is failing to create a ES 3.0 context, which is strange because I think that should work on your hardware. Make sure the libEGL.dll, libGLESv2.dll and d3dcompiler_XX.dll that you downloaded with mpv.exe have been extracted to the same folder.

In mpv 0.27, after failing to create a ES 3.0 context with ANGLE/D3D11, it (correctly) falls back to a ES 2.0 context with ANGLE/D3D9, which doesn't have high bit-depth FBOs, so that probably explains why the colour conversion is different.

In mpv 0.25, there seems to be a bug in the fallback code and it falls back to the **win** backend instead. If the above fix doesn't work and you want to replicate the old 0.25 behaviour in 0.27, try adding --gpu-context=win to your config.

**Comment by tyeeman** [comment]
I do not have libEGL.dll, libGLESv2.dll in my mpv folder. They were not in the download from https://mpv.srsfckn.biz. Do I need them? Even ver .25 does not have them in the folder, which works good.
Only files I do have are libbdplus.dll, libaacs.dll and d3dcompiler_43.dll.

**Comment by lachs0r** [comment]
You only need the files that are included in the archives. The “missing” files 
are statically linked in later versions.

**Comment by rossy** [comment]
Oh, sorry. I forgot that recent mpv builds don't have those DLLs. I also gave you the wrong option name. It's --opengl-backend=win for 0.27. (It should work on the command line or in mpv.conf.)

**Comment by tyeeman** [comment]
I tried that option also, but no difference.

**Comment by thebombzen** [comment]
What about mpv 0.28.0?

**Comment by tyeeman** [comment]
OK, just tried 0.28 from https://mpv.srsfckn.biz/ (dec. 25/17) and I get a totally blank screen! Sound works but no video, even with x264 file. I will try the other windows build from sourceforge.

**Comment by rossy** [comment]
Assuming this is fixed, since a 2018-01-18 build works. Please reopen if it's still not working for you.
