### ISSUE TITLE
How do compilations of mpv differ?

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5181]
Mpv 0.27 Windows 8.1 x64
Good morning, my question is if there is any technical difference between the mpv compilations of lachs0r and those of shinchiro. Are both of them equally valid? Is any of them a beta version?
I also ask why I see that lachs0r's compilations are every couple of months, and shinchiro's are much more frequent.
Thank you very much in advance.

**Comment by avih** [comment]
They're both "equally valid". There could be some different build options or versions of libraries, but for the most part there shouldn't be functional difference due to the different build procedures.

lachs0r's builds typically only after releases, while shinchiro builds more frequently.

Generally, but not necessarily, release versions are considered more stable but update less frequently, while builds between releases contain possibly hot new stuff but also hot new bugs. Up to you.

In mpv, generally both are fine, But I'd recommend the stable versions.

If, however, you have reasons to try builds between releases (like testing if it solves some bug you have, or you're eager to try a new feature which was added recently and is not yet at the release, or just because you must always have the latest), then sure, use more frequent builds, or even build yourself with every new commit.

There's no right or wrong here.

**Comment by EzeKees** [comment]
Many thanks!!
It's the exact answer I was looking for. I always had doubts that were very well clarified.
The truth, sincerely, congratulations for this beautiful and powerful player!
