### ISSUE TITLE
"INDUSTRY STANDARD" for video scaling by default

### ISSUE THREAD

**Issue by it-enemy** [mpv-player/mpv#5368]
Which video scaling algorithm is used by film studios when scaling, for example, a 4K video recording/edition in a 1080p version?
Which video scaling algorithm is used in mpv by default?
Open many discussions on a variety of forums, what kind of algorithm is "more correct" for the player, but I have not yet met criticism of the algorithm used by film studios.
Will not it be the best choice for mpv by default?
I did not find any information on this matter

A lot of film studios use **"Avid Media Composer"** for video editing, can the answer lie in it?

**Comment by Akemi** [comment]
mostly probably bilinear, they might have some motion compensation options. simplified they also have the freedom to just transfer at the wanted resolution, since film is still majorly used by studios.

mpv uses [bilinear](https://mpv.io/manual/master/#options-scale) by default or with a hq profile the filters defined [here](https://github.com/mpv-player/mpv/blob/d690ee095942c06ee3157480e970ff70b399e04e/etc/builtin.conf#L38).

the best choice is what the user wants and not some flaky industry standards. the reason why bilinear is used as default is stated on the man page above.

i think discussing what the 'industry standard' is belongs to those forums you were mentioning and not the mpv issues tracker. after all if you already discussed that matter so thoroughly why not just let us know about your findings?
