### ISSUE TITLE
Some youtube streams don't work

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#5389]
### mpv version and platform

git master for ffmpeg, mpv and youtube-dl
 $ mpv --version
mpv 0.28.0-105-gb478d2b1ce-dirty Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Jan 12 21:55:28 EST 2018
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.11.101
   libswresample   3.0.101
ffmpeg version: N-89788-g1eb7c1d49d

### Reproduction steps

Try to play certain streams.  Some work, some don't, but here's one that's live right now that doesn't: https://www.youtube.com/watch?v=_43TGUnXCZs

### Expected behavior

Stream starts playing.

### Actual behavior

Bunch of console spam then exits.

### Log file

https://bpaste.net/show/517f99ad0814
EDIT: Forgot to use --no-config, but it made no difference.

### Sample files

Link above which should be valid for a while since it's a 24/7 stream.

**Comment by saucyfox** [comment]
Having the same issue with https://www.youtube.com/watch?v=oYntVKsbvFM - really strange behavior.

**Comment by pr0dukter** [comment]
i can usually fix this by switching https://www.youtube.com to http or https://youtu.be/oYntVKsbvFM  perhaps has to do with terminal and no \ before certain symbols, but i seem to usually have issues with youtube urls right before youtube-dl update

**Comment by anonish** [comment]
related
https://github.com/rg3/youtube-dl/issues/15202
smplayer has it fixed already on their built-in youtube streamer

**Comment by hmedia1** [comment]
If you're using `mpv` to play a YouTube live stream directly, it's going to use the `youtube-dl` hook to get the m3u8 playlist.

You should consider `mpv`'s automatic invocation of `youtube-dl` a courtesy and not an integral component as this issue is completely on behalf of `youtube-dl`; if you passed 
As of a few days ago, YouTube changed the player config and made some changes to the live streaming system itself, so if you want this working, at this very moment, here's one temporary workaround:

`mpv` will call the format abbreviation 'best', which in the current version of `youtube-dl` (2018.01.07) will point to a single segment of a DASH stream, as opposed to the usual HLS m3u8 playlist.  While `mpv` is perfectly fine with playing static DASH streams, the construction of the parameters 
Apply [this](https://github.com/rg3/youtube-dl/issues/15202#issuecomment-357175424) patch to `youtube-dl` (confirm the exact path `mpv` uses for `youtube-dl` using `ps` ):

And then modify the hook in the invocation:

i.e. For the link you gave .. 

`mpv --ytdl-format=96  https://www.youtube.com/watch?v=_43TGUnXCZs`

**Comment by hmedia1** [comment]
If you're using `mpv` to play a YouTube live stream directly, it's going to use the `youtube-dl` hook to get the m3u8 playlist.

You should consider mpv's automatic invocation of youtube-dl a courtesy and not an integral component as this issue is completely on behalf of `youtube-dl`; if you passed the m3u8 playlist directly to `mpv`, it would work as it always did.
 
As of a few days ago, YouTube changed the player config and made some changes to the live streaming system itself, (some noticed changes are that the default stream map is now DASH, HLS streams are only retrievable using the `hlsvp` object in the player config, also, that 60fps HLS streams are no longer converted to 30fps HLS streams (format 96)

`mpv` will call the format abbreviation 'best', which in the current version of youtube-dl (2018.01.07) will point to a single segment of a DASH stream, as opposed to the usual HLS m3u8 playlist.

If you want this working, at this very moment, the temporary workaround would be to extract the playlist and pass the URL to `mpv`.  Alternatively you could just patch the `youtube-dl` used by `mpv` (using [this](https://github.com/rg3/youtube-dl/issues/15202#issuecomment-357175424) patch, and then manually specify the format.

i.e. For the link you gave, which has a 1080p30 stream ..

`mpv --ytdl-format=96 https://www.youtube.com/watch?v=_43TGUnXCZs`

**Comment by paulguy** [comment]
Yeah looks like it works now with an updated youtube-dl.  I just figured since it was trying to play some kind of something and identifying it as audio and video that it was an mpv or potentially ffmpeg issue.

**Comment by wiiaboo** [comment]
Fixed as of 2018.01.14. Still no DASH formats, though.
