### ISSUE TITLE
[vo=opengl] Weird behavior on virtualized Linux using VMware

### ISSUE THREAD

**Issue by guixxx** [mpv-player/mpv#5418]
### mpv version and platform

v0.27.0 (also tested on v0.28.0 dba143d)
Arch Linux 64-bit **(virtualized, with 3D acceleration using VMWare Workstation)**
Driver: x86-video-vmware (latest version)
MATE Desktop 1.18

### Reproduction steps

* v0.27.0: `$ mpv --no-config --vo=opengl any_video.mp4`
* v0.28.0: `$ mpv --no-config --vo=gpu any_video.mp4`

Obviously I don't casually use VMs to watch videos, I found this by accident while I was testing stuff in one of my Linux VMs and I decided to report to you guys just in case,... ❤️ 

I also tested this in another VM, running Ubuntu 17.10 (on Xorg as well), which still has mpv v0.26.0 in its repo, **there were no glitches at all**.

### Expected behavior

mpv shouldn't "zoom in" the video and leave a huge blank space on its window (see screenshot below)

### Actual behavior

![screenshot at 2018-01-19 13-10-35](https://user-images.githubusercontent.com/27077338/35152745-813f8620-fd1b-11e7-9a49-8350a97f2b86.png)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/1646658/output.txt)

**Comment by guixxx** [comment]
No, I guess?

![screenshot at 2018-01-19 13-50-50](https://user-images.githubusercontent.com/27077338/35153772-c70fe916-fd1f-11e7-9fd9-b75ccf195d4a.png)

**Comment by wm4** [comment]
Try with something that uses EGL, or try to force GLX on mpv.

**Comment by guixxx** [comment]
Sorry, my knowledge about this stuff is kind of limited, I don't know something that uses EGL. 

But running mpv with `--vo=x11` actually works! Here's a log file just in case:

[output-x11.txt](https://github.com/mpv-player/mpv/files/1646720/output-x11.txt)


So do you have an idea of what's causing this issue?

**Comment by wm4** [comment]
I didn't mean that, but I don't know how our every changing command line options work for that either.

**Comment by Panzerino** [comment]
Actually, it is very nasty bug on almost all Linux guest machines- from Arch to SUSE. The boys from mpv plays endlessly with version, ffmpeg strange "implementations" etc etc. Some years ago, it was very easy to put -vf=eq2 and to have colour controls on xv or X11. Now, this is not possible without obscure and UNDOCUMENTED lavfi tricks, ffmpeg "options", and so on, and so on. But this nasty, nasty scaling bug is the epitome of the light-heartedness of some young, untrained boys, with appetite to play games.. This never happened in the past with the mpv- probably, the best media player on Linux.

**Comment by CounterPillow** [comment]
I like how @Panzerino made a GitHub account just for this stupid reddit-tier comment.

**Comment by CounterPillow** [comment]
@guixxx to force GLX on mpv, use `--gpu-context=x11`. The vo_x11 you've tried is not GPU-accelerated at all, so it's not much surprise that it works. It's possible EGL is broken in vmware in some way, so if GLX works it would point towards that.

**Comment by guixxx** [comment]
@CounterPillow That worked, nice! But out of curiosity, is there any difference between using x11glx and x11egl? Thanks.

**Comment by CounterPillow** [comment]
Okay, so it is a problem with EGL then. The difference between EGL and GLX is how the OpenGL context is created. With GLX, you create it through the X11 windowing system as far as I'm aware, whereas EGL is independent of X11.

Can you try how `eglgears_x11` or `egltri_x11` looks?

**Comment by guixxx** [comment]
`eglgears_x11` looks like this in in windowed mode:

![image](https://user-images.githubusercontent.com/27077338/36076992-65659736-0f4b-11e8-87ad-8fce3e8f9d0d.png)

However, when I maximize it:

![image](https://user-images.githubusercontent.com/27077338/36076998-88b470fe-0f4b-11e8-975e-49e9dd18281b.png)

**Comment by CounterPillow** [comment]
So that looks to be a vmware driver issue then. That sucks. It's probably worth reporting this to vmware with `eglgears_x11` as a test case for them. Until they fix their EGL, it's best to stick with GLX.

**Comment by guixxx** [comment]
I'll report it to them, thank you! :+1:

**Comment by Panzerino** [comment]
Probably, this is not a VMware driver issue, because in Fedora 27 guest, same VMware version installation, mpv works fine with vo=gpu or opengl. Also, mpv ver 26 works fine on every single Linux guest. 
I make account here in scope to be able to comment, and to help to find solution. mpv is a fine software, if, at the end, some "boys" will destroy what is already achieved. mpv is a pivotal software in linux, and i asked about basic function to work. Not some sort of commodity. opengl works on every single mpv version I'm aware of, on every single Linux guest at least from 2010 and beyond.

**Comment by xkpd3** [comment]
Same here. I have a Debian "Testing" VM, which I use as my primary OS on top of Win10 (which is basically just there to host the VM and Outlook/Office).

Anyway, I've set vo=xv and mpv works find with this setting without needing too much CPU. But I would also be happy to see this bug fixed.

I also tested other video players:
- VLC: uses opengl and works fine
- mplayer: uses xv per default and works fine

**Comment by Panzerino** [comment]
Must confirm - with option gpu-context=x11 in mpv.conf file, and without specifying there vo parameter, mpv work.
@ CounterPillow, Pls, DO not confuse further the users!!  -it is NOT --gpu-context=X11 ! It is simply gpu-context=x11 in mpv. conf.
The --gpu-context=x11 is only when you start the mpv from command line, AND IT IS not a syntax in the mpv config file, which is without "--". It is vastly important, because one plain user must PLAY endlessly various sort of syntaxes "games", because some boys endlessly, and persistently, on every new mpv version, change the syntax of the mpv.conf file, which case loss of functionality and confusion. 

@ CounterPillow, are you able to enlighten us, when this hidden synatax acrobatics is documented??

**Comment by wiiaboo** [comment]
Or just read the manual or https://github.com/mpv-player/mpv/blob/master/DOCS/interface-changes.rst instead of making petty complaints about some "boys" mischievously breaking your special workflow.

**Comment by Panzerino** [comment]
@wiiaboo The last available ver of mpv, SUSE, is 27. Also for Debian sid the last available ver is 27.
https://packages.debian.org/sid/mpv
These "changes" concern ver 28 and after. And beyond mention that "rename --opengl-backend to --gpu-context", pls, tell us, where these hidden gpu-context options are... . 

Pls, do not think that all of us are idiots.

**Comment by wiiaboo** [comment]
` --gpu-context=help`? Or `--list-options`?
What do you mean by hidden options?
> This must be mention especially- like paradigm of fault mentality:

What?

**Comment by Panzerino** [comment]
You didn't understand, that because of the command-line richness of the software, the options must be clearly documented, with plenty of paradigms.
When you wrote in your VERY VERY confused manual, about the syntax, you never mentioned IT IS A mpv.conf syntax, or IT IS command-line syntax. The obscure mentions in the beginning of the manual, is not worth to be mentioned at all.
Why one syntax for the command line, other in the mpv.conf file? Are you unable to unify the syntax, according ONE rule> If it not possible, why do not clarify, which syntax is for the config file, and which is for the command line?

Pls, enlighten us, if some users want to use vo x11 and xv, and keys 3 and 4 to control brightness, how this will be possible? In the good old days -vf=eq2 works on every single mpv version- plainly and simply.
Now, with this lavfi graphs and so on tricks, pls, enlighten us, how to do this simply and plainly, for plain peoples.

mpv is a great piece of software. Do not destroy this by unneeded human vanity.

**Comment by wiiaboo** [comment]
> You didn't understand, that because of the command-line richness of the software, the options must be clearly documented, with plenty of paradigms.
When you wrote in your VERY VERY confused manual, about the syntax, you never mentioned IT IS A mpv.conf syntax, or IT IS command-line syntax. The obscure mentions in the beginning of the manual, is not worth to be mentioned at all.
Why one syntax for the command line, other in the mpv.conf file? Are you unable to unify the syntax, according ONE rule> If it not possible, why do not clarify, which syntax is for the config file, and which is for the command line?

https://mpv.io/manual/master/#location-and-syntax

If you're not using vo=gpu lots of things don't work, since the devs don't really care much for the others, since they're either old, or harder to maintain, or broken or all of them at the same time.

**Comment by CounterPillow** [comment]
>Probably, this is not a VMware driver issue, because in Fedora 27 guest, same VMware version installation, mpv works fine with vo=gpu or opengl. Also, mpv ver 26 works fine on every single Linux guest.

Because it's probably using GLX and not EGL in those situations. I really don't know to explain to you that a supposed mpv bug cannot magically break eglgears_x11.

**Comment by haasn** [comment]
> One time the syntax in the mpv.conf files is with "--", in the next version, the syntax is with " -", the next- without "-". Sometime ="parameter" works, sometimes- does not.

I know I'm feeding the troll, but you realize literally all of those are valid syntax and have always been, right?

**Comment by wm4** [comment]
Can someone block Panzerino already?

**Comment by lachs0r** [comment]
FWIW, the *only* working GL implementation for Linux VM guests with virtualized GPUs that is also reasonably fast seems to be Virgil, which can only be used with QEMU and virtio-gpu.
