### ISSUE TITLE
Will MPV ever get these features (windows)?

### ISSUE THREAD

**Issue by sinqbad** [mpv-player/mpv#5427]
Notify you when there's an update (maybe even up date it)

Not requires a .bat file to have file association

have an installer (not just a portable exe)

add mpv to path

have thumbnails for alot of media files

have playlist functionality

madvr

front end

hard to migrate from mpc when it feels incomplete. or is there a design philosophy I'm missing?

**Comment by kevmitch** [comment]
It is generally frowned upon to open an issue that is really multiple ones. 

> Notify you when there's an update (maybe even up date it)

There's been some talk about stuff like this. If someone has time / motivation, this is a possibility.

> Not requires a .bat file to have file association

I assume you're talking about the [installer](https://github.com/rossy/mpv-install/blob/master/README.md). Not really sure why this is worse than the usual setup.exe way, but again, this might change someday.

> have an installer (not just a portable exe)

Only if there's a good reason.

> add mpv to path

maybe

> have thumbnails for alot of media files

Probably not in the core player. This is too resource intensive and has always led to problems whenever I've seen applications do it.

It requires implementing a [Thumbnail Provider](https://msdn.microsoft.com/en-us/library/windows/desktop/cc144114(v=vs.85).aspx). Might be possible for someone to roll one that uses libmpv or something.

> have playlist functionality

It does

> madvr

No. I don't even know what this means. Why would mpv, which is essentially a video renderer, replace its internals with another renderer that only works on one platform? Just use madvr if you want madvr.

> front end

It is very unlikely mpv will ever have an internal GUI. That's why there's libmpv, so [others](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv) can write one.

Closing this to keep the issue tracker tidy since it isn't really an issue or a single clearly defined feature request.

**Comment by haasn** [comment]
Do literally any of your questions have anything to do with mpv itself? Seems like you're complaining about mpv installers and/or frontends, of which this git repository is neither.

**Comment by zc62** [comment]
>Notify you when there's an update (maybe even up date it)

mpv does not provide official builds. If you are using shinchiro's build, simply subscribe to this rss feed: https://sourceforge.net/projects/mpv-player-windows/rss?path=/64bit to see if there is an update. Or simply execute `updater.bat`. Installer? Maybe better to ask build providers too. But I don't see why it is better to have an installer.

>have thumbnails for a lot of media files

I believe those windows-only players like MPC-HC/BE or potplayer they don't provide thumbnails either. Only files of some certain kinds have thumbnails generated by Windows itself. I found Media Preview useful: http://www.babelsoft.net/products.htm

>madvr

madVR is a **DirectShow** video render. mpv is not a DirectShow player. Why do you think madVR might be better than mpv's internal video render? imho mpv is a high quality video player. If you are missing some upscalers, checkout user shaders here: https://github.com/mpv-player/mpv/wiki/User-Scripts#user-shaders

**Comment by rossy** [comment]
> hard to migrate from mpc when it feels incomplete. or is there a design philosophy I'm missing?

There might be. I can't speak for the philosophy of every mpv developer, but I think there's a cultural divide between simple keyboard-oriented software like mpv and GUI software like VLC and MPC-HC. Software in the former category isn't commonly used on Windows, but it includes programs like Vim, ncmpcpp, qutebrowser and others. One feature of software like this is that they are reluctant to add complex features that aren't directly related to their main purpose, so mpv is not likely to gain an internal thumbnail provider. Instead, you're encouraged to use an external one, like [Icaros][1].

Like others have said, mpv provides libmpv to allow _other projects_ to create GUI frontends. If you want a full replacement to MPC-HC, you're more likely to find it in one of these:


[1]: http://www.majorgeeks.com/files/details/icaros.html
