### ISSUE TITLE
video hangs, relative seeking breaks with particular video

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#5446]
### mpv version and platform

 $ mpv --version
mpv 0.28.0-105-gb478d2b1ce-dirty Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Jan 12 21:55:28 EST 2018
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.11.101
   libswresample   3.0.101
ffmpeg version: N-89788-g1eb7c1d49d

### Reproduction steps
play  https://www.youtube.com/watch?v=Qd0rOz47E0I and seek to before 00:36:38

### Expected behavior
video playback continues

### Actual behavior
video stops, audio continues, seekbar shows 00:00:00, relative seeking returns to the beginning. 

### Log file
https://bpaste.net/show/7db2103b4b69

### Sample files
https://www.youtube.com/watch?v=Qd0rOz47E0I

**Comment by wm4** [comment]
Not really sure what's going on there. It's like the segment at the mentioned time is broken, and then something bad happens. It seems it really gets a timetamp near 0 (which is why the playback time goes to 0), and shortly after that it gets a segment with the proper current time again. The latter makes mpv's video timing think it has to wait for about 20 minutes for the next frame, which is why video appears to freeze. Relative seeks also use the current playback time, which is why it gets stuck there.

**Comment by paulguy** [comment]
I suppose it might be a youtube problem or a youtube-dl problem, i dunno. I didn't try playing it in youtube itself actually to see if it worked there or not.

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
