### ISSUE TITLE
[Feature Request] Externalised, Update-able ffmpeg option

### ISSUE THREAD

**Issue by hl2guide** [mpv-player/mpv#5477]
An option for using an externalised, update-able (updater.bat) ffmpeg.exe file would be nice :D

**Comment by haasn** [comment]
What you are asking for makes no sense. FFmpeg is not a program, but a library. mpv links against libav*, either statically or dynamically depending on how you build it.

Note: Normally, you can update dynamically linked dependencies in-place as long as the ABI remains compatible, but in the case of FFmpeg, mpv specifically has safeguards to prevent users from doing that, since it has been known to cause problems despite advertised ABI compatibility.
