### ISSUE TITLE
OSD bar shown on wrong layer

### ISSUE THREAD

**Issue by mjk-gh** [mpv-player/mpv#550]
### Symptom

The OSD bar is shown on the wrong layer. It is shown _behind_ the layer with the OSD bar background. Thus, if an OSD background color is defined, the OSD bar is rendered invisible.
### Example

The configuration lines

```
osd-level=3
osd-color="#ffffff"
osd-back-color="#ff0000"
```

should give white letters / symbols on a red background.

This works for the OSD in the upper left, the OSD bar border in the lower quarter center (as well as the volume/brightness/... symbol left of it), but the actual OSD bar is invisible, because it is rendered _behind_ the OSD bar background (which can be checked by giving `osd-back-color` an alpha value of e.g. 99: `#99ff0000`).
### Software used
- mpv 0.3.5 (but older versions are also affected)
- Debian testing, amd64

**Comment by ticalc-travis** [comment]
^ Are those two “hack” patches just mentioned still available somewhere (the links no longer appear to work)? Due to vision deficiencies, I must use a background color to read the OSD easily, and it would be helpful if the sliders didn't respond by becoming even less visible by being obscured behind the background. ;)
