### ISSUE TITLE
howto keybinding in a C program

### ISSUE THREAD

**Issue by 9000h** [mpv-player/mpv#5573]
### mpv git-2018-01-28-2a0f9fc Linux Ubuntu 18.04
Hi,
howto can I do keybinding in a C program like in lua  mp.add_key_binding("F1",'vdrkeyRED',key("RED"))
I could not find any reference, is it feasible. 
CU
9000h

**Comment by wm4** [comment]
There's no public API for this yet. The internal API for it, which the Lua scripting uses, is kind of weird, and I don't want to expose it in this form (because that'd mean we can't fix it).

Normally I'd say GUI frontends (typical case where you'd use C/C++ and libmpv) should do their own key bindings handling, instead of using mpv's internal.

If you really need this, there are two choices:
- find how what the Lua code is doing (`player/lua/defaults.lua`)
- propose and implement an API that does it via C/libmpv (hard way because it'll hard to come up with a good API for someone not familiar with the problem and mpv code)

**Comment by 9000h** [comment]
ok understood, I had this used only as a workaround anyway as there was nothing to find in the docs.
I try to avoid to build all the keyboard stuff for the different platforms from scratch and like to have the keyboard(input events via input-vo-keyboard) path trough libmpv for my needs. Is there any official way?

**Comment by 9000h** [comment]
for now I have found a workaround with a small lua script to get the keys as needed back to my programm
