### ISSUE TITLE
[question] --demuxer-thread=....

### ISSUE THREAD

**Issue by dnmTX** [mpv-player/mpv#5576]
By default the demuxer is set to run on separate thread(which is fine),is it just one or...,and if it is,is it possible to implement a option to choose the thread count? The reason i'm asking is that i've notice when i stream .mkv files the cache is loading much slower when there are subtitles in it and much faster when there aren't. Maybe assigning more threads could help with that?

**Comment by wm4** [comment]
There's only one demuxer thread per file and there can't be more. It seems you have one of those crazy files that have thousands of subtitle packets per second - of course this causes inherent overhead, which can show up in various situations, including the demuxer thread being used. (Probably mostly due to prefetching, which throws _all_ subtitle packets at the decoder at once.)

**Comment by dnmTX** [comment]
@wm4  thanks for explaining this(as you would guess i'm kind of clueless how things work under the hood) and yes sometimes there are 6-7 sets of subtitles in the same file,i can only imagine the overhead.Too bad nothing can be done about this.Closing......
