### ISSUE TITLE
[Cocoa-cb] Dock bounces up after hiding in FS animation

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#5581]
### mpv version and platform
mpv 7ee0186
MacOS 10.13.3 (17D102)

### Reproduction steps
Play any video with `-no-config -vo=libmpv` and then make fullscreen
### Expected behavior
The Dock should hide directly
### Actual behavior
After the Dock goes hidden, the Dock will bounce up a little bit, as shown [here](https://0x0.st/sA5q.mov). 
### Log file

[https://0x0.st/sA5P.txt](https://0x0.st/sA5P.txt)

### Sample files

[https://0x0.st/sH1l.m4a](https://0x0.st/sH1l.m4a)

**Comment by Akemi** [comment]
you should rather complain to Apple than to us. since "but it works with other Apps" will be brought up anyway. even with [QuickTime](https://0x0.st/sA7p.mov) (VLC and iina too) one can see the Dock popping up again at the end of the animation. there is a light grayish shadow for ~4 frames at the and of the animation.

the difference, why it is more apparent on mpv, is that mpv animates to a fullscreen window that fits the aspect ratio (to prevent stretching) of the video first and only the final step changes the aspect ratio (toggle the OSC permanently visible to see what i mean). in your case you can see the dock on the left and right because the aspect ratio of the video is 1:1. other players animate directly to the screen size without keeping the aspect ratio.

this is not easily changeable.

**Comment by Akemi** [comment]
it should be hidden now with PR #5586.
