### ISSUE TITLE
(Question) every few months a new mpv version of lachs0r is released?

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5590]
### mpv 0.28 Windows 10

Hello, I know it's a silly average question, but I wanted to do it since I see that on the official page (https://mpv.srsfckn.biz) there are versions every 2 or 3 months, but also every few days, I would like to know when will be the next one, since it has several corrected errors, among them, not being able to play videos from streaming. Thank you

**Comment by wiiaboo** [comment]
When FFmpeg releases 3.5/4.0 at least.

**Comment by TrendaFet** [comment]
Is there a way to be notified of lachs0r releases?

**Comment by Hrxn** [comment]
'Watching' feature for this repository?

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/releases.atom

**Comment by TrendaFet** [comment]
Ah, got it. So there isn't a specific method to be only be notified of @lachs0r (https://mpv.srsfckn.biz/) releases.

**Comment by haasn** [comment]
Except those are the same thing?

**Comment by TrendaFet** [comment]
I am so confused right now.

The latest @lachs0r release was on Dec 25, 2017 (0.28.0) and the latest in the releases page was released on Feb 14, 2018 (0.28.2).

Are you telling me they're both the same or am I completely misunderstanding something here?

I'll try to eliminate confusion as much as possible: Is there a way to be notified of @lachs0r releases **_only_**, that is synchronized with his Windows releases on https://mpv.srsfckn.biz/ ?

Apologies for any misunderstanding.

**Comment by Hrxn** [comment]
Not really.. Well, you could write a simple script to parse the site (https://mpv.srsfckn.biz/).
Or just visit it once in a while. I know, blasphemy.

**Comment by TrendaFet** [comment]
I honestly don't know why you've been answering every question with a question and using a sarcastic tone. If my question was offensive, apologies. I was merely asking if it was available. I did not ask for someone to make it right now because I asked for it nor have I implied that it not being available is a bad thing.

A simpler "No, specific notifications aren't available but you can watch the whole repository for updates" would have been greatly appreciated, like @wiiaboo answer.

Anyway, thanks all for clearing this up.

**Comment by wiiaboo** [comment]
The latest .1 and .2 security releases are irrelevant for Windows, so no point in making Windows builds of them.
