### ISSUE TITLE
Render API: Make DR (and others?) work

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#5649]
This is a feature request for the libmpv render API. Right now, `vd-lavc-dr` doesn't work, primarily because the generic VO code has no way of dispatching stuff on the libmpv user's render thread.

Some design constraints and considerations:
1. The GL context switching threads is a very big no, so any sort of API based on locking the GL context and moving it to different threads seems inappropriate.
2. We may need to create DR buffers before we're even able to deliver a new frame to render, so doing it at the beginning of the render() function doesn't work if clients only call render() when the render API's update callback fires.

The easiest solution, I think, is to add a new function, like `update()`. Clients should call this regularly on the GL thread, typically once per vsync, even if there are no new frames being rendered. Most of the time, this would be a no-op, so the performance cost would be negligible. DR buffers are only expected to be generated very infrequently.

We probably have to make it UB if render() and update() are called at the same time from different threads, which GL prevents anyway. (Or in the worst case, take a lock inside mpv to prevent it from doing anything bad)

An alternative solution would be mashing this into `render()`, and instead making it so that `render()` itself is a no-op if there are no new frames to render - perhaps with a bool `redraw` that, when true, will always re-render the previous frame even if it hasn't changed. But that also requires changing the API of `render()`, rather than just adding a new function.

**Comment by haasn** [comment]
There's also maybe the potential for deadlock if a lua command is blocked waiting for update() to get called. But I think the libmpv API already makes that requirement. I think it states something to the effect of “you should not call main handle commands like `mpv_command` from the render thread”? So that situation hasn't changed, I believe.

**Comment by haasn** [comment]
Also, for backwards compatibility you probably have to specify up-front that you're going to be using update. If you don't, you're not required to call it, but then you also can't benefit from vd-lavc-dr etc.

**Comment by wm4** [comment]
> The GL context switching threads is a very big no, so any sort of API based on locking the GL context and moving it to different threads seems inappropriate.

How come? Didn't you have a different opinion here?

> We probably have to make it UB if render() and update() are called at the same time from different threads, which GL prevents anyway. (Or in the worst case, take a lock inside mpv to prevent it from doing anything bad)

Since both render() and update() need to be able to access the GL context, and there's no way to access the same GL context from the same thread, all we need to specify is probably that using shared contexts is not allowed. (Shared contexts do not share VAOs AFAIK, so that would break with our code anyway.)

> An alternative solution would be mashing this into render(), and instead making it so that render() itself is a no-op if there are no new frames to render - perhaps with a bool redraw that, when true, will always re-render the previous frame even if it hasn't changed. But that also requires changing the API of render(), rather than just adding a new function.

Also sounds good. The API user has to explicitly enable "other" updates (for update()) anyway, so there is no compatibility problem.

> Also, for backwards compatibility you probably have to specify up-front that you're going to be using update. If you don't, you're not required to call it, but then you also can't benefit from vd-lavc-dr etc.

Yes. Otherwise this would totally break existing clients.

> There's also maybe the potential for deadlock if a lua command is blocked waiting for update() to get called. But I think the libmpv API already makes that requirement. I think it states something to the effect of “you should not call main handle commands like mpv_command from the render thread”? So that situation hasn't changed, I believe.

It changes. Some libmpv users can not have a separate renderer and API thread (Qt in some cases and the SDL mpv example are two examples). That means they should be able to make libmpv calls on the renderer thread. Until now, this usually worked - just commands that need to block on the VO caused a deadlock. But there were not many of such commands. When deadlocks happened anyway, they would cause a freeze of 200ms and a framedrop, and ideally they happened in obscure situations only, not during normal operation.

One example where this currently _needs_ to be possible is mpv_render_context_free(). This function must make the core to destroy the video chain (because the decoder and filters depend on the hwdec context, which is bound to the GL context - the same will happen with DR images). The API user is free to call this at any time.

----

Anyway, the following API styles could be considered:

1. making update() an API function, like mpv_render_context_update(), plus a wakeup callback that tells the renderer thread that it should call it
2. making update() part of mpv_render_context_render(), and allowing the API user to control whether rendering happens at all or if a new frame is available at all with other new mechanisms
3. a user provided callback that runs a libmpv function on the GL thread
4. explicit user provided lock/unlock callbacks (would set the GL context on the thread from which lock is called)

So, option 4. sounds hard to implement, option 3. is kind of redundant with 1./2., because with 1./2. the same would happen under the hood, just that 3. is harder to implement for the user. But option 3 would still provide some alternative ways to handle it (see below). Option 4. sounds like it has other implications for locking, while 1-3. sound equivalent as far as locking issues go.

The fundamental problem with 1-3. is the following scenario:
- the user render thread makes a blocking call to a libmpv function
- the libmpv function makes a call that a) blocks on the VO, or b) blocks on allocating a DR buffer
- the update callback is invoked, but can never be handled, because the renderer thread would have to do this, and is blocked => deadlock

In particular in the a) case the blocking goes through another thread (the VO dispatch thing, which runs the VOCTRL on the VO thread), so we even with option 3. or 4. from above can't just recursively run the work on the blocked renderer thread.

But maybe we could make the blocking libmpv entrypoints special, so that they can be interrupted and run a callback for option 3.? It's getting quite complicated here, though. From the code structure, libmpv entrypoints actually lock the core and then run the core code, so the blocking function will be whatever the core does.

**Comment by haasn** [comment]
> How come? Didn't you have a different opinion here?

No, this was based on a misunderstanding. I thought it was implied that it would still run *on* the render thread. I guess maybe if `lock()` somehow guarantees that we switch to a different thread before returning into this stack frame. (Isn't this possible with some setjmp/longjmp bullshit?) and then switch back in `unlock`, it could be done. But I've been advised with very strong words that the GL thread context switching is not sane.

> Since both render() and update() need to be able to access the GL context, and there's no way to access the same GL context from the same thread, all we need to specify is probably that using shared contexts is not allowed. 

Yep, basically the requirement is that every render API call comes from the same OpenGL context - no mixing different shared contexts together ad-hoc. (And I think this requirement already exists?)

I'll have to think about the remainder of your points.

**Comment by wm4** [comment]
> that we switch to a different thread before returning into this stack frame. (Isn't this possible with some setjmp/longjmp bullshit?)

"No"

**Comment by Akemi** [comment]
was this resolved with the advanced rending?

**Comment by wm4** [comment]
Yes. Though I found bugs and might disable it again.
