### ISSUE TITLE
append-play for loadlist

### ISSUE THREAD

**Issue by burnoutberni** [mpv-player/mpv#5664]
### mpv version and platform

mpv 0.27.2 on ArchLinux

### Reproduction steps

I use mpv running ```mpv --input-ipc-server=/tmp/mpv.socket --idle --quiet``` and I want to enqueue the items contained in a playlist file specifically using ```loadlist```. In my case, this should have a behavior similar to ```loadfile [file] append-play``` in that it resumes playback in case there is nothing being played, but unfortunately this option returns an error.

### Expected behavior

```
$ echo '{ "command": [ "loadlist", "/tmp/tmp.m3u", "append-play" ] }' | socat - /tmp/mpv.socket
{"data":null,"error":"success"}
```

### Actual behavior

```
$ echo '{ "command": [ "loadlist", "/tmp/tmp.m3u", "append-play" ] }' | socat - /tmp/mpv.socket
{"error":"invalid parameter"}
```

**Comment by trames57** [comment]
**Important Information**
MPV version: 0.33.0, Arch Linux

**Reproduction Steps**
I also have a use-case for this. I want to play an entire folder. 

The following works in that mpv will expand the files into the internal playlist, but it will not start playing.
<pre><code>
echo '{ "command": [ "loadlist", "/music/Beethoven Symphony No 7", "append" ] }' | socat - /tmp/mpv.socket
{"data":null,"error":"success"}
</code></pre>

**Expected Behavior**
Add the append-play flag to loadlist and have it work just as it does with loadfile. If no file is currently playing, start playing.
