### ISSUE TITLE
VK_ERROR_OUT_OF_DEVICE_MEMORY when allocating large textures

### ISSUE THREAD

**Issue by quilloss** [mpv-player/mpv#5677]
### mpv version and platform

59a04562b1
Windows 10

### Reproduction steps
Make mpv allocate very large textures (for example 8192x8192, 8196x8196, ...) in a playlist.
`mpv --no-config --gpu-api=vulkan --profile=gpu-hq --log-file=log.txt *.jpg`
Let mpv cycle through the playlist.
Loading each image individually results in no error.

I suspect `MPVK_HEAP_MAXIMUM_SLAB_SIZE` is too large.
Also shouldn't the slab allocated at https://github.com/mpv-player/mpv/blob/master/video/out/vulkan/malloc.c#L336-L341 be set to dedicated. Else these large slabs would never be freed until the end.

Changing the max heap to 256Mb and setting the dedicated flag fixes the problem for me but it feels like a crude solution.
### Expected behavior
No errors
### Actual behavior
`vkAllocateMemory(vk->dev, &minfo, MPVK_ALLOCATOR, &slab->mem): VK_ERROR_OUT_OF_DEVICE_MEMORY`
### Log file

https://gist.githubusercontent.com/quilloss/4b025a1ce5da83eed8fe58a29e001726/raw/b8e413d0dcd5e65628769ea60935d6ac49b21976/log.txt

### Sample files
The required sample files to cause the error would depend on the user's GPU.
This is the script used to generate the sample files for the log.
```
import subprocess
import shlex

size = 8192

for i in range(10):
    cmd = shlex.split(f'magick -size {size}x{size} gradient:#FFF-#0FF -set colorspace hsb -colorspace rgb -quality 10 {i}.jpg')
    subprocess.call(cmd)
    size += 4
```

**Comment by haasn** [comment]
What's strange about your log is this line:

```
[  12.378][v][vo/gpu/vulkan] Allocating 547921920 memory of type 0x1 (id 7) in heap 0.
[  12.385][e][vo/gpu/vulkan] vkAllocateMemory(vk->dev, &minfo, MPVK_ALLOCATOR, &slab->mem): VK_ERROR_OUT_OF_DEVICE_MEMORY
```

For some reason, it's deciding to allocate 547921920 (≈ 522 MiB) of VRAM, which slightly exceeds the 512 MiB limit on slabs and therefore gets served by a new allocation. Since mpv makes no effort to free up or compact existing slabs in order to serve new allocations, this new allocation is likely what causes the total VRAM usage to exceed your device's capabilities. (And which is why it works if you open the image independently)

What I can't explain is how this 522 MiB allocation comes about; in theory your 8228×8228 plane should only be about 64 MiB large, and plenty of those would fit even inside a single 512 MiB slab. Could you maybe break on that call and print a backtrace + information about the `ra_tex_params` that caused it to be allocated?

**Comment by haasn** [comment]
That aside, we could certainly make an effort to try compacting or garbage collecting slabs when `VK_ERROR_OUT_OF_DEVICE_MEMORY` is returned.

**Comment by haasn** [comment]
Oh, actually, that's probably not the image texture being allocated, but rather the rgba16 16-bit texture that will hold the scaled result. That brings it up to the observed >512 MiB in size.

Anyway, there are several possible solutions here:

1. Do what I suggested and try garbage collecting slabs (+ retrying the allocation) if we ever hit an OOM error
2. (Possibly) Make the maximum slab size depend on the available VRAM
3. (Possibly) Cap the number of slabs at maximum size to some fraction of the total VRAM in order to always leave room for large dedicated allocations

**Comment by Akemi** [comment]
is this still the case with libplacebo? if yes please open a new issue.
