### ISSUE TITLE
mpv keeps RSIbreak awake

### ISSUE THREAD

**Issue by vandenoever** [mpv-player/mpv#5702]
mpv keeps RSIbreak awake. RSIbreak is a program that shows a dialog after 10 minutes of activity on mouse or keyboard. 40 seconds of inactivity resets the timer. Somehow playing a video in mpv also keeps RSIbreak thinking that the user is active.

VLC works fine with RSIbreak and does not keep it active.

The bug appears with windowed and fullscreen playing.

https://cgit.kde.org/kidletime.git/
https://cgit.kde.org/rsibreak.git/

### mpv version and platform

mpv 0.28.2 on NixOS Linux with X Windows.

### Reproduction steps

 - Run RSIbreak.
 - Now play a video with mpv and let it play for more than 40 seconds while not touching mouse or keyboard. RSIbreak uses a library called kidletime to track activity.

### Expected behavior

The activity timer should reset.

### Actual behavior

The activity timer does not reset and eventually a popup is shown that the user should take a break, even though the user was not using mouse or keyboard.

### Log file

Probably not relevant.

### Sample files

Not relevant. This is a bug with any video.

**Comment by vandenoever** [comment]
When a video in mpv is playing and a RSIbreak dialog comes up, it resets from 10 to 20 seconds. This implies that mpv sends a signal that wakes up RSIbreak every 10 seconds.

**Comment by lachs0r** [comment]
This is an xdg-screensaver issue. It works by simulating user activity via DBus. If you remove xdg-screensaver, mpv should use the Xss extension (which does not work in GNOME environments but should work on KDE). You can also try `--no-stop-screensaver`, but this will do what it says on the tin. We use xdg-screensaver by default because every single DE needs its own special snowflake way to manage screen savers and power management. It’s a disaster.

**Comment by mattia-b89** [comment]
I can't reproduce this issue; I tried both windowed and fullscreen.

I'm on:
archlinux x86_64
linux-ck-5.0.7-1
mpv-0.29.1
gnome-shell-3.32.0
workrave-1.10.23-2
