### ISSUE TITLE
Build failed on macOS 10.13.4

### ISSUE THREAD

**Issue by fancymax** [mpv-player/mpv#5791]
### mpv version and platform

mpv git HEAD on macOS 10.13.4 with Xcode 9.3:

clang -v output:
Apple LLVM version 9.1.0 (clang-902.0.37.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta93.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

xcode-select -p output:
/Applications/Xcode-beta93.app/Contents/Developer

### Reproduction steps

./waf configure: successful 

./waf:fail

### Expected behavior

./waf:successful

### Actual behavior

Waf: Entering directory `/Users/ws/develop/mpv/build'
[1/1] Compiling version.sh
[215/215] Linking build/mpv
ld: library not found for -ljpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/Users/ws/develop/mpv/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)

I have tried to "brew reinstall jpeg",but ./waf still build fail.
Are there any other step I can try to figure out the build problem?

**Comment by Akemi** [comment]
it's apparently because of [this](https://github.com/mpv-player/mpv/blob/master/wscript_build.py#L160) from commit https://github.com/mpv-player/mpv/commit/a17456608c0eb8dce61951b1beb0cd64e29a0f0a. apparently when setting `-isysroot` it overwrites the library search path and consequential won't look at `/usr/local/lib` for linking anymore, which it does usually. i am not quite sure how to handle this? manually setting `-L/usr/local/lib` after `-isysroot` fixes it, but that seems kinda dirty?

**Comment by fancymax** [comment]
@Akemi tks, you're right.  It build successfully by following your advice。
