### ISSUE TITLE
Clarify default color gamut conversion for BT.2020 in manpage?

### ISSUE THREAD

**Issue by bodayw** [mpv-player/mpv#5834]
I only found out recently that mpv converts BT.2020 color space in the video source to sRGB (?) by default.

This is understandable given that currently there is few to zero consumer displays come close to cover BT.2020 gamut, but it is better to have this default behavior documented.

For example, in https://mpv.io/manual/master/#options-target-prim:

> auto
Disable any adaptation (default)

which is confusing, as I assumed mpv does not do any kind of gamut conversion by default.

Also, I'm not sure sRGB is always the target. On my Windows machine with a standard gamut screen, the results look identical between the default and ``--target-prim=bt.709``, but as people reported in lhc70000/iina#1673, mpv seems could adjust the target gamut per the display (which in that case is DCI-P3). Then again, it baffled me why mpv and IINA have different colors there, therefore clarifying how exactly mpv is handling this would certainly help troubleshooting the problem there.

By the way, there is a minor typo in the manpage which I noticed a while ago, thought not worth opening an issue for it:
https://mpv.io/manual/master/#options-deband

>at the expensive of very slightly blurring

which "expensive" should probably be "expense".

**Comment by ValZapod** [comment]
> Also, I'm not sure sRGB is always the target

It is not. For BT.709 BT.1886 is the inverse and so is default target, so THAT NONLINEAR vlaues are untouched. For srgb transfer srgb is target.

> target gamut per the display (which in that case is DCI-P3).

No, display-p3 and transfer srgb. Sigh. That is what is used on all Apple devices.

> BT.2020 color space in the video source to sRGB (?) by

It is SDR mapping it, so of course transfer NEEDS TO CHANGE. You cannot present PQ on SDR display! BT.2020 primaries to BT.709 primaries is not that visable and BT.2020-NCL matrix vs bt.709 is even less visable, but those two are of course also handled now. sRGB just like PQ is display-referred so that is why it was chosen.
