### ISSUE TITLE
Feature Request : duplicate video window

### ISSUE THREAD

**Issue by AxelTerizaki** [mpv-player/mpv#5844]
Hello.

I'm not sure if this has been posted before or not, but here goes : 

When using mpv to display a vide on a secondary screen, it'd be nice if there could be the same video being displayed as well in a window on the first screen.

This might be possible natively on some OSes but I have no idea how and I wonder if it could be implemented in mpv in some way?

Basically, when showing a video to a crowd on a secondary screen, the user operating the computer attached to that display could verify that the video is correctly rendered (with subtitles, etc) on a small window on its main, internal screen (that person can't see the screen the crowd sees)

I'm not sure if I made myself clear on this, if you need further info I'd be happy to elaborate.

If there's a way outside of mpv to do this, that would work on both Windows, macOS and Linux, that'd be great.

I thought of launching two mpv simultaneously and sending them both the same command via IPC but I'm not sure if this is the best possible solution, as it wouldn't be perfectly in sync (not a big problem), and might be CPU or I/O intensive compared to a simple copy of what's displayed on the other screen.

Thanks in advance for your help.

**Comment by xantoz** [comment]
Didn't old mplayer support something to a similar effect using: http://www.mplayerhq.hu/DOCS/HTML/en/networksync.html

I think it's been removed in mpv, though.

**Comment by Hrxn** [comment]
Maybe https://github.com/Syncplay/syncplay would help?

**Comment by zc62** [comment]
Just duplicate the displays, isn't that simple?

**Comment by haasn** [comment]
At what level would you duplicate them? Would you duplicate the entire `vo`, or would you just duplicate the window and have the `vo` render twice?

**Comment by Hrxn** [comment]
I'd guess he's talking about display duplication functionality of the OS?

Most OSs should support this, as far as I know. Windows definitely does (`Settings -> Dispay -> Multiple Displays -> Set to duplicate`).

But only for "locally" connected displays, obviously.

**Comment by AxelTerizaki** [comment]
I wasn't talking about displays : I know how to duplicate displays from the OS. My ideas was to be able to duplicate the window mpv works in. Controlling one mpv but having two identical windows showing the exact same render.

**Comment by zc62** [comment]
I know you are not talking about displays. I am just curious about why duplicating the displays does not suit your need.

**Comment by AxelTerizaki** [comment]
Oh.

Well, because that'd require a 3rd screen somehow. My use case is some operator playing videos on a big screen, but he needs some kind of mirror of what's on screen, in another window while he can control whatever he's doing (think video DJ or something) on his screen.

Screen 1 : controls + small window showing what's on screen 2
Screen 2 : main screen

**Comment by zc62** [comment]
Probably [OBS](https://obsproject.com) is what you need. Run mpv on screen 2, then use OBS to preview it on screen 1.

**Comment by haasn** [comment]
Some thoughts: In theory, if we duplicate at the `vo` level, we could make it so that only the `master` display uses the main video settings, while the `slave` display uses lower settings in order to not consume as much GPU time. That said, duplicating at the `vo` level has other drawbacks, like the fact that you need to reupload the image twice instead of being able to share the GPU texture. There's also the concern of now needing to synchronize two `vo`s instead of just one. (Which is why I referred to one as the `slave`, presumably you'd completely ignore the timining of this one and just assume it roughly follows the master's output schedule. But if your GPU is too slow and is dropping frames, the two could desynchronize. Unless you actually want to put in code to try and synchronize the two `vo`s exactly, even in display-synced mode etc...)

Duplicating inside the `vo` solves some of these issues but has other drawbacks, such as the fact that you'd now be paying the render cost twice (assuming both windows would use the same settings). There's also the issue of needing to re-configure filters, and duplicate all logic related to window management.

In terms of performance, the best compromise would be this:
1. Allow `vo_gpu` to have a second "control" window reference. This is unfortunately pretty invasive, since due to crap like OpenGL, we need the context to be tied to the display connection. So the actual `ra_ctx` has to be providing two windows, which requires changing all `ra_ctx`.
2. Always render in dumb mode to this window, to avoid issues like the above. (This also needs blacklisting some other settings like HDR peak detection and presumably also color management)

All in all this seems to paint a bleak picture of either 1) invasive changes requiring lots of redundant code/logic, or 2) inefficient design.

Probably the only sane way to implement this would be to duplicate at the `vo` level inside the player core, slave the second vo to the first, and ignore any timing differences. (Or maybe we could do some best-effort timing like trying to drop frames from the slave vo if it desyncs from the master). Stuff like display-sync obviously would be completely ignored for the slave. Users would have to pay the RAM->VRAM upload twice.

**Comment by haasn** [comment]
Oh, also, to actually be useful, we'd also need an option to restrict rendering the OSD messages to the slave window only, so you can actually interact with it without the 'big screen' users realizing. Otherwise what's the point?

**Comment by AxelTerizaki** [comment]
I personally run it with the OSD disabled as I don't use it. My app sends IPC commands to navigate through the file from a web interface. Using keyboard keys also works fine. My only use of the OSD is to occasionally display text and announcements on screen via the `show-text` command.

So all in all, if the OSD is disabled, it's not a big issue.

If this feature requests causes too much hassle to implement, I'd understand. Being a dev as well, I try to keep it simple myself in my code when it comes to new features. Not being knowledgeable in mpv's code, I have no idea if this is hard to implement well or not.

**Comment by AxelTerizaki** [comment]
> 
> 
> Probably [OBS](https://obsproject.com) is what you need. Run mpv on screen 2, then use OBS to preview it on screen 1.

This is not a bad idea at all, but I'd like to avoid using another software to implement this if possible.

**Comment by zc62** [comment]
Come on, why bother adding a "feature" that only 0.0001% user will use and can be perfectly achieved by another program. mpv is a media player, let it do what a media player should do, and let other programs handle other functionalities. Would you request every game to support live streaming internally? Would you require Firefox to duplicate the window? This is complicating originally M+N implementations to MxN.

**Comment by zc62** [comment]
> If there's a way outside of mpv to do this, that would work on both Windows, macOS and Linux, that'd be great.

This is what you said in your original issue. OBS works with every program on every platform. That is why OBS exists. You do not need to request to every single program to add the features that OBS provides.

**Comment by AxelTerizaki** [comment]
If it were only for me, obviously I'd use something like OBS (although it wasn't made for this originally, mind you) but I'm making an app that uses mpv through IPC commands. Asking the end-user to configure OBS in the right way (or any other piece of software) versus having a single button to press to get a second window for monitoring what's being displayed... the latter is a much user-friendly solution.

Being user-friendly is important, but I also understand that inelegant code should be avoided at all costs. If it's feasable in a reasonable way, then I'd like this to be implemented. If it's not, requires too much work or pollutes the code too much, then it's okay, let's forget about it. Not knowing how mpv's internals work, I couldn't tell if it was a good idea or not, hence why I created the issue.

mpv already has a lot of features that 0.0001% of users would make use of, so that point doesn't sound really valid to me there. Using third-party software to implement this is not user-friendly at all, or dev-friendly in my case since I'd need to manage OBS from my app in addition of mpv, and let's not talk about download size of the whole package (OBS isn't exactly small...)

I understand if it's not easy to implement, but at least try to understand what I'm saying here.

**Comment by zc62** [comment]
> I'm making an app

If your app is designed for end-users that all require such video-DJ-like operations, shouldn't it be implemented in your app? If mpv with IPC commands does not work, try libmpv. If libmpv does not support this either, copy mpv's relevant code (with licenses compatible with LGPL) to your project and implement the window duplication.

I agree that if your app is designed for video DJ operations, it surely requires internal implementation to be user-friendly. But when it comes to mpv, probably not the case, mpv is not designed to do this. It has nothing to do with if this is easy to implement or not. It just feels... irrelevant.

> 0.0001% of users would make use of

Then you are not directly using mpv. So I may correct 0.0001% to 0%.

If you need assistants about if/how libmpv can handle this (but I know little about libmpv, sorry), and/or how to implement your window duplication yourself, I believe people here are pleased to provide helps.

**Comment by haasn** [comment]
I think it's a perfectly reasonable feature request. Being able to support multiple `vo` (or multiple `ao`) seems in scope for a media player as flexible as mpv. I just don't think it's reasonable to implement, due to mpv's internal design. If we had a cleaner module abstraction like VLC it would be a lot easier. (Incidentally, VLC supports this (or will soon))

FWIW, I agree that there's nothing wrong with supporting niche use cases in mpv as long as it doesn't get in the way, but I also want to point out that mpv does not necessarily concern itelf unnecessarily with user friendliness. If something is out of scope, it is out of scope, no matter how user friendly it might be.

**Comment by haasn** [comment]
FWIW it does sound like libmpv could be made to do what you want directly. Just have libmpv render to the main screen and then read back from this texture for your previewing purposes (just bilinear sampling should be fine. It will look like shit, but it's only a preview, right?)

**Comment by AxelTerizaki** [comment]
Again, I perfectly understand, as a dev, that if it gets too much in the way, it's not reasonable to implement it. My current way of doing it (spawning two different mpv processes and communicate with them both to keep them in sync) is working so far (albeit with a few quirks, but it's not much hassle). I was just inquiring if there was an easier way to implement that from mpv itself, from my point of view.

Unless someone comes with a clever and elegant way to do this in mpv, I believe the issue can be safely closed then :)

**Comment by haasn** [comment]
Then I'll close it for now. If something significant changes about the mpv architecture in a way that would make this reasonable to implement, we can reopen it in the future.

**Comment by AxelTerizaki** [comment]
@haasn My app is in nodeJS and I don't believe there's a way for me to use libmpv easily. Communicating through IPC with a mpv process is much easier to use on my end. I'll take a look though.

**Comment by AxelTerizaki** [comment]
Thanks everyone for your input, by the way.

**Comment by zc62** [comment]
Multiple `ao` has been requested before: #675

@AxelTerizaki [mpv.js](https://github.com/Kagami/mpv.js/) is probably a nodeJS example that uses libmpv.
