### ISSUE TITLE
--opengl-es=auto does not attempt to use OpenGL ES

### ISSUE THREAD

**Issue by AstroSnail** [mpv-player/mpv#5915]
Somewhat related to #5903 

### mpv version and platform

mpv 0.28.2
Arch Linux x86_64

```
mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May 14 09:49:30 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0
```

### Reproduction steps

Have an old computer which supports only really old OpenGL versions (in my case, OpenGL 1.4 and OpenGL ES 2.0)
**OR**
(if you use mesa) Use the `MESA_GL_VERSION_OVERRIDE` and `MESA_GLES_VERSION_OVERRIDE` environment variables to change reported OpenGL(ES) versions
**THEN**
Play videos with `--vo=gpu --gpu-api=opengl --opengl-es=(yes/no/auto)`

### Expected behavior

When video is played with `--opengl-es=auto`, mpv detects the system's OpenGL and OpenGL ES versions, and makes a decision whether to use one or the other based on the versions. (e.g. if OpenGL <2.1 but OpenGL ES =2.0, OpenGL ES is selected)

When video is played with `--opengl-es=(yes/no)`, then OpenGL ES is forced or disabled appropriately.

### Actual behavior

When `--opengl-es=auto` is used and OpenGL is _available_ (not necessarily usable), then mpv only tries to use it, and errors when the OpenGL version is insufficient. No attempt is made to use OpenGL ES.

When `--opengl-es=yes` is used and OpenGL (not ES) is _usable_, then OpenGL is used, not OpenGL ES.

### Log file

`mpv --vo=gpu --gpu-api=opengl --opengl-es=auto` https://0x0.st/s_U0.txt

In this one I use environment variables to force mesa to accept OpenGL 2.1 contexts, even if they aren't supported by the hardware, and to reject OpenGL ES contexts newer than 1.0.
`MESA_GL_VERSION_OVERRIDE=2.1 MESA_GLES_VERSION_OVERRIDE=1.0 mpv --vo=gpu --gpu-api=opengl --opengl-es=yes` https://0x0.st/s_Uk.txt

### Sample files

Happens with every file I tried so far, so I'm fairly sure I don't need to upload samples.

**Comment by AstroSnail** [comment]
The bad `--opengl-es=yes` behaviour started with commit 65979986a923a8f08019b257c3fe72cd5e8ecf68.

The `--opengl-es=auto` behaviour is still the same immediately before it. This might not be a bug, but it's unintuitive and imo needs to be explicitly stated in the documentation.

**Comment by Dudemanguy** [comment]
Gave this a whirl over here. `--opengl-es` worked just fine. With `yes` I get this in my log and it works as expected.

>[   0.057][v][vo/gpu/wayland] GL_VERSION='OpenGL ES 3.2 Mesa 21.1.5'
>[   0.057][v][vo/gpu/wayland] Detected GLES 3.2.

My default opengl is:
>[   0.063][v][vo/gpu/wayland] GL_VERSION='4.6 (Core Profile) Mesa 21.1.5'
>[   0.063][v][vo/gpu/wayland] Detected desktop OpenGL 4.6.

As for the `opengl-es=auto` behavior, I am not so sure. I can simulate not having a usable desktop EGL by using the `MESA_GL_VERSION_OVERRIDE` variable of course. And like you said, mpv is not able to find opengl es either when you do that and errors out. But since my GLES version is apparently 3.2, I'm not sure I should be expecting anything to be found in the first place if I force mesa to only look for `2.0` or something. Anyways apparently this behavior never changed and the `opengl-es` options appears to work so I will close this for now.

**Comment by AstroSnail** [comment]
Thanks for reminding me about this three-year-old issue! I tested just now with mpv 0.33.1 and the issue mostly no longer occurs, in that setting `--opengl-es=yes` and `--opengl-es=no` correctly force on or force off the use of OpenGL ES. However, `--opengl-es=auto` still behaves as described in the issue, and doesn't attempt to use OpenGL ES.

**Comment by AstroSnail** [comment]
To clarify, the testing method I'm using is as follows:
```
$ MESA_GL_VERSION_OVERRIDE=1.0 MESA_GLES_VERSION_OVERRIDE=1.0 mpv --vo=gpu --gpu-api=opengl --opengl-es=auto media/video/sleetcat.mp4
# this fails, as expected
$ MESA_GL_VERSION_OVERRIDE=2.1 MESA_GLES_VERSION_OVERRIDE=1.0 mpv --vo=gpu --gpu-api=opengl --opengl-es=auto media/video/sleetcat.mp4
# this works and uses OpenGL, as expected
$ MESA_GL_VERSION_OVERRIDE=1.0 MESA_GLES_VERSION_OVERRIDE=2.0 mpv --vo=gpu --gpu-api=opengl --opengl-es=auto media/video/sleetcat.mp4
# this fails. i expect it to attempt OpenGL ES
$ MESA_GL_VERSION_OVERRIDE=2.1 MESA_GLES_VERSION_OVERRIDE=2.0 mpv --vo=gpu --gpu-api=opengl --opengl-es=auto media/video/sleetcat.mp4
# this works and uses OpenGL, as expected
```

**Comment by Dudemanguy** [comment]
Okay yeah that makes sense. The third case does sound like a legitimate bug with `--opengl-es=auto` option. It should make an attempt to use GLES if Desktop Opengl fails for some reason (otherwise what's the point of having an auto option).

**Comment by Dudemanguy** [comment]
Okay so I figured out why this occurs. This behavior will only happen if you use `MESA_GL_VERSION_OVERRIDE` or some other thing that tricks `glGetString` into reporting a value that is less than 210. mpv has a hard requirement on at least 210 or 200 (for es) In the common opengl code, this is checked using glGetString. Thus, you get a a fatal error and mpv quits. However, the only reason the code reaches that far in the first place is because the check in EGL is passed when the EGLContext is created (i.e. you are able to create a valid EGL context because your drivers support it). mpv just loops through a hardcoded list of versions to try and you will successfully create a 4.4 context (or whatever it may be in your case).

On an actual device that doesn't actually support an appropriate desktop GL version, the `auto` behavior will work correctly (you can simulate this by simply always returning `false` in `create_context` in the desktop opengl portion). You will fail at creating any EGLContexts and then it will attempt with GLES later which will work.

So I guess the actual bug here is that sometimes mpv cares about `MESA_GL_VERSION_OVERRIDE` (when using `glGetString` even though it's implicit) and other times it totally ignores it (when probing contexts). It would be relatively simply to just parse that environment variable and take that into account but that's always a little icky. Not sure.

**Comment by AstroSnail** [comment]
Thanks for the insight. I went ahead and tested on a real device which doesn't support OpenGL 2.1, but does support OpenGL ES 2.0, and I still get the behaviour I found before.

Here's a log where I run mpv 0.33.1 on a computer which doesn't support OpenGL 2.1, but does support OpenGL ES 2.0 https://cdn.discordapp.com/attachments/799722753325400095/868191885984944178/mpvlog.txt
Here's a log where I run mpv 0.33.1 on a computer which **does** support OpenGL 2.1 https://cdn.discordapp.com/attachments/799722753325400095/868191893568258118/mpvlognv.txt
(These are discord uploads because the 0x0.st uploads didn't survive the age of this issue)

**Comment by Dudemanguy** [comment]
That's a very interesting result. I'd expect `eglCreateContext` to fail if you try to create an EGLContext for an OpenGL version that is not supported. If I simulate this with the `MESA_GL_VERSION_OVERRIDE=2.1` environment variable, that's what happens (it cycles through the loop and fails until you try 210). Apparently, that doesn't happen on your device for some reason. I don't know why that would be the case.

**Comment by AstroSnail** [comment]
I found the code you mentioned, that tries a hardcoded list of OpenGL versions.

https://github.com/mpv-player/mpv/blob/master/video/out/opengl/egl_helpers.c#L191-L196

However, there's an additional check for EGL version 1.4, which causes the code to ignore the hardcoded list of versions, and proceed with whatever it gets.

**Comment by Dudemanguy** [comment]
Oh duh, how did I miss that. At least on the surface, that looks like something that shouldn't exist. I'll run through the git history.
