### ISSUE TITLE
Build fails on Mac OS X 10.10

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#5972]
Opened a new issue as requested in https://github.com/mpv-player/mpv/issues/5899

https://gist.github.com/mlindner/1ede5b66e4069462e858f56476db1213

$ xcodebuild -version
Xcode 7.2.1
Build version 7C1002
$ swift --version
Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin14.5.0

**Comment by Akemi** [comment]
the cocoa-cb backend at least needs swift version 3 to build. if apple doesn't provide newer build tools for 10.10 you need to disable cocoa-cb via "--disable-macos-cocoa-cb" on "waf configure".

**Comment by mlindner** [comment]
xcode 7.2.1 is the latest available version for 10.10.x as far as I am aware. I believe xcode 8 is required for swift 3.

**Comment by mlindner** [comment]
Is it possible to maintain support for swift 2?

**Comment by Akemi** [comment]
possible yes, but i am not really willing to add swift 2 support for various reasons.
- 10.10 is a 'deprecated' version of macOS
- 10.10 didn't have the problems that cocoa-cb fixes on newer versions of macOS
- even swift 3 has some problems i encountered that were fixed with newer versions of swift
- there are around 350 errors/warnings (counting the duplicates) that have to be fixed, this would pollute the code base with macOS versions checks and makes it less maintainable and readable.
- i even consider dropping swift 3 support at some point.

hopefully swift will get more stable with the upcoming versions, so we won't encounter such drastic changes any more in the future.

**Comment by mlindner** [comment]
The official supported version list still says 10.8. This obviously isn't true anymore based on your comment.

**Comment by mlindner** [comment]
I should note that downgrading mpv version to 0.27.2 makes things work without issue.
