### ISSUE TITLE
Fails to build mpv 0.29 on OS X: framework not found AppKit

### ISSUE THREAD

**Issue by Civil** [mpv-player/mpv#6036]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
1. Get gentoo prefix. It's specific is that it uses upstream version of clang to build software.
2. bootstrap.py
3. export CC="/Users/civil/gentoo/usr/lib/llvm/6/bin/clang"
4. ./waf configure
5. ./waf

Frameworks that can't be found sometimes different, it can be AppKit, IOSurface, etc. - I think it depends on link order.

I suspect that culprit is changes related to https://github.com/mpv-player/mpv/commit/a17456608c0eb8dce61951b1beb0cd64e29a0f0a.diff

In 0.28.2 there was no -isysroot appended and that worked fine for Gentoo environment.

Also to fix build issues it's enough for me to apply following patch: https://gist.github.com/Civil/c48e03522c86ebbf77ca5aae49500d12

I understand that it fixes build for some of the cases, so is it possible to make this "append" under a flag or something?

### Expected behavior
1. Should build (0.28.2 builds just fine)

### Actual behavior
1. Failes with error (see log)

### Log file
mpv 0.29 build log: https://gist.github.com/Civil/74487f0a77e9fb61652c95cc1e6f53bf
mpv 0.29 config log: https://gist.github.com/Civil/22b774d6ffd39095cef97d400a429459

mpv 0.28.2 config log: https://gist.github.com/Civil/7c8f1a704a96c96d193dd357468f364e
mpv 0.28.2 build log: https://gist.github.com/Civil/6ca417e4f9156348ced669d949a5d8f5

clang configuration: https://gist.github.com/Civil/e23ee8bff1d0a83641535ae21c27a1a6

**Comment by Civil** [comment]
Sorry, I've updeated log for 0.29, now it's full.

**Comment by Akemi** [comment]
just a heads-up. i got myself a gentoo prefix for testing, and i am completely unable to build mpv with it, even with your proposed fix. i have to disable the swift features for it to work. probably because my SDK version (10.13) is different from my OS version (10.12).

i will try to test some things when i got the time and see what the actual problem is.

**Comment by Akemi** [comment]
#6703 most likely laid the ground work to fixing this. for one with swift 5 we can dynamically link to ABI stable libs and everything concerning sdk paths and versions can now be configured with env variables if the auto detections fails.

i can't and won't test this further, since the gentoo prefix is not working for me out of the box, i don't feel like wasting time on it and this setup is an out of the ordinary use case.
