### ISSUE TITLE
Can not toggle to 1.778 and 1.333 aspect ratio via shift-a

### ISSUE THREAD

**Issue by pgmd** [mpv-player/mpv#6068]
### mpv version and platform
v0.29.0 on 4.17.12-200.fc28.x86_64
I originally noticed with rpm-fusion rpm build for this version.  Below is results from local build.
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build/
./use-mpv-release
./update
./rebuild -j6
### Reproduction steps
cd mpv/build
./mpv FILE
press shift-A
### Expected behavior
Should show video in 1.778 ratio (16:9)
(pressing again would show 1.333)
(pressing again would show 2.350)
### Actual behavior
Shows 2.350, pressing again returns to 2.348
### Log file
https://0x0.st/sJTy.log
### Sample files
Did not attach.  Seems to behave this way with all locally derived and fetched from web

**Comment by zc62** [comment]
https://mpv.io/manual/master/#command-interface-cycle-values
> The command will use the current value of the property/option, and use it to determine the current position in the list of values. Once it has found it, it will set the next value in the list (wrapping around to the first item if needed).

https://github.com/mpv-player/mpv/blob/master/etc/input.conf
> cycle video aspect ratios; "-1" is the container aspect
> A cycle-values video-aspect "16:9" "4:3" "2.35:1" "-1"

The log indicates you are playing a 4:3 video. Your expected behavior should be:
1. Originally playing at aspect=4:3
1. Press Shift-A: change to 2:35:1 (because `cycle-values` will find your current aspect ratio is in the list. It needs to change the current value to the value in the next position, but not the first item in the list)
1. Press Shift-A: change to container aspect, that is 4:3
1. Press Shift-A: wrapping around to the first item: 16:9. So set to 16:9 aspect
1. Press Shift-A: change to 4:3 aspect

What I see when I test myself is:
1. Originally playing at aspect=4:3
1. Press Shift-A: change to 2:35:1
1. Press Shift-A: change to container aspect, that is 4:3, **but the message incorrectly says it is 2.348**
1. Press Shift-A: `cycle-values` once again recognizes this video is 4:3, ignoring items before 4:3 and directly goes to the value after 4:3, which is 2.35:1
1. Press Shift-A: change to container aspect again.

If you test with a 16:9 video, then the loop is 16:9->4:3->2.35:1->container (16:9)->4:3, which "looks" correct.

If you delete the "-1" in the values that aspect ratio cycles, then you will see the 4:3->2.35:1->16:9->4:3 cycle, but definitely not the correct default we want.
