### ISSUE TITLE
Add a sleep function to mp.utils module.

### ISSUE THREAD

**Issue by wjtk4444** [mpv-player/mpv#6079]
Script developers could make a great use of a sleep api provided by mpv. Currently, there's no way to 'sleep' inside of a lua script other than using external tools such as an os shell (ping) or an external dependency (lua sockets, for example). Existing solutions aren't multiplatofm as well. Consider this example of a lua sleep module:
```
local utils = require 'mp.utils'

function detect_platform()
	local o = {}
	if mp.get_property_native('options/vo-mmcss-profile', o) ~= o then
		return 'windows'
	elseif mp.get_property_native('options/input-app-events', o) ~= o then
		return 'macos'
	end
	return 'linux'
end

local platform = detect_platform()
	
sleep_module = {}

function sleep_module.sleep(duration)
	if tonumber(duration) < 1 then return end
	
	if platform == 'windows' then
		utils.subprocess({ args = {
			'ping', '-n', tostring(tonumber(duration) + 1), 'localhost > NUL'
		} })
	else
		utils.subprocess({ args = {
			'sleep', duration
		} })
	end
end

return sleep_module
```
It's just so wrong, both the precision and the implementation of the solution.

**Comment by avih** [comment]
You could have written your script instead as:
```lua
function sleep(secs)
    local t0 = mp.get_time()
    while mp.get_time() - t0 < secs do end
end
```

However, like your script, this is wrong. Your example and the code above are wrong because they're synchronous - they blocks the events loop. Like in a web browser if you have a function which busy-waits. This means that at some stage mpv will start dropping events to your script, because the script is stuck and can't process new incoming events from mpv.


The correct way to write scripts for mpv (or for a web browser), is by registering events/callbacks and then doing things quickly at your handler.

As for your problem, mpv does support "sleep", though a-synchronous. It's called timers:

In Lua:
```lua
local t0 = mp.get_time()
mp.add_timeout(1.7, function()
    print("I just slept", mp.get_time() - t0, "seconds")
end)
```

Or in JS:
```js
var t0 = mp.get_time();
setTimeout(function() {
    print("I just slept", mp.get_time() - t0, "seconds");
}, 1700);
```

These two example are correct because they don't block the event loop. The event loops knows that there's a callback which should be invoked after some seconds, and during those seconds other events can come in and get dispatched, like key binding events.

**Comment by wjtk4444** [comment]
How would one go about making a "while true" loop that does something every N seconds?
The following code makes mpv start in cli mode and use a whole cpu core to operate.
```
function sleep(secs)
    local t0 = mp.get_time()
    while mp.get_time() - t0 < secs do end
end

while true do
	sleep(5)
	mp.osd_message("I just slept", 5, "seconds")
end
```

Also, why would anything done in a script block the event loop? Afaik scripts are sandboxed, so at worst only the events registered in this particular script should be ommited / blocked.

**Comment by avih** [comment]
Use`mp.add_periodic_timer` instead of `mp.add_timeout` (in lua), or `setInterval` instead of `setTimeout` in JS. You should really [read](https://mpv.io/manual/master/#lua-scripting-mp-add-timeout%28seconds,-fn%29) the [manual](https://mpv.io/manual/master/#timers-global).

The usage of a-synchronous events in mpv is pretty much like in a web page script in a web browser. If you've never wrote scripts for a web browser or didn't do a-synchronous stuff, then it might take a bit to wrap your head around it, but this is already off topic for this issue, and covered in million other places.

**Comment by Argon-** [comment]
Absolutely have to agree with avih here.
Mpv has timers which is a considerably "mightier" concept. If desired, you could always simulate a blocking sleep with timers but there is no point.
Blocking your own script really just takes away flexibility: you can no longer receive events etc.
A blocking sleep is bad style and you should rewrite the structure your script to be asynchronous instead.

Keep in mind that timers can be dynamically created, stopped and deleted at any time. That way you have full flexibility.

**Comment by avih** [comment]
mpv and web browsers don't have sleep because it doesn't fit the event-loop-with-asynchronous-callbacks model, which mpv and web browsers use.

There are more complex concepts which do sort of support sleep in an event-driven model, like co-routines and promises and generators. I _think_ you can use co-routines in lua in mpv, and you can use promises in js in mpv (find such module someplace and `require` it), though no generators as those are ES6, and js in mpv is ES5.1 .

While it might be useful to have a sleep function, you'll figure out fast enough that timers are way better, and many times simpler to use that synchronous sleep. Every web developer knows (or should know) that, and you should too.

Take the time, it takes a bit to learn how to work in this model, but ultimately it's a tried and true model, and you'll do just fine.
