### ISSUE TITLE
script-opts of user's LUA script in filedir-conf don't take effect

### ISSUE THREAD

**Issue by koseidon** [mpv-player/mpv#6116]
### mpv version and platform
mpv-x86_64-20180902-git-a5b0d59

### Reproduction steps
Writes LUA script under default user script dir (%APPDATA%\mpv\scripts), adds use-filedir-conf=yes in default user conf (%APPDATA%\mpv\mpv.conf), and writes mpv.conf under media file dir. 

### Expected behavior
All confs in filedir-conf take effect.

### Actual behavior
All confs in filedir-conf take effect except script-opts of my LUA script, script-opts of native LUA script also take effect. If I add include=(path of filedir-conf) in default user conf (%APPDATA%\mpv\mpv.conf), script-opts of my LUA script take effect, but flexibility losts. How can I do?

**Comment by Dudemanguy** [comment]
I swear when I last tried this way back when it didn't work, but actually this works just fine for me now with a one-line script.
```
mp.set_property_bool("use-filedir-conf", true)
```

Looking at the code, there's no reason it shouldn't work since it will get read anytime you load a file. If your script doesn't set the option early enough, then it might not do anything. You can use the `on_before_start_file` if you need too.

**Comment by guidocella** [comment]
Pass an empty function as the third argument of `read_options` to enable run-time updates of your scripts' options.
