### ISSUE TITLE
[Feature Request] Frame doubling (to better support FreeSync/G-Sync)

### ISSUE THREAD

**Issue by pinumbernumber** [mpv-player/mpv#6137]
### mpv version and platform

N/A, Windows 10 x64

### Reproduction steps

Play a 24fps video using a monitor which has adaptive sync but which does not have built-in low-framerate compensation. (Most 4K monitors fall under this, for example. A 40-60hz freesync range is typical with no LFC.)

### Expected behavior

Each frame should be presented twice, resulting in a 48fps effective framerate and allowing freesync to kick in. The video should therefore play free of typical 24-on-60 judder.

Win10's built-in "Films & TV" player can do this, and so can Edge. Verified using my monitor's OSD. No other player that I've tested can do it. I think it would be a great feature to add for owners of adaptive sync displays.

I would suggest that the video's actual framerate should be multiplied by the largest integer such that the result does not exceed the monitor's reported refresh rate. For example, 24fps content would be doubled to 48 on 60hz displays, and tripled to 72 on 75hz displays. This maximises the likelihood that adaptive sync will kick in.

### Actual behavior

The video is presented at 24fps (confirmed with Afterburner's OSD), and freesync does not kick in. The monitor remains at 60fps, and the expected judder is present.

### Log file

N/A

### Sample files

N/A, any 24fps file

**Comment by Akemi** [comment]
you can use the [fps ffmpeg filter](https://ffmpeg.org/ffmpeg-filters.html#fps-1) for that, `--vf=fps=fps=48`. just simply write a script that sets this filter dynamically by observing/reading the `display-fps` and `fps` properties, similar to [this](https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/scripts/avail/fpsadjust.lua) script.

**Comment by haasn** [comment]
I thought drivers are already capable of doing this under the hood?

Solving this generally is probably going to be rather tricky, since we don't even know the input framerate. But you could approximate it maybe with `--tscale=nearest` and some options to control the display FPS? Dunno.

**Comment by pinumbernumber** [comment]
@Akemi I'll check that out, thanks for the advice. It would be nice to have it built-in instead of a separate lua script, though.

@haasn 

>I thought drivers are already capable of doing this

Not in general. With FreeSync this is called Low Framerate Compensation. Not all monitors have it, and I don't believe *any* 4K FreeSync displays do at the moment. Even when it's available, it has been known to cause flicker and other issues. Far better to output somewhere in the native freesync range (usually 40-60).

>we don't even know the input framerate

Maybe not in special cases, but the vast majority of files have a fixed known framerate, don't they?

**Comment by Argon-** [comment]
>Maybe not in special cases, but the vast majority of files have a fixed known framerate, don't they?

Problem is that even when their metadata contains it you don't know if it's correct. I've got plenty of files here claiming slightly wrong values or such that are completely ridiculous (0 or 9000). 
You don't notice this because players really don't care about this value. Relying on it would definitely lead to problems.

**Comment by pinumbernumber** [comment]
Well, it looks like my ignorance of video timing techniques is showing. If the framerate isn't reliably known upfront, then the duration of the frame that is about to be presented must at least be known immediately before said presentation, right? So to greatly oversimplify (for example I assume present() returns instantly, which it definitely doesn't), I assume it might look something like this right now:

    present(frame.data);
    sleep_ms(frame.duration);

The frame doubling would look something like

    present(frame.data);
    sleep_ms(frame.duration/2);
    present(frame.data);
    sleep_ms(frame.duration/2);

**Comment by haasn** [comment]
Actually, couldn't we do it like this? Combining the two things we *do* know:

1. The display framerate (which for adaptive sync I assume is meant to be an uppter limit)?
2. The presentation duration of the frame (by comparing this and the next frame's timestamp)

We could calculate the number of repetitions as `floor(frame_duration / vsync_interval)`. So for an example of a 41.7ms frame on a 16.6ms monitor, we would end up repeating it twice, each repeat for a duration of exactly 20.85ms, giving us an effective total framerate of 48 Hz (by repeating each 24 Hz frame twice).

**Comment by pinumbernumber** [comment]
Yes- if I follow you correctly, that would achieve what I'm looking for. The monitor's reported framerate is indeed an upper limit- the lower limit is usually around 40. (Any lower than that requires LFC which is a bit of a minefield and, as I said above, not currently available on 4K monitors).

**Comment by grantwwu** [comment]
Any possibility we could get this reopened, @Akemi?

**Comment by zc62** [comment]
Just curious, does [`interpolation`](https://mpv.io/manual/master/#options-interpolation) do the job?

**Comment by xnoreq** [comment]
@zc62 The whole point of adaptive sync is NOT to synchronize to the display refresh rate but to just present at a certain rate and the monitor adjusts to that rate.

The whole implementation should be really simple:
1) the monitor runs at the max refresh rate
2) a configuration option tells mpv the min_adaptive_refresh_rate
3) frame_repeat_count = ceil(min_adaptive_refresh_rate / video_fps)
4) present each frame at 1 / (video_fps * frame_repeat_count) time intervals

Example:
- 120 Hz monitor with 40 Hz min refresh rate
- 23.976 fps video
- => frame_repeat_count = 2
- => each frame (including the repeated ones) is presented at ~20.8542 ms intervals (= 47,952 fps)

You don't need any interpolation, no waiting for vsync. Just present the frames at a high enough rate (by showing them multiple times if needed) and the monitor will adjust.

**Comment by zc62** [comment]
I've recently acquired a freesync display, which has the range set to 57-144Hz. When I play a 24fps video file with mpv in fullscreen, the OSD of my monitor shows something around 72Hz . I think the feature is already there? Nothing needs to be done in mpv. GPU APIs or drivers handle this. You could try to enable the recently added 'Variable Refresh Rate' for d3d11 in win10 1903, but I tried vulkan API, works too.

**Comment by magicgoose** [comment]
> Solving this generally is probably going to be rather tricky, since we don't even know the input framerate.

I think it's okay. It's only needed to know pts of this frame and next frame. And you insert a frame between them (if the interval is not already short enough).  
(And if effective FPS is already high enough, then that interval will always be short enough and nothing will be inserted.)

**Comment by wm4** [comment]
Doubling the framerate is trivial, you can probably construct something with existing libavfilter filters.

**Comment by philipl** [comment]
FWIW, my freesync display allow frame doubles just fine - and from an nvidia gpu no less.

**Comment by Artins90** [comment]
> FWIW, my freesync display allow frame doubles just fine - and from an nvidia gpu no less.

Could you post your config file?
I have a 35-60Hz screen running off a 2080Ti but I can't get freesync to work properly with mpv, for 24 fps videos it uses 2.500 vsync rate instead of doubling to just 2.000.

**Comment by philipl** [comment]
@Artins90 You're using interpolation. Turn it off.

**Comment by wm4** [comment]
Do you mean --video-sync=display...?

**Comment by philipl** [comment]
Sorry, I do mean that - although I think he has to also be turning on interpolation for it to be doing 2.5 rate, right?

**Comment by Artins90** [comment]
> @Artins90 You're using interpolation. Turn it off.

Without interpolation the 24 fps video runs at 60 fps with 2.5 vsync rate.
If I delete "video-sync=display-resample" from the config file, the afterburner osd rports 24 fps but my screen can't do 24 fps since it's outside the freesync window and the monitor doesn't support frame doubling on its own.  

I would like to know if there is a way to have mpv output each frame of the 24 fps video 2 times, resulting in 48 fps playback, which is within the freesync range supported by the monitor, forcing vsync rate to 2.000 rather than 2.500 would do the trick.

**Comment by philipl** [comment]
Well, sure, then you're in the same boat as the original reporter. I was just saying my display does frame doubling so everything works fine. There's no config magic that will allow it to work with a non-doubling display.

**Comment by wm4** [comment]
I don't think interpolation affects how many frames it outputs. It'll just affect performance in various ways.

And also, with --video-sync on default, it won't measure or report any relevant statistics (it'll only show the nominal FPS reported by the OS on the stats screen).

**Comment by wm4** [comment]
Also I guess you can try ``--vf=fps=48/1.001`` (if I understand the problem correctly, but I didn't try to). Of course this is for testing only and very much not recommended for normal use. It's meant for files with ~23 fps, and won't work 100% correctly (mkv rounded timestamps and all that).

**Comment by haasn** [comment]
Does this help?

```
video-sync=display-resample
interpolation=yes
tscale=oversample
override-display-fps=48
```

**Comment by wm4** [comment]
This will just set 48 Hz as initial nominal display fps. Then mpv will notice that it can output more and adjust the display fps. (No idea how it works with freesync. I even have a fresync display, but the POS is not recognized as such, and it's probably completely different from the Windows behavior anyway.)

**Comment by haasn** [comment]
Oh, right, it doesn't change the pattern unless you combine it with `--untimed` but then the timing is fucked anyway.

**Comment by Artins90** [comment]
> Also I guess you can try `--vf=fps=48/1.001` (if I understand the problem correctly, but I didn't try to). Of course this is for testing only and very much not recommended for normal use. It's meant for files with ~23 fps, and won't work 100% correctly (mkv rounded timestamps and all that).

It works, I have never seen video play so smooth, it's quite impressive.
OpenGL wouldn't trigger G-sync no matter what, after switching to DX11 and setting
`video-sync=audio
vf=fps=48/1.001`
now g.sync works when playing the video in fullscreen, windowed mode disables it despite having set  gsync to both windowed and fullscreen in the Nvidia control panel, that's not a problem though.

It would be nice if vf=fps= could be set to 2x the video fps automatically only when the result of such modification falls within the variable refresh range of the monitor (in my case 35-60Hz), maybe falling back to "display-resample" automatically when it falls outside the range.
<img width="1777" alt="Capture" src="https://user-images.githubusercontent.com/28777957/71549168-2d110480-29b9-11ea-9baf-38c1a22c6f27.PNG">

**Comment by xnoreq** [comment]
Guys, mpv does not support any form of adaptive sync.
The monitor refresh rate is whatever you configure in Windows. It might be 60, 75, 120, 144 ... Hz and whatever the video fps, it will be displayed at that fixed refresh rate, even in fullscreen.

**Comment by zc62** [comment]
I have similar observation to what philipl had.

My display can do 57-144Hz, and if I enable interpolation and display-resample, the display reports a constant 144Hz.

If I use default `interpolation=off` and `video-sync=audio`, a 24fps video would trigger 72Hz for my freesync display (though the actual refresh rate reported by the display OSD fluctuates, don't know why.) The OSD of mpv still reports 144Hz (why?).

**Comment by ValZapod** [comment]
> Guys, mpv does not support any form of adaptive sync.

G-sync is now working in **windowed** OpenGL and Vulkan since Nvidia 440.97. Where G-sync works now since that driver? In ffplay. In [photoshop](https://photos.app.goo.gl/6uUw4svfkz1FqjJa6). In Audition. In [Blender](https://developer.blender.org/T76511)! And in mpv. 

https://www.nvidia.com/en-us/drivers/results/152654/

```
Gaming Technology
Adds support for windowed G-SYNC for OpenGL and Vulkan-based applications

```

**Comment by xnoreq** [comment]
How does that work? If the desktop refreshes at a constant 144 Hz then that's it for variable refresh non-maximized windows, isn't it?

**Comment by ValZapod** [comment]
> desktop refreshes at a constant 144 Hz

You mean DWM? That is also not true anymore, but microsoft did not implement it 100 % yet (there was a funny bug when windows start menu was fixed on 30 frames using VRR API and it broke everything, haha). So is color managment on desktop, WIP and so is system wide (like in MacOS). Lazy they are)) But yes, only the up window even windowed window has G-sync. Everything else, even if there are many videos under the window becomes broken.

**Comment by xnoreq** [comment]
Tried on Windows 10 and does not work. How could it? The DWM would somehow need to adapt to the variable refresh rate of the active window, which could be rendering at 1 Hz and would therefore break the rest of the desktop, other applications.

Fullscreen works, but that has been working for months if not years (contrary to my Dec 2019 statement)

**Comment by ValZapod** [comment]
> and does not work.

Try mpv.com --gpu-api=vulkan --vulkan-async-transfer=yes --vulkan-async-compute=yes --vo=gpu --hwdec=nvdec --vf=fps=48 (or 72 or if it is 23.976 film try 48/1.001 and 72/1.001 but it will not be perfect as G-sync by default only has 3 digits after decimal point, so...)

Also activate G-sync indicator in Nvidia control panel (AMD does not support VRR in OpenGL and Vulkan AFAIK). And you will get nice G-sync indicator like here:
![image](https://user-images.githubusercontent.com/31514790/93360970-f59afe80-f84c-11ea-916d-f67e478497ec.png)

**Comment by xnoreq** [comment]
Doesn't work for me, then again I'm using an adaptive sync monitor.

So what happens if you have e.g. a 60 fps youtube video running in the browser in the background and you start mpv with fps=48?

Also, what does your monitor actually receive? My monitor shows the (variable) refresh rate in its OSD.

**Comment by ValZapod** [comment]
> an adaptive sync monitor.

I also use AdaptiveSync and HDMI 2.1 VRR LG C9. LG C9 does show everything in OSD, monitor does not have such HW OSD.

> 60 fps youtube video running in the browser

a) G-sync is turned off by force in Nvidia profile and Directx12 that we are using for videos in chromium (technically it is what is called Directx11on12). It was also forced off in everywhere else. But it can be turned on with special flags, see https://bugs.chromium.org/p/chromium/issues/detail?id=807406.

**Comment by xnoreq** [comment]
Turns out the Nvidia control panel is bugged and messed up my mpv profile some time ago.
I had set monitor technology to "use global" setting which is set to "GSYNC compatibility", but nvidia profile inspector showed that it was set explicitly to "Off". Also another related option was set to off.

After cleanup up the profile it works. 

The implementation is definitely weird. Using the 72 fps video, my monitor shows 72 Hz, then it rises to 144 Hz where it stays shortly and then drops to 72 Hz again and this repeats over and over again.
This is with a YouTube video in the background. Cannot explain the observed behavior, but maybe the driver tries to squeeze in frames from background applications.

**Comment by wm4** [comment]
If it's VRR, isn't it expected that the framerate changes all the time?

**Comment by ValZapod** [comment]
> VRR

It is variable, not variating refresh rate, so no.

**Comment by xnoreq** [comment]
Turns out that makes no difference.

In fullscreen my monitor's OSD shows fluctuations of about +/-15 Hz around the 72 Hz. This is just an artifact of how the monitor calculates/displays the current Hz I think.
But in window mode it fluctuates from roughly 50 to 144 Hz.

Would be interesting to hear from Nvidia and AMD and Microsoft how they have implemented variable refresh in window mode.

**Comment by wm4** [comment]
> It is variable, not variating refresh rate, so no.

The idea with VRR is that you can show a frame at any time the host wants. There doesn't need to be a constant refresh rate. Switching the refresh rate on demand was possible before.

**Comment by Jules-A** [comment]
I tried Freesync with my RX570 and 75hz monitor in windowed Vulkan and at first it seemed like it improved things changing fps to 72/48 (I couldn't tell any difference) but after blind testing it was basically the same (at least when comparing notoriously bad panning shots in anime). Going to OpenGL has better vysnc but has random stutters if I do anything else on my system. DX11 has a far, far superior vsync and looks like FreeSync is working for sure BUT I can't use it since an anime4k denoising shader is broken under DX11. 
I also can't really test fullscreen vulkan since it's still broken in MPV (https://github.com/mpv-player/mpv/issues/8008)

For now I've gone back to default fps settings since I'm not sure if 48/1.001 or 72/1.001 will cause some issues and I don't always play 23.976 content.

**Comment by lextra2** [comment]
For me, FreeSync is automatically engaged (this includes frame rate doubling via driver with content below FreeSyncs minimum rate) once I go fullscreen (hwdec=auto might be needed).

This is exactly what the OP wanted, yes?

Playback is noticeable smoother for me on my Samsung TV. Also, showing the input source info on the TV shows FreeSync as enabled (It does not while mpv is windowed, further prooving things are working as intended). This is on Windows 10 with AMD driver.

So I don't see why this thread is still open? Looks like this implementation is up to the GPU vendor, which definitely works for AMD here.

**Comment by LinAGKar** [comment]
This thread seems to be about regular frame doubling (which the driver can do), but on a related note it would be nice if mpv could automatically interpolate to the highest integer multiple of the source framerate that falls within the monitors range. So in the above example with 23.976 FPS video on a 40-120 hz monitor, mpv would insert 4 interpolated frames between each frame, bringing it up to 119.88 FPS. if you watched 25 FPS video, mpv would insert 3 frames to bring it up to 100 FPS.

Because even if you can output 23.976 directly and avoid the framerate mismatch, you still get the low framerate shakiness. This would let you take advantage of VRR to natively show any framerate, and still get the smoothing effect of interpolation to avoid the shakiness of low framerates. Currently, there seems to be no way of using both interpolation and VRR.

**Comment by lextra2** [comment]
@LinAGKar
I see what you mean. `interpolation=yes` could be changed to `interpolation=<value>` where value is any value up to the maximum refresh rate of the display (to stay in VRR range). Sounds good to me. And it shouldn't be hard to implement.

**Comment by LinAGKar** [comment]
@lextra2, something like that, except it should automatically interpolate to the highest integer multiple below the limit (which would vary depending on the framerate of the video), whereas the current interpolation (designed for fixed refresh rate displays) interpolates strictly to the set framerate, which may not be an integer multiple.

**Comment by PalmtopTiger** [comment]
It is necessary to indicate the minimum and maximum.
For example, my monitor sync range is 48-70 Hz.
23.976 * 2 = 47.952
23.976 * 3 = 71.928
So, 2.5 is the only option for 23.976 fps.

**Comment by LinAGKar** [comment]
Of course, it would be even better if mpv supported some kind of motion interpolation, rather than mere frame blending.

**Comment by jsravn** [comment]
> I also use AdaptiveSync and HDMI 2.1 VRR LG C9. LG C9 does show everything in OSD, monitor does not have such HW OSD.

@ValZapod If you're using a 120hz OLED, all you need to do is `video-sync=display-resample` and make sure you have any frame limiters off. That will give you 5:5 pulldown which is perfect for OLED motion clarity and should eliminate all stutter.

**Comment by ValZapod** [comment]
> you're using a 120hz OLED,

I also use AdaptiveSync (this Display Port) monitor. So it is not perfect for all.

**Comment by jsravn** [comment]
> > you're using a 120hz OLED,
> 
> I also use AdaptiveSync (thus Display Port) monitor. So it is not perfect for all.

I just realized it won't be perfect either, you want it at 120/1.001 for 23.976 source. So it seems there isn't a great way other than to use the fps filter. It does feel like mpv should take care of this somehow.

**Comment by ValZapod** [comment]
> you want it at 120/1.001 for 23.976 source

For 24./1.001. And 120.000 for 24.000. Yeah. Or it will drop every 41 seconds (if you output 24/1 on 24/1.001 display, Apple TV), like Apple TV did untill an update from a week ago introduced automatic alternate clock switching for EDID entries (that support both integer and non-integer rate). https://www.flatpanelshd.com/news.php?subaction=showfull&id=1613548043 It was an insane issue, that is still present on Xbox Series X and Roku.

> It does feel like mpv should take care of this somehow.

There is a special script for frame switching. But otherwise there is no simple way to do it...

**Comment by ValZapod** [comment]
> you want it at 120/1.001 for 23.976 source

LG C9 does support both. 120 and 120/1.001, BTW. Just like every other. It is mandated in EDID that if one is supported, the other should be supported too. It is like that in practice, but there is also a way to construct a new timing, in that case it will only support one or the other, but you can create a new entry and usually it works, but you cannot be sure about it unless you have a super 240 fps camera.

**Comment by magicgoose** [comment]
Even 240fps camera likely won't really be enough to accurately judge 120hz display, because you can't ensure time alignment and so there will be some motion blur.
If you prepare a synthetic video with a moving rectangle, for example, and just watch it, then a naked eye should be enough to see if it's working properly, or not. Our eyes are pretty good at judging motion smoothness. It's the accurate measurement of delay that's really hard to do by eye.

**Comment by ValZapod** [comment]
Apple implemented VRR systemwide, BTW. In Safari and everywhere else, nice.

**Comment by ValZapod** [comment]
Meanwhile Apple implemented VRR system wide with their ProMotion on latests Macbooks and Macs and Google hires people to support VRR and HDR system wide for android.

**Comment by lextra2** [comment]
Apple adding VRR in such a competent way really surprised me. It is the best implementation from any plattform.

**Comment by andrius4669** [comment]
While `--vf=fps=fps=source_fps*2` generally does job pretty well, it ends up doing it wrong when fps is variable in video itself.
I think it only picks rate container tells it about.

**Comment by ValZapod** [comment]
For VFR, true VFR, you really need 1-120 VRR, like in Galaxy s22 Ultra. Really.

**Comment by andrius4669** [comment]
I don't really care if my monitor is "true VFR", but with simple frame doubling this would work as even problematic variable framerate files I was testing with only jumped around 24/1.001 ~ 30/1.001 hz.
My monitor can go down to 40hz, but for ones going down to only 48hz, something like before mentioned modified `fpsadjust.lua` could do the job just fine (or manual `--speed=1.001`), basically bringing it to 24 fps where frame doubling could bump it up to 48.
Issue is about getting the most out of current hardware we have, and it seems that outside of apple ecosystem and some smartphones, monitors with limited VRR range are fairly common.
I'm not sure how much effort is there to implement this, but something like frame_multiplier property I could set from `.lua` script if `fps < 40` would quite likely cover all the files I'm ever going to play, maybe except some with completely bogus fps values set in container, and even there the worse that could happen is some jitter. And I've not seen files with 9000 fps specified in quite a while.

**Comment by andrius4669** [comment]
I've tried implementing it, and it currently actually works with caveat that sometimes seeking hangs.
I'll probably publish the code tomorrow or something like that, possibly after debugging it a bit.

**Comment by andrius4669** [comment]
https://github.com/andrius4669/mpv/tree/frame-repeat it appears to kinda work now but isn't pretty codebase wise, and I probably broke something else with these changes, and it would kinda feel more natural to reuse `num_vsyncs` for this but existing logic of that is kinda tied to `display_synced` stuff so idk.
can kinda see why no one wants touching this.

**Comment by Jules-A** [comment]
> Thing is I'm not a huge fan of interpolation, so I'm going to look into somehow doubling frames without interpolating them, specifically for 24fps anime -- just double (or triple) the frames, without desyncing the audio or looking "sped up"

Check https://github.com/mpv-player/mpv/issues/12005 for more info. If you just want to increase without interpolation you can do ```vf=fps=fps="2*source_fps"``` if you want a perfect multiple otherwise you can just do ```video-sync=display-resample```

**Comment by llyyr** [comment]
You shouldn't use `display-resample` if you want VRR to work. Using display-resample will just pin the VRR to the highest possible refresh rate.

If you want mpv to do the frame multiplication instead of LFC, then use the `fps` filter

**Comment by Jules-A** [comment]
> You shouldn't use `display-resample` if you want VRR to work. Using display-resample will just pin the VRR to the highest possible refresh rate.

It still works but it's not great, which is why I wanted an option that would do clean multiples. Previously it required enabling Enhanced Sync in the drivers to get it working properly in fullscreen-windowed but Enhanced Sync caused a bug that would make the refresh rate 250 or so when resizing to fullscreen. It's working without Enhanced Sync now BUT will completely break (delay/drop frames) if you alt-tab/resize or doing anything else that puts a window in top of mpv for a 1 - 5secs.

That's why I really wanted an option to set a clean multiple version of display-resample but without having to do vf hacks so I could also do interpolation.

**Comment by toprak** [comment]
Guys VRR, Free sync or G-sync I'm a bit unfamiliar with these and similar technologies and since I just bought my system I'm trying to set up mpv in my own way. My monitor is Lenovo legion r25i-30. Lenovo's website has information like *Vertical frequency 48 Hz - 165 Hz* but the min. value I can see in Windows 11 is 50 Hz is this normal or if it is normal I want to use this. `--vf=fps=fps=source_fps*2`

**Comment by Spacellary** [comment]
@toprak The Windows refresh rate is unrelated to the actual VRR window, you should go with the manufacturer's information for that one. It's normal for it to show like that, it's just listing some standard resolutions.

**Comment by AndrewKeYanzhe** [comment]
Does `--vf=fps=fps=48` work on macOS for anyone? I tried mpv 3874145 (2024 build) on macOS 15.6 and vrr doesnt seem to work

And does anyone know any macOS video player that implements VRR?

**Comment by AnataBakka** [comment]
it's odd that some people believe it's ok for mpv to not know the client's minimum and maximum refresh rate. i would rather mpv allow that as input, even if it does nothing with the variables, just to give me assurance that it might use them somewhere when needed in the future. if not i hope it won't be hard for me to look as an example into what andrius did here https://github.com/andrius4669/mpv/tree/frame-repeat and try to implement it... 

for future reference, this simple pseudocode is what i believe those two variables should be used for to work for all cases https://pastebin.com/k8MjLKF3. There are only a couple of lines of pseudocode, the rest are comments. Some people might expect the display to do all of that, which i don't see how, as i believe you need next frame data to be able to process stuff, which it doesn't seem displays usually have yet, unlike the gpu. And so it would make sense if the gpu *always* managed each frame drop and repetition, covering all cases and systems.
The point of the pseudo code is to ensure the frames are always inside the refresh range, and hope that the cases where it goes outside are rare.

no, vf=fps does not reliably work for variable framerate content.

does the pseudocode make sense?

**Comment by XSpark0** [comment]
I tried frame doubling and also tried limiting display fps. While it doubles the frame rate, it doesn't do anything to fix panning shot judders. Even tried matching frame rate to monitor's hz. Also tried display resample and interpolation. Display resample just causes lot of mistimed, delayed frames and dropped frames. Interpolation=yes refuses to activate. Likely because i have Gsync Monitor.

Lossless Scaling fixes panning shot judders but in turn introduces unwanted soap-opera effect and lot of motion artifacts.

I wish mpv had a separate built-in motion interpolation feature that doesn't require messing around with VapourSynth and stuff nor requires display resample, a motion interpolation which simply focuses on detecting panning shots in any video and interpolating only the panning shots, thus avoiding unwanted soap-opera effect as well as 99% of motion artifacts, and can be easily activated with interpolatedpanning=yes or antijudder=yes.

Another way i guess would be to somehow make mpv natively compatible with G-Sync and have it work with G-Sync so it multiplies 23.976 fps of videos in a way that eliminates judder on panning shots without requiring to resorting to motion interpolation.

**Comment by Atemu** [comment]
> Even tried matching frame rate to monitor's hz.

It's not enough to match the rate, you must match the precise timing; you need V-Sync.

> Also tried display resample and interpolation.

Interpolation is something entirely different and I consider it off-topic.
