### ISSUE TITLE
Greenish 1px line on the right with -vo xv

### ISSUE THREAD

**Issue by z0rti** [mpv-player/mpv#6208]
### mpv version and platform
GPU is a i915
Kernel: 4.18.x

$ Xorg -version
X.Org X Server 1.19.2

$ lsb_release -a
Description:	Debian GNU/Linux 9.5 (stretch)

$ mpv --version
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.12-1~deb9u1

##########################################################
same with:
mpv cd89362 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Mon Jun 18 18:25:03 UTC 2018
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.20.102
   libavformat     58.17.100
   libswscale      5.2.100
   libavfilter     7.25.100
   libswresample   3.2.100
ffmpeg version: git-2018-06-18-e85c608

### Reproduction steps
Play a video with -vo xv

### Expected behavior
Plays video without artefacts

### Actual behavior
Plays video with random colored (green, multiple colors) vertical 1px line on the right 

### Sample files
screenshot: https://0x0.st/sgDc.png
video: https://0x0.st/sgDA.mp4

### Workaround
I know, "use -vo gpu/opengl", but then i got tearing, and when i enable TearFree in Xorg it uses >2gb RAM and stutters while allocating #sad

**Comment by CounterPillow** [comment]
>mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects

It's 2018. There is no support for out-of-date versions; ask Debian for help with old versions they ship.

>GPU is a i915

Old garbage, note how the mpv README says you'll need a proper GPU.

**Comment by Jj0YzL5nvJ** [comment]
**mpv version and platform**
$ mpv --version
```
mpv 0.29.0-30-g6eb59fea2f Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Sep 11 00:21:21 MDT 2018
ffmpeg library versions:
   libavutil       56.19.101
   libavcodec      58.29.100
   libavformat     58.18.100
   libswscale      5.2.100
   libavfilter     7.29.100
   libswresample   3.2.100
ffmpeg version: N-91869-g5632044939
```
Xubuntu 16.04.5 LTS / AMD64
ppa:oibaf/graphics-drivers
```
GL_RENDERER   = Radeon RX 560 Series (POLARIS11, DRM 3.23.0, 4.15.0-36-generic, LLVM 7.0.0)
GL_VERSION    = 4.5 (Compatibility Profile) Mesa 18.3.0-devel
```

 I can't reproduce your issue on my side. [I had experience](https://github.com/mupen64plus/mupen64plus-core/issues/349#issuecomment-318186426) with i915/i915g iGPU, and is problematic.
 I don't know the current status of the drivers. You need to play with xorg settings to find what works for you. 
 In my case, the SNA acceleration was garbage for me, so I used UXA instead, I used GLES2 instead of OpenGL, if I had the option, etc, etc.
 It's not worth the time spent on that hardware, it always breaks or is crippled somewhere, is a incessant headaches machine.

**Comment by gianniqq** [comment]
I have the same hardware, and I suggest you to use `--opengl-es=yes` instead of going with `--vo=xv`.
While by using vo=xv I can see the green line, it disappears with the other option I mentioned.
Let's keep using this "old garbage"!

**Comment by wm4** [comment]
Yes, that's probably correct.
