### ISSUE TITLE
0.29.1 fails to build on Mac OS X 10.9 Mavericks

### ISSUE THREAD

**Issue by yan12125** [mpv-player/mpv#6212]
### mpv version and platform

mpv 0.29.1
Mac OS X 10.9 Mavericks
Xcode 6.2

[README.md](https://github.com/mpv-player/mpv#system-requirements) says "OSX 10.8 or later", so I assume 10.9 is still supported?

### Reproduction steps
./waf configure --prefix=/opt/local --enable-manpage-build --enable-libass --enable-coreaudio --enable-cocoa --enable-cplugins --enable-zlib --disable-html-build --disable-cuda-hwaccel --disable-opensles --disable-egl-drm --disable-egl-angle-lib --disable-egl-angle-win32 --disable-audiounit --disable-ios-gl --disable-mali-fbdev --disable-direct3d --disable-android --disable-rpi --disable-dvbin --disable-pdf-build --disable-test --disable-clang-database --disable-debug-build --disable-libsmbclient --enable-dvdread --enable-dvdnav --enable-cdda --disable-vapoursynth --disable-vapoursynth-lazy --enable-libarchive --enable-rubberband --disable-pulse --disable-jack --disable-openal --enable-gl-cocoa --disable-x11 --disable-xv --disable-gl-x11 --disable-egl-x11 --disable-caca --disable-jpeg --disable-tv --enable-apple-remote --enable-gl --disable-zsh-comp --disable-javascript --disable-uchardet --enable-videotoolbox-gl --enable-lua --lua=52fbsd --enable-libass-osd 

### Expected behavior
mpv builds fine

### Actual behavior
```
ValueError: invalid literal for int() with base 10: '(swift-600'
```

### Log file
https://trac.macports.org/attachment/ticket/57385/mpv_main.log

### Sample files
N/A - build issue

**Comment by Akemi** [comment]
yeah 10.9 is still kinda supported, but not the new cocoa-cb swift backend. neither for building and running. could you please give me the output of `swift --version` from your terminal. then i can fix the auto detection.

**Comment by Akemi** [comment]
otherwise you can use `--disable-swift` to manually disable it for now.

**Comment by yan12125** [comment]
Thanks for the possible solution. As I don't have a Mavericks machine, I forwarded both messages to the original report https://trac.macports.org/ticket/57385.

**Comment by Akemi** [comment]
it's probably fixed with #6214. though i really can't test it because of the lack of a 10.9 system.

if the question pops up. it's fixed as in, it will automatically disable any swift code when applicable but will produce a working binary with the old deprecated cocoa backend. the new cocoa-cb swift backend is only supposed to build with at least swift version 3 (at least macOS 10.11 i believe) and will only run from 10.10 and newer. though recommended is to at least build it on 10.12 with SDK 10.13 and swift 4, because of a bug/bugs in swift 3/SDK10.12 (see issue #5585).

**Comment by tehcog** [comment]
FYI:  Found swift here, not in $PATH, version query different also:
{ /Applications/Utilities/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin }-> swift -version
Swift version 1.1 (swift-600.0.57.4)
Target: x86_64-apple-darwin13.4.0

**Comment by Akemi** [comment]
thx. yeah the PR will fix the issue. seems like apple didn't put swift into `/usr/bin/` on 10.9 yet, so it's quite an oddball. from 10.10 it's there and has a bit different version string. if you check the mpv configure log it says in the line `Checking for swift (Swift compiler) ` which swift compiler it picks up, it's the one in your xcode folder.

anyway seems like disabling swift at configure doesn't fix the issue since i don't check for it in that step but only later. so you have to apply the mentioned PR yourself for now if you want to build mpv.

**Comment by yan12125** [comment]
> with the old deprecated cocoa backend. the new cocoa-cb swift backend is only supposed to build with at least swift version 3 (at least macOS 10.11 i believe)

Will the cocoa backend be dropped in near future and mpv then stops working on 10.9?

**Comment by Akemi** [comment]
i won't remove it as long as it is not in the way. though i won't fix any major things if it breaks. to answer your question, i am not planning to remove it any time soon.
