### ISSUE TITLE
downscaling not producing correct results

### ISSUE THREAD

**Issue by madshi** [mpv-player/mpv#6213]
### mpv version and platform

64bit shinchiro build 20181014, Windows 10 x64.

### Reproduction steps

Downscale the attached 4K image with mpv and with ImageMagick, using Mitchell for both. Config:

profile=gpu-hq
correct-downscaling=yes or no, doesn't matter

### Expected behavior

Images should look identical. ImageMagick and madVR do agree on how the image should look like, so it's very likely mpv which is at fault for looking different.

### Actual behavior

Images don't look identical.

### Log file

No log provided, should be easy enough to reproduce for everyone.

### Sample files

![original](https://user-images.githubusercontent.com/977539/46968389-65c60600-d0b3-11e8-8659-47a726c07d6a.png)
![imagemagickdownscalemitchell](https://user-images.githubusercontent.com/977539/46968424-74acb880-d0b3-11e8-9f84-e66a3b1d9cfe.png)
![mpvdownscalemitchell](https://user-images.githubusercontent.com/977539/46968425-74acb880-d0b3-11e8-8144-a7cf8fca21dd.png)

**Comment by madshi** [comment]
Strange thing happened. When double checking the images in my browser, the ImageMagick images looks darker than it should. Maybe some weird metadata in the PNG header created by ImageMagick? Doesn't happen if I open the PNGs in MS Paint. I've saved the ImageMagick as BMP -> PNG now to get rid of the metadata, and am re-attaching, hopefully it looks alright now?

In any case, you should be easily able to reproduce the problem yourself, by downscaling the 4K image to 1080p with mpv + ImageMagick on your PCs.

![imagemagickdownscalemitchell](https://user-images.githubusercontent.com/977539/46968810-7f1b8200-d0b4-11e8-807d-49b9d39a4dc7.png)

**Comment by haasn** [comment]
Hi @madshi,

The differences you are observing are caused by linear light downscaling. I can reproduce both of your images on my end with both IM and mpv.

Observe:

## ImageMagick
### Non-linear downscaling
```convert 4k.png -filter mitchell -resize 50% im-1080p.png```
![im-1080p.png](https://0x0.st/sEmo.png)

### Linear downscaling
```convert 4k.png -colorspace RGB -filter mitchell -resize 50% -colorspace sRGB im-1080p-linear.png```
![im-1080p-linear.png](https://0x0.st/sEmH.png)

## mpv
### Linear downscaling
```mpv 4k.png --pause --no-config --profile=gpu-hq --geometry=1920x1080```
![mpv-1080p.png](https://0x0.st/sEmX.png)

### Non-linear downscaling
```mpv 4k.png --pause --no-config --profile=gpu-hq --geometry=1920x1080 --sigmoid-upscaling=no --linear-downscaling=no```
![mpv-1080p-nonlinear](https://0x0.st/sEmK.png)

Whether or not to use `--correct-downscaling=no` on top of this configuration orthogonal, it just makes the image aliased (no filter widening / anti-alias):
![mpv-1080p-nonlinear-nocorrect](https://0x0.st/sEmZ.png)

Hope that should clear things up

> Strange thing happened. When double checking the images in my browser, the ImageMagick images looks darker than it should. Maybe some weird metadata in the PNG header created by ImageMagick? Doesn't happen if I open the PNGs in MS Paint. I've saved the ImageMagick as BMP -> PNG now to get rid of the metadata, and am re-attaching, hopefully it looks alright now?

ImageMagick exported your image with a `gAMA` tag indicating a gamma value of 2.2, whereas your "corrected" image is stored with an sRGB chunk instead. If the software you are using to view these PNG files respects those tags accurately, it should explain the difference.

**Comment by haasn** [comment]
`linear-scaling` does affect scaling in general, both up- and down. But the `sigmoid-upscaling` option, which implies `linear-scaling`, will also perform sigmoidization on upscaling. So the net effect of the default `gpu-hq` settings is to use linear+sigmoid upscaling and linear downscaling.

You can see that the manual entry for `sigmoid-upscaling` mentions this behavior. But you're right that this is confusing. It's probably as good a time as any to change that. Not sure what the best design would be:

1. Deprecate `--linear-scaling`, introduce `--linear-downscaling`. Make `--sigmoid-upscaling` no longer imply this option. **Caveat**: No way to get linear upscaling (without sigmoidization)

2. Deprecate `--linear-scaling`, add two new options `--linear-upscaling` and `--linear-downscaling`, make `--sigmoid-upscaling` imply `--linear-upscaling`.

3. Rather than flags, have some new option type like `--upscaling-light=gamma|linear|sigmoid`? **Caveat**: Not as easily backwards compatible.

4. Some other solution?

**Comment by madshi** [comment]
All 3 of your suggested designs seem fine to me. I don't think the 1. caveat matters too much because I don't think linear upscaling (without sigmoid) is really good, so no big loss there.

Generally, I understand that technically, sigmoid upscaling internally requires linear light. But to the average user, that's not necessarily intuitive. So treating sigmoid as a completely separate "light" from gamma and linear would probably make things easier to understand for the average user.

(Unrelated side note: Comparing 1080p and UHD Blu-Rays of Passengers, it seems that the studio used gamma light for downscaling the UHD master to 1080p. I'm not completely sure if they used Catrom or Mitchell. Looks like something in between. Considering that the lossy encoding to 1080p might have softened things a bit, I'd rather guess it was Catrom.)
