### ISSUE TITLE
how to turn up or turn down volume

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [mpv-player/mpv#6224]
how to turn up or turn down volume with mouse wheel in mpv like vlc i can't find axis_up and axis_down
and i tried to configure it in the input.conf
i replaced seek with volume but its still the the same

**Comment by Akemi** [comment]
try WHEEL_UP/_DOWN. otherwise, you ignored the issue template.

**Comment by Hrxn** [comment]
> mpv --input-test --force-window --idle

This is running mpv via CLI...
Windows, you say? You can either use CMD or PowerShell out of the box, or some 3rd-party solution.

**Comment by Jj0YzL5nvJ** [comment]
Try WHEEL_UP/_DOWN **on the speaker icon**.

**Comment by Photosounder** [comment]
Holy hell this is absolutely horrendous from a usability perspective, this much can hardly be understated. A new user expects a visual and clickable way to set the volume. Failing that they'll try arrows up/down which skips around in time (arrow up closed the whole application for me on a short video, also a horrendous behaviour), and scrolling up or down does the same thing. Expecting users to figure out that the scroll wheel does it but only while hovering a tiny icon is baffling.

The devs of this project clearly suffer from being too used to the usability quirks of their project to realise what a massive problem this is, for a new user this is extremely off-putting and frustrating. I literally had to google how to change the volume of your program only to find other people wondering the same. This is a huge design failure. No one has that problem with VLC or MPC because it's hard to miss how to set the volume.

**Comment by duracellcell** [comment]
@Photosounder I believe this feature is called The Great Filter

**Comment by Photosounder** [comment]
As in it filters users based on whether or not they're willing to put up with horrendous design decisions? Only people who don't make commercial software could possibly feel that this could be a good thing and not a very basic design failure.

**Comment by CounterPillow** [comment]
tfw the filter is working

**Comment by wiiaboo** [comment]
There is an icon in the OSC for muting and changing the volume since v0.25.0. It doesn't take the whole vertical space of the OSC or have the rainbow colors when it goes over 100% like in VLC, but that can be changed.

> Anyway, not like I'm the one in charge of maintaining it. Just that if it were up to me, the OSC wouldn't even exist in its current form. It's too over-engineered to be a simple seek bar and too under-engineered to be an actual GUI.

There's no one maintaining it. Just people adding their own tweaks and hacks over the years.

**Comment by ryanzb** [comment]
lmao looks like the filter is working. wait til he asks about how to setup the conf file

**Comment by thenoobtester** [comment]
> lmao looks like the filter is working. wait til he asks about how to setup the conf file
> to answer the original question use 9 / 0 for volume up or down respectively.

Considering the quality of comments like yours, it's indeed obvious the filter is working in selecting the cream of the crop for this project. Kudos for the invaluable contribution.

**Comment by ryanzb** [comment]
> > lmao looks like the filter is working. wait til he asks about how to setup the conf file
> > to answer the original question use 9 / 0 for volume up or down respectively.
> 
> Considering the quality of comments like yours, it's indeed obvious the filter is working in selecting the cream of the crop for this project. Kudos for the invaluable contribution.

1. You replied to a comment made in 2019. What a winner you are.
2. "use 9 / 0 for volume up or down respectively" is indeed useful, I appreciate your compliment
3. if you bothered to read the entire thread (grep 'filter'), you would see there was a theme to the conversation
4. I read and re-read your entire comment. there was nothing useful to the conversation. just a bunch of snark. **Kudos!**
5. You replied to a comment made in 2019

**Comment by ryanzb** [comment]
> > lmao looks like the filter is working. wait til he asks about how to setup the conf file
> > to answer the original question use 9 / 0 for volume up or down respectively.
> 
> Considering the quality of comments like yours, it's indeed obvious the filter is working in selecting the cream of the crop for this project. Kudos for the invaluable contribution.

don't bother replying to my comment. i'm blocking you now. buh bye! worthless.
