### ISSUE TITLE
Support .conf file in playback directory

### ISSUE THREAD

**Issue by soulofmischief** [mpv-player/mpv#6227]
Hi, I would like to be able to drop an `mpv.conf` or `input.conf` in individual folders to give mpv special instructions for playing videos in that folder.

Since automatic deinterlacing seems to be do-not-fix for now and the lua script doesn't seem to do a good job of detecting interlaced videos, I want to find a simple way to automate the process of interlacing and deinterlacing so that I'm not triggering it each time for a new video.

If I'm playing a video in the `foo` directory, I would like to place configurations in that directory.

What would be even cooler is a way to flag in the master configuration whether to use local configuration files at all, and in both the master and local configuration files, being able to flag the option to recursively search up the directory tree for other `mpv.conf` or `input.conf` files. 

That way if a show is organized in folders by season, for example, placing a configuration file in the show's root directory would be all it would take.

How hard would it be to implement something like this?

**Comment by haasn** [comment]
Some pointers:

1. `--config-dir=.` (equivalently: `MPV_HOME=.`) can be used to redirect where mpv considers its config file location. But if you do this, then mpv will ignore `~/.config/mpv`. (You could still have global configuration in `/etc/mpv`, however)

2. If this is not sufficient as a work-around, and you wanted to add this feature, it would be very straightforward to extend `path_resolvers` / `config_dirs` (in `options/path.c`) to add support for searching in `.` with highest priority.

Some notes:
1. This must absolutely **ABSOLUTELY** be disabled by default. Huge security risk. There's a reason people don't add `.` to `PATH`, and this is basically the same thing. `mpv.conf` files can perform arbitrary computation. If we add an option, put a heavy disclaimer on it.
2. Do we want to also load e.g. lua scripts in a subfolder `scripts` in the current working directory?
3. Searching for mpv.conf recursively seems more difficult and probably also a bad idea.

**Comment by soulofmischief** [comment]
Yeah, I know I can redirect the config dir but that's pointless because you can still only maintain one config path. So it's not useful for chaining configs nor is it any different from just maintaining a configuration file in `MPV_HOME`.

If it is straightforward, I'll take a crack at it. Thanks for the tip on where to start. 

Definitely will disable it by default. It will need to be enabled in the main configuration file in `MPV_HOME`. Also will separate the option for allowing `mpv.conf` and `input.conf` files respectively, which also probably means the name for `input.conf` will probably need to be exposed as an option in order to avoid conflicts.

As for loading lua scripts, I considered it but since you raise the issue of running arbitrary computations, file reads, etc from mpv.conf files, I'm wondering if this it would be better to create a directory in `MPV_HOME` for scripts that aren't loaded by default, which can be enabled from local configuration files on an ad-hoc basis. 

I'm not familiar with this project so how difficult should it be to only allow certain options to pass through in local configuration files? We could go even further and add support for a custom whitelist in the main config that only lets the listed options pass through.

I can live with having to place `mpv.conf` files in every individual folder, but is there any way to have those files reference a parent file in a relative directory higher up? Does this functionality already exist? That way I could drop dummy `mpv.conf` files in each folder and would only have to tweak the configuration in the parent folder.

**Comment by Argon-** [comment]
So you essentially want to extend the existing local mpv.conf configuration?

**Comment by soulofmischief** [comment]
When I say local, I'm referring to a configuration present in the current working directory.

**Comment by qmega** [comment]
There's already `use-filedir-conf` which will load `mpv.conf` in the same directory as the file you're playing. (It's disabled by default for exactly the reason haasn mentioned.)

It's not recursive, but you can combine it with `include` to load the parent directory's config file. That would basically be the "dummy" setup you described. Using `../mpv.conf` will only work if you're playing *from* the directory the file is in, but using the full path will always work.

If you're fine with all that but don't want to hardcode the parent directory paths, the path of least resistance might be to extend the logic for things like `~~desktop` to expand `~~filedir` to the directory of the currently playing file. Then you could use `include=~~filedir/../mpv.conf` in all your dummy files. That's probably a relatively easy change and could be useful for other things. Though I'm not sure it's actually checked often enough to work correctly in all cases, so it's possible it wouldn't work at all.

**Comment by Argon-** [comment]
> When I say local, I'm referring to a configuration present in the current working directory.

Yes and a local mpv.conf file on the same level as a movie (working dir is unrelated) is already supported (see post above). But it sounds like you want a whole `.mpv` config dir, with input.conf and potential scripts as well?

**Comment by haasn** [comment]
If we don't want to load lua scripts or input.conf from the same dir, then adding it to `config_dirs` would probably not be the easiest approach, since that would treat it as just a regular old mpv dir.

If you *only* want to support local mpv.conf, it might be simpler to add an "include"-style command to the config file. So you could write `include ./mpv.conf` as the last line in your mpv.conf.

**Comment by soulofmischief** [comment]
@qmega thank you for the tip about using include with `use-filedir-conf`. I didn't know about either of those features. It's definitely the best way to get this working for me *right now*, but I still wouldn't mind working to reduce the boilerplate every file would need. 

Otherwise I would write a script that automatically adds the mpv file with the appropriate include link, and update it any time either directories change. If I'm going through all that trouble, I might as well just look into baking a solution into mpv. At this point is sounds like just adding a special include directive behind a flag might be a viable solution?

@haasn I was trying to avoid symbolic links generally, but specifically when dealing with series and sub-folders, the symbolic link is probably a great solution. Thanks for that tip.

@qmega What do you mean about not having the required context? What kind of problems might I run into using `use-filedir-conf` and `include`?

**Comment by qmega** [comment]
> @qmega What do you mean about not having the required context? What kind of problems might I run into using `use-filedir-conf` and `include`?

There shouldn't be any problems using them as long as you use hardcoded paths for include.

I was talking the idea I had about adding `~~filedir` expansion. That would have to be added [here](https://github.com/mpv-player/mpv/blob/da1073c247523d07d0485348447fcc02000afee8/osdep/path-unix.c#L54) (and equivalent for other platforms) and no context regarding the file being played is available there -- it was made with static paths in mind and is probably called from places where there is not file being played. Getting that context in there would probably make a mess of the code.

It would probably be easier to make `use-filedir-conf` recursive, which I think is basically what you really want anyway. You'd mainly have to worry about resolving the path you're actually in, and there could be platform weirdness involved there. Otherwise it would be a simple loop, I think, and you have everything you need there -- I actually looked at the code before talking this time. I don't know if such a patch would actually be accepted, but `player/configfiles.c` (search for filedir) would be the place to start if you wanted to try that. And it should probably require a separate option like `filedir-conf-recursive` or `use-filedir-conf=recursive` to avoid risks with people using the existing semantics.

**Comment by Dudemanguy** [comment]
Seems like the usecase was covered by `--use-filedir-conf` and `--include`.

**Comment by gharabaghi** [comment]
That worked for me!
The problem was that i had a series of videos those they volume was below the normal. my goal was to set the volume for those videos higher than others and apply this setting just with opening the video file via tap a double click on it.
So what i did?
Inside the default mpv configuration file (for user level- in the path: ~/.config/mpv/mpv.conf) I put this setting: 
`include=./.mpv-conf`
Then i create named file (.mpv-conf) inside the folder containing those videos and inside this file I put this one command:
`volume=120`
this worked for me! of course you can name the file whatever you want and put that where ever you desire!

## Notice:
I don't know if writing first command inside of default mvp .conf file may cause an error for directories missing the file! the responsibility of using this approach is on you!
