### ISSUE TITLE
how can I set filename as title

### ISSUE THREAD

**Issue by ruinb0w** [mpv-player/mpv#6288]
I got a mkv file name "course.mkv", but the titile showing weird(`EVCapture---LiveView`). Then I try to use `--title="${filename}"` to set filename as title, but it doesn't work
```
$ mpv --title="${filename}" course.mkv
Playing: course.mkv
 (+) Video --vid=1 (*) (h264 1368x768 10.000fps)
 (+) Audio --aid=1 (*) (aac 1ch 48000Hz)
File tags:
 Comment: www.ieway.cn
 Title: EVCapture---LiveView #####  you can see set filename as title is doesn't work
AO: [pulse] 48000Hz mono 1ch float
VO: [gpu] 1368x768 => 1368x769 yuv420p
AV: 00:00:01 / 00:13:44 (0%) A-V:  0.000 Cache: 821s+47MB
```
did I'm wrong of use this option to set title?
> and I have tried use --force-media-title="${filename}" but this still not work

**Comment by paulguy** [comment]
That's just showing the title as read from the file, --force-media-title sets the property that would otherwise be set and --title just directly sets the window titlebar title.  Looks like you can pass `--display-tags=` to mpv to just hide them altogether.

**Comment by wm4** [comment]
This "Title:" line in the output is just the tag, and always will be the tag. There's no way to change it, other than hididing it with --display-tags, or editing the file tags with another tool.

**Comment by asynapse** [comment]
I encountered the same problem, where mpv's title was set to metadata from the file instead of the file's filename itself. The following doesn't work (when executed from bash or sh) because of the double quotes, which bash interprets, and is effectively passing a blank --title value to mpv since the bash or sh $filename variable is blank:
```
$ mpv --title="${filename}" course.mkv
```

Using single quotes causes the literal '${filename}' to be passed to mpv's --title argument, which can then be interpreted by mpv, resulting in the filename being used as the mpv window title text:
```
$ mpv --title='${filename}' course.mkv
```

Since I always want to see the file's name in the mpv window title even when there's other metadata present, I added this to my ~/.config/mpv/config file, to make it apply to every played file without needing to pass '--title' in each execution (I tacked on the trailing ' - mpv' to make it consistent with normal behavior when there isn't extra title metadata present):
```
title='${filename} - mpv'
```

**Comment by asynapse** [comment]
And adding this to my ~/.config/mpv/config file makes a file's filename visible in the On Screen Controller:
```
script-opts='osc-title=${filename}'
```
