### ISSUE TITLE
Files with DTS-HD Master Audio/Dolby TrueHD play as stereo PCM on AV receiver

### ISSUE THREAD

**Issue by alecrobertson13** [mpv-player/mpv#6366]
### mpv version and platform

OS X builds by stolendata - build from 2018-10-05

mpv 0.29.1

macOS 10.14.1

### Reproduction steps

1. Connect Mac to AV receiver via HDMI
2. Open a video in mpv with DTS-HD Master Audio or Dolby TrueHD, ensure audio is set to output via HDMI

### Expected behavior

Audio should be sent to AV receiver as DTS-HD Master Audio/Dolby TrueHD.

### Actual behavior

Audio is sent as 2-channel/stereo PCM.

### Log file

https://0x0.st/sDLQ.txt

### Sample files

Any file with a DTS-HD/Dolby TrueHD soundtrack.

**Comment by alecrobertson13** [comment]
I was advised elsewhere to set

`--audio-channels=7.1,5.1,stereo
--audio-spdif=truehd,dts,dts-hd`

in my mpv config file. This does not resolve the issue.

**Comment by Akemi** [comment]
try with `--no-config`. yes you need to explicitly set `--audio-channels=`, otherwise you will just get stereo. i am not sure if macOS supports DTS-HD master or Dolby TrueHD passthrough, though it should definitely support multi-channel output. so you should  prioritise getting multi-channel output via PCM working first.

make sure your speakers are properly setup in `Audio Midi Setup`.

try `--coreaudio-change-physical-format=yes` and if all fails try `--coreaudio-spdif-hack=yes`. the latter should not be used usually.

i assume it might not like the picked audio format. though i can't really tell because i don't have a multi-channel audio setup to test.

i am only aware of @ChrisK2 testing this properly and he got everything to work what is supposed to work. though i am not sure if he has time to help you.

**Comment by alecrobertson13** [comment]
@Akemi Thanks for your response.

`--coreaudio-change-physical-format=yes`

enables multi-channel PCM output and it appears as though the bitrate is as expected for Dolby TrueHD. In fact, this flag alone is enough to make this work, I don't actually need to set any of the other options.

**Comment by Akemi** [comment]
that's good news. about the other problem passing through DTS-HDMaster/Dolby TrueHD, is probably not supported. at least i don't remember it ever be mentioned. 

so since you are fine with the way it works i will close the issue. if i misunderstood anything let me know and i will reopen the issue.
