### ISSUE TITLE
Hardware decoding on macOS results in chroma artifacts

### ISSUE THREAD

**Issue by inflation** [mpv-player/mpv#6369]
### mpv version and platform
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Nov  6 17:30:25 GMT 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1
```

### Reproduction steps
Open a video with strong red objects and high contrast background. Then you can see chroma artifacts near the edges.
### Expected behavior
![up quicktime down mpv with software decoding](https://user-images.githubusercontent.com/2375962/49717549-77480c00-fc25-11e8-8875-159bd13abcee.png)
Above one is from QuickTime and it also suffers the similar (but not same) issue, while the below one is correct using mpv with software decoding. 

### Actual behavior
![mpv with videotoolbox](https://user-images.githubusercontent.com/2375962/49717533-67c8c300-fc25-11e8-94a0-19c581732662.png)
I have already filed the bug to Apple. But from the results, mpv with hardware decoding does not look like flawed QuickTime either. While waiting for the response from Apple, I just want to make sure mpv or maybe ffmpeg does not make the issue worse.

I also tried to change `cscale` settings but it seemed not working.
### Log file
https://0x0.st/sDVc.log
### Sample files
For easy reproduction, try this file at 3:16:
https://0x0.st/sDVT.mkv

**Comment by ePirat** [comment]
I can observe the same problem in VLC using Videotoolbox (in Software decoder mode as my hardware does not support decoding HEVC):

<img width="152" alt="redbox" src="https://user-images.githubusercontent.com/323210/49731131-a2a91600-fc7a-11e8-9c87-98032549237a.png">

VLC has it's own implementation of the Videotoolbox wrapper and does not use ffmpeg for it, so I would assume the issue is indeed with Videotoolbox. (Or the ffmpeg and VLC wrappers are both flawed in the same way)

**Comment by Akemi** [comment]
this is the first video where mpv's/ffmpeg's hwdec works but VLC's doesn't for me, weird.

anyway, correct me if i am wrong, videotoolbox returns pre-scaled chroma planes. so mpv's chroma scaling can't do much. the `-copy` version doesn't help either. what we see is basically very bad chroma scaling done in hardware(?) that is even worse than nearest neighbour.

it's also quite possible that quicktime uses a private API for hwdec and actually gets none pre-sacled chroma planes. for me it looks like classic nearest neighbour scaling.

mpv with cscale nearest.
![screenshot 2018-12-10 at 20 02 23](https://user-images.githubusercontent.com/680386/49755414-f175a080-fcb8-11e8-9a2b-c891421ba07c.png)

this is at least one of the reasons why we don't recommend hwdec. the quality can just suffer too much (hideous chroma aliasing and ringing). anyway if it's a bug, it's an ffmpeg and it should be reported to them.

**Comment by Akemi** [comment]
that old macbook supports hevc hw decoding? my mid 2010 macbook pro with a core i7 and a gt330m doesn't.

anyway the responsibility lies with ffmpeg here or the videotoolbox api. the only thing that could theoretically be done, is use reverse (down)-scaling (on the chroma planes) to undo the effect. in the case we would actually know what was used for scaling.

**Comment by pxia** [comment]
I don't know if this information is useful to anyone, but I just tested on iPad which uses videotoolbox, and it doesn't have this chroma artifact. (Looks like mpv software decoder)

**Comment by inflation** [comment]
Yeah, and some other users reported it only happened after High Sierra update. So Apple messed it up for sure. 

Also, quoting some discussion from another forum:
>   这个就很诡异了。从log结果来看，硬解HEVC输出的是NV12，也就是YUV420p8：
>   [   1.553][cplayer] VO: [opengl-cb] 1920x1080 videotoolbox[nv12]
> 
>   另外我还很在意这一句：
>   [   1.234][v][opengl-cb] Loaded extension GL_APPLE_rgb_422.
>   根据doc（https://www.khronos.org/registry/OpenGL/extensions/APPLE/APPLE_rgb_422.txt）
>   APPLE_rgb_422实际上是YUV422p8，也就是已经做了部分chroma upscaling的结果。
>   也就是过程中可能还有类似ffmpeg那样额外不必要转换。

He was saying that videotoolbox returned `NV12` format pixel and mpv loaded `GL_APPLE_rgb_422` extension, and suspecting some unnecessary conversion here.

**Comment by Akemi** [comment]
i believe `GL_APPLE_rgb_422` was even used before and i am not quite sure that is related.

**Comment by Akemi** [comment]
just some additional info. i just removed all usage of `GL_APPLE_rgb_422` (and related) within mpv and it doesn't load that extension any more. though the issue stays the same.

so it's just loading that extension but not using it. it's only there for compatibility for older hardware.

**Comment by kkanungo17** [comment]
Mid 2010 macbooks don't have actual hardware decoding, though the videotoolbox api silently falls back to the apple provided hevc software decoder. That said, I really doubt apple would provide a software decoder that does stuff differently from actual hardware decoders.

**Comment by Acerbicus** [comment]
**Movist 2** has no such problem in hardware mode.

**Comment by Akemi** [comment]
> Movist is an easy-to-use and powerful movie player. You can choose QuickTime or FFmpeg as decoder

yeah, if it uses the quicktime decoder(?).

**Comment by Acerbicus** [comment]
> > Movist is an easy-to-use and powerful movie player. You can choose QuickTime or FFmpeg as decoder
> 
> yeah, if it uses the quicktime decoder(?).

No, it uses hardware mode.

![Movist](https://user-images.githubusercontent.com/32012394/58600242-7dda4680-828c-11e9-8889-8da091d84218.jpg)

![Iinna vs Movist](https://user-images.githubusercontent.com/32012394/58600299-bc700100-828c-11e9-8827-2a4d576e4441.jpg)

**Comment by Akemi** [comment]
i can't confirm this. just tried moviest 2.1.5 and i get the same artifacts.

![Screenshot 2019-05-30 at 12 08 17](https://user-images.githubusercontent.com/680386/58625932-c79a4f80-82d3-11e9-83e6-5e9616f6515b.png)

**Comment by Acerbicus** [comment]
> i can't confirm this. just tried moviest 2.1.5 and i get the same artifacts.
> 
> ![Screenshot 2019-05-30 at 12 08 17](https://user-images.githubusercontent.com/680386/58625932-c79a4f80-82d3-11e9-83e6-5e9616f6515b.png)

Send me this sample files.

**Comment by Akemi** [comment]
it's the one from the OP (3:16). reuploaded it https://0x0.st/sDVT.mkv

i had to use "Hardware (Force)" in movist, otherwise it didn't use hardware decoding at all.

**Comment by Acerbicus** [comment]
Movist Pro - Hardware (Force)/macOS 10.14/iMac 27 5K 2017 (MNED2RU/A)

![Movist Pro - Hardware (Force)](https://user-images.githubusercontent.com/32012394/58630898-7e54fa80-82e9-11e9-9f18-665e9984d392.jpg)

**Comment by Akemi** [comment]
now we are none the wiser.

could be that it silently falls back to software decoding. seems like movist doesn't have any kind of indicator what it actually uses, other than the difference in CPU usage that can be observed. could be difference in hardware.

since it doesn't work on my end, there is no point for me to look into it.

**Comment by Acerbicus** [comment]
> could be that it silently falls back to software decoding

**What is "Hardware (Force)" in video decode?**
To use the hardware video decode acceleration, the video file must be made to conform to the relevant format. Otherwise, hardware decode does not work although supported codec. Movist can force hardware decode through special handling to be used even in such cases. However, it is not always possible, and may cause abnormal behavior in some files.

If you have some trouble in "Hardware (Force)" mode, please change to "Software". You can change it while watching video via main menu and control panel. In the main menu, press the Option key on the video track menu item to display the submenu. In the control panel, click the video track icon to display the pop-up menu.

If it's occurred in too much files and you're not comfortable with it, set the video decode setting to "Hardware" in Preferences. It will work only for movie files that are made to conform to the relevant format. Please send the files via "Send Bug Report" to help us improve Movist.

_http://cocoable.com/faqs.html_

**Comment by Akemi** [comment]
i wouldn't blindly believe a faq. what i meant is, videotoolbox itself can fallback internally to software decoding apparently. it's always better to properly check.

**Comment by kyoukai82** [comment]
I can confirm that this issue is produced by opening an mkv file that contains bright red colors resulting in chroma artifacts along the edges of the red. However, this issue only occurs with mkv files that are encoded a certain way are played back with IINA (I don't specifically know but I know different source encodings of the same original files will have different results). For example, try finding "smallcoded" anime online (eg. animechiby (no issue), animekayo (red chroma issue) that contains bright red (Rias Gremory's hair for an example experiences this issue when encoded in a certain way) and you will see its caused by IINA's decoding settings (possibly).

I think this might be an issue with how IINA "upscales" or "high definition-ify" videos (or decodes videos) as IINA's video playback of the same source seems the most "clean and high quality" while other players video playback isn't as clean but no red chroma artifacts are seen (see attachment). This issue is still present in both hardware decoding on and off.

![IINARedChroma](https://user-images.githubusercontent.com/30968227/59392286-6f2a7e00-8dba-11e9-80e1-7eff491a054a.jpg)

**Comment by Akemi** [comment]
> This issue is still present in both hardware decoding on and off.

then this would be a totally different issue and you should open another issue for that with all info provided.

**Comment by wojciechbielecki** [comment]
Hi, may I ask whether this issue has been reported to ffmpeg? I tried looking at the ffmpeg bug tracker but couldn't find anything that matched this issue. 

The following screenshots were captured on the same frame, with IINA 1.0.4 Build 107 (mpv 0.29.1):
- Hardware decoder: Auto: https://images2.imgbox.com/93/0d/5oLGmcKq_o.png
- Hardware decoder: Disabled: https://images2.imgbox.com/33/2b/TFBQ7zIY_o.png

**Comment by Acerbicus** [comment]
> Hi, may I ask whether this issue has been reported to ffmpeg? I tried looking at the ffmpeg bug tracker but couldn't find anything that matched this issue.
> 
> The following screenshots were captured on the same frame, with IINA 1.0.4 Build 107 (mpv 0.29.1). The file is HDR HEVC encoded:
> 
> * Hardware decoder: Auto: https://images2.imgbox.com/93/0d/5oLGmcKq_o.png
> * Hardware decoder: Disabled: https://images2.imgbox.com/33/2b/TFBQ7zIY_o.png

NO

**Comment by Akemi** [comment]
as far as i know no.

**Comment by tmm1** [comment]
Can someone summarize what the ffmpeg bug here is?

**Comment by Akemi** [comment]
can't say anything specific since i have no idea what videotoolbox actually outputs. for me it looks either like vt outputs prescaled chroma planes to the full resolution with like something like nearest neighbour (though it looks even worse), the planes are prescaled but assumed not to be and some kind of mismatch happens, and/or the chroma planes are kinda only 1/4 of the full resolution or 1/2 of the chroma resolution. seems like it also depends on the hardware.

anyway i re-uploaded the mentioned sample (artifacts at ~3:16). https://0x0.st/sDVT.mkv

here the extracted U and V planes of the screenshot:
![s](https://user-images.githubusercontent.com/680386/67987041-bb247500-fc2c-11e9-92a7-c7cda50f33ff.png)
![U](https://user-images.githubusercontent.com/680386/67987042-bb247500-fc2c-11e9-96dc-d75ac73f43ae.png)
![V](https://user-images.githubusercontent.com/680386/67987043-bb247500-fc2c-11e9-94f9-bbd6a6c5889e.png)

lets use some less obvious one where one can still clearly see the problem on the chroma planes:
![s](https://user-images.githubusercontent.com/680386/67987624-3175a700-fc2e-11e9-97d8-d66f67648f2d.png)
![u](https://user-images.githubusercontent.com/680386/67987625-3175a700-fc2e-11e9-8b10-f8946a606744.png)
![v](https://user-images.githubusercontent.com/680386/67987627-3175a700-fc2e-11e9-96c4-187041e1aa09.png)

also as a small test, i downscaled the actual u plane to half the res and upscaled it to the full res with nearest neighbour and the result looks very similar to what we get with vt:
![uu](https://user-images.githubusercontent.com/680386/67987623-3175a700-fc2e-11e9-9fed-e5b88b637e95.png)

if i can help in any other way let me know @tmm1.

**Comment by Akemi** [comment]
issue on ffmpeg https://trac.ffmpeg.org/ticket/8735#ticket

**Comment by Robot-DaneelOlivaw** [comment]
Has anyone tried hardware decoding on Big Sur? The artifact seems gone.

**Comment by pxia** [comment]
Can someone upload the sample file again?

**Comment by Akemi** [comment]
https://0x0.st/iRl1.mkv
uploaded a cut sample with the red rectangle.

**Comment by pxia** [comment]
Looks identical to software decoder.

<img width="1440" alt="Screen Shot 2020-11-26 at 4 02 04 PM" src="https://user-images.githubusercontent.com/6412438/100397871-ef6d8f00-3000-11eb-8f88-4f96b49d3a56.png">
<img width="1440" alt="Screen Shot 2020-11-26 at 4 02 35 PM" src="https://user-images.githubusercontent.com/6412438/100397875-f4cad980-3000-11eb-8060-e3f1671e570c.png">

**Comment by inflation** [comment]
Can confirm. It's finally fixed after two years. That's Apple for you 🙃
