### ISSUE TITLE
Closed captions won't play

### ISSUE THREAD

**Issue by Doofussy2** [mpv-player/mpv#6376]
**mpv version and platform**
All versions, Windows 10

**Reproduction steps**
Play an MPEG2 video with cc with `sub-create-cc-track=yes` using any hwdec copyback. CC works when not using copyback

**Expected behavior**
See closed caption text

**Actual behavior**
No text displayed

**Log file**
[CC working.txt](https://github.com/mpv-player/mpv/files/3343148/CC.working.txt)

[CC not working.txt](https://github.com/mpv-player/mpv/files/3343150/CC.not.working.txt)

**Comment by Doofussy2** [comment]
Just retesting this. It looks like when deinterlacing in enabled and functioning (i.e. deinterlacing an interlaced video), closed captions don't work. If I disable deinterlacing, cc works.

**Comment by Doofussy2** [comment]
> Just retesting this. It looks like when deinterlacing is enabled, closed captions don't work. If I disable deinterlacing, cc works.

Revisiting this, it looks like I was wrong about the deinterlacing causing it. It appears to be hwdec copyback modes. Testing with d3d11va, they work just fine. But using any copyback, they don't. Is this expected?

**Comment by phkarmur** [comment]
I have same issue but in headless centos 7, And made fake display using this Xorg [https://techoverflow.net/2019/02/23/how-to-run-x-server-using-xserver-xorg-video-dummy-driver-on-ubuntu/](url)
basically have same issue as @Doofussy2 said but since i have different platform so updating logs and commands.

Logs:
[hardware dec command and logs.txt](https://github.com/mpv-player/mpv/files/3569164/hardware.dec.command.and.logs.txt)
[software dec command and logs.txt](https://github.com/mpv-player/mpv/files/3569165/software.dec.command.and.logs.txt)

 
And here is output screenshot of both commands (left is hardware decoder's output and right is software decoder output):
![picture](https://user-images.githubusercontent.com/16241179/64168888-28ed3400-ce6a-11e9-93ba-e81f27dc44e1.png)

**Comment by wm4** [comment]
Wrong hardware decoder.

**Comment by gizmotronic** [comment]
> Wrong hardware decoder.

Please elaborate; OP says any hardware decoder has this problem.

**Comment by Doofussy2** [comment]
Only copyback modes don't work.

**Comment by wm4** [comment]
Maybe my conclusion was too quick. It looked like he was using a dedicated hw decoder, instead of a hw accel (two different ways how ffmpeg handles hw decoding). The former has generally a much lower chance of working CC.

Anyway, it was true that copy mode discarded the CC data, I just fixed that.

**Comment by gizmotronic** [comment]
Thanks for the clarification, and for the fix.

**Comment by Doofussy2** [comment]
Thanks @wm4. I appreciate the work.

**Comment by phkarmur** [comment]
@wm4  CC works only in nvdec-copy not in cuda-copy.
not sure which ffmpeg decoder uses nvdec-copy but --vd-lavc-o=resize isnt working (works in cuda-copy).

--vd-lavc-o=gpu isnt working in any copy decoders
in nvdec-copy, it through error: -gpu option not found and while in cuda-copy, it doesnt through error but it usage first gpu even you pass different gpu index (0'th index).

ps. --vd-lavc-o=resize => avoption -resize, alternative or replacement of scale_npp filter
