### ISSUE TITLE
Start RTSP stream over SSH on RPi

### ISSUE THREAD

**Issue by MrGlasspoole** [mpv-player/mpv#6380]
Hi,

i can't figure out how to start a RTSP stream over SSH on the monitor that is connected to the RPi.
With OMXPlayer all i have to do is:
`omxplayer --no-keys --no-osd --avdict rtsp_transport:tcp rtsp://live1.brownrice.com:1935/westland/westland.stream --live -n -1 --timeout 30`

mpv 0.23.0
Raspbian Stretch Lite, Kernel 4.14

**Comment by CounterPillow** [comment]
>mpv 0.23.0

Update

**Comment by MrGlasspoole** [comment]
I will figure out how to do that.
But still i can't find out the command how to start the stream or a video.

**Comment by CounterPillow** [comment]
`mpv rtsp://live1.brownrice.com:1935/westland/westland.stream`

I'm not quite sure what you even have an issue with.

**Comment by CounterPillow** [comment]
@Jj0YzL5nvJ as far as I'm aware, librtmp is unrelated to rtsp, isn't it?

Also we don't know what he's having issues with since he hasn't described his issue at all. It could be that his VO isn't working, but as I said again, we cannot know because he didn't post a log and even if he did it'd be of a severely out of date version. That's despite the issue template telling you to use the latest version and to post a log.

**Comment by Jj0YzL5nvJ** [comment]
Oops, you are right on `librtmp`, I reading to many things a the time (manga too) ...let's say it's not going to hurt =P
 Building mpv against a ffmpeg without SSL support and/or without `youtube-dl` is relatively common (for newbies). Without a log we can only assume the worst possible scenario, and ffmpeg is root of many issues here, so... that was.

**Comment by Akemi** [comment]
outdated mpv.
