### ISSUE TITLE
mpv, youtube and specific url type

### ISSUE THREAD

**Issue by qazip** [mpv-player/mpv#6390]
### mpv version and platform
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1
```

### Reproduction steps
Try to do:
`mpv https://www.youtube.com/v/7ENFeb-J75k?version=3`

### Expected behavior
I expected mpv to start streaming that video.
### Actual behavior
It doesn't stream, mpv says "Exiting... (End of file)".

I am interested in supporting that kind of url because that is how they come from an rss feed.

**Comment by CounterPillow** [comment]
The issue is that this URL returns a .swf file, which ffmpeg says it can handle as an image as the swf file indeed contains one frame (the thumbnail). You can work around this by setting the option `--script-opts=ytdl_hook-try_ytdl_first=yes`, which will call youtube-dl first before trying to see whether plain ffmpeg supports the URL.

Technically one could add a hack for this specific category of youtube URLs in `ytdl_hook.lua`, but I'm not sure whether that's a good idea in the long term.

**Comment by qazip** [comment]
@CounterPillow , thank you for replying. That work-around works perfectly for me, it seems. Please feel free to close the issue, if you don't think that implementing it "natively" is a welcoming addition.

Thank you again.
