### ISSUE TITLE
always go to last frame when resuming stream

### ISSUE THREAD

**Issue by prankousky** [mpv-player/mpv#6409]
Hi,

I use `mpv 0.29.1` on `macOS Mojave 10.14` to constantly via a security cam feed. Script and commands will follow, but here is the problem first: when I send my macbook to sleep and then resume, the video will play, but it will not jump to the current (=last) frame. 

I tried this by running the regular script, going to sleep mode, resuming, then open the same feed in a new mpv window. The second mpv (the one started after resuming) will play the actual current stream, the one that has been running before going to sleep mode is still several seconds behind.

This is how I run mpv

```
#!/bin/bash
URL='<streamurl>'
COM='mpv --no-config --network-timeout=2 --geometry=100%+0+0 --screen=0 --no-resume-playback --ontop $URL'

while true;
do
$COM;
done
```

When I mouseover the mpv window, there is a minimal gui. At the moment it shows running time (left) 00:36:10 und time left between 00:00:04 and 00:00:03, however, this was after dragging the progress bar to the very right. Before, there were several seconds time left. Is there another parameter I can add to my command in order to have mpv "jump" to the very last frame whenever it gets called by the while loop in my bash script?

Thanks in advance for your help. I am a beginner scripting these things, and I did search in the issues; one result looked similar in the title, but it was from 2014 and the comments eventually stated that the issue was fixed with an update... So it must have been a different kind of problem back then.

**Comment by bothie** [comment]
The whole point of suspend/resume is after resume to have the system in exactly that state it was in upon suspend. So, I would never expect mpv to jump to the current frame of a live feed after resume. What you could do is to add some resume hook to your system's configuration to kill of that specific mpv instance so it get's restarted by your script. Maybe, WHAT could be added to mpv is some command to drop the entire cache, search for next keyframe, start initial buffering and then continue playback from that position. This would allow you to either add a key binding for that or send that command to mpv (instead of killing it and letting it be restarted by your script).
