### ISSUE TITLE
Minor hang up during volume adjustment 

### ISSUE THREAD

**Issue by iZN1337** [mpv-player/mpv#6447]
### mpv version and platform
mpv 0.29.0-107-gd6d6da4711 on Windows 10 Home x64 (1809)
(latest build off shinchiro's sourceforge)

### Reproduction steps
- Opening any video file
- Adjust volume the very first time (increasing or decreasing)
- No lags/hang-ups after that

### Expected behavior
Should normally adjust volume without any hang-ups.

### Actual behavior
Video hang-ups for a few seconds or less, sometimes more than a second for some files whenever I adjust the volume after opening the file. It does not hang-ups after setting the volume the very first time. Even if I drag a new video file on the existing window, it won't hang up. It only happens when there is a new instance of mpv window.

### Log file
https://gist.github.com/iZN1337/e04d083889dbfcebe056751787e3818b

### Sample files
Happens with any video file for me at least.

--
I also found a similar closed issue #5406 where it happens to be the same issue as mine, but I'm here to provide any other info because I've already tried everything that is mentioned there, yet no luck. Default config, default input or with `--no-config` it's still the same behaviour. I also tried `--ad-lavc-threads=0` and `--volume=95`.

**Comment by haasn** [comment]
Does `--osd-level=0` help?

**Comment by iZN1337** [comment]
That helped. No hang up when I change the volume. @haasn

**Comment by haasn** [comment]
It's most likely font-related, probably due to slow font resolution.

Dunno if there's a fix that doesn't involve switching to a platform with a working fonts system.

**Comment by iZN1337** [comment]
Yep, I have around 4000+ fonts. I see why now it's a problem, but to add more: I'm running Windows on an NVMe SSD along with mpv on that drive too. So at least there are no HDD read speeds. 

Is the work-around something I can do or it will have to wait for some update?

**Comment by zc62** [comment]
Realted: #2998

Not really sure if libass can be built with fontconfig or not on Windows. @shinchiro 
A quick google search just tells me Windows does not support fontconfig well so probably no.
Without fontconfig, libass uses directwrite (related: https://github.com/libass/libass/issues/79)

Does XySubFilter require long font loading time? Probably should have a look at how the font is loaded in XySubFilter. (https://github.com/Cyberbeing/xy-VSFilter/blob/xy_sub_filter_rc4/src/dsutil/FontInstaller.cpp)

**Comment by shinchiro** [comment]
It can but with some hacks. Before xp support was removed, the mpv's libass always built with fontconfig.

**Comment by shinchiro** [comment]
Here's the mpv's build with libass-fontconfig-enabled. Try it out whether it solves your problem or not
[mpv-x86_64-20190316-git-dd83b66-fontconfig.zip](https://github.com/mpv-player/mpv/files/2973873/mpv-x86_64-20190316-git-dd83b66-fontconfig.zip)

**Comment by iZN1337** [comment]
I'm sorry I can't test this anymore since I have basically cleared out all of the downloaded fonts from the Windows folder and have switched to a font manager like FontBase. It was a huge pain for me to remove all of those fonts so I hope someone else can do it.

**Comment by weebo221** [comment]
I've tested it and works fine, no lags at all. If someone wants to play files with included fonts only I think the solution is nice.

**Comment by Artefact2** [comment]
Same issue here, on Linux. Using mpv 0.29.1 with ffmpeg n4.1.3 and the OSD lags for a couple of seconds the first time it is used (when seeking, changing volume, etc.). 

~~~
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.5.3 (COMPLEX)
[osd/libass] Setting up fonts... <-- This is where it hangs
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/noto/NotoSans-Medium.ttf, 0, NotoSans-Medium
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
~~~

**Comment by zc62** [comment]
@Artefact2 Actually yours is not the same issue as the OP's. If you've read the comments, you would find this issue is highly platform-related. What we did was trying to let Windows use fontconfig, because we thought using fontconfig might help a bit. Apparently you are using native fontconfig on Linux. What you need to do is to try to set up your fontconfig properly (cahce, etc.). And there is no point to report such kind of problems here, as the sub/OSD font loading is 100% controlled by libass.

**Comment by Akemi** [comment]
see https://github.com/libass/libass/issues/334

**Comment by akanosora** [comment]
> 
> 
> Here's the mpv's build with libass-fontconfig-enabled. Try it out whether it solves your problem or not
> [mpv-x86_64-20190316-git-dd83b66-fontconfig.zip](https://github.com/mpv-player/mpv/files/2973873/mpv-x86_64-20190316-git-dd83b66-fontconfig.zip)

My mpv start-up has always been slow in Windows in the past (compared to Linux and OSX). I have 1400+ font files. This build solved the slow start-up issue.

**Comment by wm4** [comment]
I suspect that build either doesn't use the global font dir, or it uses the fontconfig cache from other mingw programs (probably the latter). I suspect it'll behave worse when font config has to rescan the fonts, e.g. when adding or removing a font file. Or fontconfig somehow fixed their slow mess.

**Comment by akanosora** [comment]
You are right that it uses the fontconfig cache. It did scan the fonts the first time I ran it and I saw the cache files were generated under `AppData\Local\fontconfig\cache`. It did not take too long though (I'd say it's even faster than the bulid without fontconfig enabled.). What makes me happy is that once the font cache was created, mpv starts way faster with almost no latency whatsoever.

**Comment by shinchiro** [comment]
fyi, I decided to build with fontconfig support in my future builds to avoid this kind of problem. Doesn't look like libass will fix it soon.

**Comment by avih** [comment]
Hmm.. tough choice, make it slow-ish every launch for people with thousands of fonts while fast all the time for the vast majority of users (direct write), or very slow for all users on first launch or whenever a font is installed/removed and fast for all users otherwise (fontconfig).

I know that for me it became much nicer when it started using direct write. The occasional very slow startup with fontconfig was a PITA for me.

Do we have some numbers to compare the slow-ness of the two methods?

Maybe fontconfig could be a runtime config of libass which mpv could support, so that most users will get the "fast all the time" solution, while those with extreme number of fonts could pick their poison?

**Comment by shinchiro** [comment]
> or very slow for all users on first launch or whenever a font is installed/removed and fast for all users otherwise (fontconfig).

This doesn't true anymore since I'm patching the fontconfig. First launch is faster like using directwrite-libass. The only things I'm uncomfortable is bundling noto sans fonts inside each build

I compiled libass with fontconfig support today. You can test it if you want: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20200105-git-9eb3991.7z/download

**Comment by avih** [comment]
What's the libass patch? Maybe PR it?

**Comment by Apache553** [comment]
> see [libass/libass#334](https://github.com/libass/libass/issues/334)

I think the newly released libass fixed that slow font loading on Windows. The related issue is now closed.

**Comment by Dudemanguy** [comment]
It looks like libass fixed this a while ago.
