### ISSUE TITLE
sub-filter-sdh filters out some phrases, that are not SDH hints

### ISSUE THREAD

**Issue by eternal-sorrow** [mpv-player/mpv#6502]
### mpv version and platform
0.29.1

### Reproduction steps
Play sample file with --sub-filter-sdh

### Expected behavior
All phases visible

### Actual behavior
The phrase "Всё таки" in sample file is being skipped

### Log file
https://0x0.st/zibA.log

### Sample files
https://0x0.st/zibm.mkv

**Comment by zc62** [comment]
Currently `--sub-filter-sdh` works for English only. So "Всё таки" was read as ASCII char string and probably an ASCII ":" character is matched. To properly deal with non-English languages the `skip_speaker_label` function should be rewritten with UTF-8 libraries.

**Comment by eternal-sorrow** [comment]
I personally often watch films with English subtitles and `sub-filter-sdh` sometimes makes it much more clear, so I kept it enabled in the config file. But sometimes I watch videos with Russian subtitles and some phrases got skipped. I was thinking why it could be. I thought of maybe malformed subtitle tracks that mpv could not parse. Until I tried disabling `sub-filter-sdh`, which suddenly fixed the issue.

**Comment by zc62** [comment]
Maybe you can use [`track-list/N/type`](https://mpv.io/manual/master/#command-interface-track-list/n/type) and [`track-list/N/lang`](https://mpv.io/manual/master/#command-interface-track-list/n/lang) to write a user script that automatically disables `sub-filter-sdh` for non-English subtitles.

**Comment by eternal-sorrow** [comment]
That doesn't work for external subtitle track loaded by `sub-auto=fuzzy`.

**Comment by zc62** [comment]
Turns out it is not the fault of the `skip_speaker_label` function. It needs no modification. It is when determining if the line has valid texts, only printable ASCII characters except `'-'` were considered valid. So this is easily fixed by adding one line. See the PR.

"Всё-таки" is marked as invalid since it has no ASCII characters except the `'-'`.

"мы ещё на шаг приблизились к истине." can show up because of the final period.

Don't know why but the first sentence "Да просто так." never shows up when I test it, even when SDH is totally disabled. Probably because my system does not support Russian subtitles so well. Does it show up when you play the file?

**Comment by eternal-sorrow** [comment]
>Don't know why but the first sentence "Да просто так." never shows up when I test it
it doesn't matter. is shows correctly in the full movie, even with `sub-filter-sdh` enabled. just video splitting artifact.
