### ISSUE TITLE
Multistream video

### ISSUE THREAD

**Issue by amarao** [mpv-player/mpv#651]
Here sample: https://cast.switch.ch/vod/clips/26uo9i576i/quicktime.mov

3 video streams, one audio. Different two streams embedding in third. Apple Quicktime can play them. VLC can play them but without embedding.

mpv plays only first stream.

**Comment by kevmitch** [comment]
The linked video only has one stream according to mpv, ffmpeg, and mediainfo. Maybe it's changed since it was originally posted. I don't really understand what the reporter is asking for exactly, but mpv currently handles switching between video tracks in multi video track files and even multiplexing them with `--lavfi-complex`.
