### ISSUE TITLE
seek to final frame

### ISSUE THREAD

**Issue by NoSuck** [mpv-player/mpv#6545]
### mpv version and platform

mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.1

Linux 4.20.7-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 6 18:42:40 UTC 2019 x86_64 GNU/Linux

### Expected behavior

Executing a binding for `seek -0 absolute` or `seek 100 absolute-percent` should seek the video's final frame.

### Actual behavior

The former seeks 0:00, while the latter seeks 96% (or some other non-100% position, depending upon video length).

Thank you for contributing to this great piece of software.

**Comment by qmega** [comment]
Seeks snap to keyframes by default. You need to add `exact` to your commands to get the kind of precision you seem to be looking for. `seek 100 absolute-percent+exact` should get you to the end, but mpv will then immediately exit (even if paused), unless you have `--keep-open` enabled.

-0 is the same as 0, and seek-from-end has to be strictly negative, but you could do something like `seek -0.001 absolute+exact` which I think would get you the last frame up to 1000fps. You still need `--keep-open`, based on my quick test.

Depending on how exact you need to be, you could also use something like -0.1 or -0.05 which would hit one of the last few frames and not require keep-open.

**Comment by NoSuck** [comment]
Thank you for the feedback.

> You need to add `exact` to your commands to get the kind of precision you seem to be looking for.

I did not do this, on account of the following excerpt from mpv's man page:

> By default, keyframes is used for relative seeks, and exact is used for absolute seeks.

However, testing has shown that adding `+keyframes` does indeed seek to the final frame for both of your examples.  Perhaps documentation should be amended.

That only leaves the issue of rendering the final frame.  I don't suppose there is a command for manual redrawing?  I was unable to find one.

Also, executing `frame-back-step` after seeking to the final frame results in no frame change, even though it functions as expected at other points in the video.  Is this intended behavior?

**Comment by qmega** [comment]
>  Perhaps documentation should be amended.

The code appears to be doing roughly what the documentation says it does, and when not dealing with the end of the file, the behavior I observe matches it too. We've both observed that something's off in this case, but I'm not sure what. There are definitely some edge cases when the end of the file is involved and I don't really understand them.

While exploring I saw that there's actually an internal function called `seek_to_last_frame`, which is called with keep-open when "EOF not reached normally" (e.g. seeking past the end rather than playing up to it) and when chapter-skipping past the end. For at least the one random file I tried, `seek 100 absolute-percent+exact` actually does end up calling that function.

> Also, executing `frame-back-step` after seeking to the final frame results in no frame change, even though it functions as expected at other points in the video. Is this intended behavior?

For me, `frame-back-step` does work after seeking to the final frame. Are you sure it's not for you? If you back-step a bunch of times does it never go anywhere? I think it would be fairly common for the last two frames of a video to be identical. If by chance you were going by a persistent OSD for frame position, it might have been lying to you because it wasn't updated when it hit the last frame. (You can see this very clearly with `--osd-msg1='${eof-reached}'`. It says "no" when playback stops but if you get the OSD to refresh it'll change to "yes".)

Would you mind sharing a little more context on why you want this? Do you actually just want to examine the last frame of the video for whatever reason, or is this part of some larger goal? If it's the latter, there might be an easier way to get there.

**Comment by NoSuck** [comment]
Please ignore my previous post--especially this:

> However, testing has shown that adding ~~+keyframes~~ does indeed seek to the final frame...

I meant to write `+exact` instead of `+keyframes`.  The original post has been amended.

> The code appears to be doing roughly what the documentation says it does...

I'm not sure I follow.  Did you say this in light of the aforementioned typo?  The documentation says that `exact` is default, yet it is not.

In any case, I have tested various bindings.  Here are the results:

binding | seeks to...
------- | -----------
G set pause yes ; osd-msg-bar seek -0 absolute                | 0
G set pause yes ; osd-msg-bar seek 100 absolute-percent       | 83%
G set pause yes ; osd-msg-bar seek 100 absolute-percent+exact | 0
G set pause yes ; osd-msg-bar seek -0.001 absolute+exact      | 0

Does that look right to you?  I used [a little running pig](https://i.imgur.com/tlY1kYn.mp4) (~1.5 MiB) as a test video.

> Do you actually just want to examine the last frame of the video for whatever reason...

Yes.  I was trudging through a large collection of videos to be uploaded to a viewing site.  The last frame is important because it is displayed indefinitely when playback has finished.  I tried using mpv to quickly confirm the last frame for each video but ran into this stumbling block.

**Comment by garoto** [comment]
`hr-seek=yes`

boom, all seeks are precise by nature now.

**Comment by NoSuck** [comment]
`hr-seek=yes` seems to be like adding `+exact` to every binding.  It's a handy shortcut, but it doesn't help to seek the final frame.

**Comment by qmega** [comment]
> I'm not sure I follow. Did you say this in light of the aforementioned typo? The documentation says that `exact` is default, yet it is not.

No, I figured `+exact` was what you meant. I was saying that absolute is exact by default, as it's documented. I did miss something, though, and I feel pretty dumb now that I figured it out. `absolute-percent` doesn't get auto-exact, regardless of whether it's 100% or not. `absolute` does get auto-exact. I was wrong about being near the end of the file having anything to do with it. Clarifying in the docs that absolute-percent isn't exact probably would be helpful. Or, maybe absolute-percent should be exact.

As far as getting the last frame, though: I tried with your sample, and my last two results are different from yours. I do get the last frame. Added a couple extra test cases to demonstrate what I said above.
(I've been using git master, but I tried 0.29.1 as well with the same results.)

binding | seeks to
------- | --------
`set pause yes ; osd-msg-bar seek -0 absolute` | 0
`set pause yes ; osd-msg-bar seek 100 absolute-percent` | 83% (00:00:25.000)
`set pause yes ; osd-msg-bar seek 100 absolute-percent+exact` | 100% (00:00:29.967)
`set pause yes ; osd-msg-bar seek -0.001 absolute+exact` | 100% (00:00:29.967)
`set pause yes ; osd-msg-bar seek -0.001 absolute` | 100% (00:00:29.967)
`set pause yes ; osd-msg-bar seek 30 absolute` | 100% (00:00:29.967)
`set pause yes ; osd-msg-bar seek 30 absolute+keyframes` | 83% (00:00:25.000)

In other words, for me it looks like it's getting the last frame reliably with `exact` (whether exact is automatic or not). And I can frame-back-step and immediately get a different frame when I get there.

If you're sure about the results you're getting, post a log.

And just to make sure we're on the same page: As far as I can tell, the last frame is this:
![ffmpeg-last-frame](https://user-images.githubusercontent.com/395817/54887957-75325200-4e90-11e9-96d3-fb2c2835f71b.png)
I get identical images from --vo=image (writes each frame to a file instead of displaying them), seeking with one of the above commands and taking a screenshot, and with `ffmpeg -i sample.mp4 frames/%d.png` (plain ffmpeg just disagrees on color a bit, but it's the same frame). So if there's a frame after that, ffmpeg isn't even decoding it.

**Comment by NoSuck** [comment]
Thank you for looking into this.  I used your third binding (`set pause yes ; osd-msg-bar seek 100 absolute-percent+exact`) and an empty config file in producing the attached log.  Sadly, this failed to coax mpv into seeking the final frame.

The binding was activated on line 575 and mpv was run as `mpv --msg-level=all=debug --log-file finalFrame.log --loop https://i.imgur.com/tlY1kYn.mp4`.  Any ideas?

[finalFrame.log](https://github.com/mpv-player/mpv/files/3011680/finalFrame.log)

**Comment by qmega** [comment]
It's because of `--loop`. That takes precedence over `--keep-open` and takes you back to the beginning when you hit EOF. You also aren't using `--keep-open` in the first place, actually -- you'll need to. AFAIK that's the only way to make mpv freeze on the last frame.

If you really need `--loop` while playing, you can use `set pause yes ; set loop no ; osd-msg-bar seek 100 absolute-percent+exact` for your binding.

**Comment by NoSuck** [comment]
Thank you for your patience and understanding.  The interaction among `--loop`, `--loop-playlist`, and `--keep-open` is what threw me off.

... that and the docs issue!  Please see #6589.

Your suggestions were very helpful, and I appreciate it.
