### ISSUE TITLE
[DOCUMENTATION] Could the main README file show a line of which git clone command that could be used?

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#6554]
Hello mpv team,

These days I am mostly fetching a new mpv-release every ~2 months or so, but I am
mostly doing so randomly, on my own (not using the snapshots).

The git clone command I use is this:

    git clone https://github.com/mpv-player/mpv

I am not a git expert, so this appears to be downloading a lot of stuff; most of, I
assume, I will not need, as my goal is only to compile mpv from source (which,
by the way, works fine).

Would it be possible to show the git clone command, in particular the git variant
that can be used to just do a fast download of the sources, via git?

I read somewhere on the bugtracker to use --depth 1 but someone stated that
then we lose some information (tags), so I was not sure whether this would
be a useful thing to do for me (I am a git noob, sorry).

Would it be possible to show a sentence or two how to obtain the latest source
via git, in the main README? Does not have to be long, just a short example
or two; ideally I would then be able to use the command that allows me to 
download the git sources to mpv faster ... right now git is still working and more
than ~5 minutes have passed (wget a tarball typically is much faster). Thank you
for reading - please feel free to close this issue at any moment in time to keep
the number of issue trackers low. :)

**Comment by Akemi** [comment]
this is completely out of scope of mpv. it's just the basic how git works, just read up on git commands. what you can use, like you already mentioned, is `git clone --depth 1 https://github.com/mpv-player/mpv`. this will do a shallow clone and you just lose some information that's unnecessary for building.

if you keep you folder you can also just do (`git fetch` and) `git pull` in that folder and it will get all the changes since the last time.

if that is still to slow just use the green download button (top right) on the githup page.
