### ISSUE TITLE
userscript does not react to keypress if using --input-default-binding=no

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#6583]
### mpv version and platform
mpv 0.29.1, archlinux package

### Reproduction steps
``` 
mpv   --script=/home/koko/.config/mpv/scripts/fastforward.lua  --input-default-bindings=no mediafile 
```

### Expected behavior
since the script binds to "(" and ")", i expect that it would react to those keypresses.

### Actual behavior
...but it does not.
removing the option --input-default-bindings makes it work

### Log file
script not reacting to ")" : https://0x0.st/zK2n.log
script reacting to ")": https://0x0.st/zK2k.log

script source: https://github.com/zsugabubus/mpv-fastforward/blob/master/fastforward.lua

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

**Comment by zc62** [comment]
I believe this is intended. Otherwise you get no way to disable the key bindings from user scripts.

Actually the script already tells you what to do: https://github.com/zsugabubus/mpv-fastforward/blob/e473f6acc1cb7793d5686a827663b10641b61a0a/fastforward.lua#L12-L19
```
)       script-binding fastforward/speedup
(       script-binding fastforward/slowdown
```
Put in your `input.conf`. Only those are considered as user-defined key bindings.

**Comment by kokoko3k** [comment]
What puzzles me, is that othet scripts just work even with input-default-bindings =no (eg: equalizer.lua https://gist.github.com/avih/41acff712abd32e1f436235388c8b523)

**Comment by zc62** [comment]
Because [`add_forced_key_binding`](https://mpv.io/manual/master/#lua-scripting-mp-add-forced-key-binding(-)) is used.
