### ISSUE TITLE
Subtitles can get out of the window

### ISSUE THREAD

**Issue by Porkepix** [mpv-player/mpv#6587]
### mpv version and platform
```
$ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.2
```

### Reproduction steps
Only play a video file with some subtitles that are going to appear out of the window.

### Expected behavior
Subtitles should be completely in the window.

### Actual behavior
Subtitles are partly out of the window

### Information and other tests

I have no idea if subtitles can be "positionned", however I seeked for the same time the issue was in the file with totem-player and VLC that were also installed on my laptop. While totem-player displayed a similar issue (three line subtitle on the top of the window, the first one being mostly out of the window), VLC displayed the same text on two lines, probably smaller font and nothing out of the window.

I can add a screenshot if it's useful, although it can't allow to reproduce the issue.
Or do further tests if there are some tests I can do on my side.

**Comment by zc62** [comment]
Upload the subtitle file and a full log file generated when playing it.

**Comment by Porkepix** [comment]
> Upload the subtitle file and a full log file generated when playing it.

So, instead of giving a full subtitle file, here's the line I got the issue from, extracted from the .mkv:
`Dialogue: 0,0:08:33.52,0:08:40.50,Normal,,0,0,0,,{\c&H092301&\3c&HCDCED5&\be5\pos(328,81.733)}Cat Sitting: Une demi-journée/ Un repas = 30 mon\NToute la journée / 2 repas = 50 mon
`
I also got the issue sometimes on other files.

And here's the (very long) log file: https://privatebin.net/?64d9ab066dc9b476#/0VOvZcy9F5UF5X7LjnDh+tCYhNvMASYQK7i7L93K3s=

I seeked for the place where the issue was while playing, then let it play for a few seconds before and after.

**Comment by zc62** [comment]
I thought it could be a `srt` subtitle, but apparently it is `ass`. So this issue is invalid.

> Subtitles can get out of the window

Yes, they can. They are allowed to do so. 100% sane.

The thing is, if the one who muxed the subtitle file into the mkv file got the subtitle file somewhere else, probably he ignored the fact that ass subtitle effects may depend on the video resolution. If the subtitle is designed for, for example, 640x480 video resolution, but the video you played is actually 1280x720, there can be mismatches. (Why should I guess the script resolution instead of telling it from the sample file? The line you posted is not critical, though it does indicates a `\pos` command. The header of the ass file is more important. I don't have to guess if you do upload the file.)

If the subtitle is designed for this particular video file, blame the one who made it, not mpv. (And mpv is not even responsible for subtitle rendering. libass is.)

**Comment by Porkepix** [comment]
@zc62 Sorry, didn't knew about the headers that could be useful, I'm not knowledgeable about subtitle files.
Here it is: https://privatebin.net/?2b21b20e3f4e3901#E0UlWLE6tEUrXgPg96HMws1Q4PqdKskcsQetukkJ/pU=

What's strange though is that, as explained above, totem-player suffer from the same issue as mpv while VLC display it on two lines rather than three and I think with smaller fonts, resulting in the whole text being correctly displayed inside the window. But maybe are they tweaking something?

**Comment by zc62** [comment]
I tested with a 1280x720 video, the same resolution as indicated in your log, but it shows fine.
![mpv-shot0001](https://user-images.githubusercontent.com/17048823/55103596-29092c80-509f-11e9-9ad2-0b699533ed7b.jpg)

The problem on your end is you do not have the correct font installed.
The script says
```
Style: Normal,Cambria,36,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1
```
Since you don't have `Cambria` font family installed, libass falls back to `DejaVuSans`.
```
[   6.915][i][sub/ass] fontselect: Using default font family: (Cambria, 700, 0) -> /usr/share/fonts/TTF/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold
[   6.915][v][sub/ass] fontselect: (Cambria, 700, 0) -> /usr/share/fonts/TTF/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold
```
This is what it looks like if I manually change the script to use `DejaVu Sans Bold`:
![mpv-shot0002](https://user-images.githubusercontent.com/17048823/55104840-8b632c80-50a1-11e9-81b0-d4421ad4f976.jpg)

**Comment by Porkepix** [comment]
So, what is doing VLC here? Tinkering/tweaking on the fallback font? Font size? Linea break?

**Comment by zc62** [comment]
I know nothing about VLC. You can have a look at its log.

**Comment by Argon-** [comment]
I'm pretty sure it just uses a different fallback and it works better (in this case) simply by chance. 
With ASS subs absolutely _everything_ is specified in the script. There is really no parameter left for the player to tweak without potentially ruining the subs (think of typesetting matching the video etc).

**Comment by Porkepix** [comment]
libass seems to insert its own debug into vlc debug mode, here are the related lines:
```
[ass] Shaper: FriBidi 1.0.5 (SIMPLE) HarfBuzz-ng 2.3.1 (COMPLEX)
[ass] Using font provider fontconfig
[ass] fontselect: Using default font family: (Fade to grey, 400, 0) -> /usr/share/fonts/TTF/LiberationSans-Regular.ttf, 0, LiberationSans
[ass] fontselect: (Fade to grey, 400, 0) -> /usr/share/fonts/TTF/LiberationSans-Regular.ttf, 0, LiberationSans
[ass] fontselect: Using default font family: (Bert, 400, 0) -> /usr/share/fonts/TTF/LiberationSans-Regular.ttf, 0, LiberationSans
[ass] fontselect: (Bert, 400, 0) -> /usr/share/fonts/TTF/LiberationSans-Regular.ttf, 0, LiberationSans
```

**Comment by Porkepix** [comment]
Okay so after a little bit of more digging with Akemi and JEEB on IRC, it looks like the final say is that font is missing from system and the .mkv file and that vlc have some minor changes to libass defaults in case of missing resources, therefore defaulting to another font.
This other font on this specific file result in the issue not being here, because it displays the subs on two lines rather than 3 with smaller font and so nothing is outside of the screen.
