### ISSUE TITLE
Alsa audio resampling

### ISSUE THREAD

**Issue by eblanca** [mpv-player/mpv#6643]
### mpv version and platform
mpv 0.29.0-301-g6c91314900-dirty
(static build done using mpv-build script)

### Reproduction steps
This is NOT a bug report, just a support request.
I just play any audio file with sample rate different than 48000 Hz

### Expected behavior
Open audio device with the matching sample rate parameter.

### Actual behavior
Audio device is opened as 48 kHz, regardless of audio source sample rate.

### Log file
https://0x0.st/zqzv.txt

### Sample files
No need for a sample file, just try to do the same with any audio source having sample rate != 48000 Hz.

In the log file, look at the statements
`[cplayer]  (+) Audio --aid=1 (*) (aac 2ch 44100Hz)`
and
`[autoconvert] inserting resampler`
which I'm quite sure I didn't ask for.
Nevertheless, the conversion is done.
Now, this is not a serious bug, I just want to understand whether I requested (with any options) this resampler or not, as by mpv documentation I can't see any ways to explicitly say NO to resampling/conversion (as I think any unwanted resampling is just a waste of cpu cycles, don't you?) .

**Comment by lachs0r** [comment]
Try `--alsa-resample=yes`. This is disabled by default because Debian shipped buggy ALSA. Not sure if it still applies to anything. Kind of a misnomer because IIRC it just asks ALSA to reconfigure the device to whichever sample rate is requested. In general, that results in a resampling plugin getting inserted if the underlying PCM does not support the requested rate. Which resample ALSA inserts depends on user configuration and installed plugins (libasound will prefer the speex algorithm if it’s available; otherwise it will use low-quality linear interpolation).

CPU usage in either case: Absolutely negligible. Speex’ algorithm in particular is a very good speed/quality tradeoff: http://abload.de/img/resamplersgyoik.png
Even at its lowest quality setting, the aliasing artifacts should be very hard to hear.

BTW: PulseAudio will automatically switch to supported hardware rates if possible.
