### ISSUE TITLE
Invalid JSON output on NaN

### ISSUE THREAD

**Issue by phiresky** [mpv-player/mpv#6691]
### mpv version and platform

mpv 0.29.0-325-g037cbacb8c
Arch Linux

### Reproduction steps

mpv --input-ipc-server=/tmp/mpvsocket filename

```
$ socat - /tmp/mpvsocket
{command:["get_property", "cscale-wparam"]}
{"data":nan,"request_id":0,"error":"success"}
```
### Expected behavior

nan is encoded in some way (null or a string)

### Actual behavior

the json is invalid.

This happens both in Lua with `utils.format_json(out)` and in the IPC server. Makes parsing the JSON with normal tools impossible.

**Comment by CounterPillow** [comment]
>Makes parsing the JSON with normal tools impossible.

Worthy of note is that while `NaN`, `-Infinity` and `Infinity` are invalid values according to the spec, some tools like Python's JSON module accept it (and even serialise it by default!).

>nan is encoded in some way (null or a string)

Are there any mpv properties where NaN is ever used to mean something other than "this is invalid because it hasn't been initialised yet"? null seems to be the obvious candidate if that's not the case, but to be fair both string and null suck for users of the IPC if they're e.g. checking whether something is greater than 0.

**Comment by wm4** [comment]
> Are there any mpv properties where NaN is ever used to mean something other than "this is invalid because it hasn't been initialised yet"?

Setting/getting those cscale params.

Personally, I tried to avoid exposing nan anywhere in the API, but I guess these scale params are an exception. The command line doesn't even allow setting them.

**Comment by wm4** [comment]
I explicitly fixed it for the affected options (first commit). I also made JSON output write nans as strings (second commit, untested, yolo). But if you still see any nans from mpv, please report it. In my opinion, they shouldn't appear in the API.
