### ISSUE TITLE
Incorrect gui behaviour with vo=vaapi hwdec=vaapi in fullscreen

### ISSUE THREAD

**Issue by rox4d** [mpv-player/mpv#6707]
### mpv version and platform
mpv git-2019-02-24-5370069 ,  Ubuntu-16.04 amd64 (it the same with i386)
mesa was updated from git.
I was compile libva from git (mesa and mpv for using it) with Ubuntu-16.04 i386  on system with r600 card - it is the same in that place.

### Reproduction steps
play any video with mpv -vo=vaapi -hwdec=vaapi (at least for hw supported formats on r600 and radeonsi)

### Expected behavior
In fullscreen mode UI must appears when mouse cursor close to bottom of screen

### Actual behavior
UI in full screen mode are behave the same way as  in windowed mode if it window are placed at the left top  of the screen.
### Log file
[output.txt.gz](https://github.com/mpv-player/mpv/files/3169860/output.txt.gz)

**Comment by zc62** [comment]
I guess this is a known issue and nobody cares to fix it, because `vaapi` vo is not recommended, and is left in mpv only for compatibility reasons. Read the manual: https://mpv.io/manual/master/#video-output-drivers-vaapi

>Note that there is absolutely no reason to use this, other than compatibility. This is low quality, and has issues with OSD.

Just stop using `vo=vaapi`. Use the default `gpu` vo. It is much better and supports vaapi hwdec as well.

**Comment by rox4d** [comment]
In ancient hardware with low memory mpv with vaapi (seems vaapi from git not leaks) eats noticeable less of memory (against -vo=gpu -hwdec=vdpau).

**Comment by Gusar321** [comment]
The problem here is that mesa doesn't support a vaapi feature, VA_SUBPICTURE_DESTINATION_IS_SCREEN_COORD, which allows for much better OSD/OSC/subtitle rendering. You'll also notice that the OSC is much blurrier in fullscreen, because it's rendered in video resolution and then scaled up together with the video. So I'm with zc62, just don't use vo=vaapi. Also note how he didn't mention vdpau, he meant using vo=gpu with hwdec=vaapi.

**Comment by rox4d** [comment]
mpv -vo=gpu -hwdec=vaapi works but it silent about "Using hardware decoding" and it is slow. I suppose mpv makes software decoding in that case.

**Comment by Gusar321** [comment]
Oh, right, you also need --gpu-context=x11egl. PR #5298 should really get merged, like today.

**Comment by rox4d** [comment]
It works, thanks!

**Comment by HattinGokbori87** [comment]
I have a notebook with intel core i3 3rd generation CPU with integrated graphics. I use MPV with SMPlayer front-end. For some reason "vo=vaapi & hwdec=vaapi" combination uses the least memory compared to any other combination. 
Also if I take a screenshot (PNG) of the same frame with both "vo=gpu" and "vo=vaapi" (hardware acceleration enabled on both cases (hwdec=vaapi), subtitle visibility is disabled), the size of the screenshot taken under "vo=vaapi" is also larger. Though I can't say if the images have different visual quality.

**Comment by CounterPillow** [comment]
@HattinGokbori87 what are you trying to tell us here?

**Comment by HattinGokbori87** [comment]
> @HattinGokbori87 what are you trying to tell us here?

Sorry, the topic wasn't related. I'm trying to know is there any difference in in video quality between "vo=vaapi & hwdec=vaapi" and "vo=gpu & hwdec=vaapi" combination seeing that screenshots taken under "vo=vaapi" settings always produce bigger file-size.
P.S: I'm not a programmer.

**Comment by Akemi** [comment]
yes. they make screenshots with different mechanism.

instead of asking a question on an unrelated, closed, and very old issues, next time try to open a new one with the question template.
