### ISSUE TITLE
Build fails on OS X 10.11 due to unavailable clock_gettime()

### ISSUE THREAD

**Issue by fkraiem** [mpv-player/mpv#6714]
### mpv version and platform

git master on OS X 10.11.6

### Reproduction steps

```
$ ./waf configure --disable-macos-cocoa-cb
[...]
$ ./waf
```

### Expected behavior

Successful compilation.

### Actual behavior

```
$ ./waf
[...]
[174/219] Compiling video/out/opengl/context_glx.c
../video/out/opengl/context_glx.c:298:13: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (clock_gettime(CLOCK_MONOTONIC, &ts))
            ^
../video/out/opengl/context_glx.c:298:27: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        if (clock_gettime(CLOCK_MONOTONIC, &ts))
                          ^
2 errors generated.

Waf: Leaving directory `/Users/firas/software/mpv/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
```

**Comment by CounterPillow** [comment]
As far as I can tell, 10.11 has not been supported by Apple since 2018. If there is no simple one-line fix for this, updating the README's requirement of "or OSX 10.8 or later." might be more appropriate.

**Comment by Akemi** [comment]
i guess we could do something similar to [this](https://github.com/mpv-player/mpv/blob/199aabddcc0105b504cc8e0cb240bc3c89288c1a/osdep/timer.c#L74-L85)?

i mean we also already have this [shit](https://github.com/mpv-player/mpv/blob/802f594a857c703ac88e946d14b69cd3b6eb6006/osdep/semaphore_osx.c) which could possibly be removed now with macOS 10.12.

i am also not completely sure if i want to bother with this, since 10.11 isn't really supported anymore.

**Comment by Argon-** [comment]
Isn't this X11 code? Why is this compiled by default for you? Or do I get something wrong?
OSX not having `clock_gettime` is nothing new and this code was committed in 2014.

**Comment by fkraiem** [comment]
Per Wikipedia it seems that 10.11 support ended in August indeed; looks like I didn't get that memo. The reason why I'm still on it is that I have an older Mac that doesn't officially support 10.12+ (though I hear there are some hacks around that).

I have xquartz installed, which could be why it wants to compile X11-related code. The problem appeared recently, though, I have a successful mpv build from 4 March.

**Comment by CounterPillow** [comment]
So macOS didn't finally add clock_gettime after all? :(

**Comment by Akemi** [comment]
@Argon- yes you are right it's X11. should have noticed that and i also kinda got the commit date wrong.

@fkraiem anyway, i just compiled mpv successfully on 10.11.6. there is definitely a problem on your end. you should probably post your configure log and what mpv version you are trying to build. i will close this though, since it's most likely not our problem.

@CounterPillow they did add it. i just quickly tested it and and from a quick glance it does return 'sane' values.
