### ISSUE TITLE
[LINUX] geometry odd doing

### ISSUE THREAD

**Issue by azaghi** [mpv-player/mpv#6717]
### mpv version and platform
mpv 0.29.0-329-g64cdc3694e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Thu May 16 11:52:50 CEST 2019
ffmpeg library versions:
   libavutil       56.28.100
   libavcodec      58.52.101
   libavformat     58.27.103
   libswscale      5.4.101
   libavfilter     7.53.101
   libswresample   3.4.100
ffmpeg version: N-93872-g7990df05f7

Linux DEBEDV 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.25-1~bpo8+1 (2017-05-19) x86_64 GNU/Linux

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Try to position window on the screen throught --geometry if y position is under the magic number 10 like:
 /usr/bin/mpv --geometry="960x540+960+0"  '/content/filemanager/videos/Audio Video Sync Test.mp4'

### Expected behavior
MPV window's should start at position x:960 y:0 and be of width=960 and height=540

### Actual behavior
MPV window's start with the right width and height, but at position x:0 y:0

### Log file
https://0x0.st/zAGH.txt

### Sample files
you can use any video file.

**Comment by Ckath** [comment]
can't seem to reproduce this on any of my linux installs with mpv, latest or older. is this on a wm where these things are expected to work at all?

**Comment by azaghi** [comment]
Thank you for your answer.
I'm using fluxbox (i have tried also to compile their last version) as windows manager. But, as for example, I don't get this behavior with mplayer on the same machine. 
Unfortunately, I have to use fluxbox for my application, maybe it exists some compatibility flag that can I activate or something else?

**Comment by Ckath** [comment]
very weird since it does work with other applications, I expected that to not work at all in your case. all relevant info about fluxbox I can find is they have some settings regarding a default spawn position, which shouldn't overwrite specified positions but also isn't really mentioned in depth anywhere else but this blog: https://winaero.com/blog/how-to-center-new-windows-in-fluxbox-for-linux/
and that they're `fbrun` utility can also position windows on a certain place: http://fluxbox.sourceforge.net/docbook/en/fluxbox-docs.html#AEN167

I'm not sure if either of these would help you out much in your situation, or why mpv wouldnt position where specified while mplayer does

**Comment by azaghi** [comment]
I can't use the first one as I have different mpv playing in the same time.  I can try to use fbrun I haven't see that it can set the position of the window so it can be a workaround.
Thank you again.

**Comment by wm4** [comment]
Works for me too. It could be a race condition, or something specific to Fluxbox. Maybe bring it up with the Fluxbox devs?

**Comment by lvml** [comment]
@azaghi: You may want to check a similar issue I found a work-around for long ago: https://github.com/mpv-player/mpv/issues/1344
