### ISSUE TITLE
Is demuxer-max-bytes the replacement for cache in conf now?

### ISSUE THREAD

**Issue by Samillion** [mpv-player/mpv#6726]
### mpv version and platform

```
mpv 0.29.0-329-g64cdc3694e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Mon May 13 23:04:15 DST 2019
ffmpeg library versions:
   libavutil       56.27.100
   libavcodec      58.52.101
   libavformat     58.27.103
   libswscale      5.4.101
   libavfilter     7.51.100
   libswresample   3.4.100
ffmpeg version: N-45742-g9d269301f0
```

### Question:

I've noticed recently that the cache options were deprecated and replaced with demuxer, though I wanted to make sure of this and to know if I'm using it correctly or if there would be a better way.

In my `mpv.conf` I currently have this for cache:

```
cache=yes
demuxer-max-bytes=800000KiB
demuxer-readahead-secs=20
```

I honestly don't really understand the `demuxer-readahead-secs`, so I left it as is, any help or explanation would be greatly appreciated.

**Comment by CounterPillow** [comment]
>Is demuxer-max-bytes the replacement for cache in conf now?

Yes but, actually, no. mpv's caching used to have two different parts:
1. the stream cache (the one that has been removed, but may come back due to badly muxed files)
2. the demuxer cache

Right now in git HEAD, the stream cache is removed, and the demuxer cache rules the world. But even before that, the stream cache options did not affect the demuxer cache, i.e. the demuxer kept reading until `demuxer-max-bytes`, with the stream cache being an additional cache that reads ahead of the demuxer cache if I recall correctly.

`demuxer-readahead-secs` will cache that many seconds of demuxed data, which relies on the container having proper timestamps. However, this is limited by `demuxer-max-bytes`, so if you set both you cache either `demuxer-max-bytes` or `demuxer-readahead-secs` amounts of data, whichever one limit is hit first. However, `demuxer-readahead-secs` is overridden by cache-secs if cache-secs is larger, and by default (`mpv --list-options | grep cache-secs`) this is currently set to 36000 seconds (10 hours).

So in essence, your options cache 800000 KiB of data, but at the most 10 hours of video. So unless your video is less than about 177 kbit/s, your `demuxer-readahead-secs` is never hit. Either set `cache-secs` instead or don't set `demuxer-readahead-secs` at all.

**Comment by Samillion** [comment]
@CounterPillow Thank you very much for the detailed response. I did exactly as you suggested and removed readahead. I had one more question if you don't mind, it seems with demuxer, prefetch isn't cached with stream or local files. Am I missing some configuration?
