### ISSUE TITLE
Auto profile for local files

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#6727]
### mpv version and platform

mpv 0.29.1
macOS 10.14.3

### Reproduction steps

1. Create a profile with some options
```
force-window=no

[protocol.file]
force-window=yes
```
2. Run mpv and load a local file

### Expected behavior

Options under `protocol.file` profile should be applied when a local file is opened.

### Actual behavior

Auto profile does not work for local files even when provided with a `file:///` URI.
There is no force window when an audio file is opened.

**Comment by Akemi** [comment]
maybe has something to do that `file://` is listed twice.

```
mpv --list-protocols
Protocols:

 rtmp://
 rtsp://
 http://
 https://
 mms://
 mmst://
 mmsh://
 mmshttp://
 rtp://
 httpproxy://
 rtmpe://
 rtmps://
 rtmpt://
 rtmpte://
 rtmpts://
 srtp://
 data://
 lavf://
 ffmpeg://
 udp://
 ftp://
 tcp://
 tls://
 unix://
 sftp://
 md5://
 concat://
 avdevice://
 av://
 file://
 bd://
 br://
 bluray://
 bdnav://
 brnav://
 bluraynav://
 memory://
 hex://
 null://
 mf://
 edl://
 rar://
 file://
 fd://
 fdclose://
 appending://
```

**Comment by Ckath** [comment]
the `file://` protocol prefix seems to be intentionally removed:
https://github.com/mpv-player/mpv/blob/f203a881e56e34e6d403a2091bd3dfec9a6c38ce/stream/stream_file.c#L157-L162
which causes protocol(`item` here) to be nothing where its checked:
https://github.com/mpv-player/mpv/blob/f203a881e56e34e6d403a2091bd3dfec9a6c38ce/player/configfiles.c#L132-L136
in turn making it impossible to respect a [protocol.file] block

it'd be trivial to remove the check in stream_file.c so at least files with a file:// prefix would get the file protocol, but it probably has a reason somewhere to be filtered out

overall you'd be better off doing the same with extension eg `[extension.wav]`

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/commit/1d2a11133737802baa555dcbff9482bd5c8120ad the commit.

**Comment by Ckath** [comment]
the duplicate `file://` entries are because that list is bui9lt from `stream_list` which contains a bunch of stream_info_t structures, and nothing stops different stream types from having having a `file://`:
https://github.com/mpv-player/mpv/blob/f203a881e56e34e6d403a2091bd3dfec9a6c38ce/stream/stream.c#L798-L811
the stream_info_ifo_dvdnav has the first `file://`:
https://github.com/mpv-player/mpv/blob/f203a881e56e34e6d403a2091bd3dfec9a6c38ce/stream/stream_dvdnav.c#L508-L512
and then theres also _stream_info_file:
https://github.com/mpv-player/mpv/blob/f203a881e56e34e6d403a2091bd3dfec9a6c38ce/stream/stream_file.c#L362-L369

so suppose thats fine, seems silly to filter it out just in the print in case some protocols overlap
