### ISSUE TITLE
when i rotate a video,the color is changed

### ISSUE THREAD

**Issue by kli2013** [mpv-player/mpv#6728]
i download many youtube video,some videos were shot horizontally. i used the shortcut key to rotate them vertically and the color changed. it looked black and white.

simple view
https://imgur.com/a/nT1jy7Y

i don't konw how to fix it

**Comment by CounterPillow** [comment]
mpv version? sample file? log file?

**Comment by praneetk96** [comment]
I having this same issue, it's not just about one video, it's happening with every video which is like shot from a phone for example then on playing on PC the orientation of video is sideways, it weird to watch it like that, on video-rotate function which works but the problem is on 90 and 270 degree the color of the video changes, like it video have colored strip lines but not when it's on 0 and 180 degree, my mpv version is v0.37.0, running on arch Linux.

**Comment by shohan11d** [comment]
same here. were you able to fix it?

**Comment by shohan11d** [comment]
The solution for me was installing mpv using "sudo apt-get install mpv"


Because the Snap store has a more updated version of "mpv" 
I installed it from the snap store before.  
But whenever rotating the video using keybind the video used to get black and white.
but installing using "sudo apt-get install mpv" fixed the issue for me.

**Comment by praneetk96** [comment]
> The solution for me was installing mpv using "sudo apt-get install mpv" which installs "mpv 0.36.0" rn.
> 
> Because the Snap store has "mpv 0.37.0" rn. I installed it from the snap store before. But whenever rotating the video using keybind the video used to get black and white. But installing using "sudo apt-get install mpv" fixed the issue for me.
> 
> If anyone is facing the same problem. Installing other released versions of mpv may fix your problem.

I am using Archlinux and the mpv in pacman repo has version 0.37.0, maybe downgrading will fix this but I am not doing it because it will surely cause problems with it's shared dependencies to other installed programs.

**Comment by radioxoma** [comment]
Disabling hardware video acceleration fixed issue. Remove or comment `hwdec=vaapi` from `/home/rx/.config/mpv/mpv.conf`.

**Comment by mexicancartel** [comment]
Now i noticed certain videos have problem in 90&270 rotation but certain others have problem in 0&180 rotation. I tried vp9 as well as h264 videos

**Comment by kasper93** [comment]
It's already fixed by https://github.com/mpv-player/mpv/pull/13619

**Comment by mdPlusPlus** [comment]
Then this is not present yet in 0.37.0-1ubuntu4
