### ISSUE TITLE
 warning: '#extension' : extension not supported: GL_ARB_shader_storage_buffer_object

### ISSUE THREAD

**Issue by shinstimulateshinstimulate** [mpv-player/mpv#6768]
### mpv version and platform

mpv 0.29.0-338-g6aecd10eba (shinchiro latest)
Windows 10 1809
GPU GTX 980M ruining driver 430.86 

### Reproduction steps
Play the sample file: https://0x0.st/zeW7.mkv
media info: https://pastebin.com/raw/DY7gMJ03
I get some warnings with  -v --no-config
[vo/gpu/d3d11] shaderc output:
[vo/gpu/d3d11] input:2: warning: '#extension' : extension not supported: GL_ARB_shader_storage_buffer_object
[vo/gpu/d3d11] shaderc compile status 'success' (0 errors, 1 warnings)

Same warnings with -v --no-config --gpu-context=winvk
[vo/gpu/vulkan/libplacebo] shaderc output:
[vo/gpu/vulkan/libplacebo] input:2: warning: '#extension' : extension not supported: GL_ARB_shader_storage_buffer_object
[vo/gpu/vulkan/libplacebo]
[vo/gpu/vulkan/libplacebo] shaderc compile status 'success' (0 errors, 1 warnings)

### Log file

Log -v --no-config: https://pastebin.com/raw/0TbFt4eD
Log -v --no-config  --gpu-context=winvk: https://pastebin.com/raw/iKKYyNCF  

### Sample files

https://0x0.st/zeW7.mkv

**Comment by bjin** [comment]
It's just warning, and those warnings are actually expected to be ignored. These `#extension` directives are meant for OpenGL only (for implementations like mesa to have extensions from future OpenGL versions enabled), and they are labelled are `enable` instead of `require`, following standard. They are expected to be ignored by old OpenGL implementation and Vulkan. If it's about annoying shaderc output, it's easy to fix it for sure.

**Comment by Akemi** [comment]
not really an issue.
