### ISSUE TITLE
timestamps in console / log

### ISSUE THREAD

**Issue by davidhq** [mpv-player/mpv#6773]
Is it possible to have timestamps (not media timestamps, just simply when the current line have been shown / written to log) in the mpv output (and log file)?

**Comment by CounterPillow** [comment]
`--log-file` adds timestamps relative to the program start by default. `--msg-time` can add time information before each console message.

np I love reading manpages for others.

**Comment by davidhq** [comment]
tried multiple times to find this in documentation but couldn't find it (tried with "time", "log" etc., obviously "timing" would do the trick).. anyway, thank you, I love when someone finds something for me

**Comment by davidhq** [comment]
There is only one problem, it doesn't do what I need.

Would someone know what is `timing information`, it looks like this:

```
[10060891] [osd/libass] Setting up fonts...
[10114304] [osd/libass] Using font provider fontconfig
[10114978] [osd/libass] Done.
```

No clue what are these numbers in brackets. I would like normal time and date.

**Comment by chuckn408** [comment]
The numbers on the left is how long the program has been running

Here is my output::
`mpv --log-file log --msg-time test.mkv `
`[10066367] Playing: test.mkv`
`[10106609]  (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)`
`[10107378]  (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)`
`libEGL warning: DRI2: failed to authenticate`
`[10707532] [vo/opengl] Suspected software renderer or indirect context.`
`[10771332] [vo/opengl] Suspected software renderer or indirect context.`
`Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory`
`[10796292] [vo/vdpau] Error when calling vdp_device_create_x11: 1`
`[10814100] [vo/xv] No Xvideo support found.`
`[11033015] [vo/sdl] Using opengl`
`[11048879] VO does not support requested hardware decoder, or loading it failed.`
`[11149454] AO: [pulse] 48000Hz stereo 2ch float`
`[11231739] VO: [sdl] 1920x1080 yuv420p`
`[14120739] AV: 00:00:02 / 00:12:25 (0%) A-V:  0.000 Dropped: 44`
`[14601098] `
`[14601459] `
`[14601695] Exiting... (Quit)`
The number in the brackets[eight digits] on the left show how long the program has been running in a format _FAR_ less than seconds ;)
You can see that on line 14, it shows time in hours,minutes,seconds[six digits] (2 second run-time in this case). The reason why the two times are different is because of my insufficient hardware to run the video/audio together in-sync.

Here's an example when using mpv to show a picture:
`mpv --log-file somelog --msg-time https://avatars3.githubusercontent.com/u/3899?s=400.png`
`[10065397] Playing: https://avatars0.githubusercontent.com/u/30214233?s=180.png`
`[15480452]  (+) Video --vid=1 (png 420x420 1.000fps)`
`libEGL warning: DRI2: failed to authenticate`
`[16120298] [vo/opengl] Suspected software renderer or indirect context.`
`[16173044] [vo/opengl] Suspected software renderer or indirect context.`
`Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory`
`[16200927] [vo/vdpau] Error when calling vdp_device_create_x11: 1`
`[16226357] [vo/xv] No Xvideo support found.`
`[16427611] [vo/sdl] Using opengl`
`[16496946] Using conversion filter.`
`[16503652] VO: [sdl] 420x420 bgra`
`[16892109] V: 00:00:00 / 00:00:00 (0%) Cache:  0s+0KB`
`[17906391] `
`[17906427] `
`[17906455] Exiting... (End of file)`
On line 13, the playback time for both is 0, but the time on the left keeps incrementing because the program itself is still running. If you need the time on the left to be in a different format, I can't readily help out with that just yet. Hope this helps.

**Comment by CounterPillow** [comment]
@chuckn408 jesus christ fix your graphics stack

**Comment by davidhq** [comment]
Hi! @chuckn408 thank you for what you've written... but it really doesn't say anything new.
Maybe it's useful because it kind of confirms the point that it's not possible to do what most logs do:

print the current timestamp -- this is very unusual - to just show time since the program is running... 

I have various issues with mpv on raspberry pi (black screens etc.) and when the problem happens, I'd like to note the time, then look in the log exactly when it happened.

With what is currently possible I cannot be sure at all if some line in log is close to when the issue happened... actually even with real timestamps it will probably be a challenge but still... I just wanted to know how to get them... if not possible, then I still wonder why is this and I should probably be helping in trying to add this feature instead of ranting here... this could happen and I could try to contribute to the project in a way but first I needed to be sure I actually understand correctly that what I need is not possible...

I also want to get a feel for the people around this project... I don't have an opinion yet but @CounterPillow 's answer was very unpleasant and I hope other contributors / users don't speak in such condescending tone especially if they don't know what they are talking about.

**Comment by CounterPillow** [comment]
lol

**Comment by haasn** [comment]
It's in microseconds

```
    if (root->show_time)
        fprintf(stream, "[%" PRId64 "] ", mp_time_us());
```

It would be a trivial change to make this behave the same way as `--log-file`, which just divides it down to seconds:

```
    fprintf(root->log_file, "[%8.3f][%c][%s] %s",
            (mp_time_us() - MP_START_TIME) / 1e6,
            mp_log_levels[lev][0],
            log->verbose_prefix, text);
```
