### ISSUE TITLE
No OSD with --gpu-context=d3d11

### ISSUE THREAD

**Issue by stumpedatwork** [mpv-player/mpv#6775]
### mpv version and platform
Git master
Windows 10 -  Built with msys2/mingw64

### Reproduction steps
mpv.exe  -v  -vo=gpu -gpu-context=d3d11   -gpu-debug -osd-level=3 test.mkv

### Expected behavior
OSD shown

### Actual behavior
OSD not shown

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/3331540/mpv.log)

### Likely cause
Pointers to out-of-scoped compound literals in  video/out/d3d11/ra_d3d11.c

**Comment by stumpedatwork** [comment]
I believe this is also responsible for some "[vo/gpu/d3d11] Failed to create Texture2D: The parameter is incorrect. (0x80070057)" errors.

**Comment by fzold** [comment]
Compile mpv with --disable-shaderc and it works.

**Comment by stumpedatwork** [comment]
> Compile mpv with --disable-shaderc and OSD is shown.

I believe disabling `shaderc` disables d3d11 support for gpu vo too.

**Comment by boodies** [comment]
I also having the no OSD bug.

[log file](https://0x0.st/z_F3.txt)

I'm doing self build with MSYS2 and following some guide line in [appveyor-install.sh](https://github.com/mpv-player/mpv/blob/master/TOOLS/appveyor-install.sh). Not sure what went wrong because everything was successfully compiled.

I didn't have this no OSD bug before, when crossc was still being used.

**Comment by rossy** [comment]
I think you're right about the out-of-scope pointers. I got the same thing building with recent MSYS2, and fixing the struct lifetime seems to solve it. Thanks for catching that.
