### ISSUE TITLE
Couldn't install mpv on my computer

### ISSUE THREAD

**Issue by Mackel123** [mpv-player/mpv#6784]
os: 
![image](https://user-images.githubusercontent.com/27003282/60434585-09534880-9c3a-11e9-99f9-844feee55d13.png)

mpv versions：
Information for package mpv:
----------------------------
Repository     : Multimedia Applications (openSUSE_Tumbleweed)
Name           : mpv                                          
Version        : 0.29.1-170.1                                 
Arch           : x86_64                                       
Vendor         : obs://build.opensuse.org/multimedia          
Installed Size : 2.2 MiB                                      
Installed      : Yes                                          
Status         : up-to-date                                   
Source package : mpv-0.29.1-170.1.src                         
Summary        : Advanced general-purpose multimedia player   
Description    :  

Problem: 
nothing provides libvapoursynth-43.so()(64bit) needed by mpv-0.29.1-170.1.x86_64
 Solution 1: do not install mpv-0.29.1-170.1.x86_64
 Solution 2: break mpv-0.29.1-170.1.x86_64 by ignoring some of its dependencies

**Comment by lachs0r** [comment]
Install mpv from the main Tumbleweed repository, not the Multimedia devel project. You should *always* assign lower priority for those repositories, and avoid them altogether if possible.

(Also, install the FFmpeg libraries from Packman to get full codec support.)

**Comment by lachs0r** [comment]
To clarify what happened here: The multimedia:apps devel project builds against the library versions from multimedia:libs, which do not necessarily match those found in Tumbleweed’s current snapshot. And since you apparently do not have multimedia:libs configured as well, installation from multimedia:apps will fail.

So yeah, I recommend either removing multimedia:apps, or adding multimedia:libs and set *both* of these repositories to a lower priority than the main OSS repo.
