### ISSUE TITLE
20190622:From this version, mpv(using a video or audio filter) sometimes freezes when seeking.

### ISSUE THREAD

**Issue by mpvtester** [mpv-player/mpv#6794]
mpv-x86_64-2019**0622**-git-c9e7473.7z (windows 10 pro 64bit)

From this version, mpv(enable the **audio equalizer**) sometimes freezes when seeking.
(other user's reports: **using a video or audio filter**)

**command:**

mpv-x86_64-2019**0707**-git-c379950.7z

mpv --af-add=lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,0);entry(125,0);entry(250,0);entry(500,0);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)'] test.mp4

**Comment by mpvtester** [comment]
other user's reports:

> It seems the problem happens when **using a video or audio filter**.

https://forum.smplayer.info/viewtopic.php?f=2&t=11793&start=10
https://github.com/shinchiro/mpv-winbuild-cmake/issues/30
https://github.com/shinchiro/mpv-winbuild-cmake/issues/28

**Comment by mpvtester** [comment]
log
https://file.io/7DPFr9

**Comment by mpvtester** [comment]
log file
https://tokaimusen.com/cabinet/?file=f0288.txt&mode=download

**Comment by Akemi** [comment]
i am not a fan of the way this issue was reported, but so be it.

**Comment by principealex1** [comment]
> i am not a fan of the way this issue was reported, but so be it.

I've done something wrong?, i'm the one who reported the issue on shinchiro repository and Smplayer Forum.

**Comment by Akemi** [comment]
no. i am talking about how this issue was reported here. we have the issue template for a reason, so reported issues have a certain 'standard', have all the informations we need in and that in a way it's easily readable. no one really likes to look at a mess.

**Comment by principealex1** [comment]
> no. i am talking about how this issue was reported here. we have the issue template for a reason, so reported issues have a certain 'standard', have all the informations we need in and that in a way it's easily readable. no one really likes to look at a mess.

ah okay!, anyway i think this is an important issue on Windows, i hope you can solve it ^^, i'm sticking with an older version for now. (20190616)

**Comment by principealex1** [comment]
@Akemi Sorry for insisting but other reports are coming (in other forums/threads), the bug really exist and the Windows version it's pratically **inusable** since the 2019/06/22 version (using a video/audio filter), i hope you are at least aware of this ^^.

I know that all should use the stable version ecc... , but i just want to make sure that you guys acknowledge the problem for a future fix.

**Comment by JonnyThree** [comment]
> 
> 
> @Akemi Sorry for insisting but other reports are coming (in other forums/threads), the bug really exist and the Windows version it's pratically **inusable** since the 2019/06/22 version (using a video/audio filter), i hope you are at least aware of this ^^.
> 
> I know that all should use the stable version ecc... , but i just want to make sure that you guys acknowledge the problem for a future fix.

yes i confirm. i have the freeze issue simply adding 
af lavfi=[volume=-5dB]

**Comment by Akemi** [comment]
dunno why you insist by mentioning me. i reopened the issue and that's about as much as i can do. this is apparently a windows problem(?), then there is nothing i can do about it since i solely do macOS things.

**Comment by qyot27** [comment]
Can't reproduce this on Windows 10 Pro 64-bit running on a J3455 and 8GB of RAM (personal build used: http://www.mediafire.com/file/9sthgs108b1o7ev/mpv_r46949.7z/file).  Software decoding or hardware decoding, no difference: seeks work, and fast (well, unless I'm seeking in a 4K backup, but that's a separate issue that specifically has to do with HEVC in MPEG-TS, and those issues also happen in ffplay, so that's definitely on libavformat's end).  No amount of seeking back and forth causes it to freeze.

What CPU, GPU are being used here?

Superficially, the fact that [in the SMPlayer thread] the 'last known good' build was 6aecd10, but broke as of c9e7473, it would point to being something concerning the compute shader error diffusion commits on June 16 (that doesn't mean it's a bug in mpv; it could be a bug or simple limitation of the graphics driver being used).  If you switch the `--vo` to something other than `gpu` - `direct3d` or `sdl`, for example - does it still happen?

**Comment by JonnyThree** [comment]
if this can be useful, i'm on win 7 x64, intel xeon e5450, radeon r9 380 with latest 19.7.2 driver, no overclocking.
my mpv relevant configuration:
vo=gpu
gpu-api=d3d11
hwdec=dxva2
interpolation=yes
video-sync=display-resample
tscale=triangle

**Comment by JonnyThree** [comment]
i've done a new test just now, after i have instelled latest amd graphic driver with differente video files by resolution and fps types, all h264, used latest windows build (git-65b1c2d).
seems to be that the freeze bug is now gone, i havent had any problem with random seeks with any video file

**Comment by principealex1** [comment]
> What CPU, GPU are being used here?

@qyot27 
CPU: Intel Celeron CPU 1007U 1.50GHz 
GPU integrated:  Intel HD Graphics

It's a low end pc, but the graphic drivers are updated to the latest version 2018/12/27 and i don't have problems even reproducing 1080p h265 videos using older versions.

> If you switch the `--vo` to something other than `gpu` - `direct3d` or `sdl`, for example - does it still happen?

Yes, same problem using a different vo. =(

**Comment by mpvtester** [comment]
**mpv_r46949.7z** is **no problem**.


> What CPU, GPU are being used here?

Intel Core i3 540

Intel HD Graphics
2012/11/26
8.15.10.2900


> If you switch the --vo to something other than gpu - direct3d or sdl, for example - does it still happen?

It happens but mpv_r46949.7z does not happen.

**mpv_r46949.7z**
gpu: error
direct3d: **no problem**
sdl(Using direct3d): **no problem**

gpu's error
[vo/gpu] The OpenGL driver does not support OpenGL 3.x
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu] The OpenGL driver does not support OpenGL 3.x
[vo/gpu/vulkan/libplacebo] Failed creating instance: VK_ERROR_INITIALIZATION_FAILED
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan instance
[vo/gpu] Failed initializing any suitable GPU context!

**mpv-x86_64-20190714-git-65b1c2d.7z**
gpu: **freeze**
direct3d: **freeze**
sdl: not found

The codec does not matter. It also happens with WMV1, VP9. (container mp4 mkv webm wmv ts)

**Comment by mpvtester** [comment]
This bug has **not** been fixed in the latest version.

mpv-x86_64-2019**0804**-git-69c93b6.7z

I have uploaded **more detailed log** files.

https://tokaimusen.com/cabinet/?file=f0289.txt&mode=download

**Comment by onomatopellan** [comment]
I just compiled latest build from @shinchiro repo but first I removed this line: https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/ffmpeg.cmake#L73

After compiling ffmpeg with w32threads I don't have more freezes and I can seek with enable audio filters again.

To confirm this you can test this build if you had any freezes:
https://www.mediafire.com/file/7w7hpcjfb2nwc1u/mpv-x86_64-20190807-git-639ee55.zip/file

**Comment by principealex1** [comment]
@onomatopellan Wow, now it works!, please notify @shinchiro about this, so he can fix it for all the future updates! :)

**Comment by onomatopellan** [comment]
@principealex1 He is noticed every time his name is mentioned. :)

Thanks for testing, this is just a workaround though, it doesn't explain why winpthreads did stop working since June 16. I suspect it was a Windows update. What exact Windows build are you running? Mine is 18362.267.

**Comment by principealex1** [comment]
@onomatopellan same, 18362.267 build (Windows 10 Home x64)

So it's something that Microsoft should fix or MPV developers?

**Comment by onomatopellan** [comment]
It's hard to say. I just tested latest mpv on my laptop (build 17763) and it also freezes so dunno what really happened.

I also tried qyot27 build which doesn't use w32threads either and it doesn't freeze. So it will be hard to know the real cause.

**Comment by shinchiro** [comment]
If that's a case, its a shame since pthreads-enabled ffmpeg is needed for streaming like udp,rtp. But, I never use those streaming features and not having any freezes, so I dont really care whether its compiled with win32thread or pthread

**Comment by onomatopellan** [comment]
@shinchiro Then I vote for win32thread. Freeze is really annoying and totally random. BTW which Linux distro are you running?

**Comment by qyot27** [comment]
As was pointed out, the actual mpv-related change at the point where the supposed failure starts to occur has to do with error diffusion in the gpu vo, and the platforms that seem to have this freezing problem have all been stated to be older (pre-Skylake-era) Intel GPU setups.

Concurrently with those changes was mpv's switch to libplacebo and dropping crossc in favor of using SPIRV directly.

The build I provided has those changes, and that's especially telling because the one report was that `--vo=gpu` was failing because it was looking for Vulkan when an Intel setup from that long ago would not have that available (similar to the problem I was encountering with Apollo Lake's HD Graphics 500 and the video being just a blue screen under certain circumstances - it had something to do with the driver reporting support for something the GPU wasn't actually capable of, or vice-versa?).

The most likely explanation, AFAICT, is that the freezing behavior is only happening in the graphics driver, on a 5+ year old Intel stack, possibly excerbated by however shaderc (and crossc, if still there) and SPIRV interact on something that old.  Unless of course some issue with winpthreads is arising from a git build of MinGW-w64, [whereas I have my cross environment set up to use point releases (and is currently using v6.0.0 because that's what was current when I built GCC 9.1.0)](https://github.com/qyot27/mpv/blob/extra-new/DOCS/crosscompile-mingw-tedious.txt).

**Comment by onomatopellan** [comment]
@qyot27 I forgot to say my GPU is a GT710 (and i5-9400F as CPU) and updating the drivers didn't help. It happens with totally different configurations.

This is the shinchiro build I'm using everywhere to test if it freezes. Just drop any video and press 'n' and 'right' keys simultaneously and repeatedly until it freezes. Seeking+enabling filters is the death combo it makes every PC I tried to freeze after a few seconds.
Please try again with this one:
https://www.mediafire.com/file/oha864gpictaz1n/mpv-x86_64-20190804-git-69c93b6.zip/file

**Comment by principealex1** [comment]
So... next @shinchiro builds are going to work on my pc? ^^

**Comment by mpvtester** [comment]
This bug has been fixed in this version. Thank you very much!
mpv-x86_64-20190810-git-639ee55.7z

**Comment by CeruleanSky** [comment]
Just to add to qyot27 and other peoples statements, my laptop is circa 2011 stuff, an intel 2nd gen (Sandy bridge) with an HD3000, and switches to a an nvidia gtx 555m. 

Had same bug and had to roll back to mpv-x86_64-20190616-git-6aecd10.7z.

Shinchiro's build of mpv-x86_64-20190810-git-639ee55.7z works for me.

**Comment by onomatopellan** [comment]
Mystery solved. It was [this commit](https://github.com/mirror/mingw-w64/commit/b2302cd60b94a6d68a0e18b3f886b82f4b7f22b7) from winpthreads. @qyot27 build didn't have freezes because the toolchain had an old version of winpthreads.
