### ISSUE TITLE
vo=libmpv performance degradation over vo=gpu on macOS  (0.29.1)

### ISSUE THREAD

**Issue by digital-pers0n** [mpv-player/mpv#6829]
### Latest mpv 0.29.1 release. Tested on three different machines, one with macOS 10.11 installed and other two with macOS 10.13

When using mpv with vo=libmpv I see a clear performance degradation.
Probably swift issue or CAOpenGLLayer. 

### Reproduction steps
Open any video with vo=libmpv and then open same video with  vo=gpu and compare cpu and gpu utilization graphs. When vo=libmpv enabled, utilization is much higher.

### Expected behavior
cpu and gpu utilization should not be higher than vo=gpu

### Actual behavior
cpu and gpu utilization is much higher than vo=gpu

### Log file
-
### Sample files
Can be reproduced with any file

**Comment by Akemi** [comment]
can't reproduce. try git master. sry you are way too vague.

**Comment by digital-pers0n** [comment]
Just check 
GPU Utilization:  140 vs 197
![Screen Shot 2019-07-28 at 12 09 33 AM](https://user-images.githubusercontent.com/16736646/61999538-201b7c80-b0cc-11e9-9cc5-0e7fb428e094.png)

Top functions: vo=gpu only C functions are on top, but when vo=libmpv is on there are additional 8 swift functions appeared
![Screen Shot 2019-07-28 at 12 08 37 AM](https://user-images.githubusercontent.com/16736646/61999541-27db2100-b0cc-11e9-8cda-fb53a8f49997.png)

**Comment by Akemi** [comment]
this won't lead to anything productive anyway, but here you go.

what kind of problem do you have? or is your sole problem those numbers? if latter, tough luck.

in the first place, your expectation is plainly wrong. libmpv will never be as performant as the gpu vo, simple as that. libmpv is basically a wrapper around vo=gpu and comes with a bit of overhead. the whole render loop is driven by the client and not by the mpv core. the old backend doesn't utilise swift, so you won't see anything swift related there. for the aforementioned reason you see additional swift calls with the libmpv and the new backend. furthermore and obvious, the layer does need more resources than the normal NSOpenGLContext. it uses an additional fbo and does some more processing for all the layer stuff.

please direct your complains to Apple.

**Comment by digital-pers0n** [comment]
It's not an Apple issue. You just shouldn't use Swift and CAOpenGLLayer. Don't turn mpv into another VLC.

I tried git version few days ago and it is eating even more resources than 0.29.1. I also noticed that CPU usage of WindowServer is much higher when playing videos with vo=libmpv enabled in comparison to vo=gpu.

I also made a quick-and-dirty objc port of VideoLayer.swift and even debug version under Xcode shows less CPU usage than optimized mpv build.

**Comment by Akemi** [comment]
yeah deprecating opengl and shitting all over it is totally not an Apple issue.

wtf has this todo with vlc? exactly nothing.
wtf is the issue with swift and CAOpenGLLayer? if there is one, again complain to Apple since they are responsible for that.

you can't compare the old gpu backend and the libmpv one at all. they use different contexts, one uses a layer, one uses libmpv etc.

your example that extracts those classes and just uses libmpv is not identical to what is within mpv and can't be compared to mpv.

to get back to more substantial things.
i checked your claim and the CPU and GPU usage on my end is basically identically. for me it seems like you are reading your instrument records wrongly. since for me your records seem quite identically too. for example look at your GPU utilisation.
gpu: min 2, avg 5, std dev 2, max 15
libmpv: min 1, avg 7,  std dev 1, max 12
libmpv has a smaller min, max and std dev value. meaning it works a lot more stable than gpu. the average is just 2% absolute value higher, which is well within what can be expected. your 140% vs 197% sum (+40% relative)(of what?) is not very conclusive. it's most likely just the +40% we see from 5% to 7% avg (100/5*7=140%)

here a simple benchmark of a 30 second sample playing. just what activity monitor gives me since Instruments won't give me proper data. both usage graphs are nearly identically. one could even argue that libmpv has a slight edge in performance over gpu.
![Screenshot 2019-08-03 at 23 07 21 2](https://user-images.githubusercontent.com/680386/62416946-5e70e880-b644-11e9-8dfe-66b3d4fb706b.png)

**Comment by digital-pers0n** [comment]
The screenshots that I posted earlier are just one of many tests I performed on three different machines. 
The problem with Swift is that it is just slow. For example, when you declare `var params: [mpv_render_param] = []`  Swift allocates and frees memory each time the  `func drawRender()` is called. This happens with every array, struct, string etc. You cannot control this.
![Screen Shot 2019-08-04 at 1 10 26 AM](https://user-images.githubusercontent.com/16736646/62417297-d6dfa580-b654-11e9-9892-3f4f048c317e.png)

Second problem with Swift is compatibility. Wouldn't it be better to just write code instead of solving various compatibility issues between different versions of Swift?

**Comment by digital-pers0n** [comment]
Here is objc version of `func drawRenderer()` and it's disassembly. No way this code is slower than Swift version. It's faster. 
![Screen Shot 2019-08-04 at 1 48 29 AM](https://user-images.githubusercontent.com/16736646/62417525-79e6ee00-b65a-11e9-829a-7e592fbd0213.png)
![Screen Shot 2019-08-04 at 1 49 14 AM](https://user-images.githubusercontent.com/16736646/62417527-82d7bf80-b65a-11e9-878f-3ffd10fdecac.png)

So why not to rewrite Windows code in C#? If this will make mpv slower, then it's Microsoft problem.

**Comment by CounterPillow** [comment]
>The screenshots that I posted earlier are just one of many tests I performed on three different machines.

Then why don't you show the actual data that proves your point? Because so far you haven't.

>Here is objc version of func `drawRenderer()` and it's disassembly. No way this code is slower than Swift version.

So not only are you not showing a profiler trace comparing speeds in a statistically significant way, you now just show us the disassembly of a Swift function with nothing to compare against. Boy you sure know things about performance, especially if you think you can determine which function runs faster on a modern pipelining CPU based on its assembly.

Apple's future development seems to mostly focus on Swift, and the move to vo=libmpv as the default on macOS was not just made for shits and giggles. Actual issues required the move, which are Apple's fault.

>So why not to rewrite Windows code in C#? If this will make mpv slower, then it's Microsoft problem.

Because Microsoft doesn't require using C# to properly interface with its APIs. Though mpv does default to using OpenGL through Angle on Windows, which is an actual performance hit in favour of compatibility, so rofl @ your example.

**Comment by Akemi** [comment]
this brings me back to one of my first questions. what is your actual problem? what actual impact does it make? all you proved so far is that there might be a theoretical performance degradation which doesn't have any significant impact on the actual render performance.

the code you mentioned could probably be improved (performance wise). if one wouldn't use a to the function local var and instead use a class var, it most likely wouldn't free it. if i understand what you describe properly and your claim is right.

there are no real problems with compatibility between swift versions, even less now with swift 5. some of the problems also apply to obj-c. also wouldn't it be just better to keep what we have instead of rewriting and porting everything back to objc? that time consuming argument is just pointless, since it goes both ways. there are various aspects that make swift programming a lot faster and less time consuming, too.

you can't compare your minimal example with mpv itself. it's not a viable and proper way to compare performance.

nothing major was rewritten in swift so far, only few parts of the windowing code were ported. mostly only new things were added. in that way the argument you try to make is basically pointless. also sure, why not rewrite parts in C#? i wouldn't mind, but it was decided against it at some point. yes, my point stands. if there is a problem with the performance of swift and your claimed swift+CAOpenGLLayer problem, then it's definitely a problem you should bring up with Apple. you said it yourself, it's nothing we could change, and no changing programming languages is not a viable 'fix'.

no idea why i need to justify my move to swift. if you are not aware, for many years now i am the sole maintainer of the macOS parts, and it was my decision to integrate swift for many reasons (not necessarily in that order):
- keeping my motivation up to go on working on mpv (i wasn't motivated to write the needed cocoa-cb/libmpv backend in obj-c)
- obj-c is just ugly in comparison
- it's NPE safe if done right
- i have more fun working with swift
- it's the future of macOS
- it's easier to work with and a lot more convenient (at least in the swift context)
- it's an easier start for beginners
- i wanted to attract new macOS devs with that move, by making it more attractive to work with
- i wanted to widen my experience
- i just wanted to do it

the move has been done and i don't think we will revert it. i won't for one and i most likely would quit maintaining mpv if i were forced to go back to obj-c now. if you want to influence the direction that mpv takes in the future, the easiest way would be to start contributing. i hope this won't start some hostile move via PRs to overtake the macOS parts by pointlessly porting the swift parts back to obj-c. i also decided to start porting various things to swift now, nice we got a stable ABI now and various things majorly improved. that being said i won't and don't want to accept any new obj-c code anymore (beside fixes).

**Comment by CounterPillow** [comment]
Also just to thoroughly bury this dead cat: an alloc inside the `drawRenderer` function is obviously not going to increase GPU load, because:

1. it runs on the CPU,
2. GPU and CPU run asynchronously so the CPU side being allegedly slower does not impact the GPU side of things at all if the GPU still has work to do and you're not syncing (which would be slow).

**Comment by Argon-** [comment]
I can't agree with the perceived performance degradation through usage of swift/libmpv at all. To the contrary, some features work reliably only because of this transition/change and today's mpv has better integration and feature support on macOS than it ever had.

However, fortunately this is open source software. If you feel like a pure Objective-C-based macOS backend delivers better performance and/or support, then you are free to contribute an implementation. I'm very certain nobody would oppose such a contribution. Windows has multiple back-ends to choose from as well.

**Comment by digital-pers0n** [comment]
Here are some tests on different hardware:

Ivy Bridge cpu, intel hd4000 gpu
Normal 24fps video: when vo=gpu is enabled, OpenGL Driver Monitor doesn't even detect gpu utilization because it's less than 1%, but nothing like this could be said about vo=libmpv. `time `command from `csh` shows average cpu load 7.1% vs 5.4%
![Screen Shot 2019-08-17 at 14 24 19](https://user-images.githubusercontent.com/16736646/63216914-b845d800-c145-11e9-98bf-a1fd38d377f5.png)

60fps video: cpu load 10.2% vs 8.6%. gpu usage is higher then vo=libmpv 
![Screen Shot 2019-08-17 at 14 30 22](https://user-images.githubusercontent.com/16736646/63216927-08bd3580-c146-11e9-8762-775bbfec7b35.png)

Core2Duo cpu, nvidia gt2xx gpu. Activity Monitor doesn't have GPU window under El Capitan.

24fps video: 15.7% vs 13.7%, gpu usage is slightly higher when vo=libmpv enabled
![Screen Shot 2019-08-17 at 16 07 52](https://user-images.githubusercontent.com/16736646/63216997-090a0080-c147-11e9-86b9-3c028bc1daf9.png)

60fps video: 22.8% vs 20.6%. vo=libmpv gpu usage is terrible
![Screen Shot 2019-08-17 at 16 19 50](https://user-images.githubusercontent.com/16736646/63217020-669e4d00-c147-11e9-9e92-9a1f88fe78dd.png)

CoffeeLake cpu, Intel uhd6xx gpu

24fps video: cpu load almost same 6.2% vs 5.5%, like in the ivy bridge test, vo=gpu here has almost 0% gpu utilization.
![Screen Shot 2019-08-17 at 11 14 27 PM](https://user-images.githubusercontent.com/16736646/63217078-31dec580-c148-11e9-8736-8d990144b5d7.png)

60fps video: 10.8% vs 8.3%. gpu utilization under vo=libmpv is again higher than vo=gpu.
![Screen Shot 2019-08-17 at 10 31 24 PM](https://user-images.githubusercontent.com/16736646/63217125-fb557a80-c148-11e9-8ecc-1dd602a1ae87.png)

My proposal is not to deprecate  and remove vo=gpu in the future releases, because vo=libmpv is not a good replacement.

**Comment by Akemi** [comment]
i am not going to repeat myself. you got your answers and the reasons behind. please don't waste my time with pointless proposal and comparisons.

no one intends to remove vo=gpu. i have no idea where you got that idea from? it's only the cocoa backend for vo=gpu that is (rightfully) deprecated. it stays deprecated, because it's a broken piece of shit and none intends to work on it. it only works somewhat okayish because i had to put a lot of work into fixing it, by removing crucial parts, and in the end it still has lot of inherent bugs that can't be fixed. 

if you are fine with vo=gpu, that's good for you and none is going to take it away from you (besides Apple someday in the future by removing OpenGL). you might be one of the few people that don't have issues with it or just don't want to see them.

**Comment by wm4** [comment]
@digital-pers0n are you just trying to argue that Swift is a shitty and inefficient language? Knowing Apple, that is probably true, but just a slightly less efficient function that calls the C renderer won't make a dent. This happens only once per frame, which is pretty rare (16ms are an eternity for a computer). We could write this shit even in Python, and nobody would notice.

The main difference between the vo_gpu cocoa backend and the swift one is how the render loop is driven and what cocoa classes (or whatever that objective-c garbage calls it) are used to manage the GL context and the window. We suspect that the idiot Apple "engineers" de-optimized OpenGL in various places, and somehow the approach the swift backend takes (which is also the recommended one by Apple) works better.

I think it has been confirmed many times that the swift backend is more efficient for those reasons, and it's the only reason why we have the swift backend at all. (Though truth to be spoken, Apple will probably deprecate or otherwise bully objective-c into a second class citizen, and soon you'll have to use swift to write Apple GUI software.)

It might be that it's the reverse for you, but you haven't really provided any of the requested information or otherwise useful information.

**Comment by Akemi** [comment]
some more information on this matter. the google chrome devs had similar problems and investigated. conclusion is basically, CAOpenGLLayer is the most inefficient but the most robust way of rendering. it has the least bugs and is the Apple recommended way. there is nothing one can do about that, they asked Apple and either didn't get an answer they just confirmed it. basically it's Apple's fault. NSOpenGLView (the old cocoa backend) has a lot of bugs that can't be worked around and shouldn't be used, the layer backed equivalent is a bit better. this shouldn't be used. what chromium currently does is using an IOSurface to draw into and bind that one to a CALayer (i believe).

we could do the latter to, that would need quite a bit of effort and i don't think it is worth it now since opengl is deprecated anyway.

https://docs.google.com/document/d/1IuQTfvkRezx4hH_hXPp-EKa6sI_ipw7bj07qI4CKeWA/view#
https://docs.google.com/document/d/19YX5WYnpJj-h9nMM4r5WwlGOT99OQ7aEAm2DhWl-Ltg/edit#

**Comment by wm4** [comment]
Thanks. Do you know the Metal situation? I'm kind of interested in that (and hoping we can get rid of the inverted render loop).

**Comment by Akemi** [comment]
i can't say anything about first hand experience yet, but metal should get all the improvements of the layer based rendering (since it uses a layer too) and is on the other hand not pull API like the CAOpenGLLayer and instead a push API like the old cocoa backend (and all the other backends). with that being said it shouldn't be a problem to integrate it with our normal approach within mpv and it should also get rid of the overhead of the CAOpenGLLayer.

**Comment by linxucc** [comment]
LOL on 0.34.1 and Big Sur 11.6.4, my experiment now shows the opposite, `vo=gpu` actually uses more GPU resources than `vo=libmpv` (default)... The CPU is almost the same but just slightly higher on "vo=libmpv", very interesting... not like just a wrapper... 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/24445006/176380599-c30765fc-8ff0-4735-bcd5-1c394f4af227.png">

Seems things are either improving or somehow something changed... 
But all I can feel is with the `vo=gpu` you lose the ability to double click the image to toggle full screen, so I'll stick with the default for convenience reasons.
