### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by retokromer** [mpv-player/mpv#6855]
The current release [`0.29.1`](https://github.com/mpv-player/mpv/releases/tag/v0.29.1) from 2<sup>nd</sup> of October 2018 is 369 commits behind the master.

**Comment by CounterPillow** [comment]
ok

**Comment by robertleeblairjr** [comment]
> The current release [`0.29.1`](https://github.com/mpv-player/mpv/releases/tag/v0.29.1) from 2nd of October 2018 is 369 commits behind the master.

After finishing up on the PR for homebrew, I came here to do just this. Thanks.

**Comment by CounterPillow** [comment]
There are outstanding issues that prevent a 0.30 release right now, like the removal of the stream cache probably needing to be undone, so no there's no point making a new release just because there have been 369 commits when people will then complain about the effects of not having a stream cache for the next 5 years or however long it takes before various distros stop using a specific version of mpv.

**Comment by robertleeblairjr** [comment]
> There are outstanding issues that prevent a 0.30 release right now, like the removal of the stream cache probably needing to be undone, so no there's no point making a new release just because there have been 369 commits when people will then complain about the effects of not having a stream cache for the next 5 years or however long it takes before various distros stop using a specific version of mpv.

Isn't that what revisions are for? What's to stop there being another revisions, such as 0.29.2, that could bring the source archive releases closer to master? It said on your Releases page that a new archive would be supplied every 1-2 months.

**Comment by CounterPillow** [comment]
>Isn't that what revisions are for? What's to stop there being another revisions, such as 0.29.2, that could bring the source archive releases closer to master?

Shitty ass distributions who will ignore upstream advice at all cost, and simply ship the older version and not the point release. Also, major changes like that aren't really point release sort of stuff.

If you want the latest, just use git master. As the release policy document states:

>The goal of releases is to provide Linux distributions with something to package. If you want the newest features, just use the master branch. We try our best to keep it deployable at all times.

**Comment by robertleeblairjr** [comment]
> > Isn't that what revisions are for? What's to stop there being another revisions, such as 0.29.2, that could bring the source archive releases closer to master?
> 
> Shitty ass distributions who will ignore upstream advice at all cost, and simply ship the older version and not the point release. Also, major changes like that aren't really point release sort of stuff.
> 
> If you want the latest, just use git master. As the release policy document states:
> 
> > The goal of releases is to provide Linux distributions with something to package. If you want the newest features, just use the master branch. We try our best to keep it deployable at all times.

I understand the frustration. I was just going off of the Release Cycle Document, which I did read that Linux distributions are priority over other OS. I have no idea how much has changed in all of these commits and whether it warrants a major release or minor. So, if it's not possible or the issue won't be resolved because now the snapshot release cycle is undetermined then at least it's expected. Could you change your policy that snapshots are no longer going to be updated at regular intervals or at the request of issues filed?
