### ISSUE TITLE
Is it possible to change Mpv's icon without rebuilding?

### ISSUE THREAD

**Issue by steamu93** [mpv-player/mpv#6874]
Hi everyone.

I'm pretty satisfied with the amazing MPV and I do appreciate it. Just as a request, I wish there was a chance to change the icon manually, as the other apps often let us do it.

So please implement it in you next releases, to be able to change the icon without having to rebuild. I'm sure everyone likes the feature!

Thank you.

**Comment by Akemi** [comment]
this is highly platform dependent. you should at least have taken your time to fill out the issue template partially.

**Comment by steamu93** [comment]
> this is highly platform dependent. you should at least have taken your time to fill out the issue template partially.

Oh Sorry. I've forgotten to mention the platform.

mpv 0.29.1 on macOS 10.12.6

Actually I tried to change icon file (/Applications/mpv.app/Contents/Resources/icon.icns) but unlike the other apps sadly it wasn't respected by MPV.

**Comment by Akemi** [comment]
you don't even need to change it there you can just copy paste the desired icon in the file info. like on [any other macOS app](https://9to5mac.com/2019/01/17/change-mac-icons/). though  this will only work for the app bundle and only before launching the app, since mpv changes the app icon internally again for the command line usage.

so no for macOS it's not completely possible (yet). it's most likely not much work to change that behaviour.

**Comment by steamu93** [comment]
> you don't even need to change it there you can just copy paste the desired icon in the file info. like on [any other macOS app](https://9to5mac.com/2019/01/17/change-mac-icons/). though this will only work for the app bundle and only before launching the app, since mpv changes the app icon internally again for the command line usage.
> 
> so no for macOS it's not completely possible (yet). it's most likely not much work to change that behaviour.

Thank you for the knowledge/information, dear @あけみ. 
Hopefully as you mentioned, it possibly won't take much of you and the other dev's time to be implemented!

Keep on the great job! 👍🏼
Counting days to see it under the changelog!😄
