### ISSUE TITLE
Windows console version floods console with embedded font errors

### ISSUE THREAD

**Issue by bpsib** [mpv-player/mpv#6909]
I get lots of error messages about no charmap autodetected and embedded fonts when playing audio files from the console.

### mpv version and platform
0.29.1 Windows 10

### Reproduction steps
Use mpv.com to play any MP3 audio file. E.g.
`mpv.com audio.mp3`

### Expected behavior
File plays without any excessive errors

### Actual behavior
Console is flooded with error messages
```
Playing: audio.mp3
[osd/libass] No charmap autodetected, trying the first one
[osd/libass] Error getting metadata for embedded font '8514fix.fon'
[osd/libass] No charmap autodetected, trying the first one
[osd/libass] Error getting metadata for embedded font '8514fixe.fon'
[osd/libass] No charmap autodetected, trying the first one
[osd/libass] Error getting metadata for embedded font '8514fixg.fon'
[osd/libass] No charmap autodetected, trying the first one
...
```
and so on. Then it plays. There's over 1000 lines of these error messages.

### Log file
https://0x0.st/zJP2.txt

**Comment by garoto** [comment]
Move your `mpv` binaries and its `.confs` out of the `C:\Windows\` dir and put them somewhere else, preferably in its own directory which you can then add to your `%PATH%` env. var.

**Comment by CounterPillow** [comment]
The problem here is that you put mpv inside `C:\Windows` (why did you do that?) so now mpv is trying to read `C:\Windows\fonts\` for fonts you wish to use for subtitles, as it tries to read the "fonts" directory next to the mpv.exe; however, the `C:\Windows\fonts\` directory is filled with font files that mpv doesn't support. Hence, it throws errors for each font in there it doesn't understand.

The solution here is to not put mpv inside `C:\Windows`. If you need it in your `%PATH%`, modify your `%PATH%` variable.

**Comment by garoto** [comment]
> you put mpv inside `C:\Windows` (why did you do that?)

My guess is because `<driveletter>:\Windows` is part of the `%PATH%` by default on all installations. It's an old Windows trope to tell people to drop executables inside there to this day.
