### ISSUE TITLE
Vsync Jitter is always zero.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6924]
### mpv version and platform
```
mpv 0.29.0-385-g6e6ec33168 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.35.100
   libavcodec      58.56.101
   libavformat     58.32.104
   libswscale      5.6.100
   libavfilter     7.58.102
   libswresample   3.6.100
ffmpeg version: N-94826-g558265d4bc
```
### Reproduction steps
Shift+I to see the Vsync Jitter.
### Expected behavior
Display the actual value.
### Actual behavior
It is always zero.
### Log file
https://0x0.st/zJUP.txt
![2019-09-11 10-01-59 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/64662595-96f1b680-d47b-11e9-89ed-663955ff2236.png)

**Comment by aufkrawall** [comment]
Doesn't it temporarily increase when you do seeking, window resizing etc.?
I suppose it is due to new Mesa OML sync for EGL:
https://github.com/mpv-player/mpv/commit/10a1b9808253dc67e19db2a0c4c360788b9e668e
Seems to be more robust than before regarding mistimed frames, so perhaps there is some truth to the lower jitter (not sure if constant 0 is realistic though).

**Comment by laichiaheng** [comment]
Yes, it increases when I'm seeking or resizing window.

**Comment by xantoz** [comment]
This is not a bug. This is expected behavior since presentation feedback was implemented.
Maybe we ought to increase the amount of significant digits in stats.lua though?
