### ISSUE TITLE
Changing 'video-aspect' doesn't take effect when displaying an external-file 

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#6946]
### mpv version and platform

```
mpv 0.29.0-413-ga416b3f084 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Sep 15 12:58:51 CEST 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1
```

### Reproduction steps

`mpv --no-config some_audio_file  --external-file some_image --vid=1`
Then, during playback, change the `video-aspect` property, for example using `a set video-aspect 5` in input.conf

### Expected behavior

The aspect ratio of the image changes immediately.

### Actual behavior

The ratio of the image being displayed does not change. However, if you seek to the beginning of the audio file, the aspect ratio change is applied.

If instead, the `video-zoom` property is changed, the effect is applied immediately.

### Log file

https://0x0.st/zyEb.txt

**Comment by wm4** [comment]
This happens because an image is treated like a video with 1 frame at the beginning. Generally, reacting to changes to properties like video-aspect requires decoding a new video frame.
If you change video-aspect in the middle of playback, and the next video frame doesn't come "soon" enough (like in this case), it issues a seek to the current time. But this seek doesn't get a new video frame, so nothing happens. Unless you do it at the start (or explicitly seek to the start).
The seek we're talking about is just like a normal hr-seek. This seek will skip any video frames that come before the seek target time (so the only video frame gets dropped). I'm wondering whether it should keep the last video frame, but currently that would probably force audio to be decoded from the start again, or something similarly weird. Could also cause other inconsistencies and strange behavior.
So I'm inclined to make this a wontfix for now, since it requires tricky changes for an obscure corner case.

**Comment by occivink** [comment]
>So I'm inclined to make this a wontfix for now, since it requires tricky changes for an obscure corner case.

I'd also be happy with a workaround (that doesn't require interrupting the audio ideally) if you have one. I tried various things (reloading the `external-file`, the `tpad` filter...) but nothing worked well.

**Comment by occivink** [comment]
For completeness' sake and to avoid an XY situation, I'm trying to reposition dynamically the video so that it sits at {x,y} with size {w,h}. I'm currently doing it with this snippet
```
    local ratio = w / h
    local zoom = math.log(w / window_width) / math.log(2)
    local dist_y = y - (window_height - h) / 2
    local pan_y = dist_y / h
    local dist_x = x - (window_width - w) / 2
    local pan_x = dist_x / w
    mp.set_property_number("video-aspect", ratio)
    mp.set_property_number("video-zoom", zoom)
    mp.set_property_number("video-pan-y", pan_y)
    mp.set_property_number("video-pan-x", pan_x)
```
which is run anytime the window size changes. It works ok, except for the video-aspect part which makes the audio choppy (due to the seek you mentioned I presume), and of course because it is not applied right away.
I've tried using video filters to scale/pad, it works but it's not ideal either because of the filter reconfiguration that happens during window resize.

Finally, the reason why I'm doing this in the first place is for a silly-ish music player script, it's how I reposition the waveform.
![sshot](https://user-images.githubusercontent.com/5473453/65360348-dea4da80-dbff-11e9-92de-ccc5b458fad0.jpg)

**Comment by wm4** [comment]
Not sure how that works. That looks like a GUI, what is mpv's part in that?

For explicit positioning, a direct option would probably be better.

**Comment by occivink** [comment]
It's a lua script actually, although very much WIP

**Comment by wm4** [comment]
Looked at it again, and after a few hours, I was able to come up with some simple changes that fix this.

However, it's still done as a seek, and will interrupt audio, which is probably not what you want. This can't be fixed for now. Ways around: control how video us shown differently and only with options that work on the VO level, or add an "output" aspect ratio option, or use that old RGBA overlay API to show a static image that isn't so static.
