### ISSUE TITLE
All selected files paly at once

### ISSUE THREAD

**Issue by JunaidQadirB** [mpv-player/mpv#6982]
### mpv version and platform
0.29.1-1ubuntu1 on Ubuntu 19.04 (Latest release)

### Reproduction steps
1- Select more than one video
2- Right CLick on them and click `Open With Other Application`
3- Select `mpv Media Player`

### Expected behavior
Videos should enqueue and play one by one in a single instance.

### Actual behavior
An `mpv` instance is started for each selected video and all play at once.

### Log file
Not Applicable

### Sample files
Not Applicable

**Comment by Argon-** [comment]
Doesn't that depend on what your file manager is doing? `mpv` works just as you want when you supply all selected files as arguments. On macOS, selecting multiple files graphically and opening them in mpv does what you want.
I assume your file manager starts mpv for each file which I'd call an error on his behalf.

You can use this as a workaround: https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv

**Comment by CounterPillow** [comment]
We follow the [XDG .desktop file spec which tells us](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables) to use `%U` as a field code to signal to any caller that we support taking multiple files or URLs as input arguments. [We actually do use this](https://github.com/mpv-player/mpv/blob/master/etc/mpv.desktop#L32). The reason why it's not working for you is either because your file manager does not follow the XDG spec, or because the way you made it launch mpv ignores the .desktop file and simply launches mpv as a terminal command.
