### ISSUE TITLE
meta: tag/milestone 0.30.0 release

### ISSUE THREAD

**Issue by smarek** [mpv-player/mpv#7018]
meta issue, could you please mark issues that are from maintainer point of view required to proceed with next major release?

either through labeling said issues meta:next or with creating milestone for the 0.30.0 release and assigning issues to it.

thank you

**Comment by wm4** [comment]
That's a good idea. I'm still worried about dumb OSX issues, since Apple keeps breaking our shit.
Fuck Apple.

**Comment by Akemi** [comment]
added a new label `meta:next-release`. i only have one thing to add for the next #7006.

if milestones are preferred we can create those instead.

**Comment by smarek** [comment]
Well, you can use meta:next-release for tickets accepted in the pipeline for next releases, and milestones to distinguish which of the release it is planned into.

If the tag is not named with specific release number or branch, it would be better to use milestones or combination of both.

I can imagine that not all meta:next-release tagged issues are meant to be blocking for next immediate release, and in that situation it could be bit confusing.

Also best would be to provide explanative description of the label, as soon as you decide on the management flow.

**Comment by Akemi** [comment]
what the past showed us, the smaller the managerial work the better. no one was really up to the task. i am not going to trouble myself with managing such things for the sake of a release. even less so, since i think other things are more important. maybe actually making a release.

i am of the opinion to keep it as simple as possible, with as small of a workload as possible. we should just use that tag as a blocking tag for the next immediate release.

**Comment by smarek** [comment]
Cool, then it's decided how the management works and tag will be used as blocking for next release only. I'm closing this ticket, as it served its purpose in my opinion. Thank you!

**Comment by Akemi** [comment]
i added a description to the tag for now.
