### ISSUE TITLE
libmpv failed to play fragmented mp4 files if load them manually

### ISSUE THREAD

**Issue by hanguofu** [mpv-player/mpv#7032]
### mpv version and platform
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
ffmpeg version: 4.1.3-0ubuntu1

platform : Ubuntu 19.04

### Reproduction steps
I modified libmpv/example/simple.c as follows   :

const char *cmd[] = {"loadfile", "/home/hanguofu/frag_98nai/wo_keyframe_init.mp4", NULL};
const char *cmd2[] = {"loadfile", "/home/hanguofu/frag_98nai/wo_keyframe_1.m4s", "append" , NULL };
const char *cmd3[] = {"loadfile", "/home/hanguofu/frag_98nai/wo_keyframe_2.m4s", "append"  , NULL  };

     check_error(mpv_command(ctx, cmd));
     check_error(mpv_command(ctx, cmd2));
     check_error(mpv_command(ctx, cmd3));

    // Let it play, and wait until the user quits.
    while (1) {
          // hereby , feed libmpv with the rest segments every 15 seconds.
          // ...
          // ...
        if (event->event_id == MPV_EVENT_SHUTDOWN)
            break;
    }

    mpv_terminate_destroy(ctx);
    return 0;

### Expected behavior
libmpv play them one by one.
### Actual behavior
None of them  is played . No gui windows at all.
### Log file

https://0x0.st/zwL7.txt

### Sample files

Not avail. 

The reason I did not put all these m4s files into a mpd file is because mpv fetch these segments in a rush if so , which put heavy load at my media server. And I donot know how to slow it down. Of couse , mpv plays all of them smoothly if I put them into a mpd file. For this reason , I modified libmpv/sample/simple.c to feed libmpv with these m4s files at a constant interval. However , libmpv failed to play any of them.

**Comment by Akemi** [comment]
to me the log looks like it tries to init various opengl and vulkan backends but either can't properly or fails completely. hence why i doesn't output anything. my guess is it doesn't do it because you are trying it in a VM. probably need to force an output/backend/context so it doesn't try probing more backends on detected software renderer.

```
[   0.123][v][vo/gpu] Probing for best GPU context.
[   0.123][v][vo/gpu/opengl] Initializing GPU context 'wayland'
[   0.123][v][vo/gpu/opengl] Initializing GPU context 'x11probe'
...
[   1.669][v][vo/gpu/x11] Error code: a7, request code: 97, minor code: 22
[   1.670][v][vo/gpu/opengl] Creating OpenGL 4.3 context...
...
[   1.671][v][vo/gpu/x11] Error code: a7, request code: 97, minor code: 22
[   1.671][v][vo/gpu/opengl] Creating OpenGL 4.0 context...
...
[   1.673][v][vo/gpu/x11] Error code: a7, request code: 97, minor code: 22
[   1.673][v][vo/gpu/opengl] Creating OpenGL 3.3 context...
...
[   1.714][v][vo/gpu] Detected suspected software renderer.
[   1.715][w][vo/gpu/opengl] Suspected software renderer or indirect context.
[   1.717][v][vo/gpu/x11] uninit ...
[   1.722][v][vo/gpu/opengl] Initializing GPU context 'x11egl'
...
[   1.890][v][vo/gpu/opengl] GL_VERSION='3.3 (Core Profile) Mesa 19.0.8'
[   1.890][v][vo/gpu/opengl] Detected desktop OpenGL 3.3.
...
[   1.891][v][vo/gpu/opengl] Detected suspected software renderer.
[   1.892][w][vo/gpu/opengl] Suspected software renderer or indirect context.
[   1.893][v][vo/gpu/x11] uninit ...
[   1.894][v][vo/gpu/opengl] Initializing GPU context 'x11'
..
[   1.940][v][vo/gpu/opengl] Creating OpenGL 4.4 context...
[   1.941][v][vo/gpu/x11] X11 error: GLXBadFBConfig
...
[   1.941][v][vo/gpu/x11] Error code: a7, request code: 97, minor code: 22
[   1.941][v][vo/gpu/opengl] Creating OpenGL 4.3 context...
[   1.943][v][vo/gpu/x11] X11 error: GLXBadFBConfig
...
[   1.943][v][vo/gpu/x11] Error code: a7, request code: 97, minor code: 22
[   1.943][v][vo/gpu/opengl] Creating OpenGL 4.0 context...
[   1.944][v][vo/gpu/x11] X11 error: GLXBadFBConfig
...
[   1.944][v][vo/gpu/opengl] Creating OpenGL 3.3 context...
[   1.958][v][vo/gpu] GL_VERSION='3.3 (Core Profile) Mesa 19.0.8'
...
[   1.960][v][vo/gpu] Detected suspected software renderer.
[   1.960][w][vo/gpu/opengl] Suspected software renderer or indirect context.
[   1.962][v][vo/gpu/x11] uninit ...
[   1.964][v][vo/gpu/opengl] Initializing GPU context 'drm'
..
[   1.964][v][vo/gpu/opengl] Initializing GPU context 'vdpauglx'
[   1.964][v][vo/gpu/vulkan] Initializing GPU context 'waylandvk'
..
[   1.965][v][vo/gpu/vulkan] Failed creating instance: VK_ERROR_EXTENSION_NOT_PRESENT
[   1.965][v][vo/gpu/vulkan] Initializing GPU context 'x11vk'
..
[   1.966][v][vo/gpu/vulkan] Failed creating instance: VK_ERROR_EXTENSION_NOT_PRESENT
..
[   1.991][e][vo/vdpau] Error when calling vdp_device_create_x11: 1
[   1.992][v][vo/vdpau/x11] uninit ...
[   1.997][v][vo/xv/x11] X11 opening display: :0.0
...
[   2.015][e][vo/xv] No Xvideo support found.
[   2.015][v][vo/xv/x11] uninit ...
```

**Comment by hanguofu** [comment]
Thanks for your tip. Could you please shed some light on how to assign a renderer in libmpv ? Enclose pleasea find the mpv Media Play ( intergrated in armbian desktop env. ) log file for playing the mpd file.

https://0x0.st/zw91.txt

Besides , I run the generated libmpv program and mpv Media Player at the same tv box at armbian OS.

**Comment by wm4** [comment]
In the first log I only see:
```
[   0.078][v][file] Opening /home/hanguofu/frag_98nai/wo_keyframe_init.mp4
```
This seems to not contain any video frames (nothing is decoded but the decoder doesn't complain either). Just from the context I'd guess this is a DASH init fragment, which indeed contains no video frames, only headers.

I guess this all about DASH support.

Regarding loading fragments "manually", that obviously won't work. The fragment files typically don't have a header. And running through playback init/deinit overhead for every frame would probably not result in smooth playback anyway.

You could try the EDL DASH support, but then you're on your own. It's not officially supported by us (it's an internal hack), could be removed any time, requires you to manually convert the "manifest", and doesn't support live streams.

Another possibility to emulate DASH is concatenating all files in order (init fragment first). You could even emulate live DASH by going through a pipe or stream_cb. This is also what you can achieve with streamlink. (I actually use this for HLS sometimes, because FFmpeg's implementation is just bad.)

Regarding FFmpeg's native DASH support, this was copy-pasted from its HLS demuxer, has all the same problems, plus a larger number of bugs that broke playback or even crashed inside the ffmpeg libs. Some of these have been fixed, but I guess you shouldn't expect much from it. The log in your previous post hints that either the stream you're playing is broken, or that you found another bug in ffmpeg's DASH demuxer.

I think ideally, mpv would have native HLS/DASH support, but don't hold your breath.

**Comment by hanguofu** [comment]
Let me get it straight , I am looking for a DASH  player which can meet all of the following requirements :
1. decoder pipeline and display unit are resumable . When running out of segments , the decoder pipeline can stop at the last element and resume to decode when new segment comes. The display unit should keep looping the last frame when the frame buffer are not updated  and going on with the new frames when decoder returns to work.

2. the fetch unit ( ytdl ? ) understand http responses instead of simply assume the needed file/segment are not available when server response sth. other than 200/206.
For example , when mpv open a mpd file which contains statements such as "http://1.2.3.4/mp4" , it fetch the file from the server . However , 
the server response with http 429 with Retry-After header , the fetch unit should interpret it correctly.

Is there such a thing please ?


Regards !

**Comment by wm4** [comment]
vlc? Uh well, if you find something truly well working, let us know, and we can integrate it in mpv. Personally I'd probably offer implementing good DASH support in mpv for some compensation, but since I'm not interested in money (even if someone offered some), it probably won't happen.

**Comment by wm4** [comment]
Well, I can't tell what you're trying to do. Playing DASH files that were already downloaded to a filesystem? Playing DASH segments as individual files is inefficient or doesn't work, as I already described. I offered some solutions.

In any case, I don't see anything actionable here, so I'm closing this. I created #7033 to track anything related to improving HLS/DASH in mpv.
