### ISSUE TITLE
unable to play .jpg file on raspberrypi

### ISSUE THREAD

**Issue by fitipe** [mpv-player/mpv#7040]
### mpv version and platform

- sept 2018

### Reproduction steps

I'm running a python program that generates codes to be interpreted by mpv. 

It writes lines like this one and send them to the terminal:

mpv    --fs --no-border --vo=rpi --hwdec=rpi  --{  --video-zoom=2.0493261744338644 --image-display-duration=4.221882650516774 --video-pan-y=0.030067219418309477 --video-pan-x=-0.0937035489735291 1.jpg --}

When I run it on windows10 (without the vo=rpi and hwdec=rpi) everything goes fine. But I need it to be run on a raspberrypi 3B and, when I try, I just keep getting the same error:

Playing: 1.jpg
 (+) Video --vid=1 (mjpeg 1.000fps)
[autoconvert] Converting yuv444p -> yuv420p
VO: [rpi] 3520x2688 yuv420p
mmal: mmal_vc_port_enable: failed to enable port vc.ril.video_render:in:0(I420): ENOMEM
mmal: mmal_port_enable: failed to enable port vc.ril.video_render:in:0(I420)(0x702036d0) (ENOMEM)
Could not initialize video chain.
mmal: mmal_port_disable: port vc.ril.video_render:in:0(I420)(0x702036d0) is not enabled
Video: no video
: 00:00:00 / 00:00:01 (0%)

### Log file

sorry, couldn't figure out how to use this 0x0.st ...

**Comment by LaserEyess** [comment]
First, read this https://github.com/mpv-player/mpv/wiki/FAQ#video-on-rpi-doesnt-work-or-is-too-slow

Second, why are you trying to use hardware decoding for a jpg? remove `--vo=rpi` and `--hwdec=rpi`

**Comment by fitipe** [comment]
hi @LaserEyess, thanks a lot for replying!

yes, I've read that before posting here and also added the "gpu_mem" to the /boot/config.txt, as mentioned in the end of the topic you sent me.

I also tried to remove both --vo=rpi and --hwdec=rpi and it keeps giving me the same error ...

**Comment by LaserEyess** [comment]
Most likely the raspi's GPU doesn't support images of that size. To be clear: the raspberry pi is a shit device for multimedia and you're trying to get it to render >4k images so you will have issues, period. Scale it down and it might work. Otherwise, your error is very explicit: `ENOMEM` is "Error, no memory", you do not have enough memory for what you're trying to do. Either that means you (did not properly assign gpu_mem)[https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md] in your /boot/config.txt, or it means that it can't allocate a buffer that large.

If neither of those things works post a log file, because no one can help you without that.

**Comment by wm4** [comment]
Even desktop CPUs have texture size limits that sometimes make it impossible to view images.

You could use --vo=x11 to work this around, or insert an explicit scale filter (see ffmpeg libavfilter documentation).

**Comment by fitipe** [comment]
thanks a lot, @LaserEyess  and @wm4  ->  both solutions worked!

@LaserEyess - I know I'm using a very cheap hardware, but it's been surprising me frequently. About the log file ... I'm sorry, but I really couldn't figure out how to upload it to the "0x0.st" webpage.
