### ISSUE TITLE
bilinear scale on dxva2 doesn't seem to work

### ISSUE THREAD

**Issue by blackarcher21** [mpv-player/mpv#7042]
### mpv version and platform

mpv 0.29.0-811-g2b19a7c964 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Oct  6 10:13:45 +08 2019
ffmpeg library versions:
   libavutil       56.35.100
   libavcodec      58.59.101
   libavformat     58.33.100
   libswscale      5.6.100
   libavfilter     7.61.100
   libswresample   3.6.100
ffmpeg version: git-2019-10-05-3b4e9a31

### Reproduction steps
mpv -no-config -hwdec=dxva2 -scale=bilinear
playing 360p video, go to fullscreen
my screen resolution 1366x768

### Expected behavior
![mpv-shot0001](https://user-images.githubusercontent.com/15969210/66453942-b25eda00-ea98-11e9-8c35-0726f97a04ab.jpg)
scaled with image editor with bilinear, give output like this
![mpv-shot0003](https://user-images.githubusercontent.com/15969210/66453971-d02c3f00-ea98-11e9-83c8-dae0251e363e.jpg)
so output from mpv should be quite like this
I don't understand difference between image resample and video upsampling, but at least just tried again with other player like MPC-HC with bilinear, pixel block not really noticable here compared to mpv.

### Actual behavior
![mpv-shot0002](https://user-images.githubusercontent.com/15969210/66454018-f356ee80-ea98-11e9-8d78-a66db8635f9a.jpg)

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/3705687/log.txt)

### Sample files
https://www60.zippyshare.com/v/2BzqkuDN/file.html

**Comment by blackarcher21** [comment]
My notebook with that GPU is able to play hevc 10bit content with hw acceleration dxva2 but not d3d11va.

**Comment by avih** [comment]
I'm not sure, but I _think_ it used to work correctly. It also looks like nearest neighbor without setting explicit `--scale=...`.

However, when using `dxva2-copy` then it _looks_ like bilinear.

**Comment by rossy** [comment]
> I'm not sure, but I _think_ it used to work correctly.

Yeah, this is weirding me out. It looks broken in the original dxva2dxgi commit, and I don't see anything that could have broken it since then, but it's hard to believe it's been broken this whole time, especially since ``--scale=bilinear`` is the default.

Thanks again for the report, @blackarcher21. I had no idea people were using hardware where dxva2 was preferable to d3d11va. Just to clarify, does d3d11va not work because it doesn't support 10-bit HEVC, or because it's too slow for realtime playback? If it's the latter, we might be able to speed it up by using d3d11vpp instead of shaders for colour conversion.

**Comment by blackarcher21** [comment]
Using DXVA Checker, it says that GPU supports hevc 10bit with both DXVA2/D3D11. mpv always fallback to software decoding when I set hwdec=d3d11va
log file if you are interested [log.txt](https://github.com/mpv-player/mpv/files/3711672/log.txt)
I can't test the fix, waiting next shinchiro build, so can't give any feedback. But I believe that issue is fixed. thank you :)
