### ISSUE TITLE
the God mpv.io, please guild your believers setting 'hwdec' default

### ISSUE THREAD

**Issue by Justsoos** [mpv-player/mpv#7061]
https://github.com/Homebrew/homebrew-cask/issues/70960
As discussed here, I think the mpv.io official should give the attitude of default `hwdec` setting, otherwise there will be more "user victims", play the MPV player with default SOFT decompression, do not know to turn on the hardware decompression, which will cause excessive CPU overload.

The key reason is that homebrew guys believe in following the original package which you God gave.

**Comment by wm4** [comment]
hwdec is off by default. mpv has conservative, "safe" defaults, even if that means worse user experience in some cases. For example we don't enable gpu-hq rendering by default either.

The main reason for not enabling hwdec by default is because it adds bugs that were not present with software decoding (the other way around almost never happens, except that it might be slower). If you don't like this, just change the setting to ``hwdec=auto`` in your config file.

I'm not sure what kind of language barrier it is that you throw around words like "god" and "believers" in this context.

**Comment by CounterPillow** [comment]
his language barrier is "apple user"

**Comment by Justsoos** [comment]
your mind barrier is "flatter programmer"

could you pls have a survey for HOW many users CAN find and open the mpv.conf file and write hwdec correctly, and save it all correctly?

**Comment by wm4** [comment]
If they can't, the player is not for them, and they should use a frontend like iina.

**Comment by Justsoos** [comment]
I'm here just because IINA works with 30% CPU and 107% by MPV.
Is there something to be proud of?

**Comment by CounterPillow** [comment]
Why is it always homebrew people that are like this

**Comment by Akemi** [comment]
> Why is it always homebrew people that are like this

i think in this case it's something entirely different...
