### ISSUE TITLE
Hardware decoding error when switching from background to foreground on ios

### ISSUE THREAD

**Issue by macrohard** [mpv-player/mpv#7077]
mpv version: mpv 0.29.0-849-gbd0af9a761-dirty
FFmpeg: N-95425-g1e35519fe0
iOS 9.3.5 on iPad2

When the App enters the background and then returns to the foreground, a bunch of error logs are printed. And CPU usage increased from 25% to 150%, memory usage doubled, and "Energy Impact" changed from low to high.

> [  20.656][e][ffmpeg/video] h264: Failed to decode frame (invalid session, -12903)
[  20.657][e][ffmpeg/video] h264: hardware accelerator failed to decode picture
[  20.657][w][vd] Error while decoding frame!
[  20.658][d][ffmpeg/video] h264: VideoToolbox decoder needs reconfig, restarting..
[  22.212][e][ffmpeg/video] h264: Failed to decode frame (decoder malfunction, -12911)
[  22.212][e][ffmpeg/video] h264: hardware accelerator failed to decode picture
[  22.212][w][vd] Error while decoding frame!
[  22.212][d][ffmpeg/video] h264: VideoToolbox decoder needs reconfig, restarting..
[  22.241][e][ffmpeg/video] h264: Failed to decode frame (decoder malfunction, -12911)
[  22.241][e][ffmpeg/video] h264: hardware accelerator failed to decode picture
[  22.241][w][vd] Error while decoding frame!
[  22.251][w][vd] Falling back to software decoding.
[  22.251][v][vd] Detected 2 logical cores.
[  22.251][v][vd] Requesting 3 threads for decoding.

Through multiple tests, I found that the problem is 'hwdec'. If I turn off hardware decoding, everything works fine. But with software decoding,  the CPU usage on iOS devices has been maintained at around 150%, and 'Energy Impact' has been High, which is not acceptable.

I tried to set pause = 1 in applicationDidEnterBackground and pause = 0 in applicationWillEnterForeground, but this didn't work. 

The current workaround is to set hwdec to 'no' when entering the background, and reset to 'videotoolbox' when it is restored to the foreground. Although the error log is still output, the CPU, memory, and 'Energy Impact' are all normal.

But this should not be a good solution. Is there any other solution?

full log:
https://0x0.st/z3cx.txt

**Comment by Akemi** [comment]
don't think many can help here, since not many use mpv on iOS. maybe @tmm1 knows something.

this is just me guessing. iOS's power management is rather aggressive and in background quite a few things are not supposed to work, it returns a `kVTInvalidSessionErr` error after all. something we can't do anything about, besides manually recovering the state at a later point. quote from the [docs](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622997-applicationdidenterbackground):
```
It is also imperative that you avoid using OpenGL ES in the background.
```

the situation you describe is a bit similar to what could happen to apps on macOS when being minimised for example. in that case one can send a MPV_RENDER_PARAM_SKIP_RENDERING with the render call (kinda unrelated to hwdec).

anyway what i would try:
- try if manually setting pause before going background works (just for testing)
- if above works the "applicationDidEnterBackground" is just too late to pause and the error already happens while entering background, in that case use an earlier event to pause [(applicationWillResignActive)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622950-applicationwillresignactive).

same problem [here](https://trac.pjsip.org/repos/ticket/2114). as a fix they stop decoding on background and reset hwdec on foreground. so if above doesn't work your best bet really is turning off hwdec and turning it on again. this can't be fixed within mpv or ffmpeg because neither knows about the app state, this has to be done by the libmpv user.

**Comment by macrohard** [comment]
@Akemi thank you very much! I also want to know if there is an interface to stop decoding, I checked the manual, except that hwdec is set to no, no other options are found.

**Comment by Akemi** [comment]
just pausing the playback should be enough. though i am not sure how vd-lavc-threads plays into that.
