### ISSUE TITLE
Crash while playing ass subtitles with asian character & emoji on macOS

### ISSUE THREAD

**Issue by LIznzn** [mpv-player/mpv#7123]
### mpv version and platform

mpv 0.30.0
macOS 10.15.1

### Reproduction steps

Ass subtitles with asian character & emoji

### Expected behavior

Display emoji correctly

### Actual behavior

Crash

### Fix

This problem is possible caused by CoreText which is libass's default font selection backends on macOS. 
Compiling libass using --with-fontconfig option to disable CoreText can fix this problem.

**Comment by Akemi** [comment]
no log, no crash report. if it's a libass issue you should report it to libass not us.

**Comment by LIznzn** [comment]
Sorry for the incomplete issue this morning. I try to find out this problem all day.
This is related by libass but **NOT** a issue.  Just add **--enable-fontconfig --disable-coretext** options to build libass can fix this problem.
It is caused by CoreText.framework in macOS system, I think.

**Comment by wm4** [comment]
Either a bug in CoreText or libass. libass could be passing invalid parameters to CoreText. That even seems likely. On the other hand, a bug in mpv seems rather unlikely. You should continue debugging this. Using fontconfig is not really a solution. It'll cause weird pauses on startup (or first subtitle) if there are many fonts installed. That's why the CoreText backend was added in the first place.
