### ISSUE TITLE
[regression v0.30] audio delay when playing a stream

### ISSUE THREAD

**Issue by eoli3n** [mpv-player/mpv#7124]
### mpv version and platform

Archlinux mpv 0.30.0-2 x86_64

### Reproduction steps
It only happens in video from tf1.fr, can't reproduce with youtube.
```
mpv https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/quotidien-premiere-partie-du-4-novembre-2019-47247497.html
```
### Expected behavior
No sound delay
### Actual behavior
Sounds start 10sec after video
### Log file

[Log file of 15 first seconds](https://x0.at/JhU.txt)

### Workaround

Downgrade to mpv 0.29.1

**Comment by wm4** [comment]
Ha something to do with the EDL DASH hack.

**Comment by wm4** [comment]
OK, it's because we switched the ytdl script from using --audio-file to an EDL combined stream. The audio stream in your URL is a separate HLS stream, which starts at a timestamp of 10 seconds. --audio-file explicitly rebases the start time to 0, and since the video also starts at 0, both streams start at the same time. With the new code, it's using a EDL separate tracks, which explicitly does not do this. In theory, what the new code does is more correct and more efficient; it just doesn't work in this case I guess.

**Comment by eoli3n** [comment]
so is there any core fix for this ?

**Comment by wm4** [comment]
Who knows, at this point it's a mystery how this stream is handled, and that it sort of works. The video stream is apparently DASH (!), which is handled by mpv's EDL DASH hack (!!), and the audio is a hls stream (!!!).

Determining why it has this odd start time, and when the start time should be compensated, would probably take some time to hunt down.

**Comment by Dudemanguy** [comment]
OP's command worked for me so I will assume this has been fixed.
