### ISSUE TITLE
mpv through socat delaying to report back new volume value (when volume changes)

### ISSUE THREAD

**Issue by s-n-g** [mpv-player/mpv#7153]
### mpv 0.30.0 on manjaro linux

I am using mpv as a backend to play radio stations (the program is [pyradio](https://github.com/coderholic/pyradio))
Up until 0.29.0 I would change the volume (commands "cycle volume" and "cycle volume down" on the socket) and would immediately get the new volume value (i.e. "Volume: 51%")

Now with 0.30.0, the command is still sent and executed (volume changes) but I get no response ("Volume: 51%" or whatever).

Instead, I get the new volume value whenever the radio station sends an "icy-title" update.
Furthermore, if multiple volume changes were performed, I get reports for all of them as one response upon "icy-title" update.

### Reproduction steps
Well, this is kind of hard to do.
If you want, clone [pyradio](https://github.com/coderholic/pyradio), install it and execute it:
```
pyradio -u mpv -d
```

This will create a log file (~/pyradio.log)

Running pyradio with 0.29.0 and changing the volume (keys -/+), will display the new volume value.
Running it with 0.30.0 it does not (the new volume comes too late).

But I think it would be better to see the logs I've included...

### Expected behavior
When a "cycle volume" command is received through the socket, mpv should report back the new volume value (i.e. "Volume: 51%", or whatever)

### Actual behavior
The new volume value is reported back when an "icy-title" update comes from the radio station (which probably triggers a response from mpv). Furthermore, if multiple volume changes were performed, mpv reports for all of them as one response upon "icy-title" update.

### Log file

[debian-0.29.0.-pyradio.log](https://0x0.st/z6PH.log)

[manjaro-0.30.0.-pyradio.log](https://0x0.st/z6Pr.log)

### Sample files

No sample files needed to reproduce this issue.

**Comment by wm4** [comment]
Does it happen with git master?

**Comment by s-n-g** [comment]
I don't know, I am using distro provided packages.
I will try to build it on a vbox if it's not too much trouble

**Comment by s-n-g** [comment]
I have just built **mpv** using **mpv-build**, and I still get the same behavior

```
mpv --version
mpv 0.30.0-144-g8d4e012bfa Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Fri Nov 15 11:44:59 EST 2019
ffmpeg library versions:
   libavutil       56.35.101
   libavcodec      58.62.100
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.66.100
   libswresample   3.6.100
ffmpeg version: N-95733-g73ee53f317
```

**Comment by wm4** [comment]
How do I run this? No, I don't want to install it.

**Comment by wm4** [comment]
OK, this may be due to 8721ac50fb7d779476d7cad063. That means it uses `\r` and other terminal control codes now even if stdout/stderr is not a terminal.

For years, the manpage has stated that scripts etc. should not parse the terminal output. You ignored this, so we can't provide compatibility. This could have been broken in any other way, such as us changing the OSD output's spelling. This is not API and intended for humans only. This is a bit like you'd screenshot a GUI window and OCR its contents and treat that as API.

Still on the fence whether to revert the mentioned commit, but I think I'm tending towards no. So this is a WONTFIX. It should be easy for you to work this around, or to implement this properly.

On that note, what's even the point of parsing the volume line printed by mpv?

**Comment by s-n-g** [comment]
Ok, I just got on and saw this.

As you've said this is not an API, so yes you are right, I should implement it some other way.

> On that note, what's even the point of parsing the volume line printed by mpv?

Well, the thing is I want to display the current volume value whenever any of the volume up/down keys are pressed. Parsing the volume line seemed like the way to go...

**Comment by wm4** [comment]
The text about not parsing terminal output was sort of hidden, so I added something new to the manpage that stresses this.

Anyway, reverting this terminal change would probably not help you anyway, since 0.30 is already released. Though whether the terminal change was a good idea (on its own) is probably still open for discussion.

>    On that note, what's even the point of parsing the volume line printed by mpv?

What I meant was, why do you need to parse/know this at all? You'll just read back the value you've just set.

**Comment by s-n-g** [comment]
I initially do not know the value.
I just use "cycle volume" and "cycle volume down" and read the value returned
