### ISSUE TITLE
Video frames pile up while on different virtual desktop

### ISSUE THREAD

**Issue by codesoap** [mpv-player/mpv#7175]
### mpv version and platform
- mpv: 0.29.1 
- Operating system: OpenBSD 6.6 (amd64)
- Window manager: dwm

### Reproduction steps
- Start video like so: `mpv --log-file=output.txt --ytdl-format 'bestvideo[height<=?1080]+bestaudio/best' 'https://www.youtube.com/watch?v=aqz-KE-bpKQ'` (my graphics card / drivers are too slow for 4K)
- Switch to a different virtual desktop (I'm using the dwm window manager)
- Wait at least 15s
- Switch back to the virtual desktop that contains mpv

### Expected behavior
Upon switching back to mpv I can continue watching the video without any racing video.

### Actual behavior
The video seems to race through all frames, that I missed while being on the other virtual desktop; the audio keeps playing normally (asynchronous to the video). After all the missed frames have been displayed, normal playback continues.

The longer I have been "gone", the longer I will have to wait for the video to return to normal playback.

I can  pause mpv, while the frames are racing, but when I continue they will still race until every missed frame has been displayed.

The audio keeps playing normally while I am on the other virtual desktop and when the video is racing.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/3880878/output.txt)

### Sample files
Use the YouTube-URL provided in "Reproduction steps", or download the video: `youtube-dl -f 'bestvideo[height<=?1080]+bestaudio/best' 'https://www.youtube.com/watch?v=aqz-KE-bpKQ'`. There is no difference between playing local files vs. streaming from YouTube.

**Comment by Ckath** [comment]
while I cant reproduce the exact behavior, I can confirm that dwm (or x11 for that matter, not sure) will ruin performance of things running in a non focused workspace. I've experienced it with numerous things before, its not limited to mpv.

now since your log also mentions the video is experiencing severe desync issues, which is most likely due to this and your hardware.. its probably not really an issue mpv should and can solve for you here. iirc the fast-forwarding/rubberbanding of video to get up to speed with audio and vise versa is defined behaviour

**Comment by codesoap** [comment]
Thank you for the info!

> iirc the fast-forwarding/rubberbanding of video to get up to speed with audio and vise versa is defined behaviour

Interesting; do you happen to know the reasoning behind that behaviour? I think it would be better, if I could disable this fast-forwarding. Or maybe the fast forwarding should have limits, e.g. skip forward instead, when the desynchronization is >5s or similar.

**Comment by wm4** [comment]
If the VO is completely blocked on display, mpv can't decode more video. Frame dropping only happens when a new frame is displayed. Then it has no other choice than to catch up (which gets you the observed effect because decoding is limited by CPU), or to issue a seek (no such behavior is implemented).

The blocking shouldn't happen. Many other things could go wrong if it does, including freezing the whole player completely.

Sounds like a pretty broken window manager to me if it really does that. (And of course broken windowing/graphics API.)

**Comment by codesoap** [comment]
I just discovered that using the `--vo=xv` flag eliminates the problem for me.
