### ISSUE TITLE
Unable to display certain subtitles from DVDs

### ISSUE THREAD

**Issue by ViktoriiaKh** [mpv-player/mpv#7218]
mpv does not display certain subtitles from DVDs converted to MKV.
mplayer and VLC display these subtitles.

[log.txt](https://github.com/mpv-player/mpv/files/3911078/log.txt)
[Sample file](https://www.dropbox.com/s/nupgvcl6sf2s3bq/sample.mkv?dl=0)

**Comment by Akemi** [comment]
the subtitles work they are just offscreen. i assume it's because of the different scaling and the mismatch of aspect ratio. vlc also cuts them off for me.

![Judgment  Toaru Kagaku no Railgun - Motto Marutto Railgun  4AA2AEC6 _(00-00-21 647)_01](https://user-images.githubusercontent.com/680386/70086115-f6420b80-1611-11ea-9280-c52c6059fff2.png)

**Comment by wm4** [comment]
Why rotated of all things?

But yeah, how scaling of vobsubs is supposed to be done if the resolution mismatch is a mystery to be solved.

**Comment by wm4** [comment]
OK, I looked at it. The video doesn't have a reasonable aspect ratio to begin with. The subtitle resolution (as encoded in the file headers) match the video resolution, but it produces subtitles outside of this bounding box.

I suspect the subtitles were made for video with a resolution of 640x480 or so, but the resolution was set incorrectly when someone severely incompetent muxed the video file.

Broken file, try to fix it manually (you can probably extract the subs, edit the .idx, and remux manually).

**Comment by wm4** [comment]
Workaround and explanation why it works in MPlayer in the commit above. Please punch whoever produced this file for me.

**Comment by ViktoriiaKh** [comment]
Thank you very much for the explanation.
