### ISSUE TITLE
macOS mpv v0.30 Swift dependency takes 11MB

### ISSUE THREAD

**Issue by relikd** [mpv-player/mpv#7235]
Hey there,

I was wondering why mpv v0.30.0 for macOS has suddenly the Swift libraries included in the binary. Compared to the v0.29.1 version that did make use of Swift too, but does not have the libraries included in the `.app` bundle.
```
libswiftAppKit.dylib
libswiftCore.dylib
libswiftCoreData.dylib
libswiftCoreFoundation.dylib
libswiftCoreGraphics.dylib
libswiftCoreImage.dylib
libswiftDarwin.dylib
libswiftDispatch.dylib
libswiftFoundation.dylib
libswiftIOKit.dylib
libswiftMetal.dylib
libswiftObjectiveC.dylib
libswiftos.dylib
libswiftQuartzCore.dylib
libswiftXPC.dylib
```

I did not compile it, rather compared the two versions from here: https://laboratory.stolendata.net/~djinn/mpv_osx/

Application size:
v0.29.1:  39.6 MB
v0.30.0:  54.7 MB

**Comment by CounterPillow** [comment]
Ask the person who made the build (@stolendata), not us. As the installation page says, these are unofficial third-party builds.

**Comment by wm4** [comment]
Or ask Apple...

**Comment by Akemi** [comment]
Apple's preferred way to link against the swift runtime library changed from static to dynamic linking. prior to 0.30 we statically linked to the swift runtime and it was included in the binary (contrary to what you said, you got your terms wrong). since 0.30 we dynamically link to the swift runtime, which does have some possible overhead, resulting in those .dylib files being included in the app bundle.

those libs are basically optional since swift 5. we do include them because apple doesn't ship the swift runtime with all supported macOS versions yet and they need to be manually installed. if you are on a system with the swift runtime installed it should be safe to just delete those libs.
