### ISSUE TITLE
Zsh completion does not works with macOS Catalina preinstalled zsh

### ISSUE THREAD

**Issue by ixearth** [mpv-player/mpv#7240]
### mpv version and platform

0.30.0
macOS Catalina (10.15.1)
installed by `brew install mpv`

### Reproduction steps

Use macOS preinstalled zsh, type `mpv --` then press TAB

### Expected behavior

`zsh: do you wish to see all 972 possibilities (780 lines)?`

### Actual behavior

output this error and completion does not works.
```
generate_arguments:9: failed to load module `zsh/pcre': dlopen(/usr/lib/zsh/5.7.1/zsh/pcre.so, 9): image not found
generate_arguments:9: -pcre-match not available for regex
```

`/usr/lib/zsh/5.7.1/zsh/pcre.so` does not exist on macOS Catalina, the preinstalled zsh does not seem support PCRE.

the zsh installed by brew does not have this problem.

**Comment by qmega** [comment]
Huh. I did actually intend for PCRE to be optional, but I didn't have a system without it to test. I thought the setopt would fail, but apparently it succeeds and then just breaks any matches. Looked through some docs and I think I can fix this by trying to load the pcre module and only setting the option if *that* succeeds.

The script should otherwise work without re_match_pcre set -- it uses only POSIX-compatible regex.

Can you test a patch? Even if you don't want to recompile, you can just replace the completion script on your filesystem with the modified one.

**Comment by qmega** [comment]
@ixearth Please try out the linked PR #7242 .
