### ISSUE TITLE
Proposal: make vulkan-queue-count=3 default due to improved performance

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#7251]
mpv 0.30.0-294-g22e4aac9fa
libplacebo 1.21
RX 570 with recent mesa 20 git

Benchmark with the most demanding scalers that mpv offers + deband:

```
hwdec=vaapi-copy
gpu-api=vulkan

dither-depth=8
sigmoid-upscaling
linear-downscaling
correct-downscaling

cscale=ewa_lanczos
scale=ewa_lanczos
dscale=ewa_lanczossharp

deband

vulkan-queue-count=1/2/3

audio=no
untimed=yes
video-sync=display-desync
vulkan-swap-mode=immediate
opengl-swapinterval=0
osd-msg1="FPS: ${estimated-display-fps}"
```
Use an H.264 video, as performance with other formats quickly gets bound by the VPU speed. To make sure rendering speed actually is limited by the GPU's processing power, simply switch to bilinear scaling and fps should increase a lot.

Downscale a 2160p 60fps video to 1440p:
vulkan-queue-count=1: ~152fps
vulkan-queue-count=2: ~153fps
vulkan-queue-count=3: ~166fps (would be even faster if my GPU didn't power throttle)

I think since async compute is enabled by default, we can also let modern GPUs (GCN, RDNA and Volta/Turing) take advantage of multiple compute queues by default.

**Comment by mibby** [comment]
Just to provide a counter argument, here are my benchmarking stats comparing various settings.

**Testing methodology:**
**CPU:** 3950X with Chipset Driver 1.11.22.0454
**GPU:** RTX 2080 Ti with Graphics Driver 411.66
**OS:** Windows 10 v2004 Build 19041.1

Checking FPS count after 5 seconds of playback playing a 1080p video in windowed mode on a 1440p monitor. After the 5 seconds when the video is paused, I move the mouse to display the osc so the FPS count updates to the final value, since it seems to update again when the osc is shown. Same video file is used and played back 5 times.

**Benchmarking Settings:**
```
## Backend ##
profile=bench
gpu-api=vulkan
vulkan-async-transfer=yes
vulkan-async-compute=yes
vulkan-queue-count=1

[bench]
audio=no
untimed=yes
video-sync=display-desync
vulkan-swap-mode=immediate
opengl-swapinterval=0
d3d11-sync-interval=0
osd-msg1="FPS: ${estimated-display-fps}"
end=5
```

---

With ``vulkan-async-compute=yes`` & ``vulkan-queue-count=1``, fps after 5 seconds:
* Sample 1: 1650.587
* Sample 2: 1640.285
* Sample 3: 1650.070
* Sample 4: 1645.833
* Sample 5: 1643.615

---

With ``vulkan-async-compute=yes`` & ``vulkan-queue-count=2``, fps after 5 seconds:
* Sample 1: 1267.347
* Sample 2: 1405.590
* Sample 3: 1280.754
* Sample 4: 1331.576
* Sample 5: 1181.782

Don't ask me why this is much lower. I ran multiple samples past 5 times and they always average around 11-1300, nvidia just doesn't like even numbered queues I guess?

---

With ``vulkan-async-compute=yes`` & ``vulkan-queue-count=3``, fps after 5 seconds:
* Sample 1: 1642.791
* Sample 2: 1661.972
* Sample 3: 1659.448
* Sample 4: 1651.691
* Sample 5: 1694.973

---

With ``vulkan-async-compute=yes`` & ``vulkan-queue-count=8``, fps after 5 seconds:
* Sample 1: 1374.835
* Sample 2: 1435.544
* Sample 3: 1402.210
* Sample 4: 1448.971
* Sample 5: 1282.471

---

With ``vulkan-async-compute=no`` & ``vulkan-queue-count=1``, fps after 5 seconds:
* Sample 1: 2065.796
* Sample 2: 2067.782
* Sample 3: 2054.485
* Sample 4: 2086.724
* Sample 5: 2052.377

---

With ``vulkan-async-compute=no`` & ``vulkan-queue-count=2``, fps after 5 seconds:
* Sample 1: 1707.971
* Sample 2: 1673.688
* Sample 3: 1645.373
* Sample 4: 1680.644
* Sample 5: 1653.193

---

With ``vulkan-async-compute=no`` & ``vulkan-queue-count=3``, fps after 5 seconds:
* Sample 1: 1764.914
* Sample 2: 1761.820
* Sample 3: 1768.378
* Sample 4: 1787.534
* Sample 5: 1769.004

---

With ``vulkan-async-compute=no`` & ``vulkan-queue-count=8``, fps after 5 seconds:
* Sample 1: 1427.348
* Sample 2: 1355.537
* Sample 3: 1362.630
* Sample 4: 1461.529
* Sample 5: 1482.360

---

With ``vulkan-async-transfer=no``, ``vulkan-async-compute=no``, & ``vulkan-queue-count=1``, fps after 5 seconds:
* Sample 1: 1909.290
* Sample 2: 1942.426
* Sample 3: 1958.672
* Sample 4: 1975.562
* Sample 5: 1938.811

---

I get repeatedly better performance with ``vulkan-async-transfer=yes``, ``vulkan-async-compute=no``, & ``vulkan-queue-count=1``. Since ``vulkan-queue-count`` is defaulted to 1 (currently), I do not set it in my config. Setting the queue count to 0 didn't seem to result in any differences to 1 outside of margin of error. Usually resulted in the same numbers. ``vulkan-async-compute`` was specified to be off by default in the documentation but was enabled on the change to libplacebo without adjusting the manpage. Documentation has since been fixed but the setting remains defaulted to enabled.

I do not have an AMD card to compare with so I don't know if vulkan async behavior has a better threaded implementation. However since I use an nvidia card and nvidia generally has a higher market share (usually ~70% to 30% in comparison with each other or taking steam hardware survey stats, 75% nvidia, 15% amd, 10% intel), I'm a bit weary about changes being made to worsen overall performance.

Using vulkan instead of d3d11 with my forced setting change gives me higher performance by ~300-400 fps

*Primary config I use for 24/7 use:**
https://pastebin.com/raw/x87Cuknv

**Comment by aufkrawall** [comment]
You need to make sure that you are actually limited by GPU processing throughput and not by decoder performance etc. Having async compute and multiple queues might increase CPU overhead, but it's not a realistic problem apart from benchmarking with insanely high fps.
It might not be possible to find a proper test case with such a fast GPU and mpv's internal scalers, which are quite fast.

**Comment by mibby** [comment]
Perhaps you may be right, but I also benchmarked using FSRCNNX_x2_16-0-4-1 edited to upscale 1080p to 1440p in fullscreen. Still, vulkan provided better performance than d3d11 and I got the best performance out of vulkan with 1 queue-count and no async-compute doing so in that test.

**Comment by mibby** [comment]
Haha..

Testing d3d11 again (no ``gpu-api`` set in config so it auto defaults / picks d3d11) with ``d3d11-flip=no`` set in the config (since flip mode defaulting to on seems to cap fps to 180 no matter what when fullscreen), I get these results.

* Sample 1: 285.953
* Sample 2: 286.615
* Sample 3: 287.060.

Vulkan wins out in windowed mode but I guess what matters is when under load, fullscreen, and upscaling at the end of the day. Guess mpv picking what's best _is_ the best after all.

**Comment by Dudemanguy** [comment]
Eh, increasing the vulkan-queue-count worsens my performance (RX 550). My usual settings are upscaling from 1080p->4k with FSRCNNX 8. At the default value of 1, I get around 80fps on this particular sample. At 3, it goes down to about 77fps. I remember playing with that option in the past before and coming to the same conclusion.

**Comment by aufkrawall** [comment]
Meh, that's a bummer. So it seems it's really up to the used shaders.
Though I'd argue that the default settings should suit the buit-in shaders best.

**Comment by haasn** [comment]
I wonder if [this commit](https://code.videolan.org/videolan/libplacebo/commit/7067c7356eaa91be4ce78a65712318baf4c5e00f) helps your performance with queue count > 1?

**Comment by Dudemanguy** [comment]
@haasn: Seems pretty much the same here.

**Comment by Akemi** [comment]
seems like this is a no because we get mixed results.
