### ISSUE TITLE
800% CPU utilization with HEVC 4k HDR

### ISSUE THREAD

**Issue by urosk** [mpv-player/mpv#7252]
### mpv version and platform

0.30 OSX

### Reproduction steps

Have a Mac Mini 8700k with UHD 630 igpu
Have a 4k TV
Open a HEVC 4k HDR video: https://4kmedia.org/sony-swordsmith-hdr-uhd-4k-demo/
Have an empty mpv.config file
Observe CPU utilization shoot up to 800% in OSX Activity Monitor

QuickTime has 9% CPU utilization for this same video
Even IINA has only 15%

I experimented with a bunch of basic and more esoteric settings, but I couldn't make it much better.

How it should be:
- default settings should provide optimal performance on common hardware

**Comment by CounterPillow** [comment]
>default settings should provide optimal performance on common hardware

Says who?

The reason why mpv uses the CPU much more here is because hwdec is off. IINA (which utilises libmpv by the way) seems to just turn hwdec on by default.

mpv's attitude towards hwdec has always been that it's nice when it works but due to being a minefield of vendor-specific bugs it's not on by default. These aren't just a case of "hwdec doesn't work on a certain file and we can detect it and fall back to swdec"; sometimes it produces the wrong output, or degraded output, or even segfaults mpv. Especially the last one is part of why browsers are wary of enabling hardware video decoding, because it has potential security implications for them.

We've been proven right in this assessment time and time again, e.g. when Ubuntu decided to turn on `hwdec=auto` by default, resulting in bug reports from users running into issues with hwdec that didn't have issues before, which made Ubuntu change it to `hwdec=vaapi` thinking it's a safer bet, resulting in even more bug reports.

On macOS the issue isn't much better, as [can be easily seen from the issue tracker](https://github.com/mpv-player/mpv/issues?q=is%3Aissue+is%3Aopen+videotoolbox+label%3Ahwdec%3Avideotoolbox).

This attitude towards hwdec works well for most codecs as their software decoding is usually competent enough for the codec's complexity, except for one: HEVC. Because of licensing issues, HEVC is pretty much dead outside of broadcast TV and UHD BDs. This means absolutely no money is going into the optimisation of HEVC software decoders, which is why software decoding for HEVC performs so poorly. As a result, software decoding is sometimes a strictly inferior experience to hardware decoding when viewing HEVC video, but that's why we have hwdec bound to ctrl+h to be turned on at any time if needed.

If you disagree with upstream mpv's view of hwdec, you can put `hwdec=auto` into your `mpv.conf` at any time.

**Comment by urosk** [comment]
The issue is that stolendata's builds are not using hwdec for HEVC content, as discovered by @Akemi here https://github.com/mpv-player/mpv/issues/7256
