### ISSUE TITLE
macosx 10.15.2 dedicated gpu not used/switched to when --vo=libmpv enabled, extreme bad performance

### ISSUE THREAD

**Issue by tomeq82** [mpv-player/mpv#7272]
### mpv version and platform

[cplayer] mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Nov  5 05:50:07 GMT 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.31.100
[cplayer]    libavcodec      58.54.100
[cplayer]    libavformat     58.29.100
[cplayer]    libswscale      5.5.100
[cplayer]    libavfilter     7.57.100
[cplayer]    libswresample   3.5.100
[cplayer] ffmpeg version: 4.2.1

Platform is MacOSX 10.15.2 running on MacBook Pro 2019 with i9 (Intel 630 integrated) and Radeon Pro 560X

### Reproduction steps

1) Launch mpv with --no-config and --cocoa-force-dedicated-gpu=yes, observe that only Intel 630 is being used for decoding which has dramatically bad performance, fullHD video is being rendered in avg 20-22 fps. Same happens with --vo=libmpv is set explictly
GPU switch doesn't happen at all. It should. 

2) Launch mpv with --no-config and --cocoa-force-dedicated-gpu=yes and --vo=gpu will output to Radeon Pro correctly with smooth playback and no performance issues.

### Expected behavior

When --vo=libmpv is used and  --cocoa-force-dedicated-gpu=yes, Radeon GPU should be used for playback. 

When --vo=libmpv is used and intergrated GPU is used it should not have such a bad performance as Intel 630 should be able to eat anything up to 4K not to mention normal H.264 1080p videos.... 

### Actual behavior

GPU switch to Radeon doesn't seem to happen, also integrated Intel 630 output via libmpv has extremally bad performance event without any filters. 

### Log file

1) --vo=default
https://0x0.st/z0Sl.txt
2) --vo=gpu
https://0x0.st/z0SU.txt

### Sample files
will add if needed....

**Comment by Akemi** [comment]
> ...observe that only Intel 630 is being used for decoding...
by default your CPU always does the decoding.

> --cocoa-force-dedicated-gpu=yes
is currently not supported by the cocoa-cb/libmpv backend. i guess this is a request to support it.

> When --vo=libmpv is used and intergrated GPU is used it should not have such a bad performance as Intel 630 should be able to eat anything up to 4K not to mention normal H.264 1080p videos....
sure, my mid 2010 MBP has no problems doing 1080p. either apple fucked up opengl even more with 10.15, 10.15 is even more shit than currently known, there are some combinations of settings that don't play well with intel, or Apple adjusted their heuristic again how to ramp up frequencies with opengl (see my comment https://github.com/mpv-player/mpv/issues/5536#issuecomment-370236454 and that issue). tbh it's most likely Apple fucking over opengl.

for testing, if you can build yourself, you can remove [this line](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa-cb/video_layer.swift#L64). this should alw<ys force the dedicated gpu.

otherwise, is there a difference between vo=libmpv and vo=gpu when both use the integrated GPU?

without much more information there is not much i can do about performance. most likely there is no way doing anything about it.

**Comment by tomeq82** [comment]
Hm, maybe i'm a bit not precise with wording and issue description. Let me try to explain. The default behavior is that mpv launches video on integrated GPU - it is fine for me, but for some reason enabling near any of the non-default filters like interpolation, some usual scalers (ewa_lanczossharp) makes any videos totally unwatchable - 20 fps on i9 CPU and intel 630... hm. That is not right. 

Option --vo=gpu enables Radeon GPU and all is ok, --vo=libmpv always decode via Intel integrated and it never switches to Radeon GPU.
 I think it is a bug/should-be-feature that mpv doesn't trigger using Radeon GPU instead of integrated GPU when using --vo=libmpv output... 

Answering your question: there is difference when using vo=gpu and vo=libmpv as vo=gpu doesn't use Intel at all, only Radeon, while libmpv does the opposite.... so I can't compare intel on intel using different vo's

**Comment by Akemi** [comment]
you said you used `--cocoa-force-dedicated-gpu=yes` with `--vo=gpu`, as does your log. in that case it's obvious it always does use the dedicated GPU (whi vo=gpu). libmpv ignores that flag. if you use `--no-config` and both VOs behave different it's an Apple bug because we don't manage what GPU that is used (it's completely managed by the system). you should file a bug report with Apple, though they will just ignore you.

**Comment by Akemi** [comment]
i added support for this in PR #7376. the old option still works (works for cocoa-cb now) but i replaced it with a new option `--macos-force-dedicated-gpu`. feel free to test.
