### ISSUE TITLE
Opening preferences attempts to install vpn profile

### ISSUE THREAD

**Issue by jeff-geoff** [mpv-player/mpv#7291]
### mpv version and platform
0.30.0
MacOS (homebrew)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Open mpv
Go to menu bar
Open "Preferences" in the "mpv" menu

### Expected behavior
Display preference pane

### Actual behavior
Attempts to install .ovpn file via Tunnelblick

### Log file

N/A

### Sample files

N/A

**Comment by Cpuroast** [comment]
There's no preference pane, it supposed to load mpv.conf in a text editor.

mpv.conf lives in ~/.config/mpv/mpv.conf

I tested and it behaves as expected.

**Comment by jeff-geoff** [comment]
It allows Finder to choose the editor, which does not seem safe as it potentially launches any installed application.

**Comment by Cpuroast** [comment]
All it's doing is opening the file, it doesn't specify anything, it assumes your file associations are correct. Same as if you would double-click mpv.conf file in finder or do "open mpv.conf" in terminal.

**Comment by Akemi** [comment]
a Preferences Pane is out of scope for mpv. it only will try to open the two mentioned files (mpv.conf, input.conf) with the application associated with them. if it can't it will open the folder, and if it can't open the folder it will ask you to crate them.

it will never try to open a .ovpn file directly. if your .conf files are associated with tunnelblick and it tries to install something, that's how you set it up.

there are four things we could do:
1. remove both menu items
2. only ever open the config folder
3. always force open the config file with TextEdit
4. ask the bloody user if he really wants to open the file

1. will not be very popular with the people i added those for
2. is a shabby compromise
3. suboptimal if you associated a proper text editor to the file, suboptimal because TextEdit
4. yeah, better we ask the user if they reallyyy want to do it

mpv isn't really a safe app since any script can potential do anything or searches for specific binaries (youtube-dl) in specific places to call them already.

closing for now since i think it's fine as it is. though feel free to discuss potential other solutions with interested people.

**Comment by deus0ww** [comment]
Option 2 (open the config folder) would be nice. It seems like I'm editing input.conf, script-opts, or scripts much more often than mpv.conf (but that could very well be a use case specific to me...).
