### ISSUE TITLE
OSC continues to receive mouse input after being hidden

### ISSUE THREAD

**Issue by d87** [mpv-player/mpv#7298]
### mpv version and platform

0.30.0 Windows

### Reproduction steps

1. Show OSC (because initially if player starts with osc hidden it's fine)
2. Hide OSC (visibility to "never")
3. Click on lower part of the frame, where the seekbar was.

Or just use this bind to cycle
```b script-message osc-visibility cycle```

### Expected behavior

After being hidden no longer reacts to mouse clicks

### Actual behavior

It does react and jumps to random time when you accidentally click on the invisible seekbar, somehow happens to me pretty often

**Comment by avih** [comment]
Is it version 0.30.0 exactly? or something newer? (there were recent osc/events changes recently). The exact version appears at the og - which you didn't attach as requested.

**Comment by d87** [comment]
Yes, exactly. or at least it was marked as stable
[output.txt](https://github.com/mpv-player/mpv/files/4008015/output.txt)

**Comment by avih** [comment]
Thanks for the report. I can reproduce, and it appears to go long way back, and seems to be an issue at `osc.lua`.

I was able to "fix" it with something I consider hacky, but I won't push it because it'll just make the osc code even more delicate than it already is, and it's not a huge issue for users (you seem to be the first which notices it among users and devs).

Not sure yet what to do about it.
