### ISSUE TITLE
--macos-title-bar-appearance=auto doesn't recognize dark mode

### ISSUE THREAD

**Issue by lsnch** [mpv-player/mpv#7318]
10.15.2
mpv 0.31.0

It says here https://mpv.io/manual/stable/#options-macos-title-bar-appearance
>Detects the system settings and sets the title bar appearance appropriately. On macOS 10.14 it also detects run time changes.

I assume it means if I have dark mode enabled it will choose `darkAqua`.
That's not what happens. It just remains light. It goes dark if I explicitly set it to `darkAqua`.

**Comment by Akemi** [comment]
btw. i could reproduce this with stolendata's build but not with my own from 0.31.0. even with an older SDK it should fall back to the proper styling, that is if `UserDefaults.standard.string(forKey: "AppleInterfaceStyle")` still returns the same on 10.15. though since i could reproduce this here it probably is a macOS SDK 10.13 problem.

also going to keep that closed since you ignore the issue template.
