### ISSUE TITLE
mpv "mf://*.jpg": can we have date modified descending order

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#7328]
### mpv version and platform
$ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.2

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
$ mpv "mf://*.jpg" -mf-fps 0.25 --pause

### Expected behavior

I want the images to be  shown w.r.t date modified and descending order

### Actual behavior

The images are loaded based on name ascending order

### Log file

https://0x0.st/znEd.txt

### Sample files

Just a folder full of jpg files

**Comment by qmega** [comment]
It's unlikely that mpv itself will grow the ability to arbitrarily sort mf:// globs.

It's a dirty hack but this works in bash or zsh, as long as you don't have too many funny characters in your filenames:

```
mpv mf://@<(ls -t1 *.jpg) -mf-fps 0.25 --pause
```

That's newest first. If you want oldest first, `ls -tr1`. Not sure which you meant by descending.

Explanation: `mf://` can take a list file (with `@`) instead of a glob, in which case it just plays them in the order listed. So we list the files in the order you want, pipe that to a file descriptor, and then give mpv a filesystem handle to that file descriptor.

Mandatory disclaimer: Using `ls` programmatically is bad. Don't do it in a script or program, it'll eventually break.

**Comment by sant527** [comment]
Yes that will work. Thank you
