### ISSUE TITLE
Mouse cursor sometimes not visible in fullscreen on Sway

### ISSUE THREAD

**Issue by Limero** [mpv-player/mpv#7345]
### Important Information

- mpv version
0.31.0
- Linux Distribution and Version
Arch Linux
- Source of the mpv binary
Arch Linux repository
- Window Manager and version
Sway 1.2
- GPU driver and version
mesa 19.3.2

### Reproduction steps

Run: `mpv --fs --config=no --start=10% abc.mp4` on a video file
If mouse cursor is visible when moving it, press q and run same command again.

### Expected behavior

Mouse cursor should be visible when moving it around the player.

### Actual behavior

It's hidden.

Bug occurs on both sway 1.2 and latest sway from master branch (2020-01-06)
Bug does not occur on Gnome 3.34 on Wayland

**Sway developer has confirmed this is a mpv bug https://github.com/swaywm/sway/issues/4890**

### Log file

mpv --log-file log (open mpv, cursor hidden)
https://gist.github.com/Limero/fbfe69ad2373a829aa482aaefa227bce

WAYLAND_DEBUG log (open mpv, cursor hidden)
https://gist.github.com/Limero/facbe5484f3a7a8f68cc6bfd362f1d4f

sway -d 2 log (open mpv, cursor visible, close, open again and it's hidden)
https://gist.github.com/Limero/2bfb218efa9cec7f25d19455d18eae04

**Comment by CounterPillow** [comment]
It might be some sort of race condition involving the `pointer_handle_enter` callback(?)

```
[802204.711] wp_presentation_feedback@25.discarded()
[802204.724]  -> wl_surface@6.set_buffer_scale(1)
[802204.844]  -> wl_shm_pool@24.create_buffer(new id wl_buffer@25, 1059840, 24, 24, 96, 0)
[802204.870]  -> wl_pointer@22.set_cursor(0, wl_surface@7, 4, 4)
[802204.885]  -> wl_surface@7.set_buffer_scale(1)
[802204.891]  -> wl_surface@7.attach(wl_buffer@25, 0, 0)
[802204.903]  -> wl_surface@7.damage(0, 0, 24, 24)
[802204.918]  -> wl_surface@7.commit()
[802204.959] wl_callback@29.done(4795)
[802205.827]  -> wp_presentation@12.feedback(wl_surface@6, new id wp_presentation_feedback@29)
[802205.857]  -> wl_drm@21.create_prime_buffer(new id wl_buffer@30, fd 23, 2560, 1440, 808669784, 0, 10240, 0, 0, 0, 0)
[802205.894]  -> wl_surface@6.attach(wl_buffer@30, 0, 0)
[802205.905]  -> wl_surface@6.damage(0, 0, 2147483647, 2147483647)
[802205.982]  -> wl_surface@6.commit()
[802205.989]  -> wl_display@1.sync(new id wl_callback@31)
[802206.560] wl_display@1.delete_id(28)
[802206.584] wl_display@1.delete_id(31)
[802206.612] wl_surface@6.enter(wl_output@14)
[802206.619] wl_pointer@22.enter(4797, wl_surface@6, 1207.171875, 647.050781)
[802206.648]  -> wl_pointer@22.set_cursor(4797, nil, 0, 0)
```

We unhide the cursor, then receive a "the pointer has entered the window" event, then call `set_cursor_visibility` with `wl->cursor_visible` which might be the wrong value now. Either that or `wl->vo_opts->cursor_autohide_delay` is a bogus value in this case and triggers hiding the cursor when it shouldn't.

**Comment by CounterPillow** [comment]
Does reverting https://github.com/mpv-player/mpv/commit/7f300a00e929bd728c6cbff27b68bbbf28e85d0f fix this for you?

**Comment by Limero** [comment]
I just tested mpv 0.30.0 and I'm not able to replicate the issue on that version, so I guess that commit broke it.

**Comment by CounterPillow** [comment]
cc @Dudemanguy

**Comment by Dudemanguy** [comment]
Actually, it's 9eb3991 that broke which is kind of interesting and unexpected. Interestingly enough, it seems to only happen in Sway and not in Weston. For some reason, moving the cursor around in Sway doesn't flip the wl->cursor_visible bool anymore like it normally should have. Initially hiding the cursor when the window is launched as fullscreen is desirable (that's what happens in X11 as well) hence why we initially set the bool to false on the initial entry. However, it normally should flip again when the cursor is moved. Or at least, that's what used to happen.

**Comment by Dudemanguy** [comment]
cfceaec doesn't fix this, but thanks to these debug logs I did notice that the wayland backend initially tries to set the cursor before the pointer id actually exists which should be avoided. The `WAYLAND_DEBUG` logs should be easier to understand now.

If you try it now with the fullscreen flag, you'll see that initially the cursor is set to a nil when entering the surface (this is correct). But if you move the mouse around (which never appears), the `WAYLAND_DEBUG` log never shows that the set_cursor function is executed again. This gets weird because for some reason the bool immediately becomes false again in Sway when you attempt to move it around (it returns 0). In Weston, it returns 1 as expected.

I'm not ready to blame Sway yet since the behavior honestly makes absolutely no sense, but I suspect the older method before `m_config_cache_get_next_changed` was used had these same fundamental problems and just happened to work by sheer luck. Also the return statements that used to be in `VOCTRL_VO_OPTS_CHANGED` probably affected `*arg` value and also used to work by just plain luck. Why adding `start` to mpv 31.0 triggers this behavior is beyond me at this time (maybe some random reconfigure event or something?). In master, it breaks with just `--fs` which makes more sense.

**Comment by Limero** [comment]
Great job, thank you!
