### ISSUE TITLE
mpv: shuffle uses noticably bad rand(3)

### ISSUE THREAD

**Issue by cemeyer** [mpv-player/mpv#7374]
### Important Information

Provide following Information:
- mpv version: 0.29.1
- Platform and Version: FreeBSD CURRENT
- Source of the mpv binary: FreeBSD pkg

### Reproduction steps

mpv -shuffle is noticeably poor at shuffling.  In part this may be due to the low quality of rand(3) on FreeBSD.  I believe linux's rand(3) is more like the more-sophisticated random(3), which might hide the issues from developers.

Here's the relevant code: https://github.com/mpv-player/mpv/blob/master/common/playlist.c#L143-L148

### Expected behavior

Shuffle produces a random ordering with repeated `mpv -shuffle` of the same playlist.

### Actual behavior

Shuffle's orderings are noticeably repetitive / nonrandom due to use of weak / poorly seeded RNG.  I'd suggest, in order of preference, `arc4random()` on platforms where that is present, followed by `random`, followed by `rand.`  For the latter two, I suggest seeding with `getentropy()` where present, or `getrandom()`, or `RtlGenRandom()`, or reading 32 bytes from `/dev/urandom`, or nothing/weakly seeded with `time(NULL)` or something as we seem to do today.

### Log file

n/a

### Sample files

n/a

**Comment by avih** [comment]
I think `rand()` is supposed to be reasonably useful, and I don't see the value in shuffle being cryptographically secure or otherwise having strong randomness. Is there a value in that?

However, shuffle should probably not produce the same order on each run. I think just seeding it with time should be enough.

**Comment by cemeyer** [comment]
Set aside cryptographic security; I totally agree that's not the point here.  The goal is just producing an output sequence that isn't *noticeably* non-random to end users.  `rand()` is so bad it is actually human-observable (to me) that shuffle has bias / common sequences / etc.  See, e.g., http://man7.org/linux/man-pages/man3/rand.3.html#NOTES .  I can work from my end on making FreeBSD's `rand(3)` no worse than `random(3)`, like Linux, but that will be a slow change.

(You can see exactly how bad FreeBSD's rand(3) is here: https://svnweb.freebsd.org/base/head/lib/libc/stdlib/rand.c?view=markup#l53 (through line 104 or so).)

Shuffle's `rand` use does appear to be seeded with time already; it's not like it produces exactly the same sequence every time.  The problem with time (in seconds) is that it does not have a lot of differing bits between executions, and (current) `srand()` doesn't do any kind of whitening / bit distribution.  `srand(MD5(time()))` would be better than just seeding with raw time even if doesn't have more seed "entropy" in an information theory sense.

Is the concern with non-`rand` solutions portability / maintenance overhead?  Syscall overhead? 
 Thanks.

**Comment by avih** [comment]
I also think that shuffle should not have obvious patterns. From your first post I thought it's not seeded, but now I see that it is, then indeed maybe it just needs a better seed. It's also possible that the seed is lacking only on some platforms (I didn't look at the seed code).

> Is the concern with non-rand solutions portability / maintenance overhead? Syscall overhead?

Speaking only for myself, I'd say mostly code simplicity/readability/size, but also maintenance overhead, and initial setup (at configure etc). Performance is unlikely to be a meaningful factor for shuffle IMO.

**Comment by rossy** [comment]
It's true that rand() in most operating systems is a bad general purpose random number generator, but I'm not sure FreeBSD's rand() is so bad that it's noticeable when just shuffling a playlist.

I tested mpv's shuffle algorithm with FreeBSD's rand() and various playlist sizes, and it seemed fairly uniform. For example, for a playlist of 50 items, after 1,000,000 trials, each playlist item appeared in each position around 19,800-20,200 times, and each playlist item was followed by each other item around 19,800-20,200 times. That is, there was about a 2% chance that a certain playlist item would appear in a certain position, and a 2% chance that a certain playlist item would follow another playlist item.

I was surprised at how uniform the results were, though I admit I don't know much about statistics, and I don't know if there are other statistical tests I should be running. Maybe I should be looking for common sequences of three or four tracks. It's also possible that rand() starts getting bad for very large playlist sizes (10,000 items or larger,) which I haven't fully tested yet.

> Shuffle's ``rand`` use does appear to be seeded with time already; it's not like it produces exactly the same sequence every time. The problem with time (in seconds) is that it does not have a lot of differing bits between executions, and (current) ``srand()`` doesn't do any kind of whitening / bit distribution. ``srand(MD5(time()))`` would be better than just seeding with raw time even if doesn't have more seed "entropy" in an information theory sense.

mpv's seeding should be a bit better than just calling time(). mpv calls srand() with the current monotonic time in _microseconds_. In most operating systems, the timer APIs we call should have microsecond granularity, so the quality of the seed should be pretty good. Even if a user switches on their computer and opens mpv at the same time every day, there should still be a lot of entropy in that timestamp. Enough to shuffle a playlist of 50-100 items with a questionable rand(), anyway.

> Is the concern with non-``rand`` solutions portability / maintenance overhead? Syscall overhead?
Thanks.

IMO, a bit of all three. rand() is the only portable RNG that works on Windows, so any solution would require platform-specific ifdeffery, and probably just embedding our own RNG rather than using the OS's. That seems overkill unless there's solid proof that rand() isn't suitable for shuffling a playlist.

Keep in mind that randomness doesn't intuitively look like randomness. The human brain is good at finding patterns in truly random data, so people often complain about RNGs not being random enough, when they're actually fine. [Spotify][1] is an example of this. There was also a [gaming site][2] where users would complain that dice rolls from random.org weren't random enough, and that resulted in the owner building a physical dice-rolling machine to satisfy them. That's why I think some statistical proof is needed.

Not that I'm saying we shouldn't replace rand(). It needs more testing, but I think it might be bad for very large playlists on some platforms, like Windows, where RAND_MAX is only 32767.

[1]: https://labs.spotify.com/2014/02/28/how-to-shuffle-songs/
[2]: http://gamesbyemail.com/news/diceomatic

**Comment by Dudemanguy** [comment]
>I was surprised at how uniform the results were, though I admit I don't know much about statistics, and I don't know if there are other statistical tests I should be running. Maybe I should be looking for common sequences of three or four tracks. It's also possible that rand() starts getting bad for very large playlist sizes (10,000 items or larger,) which I haven't fully tested yet.

Given a very large n, a random number generator should look like a uniform distribution (assuming it's not biased to some other distribution of course). Under this assumption, each spot in the playlist would have an expected value of 20,000 so a standard deviation of 200 looks incredibly good.

Now of course, whether or not this is perceived as random is a whole different story, but the results suggest this is reasonably random.

**Comment by CounterPillow** [comment]
>You can see exactly how bad FreeBSD's rand(3) is here

They're using a fairly bog standard pseudo-random number generator, it's way outdated compared to more modern methods like [Mersenne-Twister](https://en.wikipedia.org/wiki/Mersenne_Twister) but for random music playback it's probably not noticeably non-random. I think rossy's note about true randomness vs. human perceived randomness is what's going on here.

Even if it were the case that `rand` was abhorrent on FreeBSD, that's really something FreeBSD should fix instead of every application having to work around BSD's shit code.

**Comment by avih** [comment]
> it is actually human-observable (to me) that shuffle has bias / common sequences / etc

Can you provide some examples of that? So far all we have is this claim of yours that it's human observable...

**Comment by cemeyer** [comment]
I suspect y'all may be right that this is just a human perception thing and really the shuffle order is sufficiently random with `rand()`.  A few questions / responses, then we can probably close this out.

@rossy, I can't argue with your results and don't have empirical data on my end.  I just have some methodology questions about your trials.  Did you seed once and do the trials back to back on that state?  Or pick 1 million seeds and run each trial with independent seeds?  If the latter, how were the seeds selected?  If they were chosen from some other RNG, rather than something more like current time in microseconds, that _might_ give better results than actual.  (Might not!)  I'm looking at a playlist of around 1000 items rather than 50, but I doubt that makes much difference.

@CounterPillow, It's funny you mention MT.  I have been doing some PRNG research lately and as I understand it, Mersenne Twister is actually a pretty bad PRNG in all respects — although I'm not claiming it's worse than a 32-bit LCG.  It has a huge state, isn't particularly fast, and [still manages to fail statistical tests in suites like TestU01/BigCrush and PractRand](https://www.johndcook.com/blog/2017/08/14/testing-rngs-with-practrand/).  You can make [a faster, higher-quality generator with only 128 bits of state and a trivial step function](https://lemire.me/blog/2019/03/19/the-fastest-conventional-random-number-generator-that-can-pass-big-crush/).

> Even if it were the case that rand was abhorrent on FreeBSD, that's really something FreeBSD should fix

I don't disagree: I authored https://reviews.freebsd.org/D23290 .

@avih, I don't have any way of capturing statistically significant amounts of data and am inclined to believe that it is just classic human brain perceiving patterns where none really exist.

**Comment by avih** [comment]
Well, the way to check is to patch your build to use something you consider better than `rand()`, then test yourself blindly with the two builds. If you can tell with reasonable success which has the better randomness, then maybe you're right. If not, then you're hallucinating.

You don't give examples, you only tell us to count on your ability to recognise bad randomness, so  just prove it to yourself first that you're right, then maybe others would listen.

I think it's time to close this unless there are objections.

**Comment by haasn** [comment]
I propose we switch to using RDRAND unconditionally.

**Comment by cemeyer** [comment]
@avih, Yes, I understand how to run a scientific experiment; but I can't spend the enormous amount of time required to do so.  I think you're taking a needlessly hostile tone; I'm not demanding or insisting on anything.  Like I already wrote in the first sentences of my most recent comment and the sentence you're responding to:

> I suspect y'all may be right that this is just a human perception thing and really the shuffle order is sufficiently random … we can probably close this out.
> I ... am inclined to believe that it is just classic human brain perceiving patterns where none really exist.
