### ISSUE TITLE
Control mpv properties from command line in Windows

### ISSUE THREAD

**Issue by pehojul** [mpv-player/mpv#7375]
Following this https://github.com/mpv-player/mpv/issues/2381

I can start mpv in Windows 10 with:

`mpv file.mkv --input-ipc-server=\\.\pipe\mpv-pipe`

and then I can pause mpv from command line while it is running:

`echo cycle pause >\\.\pipe\mpv-pipe`

I also found that the following works for increasing and decreasing the volume in Windows 10:

```
echo cycle volume +1 >\\.\pipe\mpv-pipe
echo cycle volume -1 >\\.\pipe\mpv-pipe
```

My 4 questions:

1) Is it possible to set the volume to a specific percentage while mpv is running in Windows? The commands I put above produce RELATIVE volume increments only.

2) Is it possible to jump, to the next file in playlist, from command line in Windows? 

3) According to the list of mpv properties in https://github.com/stax76/mpv.net/wiki/mpv-properties , there is a property called "lavfi-complex". Is it possible to use it to invoke and remove filters from command line in real time?? For instance, I tried in Windowds 10 `echo cycle lavfi-complex extrastereo >\\.\pipe\mpv-pipe` but nothing happens.

4) Where is the file "mpv-pipe" located  in Windows?

Thank you!!

**Comment by CounterPillow** [comment]
1. Yes, use `set volume 130` for example to set the volume to 130%.

2. Yes, see [List of input commands](https://mpv.io/manual/master/#list-of-input-commands). You're looking for `playlist-next`.

3. You can use `set lavfi-complex extrastereo`

4. I'm no Windows user but `\\.` looks like the current working directory to me, so probably in a `pipe` subdirectory of wherever you're `cd`'d to.

In general I recommend you read [The JSON IPC docs](https://mpv.io/manual/master/#json-ipc), you can do a lot more by using the JSON IPC instead of just shoving flat input commands into the IPC socket.
