### ISSUE TITLE
autoload.lua: how to create a hotkey for switching videos?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#7385]
https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua

Can a hotkey be created? Also, I'd prefer to only add support for manually moving to the next video with this hotkey and not change the default behavior (mpv closes after playback).

**Comment by avih** [comment]
The way to define keyboard bindings in mpv is via `input.conf`. I don't see how it's related at all to autoload.lua.

Care to be just tiny bit more specific about what you're trying to do? what you tried already? etc

**Comment by zc62** [comment]
`ENTER` is the default key to `playlist-next`. See https://github.com/mpv-player/mpv/blob/master/etc/input.conf

**Comment by Akemi** [comment]
they most likely doesn't know exactly how autoload.lua works, eg it loads next/prev files into a playlist. they probably assumed that it loads the next files on end of the current file.

what he wants is only adding/loading the next file(s) on a keypress, so that the 'standard behaviour' that only the initial loaded files are being played and mpv closes afterwards.

you can most likely just replace the last line:
```
mp.register_event("start-file", find_and_add_entries)
```
with:
```
mp.add_key_binding("X", "find-and-add-entries", find_and_add_entries)
```
and change MAXENTRIES to 1, to only add one next playlist item.
