### ISSUE TITLE
load C Plugins form the current working directory

### ISSUE THREAD

**Issue by sdg31** [mpv-player/mpv#7386]
Trying to use the [simple](https://github.com/mpv-player/mpv-examples/blob/master/cplugins/simple/simple.c) c-plugin, as well as any other c-plugin yields the following error:
> C plugin error: 'simple.so: cannot open shared object file: No such file or directory'
> [simple] Could not load SO plugin simple.so

I ran it with
`mpv --script=simple.so ~/Videos/some_video.mp4`

I built the current version of mpv with
`./waf configure --enable-cplugins --disable-vulkan`

I'm using Arch Linux and compiled simple.c exactly as described in the comment.

log file [on pastebin since github refuses to upload]
https://pastebin.com/3dv8dYei

**Comment by CounterPillow** [comment]
Is `simple.so` in `/home/sam/.config/mpv/scripts/`?

**Comment by CounterPillow** [comment]
It looks like mpv doesn't load C-Plugins from the current working directory unless you specify `./simple.so` as the scripts option, which appears to be a bug/oversight to me.

**Comment by sdg31** [comment]
that does seem to be a proper workaround though, thank you.

**Comment by Ckath** [comment]
since the path is just directly passed to dlopen() it does work as intended™

dlopen(3):
> If filename contains a slash ("/"), then it is interpreted as a (relative or absolute) pathname. Otherwise, the dynamic linker searches for the library as follows (see ld.so(8) for further details)

the *further details* being ld looking in `LD_LIBRARY_PATH`

sure if it is actually intended behavior to have `simple.so` look for it in your cwd, instead of the library path, it can easily be changed in scripting.c but that'd also mean a user could (accidentally) use a local lib.so when specifying lib.so with the intend of it being used from library path.

I also wouldn't call it too far fetched to tell people to throw their custom c plugin libs in a directory from `LD_LIBRARY_PATH`, or add their custom mpv plugin dir to it.

**Comment by Akemi** [comment]
this seems like intended behaviours.
