### ISSUE TITLE
How to prevent frame delayed in Gnome Wayland?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#7394]
I always get frame delayed in Gnome Wayland session, how to prevent it?
It also has lots of Vsync Jitter.
Wayland is the future, I really hope it works.

**Comment by Akemi** [comment]
this isn't really a question but an issue. why not use the proper issue template?

gnome is known to maker problems with mpv.

**Comment by laichiaheng** [comment]
So...they are the earliest team to implement the Wayland stuff for their desktop environment, but also the worst implement out there?

**Comment by Akemi** [comment]
i can't speak out of experience but what i gathered from the discussions, gnome is bad and causes many unique issues.

**Comment by Dudemanguy** [comment]
Gnome doesn't play well with mpv and has unique problems no other compositor has. It sounds like you might be suffering from [this issue](https://gitlab.gnome.org/GNOME/mutter/issues/957). If you really want to use wayland, give Sway or Weston a whirl since they currently have the best playback in mpv right now (presentation time).

**Comment by travankor** [comment]
@laichiaheng [Wayfire](https://github.com/WayfireWM/wayfire) works very well with mpv.

**Comment by laichiaheng** [comment]
> @laichiaheng [Wayfire](https://github.com/WayfireWM/wayfire) works very well with mpv.

Can I use it in Gnome?

**Comment by laichiaheng** [comment]
They said that they had improve it in Gnome 3.34.3, has anyone tried it?

**Comment by Dudemanguy** [comment]
Gnome fixed their frame callback in 3.34.2, so it should be better than before, but the vsync spikes and mistimed frames still occur in 3.34.3 anyway. I'd be curious to know what the source of the problem is. Presumably all applications that constantly spit out frames would be affected, but mpv just happens to be a special case since it's pretty easy to notice when your frame timings are messed up.

Regarding different compositors, there's no "mixing and matching" in wayland world. So switching to sway, wayfire, weston, plasma, or whatever requires completely changing your window manager as well.

**Comment by travankor** [comment]
>I keep failing to build it in AUR.

The AUR package looks broken. Maybe try the [-git version](https://aur.archlinux.org/packages/wayfire-git) in AUR or git clone and manually build it with meson (Make sure to install wf-config and wf-shell if doing it manually).

>Can I use it in Gnome?

FWIW, I mostly use Sway, but  [Wayfire](https://www.youtube.com/watch?v=LcWlpo5m4XU) looks similar to Gnome, which is why I suggested it.

**Comment by laichiaheng** [comment]
@Akemi @Dudemanguy @travankor I still have the Vsync Jitter spikes problem when the gpu-hq is enabled in Weston.

**Comment by Dudemanguy** [comment]
>Radeon RX 580

This is concerning. That card should certainly perform well. My RX 550 has no performance difference from xorg and I run it with relatively demanding settings. Try benchmarking the wayland backend with the settings listed [here](https://haasn.xyz/posts/2017-10-05-how-to-benchmark-mpvs-raw-throughput.html). You just need to add a `wayland-disable-vsync=yes` line to that. What FPS to you get back on that file in wayland? What does Xorg report?

**Comment by laichiaheng** [comment]
@Dudemanguy About 499~580 on Gnome Xorg, 60 on Meson Wayland.

**Comment by Dudemanguy** [comment]
Yeah that's pretty horrible. What happens if you disable all hwdec? I've never played with vaapi-egl.

**Comment by laichiaheng** [comment]
> Yeah that's pretty horrible. What happens if you disable all hwdec? I've never played with vaapi-egl.

I forgot to add wayland-disable-vsync=yes, I have disabled all hwdec.

**Comment by Dudemanguy** [comment]
Oh duh, I guess I should have noticed since you reported 60.

**Comment by laichiaheng** [comment]
> Oh duh, I guess I should have noticed since you reported 60.

The range from the Wayland report is huge, and it jumps too fast that I can't see it clearly, it's about 3XX to 6XX.
If I enable the VAAPI hwdec, they both are 2XX to 3XX.

**Comment by Dudemanguy** [comment]
That range does seem a little unstable, but it should be fine for normal playback. Could you try looking at frame timings (shift + i) without any of the bench profile stuff? Are there random frames in there that take a very long time compared to everything else? With a 60HZ monitor, you'd expect a frame every 16.666 ms (or 16666 us), but a little more or less than that number is OK as long as it's reasonable consistent. If there are big spikes in there, that might explain what you're seeing.

**Comment by laichiaheng** [comment]
@Dudemanguy Do you mean with my own config?
Xorg: fresh 17XXX/17XXX/18XXX, redraw: 6XXX/6XXX/6XXX

**Comment by Dudemanguy** [comment]
Hmm, I did notice that Weston had some slight jitter spikes if I cranked up the rendering settings so fresh frames took longer than 16666 (this doesn't seem to happen in sway FWIW). However, I did try setting `--wayland-frame-wait-offset=0` (the default is 1000) and this seemed to entirely go away. How is playback for you with that option set to 0?

**Comment by laichiaheng** [comment]
> Hmm, I did notice that Weston had some slight jitter spikes (nothing too severe though) if I cranked up the rendering settings so fresh frames took longer than 16666 (this doesn't seem to happen in sway FWIW). However, I did try setting `--wayland-frame-wait-offset=0` (the default is 1000) and this seemed to entirely go away. How is playback for you with that option set to 0?

The frame timing is lower 14XXX/14XXX/15XXX, but there still is jitter spikes.

**Comment by Dudemanguy** [comment]
Hmm well I might remove that option anyway. The original reason I added it was because weston without presentation time behaved badly in certain scenarios without an artificial delay. It might not be necessary anymore since presentation time seems to take care of that scenario. I'll double check the other compositors to see if there's any utility.

>Sway seems to be difficult to set up, I can't click on anything in it.

Yeah it's a tiling WM. It's all keyboard oriented.

I'm not sure what the problem is in your case. I'm very hesitant to call it a driver bug since I've never heard of anyone having problems like this with amdgpu before. It seems similar to a known [intel issue](https://github.com/mpv-player/mpv/issues/7106) at least. However, my card is very similar to yours and doesn't have this issue.

**Comment by travankor** [comment]
>I got black screen in Wayfire.

You probably need to install [wf-shell](https://aur.archlinux.org/packages/wf-shell/). And then create config files in `~/.config/wayfire.ini`; `~/.config/wf-shell.ini`

Github website for wayfire has the default example [configs](https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini.default).

**Comment by Dudemanguy** [comment]
@laichiaheng: Could you test #7427? Is vsync jitter smoother for you with that approach?

**Comment by laichiaheng** [comment]
> @laichiaheng: Could you test #7427? Is vsync jitter smoother for you with that approach?

I don't know, but I still see the Vsync spikes.

**Comment by Dudemanguy** [comment]
Hmm bummer. That seems robust for me when I play around with different settings.

**Comment by newperson1746** [comment]
What's interesting is that this behavior only just showed up on mpv from ubuntu 20.04 -proposed a few days ago and it runs gnome 3.36.1. Just a week or two ago, before updating, I had 100% perfect and beautiful interpolation on a 59.94hz monitor of a 23.976 movie. What changed?

**Comment by Dudemanguy** [comment]
What gnome version and mpv version were you using before?

**Comment by newperson1746** [comment]
mpv latest correct, from ppa. Seems to not be an issue with MPV though, as even with the main repo version the stutters occur in exactly the same manner. I distinctly remember having flawless interpolation on 3.35.92 (and whatever corresponding graphics drivers matched at that time)

**Comment by newperson1746** [comment]
Installed plasma-wayland on the 7870 computer, can confirm interpolation is flawless on plasma-wayland-- just as it was in gnome-wayland before ~3.35.92/corresponding package versions on ubuntu (gnome 3.36 rc2)
