### ISSUE TITLE
command for saving a verbose log for pseudo-gui mode

### ISSUE THREAD

**Issue by Akemi** [mpv-player/mpv#7396]
it seems like there is a general problem for people providing a log file when used in pseudo-gui mode, especially macOS users and the bundle. 

it would be nice to have a command that saves an in-memory verbose log to the Desktop/Home dir/dedicated log dir in .config/mpv. similar to [console.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/console.lua#L740-L774) we would need to keep a history of all verbose log messages (or a specified higher log level, if we don't already do so). 

for macOS i could add that command to the Help menu, people would be able to save a log even after opening mpv and without specifying log-file option. admittedly this is only helpful for generating logs that don't crash mpv.

maybe it's even feasible to save that log automatically to disk, only when in pseudo-gui mode, or even on crash/periodically (to not pointlessly writing to disk all the time).

i am not sure how feasible such a feature is or if it would be a waste of memory.

**Comment by wm4** [comment]
--log-file was originally intended for this, but I still had enough reservations to write a log to disk by default.
console.lua uses a feature to buffer log messages in memory before a script reads them, but currently it only works for one script, and once console.lua reads the messages (when the console is opened), the messages are gone.
I'm not exactly sure what we can/should do here.

**Comment by Akemi** [comment]
your reservations about writing a log to disk by default are warranted. we still have an open issue about the default log redirect on macOS #1590 (which i hoped to solve/remove completely with this proposal), with which i had some problems before. in the case of a big log spam it made mpv/the system a bit more unresponsive due to the many consecutive disk writes. it manifested in some more dropped frames probably, due to some IO bottleneck(?), and back then it also deactivated display-resample because of that.

**Comment by wm4** [comment]
Yeah that sounds worrying.

So, available ideas:
a) enable log-file by default, but add an extra thread that buffers the writes (won't be able to deal with throughput issues, but will still reduce latency spikes caused by waiting for disk)
b) steal console.lua's log buffer and write to disk (if the console was opened before, these log messages wouldn't be available anymore)
c) add the feature to console.lua itself (make it writes its own backlog to disk)
d) add a OSX menu entry or so, which simply toggles the log-file default (off by default, user would enable it, and if it causes additional problems, explicitly disable it via menu again)

**Comment by Akemi** [comment]
a) seems okay'ish but not optimal
b) seems unexpected from a users standpoint
c) would probably be the best from a users standpoint, atm it only keeps/requests "terminal-default" and not the verbose right(?). we wouldn't really want verbose output for the console overlay within the mpv window i assume. would need some message filtering for file output/console output.
d) could do that, though we wouldn't be able to save a log of events that already happened, eg it would be nice to save a complete log after the issue actually happened. that is helpful for hard to reproduce issues.

**Comment by wm4** [comment]
Well, you could start the player with "-v -v" or so, which would elevate the log level console.lua  uses (due to using "terminal-default").

There's only a special log buffer with "terminal-default" log level by default, which records early log messages. console.lua always picks up this buffer. This whole thing is just because I didn't want to waste memory for a big log buffer that is probably never needed. With the current log level it wastes only a few bytes, but still gets important stuff like error and warning messages.

**Comment by Akemi** [comment]
maybe just "-v" would be enough. though would we want every pseudo-gui to have an elevated log level or at least having console.lua show more logging depending on the way it was started?

**Comment by wm4** [comment]
One problem is that console.lua currently can't even seek back.
I'm starting to think maybe a) would be decent?

**Comment by Akemi** [comment]
yes, a) would also definitely be an improvement. i would be able to get rid of that redirection mess and user would have a possibility to get a log after something happened.

just wondering where it should be located and if it should only be activated for pseudo-gui usage.

**Comment by wm4** [comment]
I think this is solved with the log-file change. (Not ideal, but will do it.)

**Comment by Akemi** [comment]
yes.
