### ISSUE TITLE
Making archive:// files run fluid, how to decrease the wait time between images in a .zip file? 

### ISSUE THREAD

**Issue by nnadd** [mpv-player/mpv#7418]
**Important Information**

    mpv version: 0.31.0
    Linux Distribution and Version: OpenSUSE
    Window Manager and version: KWin 5.17.5
    GPU driver and version: Intel GPU from kernel 5.4.13

Just like the title says, I have a bunch of zip with a lot of CG files in them, mostly just a bunch of jpg (pixiv, etc) in them, mpv waits 1 second before moving to the next jpg in the archive, is there any way to get this wait time down to zero so it looks like it's actually animated?

**Comment by CounterPillow** [comment]
Sort of. You can use `--image-display-duration=0.03` (or replace `0.03` with 1 divided by the framerate you want) to only wait that specific amount inbetween them. However mpv will still treat them like individual image files instead of one video file, and the frame timing will probably not be very accurate.

To treat a series of images as an actual video file, you can use the `mf://` demuxer and `--mf-fps`, but to the best of my knowledge it doesn't support loading from archives or at least not in any way that I've tried.

**Comment by wm4** [comment]
mf:// would need support for playlists to do that.
