### ISSUE TITLE
Framedrop and audio desync issue

### ISSUE THREAD

**Issue by DimenP** [mpv-player/mpv#7424]
### Important Information

Provide following Information:
- mpv version 
0.27.2
- Linux Distribution and Version
  Ubuntu 18.04 LTS
- Source of the mpv binary 
ppa:mc3man/mpv-tests
- If known which version of mpv introduced the problem
.27.2
- Window Manager and version
Idk
- GPU driver and version
Idk
- Possible screenshot or video of visual glitches
no glitch

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
played a movie with mpv.
### Expected behavior
smooth 30fps playback like on the ubuntu default video player.
### Actual behavior
laggy playback and video-audio desync occurs when there is lag.
### Log file
[mpvlog.txt](https://github.com/mpv-player/mpv/files/4144225/mpvlog.txt)
The issue will be closed for ignoring the issue template.

### Sample files

[mpv.conf](https://github.com/mpv-player/mpv/files/4144227/mpv.txt)

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wm4** [comment]
We don't add these things to the issue template just for fun.
Effortless bug report -> effortless handling of it.

**Comment by CounterPillow** [comment]
It looks like your mpv version is out of date. When you install mpv from your distribution's repositories, you are receiving an mpv version that the maintainers of your distribution have chosen. For some distributions with a "stable" release cycle (Debian, Ubuntu, CentOS, ...) this version is out-of-date on purpose, and there is nothing we can do about this. Just because your distribution has no update for the mpv package does not mean that it is the newest version of mpv.

We do not support out of date mpv versions, as we do not wish to spend debugging and development efforts on versions of mpv that we consider to be superseded. If you want to use a version of mpv that we do support, your best bet is to use [mpv-build](https://github.com/mpv-player/mpv-build/) to statically build your own mpv binary.

If you'd rather stay with your out of date version of mpv, then all support inquiries should be directed at your distribution's maintainer of the mpv package, not towards us. We cannot help you with your problems in that case.
