### ISSUE TITLE
support keypad in REPL

### ISSUE THREAD

**Issue by shabahengam** [mpv-player/mpv#7431]
it would be great if REPL support keypad.right now it doesn't support KP[0..9],KP_ENTER,KP_DEC

**Comment by wm4** [comment]
It should work if you enable numlock.

**Comment by shabahengam** [comment]
numlock is enabled.
![image](https://user-images.githubusercontent.com/53096747/73872808-aa0b8580-4865-11ea-89bf-4d89ff073e93.png)
numlock in disabled.
![image](https://user-images.githubusercontent.com/53096747/73872839-b98ace80-4865-11ea-89dd-90d443412fc4.png)
mpv version: 0.32.0-16-g13624b5

**Comment by wm4** [comment]
Not expected, probably a different OS.

**Comment by shabahengam** [comment]
Sorry for didn't mention that.
OS: Void Linux x86_64
Kernel: 5.4.17

**Comment by wm4** [comment]
Works for me, also "Linux".

**Comment by shabahengam** [comment]
If there's anything I can do to help, please let me know (other than changing my distro :) )

**Comment by garoto** [comment]
It doesn't work on my Winblows (8.1) as well. With my regular config, it will execute whatever binds I have setup for the numpad and with `--no-config`, just outputs `[input] No key binding found for key 'KP[*]'`

**Comment by wm4** [comment]
Actually the "works for me" was wrong. I remembered incorrectly. It always produces KP_* on x11 too, no matter the numlock state. Oops. (I can't easily test because I mapped the numlock key to something else.)
Anyway, the question is what KP_* should do. Since mpv apparently ignores numlock, this is even worse. Normally, KP_4 for example produces "4" with numlock on, but is equivalent to the "left" key if numlock is off.

**Comment by avih** [comment]
i think it can also depend on the terminal, and whether or nor keypad mode is on.

**Comment by avih** [comment]
> Anyway, the question is what KP_* should do

I think map them to numbers, +/-/*/ / = and enter?

**Comment by wm4** [comment]
> I think map them to numbers, +/-/*/ / = and enter?

Read my post. Numlock.
