### ISSUE TITLE
VO gpu: toggle fullscreen doesn't work since 0.31.0

### ISSUE THREAD

**Issue by mag01** [mpv-player/mpv#7439]
### Important Information

Provide following Information:
- mpv 0.32.0
- macOS 10.14.6
- Source of the mpv bundle https://laboratory.stolendata.net/~djinn/mpv_osx/

### Reproduction steps

Toggle fullscreen doesn't work in the GPU VO mode since 0.31.0 - just nothing happens. I can start into the fullscreen mode, but can't switch between the fullscreen and windowed modes when starting normally. In LIBMPV VO mode it works.

But since the LIBMPV VO mode performs worse than the GPU VO (as was reported by someone else in #6829 (I've got an older MacBook Air 11" Mid 2012 with the Intel Core i5-3317U 1.7GHz CPU, where such differences are easily visible) I'm going back to 0.30.0 for now.

My **~/.config/mpv/mpv.conf**:
```
hwdec=videotoolbox

sub-codepage=utf8:cp1250

keep-open=yes
autofit-larger=90%

vo=libmpv

script-opts=osc-layout=box,osc-deadzonesize=0,osc-minmousemove=3
```

**Comment by wm4** [comment]
It was broken because nobody wanted to fix it.

**Comment by wm4** [comment]
I repeat: nobody wants to maintain this code, so when an internal change required to update the code, nobody did it.

**Comment by Akemi** [comment]
the mechanism for signalling to the core had to be changed and i am not going to work on a deprecated backend, which mpv also warns about.

also that referenced issue is a joke.

**Comment by mag01** [comment]
It isn't a joke, I can confirm the same results myself. Your attitute is a joke. A bad one.

**Comment by wm4** [comment]
Well, we could just disable the issue tracker.
Would probably make this project more fun.

**Comment by mag01** [comment]
wm4: Seeing how you tend to communicate here and just close issues without any meaningful explanation that wouldn't make much difference to how things are now.

**Comment by wm4** [comment]
No, it's "not going to be fixed" because it's "deprecated". It's deprecated and broken because nobody wants to fix it, not more and not less. The swift backend was written to accommodate Apple's incompetent bullshit that broke everything for no reason in the first place. Otherwise we wouldn't have to rewrite everything. God, I need to find out where Steve Jobs grave is, so I can piss on it.

**Comment by wm4** [comment]
I looked at this issue, the user simply thought he knew better, didn't acknowledge information that said otherwise, had bogus arguments, and was also rude.

Anyway, do you volunteer to maintain the cocoa backend?

>wm4: Seeing how you tend to communicate here and just close issues without any meaningful explanation that wouldn't make much difference to how things are now.

I'll discuss it.

**Comment by mag01** [comment]
I see why it's been deprecated, but it's slightly different matter (not so directly related to the reported issue). When one reports "something is now broken but was working before" then simply address that in the response (it's deprecated and thus unmaintained code, we're sorry, but the libmpv backend is the way to go due to changes in the OS). If you want to go into more detail (why we all got where we are) then you can, but that's secondary. Answering with "It was broken because nobody wanted to fix it" is really weird.

**Comment by Akemi** [comment]
@mag01 yes this issue is a complete joke. like already mentioned there, it tries to compare completely different things that are not comparable. it tries to find faults in minuscule things that are definitely not the problem. i never said that there isn't an issue and i am still open to try to fix that issue, but only if there is some constructive discussion and not everything i say and bring up is just plainly ignored or my questions are not answered.

i admit i could have handled the situation better initially, though the same goes for the issue creator.  he basically demanded of us to remove the new libmpv backend, even though there still is an alternative that i didn't remove just deprecated. he was especially passive aggressive about the swift and layer usage. the latter is not even my fault but Apple's for fucking us over.

**Comment by mag01** [comment]
I know the exchange in that issue has gone a bit nasty at places, but the reporter didn't start it if you look at it carefully.
Anyway after some time I could fix the fullscreen issue with the gpu vo, I had to spend much more time than it would take someone who works with that code on frequent basis, but whatever.

Akemi: As I understand (what was going on in that other issue) the one thing he pointed out was just one example, not that he was pointing at the sole cause of the performance difference.

**Comment by Akemi** [comment]
the reporter started it by ignoring the issue template and not providing the informations we ask for. i personally think it's respectless towards us maintainers to not even take the time to write up a proper issue report.

tbh his comments don't leave much room for interpretation. he completely tried to pinpoint the problem onto swift and the layer usage. he even passively demanded of us to remove an alternative that works.

> You just shouldn't use Swift and CAOpenGLLayer. Don't turn mpv into another VLC.

**Comment by wm4** [comment]
> Akemi: As I understand (what was going on in that other issue) the one thing he pointed out was just one example, not that he was pointing at the sole cause of the performance difference.

That's less than constructive, because even though these things might be slightly less efficient, they don't contribute to the performance problem at all. It's like someone suggesting that a piece of Python code should be rewritten in assembler, all while the code uses bubble sort.

> The performance difference is especially visible at older hardware and maybe you don't have any such to see it yourself as your results shown in that issue contradict his. 

Haven't we repeatedly said that the swift backend fixes performance issues for most users.

**Comment by mag01** [comment]
> the reporter started it by ignoring the issue template and not providing the informations we ask for. i personally think it's respectless towards us maintainers to not even take the time to write up a proper issue report.
> 
> tbh his comments don't leave much room for interpretation. he completely tried to pinpoint the problem onto swift and the layer usage. he even passively demanded of us to remove an alternative that works.
> 
> > You just shouldn't use Swift and CAOpenGLLayer. Don't turn mpv into another VLC.
It (incomplete issue report) happens - just ask for the missing information etc, but avoid derailing the discussion and don't go the way of "wtf" comments. I keep getting even more vague (1 brief sentence) issues all the time. I can scream and swear privately, but in the end I just return the issue to the reporter with (more specific) request for more information.

It seems you're reading too much into his comments. Just try to explain better (right from the start) why one backend is deprecated, why it's replacement is the way it is and if you're willing to try to optimize it, try to go that direction in order to get somewhere. It took few nasty and unnecessary exchanges to get to the point where thigs should've started and any doors for possible optimization work were closed by then.

wm4: See the above paragraph. Take (what he pointed out) just as some simple (or generic) example, nothing more than that. No need to spend hours and lengthy discussion on that, but there may be still things to improve with some real impact.

**Comment by mag01** [comment]
And maybe just explain things better somewhere in the docs? For example in the release notes or reference manual there isn't much about the gpu vs libmpv VOs.
Actually this (in the hwdec section):
> videotoolbox: | requires --vo=gpu (OS X 10.8 and up),             or --vo=libmpv (iOS 9.0 and up)
even refers to libmpv VO use at iOS only which seems confusing.

**Comment by wm4** [comment]
>It seems you're reading too much into his comments. Just try to explain better (right from the start) 

I don't think so, he had a "strong" opinion and seemed to know better, which he didn't. He started right with his most likely meaningless graphs.

**Comment by mag01** [comment]
He did show his system basic data. If I'd go the way of reporting that thing I'd provide something similar. I wouldn't bother with graphs, but in the end there would be similar kind of information to show where things are. If you want something else / better, just ask for it / describe what you need. There's always some way to go.

**Comment by wm4** [comment]
> He did show his system basic data. 

No, he did not. We still don't know what his hardware is at all. He did not provide a log, which is essentially mandatory. The issue template even warns ``The issue will be closed for ignoring the issue template.``. That's because we get so many bug reports where we have to "force" users bit by bit to provide the information we asked in the first place. This is getting pretty boring and annoying with time. Why the fuck would we spend our free time to act like we're working for a tech support call center?

**Comment by CounterPillow** [comment]
oh are you guys talking about the moron who pointed at some CPU code disassembly to argue that the GPU code was running slower?

Please stop cargo-culting perceived placebo problems from utter idiots.

**Comment by Akemi** [comment]
i will be upfront. this is already leading to nothing that way and starts to waste my time. the only thing we discuss here are semantics and behaviour instead of actually tackling any kind of problem. if you really want to have anything changed/problems solved then please open a proper issue instead of discussing what the best approach is to discuss something. i don't feel like or see a need to justifying myself any more i already did and i already said what i wanted to say. i think the way you try to make your point is flawed and any more arguing against that will just lead in a for me pointless back and forth.

docs are always a subject for improvements. if you feel like there is information missing, you either ask about it via an issue or irc. for a start this commit and the linked issues at the bottom have quite and extensive explanation about the reasons https://github.com/mpv-player/mpv/commit/c5e4538bc4b63f02bf89f62aa25a37b9eb0c0316#diff-436e4a8a7b261e9928a4f6a71e5ae3c5). the #2392 issue was one of the main reasons.

**Comment by mag01** [comment]
wm4: As I stated, I have to deal with much less detailed issue reports on a frequent basis and still manage to get somewhere. You spent a lot of time on that issue already. Instead you could just request any information you were missing. The reporter seemed to be communicating so he'd likely provide that.

Akemi: Yes it wasn't going anywhere the entire time (I felt like walking in circle most of that time), but that was obvious. I can only say that I disagree with your (overall) approach here etc (and see the comment from CounterPillow), but if it's your choice, then so be it. I don't feel like I'm going to bother reporting any more issues here now (I even have got the fullscreen toggle working again, but not really going to contribute, and since this VO is deprecated on your side it's going to slowly die anyway so it doesn't matter much) because of that. It's a weird place over here. At least thanks for referring to some additional information regarding the backend move. That was really useful and it explains something.

**Comment by wm4** [comment]
Feel free to volunteer as issue manager for this project then. As you see, we don't really like triaging issues and trying to beg users for providing required information.

**Comment by CounterPillow** [comment]
So you're willing to maintain the backend for yourself but you won't upstream the changes? Seems like an odd move.

**Comment by wm4** [comment]
Well in exchange he won't annoy us anymore.

**Comment by Akemi** [comment]
i added some further informations to #6829. it's basically what i said, it's out of our hands and entirely in Apple's side.
