### ISSUE TITLE
Mpv build in macos

### ISSUE THREAD

**Issue by Macosss** [mpv-player/mpv#7448]
Hello friends.
I have the last version of mpv and macos catalina. My machine is a macbook pro 13inch 2017.
I am a movie lover.i download the mpv as followed.

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
And after
brew cask install mpv

I have issues with all movies. The motion frozed every second. I create a file mpv.conf with as following

scale=bilinear
cscale=bilinear
dscale=bilinear
scale-antiring=0
cscale-antiring=0
dither-depth=no
correct-downscaling=no
sigmoid-upscaling=no
deband=no
hwdec=auto

After that, i don't know if just happens or the file helps a lot, but now the motion is ok but in hdr i have the same problem with motion.

Is there a way to solve this problem?!

Thanx a lot

**Comment by CounterPillow** [comment]
Your issue has been closed because you have ignored the issue template. Issue templates will appear when you open a new issue, and choose which category of issue you want to report. Currently, a GitHub bug prevents this choice from appearing if you're not logged in at the time you click on the new issue button, so if you never saw any template, that may be why.

Our closing of this issue does not mean that the problem you are experiencing is not real or that we somehow are being rude to you, it's simply a matter of issue triage to separate those we can do something about (ones that fill out the issue template) from those that waste everyone's time by not providing us with the information we explicitly and very clearly ask for (yours).

Following our established processes helps you get your issue resolved quicker, and helps us in identifying the issue. If you are unwilling to follow this simple process we are unwilling to have you on our issue tracker.
