### ISSUE TITLE
Movie filter and Webcam (or TV Tuner Card) in Windows

### ISSUE THREAD

**Issue by pehojul** [mpv-player/mpv#7468]
I am able to view my webcam stream live in Windows 10, using

`mpv av://dshow:video="Integrated Camera"`

(1) Instead of using "av://" as above,  is there any way of viewing the webcam using the "movie" filter (in Windows 10) in a similar way as opening a picture with the following mpv command?

`mpv --lavfi-complex="movie=example.jpg[vo]"`

The reason why I want to use the "movie" is that I am using mpv in SMPlayer. I need to apply, in real time, combined filtering operations to both the webcam stream and the videos that SMPlayer itself opens in Windows 10.

(2) I am assuming that I can use a command similar to mpv av://dshow:video="Integrated Camera" in order to open a TV Tuner Card in Windows, just by replacing "Integrated Camera" with the name of my USB DVB-T TV Card device. How can I tune the frequency/channel in Windows? Can this tuning (selecting a frequency) be done using the "movie" filter?

I did not find exact answers (for Windows) in mpv's documentation.

Thank you!!

**Comment by wm4** [comment]
``av://`` just delegates to the the ``libavdevice`` ffmpeg library. FFmpeg arguments (that affect this part) can be provided with ``--demuxer-lavf-o``. The rest is either in the ffmpeg decs, or not documented at all.

Instead of the ``movie`` filter, you can try ``--external-file``, which will add extra sources as video tracks, which you can reference as inputs in ``--lavfi-complex``. Whether this works better or worse than ``movie``, I don't know. In mpv it's not possible to give each ``av://`` use separate options though.
