### ISSUE TITLE
UHD/4K 50 fps playback with GT 1030 2GB

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#7478]
This is not a bug report or feature request, just a notification about an efficiency problem that exists in **all** software players except Kodi, only Kodi can fluidly hw decode and render UHD/4K 50 fps with a GT 1030 2GB card. Fortunately I have only very few such files so it's not a real problem for me, my next video card will be much more powerful.

**Comment by CounterPillow** [comment]
ok

**Comment by jeeb** [comment]
I am just guessing that since you flagged the thing as Windows, you mean the D3D11 output for the GPU VO. You'd have to have that sort of hardware as well as the will to profile D3D11 to figure out where the rendering time is going.

If there's no apparent bottleneck in what mpv does outside of the shaders, then it's just slow rendering due to actually having to use shaders - sorry. mpv's core idea is to do correct rendering through shaders, instead of passing the video to the GPU's hard-coded rendering interface and hoping that it will show the video correctly (which without looking at the code I would guesstimate Kodi does since it most likely prioritizes performance).

If there is a bottleneck somewhere that is actually under the control of mpv, that's a whole other point of discussion. But as noted, actual profiling would be required. 

It's all about the priorities. Some prioritize performance, others prioritize having control of the render output. This is also the reason that a GTX 1080 just can't handle 4320p, even though the decoder is running around the user in circles :P . Larger resolutions, more and more calculations and memory bandwidth required.

**note:** For linux there's some compatibility VOs like vaapi and vdpau, which do exactly that. They throw the decoded video into the GPU's own rendering pipe line. Thus you lose all control over the result, but for very low-power graphics hardware it can be the only way to show 2160p video :P . For D3D11 there is no such thing as nobody has been interested in implementing anything like that.

**Comment by wm4** [comment]
Could try the zero-copy option (it's off for D3D11 AFAIK). Other than that, like JEEB I wonder if kodi isn't just using the fixed function video mixer instead of shaders.

**Comment by aufkrawall** [comment]
Perhaps it's amount of VRAM (2GB is really shitty for 4k) and exclusive fullscreen mode would help (but perhaps not, since it's Windows and who knows if DWM steals whatever regardless).

**Comment by philipl** [comment]
I'm fairly certain that 4k/60 worked ok with nvdec on Linux when I tested this hardware before. I don't have it anymore so cannot retry. Obviously many different variables, but nvdec works on windows so could try that.

**Comment by aufkrawall** [comment]
@stax76 You then may need to specify `--gpu-context=win` or `dxinterop` when using `gpu-api=opengl` for `--hwdec=nvdec`.

Though I guess nothing can beat Linux Xorg in fullscren without compositor.

**Comment by wm4** [comment]
I bet nvdec could work on D3D11, but if so, would have to be implemented.

**Comment by aufkrawall** [comment]
Ran a quick test: ogl-nvdec consumes 300MB more of VRAM than d3d11-d3d11va.

**Comment by stax76** [comment]
> Could try the zero-copy option (it's off for D3D11 AFAIK). Other than that, like JEEB I wonder if kodi isn't just using the fixed function video mixer instead of shaders.

`d3d11va-zero-copy=yes` does not help. I asked a Kodi developer what is used, did not yet reply.

edit:

`hwdec = cuda` apparently fixes it! 🙂

**Comment by philipl** [comment]
hwdec=cuda should not fix anything that hwdec=nvdec doesn't fix and nvdec is preferred.

**Comment by wm4** [comment]
Maybe it's just buffering?

**Comment by stax76** [comment]
`hwdec=nvdec` works too.

**Comment by philipl** [comment]
> I bet nvdec could work on D3D11, but if so, would have to be implemented.

Yes. You can write a D3D11 interop. I'd like to do it as an intellectual exercise, but don't have the time right now.

**Comment by stax76** [comment]
Sorry I did not notice before but `hwdec=nvdec` and `hwdec=cuda` use 70% CPU.

**Comment by philipl** [comment]
> Sorry I did not notice before but `hwdec=nvdec` and `hwdec=cuda` use 70% CPU.

Compared to what?

**Comment by stax76** [comment]
hwdec=yes uses 2% CPU but it's not fluid, with Kodi it's fluid at 3% CPU, file is:

V: HEVC, Main 10@L5.1@High, 3840x2076, 59.940 FPS, 20.4 Mb/s
A: AC-3, 640 kb/s, 6ch, 48.0 kHz

**Comment by stax76** [comment]
Sample:

http://www.mediafire.com/file/kbn371cc9oskjpi/GeminiMan.mkv/file

**Comment by philipl** [comment]
I don't know how that's possible if `vo=gpu` is in use. Even here on linux, in dumb mode, you're still looking at ~23% of a core (vs 200% for software decode). It's possible the windows architecture causes CPU usage to get attributed to other components like the compositor, depending on how its being rendered but 4k60 won't be low single digit CPU consumption.

**Comment by aufkrawall** [comment]
Having ~4% CPU load in total with both d3d11va and nvdec and Task Manager opened at the same time.

**Comment by aufkrawall** [comment]
@stax76 This is HDR video. You might want to set `--hdr-compute-peak=no` for weak GPUs.

Since it's a compute shader, it would also break dumb-mode?

**Comment by stax76** [comment]
GT 1030 does not support nvenc so it probably also does not support nvdec.

**Comment by aufkrawall** [comment]
Yes, it does:
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix

**Comment by stax76** [comment]
All tests using 4K full screen, looking at task manager:

hwdec = nvdec
gpu-api = opengl
CPU: 2%
Video Decode: 80%
3D: 50%
Memory: 100%
Impression: somehow fluid

hwdec = nvdec
gpu-api = d3d11
CPU: 70%
Video Decode: 0%
3D: 100%
Memory: 70%
Impression: completely fluid

hwdec = yes
gpu-api = d3d11
CPU: 2%
Video Decode: 80%
3D: 100%
Memory: 100%
Impression: completely jerky

Kodi
CPU: 2%
Video Decode: 100%
3D: 100%
Memory: 50%
Impression: completely fluid

**Comment by aufkrawall** [comment]
Have a look at doc and terminal output, it doesn't make sense yet to set up nvdec + d3d11.

**Comment by stax76** [comment]
Yes it's not implemented, does software decoding, it's fluid however, according to the test results it seems the problem has something to do with memory.

**Comment by philipl** [comment]
Your detailed summaries make much more sense. Previously you said `hwdec=nvdec` was consuming 70% cpu, but now we see it's not - and 70% happens when doing software decoding, which is what I'd expect.

I'm now not sure what the remaining question is. Those numbers all look reasonable. I guess you're asking about the jerky playback with `gpu-api=d3d11`?

**Comment by stax76** [comment]
> I guess you're asking about the jerky playback with gpu-api=d3d11?

Yes but also about opengl which is more fluid but still jerky.

A Kodi developer answered now and said there is an option for the render method, dxva or pixel shader, I tried both and both are totally fluid, both show wrong colors for my HDR file on non HDR hardware, pixel shader shows not enough color and dxva too much.

I would like to get a GTX 1660 card, unfortunately my current PC probably cannot fit such a card.

**Comment by stax76** [comment]
hwdec=d3d11va-copy is much better than hwdec=d3d11va, it's than on par with gpu-api=opengl but still far away from completely fluid like in Kodi.

**Comment by philipl** [comment]
Try `gpu-api=vulkan` with nvdec

**Comment by stax76** [comment]
I've tried dozens of settings today and nothing made it fluid, Kodi appear to always look most fluid.

I almost wanted to give up, found out some files don't drop frames, so I made some encodes and compared them, apparently the problem is the VUI/color/transfer metadata, files without such metadata drop **zero** frames.

**Comment by stax76** [comment]
There is also a codec difference:

x264 4K 60fps 10bit: no frames dropped
x265 4K 60fps 10bit: many frames dropped

**Comment by v0lt** [comment]
Which GT 1030 graphics card are we talking about?
What kind of memory is GDDR5 or SDDR4?

https://www.geforce.com/hardware/desktop-gpus/geforce-gt-1030/specifications
GDDR5 - 48 GB/sec
SDDR4 - 16.8 GB/sec

**Comment by stax76** [comment]
Apparently I found the solution:

hdr-compute-peak = no
d3d11va-zero-copy = yes

Zero dropped frames!

And mpv is the only player that is working so far, Kodi plays it fluid but colors are off.

Tried three different renderers in mpc and none is working.

> Which GT 1030 graphics card are we talking about?

https://www.msi.com/Graphics-card/GeForce-GT-1030-2GHD4-LP-OC/Specification
