### ISSUE TITLE
mpv crashes with hardware acceleration enabled

### ISSUE THREAD

**Issue by ViktoriiaKh** [mpv-player/mpv#7488]
mpv v0.32.0
macOS v10.15.3

When playing certain files mpv crashes if hardware acceleration is enabled.

I can reproduce this crash on two devices:
- Macmini6,2 with the Intel HD Graphics 4000 1536 MB graphics;
- MacBookPro14,3 with Radeon Pro 560.

Sample file
https://0x0.st/iqIq.ts

mpv also crashes when seeking in the file:
https://0x0.st/iqlG.mts

Crashes
https://0x0.st/iq0o.zip

**Comment by Akemi** [comment]
why did you ignore the issue template? please provide the info we ask for.

**Comment by Akemi** [comment]
both test files don't crash for me. first one i get a bunch of decoding errors and it fallsback to sw decoding

```
GVA info: Successfully connected to the Intel plugin, offline Gen9 
[ffmpeg/video] h264: reference picture missing during reorder
[ffmpeg/video] h264: Missing reference picture, default is 2147483647
GVA error: pushPicture, field pair frame number, m_second_field_parsed: 1 
[ffmpeg/video] h264: hardware accelerator failed to decode picture
[vd] Error while decoding frame (hardware decoding)!
GVA error: pushPicture, field pair frame number, m_second_field_parsed: 1 
[ffmpeg/video] h264: hardware accelerator failed to decode picture
[vd] Error while decoding frame (hardware decoding)!
[ffmpeg/video] h264: reference picture missing during reorder
[ffmpeg/video] h264: Missing reference picture, default is 65660
GVA error: pushMetaData, submitNewJobs
[ffmpeg/video] h264: hardware accelerator failed to decode picture
[vd] Error while decoding frame (hardware decoding)!
[vd] Falling back to software decoding.
```

the second one plays just fine.

since you didn't post a log, i will just assume that your ffmpeg build is too old/broken/whatever. it's an ffmpeg issue most likely anyway and you should report it to them.

**Comment by ViktoriiaKh** [comment]
@Akemi, I am sorry for not providing all the necessary information.
I’ve corrected the issue description.
I would be very grateful if you could take a look at this issue again.

**Comment by Akemi** [comment]
tried the same binary too from stolendata and still don't get a crash. just to be safe, try with `--no-config --hwdec=auto` and see if it still crashes. otherwise you could try ffmpeg directly, though since you use a downloaded bundle you most likely don't have the same ffmpeg on your system as the bundle was linked too. for testing ffmpeg and hwdec you can use `ffmpeg -benchmark -hwaccel videotoolbox -i /Volumes/AkemiData/Downloads/iqIq.ts -f null -`.

if you build ffmpeg yourself and it work with that command, you have to build your own mpv and link it against that ffmpeg. if ffmoeg doesn't crash but mpv does with the same ffmpge, only then it's most likely an mpv issue. otherwise it's ffmpeg.

you can also try this. bundle https://0x0.st/isop.zip i built some time ago and see if it also crashes.

**Comment by ViktoriiaKh** [comment]
Thank you for your reply.

1. Your bundle also crashes.
2. `ffmpeg -benchmark -hwaccel videotoolbox -i /Volumes/AkemiData/Downloads/iqIq.ts -f null -`
crashes with the segmentation fault.
See the ffmpeg console output https://0x0.st/ibKl.log
3. I’ve built ffmpeg and mpv from the latest sources. They also crash.

I`ve created the ticket: https://trac.ffmpeg.org/ticket/8541

**Comment by Akemi** [comment]
thanks for reporting the problem to ffmpeg.
