### ISSUE TITLE
Multiple video streams together

### ISSUE THREAD

**Issue by davidoskky** [mpv-player/mpv#7556]
I have various videos with two video tracks taken from two different cameras, it would be nice to be able to look at both the videos at the same time.
What I can do is open two separate instances of mpv and play one track on each of them; a problem occurs if I stop or increase the speed one of the two, as those won't be in sync anymore.

### Expected behavior of the wanted feature
When I open a file with multiple video tracks, I can specify with a flag or with a command that the interface should split in two, one of the two displays the first video track, and the second one another one.
It would also be great if these two displays where resizable.

### Alternative behavior of the wanted feature
When I execute the command two separate windows of mpv are opened, each one is displaying a different video track; these two tracks are synchronized, therefore if I stop one of the two the other stops as well.

**Comment by qmega** [comment]
See #3854.

[`--lavfi-complex`](https://mpv.io/manual/master/#options-lavfi-complex) seems like it does most of what you want. They won't be resizable with respect to each other, though. (You can change their relative sizes in the lavfi-complex definition, but you can't drag them around at runtime. You can resize the whole window and they'll scale together to fit like a normal video, though.)

**Comment by davidoskky** [comment]
Thank you and sorry for the duplicate issue, I really didn't find that.
Although not as flexible as dragging runtime would be, this way it works exactly how I wanted to, I just will have to fiddle a bit with the sizes...
I'll close the issue then.

**Comment by sharethewisdom** [comment]
> See #3854.
@davidoskky @qmega 

Sorry to intrude, but the issue here is about synchronized playback of multiple tracks in the same Matroska container in different windows. This could be useful for playback on multiple monitors. Vlc allows for runtime mkv track selection from version 2.0.1 I think.

I'm looking for a solution to playback four different video tracks, four single channel audio tracks and one subtitle track. It's a four-part choral performance: the audio of each voice would sound from speakers positioned underneath their projected heads.
