### ISSUE TITLE
Mac touchbar: Remaning time does not update when playback speed changes

### ISSUE THREAD

**Issue by aplatti** [mpv-player/mpv#7559]
I noticed that when I increase the speed that my video is playing, the time remaning that displays on my Mac's touchbar always shows the original duration.   The scrub bar on the main screen, however, properly updates with the remaining time.

Steps to reproduce:
1. Start video playing from finder
2. Notice time remaning at normal playback speed.
3. Increase playback speed to a faster speed by pressing "]" key
4. *BUG* Notice the time remaining on the Mac Touchbar does not update to the time remaining at the current playback speed.

macOS Catalina 10.15.3
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Fri Jan 31 11:28:05 CET 2020
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.2

<img width="979" alt="IMG_2470_HEIC" src="https://user-images.githubusercontent.com/108964/77603032-3f251500-6ecc-11ea-8714-57749abb0ed9.png">

**Comment by Akemi** [comment]
why did you ignore the issue template? usually i would just close this issue.

the touchbar uses a different property for the remaining time. the one in the OSC is a preprocessed one with padding. i decided to go with my own processing, because the touch bar is a bit limited in size. always padding two zeroes is a waste of space. i don't think this can be easily done.

**Comment by aplatti** [comment]
Thanks, this was the first time I ever filed a bug report on an open source project.  I did not know about the template.  It was fun to write, and I love this product a lot.  :)
