### ISSUE TITLE
Can't see stream information anymore

### ISSUE THREAD

**Issue by eblanca** [mpv-player/mpv#7570]
### Important Information

Provide following Information:
- mpv version
mpv 0.32.0-321-gc8e5a615e9-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Mar 30 20:11:58 CEST 2020

- Linux Distribution and Version
LMDE4 (based on Debian Buster) x86_64

- Source of the mpv binary
Self-built

- If known which version of mpv introduced the problem
Same git master on LMDE3 (based on Debian Stretch) x86_64 doesn't show the problem

- Window Manager and version
cinnamon 4.4.8

- GPU driver and version
vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 2.3.0

- Possible screenshot or video of visual glitches
none

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
During the video reproduction I can't enable the stream detail view using SHIFT+i
OSD works indeed, as I can see duration ('o') and stream list (f9) but nothing using shift+i
Instead, on the command line mpv just prints
"[cplayer] Can't find script 'stats' when handling input."
it can't due to some missing packages, as the build finishes successfully.
Maybe some runtime dependency...?

This happens using "--no-config" as well.

**Comment by CounterPillow** [comment]
Provide a log file.

**Comment by CounterPillow** [comment]
Actually scratch that, instead of waiting for your log file I will take an educated guess and say that you've built without Lua support because you don't have any single one of the following installed: luajit, lua 5.1, lua 5.2.

mpv needs at least one Lua implementation for Lua 5.1 or Lua 5.2 to use the builtin scripts. Whether such a Lua implementation is available is autodetected at build-time, which makes the statement " it can't due to some missing packages, as the build finishes successfully." false as we don't fail when an optional feature is missing.

Feel free to prove me right by posting your log file.

**Comment by eblanca** [comment]
https://0x0.st/iM_7.txt
Didn't know lua dependency could be related to that feature, thanks.

**Comment by CounterPillow** [comment]
Yep, you built without lua.
