### ISSUE TITLE
Youtube progress is ~20% after watching full video

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mpv-player/mpv#7586]
I watched this videos to the end, but red bar is not 100%:
![image](https://user-images.githubusercontent.com/3514015/78460589-b3309b80-76ca-11ea-96ff-9551c0ec9135.png)

- mpv version: 0.32.0
- Linux Distribution and Version: Gentoo current version
- Source of the mpv binary: official Gentoo repository

Log make with `-v -v or --log-file=output.txt`
[output.txt](https://github.com/mpv-player/mpv/files/4432396/output.txt)

**Comment by CounterPillow** [comment]
We're never calling the `https://www.youtube.com/api/stats/watchtime` API endpoint because we do not handle anything regarding YouTube specific stuff at all; we just play back the URLs that youtube-dl gives us.

That API needs all kinds of weird superfluous data for tracking purposes, and I suspect it would also require you to actually somehow handle logging into youtube from within mpv to make these calls associated to the correct account, which is way out of scope for mpv.

**Comment by brian6932** [comment]
Anyone know if some kind of plugin exists for this purpose?
