### ISSUE TITLE
Socat permission denied

### ISSUE THREAD

**Issue by fitipe** [mpv-player/mpv#7591]
Hi there,

I'm launching mpv with `--input-ipc-server=/tmp/mpvsocket`, and it probably creates a socket, because I can get informations from the video with `echo '{ "command": ["get_property", "playback-time"] }' | socat - /tmp/mpvsocket`. 

But when I try to set properties with `echo '{ "command": ["set_property", "speed", "3" ] }' | socat - /tmp/mpvsocket`, it just keeps giving me this error:

_2020/04/07 00:25:24 socat[35964] E connect(5, LEN=16 AF=1 "/tmp/mpvsocket", 16): Permission denied_

I've tried it with `sudo`, ando it gives me the same ...

I know it is probably related to a "read only" spec on the socket file, but I can't figure out how to change it, cause I'm assuming that this socket-file is erased every time mpv is closed.

Could any one help me with that?

Cheers! Stay safe, be at home

**Comment by fitipe** [comment]
I tried it again today, without changing anything, and now I get the same error for both setting and getting properties attempts ... I found the mpvsocket file using terminal, and it looks like I have read and write permissions. 

It was created as a root file, not user file ... would it be the problem?

**Comment by fitipe** [comment]
Solved by adding `sudo` before `socat`, not before `echo` as I was trying.

**Comment by ernstki** [comment]
On a related note, an error message like this

```
2025/03/27 19:12:13 socat[191056] E connect(5, AF=1 "/tmp/mpvsocket", 16): Connection refused
```

probably means that mpv isn't even running, or maybe you ran it with `--idle=once` and then it terminated after the first command you sent it (true story).

In any event, it makes me nervous when the answer is <q>just use `sudo`</q> or <q>just `chmod 777` it</q>. Too bad this was four years ago, because I'd be real curious what the POSIX permission bits and the ACLs looked like on that file, and what mount options were used for `/tmp`, because a file _you created and own_ shouldn't require `sudo` to write to, socket or no.
