### ISSUE TITLE
Color clipping in high brightness content with HDR output

### ISSUE THREAD

**Issue by quietvoid** [mpv-player/mpv#7607]
### Important Information

- mpv version: mpv-x86_64-20200405-git-c5f8ec7 (shinchiro)
- Windows Version: Windows 10 Pro, 1909, 18363.752

### Reproduction steps

First, the output display needs to support HDR.
Windows HDR is not enabled, mpv triggers HDR when set into fullscreen.
Config:
> target-peak=700
> d3d11-output-csp=pq

If it's of any use, removing `target-peak=700` still exhibits the same issue but it's not clipping as much.

### Expected behavior

The orange color on the mountain's peak should be desaturated to show the details.

### Actual behavior

The orange color looks like it's clipping and looks "flat" instead of showing the actual details in the video stream.
There is also haloing around the mountain.
Not pretty but this is a close up on my TV, an LG OLED C8. https://imgbox.com/MJt0r7tQ

### Log file

https://0x0.st/iSGO.txt

### Sample files

https://0x0.st/iSGe.mkv

**Comment by jeeb** [comment]
What about when you have no tone mapping added? In other words, just the CSP set.

**Comment by quietvoid** [comment]
> 
> 
> What about when you have no tone mapping added? In other words, just the CSP set.

I have just edited this in: 

> If it's of any use, removing target-peak=700 still exhibits the same issue but it's not clipping as much.
It still looks "bad" compared to the tonemapped SDR image.

**Comment by jeeb** [comment]
OK. Looking at your logs apparently your DISPLAY1 is 8bit and configured for SDR:
```
[   0.104][v][vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 3840x2160 @ 8 bits, colorspace: RGB_FULL_G22_NONE_P709 (0)
[   0.104][v][vo/gpu/d3d11] Selected swapchain format R8G8B8A8_UNORM (28), attempting to utilize it.
[   0.105][v][vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G2084_NONE_P2020 (12), attempting to utilize it.
[   0.105][v][vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G2084_NONE_P2020 (12): normal: yes, overlay: no
[   0.105][v][vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G2084_NONE_P2020 (12)!
```
This leads to:
1. swap chain configured for 8bit RGB output
2. You force colorspace to PQ, so that will be PQ

I guess you are dragging the window across to your secondary, HDR screen? Can you post how [this screen](https://kuroko.fushizen.eu/screenshots/mpv/lol_windows_hdr_24hz.png) looks for you?

If your HDR screen is still configured as SDR, then that would explain the blow-out as that would be Windows's own attempt at tone mapping.

What one gets with most HDR screens by default if there's an RGB connection, is
```
--d3d11-output-format=rgb10_a2
--d3d11-output-csp=pq
```

While developing on nvidia, there was also a 16bit floating point format (`d3d11-output-format=rgba16f`) available, but whether that worked or not was *very* irregular. Also I had no data on how things worked overall. Thus it is not utilized automagically in the code. That said, for *some* reason setting that improved things for someone in #7600 , so that is also something that could be attempted.

**Comment by haasn** [comment]
Seems like the issue here is that the peak detection is not picking up the increasing scene brightness aggressively enough.

If this theory is correct, then `--hdr-compute-peak=no` should eliminate the clipping artefacts. That being said, there are other options we can tune to try fixing this. Stuff you can try includes:

- `--hdr-peak-decay-rate=10`
- `--hdr-scene-threshold-low=3`
- `--hdr-scene-threshold-high=7`

and various combinations of these options (or other values).

**Comment by haasn** [comment]
We may need to allow the peak to change more aggressively than the scene average, i.e. use different smoothing coefficients for both. We might also want to try tuning the function a different way (piece-wise instead of linearly). Gives me a couple of improvement ideas, I'll have to see about trying them out.

**Comment by haasn** [comment]
Oh, we could also add a sort of constant "safety margin" on the peak to avoid clipping due to slight overshoot.

**Comment by quietvoid** [comment]
While the display is configured to 8 bit RGB Full, enabling Windows HDR and setting it to 10 bit RGB does not change the outcome, regarding the colors.
The luminance mapping is perfectly fine, it is not blown out in full screen.

The only thing being clipped is the orange color on the peaks.
Using `hdr-compute-peak=no` does improve the details underneath, however it still seems as if the colors are not desaturated enough.

Just for the sake of comparison, this is how it looks against madVR:
![mpv-madvr](https://user-images.githubusercontent.com/39477805/79056713-1e2c2600-7c27-11ea-91ef-9a1fd589db9c.jpg)

I will try the other suggested settings next.

**Comment by haasn** [comment]
To get more aggressing desaturation you can try `--tone-mapping-desaturate=1` and maybe even `--tone-mapping-desaturate-exponent=0`. But I'm not quite sure what logic madVR uses to decide to generate those "super-highlights". It's possible they use some local highlight detection algorithm. I haven't really looked into it.

**Comment by quietvoid** [comment]
I pretty much have to use both options for it to not look oversaturated.
It would be a good compromise to use these if they don't affect regular brightness titles (1000-4000 nits) too much.
Either way, this type of content is pretty extreme and not common at all.

**Comment by haasn** [comment]
Yeah it's unfortunately a bit of a pathological case for our algorithm, which really hates fast "fade in"s like this.

**Comment by quietvoid** [comment]
I guess this issue can be closed then. It's unfortunate that `hdr-compute-peak=yes` causes this, because being dynamic should technically help resolve highlight details.

For future reference, this is the config I would use for HDR output on a 700 nits display:
> target-peak=700
d3d11-output-csp=pq
d3d11-output-format=rgb10_a2
hdr-compute-peak=no
tone-mapping-desaturate=1.5
tone-mapping-desaturate-exponent=0
