### ISSUE TITLE
Base the hash for watch later on file, not filename.

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#7613]
### Expected behavior of the wanted feature
When set, the hash in watch later would be based on the file itself (using md5sum or something similar) and not the filename. So when the file gets moved or renamed, the saved progress would not get lost.

`--ignore-path-in-watch-later-config` already partially does that, but only for moving the file not renaming it. Thanks for keeping that feature though, it has its users: https://github.com/mpv-player/mpv/issues/3138 and https://github.com/mpv-player/mpv/issues/1281
Though I think this option might remove the need for `--ignore-path-in-watch-later-config`.

Not sure if this would break streams but for files stored locally, it would be quite useful to me.

**Comment by wm4** [comment]
Tons of reasons against this.

**Comment by v-fox** [comment]
@Akemi Any chance of reopening this? This is what smplayer does with mpv backend. I doubt that it goes through whole file for hash, probably just container metadata.

**Comment by Akemi** [comment]
i don't think this feature is feasible. calculating the hash of a whole file might take minutes, also this will surely break for files that data is appended/added to like streams.

if you want the watch later behaviour changed based on different criteria it's best to open a new feature request.

**Comment by v-fox** [comment]
>  don't think this feature is feasible. calculating the hash of a whole file might take minutes, also this will surely break for files that data is appended/added to like streams.
> 
> if you want the watch later behaviour changed based on different criteria it's best to open a new feature request.

Of course, no one would want to read the whole file, I'm sure original poster meant that file's unique characteristics should be used, not literally every bit. Smplayer does that somehow almost instantaneously on files of any size (tested mkv's >20GB). I want what OP wanted: not to use names that are volatile.

Although, looking at its code, it seems that it's sillier than I though and it hashes the names: https://app.assembla.com/spaces/smplayer/subversion/source/HEAD/smplayer/trunk/src/filesettingshash.cpp

What about something like that ?
* Select the list of common entries of metadata from what's embedded in the container or always queried by player at opening.
  * All of that data should be static. Such as encoding parameters of default video and audio tracks and their exact duration. For video-files all internal metadata info-tags may be used because they're rarely changed but that's no good for audio-only.
  * Probably, only long audio files should be remembered, like >10 minutes by default.
  * For streams that is questionable due to constant changes but is it even practical to ?
* Shrink the list to use only most diverse entries and hash them.
  * But changes to that list or representation of any of its entries would change format and invalidate all older hashes. That should be permissible to avoid further complications.
