### ISSUE TITLE
gpu-api=vulkan results in a "VK_ERROR_EXTENSION_NOT_PRESENT" error

### ISSUE THREAD

**Issue by Unser395** [mpv-player/mpv#7626]
### Important Information

Provide following Information:
- mpv version = 0.32
- Linux Distribution and Version = Manjaro
- Source of the mpv binary = Manjaro repository
- If known which version of mpv introduced the problem = no
- Window Manager and version = i3
- GPU driver and version = nvidia 2080 rtx with 440.82 driver

### Reproduction steps

Add gpu-api=vulkan to mpv.conf.

### Expected behavior

Able to use gpu-api=vulkan.

### Actual behavior
Here's the relevant error message in the console : 
`[vo/gpu/vulkan/libplacebo] Failed creating instance: VK_ERROR_EXTENSION_NOT_PRESENT
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan instance`

libplacebo is installed on my computer. What can I do ? Thanks.

### Log file
https://0x0.st/iQEQ.txt

**Comment by sfan5** [comment]
This error happens during probing of the `waylandvk` context, mpv falls back to `x11vk` and Vulkan rendering will still work (also visible in your log file).

**Comment by Unser395** [comment]
> This error happens during probing of the `waylandvk` context, mpv falls back to `x11vk` and Vulkan rendering will still work (also visible in your log file).

Ok, so gpu.api=vulkan is working as it should ? No need to do anything ? Sorry for the dumb question by the way, I'm a total noob.
Thank you very much for your help.

**Comment by haasn** [comment]
In some sense this is a consequence of mpv being compiled with wayland support but your graphics drivers being compiled without wayland support. I would honestly consider this a packaging bug.

I was considering whether or not to suppress this message (or degrade it to a warning or something) but it's not actually as common as it would seem, since on systems where wayland support is universally available, this error does not get triggered.

Anyway, a better solution might be to test for wayland initialization *before* testing for vulkan support.

**Comment by haasn** [comment]
Anyway I've decided to just suppress the errors for now as the least annoying compromise. YMMV
