### ISSUE TITLE
how to change tempo and not change playback speed

### ISSUE THREAD

**Issue by asnahu** [mpv-player/mpv#7642]
my video source has been slow down for slow motion, now i need restore tempo :

```
mpv \
--af-rubberband=pitch-scale=2.4 \
--speed=1 \
$file
```
or

```
mpv \
--af-scaletempo=tempo=2.4:speed=pitch \
--speed \
$file
```

 how to get wanted result?

**Comment by kevmitch** [comment]
You haven't fully specified your situation. What happened to the audio when the video was originally slowed down?

If it was also slowed down with no pitch correction so that the audio is now low pitch, restore both audio and video with

    --speed=2.4 --audio-pitch-correction=no

If the slowing down also included audio pitch correction so the audio is at the right pitch despite being slower, you'll want to undo the pitch correction, but keep in mind this will probably sound horrible due to converting back and forth. This is mpv's default mode of speed change so just specify the speed you want

    --speed=2.4 

If you think the rubberband filter does a better job

    --speed=2.4 --af=rubberband





It sounds like you're looking for the first example in the [manual](https://mpv.io/manual/master/#audio-filters-scaletempo)

**Comment by asnahu** [comment]
I think its the first situation: audio is in low pitch and no pitch correction.

I need keep video playback (which is slowed down ) and restore audio original pitch.
