### ISSUE TITLE
OSC has issue with double click on wayland

### ISSUE THREAD

**Issue by shabahengam** [mpv-player/mpv#7651]
if I pause a file with double click and trigger OSC,then OSC will shows up everytime mouse move into the window even if its deadzone.

### Important Information

Provide following Information:
- mpv version: ``git-master 055a490``
- Linux Distribution and Version: ``voidlinux, kernel 5.4.33``
- Source of the mpv binary: ``compiled from git-master``
- Window Manager and version: ``sway 1.4, wayland 1.18, wlroots 0.10.1``
- GPU: ``Intel``
- Driver in use: ``i915``

### Reproduction steps
put this in your input.conf
``MOUSE_BTN0_DBL cycle pause``
and put this in your sway config file
``for_window [app_id="mpv"] floating enable``
**Note:** I cant reproduce the issue in tiling mode.mpv should be a floating window.
pause the file with double click and trigger OSC.now OSC will shows up everytime you move the mouse into the window even if its deadzone.
### Expected behavior
Dont trigger OSC if mouse is in deadzone.
### Actual behavior
OSC shows up everytime mouse move into the window even if its deadzone.
### Log file
[log.txt](https://github.com/mpv-player/mpv/files/4512401/log.txt)

**Comment by wm4** [comment]
CC @Dudemanguy (maybe, and if it's really a wayland issue)

**Comment by Dudemanguy** [comment]
I don't think(?) I can reproduce this (also sway). I don't really know how the deadzone is supposed to work though. To me, the mouse cursor/osc appearing seems the same paused and unpaused in a floating window. I'm not sure what I'm supposed to see or not see.

**Comment by shabahengam** [comment]
after pause and triggering OSC move the cursor out of the window and then put the cursor on top of the window(enter to window from top) now if OSC appeared this means you reproduced the issue because default [deadzone](https://mpv.io/manual/master/#on-screen-controller-deadzonesize) value is 0.5 and in this situation OSC should not show up.(sorry for my english)

**Comment by Dudemanguy** [comment]
Oh okay, I understand the problem now. I can see it on sway and weston.

It not happening in titled mode is probably some lucky trick due to the window technically being considered maximized in xdg-shell.

**Comment by Dudemanguy** [comment]
This actually has nothing to do with double click (or pausing). You can reproduce the same thing with a single left click. Basically what happens is that `xdg_toplevel_move` gets executed (even if you don't move the window) which somehow magically messes up mpv's deadzone (???). In the event that you do a resize instead of a move with left click (if the windowcontrols are active), the same bug still occurs.

**Comment by mc4man** [comment]
See same here though taken with grain of salt as using crappy gnome wayland.
Anyway it only occurs with the windowcontrols enabled, if disabled in script-opts then never happens.

Also can't see then why anyone using windowcontrols & default deadzone of 0.5 would notice this anyway as it, (osc & windowcontrols deadzone)  works top down & bottom up so there is no area where the cursor won't expose osc & controls.
Obvious with more reasonable deadzone of 0.85

**Comment by Dudemanguy** [comment]
This is a pretty subtle bug that probably always existed (or at least existed for as long as the `window_move` function existed). I'm glad someone noticed it because this is exactly the kind of thing I would never catch myself.

Anyways, I figured out a dumb fix that seems reasonable/harmless enough so I'll push it in a bit.

**Comment by shabahengam** [comment]
confirm the issue fixed.thank you so much.
