### ISSUE TITLE
Changing Audio Pitch to 432hz

### ISSUE THREAD

**Issue by mysteryx93** [mpv-player/mpv#7673]
Is there any way to change audio pitch from 440hz to 432hz in realtime with MPV?

One method I'm currently using is loading an Avisynth script file that changes the audio pitch, but this has several drawbacks.

Any way to do it directly with MPV, even if it requires programming?

**Comment by paulguy** [comment]
```
[detune]
audio-pitch-correction=no
speed=0.98
```
as a simple solution in your mpv config, and setting it with `--profile=detune`?

**Comment by CounterPillow** [comment]
`scaletempo=speed=pitch:scale=0.9818181818181818` should work. See the manual on the scaletempo filter for more details.

**Comment by CounterPillow** [comment]
nevermind, this doesn't seem to work quite as intended, since it still changes the tempo despite speed for the scaletempo being set to pitch.

Anyway, if scaletempo doesn't want to work, you can use the [rubberband audio filter](https://ffmpeg.org/ffmpeg-filters.html#rubberband) as long as the ffmpeg your mpv is built against is compiled with librubberband support. I'm sure there's also a different ffmpeg-internal audio filter somewhere which can do pitch shift on that page.

**Comment by mysteryx93** [comment]
paulguy, changing the speed has the draback of... well... changing the speed. Not ideal.

CounterPillow, are you saying it would be possible but only by custom-compiling MPV?

Rubberband and SoundTouch seem to be 2 main processing algorithms out there; but SoundTouch isn't integrated into FFmpeg.

I believe I made some tests with Rubberband in the past to see whether it would increase quality, and it caused audio distortion in some cases. SoundTouch seems to be the algorithm used in Avisynth that I was using.

So the 3 options right now are:
1. Simply change tempo in MPV config
2. Load an Avisynth script using SoundTouch
3. Custom-compile MPV with Rubberband support

Correct? Not that it's helping much right now... there's got to be a better way?

**Comment by wm4** [comment]
4. patch to mpv

**Comment by CounterPillow** [comment]
scaletempo's pitch-only adjustment seems broken right now so that's a good place to start with a patch.

**Comment by mysteryx93** [comment]
Other solutions:
- Loading a 2nd audio file for an Avisynth or Vapoursynth script (VapourSynth will soon have audio support). Hoping MPV will keep both the video and audio in sync.
- Loading a custom audio filter? How can I add audio filters, if possible?

**Comment by wm4** [comment]
You could use the ffmpeg scaletempo filter. I don't know what's the problem with mpv's scaletempo (maybe it's the weird way it manages playback speed), but I haven't tried.

**Comment by mysteryx93** [comment]
Looking at the documentation, audio pitch is supposed to be well-supported by internal filters, both scaletempo and rubberband.

And this works perfect!

    --af=rubberband=pitch-scale=0.981818181818181

Nothing else to do.

**Comment by clort81** [comment]
> The rubberband filter works great. I’m interested in increase/decrease semitones: multiplying by 0.9438743126816935 decreases one semitone and by 1.059463094352953 increases a semitone. A semitone is increased with the command `mpv --af=rubberband=pitch-scale=1.059463094352953 /path/to/file` What I’m trying to do is to create two key combinations (in input.conf) to increase and decrease semitones. But after reading the manual and trying multiple syntax like this, in input.conf, I had no success…
> 
> ```
>     Ctrl+k multiply rubberband multiply-pitch 0.9438743126816935
>     Ctrl+j multiply rubberband multiply-pitch 1.059463094352953
> ```
> 
> Any idea on how to put this to input.conf

Look in to mpv scripts to store a dynamic variable for $current_pitch, then bind keys to functions to multiply/divide as needed.

**Comment by nazarux** [comment]
> 
> Look in to mpv scripts to store a dynamic variable for $current_pitch, then bind keys to functions to multiply/divide as needed.


My current input.conf file:


```
# ALT+t -> toggle rubberband pitch changer ON/OFF (af=@rb:!rubberband    # written to mpv.conf file)
ALT+t af toggle @rb

# ALT+4 -> DOWN one semiton
ALT+4 af-command rb multiply-pitch 0.9438743126816935

# ALT+5 -> Reset set-pitch 1.0
ALT+5 af-command rb set-pitch 1.0

# ALT+6 -> UP one semiton
ALT+6 af-command rb multiply-pitch 1.059463094352953



# Increase subtitle font size:
Ctrl+k add sub-scale +0.1

# Decrease subtitle font size:
Ctrl+j add sub-scale -0.1

# Cycle Video Rotate to 90º, 180º, 270º, NONE:
Ctrl+r cycle_values video-rotate 90 180 270 0
```

**Comment by clort81** [comment]
This point should have been made far up in the thread. 

For PCM audio, changing pitch without changing tempo  **### _will always introduce significant audio distortion_**.  You can do it *without* distortion only for spectral formats like mp3, opus, but that requires hooking into the decoder itself, which those libraries don't support (or do they?)

The tradeoff we face when shifting frequency is:
* correct signal vs
* correct tempo

For my personal music listening a 1.8% change in tempo is usually negligible 

in my input.conf
```
p set audio-pitch-correction no; set speed 0.981818181818
P set audio-pitch-correction no; set speed 1.0

```

Since our lossy-compression formats like mp3,opus,m4a,ogg etc all transform the original signal from the time domain (PCM) to frequency domain, those decoders theoretically *could* stretch tempo without introducing _any_ distortion. 

Leveraging this fact is something that just hasn't been gotten-around-to yet, to my knowledge, in _any_ player or pitch-shift plugin -- they all (incl rubberband etc) operate on a PCM input waveform, using really gross hacks to overlay windowed segments shifted in time - ruining transients etc.  Try listening to a hi-hat strike with 50% time-streched pitch shifting sometime to hear the overlaps.

It's a very suboptimal situation.

**Comment by mysteryx93** [comment]
Doing it at the decoder level? That's an "interesting" idea; but then would need a custom decoder implementation for every data format?

**Comment by clort81** [comment]
> Doing it at the decoder level? That's an "interesting" idea; but then would need a custom decoder implementation for every data format?

Yes. Arguably this is an obvious feature that should have been implemented in decoders from the start in order to achieve arbitrary time scaling with no signal degradation.

There's no technical objection. Nobody thought of it and now people just assume it's impossible or "interesting".

EDIT: Ask your LLM:

`
Audio digital signal processing revelation:  Perceptual audio encoders like mp3, ogg, m4a transpose a pcm volume signal into frequency domain, for later masking and efficient compression.
Since the audio data is stored in frequency domain, a playback-decoder could stretch or compress the time component to achieve 'audio stretching' without the distortion induced by stretchers based on PCM domain.
Describe the algorithm of a frequency based audio format, the FFT, and how a decoder can be trivially modified to change the playback tempo without affecting pitch or introducing any harmonic distortion. Do not confuse this proposal with existing time-stretching algorithms that operate on PCM signals by merging overlapping segments.
`
