### ISSUE TITLE
Play two audio streams on two different outputs

### ISSUE THREAD

**Issue by mhe2405** [mpv-player/mpv#7684]
Hi,

Is it possible to play two audio streams from a video file simultaneusly on two different outputs? 

I want to play a movie audio in german language on the hdmi port and the english audio on the headphones.

**Comment by wm4** [comment]
That's currently not possible. Outputs are limited to 1. You might be able to "fake" it with syncplay, or (with low probability of success) construct a filter with --lavfi-complex, that diverts some audio to an libavdevice output.

Maybe one day, but not any time soon.

**Comment by wm4** [comment]
Another complicated and not very robust idea: use --lavfi-complex to join two audio streams (each stream into its own set of channels), then use --ao=jack, and reroute the individual channels to different outputs.

**Comment by mhe2405** [comment]
@wm4, Thank you for the fast answer

What could the solution with --lavi-complex look like?

**Comment by wm4** [comment]
From what I can see, libavfilter has no libavdevice sinks (only sources), so that idea is dead. That leaves the jackaudio idea, which should be possible, but is pretty involved.

Probably better if you just try syncplay, or wait until mpv can do multiple outputs (shouldn't take more than a few years at normal dev speed).

**Comment by bitingsock** [comment]
I just made this simplistic solution. If you're not on Windows you might have to format it a bit.
[audio-dupe](https://gist.github.com/bitingsock/5e9714efff963c9689b0671d68f195ad)
