### ISSUE TITLE
Request to make mpv accept dirs as well with --merge-files

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#7715]
Currently it accepts only files, and when trying to start a dir with
`mpv --merge-files "/mnt/abooks/Der Herr/"*`
it says :
> EDL: source file '/mnt/abooks/Der Herr/01' has unknown duration.

**Comment by wm4** [comment]
Hm, I think this is WONTFIX. This is technically messy, because when the EDL is built, we don't know yet whether your directory is a directory or a file. When it comes to the point where the file is actually opened, it's too late to insert it properly in the EDL timeline. We _could_ still do it, but I think the effort and resulting mess outweighs the gain, especially because there are simple workarounds which don't require such a feature.

You need to pass all files manually. You could do with find or advanced shell globbing. Pretty simple to work around.
