### ISSUE TITLE
failed to recognize file format

### ISSUE THREAD

**Issue by flatusv** [mpv-player/mpv#7732]
when i play my youtube playlist with mpv, after some time i get the error "failed to recognize file format". I dont know what i did wrong, here is how i use it "mpv 'https://www.youtube.com/playlist?list=PLN_adWB2_ZF4fTElMzEhpGzl5KEsSNeZu' --no-vid --shuffle --no-resume-playback"

**Comment by CounterPillow** [comment]
Your issue has been closed because you have ignored the issue template. Issue templates will appear when you open a new issue, and choose which category of issue you want to report. Currently, a GitHub bug prevents this choice from appearing if you're not logged in at the time you click on the new issue button, so if you never saw any template, that may be why.

Our closing of this issue does not mean that the problem you are experiencing is not real or that we somehow are being rude to you, it's simply a matter of issue triage to separate those we can do something about (ones that fill out the issue template) from those that waste everyone's time by not providing us with the information we explicitly and very clearly ask for (yours).

Following our established processes helps you get your issue resolved quicker, and helps us in identifying the issue. If you are unwilling to follow this simple process we are unwilling to have you on our issue tracker.

**Comment by mc4man** [comment]
Update your youtube-dl to latest version..
