### ISSUE TITLE
HDR10 wrong colours to SDR monitor, 8K videos unplayables, and other

### ISSUE THREAD

**Issue by chrnodroid** [mpv-player/mpv#7742]
- mpv v0.31 Portable
- Windows 10 Pro 1909
- Hardware: Intel i5-9400F, Nvidia GTX 1060 6GB, 16GB DDR4-3000
- Source of the mpv binary: https://www.videohelp.com/download/mpv-0.31.0-x86_64.7z
- Screenshot of the problem:

![Annotazione 2020-05-20 095249](https://user-images.githubusercontent.com/62098617/82420738-6dfcd900-9a80-11ea-879c-2ea9165be129.png)

- Config file
The problem happens also with no config file. 
[mpv.conf.txt](https://github.com/mpv-player/mpv/files/4655441/mpv.conf.txt)

- Log file
[log.txt](https://github.com/mpv-player/mpv/files/4655470/log.txt)

- Source of the video: https://www.demolandia.net/downloads.html?id=887452455

I also noticed that the colours in general in mpv are darkers than other video players also with SDR videos. It's almost imperceptible, you have to compare them to notice them. 
I have exacly this issue: https://github.com/mpv-player/mpv/issues/4248

I have also another big issue, mpv cannot play 8K videos in VP9 format, they have several slow down, umplayables just like a potato PC. This not happens with others video players.
- Video sample: https://www.youtube.com/watch?v=1La4QzGeaaQ

**Comment by haasn** [comment]
`--tone-mapping-desaturate=1 --tone-mapping-desaturate-exponent=0` should make the red tint go away, at the cost of distorting colors of more sanely mastered clips.

**Comment by haasn** [comment]
> I have also another big issue, mpv cannot play 8K videos in VP9 format, they have several slow down, umplayables just like a potato PC. This not happens with others video players.

My dowsing rod says 'hwdec'.

**Comment by chrnodroid** [comment]
> `--tone-mapping-desaturate=1 --tone-mapping-desaturate-exponent=0` should make the red tint go away, at the cost of distorting colors of more sanely mastered clips.

This has solved the problem, but I immediately noticed the distorting white colours on the same video.

> My dowsing rod says 'hwdec'.

I've tried also, 'cuda', 'cuda-copy', 'nvdec-copy', 'dxva2-copy',  and nothing.  Every hwdec setting or api setting are just the same on 8K VP9 videos.
Also, cuda simply don't work with VP9 in general.

**Comment by jeeb** [comment]
For the record, 8K rendering through shaders is slow. Even with hwdec.

I have not done proper analysis on where exactly it's slow, but frankly I am not surprised. If you pass your playback straight onto some hardware video output thing (like `vo=vaapi` on Linux), it should work better. That is most likely what players which work with this stuff are doing.

The issue with doing that is that you lose all of the processing that mpv handles.

**Comment by aufkrawall** [comment]
Afair nvdec/cuda aren't zero-copy with vulkan, unlike with opengl. I suppose it should work in dumb-mode also with `vo=gpu` and opengl.

**Comment by jeeb** [comment]
For windows and the defaults (`d3d11` rendering) the fastest hwdec is `d3d11va` (non-copy) and it's nice because it works across vendors.

Performance wise with the 8K60 non-HDR BT.2020 sample I have neither rendering API is fast enough, so this is just where shader based rendering atm is going to hurt. Not that someone can't profile it, but that requires effort.

**Comment by aufkrawall** [comment]
I can play the 8k 60fps VP9 SDR video fluidly on Windows with D3D11VA and bicubic scaling on a GTX 1070, while OGL NVDEC is too slow.

**Comment by chrnodroid** [comment]
Whit these settings 8K 60FPS HDR videos works a little better than before but still unwatchable.
`gpu-api=vulkan
vulkan-async-transfer=yes
vulkan-async-compute=yes
vo=gpu
hwdec=d3d11va`

I triead with gpu-api `d3d11` and `opengl` but they are too cpu/gpu intensive, vulkan is so far better overall.

**Comment by WizRay** [comment]
@chrnodroid, I dont think hwdec=d3dd11va works with vulkan

**Comment by KloudKoder** [comment]
This may be a separate bug, but I'm seeing wrong colors in HDR10 under Ubuntu. I took several videos with several different codecs just for the sake of comparison. The HDR10 is consistently too dim. I tried "--tone-mapping-desaturate=1 --tone-mapping-desaturate-exponent=0" but it made no difference.

Just out of curiosity, I uploaded the videos to YouTube. Sure enough, the HDR10 was still very messed up, but this time it was way too _bright_.

Sounds like someone is trying to convert pixel values to intensity values and screwing up royally. I wonder if this comes down to the pervasive problem of incorrect sRGB component math. (Pixel values _do not_ correspond linearly or even exponentially to intensity values.) Of course, this may not _literally_ have to do with the sRGB nonlinear mapping, but perhaps HDR10 uses some other equally moronic mapping of pixel values to intensity. I'm driven toward this hypothesis because it's clear that both MPV and YouTube are messed up, but in opposite directions.

Rounding error or quantization artifacts (due to a lack of dithering) could be a secondary factor, although in theory "high dynamic range" suggests that one shouldn't need dithering because it's superfluous and would only create noise. I'm just saying: it looks like the whole frame is getting chromatically squashed up or down depending on the player.

I'm running all this with Intel 620 video. There is no external GPU available. The videos were shot on a recent Samsung phone.

**Comment by amariami** [comment]
> 
> 
> I'm running all this with Intel 620 video. There is no external GPU available. The videos were shot on a recent Samsung phone.


`### Use this if you want to display HDR content on an SDR screen or dislike the “effect” of HDR.`
`##--vf=format=fmt=help`
`##--vf=format:colormatrix=auto:convert=yes`
`##--vf=format=420p:colormatrix=bt.709:colorlevels=limited:primaries=709:light=709-1886:convert=yes`
`--vf=format=colormatrix=bt.709:colorlevels=limited:primaries=bt.709:light=709-1886`
###https://mpv.io/manual/master/#video-filters-format

`--video-output-levels=limited`
`###auto [automatic selection (equals to full range) (default)]`
`###limited limited range [(16-235 per component), TV and studio levels]`
`###full [full range (0-255 per component), PC levels]`

`--tone-mapping=mobius             #<bt.2390|clip|mobius or reinhard|gamma|linear|hable>`
`--tone-mapping-param=0.3`
`--tone-mapping-max-boost=1.0`
`##--tone-mapping-desaturate=0.75`
`##--tone-mapping-desaturate-exponent=1.5`
`##--gamut-warning`
`--gamut-clipping`
`##--icc-profile-auto`
`##--use-embedded-icc-profile`
`##--icc-contrast=200`
###https://mpv.io/manual/master/#options-tone-mapping

`##--target-trc=pq or srgb or bt.1886
`--target-trc=srgb`
`#<auto(default)|bt.1886|srgb|linear|gamma1.8|gamma2.0|gamma2.2|gamma2.4|gamma2.6|gamma2.8|prophoto|pq|hlg|v-log|s-log1|s-log2>`
###https://mpv.io/manual/master/#options-target-trc

`--target-prim=auto`
`###<auto(default)`
`###bt.470m`
`###bt.601-525[ITU-R BT.601 (525-line SD systems, eg. NTSC), SMPTE 170M/240M]`
`###bt.601-625[ITU-R BT.601 (625-line SD systems, eg. PAL/SECAM), ITU-R BT.470 B/G]`
`###bt.709[ITU-R BT.709 (HD), IEC 61966-2-4 (sRGB), SMPTE RP177 Annex B]`
`###bt.2020[ITU-R BT.2020 (UHD)]`
`###apple[Apple RGB]`
`###adobe[Adobe RGB(1998)]`
`###prophoto[ProPhoto RGB (ROMM)]`
`###cie1931[CIE 1931 RGB (not to be confused with CIE XYZ)]`
`###dci-p3[DCI-P3 (Digital Cinema Colorspace), SMPTE RP431-2]`
`###v-gamut[Panasonic V-Gamut (VARICAM) primaries]`
`###s-gamut[Sony S-Gamut (S-Log) primaries]>`
###https://mpv.io/manual/master/#options-target-prim

**Comment by KloudKoder** [comment]
@amariami Impressive recommendations, but shouldn't this be dumbed down to a mix of automated smarts and maybe a user button that says "HDR doesn't work on my monitor so please make it look like it does"?
