### ISSUE TITLE
Create a semi-transparent MPV child window in X11

### ISSUE THREAD

**Issue by egormalyutin** [mpv-player/mpv#7753]
I doubt it's really right place to ask questions like this. If so, please sorry.

I have this code in C:
```c
#include <X11/X.h>
#include <X11/Xlib.h>
#include <mpv/client.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Handle MPV errors
void checkMPV(int status) {
  if (status < 0) {
    printf("MPV error: %s\n", mpv_error_string(status));
    exit(1);
  }
}

int main(void) {
  Display *display = XOpenDisplay(NULL);
  if (display == NULL) {
    fprintf(stderr, "Cannot open display\n");
    exit(1);
  }

  // Create X11 window
  int screen = DefaultScreen(display);
  Window window = XCreateSimpleWindow(
      display, RootWindow(display, screen), 10, 10, 100, 100, 1,
      BlackPixel(display, screen), WhitePixel(display, screen));
  XSelectInput(display, window, ExposureMask);
  XMapWindow(display, window);

  // Create MPV context
  mpv_handle *ctx = mpv_create();
  if (!ctx) {
    printf("failed to create context\n");
    return 1;
  }

  // bind MPV to master window
  char wid[64];
  sprintf(wid, "0x%lx", window);
  checkMPV(mpv_set_option_string(ctx, "wid", wid));

  // configure MPV
  checkMPV(mpv_set_option_string(ctx, "keepaspect", "no"));
  checkMPV(mpv_set_option_string(ctx, "x11-bypass-compositor", "no"));
  checkMPV(mpv_set_option_string(ctx, "gapless-audio", "yes"));
  checkMPV(mpv_set_option_string(ctx, "aid", "no"));
  checkMPV(mpv_set_option_string(ctx, "vo", "xv"));
  checkMPV(mpv_set_option_string(ctx, "hwdec", "auto"));
  checkMPV(mpv_set_option_string(ctx, "input-default-bindings", "no"));
  checkMPV(mpv_set_option_string(ctx, "input-vo-keyboard", "no"));

  int flag = 0;
  checkMPV(mpv_set_option(ctx, "osc", MPV_FORMAT_FLAG, &flag));

  // Initialize MPV
  checkMPV(mpv_initialize(ctx));

  // Play video
  const char *cmd[] = {"loadfile", "video.mp4", NULL};
  checkMPV(mpv_command(ctx, cmd));

  // Draw rectangle in loop
  XEvent event;
  while (1) {
    XNextEvent(display, &event);
    XClearWindow(display, window);
    XFillRectangle(display, window, DefaultGC(display, screen), 10, 10, 300,
                   300);
  }

  // Cleanup
  mpv_terminate_destroy(ctx);
  XCloseDisplay(display);
  return 0;
}
```

It's just slightly modified [simple](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/simple/simple.c) example, which attaches MPV window to X11 window. It looks like this (just a video frame):

![now](https://user-images.githubusercontent.com/11716104/82726078-90525900-9d03-11ea-9984-fef4f5ac298a.png)

The question is, can I make MPV window semi-transparent (for example, by 70%), so rectangle drawed by ` XFillRectangle(display, window, DefaultGC(display, screen), 10, 10, 300, 300);` will be kinda visible? It would look like this:

![frame](https://user-images.githubusercontent.com/11716104/82726137-f343f000-9d03-11ea-92f5-8f2a13b16e36.png)

Is it possible without using things like opengl?

**Comment by wm4** [comment]
Probably not. Alpha was never part of X11. I don't think non-toplevel windows with alpha are possible on X11. Top-level windows with alpha are a hack that relies on compositors using it. mpv actually can create top-level windows with alpha on X11, but I guess it's currently broken due to the mess in EGL (I could look for the bug report).

If you want overlays, either use the mpv bitmap overlay API, or the render API. Also see: https://github.com/mpv-player/mpv-examples/tree/master/libmpv#methods-of-embedding-the-video-window

Unless you're using the bitmap overlay API, you basically need to do it yourself. This easiest way is using OpenGL. Another way would be full software rendering (although mpv currently has no API to return raw frames efficiently - but it's not going to be efficient anyway).

**Comment by egormalyutin** [comment]
Thanks!
