### ISSUE TITLE
[Question] How to use MPV for video wallpapers on macOS?

### ISSUE THREAD

**Issue by sheharyarn** [mpv-player/mpv#7790]
It seems pretty simple to do on Linux using [`xwinwrap`](https://github.com/Aaahh/xwinwrap) or something else like `bspc` to use mpv as a wallpaper. Unfortunately, they're not available on macOS.

VLC can also run in behind all system elements to [achieve the same effect](https://www.youtube.com/watch?v=q1gjphKdIVQ). I'm wondering if I can replicate the same with mpv.

Here's what I've come up with so far:

```shell
mpv \
  --wid=0 \
  --loop \
  --really-quiet \
  --fullscreen \
  --no-native-fs \
  --no-audio \
  --no-osc \
  --no-osd-bar \
  --no-config \
  --no-input-cursor \
  --no-input-default-bindings \
  --cursor-autohide=no \
  --speed=1 \
  --zoom=0.15 \     # to "fill" the screen, is there another option to do this automatically?
  my-video-wallpaper.mkv
```

But this isn't perfect because of a couple of reasons:
  - Hides Menubar and Dock
  - Is on top of desktop icons, not behind them
  - Grabs focus (should run in the background and not accept any input)

Any ideas? Is this even possible?

**Comment by Akemi** [comment]
currently it's not possible completely.

i implemented the desktop level (behind everything) for another issue here, but the person wasn't interested anymore so i never merged it. https://github.com/Akemi/mpv/commit/cb1fb23e8e573878850e09f5aad2afea4c3b4471

no focus stealing on launch is a requested feature https://github.com/mpv-player/mpv/issues/7725
not accepting any input should be possible by deactivating all keybindings with `--no-input-default-bindings`, which you already use, or is there another problem with that?

maybe the vo dragging needs to be deactivated too.

otherwise open a feature request if you want the desktop level change.

**Comment by sheharyarn** [comment]
Thank you for the quick reply. Yes, I think the `desktop` level is what I'm looking for. I'll open a feature request.

By not taking any input I meant it should never grab focus even on clicking. Ideally not showing it's menubar either. Not familiar with how macOS handles this so probably not that easy. Also not sure what "vo dragging" means, sorry.

**Comment by Akemi** [comment]
the title bar can be deactivated via --no-border, though the window still gets rounded corners with that.

never grabbing focus is probably not that easily possible. though it shouldn't make a difference if it stays in the background, besides the menu bar.

vo dragging is the feature to drag the window when clicking anywhere on the window, holding it and moving the window around.
