### ISSUE TITLE
RFC: Rename "master" branch to "trunk"

### ISSUE THREAD

**Issue by pigoz** [mpv-player/mpv#7836]

**Comment by haasn** [comment]
Vote agree, if only to piss people off and laugh at the fallout.

**Comment by CounterPillow** [comment]
oh please do we need to shitpost about this? it's so tiring

**Comment by Dudemanguy** [comment]
Let's just make it in Japanese to better represent the primary target audience of this project. So "ご主人様"

**Comment by pigoz** [comment]
> Let's just make it in Japanese to better represent the primary target audience of this project. So "ご主人様"

I don't think windows has unicode support yet

**Comment by pigoz** [comment]
> oh please do we need to shitpost about this? it's so tiring

It's a small change, and it helps developers stuck with past technologies more welcome. You can think of this as the final assault to mplayer1.

**Comment by CounterPillow** [comment]
Hello and welcome to this year's iteration of "internet kneejerk over some bugman shitlib's feelgood faux woke word policing," you've sure heard of the past 5 or 6 such annual events we've held! If you're just joining us, in this competition, we purposefully seek out wokescolds on twitter who want to feel like they're doing "their part" to fight systemic racism by being very conscious of the set of words that are cool and nice to use this month, and shaming everyone who does not spend as much time on the computer.

We then act like this person is someone that will truly endanger the very foundations of how we type text into computers collaboratively, and use the various SF bay area startups jumping on the bandwagon for publicity to fuel their unsustainable capitalist growth model as evidence that It's Truly Big This Time™, and that they're going to make us wear skirts before using a computer or something.

Of course, we're too cool to blurt out these beliefs directly, because we've learned that it also makes us look like schizoid idiots online. Instead we hide behind several layers of sarcasm that are neither clever nor funny, but merely beating a dead horse that has been thoroughly mushed into a pulp since the "politically correct unix" days.

Nothing will change, everything will be forgotten about in 2 months time, but at least we've all played our role in this stupid theatrical display so that one side can feel like they solved racism and the other side can feel like they've defended freedom and rationality. Either side will then retreat to their respective circlejerks to pat themselves on the shoulder for how well of a job they did this time, and how crazy the world is we're living in.

**Comment by qyot27** [comment]
>I don't think windows has unicode support yet

That happened two years ago, actually.  They just snuck it in there and didn't announce it apart from a couple of tech pages about UWP apps and whatnot.  I remember Notepad finally defaulting to UTF-8 w/o BOM and understanding LF correctly getting a lot more press.

Language->
Administrative language settings->
Language for non-Unicode programs->'Change system locale' button->
Enable the 'Beta: Use Unicode UTF-8 for worldwide language support' checkbox.

**Comment by Akemi** [comment]
since **master** has such negativity attached to it we should reverse it to negate that negativity. my proposal is to name it **retsam** instead

**Comment by richardpl** [comment]
Rename it to slave.

**Comment by wm4** [comment]
English is an inherently racist language to begin with. It's the language of the conquerors, invaders, and slave owners. Keep in mind that this is the language the people kidnapped from Africa had to learn - to understand the commands of their owners. The whole reason English is a lingua franca (and how a hungarian project designed for watching japanese cartoons came to use it as official language) is because of the brutal history of anglo colonialism. And the language is inseparable from this culture.

So I can't take it seriously when people go around and cherry-pick random English words, declare them as problematic, require that everyone invents other (more awkward) words to use, and threatens to label whoever disagrees as racists. It's amazing that anyone listens to them. All it really achieves is polarizing and politicizing everything, seeding conflict, and ultimately helping the far-right rise. Is that what you want, seeding as much conflict until everything explodes, and every country gets this abortion that is US politics?

That brings me to my next point: fuck off with US politics. Just take them and shove them up your american stinky shithole. This is not an american project. We're using the English language only as lowest common denominator. We don't want your american shit, with murderous cops, looting gangs, hate everywhere, two camps who would like to genocide each other. It's disgusting. Go away.

Of course pigoz opened this issue as a joke only, which makes it toxic (or whatever label is to be used?) instead of commendable. Strange stuff. Oh, also funny thing: how slavs are still called slavs, and nobody from the PC camp gives a shit.

**Comment by garoto** [comment]
`trunk` isn't PC either since it's to closely associated with the karma-heavy word `post`. Not good enough EU people.
