### ISSUE TITLE
[enhancement] stats/display-stats ("i" shortcut) is missing subtitle and language information

### ISSUE THREAD

**Issue by mattia-b89** [mpv-player/mpv#7847]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
stats/display-stats (called by pressing "i" or "I" key during the playback) should show information about:

1. language selected (under "audio" section), just the current one, not all available
2. subtitle selected (under "video" section?), just the current one if selected or "none" if disabled, not all available

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/4807985/output.txt)

**Comment by Argon-** [comment]
There's very limited space available (amount of lines) on the screen for stats. In fact, the default page was only recently shortened because it was too high for certain aspect ratios. This in itself is a fundamental problem. The solution would be to introduce a separate page to display all available audio/sub languages but this already exists: `script-message osc-tracklist` (use in `input.conf`).

There's one more reason I'd advise against it. The language is something you set yourself, so you know the values already. There's no need to see them because you set them. 
You either go with the default (default language/first track) or set certain mpv options to select specific languages. In both cases, you know what you got. It just works. *Unless* it didn't work (e.g. incorrectly tagged tracks). Then you need to change the selection by hand which you can only reasonably do by cycling through all available options or by looking at `osc-tracklist`. And then you set the language yourself and know what it is. There's no point in presenting this information back to you.

**Comment by kasper93** [comment]
Fixed by: #14330
