### ISSUE TITLE
[Bug Report]loop-file repeats only the first file

### ISSUE THREAD

**Issue by vsub** [mpv-player/mpv#7858]
Using the latest windows binary x64 mpv version if you set the loop-file option to anything(lets say 5)and add multiple files by dropping them over the mpv window(to create a playlist),it makes mpv repeat the first file 5 times and every other file just once

It was always running like this and if you want to slideshow pictures,you will not be able to because the first file is repeated 5 times and everything else is displayed once for 1 second per file

**Comment by CounterPillow** [comment]
Please don't ignore the issue template. If you're trying to show pictures for longer than 1 second, then there's a better option than looping them, it's called `image-display-duration`.

If you're looking to loop the whole list several times instead of the individual files, then you're looking for `loop-playlist`.

**Comment by vsub** [comment]
Sorry,I figure it out
I need to use the image-display-duration option and add a profile for gif files because they are played only once
