### ISSUE TITLE
ao_pulse: Audio file playback stalls at beginning

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#7874]
### Important Information
<pre>
mpv 0.32.0-570-g22a27c6720 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat Jun 27 22:21:25 CEST 2020
FFmpeg library versions:
   libavutil       56.55.100
   libavcodec      58.93.100
   libavformat     58.47.100
   libswscale      5.8.100
   libavfilter     7.86.100
   libswresample   3.8.100
FFmpeg version: N-98326-gb6fbbe08c3
</pre>

### Reproduction steps

Play a playlist of multiple audio files from a network file system.
This is not reliably reproducible, I suspect it's dependent on how fast the disk reads complete.

Reproduction by provoking audio underruns: (happens mid-playback)
<pre>
$ wget https://0x0.st/iybB.flac -O a.flac
$ pv -L 60000 a.flac | mpv --no-config -v --mute -
</pre>

### Expected behavior

1. File plays

### Actual behavior

1. File doesn't play despite mpv not being paused.
Pausing/unpausing doesn't resolve this, seeking does.

Notably `[cplayer] Audio device underrun detected.` appears when this happens.

### Log file

[cut.txt](https://github.com/mpv-player/mpv/files/4870283/cut.txt)

`3185.840`: previous file finishes playing
`3186.003`: playback is supposed to restart but doesn't
`3318+`: I toggle play/pause a few time, playback remains stalled
`3543+`: I seek to the beginning and unpause, playback starts

Different log: https://0x0.st/iybE.log playback is supposed to start at 21.643 but doesn't

**Comment by rubyFeedback** [comment]
I am not sure this is specific to mpv per se because I actually also have had similar problems in general. For example, I try to play a file with mpv, no audio. I kill mpv, try again. No audio. I kill mpv, try again - suddenly the file plays fine.

There are also messages on the commandline, lots of error messages and stuff. When I go back to pure ALSA instead, and disable pulseaudio, I have no issue and things work fine. This may all depend on the setup and user (after all the sound DOES work even with pulseaudio), but I found the pure ALSA output simpler than the additional pulseaudio layer. So that is what I tend to use, with mplayer, mpv, vlc etc... (I use palemoon as browser too, so I guess this is a niche ecosystem that I use here on Linux).
