### ISSUE TITLE
Full screen controls stop working after maximized by osc windowcontrols

### ISSUE THREAD

**Issue by dardoor** [mpv-player/mpv#7887]
- mpv version: 0.32.0
- Windows Version: Windows 7 64bit
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files

### Reproduction steps
1. Use no-border in mpv.conf to make the osc-windowcontrols appear.
2. Open a video.
3. Make it full screen it by clicking the windowcontrols maximize button.
4. Try to exit full screen by pressing F or double clicking LMB.

### Expected behavior
Exits fullscreen.

### Actual behavior
Stays in fullscreen (and the taskbar appears).

**Comment by dardoor** [comment]
On second thought, I guess the original problem is that the maximize button works as a (fake?) full screen, instead of what you'd expect from a standard maximize window function. So things get messy after that.

This whole new windowcontrols thing is a weird and IMO not needed feature. Thankfully it can be disabled.

**Comment by avih** [comment]
> Make it full screen it by clicking the windowcontrols maximize button.

Clicking the maximize button maximizes the window - it doesn't make it full screen.

They do look the same when there's no border, so the source of confusion is clear.

I don't know if making the maximize button do fullscreen instead of maximize is better or not...

**Comment by dardoor** [comment]
> Clicking the maximize button maximizes the window - it doesn't make it full screen.
> 
> They do look the same when there's no border, so the source of confusion is clear.

Yeah, I see that now.
Is there a technical reason for why it works that way, instead of leaving space for the taskbar like most other maximized programs?

**Comment by avih** [comment]
> Is there a technical reason for why it works that way, instead of leaving space for the taskbar like most other maximized programs?

Good question, though unrelated to the OSC maximize button. It seems that when there's no border, setting the `window-maximized` property to `yes` covers the whole screen, but with a border it "stops" at the taskbar.

I don't know if it's a windows or an mpv thing, though I do agree the more expected behavior for maximize would be to not-cover the taskbar regardless if there is or isn't a border.

Maybe @rossy would know more?

**Comment by rossy** [comment]
It's kind of a Windows and a mpv thing. When --no-border is set, mpv creates what's known in Win32 as a popup window. Unlike normal (overlapped) windows, popup windows don't consider the size of the taskbar when maximised, so they take up the whole screen instead. Also, the Windows taskbar uses a heuristic to detect fullscreen windows. If any window happens to have a client area that's the same size as the screen, it considers it a fullscreen window and "helpfully" hides itself. Because of this, the "maximized" mpv is indistinguishable from fullscreen, even though mpv doesn't consider itself to be fullscreen. The maximize and fullscreen buttons in mpv still work independently, but both states appear as fullscreen.

It would be possible to fix this by creating a borderless overlapped window instead, since an overlapped window would avoid covering the taskbar, but creating borderless overlapped windows is tricky.
