### ISSUE TITLE
Disabling natural sorting

### ISSUE THREAD

**Issue by Bl4Cc4t** [mpv-player/mpv#7961]
Is there a way to disable natural sorting?
I have a lot of files that have hexadecimal filenames and would like to play them in the correct order.

**Comment by avih** [comment]
I don't there's a way to disable it.

Out of curiosity, which tool or use case has media files with hex numbers?

**Comment by Bl4Cc4t** [comment]
Some sites have their files named like this (mostly images).

This is the natural sorting order:
```
$ ls -1 -v 
26e5570b1bce8.png
26e5571d04c40.png
26e55704af866.png
26e55712ebc91.png
```

and here is how I would like to have it:
```
$ ls -1
26e55704af866.png
26e5570b1bce8.png
26e55712ebc91.png
26e5571d04c40.png
```

I know this is a question, but would it be possible to implement this feature?

**Comment by avih** [comment]
Almost everything is possible in software, and it's mostly a question of effort and/or will. In this case it was alphanumeric and was changed to natural order about a year ago at commit a7158ceec0 because we thought it's better for most users.

If you build can mpv yourself then you can either revert this commit, or change this line:
```c
    return mp_natural_sort_cmp(*(char **)a, *(char **)b);
```
to this line:
```c
    return strcmp(*(char **)a, *(char **)b);
```
[here](https://github.com/mpv-player/mpv/blob/master/demux/demux_libarchive.c#L36) and [here](https://github.com/mpv-player/mpv/blob/master/demux/demux_playlist.c#L361) .

Adding the sort type as an option needs more consideration of balancing how useful it is to a reasonable amount of users (my guess is not too much), how easy it is to achieve in other ways (quite easy usually, e.g. with an mpv shell wrapper that lists the files in any order you want, or lua/js script which reorders the entries, etc).

Personally I think it's not worth adding as an option, but other developers might think differently.

**Comment by Akemi** [comment]
> or lua/js script which reorders the entries, etc

i think this is the most appropriate for now. since the question has been answered, i am closing this.

**Comment by Bl4Cc4t** [comment]
Okay, I guess I'll stick with an older build then
