### ISSUE TITLE
GPL violation

### ISSUE THREAD

**Issue by time-killer-games** [mpv-player/mpv#7987]
Hey, I just wanted to inform you guys that I accidentally violated your GPL license by distributing the binary without providing the source. I linked to your website initially on the site i distributed the binary, and explained the source may be retrieved from there. I originally thought that would be sufficient based on what other people have told me. But someone else brought to my attention conflicting information that appeared to be more correct, as they sited their source of information. 

I correct the problem within roughly 24-hours by publishing an update which includes the source code. More information can be found here: https://forum.yoyogames.com/index.php?threads/video-player-for-windows-and-ubuntu.77882/#post-462048

I wanted to inform you of my mistake not because I wanted to get in trouble legally, I just found it morally correct to let you know, and that also I have corrected the issue to the best of my knowledge.

----------------------------

Now for my questions...

I would like to ask if my impression on a different matter is correct - am I permitted to run the mpv media command line program from the shell in applications that are proprietary or otherwise closed source? This I have been told is ok to do by someone who works for Google and is well aware of such legal matters, but I just wanted to be absolutely sure. The reason he said it was not a violation to have the software that runs the player closed source is because in a legal sense it is not technically linking with the software, whether statically or dynamically, therefore it is permissible. Is this piece of information 100% right?

Slightly unrelated but I do have another question, is the update on to the source code that was committed yesterday on this repository here on github the same update that was published in binary form yesterday to sourceforge? Does my distribution of the binary software have to match the exact source code it was built from line for line exactly to avoid GPL violation? At the time of writing that is the exact source and binary I have included for the distribution I uploaded. If this is not acceptable, please steer me in the right direction of which copy of the source of which most recent binary I should download and distribute with each other. I updated my asset to include the source code without asking this question here hoping I might solve the issue as quickly as possible if you guys are at all lax or understanding about these things. Depending on what you tell me to do I will update my uploaded distribution again to address any leftover mess I've made before any more people download it, which I'd like to correct this as soon as possible to avoid getting in trouble, if I'm not in trouble already. I apologise for this,

**Comment by wm4** [comment]
>Hey, I just wanted to inform you guys that I accidentally violated your GPL license by distributing the binary without providing the source.

From what I know, you don't need to provide the source code proactively, but only on request. (Maliciously acting GPL violators have used this in the past to be assholes, and provided the source code only via physical mail, and funny stuff like that.)

>I linked to your website initially on the site i distributed the binary, and explained the source may be retrieved from there. I originally thought that would be sufficient based on what other people have told me. But someone else brought to my attention conflicting information that appeared to be more correct, as they sited their source of information.

A bit surprising to me. I mean, maybe you might be technically required to offer a tar ball of the sources anyone who's asking.

>I would like to ask if my impression on a different matter is correct - am I permitted to run the mpv media command line program from the shell in applications that are proprietary or otherwise closed source?

Yes. That's how everyone interprets the GPL at least.

>Slightly unrelated but I do have another question, is the update on to the source code that was committed yesterday on this repository here on github the same update that was published in binary form yesterday to sourceforge?

We don't know. We don't publish anything on sourceforge. We link to unofficial builds - but they're not by us, thus unofficial.

>Does my distribution of the binary software have to match the exact source code it was built from line for line exactly to avoid GPL violation?

I think if someone requests the source code, you have to be able to provide the exact source code it was built from. On the other hand, if you didn't even build the binary, maybe it's OK to defer such requests to the actual source. I'm not entirely sure if that is sufficient, but maybe yes. Also if this is built from git (a commit contained in master or any other public branch), then, in my opinion, linking the git should be sufficient. From a purely legal point of view, this might not be enough, but IANAL. In any case, if there are no private changes to the source code, I don't see any problem. Since it's not _you_ who is making this builds, but another unrelated 3rd party offering these builds publicly, this isn't quite straight forward.

This is not legal advice. The legal system is optimized towards sinking your money into lawyers to get definite answers that won't hold up in court.

**Comment by time-killer-games** [comment]
Thanks for the insight!

**Comment by CounterPillow** [comment]
shinchiro's windows build probably also contain the git short hash in both the archive name and the `--version` output, so you can basically refer people to this repository and you should do fine. GPL isn't as scary as people make it out to be.

**Comment by haasn** [comment]
Concerning your other question, you can even build LGPL versions of mpv
+ dependencies and link to libmpv directly. (But I think LGPL ffmpeg
comes with some restrictions)
