### ISSUE TITLE
Disable terminal output when launching mpv from command line

### ISSUE THREAD

**Issue by rightaway** [mpv-player/mpv#7995]
### Expected behavior of the wanted feature

When I open a file in mpv from the command line `mpv ~/folder` or `mpv ~/folder/file.mp4`, it opens mpv player but also changes the command line to show the playback and let you control it from the terminal. Can we have a setting in the config file to disable this for video files? Since the video player opens and we can control the playback from there, the command line should immediately return and not have any output so that we can continue using that terminal window for other things.

**Comment by orbea** [comment]
```
mpv /path/to/some/video/file &
```

**Comment by CounterPillow** [comment]
You have two requests in one there. As orbea explained, what you want is to detach the process with `&` after its invocation; this is just common shell usage. What you probably also want is to pass mpv the option `--no-terminal` in addition to that, so it doesn't output anything either.

**Comment by UnixCro** [comment]
How I can turn this shit off?

```
File: Song1.m4a
File: Song1.m4a
File: Song1.m4a
File: Song1.m4a
File: Song1.m4a
File: Song1.m4a
File: Song1.m4a
File: Song1.m4a
File: Song1.m4a
File: Song1.m4a
File: Song1.m4a

	Size: 3.340 MiB	Format/Protocol: mov,mp4,m4a,3gp,3g2,mj2
	Total Cache: 38.52 KiB (1.0 sec)

Audio: aac (AAC (Advanced Audio Coding))
	Channels: 2	Format: floatp
	Sample Rate: 44100 Hz
	Bitrate: 127 kbps
````

**Comment by guidocella** [comment]
`--really-quiet`, or `--no-terminal` if you also want to disable terminal input.

**Comment by UnixCro** [comment]
These parameters are not too bad, but they block too much. Only the seconds display should be displayed. Possibly a codec. But not every millisecond is displayed which song is being played and my terminal output is completely filled.

**Comment by UnixCro** [comment]
And sorry for the ping.

```
2022-07-03 10:16:11.770 mpv[96853:17200932] Warning: Expected min height of view: (<NSButton: 0x7fa04ef31b30>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-07-03 10:16:11.771 mpv[96853:17200932] Warning: Expected min height of view: (<NSButton: 0x7fa04ef37270>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-07-03 10:16:11.771 mpv[96853:17200932] Warning: Expected min height of view: (<NSButton: 0x7fa04ef37bf0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
```

What is mpv problem?

**Comment by guidocella** [comment]
`--display-tags-clr --msg-level=cplayer=error`

**Comment by UnixCro** [comment]
`--display-tags-clr` Finally it works as I imagined.
Thanks. Please stay healthy forever!

**Comment by Galicarnax** [comment]
Using `--no-terminal`, even though some output is suppresses (such as progress), I still get some. E.g.:
```
libdvdread: Encrypted DVD support unavailable.
libdvdread: Couldn't find device name.
libdvdnav: Can't read name block. Probably not a DVD-ROM device.
libdvdnav: vm: dvd_read_name failed
libdvdnav: DVD disk reports itself with Region mask 0x00000000. Regions: 01 02 03 04 05 06 07 08
Updated device 'nv_backlight':
Device 'nv_backlight' of class 'backlight':
	Current brightness: 100 (100%)
	Max brightness: 100
```
even though the file begins to play Ok (the message about `nv_backlight` is from my Lua script in which I dim second display when `mpv` goes fullscreen, by using `os.execute(...)`). How can I really-really disable any output, including from user scripts, so that, e.g. when opening a youtube link from terminal chat client, the chat wouldn't scramble up? BTW, no difference when using `--really-quiet`.

I even tried `mpv --no-terminal > /dev/null`, that helped to get rid of the `libdvd` messages, but the ouptut from Lua's `os.execute` still makes it way to the terminal!

**Comment by UnixCro** [comment]
Try to add the argument `2&>1 1>/dev/null`

**Comment by Galicarnax** [comment]
I actually tried that - no difference (the output about backlight is a normal diagnostic message, not an error, so I guess it's get printed to `stdout` by `os.execute`).

**Comment by Galicarnax** [comment]
I've found that this does not happen when running `mpv` verbatim in terminal (`mpv --no-terminal 2&>1 1>/dev/null /path/to/video` - no any output as expected). What I had described happens when `mpv` is invoked via `mimeo` (e.g., from terminal chat client), even though I have the same `mpv --no-terminal 2&>1 1>/dev/null` indicated in `mimeo` files associations.

**Comment by dudeawsomeness1** [comment]
> Try to add the argument `2&>1 1>/dev/null`

For me this makes a file called "1". Use `&>/dev/null` instead (https://askubuntu.com/a/350216).
