### ISSUE TITLE
CPU & Memory

### ISSUE THREAD

**Issue by DjBenny** [mpv-player/mpv#8025]
Can You Please Fix The High CPU & Memory Usage? I Have The Very Latest Version I Check For New Updates Every 3 Days.. And When I Watch 1080p BluRay Remux Movies Or Other Formats The CPU Is More Than 25 Very High I Tested Other Players Like VLC Is Very Low Perfect.. Only MPV Have Very High Usage... Can You Please Fix This Coz I Really Love MPV Player. And God Bless You All For Making This Amazing Player.

**Comment by CounterPillow** [comment]
Hello You Can Use `hwdec=auto` In Your `mpv.conf` To Use Fixed Function GPU Decoding Instead Of CPU Decoding Which Should Lower CPU Usage Also You Can Use `demuxer-max-bytes` Like `demuxer-max-bytes=10M` To Limit How Large The Cache Grows, Other Than That The Rest Of The Memory Usage Is Probably Caused By The Libass Glyph Cache Which Is Outside Of MPV Player Control.

**Comment by DjBenny** [comment]
> Hello You Can Use `hwdec=auto` In Your `mpv.conf` To Use Fixed Function GPU Decoding Instead Of CPU Decoding Which Should Lower CPU Usage Also You Can Use `demuxer-max-bytes` Like `demuxer-max-bytes=10M` To Limit How Large The Cache Grows, Other Than That The Rest Of The Memory Usage Is Probably Caused By The Libass Glyph Cache Which Is Outside Of MPV Player Control.

Can You Please Tell Me How To Use Them Coz Im Using Windows 10 And MPV Dont Have Any Options

**Comment by DjBenny** [comment]
And Im Wondering Why VLC Is Ok.. I Mean It Has Very Very Low % Usage From 0-5 And MPV Have More Than 20% Sometimes 30% ... Can You Please Tell Me How To Fix This, But Without Losing Any Quality In Movies.

**Comment by DjBenny** [comment]
![MPV](https://user-images.githubusercontent.com/46375614/91086194-df838f00-e64e-11ea-894d-2cbd7d7fee40.png)

**Comment by DjBenny** [comment]
Even Memory Goes To 450%

**Comment by CounterPillow** [comment]
> Can You Please Tell Me How To Use Them Coz Im Using Windows 10 And MPV Dont Have Any Options

Read the files on Windows section of the official manual. https://mpv.io/manual/master/#files-on-windows

Create a text file named `mpv.conf` (make sure you don't accidentally name it `mpv.conf.txt`, that's a common mistake because Windows hides known extensions by default) and put those two options I mentioned in on separate lines.

**Comment by DjBenny** [comment]
Bro I Cant I Dont Know How, Pls Tell Me More Detailed.. Please Make An Example Vith Photos Or Gifs.

**Comment by WizRay** [comment]
Now i am wondering whether you're a troll or not. Read the links @CounterPillow provided and follow his intructions. It can't get any simpler. To enable hardware decoding during video playback, you can pause the video and use the shortcut `ctrl+h`.
