### ISSUE TITLE
How to debug mpv On Window

### ISSUE THREAD

**Issue by wxz879526** [mpv-player/mpv#8031]
Cross compile in ubuntu by mingw, how to debug mpv code? thanks

**Comment by jeeb** [comment]
Make sure you didn't strip symbols (mpv I think by default doesn't, for FFmpeg you need `--disable-stripping` in the configure line for example). Use a mingw-w64 built gdb. I am still using one I built ages ago (https://kuroko.fushizen.eu/random/gdb_builds/gdb-8.0.1.7z).

Tried building a newer one but somehow I always end up getting a bad stack trace.

Alternatively look into wbs's clang/llvm based mingw-w64 toolchain which can create PDB files which MSVS or windbg can load: https://github.com/mstorsjo/llvm-mingw

**Comment by rubyFeedback** [comment]
I can not assist, due to my lack of knowledge, but I would like to say that the above information is quite appreciated, probably not only by me. I am a linux guy (and ruby guy), but I am also now using a win10 laptop, with wsl1 (for now). At a later point I may want to look into similar setups (ming, msys2 etc...), so every information here is really really helpful in the long run; specifically to what jeeb contributed here. It still seems quite complex though.

**Comment by Akemi** [comment]
closing since the question has been answered and there weren't any more replies.
