### ISSUE TITLE
Stdout/pipe Output Driver

### ISSUE THREAD

**Issue by Rio6** [mpv-player/mpv#8036]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
Having an output drivers that pipes video and audio data to stdout.

So it's possible to do things like using ffmpeg to write to v4l2loopback, directly play video inside graphical terminal (with some backend script), etc. I think it'd be pretty nice to have mpv just as a file/playlist loader plus playback control, while using other programs to render the video.

### Alternative behavior of the wanted feature
Piping to a fifo can probably work too.

### Log file
Don't have one for the feature request.

**Comment by thebombzen** [comment]
Why would you want to do this? Which program would you want to render the video?

**Comment by thebombzen** [comment]
I ask because there are a few ways to do this without adding code to mpv, depending on what you're trying to do:
- If you're trying to save the file for later, you can use `--o` or `--stream-record` depending on the situation.
- If you're trying to send it over the network, to another device, you're better off running mpv on that other device, and potentially send playback controls via IPC
- If you're trying to test another rendering engine, you're better off just embedding libmpv and using libmpv to handle the playback and have you handle everything else with your frontend. 
Is this something that really needs to be added to mpv?

**Comment by Rio6** [comment]
I was looking for this feature when I tried to play video through v4l2loopback. On theire wiki, they use a [fifo to stream mplayer's output](https://github.com/umlaeute/v4l2loopback/wiki/Mplayer#producer-1), that's where I thought it'd be nice if mpv can output to a pipe.

Probably not something that'd be used often though.

**Comment by thebombzen** [comment]
Just use `--stream-record` for this.
