### ISSUE TITLE
--enable-cplugins does not generate mpv.pc

### ISSUE THREAD

**Issue by CounterPillow** [mpv-player/mpv#8048]
### mpv version and platform versions

git master

### Reproduction steps

1. Build mpv with `--enable-cplugins` but without `--enable-libmpv-shared` or `--enable-libmpv-static`
2. No `mpv.pc` file is generated from `mpv.pc.in`

### Expected behavior

An `mpv.pc` file with only the includes is generated for cplugins to use, as any cplugin will at least need the mpv headers, so could benefit from `pkg-config --cflags mpv`.

### Actual behavior

`mpv.pc` is only generated if libmpv is built, which doubles the build time. Exact wscript code that triggers this can be found here: https://github.com/mpv-player/mpv/blob/master/wscript_build.py#L637

### Log file

Not really applicable.

**Comment by wm4** [comment]
The solution is to pass one of the configure options you mentioned.

**Comment by Dudemanguy** [comment]
Meson behaves the same way, but just for the sake of explaining here. An already compiled .so plugins works 100% fine on an mpv binary with cplugins enabled without any headers being needed at runtime. Now of course, if you want to compile the cplugin yourself and/or develop your own you will need those headers since it uses the client API. We could hypothetically always generate a .pc + install headers if cplugins are enabled, but that would essentially mean always installing that stuff on any user's machine (well not including Windows of course) if they don't explictly disable cplugins (which they probably don't want to do because it's useful).

Since the headers are only needed for development reasons (compiling, making your own, etc.), I think hiding it behind the libmpv switch is fine. Someone that just wants to run `mpv` has no use for it. Now yes, it would increase buildtime for the person out there that doesn't want libmpv.so in any way shape or form and still wants the .pc and headers, but I think this is pretty niche and not worth worrying about. We could hypothetically come up with a third check but eh. Distros split out the dev and lib out for us in packages, so I don't think we really need to worry about this. Closing for now.
