### ISSUE TITLE
Sometimes when mpv closes it freezes "whole" system

### ISSUE THREAD

**Issue by SGOrava** [mpv-player/mpv#8062]
### Important Information
The "whole" in title mean that most of the modern programs will be frozen unless killed.
From my humble perspective affected programs are using some gpu acceleration (opengl) to be drawn.
The best example of such program is compositor and modern gui toolkit (qt/gtk).

Provide following Information:
- mpv version 0.32.0
- Linux Distribution and Version Artix
- Source of the mpv binary Artix Repository
- If known which version of mpv introduced the problem Nope, but it is doing this for a while
- Window Manager and version Openbox 3.6.1 + picom or unagu
- GPU driver and version i965 (for my intel laptp) and amdgpu (for my current pc)
- Kernel version 5.8.4
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

RANDOM

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior
MPV closes and everything else is still fine.

### Actual behavior
When MPV closes system freezes at random. To be more precise the compositor and all programs using gpu/opengl (which are almost all since major toolkits like gtk and qt are doing so) will freeze.
In my case when I kill compositor (picom) Openbox is still running fine but all other GUI programs are frozen and need to be killed with "kill -9"

### Log file
sadly I do not have one, on the intel laptop it said something in dmesg that gpu error and it reloaded it. I can try to get it in a while.

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

In this case no sample files are needed, it can happen with any file

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

### Simillar issues:
The issues which sounds very similar to my own:
https://github.com/mpv-player/mpv/issues/7959 , https://github.com/mpv-player/mpv/issues/5876

### My mpv config:
```
profile=normal

[normal]
alang=jpn,eng,en,sk,cs,cz
slang=jpn,eng,en,sk,cs,cz
```

**Comment by wm4** [comment]
Likely just a problem with your GPU drivers or compositor, especially if mpv has actually terminated when the freeze happens. Nothing mpv can do about.

**Comment by SGOrava** [comment]
Drivers? That is an excuse, drivers are fine. It happens on intel and amd drivers how can both drivers be bad?

It can have something to do with compositor, I suspect that, that is why I am trying to get this error without compositor.
The question I ask is: Why would mpv kill standard compositor when all other programs (even wine) dont?

**Comment by wm4** [comment]
Then report it to your compositor. mpv doesn't try to freeze other programs.

**Comment by haasn** [comment]
On Sun, 06 Sep 2020 13:16:15 -0700, Juraj Oravec <notifications@github.com> wrote:
> Drivers? That is an excuse, drivers are fine. It happens on intel and amd drivers how can both drivers be bad?

OpenGL semantics forbid a misbehaving client freezing the system.

**Comment by SGOrava** [comment]
It has nothing to do with compositor, just tested without it. And same behaviour as before.

**Comment by SGOrava** [comment]
> On Sun, 06 Sep 2020 13:16:15 -0700, Juraj Oravec ***@***.***> wrote: Drivers? That is an excuse, drivers are fine. It happens on intel and amd drivers how can both drivers be bad?
> OpenGL semantics forbid a misbehaving client freezing the system.

How else should I describe it?
When mpv closes all programs become unresponsive. Be it terminal emulator, web browser, text editor, panel, compositor.

**Comment by SGOrava** [comment]
[Vivid Strike「ＡＭＶ」Inside Of Me-PKgtLndRlm4.mp4.txt](https://github.com/mpv-player/mpv/files/5180280/Vivid.Strike.Inside.Of.Me-PKgtLndRlm4.mp4.txt)
Here is a log from MPV from time when it happened

**Comment by wm4** [comment]
At the point it shows that message it basically calls only `XCloseDisplay()`. If your system freezes because of this, there must be something wrong with your drivers, X server, or compositor.
The only way mpv could actually freeze your computer is:
- maliciously interfering with your system (probably not the case)
- aggressively using all CPU time, GPU time, or memory (could happen with "bad" files, you can tell with `top` whether this is the case)
- using a "dangerous" API like DRM

Your kernel log is probably more interesting than the mpv log. But not ours to debug.

**Comment by SGOrava** [comment]
It could also be that I started X from tty1 and set it to use tty1 (I can only think of this because some other little things are strange but I like them anyway.)

**Comment by wm4** [comment]
Please reword that.

**Comment by VincentChalnot** [comment]
Hello, I clearly have the exact same issue as mentioned above and I'm forced to reboot each time it happens.
It was perfectly reproducible, it happened each time I closed mpv after reading a video but right now I can't seem to reproduce it.
Note that it doesn't happen while mpv is still running but only after closing it.
I'll try to dig further into this when it happens again.

**Comment by PaperOrb** [comment]
> Hello, I clearly have the exact same issue as mentioned above and I'm forced to reboot each time it happens. It was perfectly reproducible, it happened each time I closed mpv after reading a video but right now I can't seem to reproduce it. Note that it doesn't happen while mpv is still running but only after closing it. I'll try to dig further into this when it happens again.

Did you ever get this figured out? I'm having this system-freezing issue when closing MPV as well.

**Comment by PaperOrb** [comment]
@VincentChalnot @SGOrava  Did you ever get this figured out? I'm having this system-freezing issue when closing MPV as well.

**Comment by VincentChalnot** [comment]
I'm using VLC now 😅

**Comment by cprn** [comment]
I have the same symptom, but I'm not sure it's the same issue. I'm having it for about a month now, but I narrowed it down to scripts calling shell commands in the background, e.g. I can reproduce it when using a custom script that marks a video for deletion on exit:

```
❯ mpv .
Playing: ./millennials-meme.mp4
 ● Video  --vid=1  (av1 3840x2160 60 fps) [default]
 ● Audio  --aid=1  (aac 2ch 44100 Hz 160 kbps) [default]
AO: [pipewire] 44100Hz stereo 2ch floatp
VO: [gpu-next] 3840x2160 yuv420p
[rm_or_wipe] deletion mode: rm
AV: 00:35:38 / 00:36:03 (99%) A-V:  0.000
Exiting... (Quit)
# normally something like `shell: rm ./millennials-meme.mp4` goes here, confirming successful deletion, but it doesn't happen
```

This freeze is tightly related to my `/home` mounted HDD suddenly becoming unreadable, but the system itself remains partially responsive, because in my case it's on a different physical drive (e.g. I managed to open a tab in the browser and fill this ticket)... still, things like e.g. opening a new terminal (which reads rc files), or trying to log in on tty (which reads `/etc/passwd`), hang forever. There's no issue if I manually `rm` the file from the terminal. If you had some `mpv` add-on scripts installed, and the video you were watching was on the same drive as your system, it might be the same issue.

I'll edit my script to call something more akin to: `strace -o ~/tmp/mpv.log rm ./millennials-meme.mp4` instead, and thus try to debug this further, so maybe it'll help narrow the issue down(or prove it's not `mpv` at all, maybe my drive's just failing and it's a coincidence 🤷‍♂️), but IDK when.
