### ISSUE TITLE
White Line on Top of mpv

### ISSUE THREAD

**Issue by robrt1010101** [mpv-player/mpv#8066]
### Important Information

Provide following Information:
- mpv version - 032.0
- macOS Version - 10.15.6
- Source of the mpv binary or bundle - https://laboratory.stolendata.net/~djinn/mpv_osx/
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

https://i112.fastpic.ru/big/2020/0908/d7/a18015c1b360eb7aadc804898365bdd7.jpg

There is a distracting white line at the top of mpv, can this line be removed?
Thanks.

**Comment by Akemi** [comment]
the line you mean is probably the macOS window decoration. you can change the appearance of the window with `macos-title-bar-appearance` https://mpv.io/manual/master/#options-macos-title-bar-appearance.

if you are on the dark macOS theme, the auto selection was broken on djinn's build and fixed with https://github.com/mpv-player/mpv/commit/5d7f0edfebb9829eb167770f943970203bdf63c0#diff-179e359558516737f66996d5f9b7ce5c. this fix is only in master and in no version yet. for the dark theme "vibrantDark" is the default.

btw, this is a horrible image hoster.
