### ISSUE TITLE
Is there a way to always show the GUI in mpv?

### ISSUE THREAD

**Issue by sudo-panda** [mpv-player/mpv#8070]
I am talking about the minimal GUI that mpv has. Can the auto hide feature of it be disabled?

**Comment by emanuele6** [comment]
You mean the OSC (**O**n*-*S**creen **C**ontroller)?

Yes, you can disable it: by default, the `osc` option named "visibility" is set to *auto* (which means auto-hide), you can also set this option to *always* (to always show the OSC) or to *never* (to never show it).

To set this option to *always*, you can either put this line in `mpv.conf`:
```
script-opts=osc-visibility=always
```
Or you can, if you don't already have it, create a directory named `script-opts` in the same directory `mpv.conf` is in, and then, if you don't already have it, create a file named `osc.conf` in that directory and then put this line in that file; `script-opts/osc.conf`:
```
visibility=always
```

The second method is preferred because that `osc` setting won't be overwritten if you use `--script-opts=` to set another option; example:
```
mpv --script-opts=console-scale=2 ./video.mp4
```

**Comment by sudo-panda** [comment]
Thanks. This is exactly what I was looking for.

**Comment by emanuele6** [comment]
You are welcome! Check out the other OSC options too if you want: https://mpv.io/manual/stable/#configurable-options .
