### ISSUE TITLE
Big Sur ARM support ?

### ISSUE THREAD

**Issue by desudesune** [mpv-player/mpv#8083]
Will MPV be available for Big Sur ARM MacBooks when they arrive later this year?

**Comment by Akemi** [comment]
from what i can see there is nothing stopping it from working. opengl is still only deprecated but not removed. there is also nothing from our side that might prevent building for apple silicon. the only thing mentioned by apple on their [documentation about difference between apple silicon and x86](https://developer.apple.com/documentation/apple_silicon/addressing_architectural_differences_in_your_macos_code) is the mach_absolute_time part that we use. on all [occurrences in our code](https://github.com/mpv-player/mpv/search?q=mach_absolute_time&unscoped_q=mach_absolute_time) we already use the proper timebase instead of assuming something.

it should work via Rosetta 2 with the current bundles/binaries that are provided by third parties. for native code you should ask those who provide those bundles/binaries if they will provide a universal binary.

otherwise, since i don't have a DTK, we will have to wait and see if it will actually work.

**Comment by rgaufman** [comment]
Is anyone able to get mpv working natively on Apple Silicon/M1?

**Comment by Akemi** [comment]
yes, see #8288 and #8281

**Comment by fxcoudert** [comment]
For the record, it's not building for us at Homebrew:

```
  File "/private/tmp/mpv-20210107-19120-10dxp5l/mpv-0.33.0/waftools/detections/compiler_swift.py", line 201, in configure
    __find_macos_sdk(ctx)
  File "/private/tmp/mpv-20210107-19120-10dxp5l/mpv-0.33.0/waftools/detections/compiler_swift.py", line 158, in __find_macos_sdk
    minor = string.ascii_lowercase.index(version_parts.group(2).lower())
ValueError: substring not found
```

https://github.com/Homebrew/homebrew-core/pull/68460

**Comment by Akemi** [comment]
commenting on an already closed issue isn't really the best idea. if you want proper help please open a new one.

it would be helpful to know what `xcrun --sdk macosx --show-sdk-build-version` returns.

**Comment by fxcoudert** [comment]
@Akemi not really asking for help, actually… just adding information that I thought might be relevant to OP (Apple Silicon support is apparently incomplete)
