### ISSUE TITLE
Confusing/inconsistent behavior involving "ytdl-format", "ytdl_hook-try_ytdl_first=yes", an "auto-profiles.lua" (the new one) condition and a CLI arg

### ISSUE THREAD

**Issue by garoto** [mpv-player/mpv#8108]
### Important Information

- mpv version: 
```
mpv 0.32.0-723-g49f5c9b482 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Sep 15 01:13:12 -03 2020
FFmpeg library versions:
   libavutil       56.59.100
   libavcodec      58.106.100
   libavformat     58.56.100
   libswscale      5.8.100
   libavfilter     7.87.100
   libswresample   3.8.100
FFmpeg version: git-2020-09-14-05c8d0bc
```
- Windows Version:
```
Windows 8.1 Microsoft Windows [Version 6.3.9600]
```
- Source of the mpv binary
```
own compile using mia's/shinchiro's cross-compile script
```
- If known which version of mpv introduced the problem: ```n/a```
- Possible screenshot or video of visual glitches:```n/a```

### Reproduction steps

Generate a `conditional auto profile` rule that applies to a specific ${path} propertie:
```
[vreddit]
	profile-desc=videoreddit
	profile-cond=string.match(get("path", ""), "v.redd.it") ~= nil
	ytdl-format="(bestvideo+bestaudio/bestvideo)[protocol!*=m3u8]"
```

And then call mpv like this:

`mpv --script-opts=ytdl_hook-try_ytdl_first=yes --ytdl-format=bogus_format_string https://v.redd.it/d80ban0t0eo51`

The above will cause `ytdl_hook.lua+youtube-dl` to fail to find any formats based on the `--ytdl-format` string provided.

### Expected behavior

The  `--ytdl-format=` string declared via CLI should be overriden by the one declared in the [vreddit] profile and the player should successfully load the video in the example URL given.

### Actual behavior

```
> mpv --script-opts=ytdl_hook-try_ytdl_first=yes --ytdl-format=bogus_format_string https://v.redd.it/d80ban0t0eo51
 auto_profiles: Applying auto profile: vreddit
 ytdl_hook: ERROR: requested format not available
 ytdl_hook: youtube-dl failed: unexpected error occurred
   cplayer:
   cplayer: Exiting... (Quit)
```

Passing to the player a CLI argument like `--really-quiet` OR `--msg-level=all=no,ytdl_hook=trace`, makes the Lua condition to apply successfully everytime.

### Log file

The failed `ytdl_hook: ERROR: requested format not available` log:
https://0x0.st/ilpa.log

A succesfull parsing when giving the player the `--msg-level=all=no,ytdl_hook=trace` argument:
https://0x0.st/ilpS.log

### Sample files
n/a

wm4 mentioned this can be a race condition somewhere, so hopefully all this will can useful somehow. I guess there's more to it as well, but I coudn't find a place to fit all the extra info I have without being overly verborragic, not sure tho. Very confusing to troubleshoot.

**Comment by Argon-** [comment]
Wouldn't call this a race condition. As far as I understood your problem, this is expected behavior.
Auto-profiles are evaluated and based on a script. Lua scripts are probably(?) loaded after command line arguments were parsed. So your CLI arguments are set correctly but then auto-profiles.lua kicks in and overwrites it with your `[vreddit]` profile.

**Comment by garoto** [comment]
> Wouldn't call this a race condition [...]

@Argon-, I can't say either way regarding a race condition or not, but before posting this issue I posted this on IRC: https://0x0.st/il91.log.

Same settings were used in everything I posted until this moment. It either applies or not the profile at random when calling mpv via `cmd.exe`. The only sure way to make the `auto-profile.lua` condition to apply 100% of the time is to make mpv busy with a CLI arg like `--msg-level=all=no,ytdl_hook=trace` or `--really-quiet` and possibly others.

**Comment by Argon-** [comment]
Ah, I get what you mean. Both are scripts, so the youtube-dl hook could run before auto-profiles set the vreddit profile and the other way round, leading to varying results. 
(Also, auto-profiles could be loaded earlier but not yet apply the profile because the condition is not yet met - only later when some property gets a certain value)

But this doesn't change what I said above. Auto-profiles is designed to run and re-evaluate all the time. Even if you can consistently overwrite the initial conditions, profiles might re-evaluate seconds or minutes later, depending on the properties used.

In theory, you could extend the script and prevent CLI-set options from being overwritten.

**Comment by garoto** [comment]
But how can a CLI arg like e.g. `--msg-level=all=no,ytdl_hook=trace` or e.g. `--really-quiet` make the lua-script parsing work 100% of the time?

**Comment by garoto** [comment]
Closing this since this probably a poorly documented issue with hard, specific conditions for anyone to be able to reproduce without some really annoying tinkering. But my memory tells me there's some sort of weird race condition happening somewhere.
