### ISSUE TITLE
mpv can't play youtube url because youtube temporary banned

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#8124]
How can I play youtube url while youtube temporary banned in my country?

**Comment by Akemi** [comment]
get a vpn or proxy i guess?

**Comment by Max-Enrik** [comment]
I need to use Proxy. I already read some solution but didn't helped me. (VPN I don't need to use VPN just for youtube url - because VPN decrease speed of internet.)

**Comment by Akemi** [comment]
https://mpv.io/manual/master/#options-ytdl-raw-options

read the manual then.

**Comment by Max-Enrik** [comment]
Nice, I have to do it by myself. Thanks time to try it. Thank you.

**Comment by Max-Enrik** [comment]
I added `ytdl-raw-options=proxy=[http://127.0.0.1:3128]
ytdl-raw-options-append=proxy=http://127.0.0.1:3128` didn't worked. (Of course, I've changed the proxies.)

**Comment by garoto** [comment]
There are two different network requests that happens when fetching e.g. `youtube.com` content: the `ytdl_hook.lua` script one which uses `youtube-dl` to resolve plain, browser looking URLs into a streamable, mime-type aware content URL that ffmpeg can understand, and then there's `ffmpeg's` native network downloader (http, hls, etc) which takes over from this point on and makes all the subsequent network requests.

**Comment by Max-Enrik** [comment]
Thanks for the explanation. Looks like I have to knowledge to implement `ytdl_hook.lua`. By the way I tried `HTTP` but didn't worked. I used free proxy servers. Maybe this is reason mpv didn't played youtube url?
