### ISSUE TITLE
Arm64 Bluetooth player always stuck in the first frame

### ISSUE THREAD

**Issue by gladiatorplus** [mpv-player/mpv#8160]
### Important Information

- mpv 0.32 / mpv0.29
- arm 64
- wayland

### Reproduction steps

Connect Bluetooth, play video with MPV and observe the phenomenon

### Log file
[log.log](https://github.com/mpv-player/mpv/files/5360466/log.log)
![截图录屏_选择区域_20201011091645](https://user-images.githubusercontent.com/62606831/95668218-737bcc80-0ba3-11eb-9a46-d6a66abc92f9.png)

**Comment by CounterPillow** [comment]
"Connect bluetooth"? Connect bluetooth what? Bluetooth audio? If it's bluetooth audio, then please retry with a build of the latest git version, there has been a rewrite of the audio system since 0.32, and bugs in the AO code (that may no longer exist now) can exhibit themselves as playback not progressing.

**Comment by gladiatorplus** [comment]
sorry,"Connect bluetooth" ，this means using a Bluetooth headset as audio output.

**Comment by Akemi** [comment]
please try with the latest version. if the problem still persists please open a new issue with all the infos we ask for.
