### ISSUE TITLE
[BUG] input-conf option set too late with auto profiles

### ISSUE THREAD

**Issue by NightMachinary** [mpv-player/mpv#8186]
### Important Information

Provide following Information:
- mpv version
```
❯ mpv --version
mpv 0.32.0-750-ge1536193cb Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Sep 28 14:02:04 UTC 2020
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: 4.3.1
```
- macOS Version: 10.15
- Source of the mpv binary or bundle: https://github.com/jnozsc/mpv-nightly-build

### Reproduction steps

mpv.conf:
```
[extension.JPG]
input-conf=/Users/evar/Base/_Code/lua/mpv/image_input.conf
```

```
mpv --input-test /Users/evar/Base/_Art/photography/Garden/IMG_0046.JPG --profile=extension.JPG # works just fine
```

```
mpv --input-test /Users/evar/Base/_Art/photography/Garden/IMG_0046.JPG --log-file=mpv.log # does NOT use /Users/evar/Base/_Code/lua/mpv/image_input.conf 
```

Looking through the log file, it seems to me that the problem is that the auto profile is loaded too late and mpv has already loaded its default input config by then.

### Log file

[mpv.log.txt](https://github.com/mpv-player/mpv/files/5396053/mpv.log.txt)

**Comment by NightMachinary** [comment]
I tested this with
```
[image]
profile-cond=estimated_frame_count < 2
force-window=yes # Not necessary?
hr-seek=yes
image-display-duration=inf
input-conf=~/.config/mpv/image-input.conf
```
as well, the result is the same.

**Comment by guidocella** [comment]
You can achieve this behaviour with input sections. Even if input-conf worked at runtime, input sections are better because you can put videos and images in the same playlist and change the keybindings when the type of file changes, without creating an opposite input.conf that resets every image keybinding. (The manpage says they are deprecated, but they haven't been replaced after 11 months.)
https://github.com/occivink/mpv-image-viewer has a brief example. I can also share my (rather different) image viewing config if more examples are useful.
