### ISSUE TITLE
youtube-dl has been DMCAed and is being removed from package managers. How will this affect mpv in the future?

### ISSUE THREAD

**Issue by l1ving** [mpv-player/mpv#8201]
Seeing as youtube-dl is now gone and is already gone from the AUR, and will be gone from all other distros repos in the near future, how is this being handled? Is mpv just dropping support for playing youtube urls?

**Comment by Akemi** [comment]
who knows. maybe wait a bit longer and see what actually happens.

**Comment by sfan5** [comment]
> Seeing as youtube-dl is now gone and is already gone from the AUR

By the way: I don't know why you'd look in the AUR when a [youtube-dl package](https://www.archlinux.org/packages/community/any/youtube-dl/) literally exists.

**Comment by l1ving** [comment]
Oops. I'm blind, thank you.

**Comment by v-fox** [comment]
Wow, just discovered that from [here](https://github.com/mpv-player/mpv/issues/8204)… unbelievable.
It shouldn't be hard to migrate youtube-dl repo to a GitLab or BitBucket instance BUT youtube-dl had tens, if not hundreds, open and actively developed merge-requests, including one I was backporting into a package of my distro. That would not be easy to restore since it's not a part of git's meta-data.

mpv similarly has quite a few of hanging MRs. How hard would it be to, if not migrate from GH, at least keep a GL or BB instance that's automatically synced with all of development meta-data (MRs, issues, access rights, possibly roadmaps, etc.) ? Since mpv and vlc share their ffmpeg & libplacebo basis, it might be a good pretence to migrate from GH and legacy mailing lists, in case of vlc, to own or 3rd-party-outside-of-US alternative git-based UI development management instance. In fact, doesn't vlc [already do that](https://code.videolan.org/groups/videolan/-/merge_requests) (seen as residing in France), despite its [wiki guidelines](https://wiki.videolan.org/Sending_Patches_VLC/) and GitHub [mirror stub](https://github.com/videolan/vlc) ?

PS: stumbled on [a guy](https://twitter.com/xor/status/1319738279772770308) doing some legal analysis on the situation but the very fact that this happened should be disconcerting despite any conclusion.

**Comment by guidocella** [comment]
There is a fork at https://github.com/l1ving/youtube-dl that removed the example videos under accusation. Let's see if it sticks.

**Comment by Akemi** [comment]
@v-fox see #7924

**Comment by CounterPillow** [comment]
@guidocella they're not examples, they're test cases.
They don't care about them specifically, they don't like the project as a whole.

**Comment by l1ving** [comment]
The tests were the only legal ground they were standing on. Either way, the question has been answered and this issue has been closed.

**Comment by Hrxn** [comment]
It's technically not a real DMCA notice...
More like a claim that the whole thing (the source code) is illegal *per se*

https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md

> Anticircumvention Violation. We also note that the provision or trafficking of the source code violates 17 USC §§1201(a)(2) and 1201(b)(1). The source code is a technology primarily designed or produced for the purpose of, and marketed for, circumventing a technological measure that effectively controls access to copyrighted sound recordings on YouTube, including copyrighted sound recordings owned by our members. For further context, please see the attached court decision from the Hamburg Regional Court that describes the technological measure at issue (known as YouTube’s “rolling cipher”), and the court’s determination that the technology employed by YouTube is an effective technical measure within the meaning of EU
[..]
and German law, which is materially identical to Title 17 U.S.C. §1201 of the United States Code. The court further determined that the service at issue in that case unlawfully circumvented YouTube’s rolling cipher technical protection measure.2 The youtube-dl source code functions in a manner essentially identical to the service at issue in the Hamburg Regional Court decision

Ah, yes. The Hamburg Regional Court, because of course it is. 🤣

**Comment by lextra2** [comment]
> 
> 
> It's technically not a real DMCA notice...
> More like a claim that the whole thing (the source code) is illegal _per se_
> 
> https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md
> 
> > Anticircumvention Violation. We also note that the provision or trafficking of the source code violates 17 USC §§1201(a)(2) and 1201(b)(1). The source code is a technology primarily designed or produced for the purpose of, and marketed for, circumventing a technological measure that effectively controls access to copyrighted sound recordings on YouTube, including copyrighted sound recordings owned by our members. For further context, please see the attached court decision from the Hamburg Regional Court that describes the technological measure at issue (known as YouTube’s “rolling cipher”), and the court’s determination that the technology employed by YouTube is an effective technical measure within the meaning of EU
> > [..]
> > and German law, which is materially identical to Title 17 U.S.C. §1201 of the United States Code. The court further determined that the service at issue in that case unlawfully circumvented YouTube’s rolling cipher technical protection measure.2 The youtube-dl source code functions in a manner essentially identical to the service at issue in the Hamburg Regional Court decision
> 
> Ah, yes. The Hamburg Regional Court, because of course it is. 🤣

Ah yes. Of course. The german law enforcement is at it again. IIRC they took 8 years to solve the issue of youtube music videos being blocked (VEVO).

[Das Internet ist Neuland...](https://youtu.be/DWqXsXR8h4E)
