### ISSUE TITLE
PGS subtitles showing and hiding unexpectedly

### ISSUE THREAD

**Issue by mseeley** [mpv-player/mpv#8202]
### Important Information

- mpv version: [0.32.0-750-ge1536193cb](https://github.com/jnozsc/mpv-nightly-build/releases/tag/0.32.0-750-ge1536193cb); latest nightly at time of writing. Also repro'ed on earlier ~0.32.0-6xx build; sorry I updated before recording the previous version number fully.
- macOS Version: 10.15.7; please note I have not validated behavior on other platforms
- Source of the mpv binary or bundle: https://github.com/jnozsc/mpv-nightly-build/releases/tag/0.32.0-750-ge1536193cb
- If known which version of mpv introduced the problem: unknown
- Possible screenshot or video of visual glitches: please see below

### Reproduction steps

- Play the sample file.
- The video has PGS subtitles which show/hide at different times at the top and bottom of the video frame.
- Notice the cadence of subtitles appearing on the top and bottom of the video frame.

### Expected behavior

I believe the top and bottom subtitles should show and hide at independent timings. I can't vouch for the PGS timing itself. As a user the VLC behavior _looks_ correct although I'm unsure from the implementation side.

### Actual behavior

Notice mpv "flash" the subs in this [example video](https://github.com/mpv-player/mpv/files/5432273/mpv-vlc-compare.mp4.zip). This is mpv 0.32.0-750-ge1536193cb and VLC 3.0.11.1 Vetinari (Intel 64bit) (Compiled by d-fu with clang 9.1.0 (clang-902.0.39.2) (Jul 27 2020 20:09:55)). Here's a preview, notice the way `Disciplining Delinquents` flashes. The flash also occurs earlier in the demo video on another set of subs too.

![Recording-1080](https://user-images.githubusercontent.com/30019/97065084-b2683580-1546-11eb-8704-25694c281bf3.gif)

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/5432292/mpv.log)

### Sample files

[Mob Psycho 100 S01 E06-1.mkv.zip](https://github.com/mpv-player/mpv/files/5432274/Mob.Psycho.100.S01.E06-1.mkv.zip) (5MB)

**Comment by gw711** [comment]
Similar issue just now watching Bluray rips made with MakeMKV. At certain specific points a subtitle appears but then disappears too quickly. In VLC this issue doesn't happen.

**Comment by Flo56958** [comment]
I can confirm this issue. If one subtitle is removed from screen all subtitles get hidden and only reappear in their timeframe if another subtitle is shown. This results in flickering of the text (due to the unnecessary on/off switching) or very few screen time for some subtitles which makes reading unpleasant and sometimes impossible.

Tested on mpv-x86_64-20220320-git-f871294 with Windows 11.

**Comment by Flo56958** [comment]
After a bit of crude testing I've found a "solution" for the flashing. (not tested on the total disappearance when no subtitle follows the falsely hidden subtitle)
Increasing the constant 1e-6 in the line https://github.com/mpv-player/mpv/blob/84821dbcb6d9e16b8f11da2135208e4f3e66fcd0/sub/sd_lavc.c#L397 to 0.2 seems to do the trick. Higher values only shift the subtitle more forward in time as expected.

I am not comfortable in sending a PR because of this, as I do not have a deeper understanding of what this constant implies and found this solution without any reason behind it, just try and error. It seems a bit arbitrary for me. A response from a moderator in this regard would be helpful!

**Comment by chafinchris97** [comment]
Hi I just want to chime in to show a workaround I found in the meantime for those with the same issue. Since the issue is that two timestamps are appearing at the same time, then you can remake the .sup file so there isn't any overlapping timestamps. Subtitle Edit for Windows seems to work the best for that. So extract the .sup file from the .mkv, on Subtitle Edit file -> import -> blu ray (.sup) subtitle file for edit -> then just file -> save as new .sup file. Now just mux that back into the original .mkv. 

Here's how it look with that sample .mkv file:
![Screen_Recording_2022-05-03_at_5_20_28_PM_AdobeCreativeCloudExpress(1)](https://user-images.githubusercontent.com/34977196/166608573-23724cec-57ed-4a0b-870a-8c16beb341a3.gif)

**Comment by Obegg** [comment]
Uh I didn't know there was already an open issue about it, it seems the same as this one: https://github.com/mpv-player/mpv/issues/10051
