### ISSUE TITLE
How to crop a video to 4:3?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#8203]
I have a natively 4:3 video presented in 16:9, the channel logo could be cropped out without losing much of the image. I've tried from [input.conf](https://github.com/mpv-player/mpv/blob/master/etc/input.conf):

```
#Alt+left  add video-pan-x  0.1
#Alt+right add video-pan-x -0.1
```
... video position isn't centered.

`#A cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"`

...doesn't crop the video to the set ratio.

**Comment by guidocella** [comment]
Have you tried zooming in with Alt + + (alt and plus)?

**Comment by 07416** [comment]
> Have you tried zooming in with Alt + + (alt and plus)?

I now see that's an option as well, but I've only attempted to crop horizontally (x). Sorry if I was unclear.

**Comment by guidocella** [comment]
Try using `set video-unscaled no` and resizing the window horizontally, zooming if necessary. You can also set the geometry option instead of manually resizing the window. You can also zoom only until black bars are filled by increasing panscan with W or e, but I don't think that's what you want to do if I understand correctly.

**Comment by Akemi** [comment]
the question has been answered.
