### ISSUE TITLE
mpv is not maintained by wm4

### ISSUE THREAD

**Issue by ewarv** [mpv-player/mpv#8254]
### Important Information

Provide following Information:
- mpv version: latest from git
- Platform and Version: N/A
- Source of the mpv binary: N/A

### Reproduction steps
Go to https://github.com/mpv-player/mpv/graphs/contributors or https://github.com/mpv-player/mpv/commits/master and search for "wm4".

### Expected behavior
The search should show results.

### Actual behavior
No matching results are found and If you take a look at the pages you notice an alarming amount of anime avatars,  mpv is still his project and he knows mpv best. Without him, mpv will die. Therefore, he should be put back on his position that belongs to him by right.

### Log file

N/A

### Sample files

N/A

**Comment by CounterPillow** [comment]
> and If you take a look at the pages you notice an alarming amount of anime avatars

![1597646030840](https://user-images.githubusercontent.com/308818/98620409-91089700-2305-11eb-8b41-d4938b4e6e02.jpg)

**Comment by Akemi** [comment]
if you hadn't noticed, wm4 disassociated his contributions even before the recent events and wasn't listed on the first graph. it's something he was and is solely responsible for and there is nothing we can do about it. otherwise try reporting it to github.

he is still in the commit log, just that his name isn't associated with his account. though that was the case even before.

i hate to break it to you, even though wm4 is the biggest contributor to the project, it doesn't belong to him. this is an insult to those who also contributed massively to this project.

locking this issue since it will only lead to nothing.
