### ISSUE TITLE
autofit 100% for height is slightly larger than screen height

### ISSUE THREAD

**Issue by jasonhan-vassar** [mpv-player/mpv#8272]
### Important Information

mpv 0.32.0
macOS Big Sur (11.0.1)
- Screen resolution: 2880 × 1800

### Reproduction steps

1. Use a video that, when scaled proportionally, will fit 100% of the screen height before fitting 100% of the screen width — I've included a 1000x1000 sample video under **Sample files** that should be a good example. Feel free to use your own video though, since it's not specific to this sample.
2. Add `autofit="100%x100%"` as the only option in your config.
3. Open the video with `mpv`.

### Expected behavior

The video should fit the screen in terms of height. Here is a screenshot below (I maximized the video manually for demonstration):

<img width="1680" alt="Screen Shot 2020-11-15 at 9 51 50 AM" src="https://user-images.githubusercontent.com/34594853/99188149-7df02f80-2728-11eb-8555-1e7d29970003.png">

### Actual behavior

Below is what actually happens upon opening the sample video. Note that the bottom is slightly cut off.

<img width="1680" alt="Screen Shot 2020-11-15 at 9 52 09 AM" src="https://user-images.githubusercontent.com/34594853/99188177-9bbd9480-2728-11eb-8773-a6d2536609f6.png">

Is this intended behavior? I would guess that maybe the bit of height that the Menu Bar occupies isn't being accounted for, so width autofitting should be fine but height will be slightly off. Please let me know if there is a better way to achieve what I am looking for than the `autofit` option!

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/5542581/mpv.log)

### Sample file

[sample.mp4.zip](https://github.com/mpv-player/mpv/files/5542609/sample.mp4.zip)

**Comment by Akemi** [comment]
> I would guess that maybe the bit of height that the Menu Bar occupies isn't being accounted for

yes, i believe that is the case. though what height should it be? there is also the possibility of the dock being shown for example. do we want to restrict the height by that too? what about when the dock is on either side?

**Comment by jasonhan-vassar** [comment]
Those are some good questions to consider. I was thinking we could default to OS behavior — I just tested it now, maximized windows will fit snugly with the dock on any side of the screen. However, this essentially sounds like the `window-maximized` option, so maybe keeping `autofit` the way it is would be better.

Speaking of which, can you confirm that `window-maximized` works on macOS? If I could use that setting, I would do so over `autofit`, but unfortunately it's not having any effect.

**Comment by Akemi** [comment]
yes, window-maximized works. though the behaviour is a bit different. it will not centre the window, eg it's the standard macOS behaviour (and function) that it will grow/shrink the window (from the current/start position which is whatever is defined otherwise in the config, geometry, autofit, etc) till it hits the right side and only then moves the window to the left. so you will get the white space on the left side usually.

it does work, though tested on 10.14. maybe big sur changed/broke something again.

for tacking the dock into acount we might need to use [visibleFrame](https://developer.apple.com/documentation/appkit/nsscreen/1388369-visibleframe), though the note on that property might be a problem.

**Comment by jasonhan-vassar** [comment]
Thanks for the help! I'll wait for Big Sur support for `window-maximized` then in the meantime.

For future reference (closing this issue after this since it is intended behavior), is there a way to use `window-maximized` in conjunction with `geometry` or something to maximize the window and have it centered?

**Comment by Akemi** [comment]
if it's really a big sur problem, you should open another issue for it, please.

no maximisation is done after the geometry stuff. so it's not possible.

you can most likely keep this open since i think changing the behaviour here is reasonable, eg using the actual usable screen rectangle instead of the whole one. i guess dock + menu bar should be considered in this case. if i am not mistaken this should only add one maybe two lines of code.

**Comment by jasonhan-vassar** [comment]
Unfortunately I don't have access to a 10.15 machine at the moment, but I could try it on a VM or something in the future? For now, I'll wait to see if others are having similar issues on Big Sur before opening anything.

I'm looking forward to the suggested `autofit` change as well then!

**Comment by Akemi** [comment]
i tried it in my 10.15 VM. just wanted to make sure that it actually works on a real system. i had a few cases that worked in the VM but not on an actual system and vice versa.

**Comment by Akemi** [comment]
should be fixed with #8394. feel free to test.
