### ISSUE TITLE
Build fails on arm64 Mac due to hardcoded architecture in waftools/detections/compiler_swift.py

### ISSUE THREAD

**Issue by zrait** [mpv-player/mpv#8281]
The Swift code for the cocoa-cb backend is compiled with a hardcoded architecture: https://github.com/mpv-player/mpv/blob/19913921eb9ee4c35de230c62c46d1591cf3326e/waftools/detections/compiler_swift.py#L20

This breaks when compiling mpv on new Apple Silicon Macs.

I was able to compile successfully by changing the target to `arm64-apple-macosx11.0`

At a minimum this script should use the current system architecture since that's what the rest of the code will be compiled under. 

Presumably this also broke cross-compilation for iOS back when it was merged (quite a long time ago), but maybe no one is doing that these days or I'm misunderstanding something. The last time I cross-compiled for iOS was 4 years ago and required setting quite a few environment variables manually.

**Comment by Akemi** [comment]
yeah, this is kinda shit and is some legacy shit from when i added cocoa-cb to restrict everything to at least macOS 10.10. i guess i should add some kind of proper platform SDK check and just remove the target altogether.

just two side notes, whether you know that already or not. since there are no iOS specific features coded in swift it's pointless to activate this anyway for cross compiling. there is still `--swift-flags` option to overwrite that flag manually.

**Comment by Akemi** [comment]
could you please give me the output of `xcodebuild -version` and `xcrun --sdk macosx --show-sdk-build-version`?

**Comment by zrait** [comment]
```
% xcodebuild -version
Xcode 12.2
Build version 12B45b
% xcrun --sdk macosx --show-sdk-build-version
20A2408
```

**Comment by Akemi** [comment]
opened a PR #8288. if you don't mind you can try it and report back. also check if the sdk version is properly detected, eg this line
```
Checking for macOS SDK                   : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk (version found: 10.15.1)
```

**Comment by zrait** [comment]
Just tried it and yes, that fixed it. Thanks for the quick turnaround.
