### ISSUE TITLE
Nonexistent swift dylib linked in executable

### ISSUE THREAD

**Issue by i0ntempest** [mpv-player/mpv#8295]
### Important Information

- mpv version: 0.32.0 and 0.33.0
- macOS Version: 10.15.7
- Source of the mpv binary or bundle: build from source

### Reproduction steps

Build mpv using `./bootstrap.py && ./waf configure && /waf`

### Expected behavior
Executable links properly
### Actual behavior
Nonexistent library `/usr/lib/swift/libswiftUniformTypeIdentifiers.dylib` got linked in mpv executable
### Log file

Not applicable

**Comment by Akemi** [comment]
what about the configure and build logs?

**Comment by i0ntempest** [comment]
Here you go
[build.log](https://github.com/mpv-player/mpv/files/5580122/build.log)
[configure.log](https://github.com/mpv-player/mpv/files/5580123/configure.log)

**Comment by i0ntempest** [comment]
This is the log generated by macports in case you're interested.
[main.log](https://github.com/mpv-player/mpv/files/5580142/main.log)

**Comment by Akemi** [comment]
maybe try to be a bit more specific next time. i assumed you had problems with building/linking. but from the main.log everything build and linked just fine. do you get the error when executing the binary?

that configure.log is horrible with all those formatting sequences in there, and makes it nearly unreadable.

next time, just say you have problems building via macports. since that main.log looks suspicious wrong. you can't have the DEVELOPER_DIR be the Applications/Xcode.app itself but the rest is coming from the CommandLineTools. the sdk path should also reference the sdk from the xcode.app.

```
:debug:configure CFLAGS='-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64'
:debug:configure CPPFLAGS='-isystem/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk'
:debug:configure CXXFLAGS='-pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64'
:debug:configure DEVELOPER_DIR='/Applications/Xcode.app/Contents/Developer'
:debug:configure LDFLAGS='-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64'
:debug:configure OBJCFLAGS='-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64'
:debug:configure OBJCXXFLAGS='-pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64'
:debug:configure SDKROOT='/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk'
```

in the same log, mpv picks up the xcode SDK and the CommandLineTools SDK. which is also the macOS 11.0 sdk. which is mismatched. that seems to be a macports problem. report it to them. since the linked SDKs and env vars that are passed to the mpv build system should match.
```
:info:configure Checking for macOS SDK                   : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk (version found: 11.0) 
...
-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk', '-arch', 'x86_64', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk', '-L/usr/lib', '-L/usr/local/lib'
```

**Comment by i0ntempest** [comment]
Thanks, this seems to be indeed caused by mismatched sdk version. Binary built with 10.15 sdk doesn't reference that library.

**Comment by i0ntempest** [comment]
Is there a way to override waf's choice of SDK path? It seems to choose whichever is the newest even though macports sets some environment vars pointing to a SDK that matches the OS version

**Comment by Akemi** [comment]
no it doesn't chose "whichever is the newest". it uses the one set in your dev environment which can be retrieved via "xcrun --sdk macosx --show-sdk-path" (https://github.com/mpv-player/mpv/blob/master/waftools/detections/compiler_swift.py#L137). this is the develop environment which you set via `xcode-select`. `xcode-select -p` will show the configured path. you can change that path via sudo `xcode-select -p /Library/Developer/CommandLineTools` for example.

you can manually overwrite this with MACOS_SDK env var (https://github.com/mpv-player/mpv/blob/master/waftools/detections/compiler_swift.py#L130-L131).
