### ISSUE TITLE
Embedded shader texture rgba16hf format ?

### ISSUE THREAD

**Issue by butterw** [mpv-player/mpv#8309]
Can you provide a simple example demonstrating how you create an embedded texture in a .hook shader ?

The manual seems clear except on the issue of how to create the hex data string. Is there a program that can transform values (or a 32 bit png image) to suitable rgba16hf hexadecimal ? ex: How is the color orange vec4(1, 0.5, 0, 1) coded in rgba16hf ?
What should the data sequence be: xxxyyyy, where x is (R16, G16, B16, A16 bit) ?

//!TEXTURE DISCO
//!SIZE 3 4
//!FORMAT rgba16hf
//!FILTER NEAREST
//!BORDER REPEAT
0000803f000003f0000803f00aa03f00000555555803f0008

"FORMAT <name> (required)
    The texture format for the samples. Supported texture formats are listed in debug logging when the gpu VO is initialized (look for Texture formats:). Usually, this follows OpenGL naming conventions. For example, rgb16 provides 3 channels with normalized 16 bit components. One oddity are float formats: for example, rgba16f has 16 bit internal precision, but the texture data is provided as 32 bit floats, and the driver converts the data on texture upload."
...
Following the metadata is a string of bytes in hexadecimal notation that define the raw texture data, corresponding to the format specified by FORMAT, on a single line with no extra whitespace.

**Comment by haasn** [comment]
The [Khronos Data Format specification](https://www.khronos.org/registry/DataFormat/specs/1.3/dataformat.1.3.html) provides the authoritative reference for questions of how to encode particular texture formats, in particular [this section on 16-bit floating point numbers](https://www.khronos.org/registry/DataFormat/specs/1.3/dataformat.1.3.html#16bitfp) seems to be what you're looking for.

Side note, it's easier and more portable to just use rgba16f instead of rgba16hf, which is supposed by modern versions of libplacebo. In that case, the encoding is simply the same as usual 32-bit floating point numbers.

**Comment by butterw** [comment]
In mpv0.32/dx11 rgba16f didn't work for me, only rgba16hf is available + a tool to do the conversion from decimal to hex would be needed.  
rgba8 seems a lot simpler to deal with (0-255 uint8: XX hexa). 

---
//!SIZE 3 2
On Windows, the data layout is as follows:
0 1 2
3 4 5
