### ISSUE TITLE
What properties name should I add in the profile?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8336]
Some of them are so easy like `height` and `width`, but some of them are so complicated like `get("estimated-vf-fps", 0)` and `get("video-format", 0)` and `get("video-params/privaries", 0)` and `get("audio-params/channel-count", 0)`, if I don't add the `get()` stuff, it doesn't work.
These properties are all listed in the manual
### Log file

I will offer one if it is needed.

**Comment by guidocella** [comment]
You can use `estimated_vf_fps` and `video_params.primaries`. But it seems that the short form doesn't replace _ with - within sub-properties (a bug?). For sub-properties with -, you can use `get("audio-params/channel-count")` . The second argument is optional.

**Comment by laichiaheng** [comment]
> You can use `estimated_vf_fps` and `video_params.primaries`. But it seems that the short form doesn't replace _ with - within sub-properties (a bug?). For sub-properties with -, you can use `get("audio-params/channel-count")` . The second argument is optional.

So you not only need to replace the - with _, but also replace the / with .?

**Comment by guidocella** [comment]
If you want to use the short form yes, because that's how you access fields in Lua tables, it's not something special to `profile-cond`. Lua also has `table['field']` as an alternative. In fact, `profile-cond=audio_params['channel-count']` works, and you can use that as a workaround of _ in subproperties currently not being replaced when using magic variables.

**Comment by laichiaheng** [comment]
Is the profile-desc needed anymore? It was needed in the old auto-proifles.

**Comment by guidocella** [comment]
profile-desc is optional.
