### ISSUE TITLE
mpv doesn't return to full screen when opening a new video

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#8337]
### Important Information

$ brew info mpv
mpv: stable 0.33.0 (bottled), HEAD
$ system_profiler SPSoftwareDataType
System Version: macOS 10.15.7 (19H2)

### Reproduction steps

1. `fs=yes` in `mpv.conf`
1. Open any video from Finder
1. (mpv starts playing the video in full screen)
1. Press `Cmd+Tab` to switch to Finder
1. Open another video from Finder (using `Cmd+Cursor Down`)

### Expected behavior

I expect to return to mpv in full screen, playing the new video.

### Actual behavior

The video starts (I can hear the audio), but I am still in Finder.

Attempting a workaround reveal further problems:

1. Hold`Cmd+Tab` in an attempt to switch to mpv manually
1. (mpv is first in the list, which is strange since I'm still in Finder, and Finder is second/highlighted)
1. (Releasing `Cmd+Tab` would make me stay in Finder, so I must instead press `Cmd+Shift+Tab` to select mpv)
1. (I finally return to mpv in full screen)

### Log file

If you can't reproduce this immediately and need a log, let me know.

**Comment by Akemi** [comment]
i am not sure what you mean with 5 "opening using `cmd+cursor down`", though that probably doesn't matter since i can reproduce it. i am also not sure if this isn't meant to work like this. for one, VLC in native fullscreen behaves exactly the same way.

is there an Apple App that behaves like you want it to? quicktime just opens a new video window. maybe even any other app that behaves like that?
this might need something to explicitly switch the space, though i believe (nearly) all APIs in that regard are private(?). maybe setting the window active again might work, though is that even what all users want? some might want to stay on the current space.
clicking on the mpv dock icon switches the space. so opening a file via finder doesn't make it an 'active' app but just focused.

if my assumptions are right, this is something Apple needs to change and/or add new window collection behaviours for (or similar).

**Comment by Akemi** [comment]
also on a side note since we had it before on the other issue. please just provide the log in the first place. it doesn't even take a minute and i don't want to ask every time for something if i can't reproduce it and it was already requested.

you want something from us, so please adhere to our requests.

**Comment by forthrin** [comment]
If the behavior is consistent across apps, and is a design decision by Apple that is hard or counterproductive to work around, it's understandable to leave this as-is. (I'll leave this to someone who knows macOS from the inside.) My concern is that the behavior is just unexpected when you Cmd+Tab out to Finder to quickly start another video. I'll enclose logs for further issues. Thanks for your very prompt attention. My impression with this project just continues to soar.

**Comment by Akemi** [comment]
oh i see, i thought it was only for jumping in or out of folders.

**Comment by Akemi** [comment]
i looked into this. we can manually refocus the window. the problem is, we can't distinguish between a dropped file/new playlist and next/previous file in a playlist. so it would refocus even if just the next file is played for example. i am not sure if this is really wanted behaviour. then there is also the question if it should only do this in fullscreen or also windowed.

it might be possible to to this only and dropping file, but at that stage we wouldn't even know if mpv actually can open this file or it might be a file without video track, so refocusing seems not useful in those cases.

i think the first behaviour is the most logical, but it has some caveats.

**Comment by forthrin** [comment]
Have to test this in real life to give an opinion. Let me know if a test becomes available some time.

**Comment by forthrin** [comment]
Bump. This is still an issue, and rather annoying. I very often Cmd+Tab out of full screen to check stuff. Obvious workaround: Go out of full screen manually before switching to other applications.

Would appreciate a fix unless it is requires dirty hacks and is counterintuitive to how macOS works.

**Comment by forthrin** [comment]
Seems to work perfectly! Thanks! Seems you're doing a huge sweep now. Keep up the good work!
