### ISSUE TITLE
Load fonts from external folder  

### ISSUE THREAD

**Issue by DeadNews** [mpv-player/mpv#8338]
### Expected behavior of the wanted feature
Option like [--sub-file-paths=<path-list>](https://mpv.io/manual/master/#options-sub-file-paths), but for fonts folders.

For example:
sub-file-paths=subs:/or/absolute/path/to/
font-file-paths=subs/fonts:/or/absolute/path/to/

ffmpeg has similar functionality:
https://ffmpeg.org/ffmpeg-filters.html#subtitles-1
```
11.201 subtitles
Draw subtitles on top of input video using the libass library. 
...
fontsdir
    Set a directory path containing fonts that can be used by the filter. These fonts will be used in addition to whatever the font provider uses.
```

**Comment by guidocella** [comment]
You can already load fonts from `~/.config/mpv/fonts`, or do you want to customize that directory?

**Comment by DeadNews** [comment]
Yes, I can load fonts from specific folders like `~/.fonts/`, but required fonts for subtitles are in the subs/fonts folder I just downloaded.

1) How will the fonts appear in specific folders if I don't copy them (or create a symlink) beforehand?
2) Why do I need these fonts in specific folders all the time, if they are needed only during viewing with specific subtitles?

I want to be able to set a directory for loading fonts like in the ffmpeg example above.

**Comment by DeadNews** [comment]
Yes, I can load fonts from specific folders like `~/.fonts/`, but required fonts for subtitles are in the subs/fonts folder.

1) How will the fonts appear in specific folders if I don't copy them (or create a symlink) beforehand?
2) Why do I need these fonts in specific folders all the time, if they are needed only during viewing with specific subtitles?

I want to be able to set a directory for loading addition fonts like in the ffmpeg example above.

**Comment by DeadNews** [comment]
Yes, I can load fonts from specific folders like `~/.fonts/`, but required fonts for subtitles are in the subs/fonts folder I just downloaded.

1) How will the fonts appear in specific folders if I don't copy them (or create a symlink) beforehand?
2) Why do I need these fonts in specific folders all the time, if they are needed only during viewing with specific subtitles?

I want to be able to set a directory for loading addition fonts like in the ffmpeg example above.

**Comment by DeadNews** [comment]
Yes, I can load fonts from specific folders like ~/.fonts/, but required fonts for subtitles are in the subs/fonts folder I just downloaded.

1) How will the fonts appear in specific folders if I don't copy them (or create a symlink) beforehand?
2) Why do I need these fonts in specific folders all the time, if they are needed only during viewing with specific subtitles?

I want to be able to set a directory for loading additional fonts like in the ffmpeg example above.

**Comment by snylonue** [comment]
https://github.com/yzwduck/FontLoaderSub
this may be of some help

**Comment by hooke007** [comment]
recently the [update](https://github.com/clsid2/mpc-hc/releases/tag/1.9.14) of mpc remind me of this feature , unfortunately it hasn't been implemented in mpv.

**Comment by GribanovIvan** [comment]
Be really good just load fonts from SUBDIR/fonts with ignoring capitalization letters for "fonts" dir

**Comment by fbriere** [comment]
To anyone interested, I have submitted PR #9856, which adds a `--sub-fonts-dir` option (along with its corresponding `--osd-fonts-dir`).

For the record, [libass](https://github.com/libass/libass) (which is in charge of loading the fonts) only supports [a single directory](https://github.com/libass/libass/blob/master/libass/ass_library.h#L31)¹, thus precluding a plural "paths" option.

Furthermore, since there's already a default location (`~~/fonts`), automatically selecting another one based on the presence or absence of a directory (as suggested by @GribanovIvan) would unfortunately be likely to break something.  (That's too bad; I really liked the idea.)  Thus, you will have to set the value yourself for each directory with `use-filedir-conf` or some other way².

¹ Despite [what the documentation might seem to imply](https://github.com/libass/libass/blob/master/libass/ass.h#L258-L259), this directory is not searched recursively, so we can't trick our way around this limitation.
² Not to toot my own horn, but my [tree-profiles](https://github.com/fbriere/mpv-scripts/blob/master/doc/tree-profiles.md) script can be rather useful in this situation.
