### ISSUE TITLE
Prominent single-frame glitch when exiting full screen

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#8371]
### Important Information

```
$ brew info mpv
mpv: stable 0.33.0 (bottled), HEAD
$ system_profiler SPSoftwareDataType
System Version: macOS 10.15.7 (19H2) -- Also happens in 11.0.1
```

### Reproduction steps

1. Open a video
2. Enter full screen
3. Exit full screen

### Expected behavior

No glitch

### Actual behavior

A single frame contains a full-width gray (#E9E9E9) area, about 90 pixels high, at the top of the window.

### Log file

[foo.txt](https://github.com/mpv-player/mpv/files/5649203/foo.txt)

### Sample files

[bar.mov.gz](https://github.com/mpv-player/mpv/files/5649208/bar.mov.gz)

**Comment by Akemi** [comment]
cann you remove/comment this line https://github.com/mpv-player/mpv/blob/master/video/out/mac/window.swift#L175 and try again?

**Comment by forthrin** [comment]
```
diff --git a/video/out/mac/window.swift b/video/out/mac/window.swift
index d692d0d..c45ab3f 100644
--- a/video/out/mac/window.swift
+++ b/video/out/mac/window.swift
@@ -175 +175 @@ class Window: NSWindow, NSWindowDelegate {
-        styleMask.remove(.fullScreen)
+        //styleMask.remove(.fullScreen)
```

```
$ ./build/mpv --version
mpv b8156a9-dirty built on Mon Dec  7 08:53:38 CET 2020
```

Still the same glitch, plus when going into full screen, the last but two zoom factors seem to be swapped.

Let me know if you need more information or testing.

**Comment by Akemi** [comment]
the new glitch can't be related to that change since that change is only applied to exit fullscreen.

the animation is completely calculated by the OS or more specific by Apples animation functions. if something is swapped, there is nothing we can do about.

try with a video file smaller then your display resolution for now.

**Comment by forthrin** [comment]
> "Try with a video file smaller then your display resolution for now."

1. Should I read this as: "Bug acknowledged. Will be fixed sometime in the future."?
1. The initial glitch (gray area) happens with any screen and any video size as far as I can tell.

There is no "exit full screen" glitch when the video is paused. Also, the animation is much smoother then. So could be performance-related or race condition. My CPU is 1,8 GHz Dual-Core i5. Tests were done without GPU acceleration.

PS! Will report separate issues as... separate issues... in the future to avoid confusion.

**Comment by Akemi** [comment]
i acknowledge the bug. though i can't reproduce it and i am not sure where it is yet. i am planning to make a branch with a few debugging outputs and would like you to test it and provide me the output from the console, if you don't mind. probably at the weekend.

thanks for the info that it works with any dimension.

that the animation is smoother when paused is expected. it's because how the rendering loop and the blocking synchronisation between rendering and the resizing/re-rendering of the window works. this is limited by the refresh rate of the video itself, eg if your video is ~24fps the resizing steps (animation) will only be at that refresh rate in the worst case. because, even though the animations wants to push at 60hz our rendering loop waits for the next new frame at ~24fps. which is a huge discrepancy. if you use `--video-sync=display-resample` to resample the video to the display refreshrate the animation will be much smoother, or a higher refresh rate video. otherwise it could also be a rendering bottleneck, but the former reason is much more likely.

> Tests were done without GPU acceleration

what do you mean. if you don't forcefully use a software renderer, rendering is always GPU accelerated. do you mean hwdec, eg GPU accelerated decoding?

**Comment by Akemi** [comment]
in the end i could reproduce the bug. i tested with a video that had exactly the aspect ratio of my monitor and there the bug is there but nearly not visible or not at all. videos with a vastly different aspect ratio than the monitor makes this a lot easier to recognise.

if you can test #8391 that would be nice. if it doesn't fix the bug for you the normal terminal output of a glitching run would be nice (i added some debug output there).

**Comment by forthrin** [comment]
I was not able to produce the glitch with the suggested change! So seems like you may have nailed it.

PS! When testing on a video larger than the screen, there was a minor stall in video playback before the full screen animation started. Also, the subtitles jumped a bit too. Separate issues?

**Comment by Akemi** [comment]
you have to be more specific. what exactly happens when exactly? from windowed to fs, or from fs to windowed? subtitles don't jump, because it is entirely in the hands of the backend. only the window can jump or the rendered result could be cut off.

**Comment by Akemi** [comment]
please report the other problem in a new issue.
