### ISSUE TITLE
How to show half of frame number on osd

### ISSUE THREAD

**Issue by tkkcc** [mpv-player/mpv#8402]
Hi，
For better developing procedure, I use the following script to show half of current frame number. 

```lua
require("mp")
-- mp.observe_property("estimated-frame-number", nil, function(name)
mp.observe_property("time-pos", nil, function()
  local num = mp.get_property("estimated-frame-number")
  local count = mp.get_property("estimated-frame-count")
  if num == nil then return end
  mp.commandv("show-text", "half frame: " .. math.floor(num / 2) .. ' / ' ..
                math.floor(count / 2), -1, 3)
end)
```

However, I believe listening on time-pos is too much, and such implementation can not be found in user scripts listed in wiki. Is there any better way to achieve this?

**Comment by avih** [comment]
> I believe listening on time-pos is too much

Too much for what? if you want to display this thing for every frame, then observing time-pos is what it needs. But if you only want to show it after some specific trigger, then the procedure which displays it should just read the value of time-pos instead of observing it.

And if you want to display it periodically but not every frame, then use a timer.

**Comment by Argon-** [comment]
`tick` would be the frame-perfect option, wouldn’t it?
Either way, this hogs a lot of resources for the gained functionality.

**Comment by avih** [comment]
> `tick` would be the frame-perfect option, wouldn’t it?

tick is deprecated, and typically triggers at the same frequency as time-pos, but it also trigger on idle and pause, which time-pos doesn't.

> Either way, this hogs a lot of resources for the gained functionality.

Based on what? did you measure the CPU power consumption with and without tick/time-pos callbacks? and how do you know what the gained functionality is?

If the value is needed every frame, then it's not too much. Completely depends on the need in order to assess the value.

**Comment by tkkcc** [comment]
recently it's causing frame drop greatly. i switch to only update osd message on "pause" change.

```lua
require("mp")

mp.observe_property("pause", nil, function()
  local num = mp.get_property("estimated-frame-number")
  local count = mp.get_property("estimated-frame-count")
  num = tonumber(num) or 0
  count = tonumber(count) or 0
  mp.osd_message("1/2 frame: " .. math.floor(num / 2) .. ' / ' ..
                   math.floor(count / 2) .. "\n2/5 frame: " .. math.floor(num / 2.5) .. ' / ' ..
                   math.floor(count / 2.5).. "\n1/4 frame: " .. math.floor(num / 4) .. ' / ' ..
                   math.floor(count / 4), 9999)
end)
```
