### ISSUE TITLE
libmpv: how to know the coordinates of the OSC box?

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#8426]
Is there a way to get the OSC box coordinates?

My design requires to know the OSC coordinates to handle things like window dragging. My current implementation assumes the OSC sits at the bottom with a height of 10%. This means customizations like osc-layout=slimbox are currently not working in my frontend.

I quickly looked in osc.lua without understanding much, what I found is the function:

mp.set_mouse_area

I've labeled it as low priority on my tracker, would be nice but not very important:

https://github.com/stax76/mpv.net/issues/195

**Comment by avih** [comment]
If you mean the actual OSC box (and maybe the area which it registers mouse move at) then it's not something which the OSC exports, and it's also not something which libmpv is aware of (well, except the mouse area, but I don't think it's exposed in any way).

If you need values which only the OSC knows, you'll have to patch it and export these values, e.g. maybe at script-opts, or maybe as an API (script-message query) which the OSC responds to with whatever values you need.

If it's not too intrusive, then it might be accepted upstream so that you don't have to keep it patched.

**Comment by stax76** [comment]
Thanks for the help.
