### ISSUE TITLE
How to turn off the UI size scaling (question)

### ISSUE THREAD

**Issue by fasilav** [mpv-player/mpv#8444]
### Important Information

Provide following Information:
- mpv version: 0.33.0-56-g3e175dff4a
- Windows Version: Windows 10 20H2
- Source of the mpv binary: https://mpv.io/

### Reproduction steps

- `--no-config` doesn't help.
- Clean install in a fresh VM doesn't help.

### Expected behavior

I would like to know if it is possible to turn off the scaling of the graphical user interface when resizing a video. This question has been asked before [here](https://www.reddit.com/r/mpv/comments/ach8nu/prevent_scaling_of_the_ui/), but he didn't receive a very good answer..

- This is probably normal behavior, but I need to know how to turn this off, if it is possible.

### Actual behavior

![Rec 01-07-21-00-00-01-200](https://user-images.githubusercontent.com/75840486/103900136-be9c7180-50f7-11eb-8a71-891ac8e776c9.jpg)

![Rec 01-07-21-00-00-10-200](https://user-images.githubusercontent.com/75840486/103900137-bfcd9e80-50f7-11eb-8dc0-6500f692fe5c.jpg)

### Log file

- Probably not needed.

### Sample files

- Probably not needed.

**Comment by avih** [comment]
Maybe this https://mpv.io/manual/master/#on-screen-controller-vidscale but you should consider that there's a limit to how much can be done when there's such a narrow space to render it.

**Comment by thebombzen** [comment]
This issue here with `--script-opts=osc-vidscale=no` seems to be that it ignores the option if the video is small enough, and the threshold for "small enough" is in the wrong place. If you take a 1080p video and render it at 720p with this option, it will behave properly (i.e. the same size for each one). But rendering it at 480p is will not work, even though there is ample room to render it the same size as 720p.

**Comment by fasilav** [comment]
> Maybe this https://mpv.io/manual/master/#on-screen-controller-vidscale but you should consider that there's a limit to how much can be done when there's such a narrow space to render it.

If you are thinking of `vidscale=no`, it doesn't help. Still resizing the UI.

**Comment by Kekerykek** [comment]
I've been wondering if this was possible as well.  None of the available options in the manual seems to help regarding this.

**Comment by avih** [comment]
As I mentioned earlier, there's a limit to how big the font can be in such a narrow area. Maybe if you posted a screenshot (mockup) of how it should look instead, then it would be easier to understand what you mean.

**Comment by AjvarXX** [comment]
There should be option to set (or built-in) minimum size/height of a bar (both upper and lower).
Here I asked about the upper one #8294

**Comment by avih** [comment]
I'm closing this issue because I don't think it can be done with the current layouts. The issue is that the available width determines the font size. For instance, if you have only 50 pixels wide, then however you look at it you just cannot fit big fonts into it while keeping the same amount of data visible.

The only element which can change its size (width) is the seek area, and it already gets smaller in narrow space - up to a limit, because it still needs to contain the position when hovering it with the mouse. After that limit is reached, there's no other choice but make the font smaller. Maybe it could be made very slighty narrower still before starting to shrink the font, but it won't be meaningful in this case anyway.

If I misunderstood and someone can show an image (mockup) of how it should look, then we can reopen this issue.

Alternatively, you might open an issue to add a new layout which is specifically designed/organized so that it can fit in very narrow space while keeping the font big, e.g. maybe use three rows instead of two, and/or maybe remove some of the elements, etc. We can't promise someone will implement it, but PRs are welcome.

**Comment by avih** [comment]
Also, for vertical video, you can also switch to fullscreen, which will make the OSC span to the screen width (outside the video content boundaries) - which would be able to keep the font bigger.

Or, to the same effect, you can set `keepaspect-window=no` in your `mpv.conf` which will allow you to resize the window and make it wider by adding back bars as needed - so the OSC and its font can also be bigger - https://mpv.io/manual/master/#options-keepaspect-window

**Comment by HubKing** [comment]
So... there is no way to keep the UI size constant when the video size changes (granted that it would need a minimum window size limit) like most other video players? 

MPV is smoother than VLC, whose UI flickers when resizing the video, and that looks blurry because it does not support Wayland, but the UI is just... how should I say, too unrealistic to be actually used. It's almost like just a proof-of-concept. Of course, you would say "Use other front-ends." but the problem is that none of them are good.  SMPlayer looks blurry (QT 5.14, no Wayland) and the UI is clunky like early 2000's, and Celluloid is buggy. It is a shame that the UI sucks because its playback ability is great.

**Comment by Baerbeisser** [comment]
I'm trying to tackle this with conditional profiles. It should wok somewhat, but i seem to be doing something wrong in my conditions.

```
#[medium]
## displaying medium res in medium res # but makes low res big, why??
#profile-desc=cond:(get('width', 0) > 900 and get('width', 0) < 1920) or (get('height', 0) > 780 and get('height', 0) < 1080)
#autofit-larger=1920x1080
#geometry=1920x1080
#
[small]
# don't make low-res videos big # but makes high res small, why??
#profile-desc=cond:get('width', 0) < 720 or get('height', 0) < 480
#autofit-larger=720x480
#geometry=720x480
#osd-font-size=100
```

Anyone an idea how to fix?

**Comment by relikd** [comment]
Not the original question, but I was searching for an anwer why my mpv window is so tiny on launch (without any media). It launches with 1/3 the screen height, which is very very small on a 13" screen. I just used my 5 year old config on a new computer and the change suddenly appeared.

For whoever needs it, this will also upscale very small cover artwork:
```
autofit-smaller=720x720
```

**Comment by sjehuda** [comment]
The problem is even worse with the software "nouveau", as the interface is blurred.

```
resentation
Note: you can probably enable DRI3 in your Xorg config
[vo/gpu-next/libplacebo] Found no suitable device, giving up.
[vo/gpu-next/libplacebo] Failed initializing vulkan device                                                            
libEGL warning: DRI3 error: Could not get DRI3 device                                                                 
libEGL warning: Ensure your X server supports DRI3 to get accelerated rendering
[vo/gpu-next/opengl] Suspected software renderer or indirect context.                                                                                                              
[vo/gpu-next/opengl] Suspected software renderer or indirect                                                          context.                                                                                                              
[vo/gpu-next/drm] VT_GETMODE failed: Inappropriate ioctl for                                                          device                                                                                                                
[vo/gpu-next/drm] Failed to set up VT switcher. Terminal swit                                                         ching will be unavailable.                                                                                            
[vo/gpu-next/drm] Could not find any preferred mode. Picking                                                          the first mode.                                                                                                       
[vo/gpu-next/drm] Failed to create DRM atomic context, no DRM                                                          Atomic support                                                                                                       
MESA: info: vulkan: No DRI3 support detected - required for p                                                         resentation
Note: you can probably enable DRI3 in your Xorg config
[vo/gpu/libplacebo] Found no suitable device, giving up.
[vo/gpu/libplacebo] Failed initializing vulkan device                                                                 
libEGL warning: DRI3 error: Could not get DRI3 device                                                                 
libEGL warning: Ensure your X server supports DRI3 to get accelerated rendering
[vo/gpu/opengl] Suspected software renderer or indirect context.                                                          
[vo/gpu/opengl] Suspected software renderer or indirect context.                                                          
[vo/gpu/drm] Can't handle VT release - signal already used   
[vo/gpu/drm] Failed to set up VT switcher. Terminal switching will be unavailable.                                        
[vo/gpu/drm] Could not find any preferred mode. Picking the first mode.                                                   
[vo/gpu/drm] Failed to create DRM atomic context, no DRM Atomic support                                                   
Failed to open VDPAU backend libvdpau_nouveau.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[vo/xv] Could not grab port 62.                              
[vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.                                                           
```
