### ISSUE TITLE
Build failure on Apple Silicon

### ISSUE THREAD

**Issue by fxcoudert** [mpv-player/mpv#8445]
### Important Information

- mpv version: 0.33.0
- macOS Version: 11.1
- Source of the mpv binary or bundle: build from github source tarball

### Reproduction steps

```
==> /opt/homebrew/opt/python@3.9/bin/python3 bootstrap.py
==> /opt/homebrew/opt/python@3.9/bin/python3 waf configure --prefix=/opt/homebrew/Cellar/mpv/0.33.0_2 --enable-html-build --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-uchardet --confdir=/opt/homebrew/etc/mpv --datadir=/opt/homebrew/Cellar/mpv/0.33.0_2/share/mpv --mandir=/opt/homebrew/Cellar/mpv/0.33.0_2/share/man --docdir=/opt/homebrew/Cellar/mpv/0.33.0_2/share/doc/mpv --zshdir=/opt/homebrew/Cellar/mpv/0.33.0_2/share/zsh/site-functions --lua=51deb
```

### Actual behavior

```
  File "/private/tmp/mpv-20210107-19120-10dxp5l/mpv-0.33.0/waftools/detections/compiler_swift.py", line 201, in configure
    __find_macos_sdk(ctx)
  File "/private/tmp/mpv-20210107-19120-10dxp5l/mpv-0.33.0/waftools/detections/compiler_swift.py", line 158, in __find_macos_sdk
    minor = string.ascii_lowercase.index(version_parts.group(2).lower())
ValueError: substring not found
```

https://github.com/Homebrew/homebrew-core/pull/68460

### Log file

Full logs are available here: https://github.com/Homebrew/homebrew-core/pull/68460/checks?check_run_id=1662425196

**Comment by fxcoudert** [comment]
As asked over there (https://github.com/mpv-player/mpv/issues/8083):
`xcrun --sdk macosx --show-sdk-build-version` returns `20C63`

**Comment by Akemi** [comment]
is it possible that the line https://github.com/mpv-player/mpv/blob/master/waftools/detections/compiler_swift.py#L141 actually fails in some way on the homebrew CI? is it possible to add a `print(sdk_build_version)` after that line and actually see what is stored in `sdk_build_version`?

**Comment by Akemi** [comment]
i made a branch https://github.com/Akemi/mpv/commits/swift_build with a debug output, if that is any help with build on the CI.

**Comment by fxcoudert** [comment]
@Akemi I swear I'm becoming crazy. It logged onto an ARM CI node, it failed like it first did on our CI, then I added print statements to that python script, and it passed. I thought it might be a weird one, rebuilt from original source, and now it's passing several times in a row. What the f is that?

Before I turn crazy, I'm re-running it on CI at https://github.com/Homebrew/homebrew-core/pull/68460

**Comment by fxcoudert** [comment]
And this time it passed on CI 😨  https://github.com/Homebrew/homebrew-core/pull/68460/checks?check_run_id=1663871057

I have absolutely no idea why that is not reproducible. This is scary :(

**Comment by Akemi** [comment]
weird shit. apparently at least one other person on irc had the same problem on 10.13 and a rebuild worked for him too.

**Comment by fxcoudert** [comment]
Closing for now, I hope it never shows up agin

**Comment by gch1p** [comment]
I just had the same error on my machine, and running `./waf configure` again time helps :) Lol.

**Comment by FiloSottile** [comment]
Well, this is weird. `brew reinstall mpv` fails, then `brew reinstall mpv` works.

```
$ brew reinstall mpv
[...]
==> Installing mpv --HEAD
==> /opt/homebrew/opt/python@3.9/bin/python3 bootstrap.py
==> /opt/homebrew/opt/python@3.9/bin/python3 waf configure --prefix=/opt/homebrew/Cellar/mpv/HEAD-5824d9f_3 --enable-html-build --enable-javascript --enable-libmpv-shared --enable-lua --enable
[...]
  File "/private/tmp/mpv-20210319-20138-1vfh2jo/waftools/detections/compiler_swift.py", line 201, in configure
    __find_macos_sdk(ctx)
  File "/private/tmp/mpv-20210319-20138-1vfh2jo/waftools/detections/compiler_swift.py", line 158, in __find_macos_sdk
    minor = string.ascii_lowercase.index(version_parts.group(2).lower())
ValueError: substring not found
[...]
$ brew reinstall mpv
[...]
🍺  /opt/homebrew/Cellar/mpv/HEAD-5824d9f_3: 31 files, 10.8MB, built in 31 seconds
```

Does macOS 11 do something weird with repeated calls to query the version, as part of some magic compatibility story?

<details><pre>
$ brew reinstall mpv
Warning: Treating mpv as a formula. For the cask, use homebrew/cask/mpv
==> Downloading https://homebrew.bintray.com/bottles/dav1d-0.8.2.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/filippo/Library/Caches/Homebrew/downloads/c586a9cf1d7c6845abb2b4569c3e9f440aef0fa5c05d1a22d695c3fec3f52b3c--dav1d-0.8.2.arm64_big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.3_3.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/filippo/Library/Caches/Homebrew/downloads/0a5e94a56fd64d42de58b2ef6a04d45797dfc05f4808e2718e1a47f4bdadbcf8--libffi-3.3_3.arm64_big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.19.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/filippo/Library/Caches/Homebrew/downloads/384bd7d1d59f14c07f0ec96a7a4e6fb9d2cd491ae129c77677aeb970815d224e--gdbm-1.19.arm64_big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.34.1.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/filippo/Library/Caches/Homebrew/downloads/ed16515ab60dae6289291e0a8d857a5eb8c44877fd6952f38449642afced9408--sqlite-3.34.1.arm64_big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.2_2.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/8175f77ac2ca3caaa2386abaea299994d95a09d50a54ae8e041151b1e9fd0ebb?response-content-disposition=attachment%3Bfilename%3D%22python%403.9
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-2.8.0.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/d48cb4c08e239ac3ed692a1b250ee72ea453333636a5e6e27e2e3e491bd05eb0?response-content-disposition=attachment%3Bfilename%3D%22harfbuzz-2.8
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/rubberband-1.9.1.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/b5c746daacac9890ebec61ba76db168a7a43a9ea68855ef0c11e705a94458050?response-content-disposition=attachment%3Bfilename%3D%22rubberband-1
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/x265-3.5.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/a9fbfb88baa295ff5a3d2d91e474a47a8c129f7b7ec6730e7e6259b64cdd96fa?response-content-disposition=attachment%3Bfilename%3D%22x265-3.5.arm
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-4.3.2_1.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/a4f02dfa8a56817cd7be885061073f188118c41a815657bee084b40ec5007191?response-content-disposition=attachment%3Bfilename%3D%22ffmpeg-4.3.2
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/zstd-1.4.9.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/beddf3a858da5063f7a407e5c78c0c83a2efd2595354acb750118da7d87f0974?response-content-disposition=attachment%3Bfilename%3D%22zstd-1.4.9.a
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/youtube-dl-2021.3.14.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/3cbeeba083449acf0dc719a60a4b267c952d1977aa6372abee378a9d39108a71?response-content-disposition=attachment%3Bfilename%3D%22youtube-dl-2
######################################################################## 100.0%
==> Cloning https://github.com/mpv-player/mpv.git
Cloning into '/Users/filippo/Library/Caches/Homebrew/mpv--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Reinstalling mpv
==> Installing dependencies for mpv: dav1d, libffi, gdbm, sqlite, python@3.9, harfbuzz, rubberband, x265, ffmpeg, zstd and youtube-dl
==> Installing mpv dependency: dav1d
==> Pouring dav1d-0.8.2.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/dav1d/0.8.2: 15 files, 990.5KB
==> Installing mpv dependency: libffi
==> Pouring libffi-3.3_3.arm64_big_sur.bottle.tar.gz
==> Caveats
libffi is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"

For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"

==> Summary
🍺  /opt/homebrew/Cellar/libffi/3.3_3: 17 files, 617.4KB
==> Installing mpv dependency: gdbm
==> Pouring gdbm-1.19.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/gdbm/1.19: 24 files, 880KB
==> Installing mpv dependency: sqlite
==> Pouring sqlite-3.34.1.arm64_big_sur.bottle.tar.gz
==> Caveats
sqlite is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have sqlite first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/sqlite/bin:$PATH"' >> ~/.zshrc

For compilers to find sqlite you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/sqlite/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/sqlite/include"

For pkg-config to find sqlite you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/sqlite/lib/pkgconfig"

==> Summary
🍺  /opt/homebrew/Cellar/sqlite/3.34.1: 11 files, 4.2MB
==> Installing mpv dependency: python@3.9
==> Pouring python@3.9-3.9.2_2.arm64_big_sur.bottle.tar.gz
==> /opt/homebrew/Cellar/python@3.9/3.9.2_2/bin/python3 -m ensurepip
==> /opt/homebrew/Cellar/python@3.9/3.9.2_2/bin/pip3 install -v --global-option=--no-user-cfg --install-option=--force --install-option=--single-version-externally-managed --install-option=--r
==> /opt/homebrew/Cellar/python@3.9/3.9.2_2/bin/pip3 wheel --wheel-dir=/opt/homebrew/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/_bundled /opt/ho
==> Caveats
Python has been installed as
  /opt/homebrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /opt/homebrew/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /opt/homebrew/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /opt/homebrew/Cellar/python@3.9/3.9.2_2: 3,938 files, 66.6MB
==> Installing mpv dependency: harfbuzz
==> Pouring harfbuzz-2.8.0.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/harfbuzz/2.8.0: 68 files, 6.4MB
==> Installing mpv dependency: rubberband
==> Pouring rubberband-1.9.1.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/rubberband/1.9.1: 12 files, 973.3KB
==> Installing mpv dependency: x265
==> Pouring x265-3.5.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/x265/3.5: 11 files, 6.6MB
==> Installing mpv dependency: ffmpeg
==> Pouring ffmpeg-4.3.2_1.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/ffmpeg/4.3.2_1: 274 files, 47.6MB
==> Installing mpv dependency: zstd
==> Pouring zstd-1.4.9.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/zstd/1.4.9: 26 files, 3.1MB
==> Installing mpv dependency: youtube-dl
==> Pouring youtube-dl-2021.3.14.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/youtube-dl/2021.3.14: 1,391 files, 13.4MB
==> Installing mpv --HEAD
==> /opt/homebrew/opt/python@3.9/bin/python3 bootstrap.py
==> /opt/homebrew/opt/python@3.9/bin/python3 waf configure --prefix=/opt/homebrew/Cellar/mpv/HEAD-5824d9f_3 --enable-html-build --enable-javascript --enable-libmpv-shared --enable-lua --enable
Last 15 lines from /Users/filippo/Library/Logs/Homebrew/mpv/02.python3:
  File "/private/tmp/mpv-20210319-20138-1vfh2jo/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/private/tmp/mpv-20210319-20138-1vfh2jo/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/private/tmp/mpv-20210319-20138-1vfh2jo/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/private/tmp/mpv-20210319-20138-1vfh2jo/wscript", line 947, in configure
    ctx.load('detections.compiler_swift')
  File "/private/tmp/mpv-20210319-20138-1vfh2jo/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Configure.py", line 156, in load
    func(self)
  File "/private/tmp/mpv-20210319-20138-1vfh2jo/waftools/detections/compiler_swift.py", line 201, in configure
    __find_macos_sdk(ctx)
  File "/private/tmp/mpv-20210319-20138-1vfh2jo/waftools/detections/compiler_swift.py", line 158, in __find_macos_sdk
    minor = string.ascii_lowercase.index(version_parts.group(2).lower())
ValueError: substring not found

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
$ brew reinstall mpv
Warning: Treating mpv as a formula. For the cask, use homebrew/cask/mpv
==> Cloning https://github.com/mpv-player/mpv.git
Updating /Users/filippo/Library/Caches/Homebrew/mpv--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 5824d9f stats.lua: include a filter's @label when displaying filters on page 1
==> Reinstalling mpv
==> /opt/homebrew/opt/python@3.9/bin/python3 bootstrap.py
==> /opt/homebrew/opt/python@3.9/bin/python3 waf configure --prefix=/opt/homebrew/Cellar/mpv/HEAD-5824d9f_3 --enable-html-build --enable-javascript --enable-libmpv-shared --enable-lua --enable
==> /opt/homebrew/opt/python@3.9/bin/python3 waf install
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/mpv/HEAD-5824d9f_3: 31 files, 10.8MB, built in 31 seconds
</pre></details>
