### ISSUE TITLE
Linked MKVs don't work

### ISSUE THREAD

**Issue by phly95** [mpv-player/mpv#8460]
When using videos that have linked MKVs, the parts that are not in the file are cut out. For example, a lot of Anime will store the OPs (Theme songs) in a separate file, so while VLC plays the theme song just fine, it doesn't work with MPV.

**Comment by Akemi** [comment]
has been requested before and has been rejected. linked mkvs are a rarely used feature and all fansubbers (besides one) didn't use it after the first few times or never used it. order chapters are supported and should be used instead.

if you really want this feature, please make a proper feature request. preferable with example files. though i doubt anyone is interested in implementing it, since it's such a niche feature.

https://github.com/mpv-player/mpv/issues/3073
https://github.com/mpv-player/mpv/issues/1554

**Comment by phly95** [comment]
Cardcaptor Sakura [BD 1080p Hi10P 5.1 AAC][kuchikirukia]
[Coalgirls]_To_Aru_Majutsu_no_Index
[FFF] Love Live!
Serial Experiments Lain (NPC)
[Elysium]Seitokai.Yakuindomo(BD.1080p.FLAC)

These are all different Animes (and different groups) that have this feature. I'd hardly call it a "rarely used feature" when so many anime fansubs actually use this feature. Maybe new releases don't use the feature as much, but that doesn't solve the problem for older releases.
