### ISSUE TITLE
Some valid modplug files are not played

### ISSUE THREAD

**Issue by foxpy** [mpv-player/mpv#8474]
I have a file which is played nicely with ffplay, but mpv does not recognize it as a playable file.
I am running ArchLinux, using latest mpv-git from AUR: https://aur.archlinux.org/packages/mpv-git/

```
$ mpv --version
mpv 0.33.0-61-gdae9ea3fa7 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat Jan 16 12:43:13 MSK 2021
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.1
$ uname -a
Linux thinkpad 5.4.89-1-lts #1 SMP Wed, 13 Jan 2021 05:48:12 +0000 x86_64 GNU/Linux
```

### Reproduction steps

My issue is reproducible with `--no-config` option.
A file is attached to issue. Simply run:
```
$ mpv --no-config hard_day.mod
Failed to recognize file format.

Exiting... (Errors when loading file)
```

### Expected behavior

mpv plays file as it is supported by libmodplug.

### Actual behavior

mpv refuses to play this file, it does not even recognize it as a playable file.

### Log file

https://share.rfnull.com/mpv-issue-1/log.txt

### Sample files

https://share.rfnull.com/mpv-issue-1/hard_day.mod

### How ffplay plays this file

```
$ ffplay -hide_banner hard_day.mod
[libmodplug @ 0x7ffa6c000bc0] Format libmodplug detected only with low score of 24, misdetection possible!
Input #0, libmodplug, from 'hard_day.mod':
  Metadata:
    name            : hard day
    sample          : hard day
                    : composed by
                    : chris of
                    : funny business
                    : 05.07.1992
                    : contact me at
                    : christian maul
                    : w-7930 ehingen/donau
                    : wachtelweg 16
                    : germany
    extra info      : 9 patterns, 4 channels, 10/31 samples
  Duration: 00:01:09.00, bitrate: 1 kb/s
    Stream #0:0: Audio: pcm_s16le, 44100 Hz, 2 channels, s16, 1411 kb/s
   1.51 M-A: -0.000 fd=   0 aq=  301KB vq=    0KB sq=    0B f=0/0
```

### What do I think

I guess mpv stops probing file at probescore higher than 24 so this file gets ignored?

**Comment by sfan5** [comment]
likely identical to #8466

Works in my testing environment tho:
<pre>
root@ubuntu:~# apt show libmodplug1 
Package: libmodplug1
Version: 1:0.8.9.0-2build1
[...]
root@ubuntu:~# mpv -v -v hard_day.mod 
[cplayer] Command line options: '-v' '-v' 'hard_day.mod'
[cplayer] mpv 0.33.0-61-gdae9ea3fa7 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Thu Jan 14 14:49:31 CET 2021
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.63.101
[cplayer]    libavcodec      58.117.100
[cplayer]    libavformat     58.65.101
[cplayer]    libswscale      5.8.100
[cplayer]    libavfilter     7.95.100
[cplayer]    libswresample   3.8.100
[cplayer] FFmpeg version: N-100625-gf6477ac9f4
[cplayer] 
[cplayer] Configuration: ./waf configure --disable-gl
[cplayer] List of enabled features: asm build-date cplayer cplugins debug-build ffmpeg glibc-thread-name glob glob-posix gpl iconv libass libavdevice libdl libm librt linux-fstatfs linux-input-event-codes optimize posix posix-or-mingw pthreads stdatomic vt.h zlib
[global] config path: '' -> '/root/.config/mpv'
[global] user path: '~~home/' -> '/root/.config/mpv'
[global] user path: '~~old_home/' -> '/root/.mpv'
[global] config path: 'encoding-profiles.conf' -/-> '/root/.config/mpv/encoding-profiles.conf'
[global] config path: 'encoding-profiles.conf' -/-> '/root/.mpv/encoding-profiles.conf'
[global] config path: 'encoding-profiles.conf' -> '/usr/local/etc/mpv/encoding-profiles.conf'
[cplayer] Reading config file /usr/local/etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[global] config path: 'mpv.conf' -/-> '/root/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/root/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/root/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/root/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -/-> '/root/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/root/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/etc/mpv/input.conf'
[global] config path: 'scripts' -/-> '/root/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/root/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/root/.config/mpv/watch_later'
[file] Opening hard_day.mod
[file] resize stream to 131072 bytes, drop 0 bytes
[file] Stream opened successfully.
[demux] Trying demuxers for level=normal.
[demux] Trying demuxer: disc (force-level: normal)
[demux] Trying demuxer: edl (force-level: normal)
[demux] Trying demuxer: cue (force-level: normal)
[demux] Trying demuxer: rawaudio (force-level: normal)
[demux] Trying demuxer: rawvideo (force-level: normal)
[demux] Trying demuxer: mkv (force-level: normal)
[demux] Trying demuxer: lavf (force-level: normal)
[lavf] Found 'libopenmpt' at score=76 size=2048.
[lavf] avformat_find_stream_info() finished after 12350 bytes.
[demux] Detected file format: libopenmpt (libavformat)
[cplayer] Opening done: hard_day.mod
[find_files] Loading external files in .
[global] config path: 'sub' -/-> '/root/.config/mpv/sub'
[global] config path: 'sub' -/-> '/root/.mpv/sub'
[global] config path: 'sub' -/-> '/usr/local/etc/mpv/sub'
[lavf] select track 0
[cplayer]  (+) Audio --aid=1 (pcm_f32le 2ch 48000Hz)
[...]
</pre>

I can neither find recent changes to [ffmpeg's support code](https://github.com/FFmpeg/FFmpeg/commits/master/libavformat/libmodplug.c) or [libmodplug](https://github.com/archlinux/svntogit-packages/commits/packages/libmodplug/trunk), which is weird because that leaves nothing to explain the failure.

**Comment by foxpy** [comment]
> [lavf] Found 'libopenmpt' at score=76 size=2048.

For some reason on your system it works with openmpt but not modplug? What is your testing environment?



> likely identical to #8466

My bad! It **is** a duplicate of #8466.

**Comment by foxpy** [comment]
I have tried to compile ffmpeg with libmodplug disabled and libopenmpt enabled but mpv still doesn't want to play this file on my machine.

**Comment by sfan5** [comment]
> For some reason on your system it works with openmpt but not modplug?

Oh indeed, didn't notice that. Arch doesn't even have libopenmpt so that might be it.

> What is your testing environment?

An Ubuntu 20.04.1 LTS container with libmodplug 1:0.8.9.0-2build1 and libopenmpt 0.4.11-1build1.
FFmpeg and mpv cloned and compiled from git (ffmpeg with `--enable-libopenmpt --enable-libmodplug` obviously).

**Comment by foxpy** [comment]
Oh okay, so I guess this issue is not related to mpv, it is just an Archlinux quirk. Maybe I should poke Arch maintainers to bring libopenmpt?

**Comment by sfan5** [comment]
The main cause for this is that ffmpeg returns a [lower probe score](https://github.com/FFmpeg/FFmpeg/commit/c605adbf562fbf535e83ae427bb681bc45e440c8) for files that it can identify as modplug but are below 16k bytes in size, this lower score apparently isn't enough for mpv identify the file. libopenmpt also has [more advanced probing code](https://github.com/FFmpeg/FFmpeg/blob/f975cf7cc061b814bc029bb2fc86f656494c4d5c/libavformat/libopenmpt.c#L235-L275) so it generally seems like the better alternative.

I couldn't tell you whose bug this is, but telling your distro to swap out libmodplug with libopenmpt seems like the easiest way to have this fixed.

**Comment by foxpy** [comment]
> this lower score apparently isn't enough for mpv identify the file

Just wondering, is it a good idea to lower minimum requirement for probe score in mpv?

**Comment by foxpy** [comment]
@sfan5 I have just put `demuxer-lavf-probescore=20` in my mpv config and everything works like a charm :)
