### ISSUE TITLE
Extreme frame drops when window is focused, plays fine when not in focus

### ISSUE THREAD

**Issue by mwsduelle** [mpv-player/mpv#8475]
### Important Information

- mpv version: latest git
- Windows Version: Win 10 Pro build 19042
- Source of the mpv binary: Shinichiro
- If known which version of mpv introduced the problem: not sure

### Reproduction steps

Play any video, with my config or --no-config.

### Expected behavior

Video plays with no issues.

### Actual behavior

A 0.5 FPS mess when mpv is in focus and completely normal when not in focus. I was just watching something a few hours ago without issue. I had made no changes to config or scripts since then. I can only assume this is a Windows or driver problem that appeared out of nowhere.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/5825031/log.txt)

**Comment by mwsduelle** [comment]
I tried turning off G-Sync and that fixed it. However, it was working fine with G-Sync enabled until yesterday.

**Comment by richardmalone** [comment]
Same here, I found that losing focus then going back to focus fixes it.

Try changing gpu-api to OpenGL or Vulkan. That also fixed the problem for me.

I also have G-Sync enabled.

**Comment by CrendKing** [comment]
Do you have NVIDIA driver 461.xx or above installed? If so, can you try reverting back to 460.89 and see if the problem still exist?

I think there is a bug (or feature, who knows) introduced in NVIDIA 461.09 and still exists in today's 461.40, which activates G-Sync regardless if you choose to not enable it in windowed mode. If you can confirm my theory, I'll create a more detailed issue. I don't think mpv is responsible for anything because other video players are also affected.

**Comment by Dudemanguy** [comment]
Driver issue that we can't do anything about (hopefully they fixed this by now).
