### ISSUE TITLE
(YouTube) Auto-generated + manually submitted subtitles

### ISSUE THREAD

**Issue by smnthermes** [mpv-player/mpv#8518]
How to set a config file enabling auto-generated subtitles for certain languages, while still keeping all manually submitted ones for videos that have these?

**Comment by garoto** [comment]
`ytdl-raw-options=sub-lang="en,fr,tt,yi",write-sub=,write-auto-sub=`

**Comment by smnthermes** [comment]
It works, but isn't a very elegant solution, since manually submitted subtitles have regional variants (unlike auto-generated ones). Is it possible to only link `sub-lang` to `write-auto-sub`, and link `all-subs` to `write-sub`?

**Comment by garoto** [comment]
> manually submitted subtitles have regional variants (unlike auto-generated ones)

Just specify those then. e.g.: `sub-lang="pt-BR,es-419,zh-TW,en-GB,en,pt"`

**Comment by Akemi** [comment]
the question has been answered.

**Comment by anishmittal2020** [comment]
@Akemi @garoto  Please reopen the issue.

You can see from the folllwoing what you mentioned does not work:

```bash
$ echo $Url
https://www.youtube.com/watch?v=7sxpKhIbr0E
$ mpv --no-config --fs --ytdl-raw-options=ignore-config=,sub-lang='en\,de',write-sub=,write-auto-sub= $Url
[ytdl_hook] Usage: youtube-dl [OPTIONS] URL [URL...]
[ytdl_hook] 
[ytdl_hook] youtube-dl: error: no such option: --de,write-sub 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 
Failed to recognize file format.


Exiting... (Errors when loading file)
$ mpv --no-config --fs --ytdl-raw-options=ignore-config=,sub-lang='en,de',write-sub=,write-auto-sub= $Url
[ytdl_hook] Usage: youtube-dl [OPTIONS] URL [URL...]
[ytdl_hook] 
[ytdl_hook] youtube-dl: error: no such option: --de,write-sub 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 
Failed to recognize file format
```

**Comment by Akemi** [comment]
because you didn't properly escape your options. also this was a question and not an issue so not going to reopen it. if you have an issue please open a new one.

**Comment by anishmittal2020** [comment]
@Akemi I wrote 2 examples. In the first one I escaped the comma and the second I didn't. In both cases I am getting the same error. Could you please tell me what is wrong?

**Comment by garoto** [comment]
I believe you need to escape the quotes , not the comma: `sub-lang=\'en,de\'`

**Comment by anishmittal2020** [comment]
@garoto What you mentioned does not work. Please don't comment if you are not sure.

**Comment by JoseHidalgo** [comment]
@all sorry to chime in, but I think my question is relevant to this discussion.

There's [this YT video for example](https://www.youtube.com/watch?v=dfnCAmr569k), where if you want to access the english predefined subtitles, they are named something like `en-en-NP7-etc. `(see attached screenshot), and they are #45 on the list. I know other videos with similar naming issues.

In that case, what would be the correct syntax for `sub-lang` ? Would it be possible to use a wildcard such as `sub-lang=en*` ? Of course I have tried that but it doesn't work... And if I omit the `sub-lang` part, I get more than 200 subtitles and I have to cycle throught until I reach #45, so that's not very convenient.

![2023 05 05 - 00 12 08](https://user-images.githubusercontent.com/10851603/236341379-a26c002c-fcf7-4d44-93f6-67002b4f3de4.png)

**Comment by rxmmah** [comment]
> `ytdl-raw-options=sub-lang="en,fr,tt,yi",write-sub=,write-auto-sub=`

where should i write this?
please help me

**Comment by llyyr** [comment]
> where should i write this?

In your mpv.conf or pass it as a command line argument when running mpv
