### ISSUE TITLE
White screen delay

### ISSUE THREAD

**Issue by marconii2002** [mpv-player/mpv#8520]
- mpv version: 0.33.0-62-ga3e440c611
- Windows Version: 10 20h2
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
- If known which version of mpv introduced the problem: not known
- Possible screenshot or video of visual glitches: https://i.imgur.com/l9RQKLQ.png

**Reproduction**

Double click on any video file in Windows Explorer

**Expected behavior**

Immediately start video playing after mpv start with profile=gpu-hq, scale=ewa_lanczossharp, cscale=ewa_lanczossoft in mpv.conf file.

**Actual behavior**

Short white screen delay after mpv start with profile=gpu-hq, scale=ewa_lanczossharp, cscale=ewa_lanczossoft in mpv.conf file.

**Log**

https://pastebin.com/mvG0fJzT

**Comment by Akemi** [comment]
don't ignore the issue template

**Comment by marconii2002** [comment]
Corrected.

**Comment by Akemi** [comment]
please do what the issue template said. does it work with `--no-config `? if yes, which option exactly causes the problem? is it only reproducible with the config you mentioned?

**Comment by marconii2002** [comment]
Yes this is reproducible with the config that I mentioned. You have to just create simple mpv.conf file with that three options. With --no-config white screen do not appear.

**Comment by jeeb** [comment]
I recommend checking the timings after `shaderc compile status 'success' (0 errors, 0 warnings)`.

F.ex. in your log there is a few of these, just giving an example of one:
```
[   0.299][d][vo/gpu] Resizing texture: 1920x1080
[   0.368][v][vo/gpu/d3d11] shaderc compile status 'success' (0 errors, 0 warnings)
[   0.370][v][vo/gpu/d3d11] Compiled a vertex shader in 70211us
[   0.370][v][vo/gpu/d3d11] shaderc: 68565us, SPIRV-Cross: 313us, D3DCompile: 1333us
```

If those are too long, you will have a placeholder around most likely. We cannot make these components magically faster, unfortunately :) . And of course if you compare the log with simpler shaders you most likely have these times be much shorter? If not, then it's something else.

In theory shaders could be cached (which would only work for specific input/output resolutions, pixel formats etc, which makes it much less useful than you'd think), or reworked made to more parameterized so that caching might make more sense, but currently I do not see the use in putting too much effort into this.

**Comment by marconii2002** [comment]
I tested witch scale=bilinear, cscale=bilinear https://pastebin.com/r7sCqq9j

```
[   0.276][d][vo/gpu] Resizing texture: 1920x1080
[   0.345][v][vo/gpu/d3d11] shaderc compile status 'success' (0 errors, 0 warnings)
[   0.347][v][vo/gpu/d3d11] Compiled a vertex shader in 70167us
[   0.347][v][vo/gpu/d3d11] shaderc: 68530us, SPIRV-Cross: 316us, D3DCompile: 1321us
```
This is something else.

**Comment by jeeb** [comment]
Don't focus on a single one. There's multiple and they stack up. You have just shaved off 300ms with that log off your start-up delay :P .

```
[   0.490][v][cplayer] first video frame after restart shown
```
VS in the previous log
```
[   0.755][v][cplayer] first video frame after restart shown
```

**Comment by Akemi** [comment]
if it's the shader compilation then `--gpu-shader-cache-dir=` might help at least for the reoccurring combinations?

**Comment by marconii2002** [comment]
White state is for about 1 sec for videos in resolution less than 1280x720 and 0.5 sec bigger resolution.
When I tested on bilinear scalers white state do not appear on videos in 1920x1080 and became visibly shorter on videos in lower resolutions.
White screen state is only on windows. I tested on Manjaro live with this same scalers like on Windowa and white screen do not appear. Here is log from linux https://pastebin.com/Q3Wbhfcn
