### ISSUE TITLE
Maximal rotation degree is 359, but should be 360

### ISSUE THREAD

**Issue by crazysword1** [mpv-player/mpv#8527]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

Imagine a video.
Rotate right by 90
Rotate right again by 90 (the video will be 180 from the original)
Rotate right again by 90 (270)
Rotate right again by 90 (359) Here is where the problem starts. If you rotate the video by 90 degrees four times, it will end at 359. Furthermore, the video will be slanted.

Currently, maximal rotation degree is 359, but should be 360. And in the manual, it says "Currently supports 90° steps only", however with n cycle video-rotate rotation step is 1°.

**Comment by Akemi** [comment]
yes you can rotate by arbitrary numbers by now. it was forgotten to update the docs.

instead of 
```
n add video-rotate 90
```
use something like this
```
n cycle-values video-rotate "90" "180" "270" "no"
```

for more complex things a script like https://github.com/mpv-player/mpv/issues/3434#issuecomment-274929417 would probably be better.

otherwise, since 360 and 0 are the same it shouldn't be added to the range, because then we would get 3 'neutral' values when cycling the value, eg 0, 360 and no would look the same.
