### ISSUE TITLE
MPV does not show output in the terminal

### ISSUE THREAD

**Issue by siferati** [mpv-player/mpv#8544]
### Important Information

- **mpv version:** 0.33.0
- **Windows Version:** Windows 10 Pro 1909
- **Source of the mpv binary:** https://sourceforge.net/projects/mpv-player-windows/files/stable/mpv-0.33.0-x86_64.7z/download

### Reproduction steps

Run mpv in the terminal: `mpv.exe --help`

### Expected behavior

Terminal outputs help message.

### Actual behavior

Nothing happens.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5946214/output.txt)

### Other

I tried running mpv with different options. No matter what I do it never shows output in the terminal and the process exits.

**Comment by jeeb** [comment]
Windows has a concept of a "GUI app" and a "CLI app". An application has to one of these.

* If you build as a CLI app, you get a forced cmd.exe pop up and you get standard output/error there.
* If you build as a GUI app, you get no forced cmd.exe and you get standard output/error in the debug output (I think process explorer or so shows that if I recall correctly).

Basically what mpv does is that you have:
* `mpv.com`, which is a CLI app. IT in the background starts up `mpv.exe` and hooks into the debug output.
** And because `com` is before `exe` alphabetically, if you just run `mpv` you get mpv.com.
* `mpv.exe` which is a GUI app. This is the thing that you can register file extensions etc to, and do not get a forced cmd.exe command prompt.

**Comment by avih** [comment]
You need to run `mpv.com` to make it use the terminal, which is what gets executed when you run `mpv` without a file extension.

**Comment by siferati** [comment]
Thank you!

**Comment by garoto** [comment]
> And because com is before exe alphabetically, if you just run mpv you get mpv.com.

Minor correction: extension priority is determined by the `%PATHEXT%` environment variable.

**Comment by bitraid** [comment]
> > And because com is before exe alphabetically, if you just run mpv you get mpv.com.
> 
> Minor correction: extension priority is determined by the `%PATHEXT%` environment variable.

And console applications not started from the terminal, don't spawn `cmd.exe` but `conhost.exe`.
Explained in more detail in the FAQ: https://github.com/mpv-player/mpv/wiki/FAQ#on-windows-why-does-mpvexe-not-attach-to-the-console-and-what-does-mpvcom-do

**Comment by jeeb** [comment]
Yup, you can clearly see that i wrote something quickly not remembering if this was in the FAQ or so (which it was). So some details went the way of the dodo :P .
