### ISSUE TITLE
ADD clock time (wall time) seek that takes into account playback speed

### ISSUE THREAD

**Issue by allanlaal** [mpv-player/mpv#8558]
ADD clock time (wall time) seek that takes into account playback speed
OR:
ADD playback speed variable multiplication for current seek

### Expected behavior of the wanted feature

when I'm viewing a video with speed 4.7 and seek back 2 sec, I personally want it to seek backwards 2 seconds of Wall time, not 2 seconds of playback time.

### Alternative behavior of the wanted feature

feature not present. normal seek seeks playback time amount, not taking speed into account

### Log file

(log does not apply here)

**Comment by avih** [comment]
Just write a script for that. In JS that would be:
```js
mp.register_script_message("speed-seek", function(speed) {
    mp.commandv("seek", (mp.get_property_number("speed") || 1) * Number(speed));
})
```

and then at `input.conf` you can add, for instance:
```
ctrl+right script-message speed-seek 2
```

**Comment by allanlaal** [comment]
shouldn't this be a feature in mpv itself?

**Comment by avih** [comment]
> shouldn't this be a feature in mpv itself?

Put the script at your scripts dir, and it will be a feature of YOUR mpv.

Personally I don't think it's a useful feature, and judging by the fact that no one asked for it ever, it seems I'm not alone.

mpv is extensible with scripts exactly so that it's easy to add custom functionality which is not important to most users without making the mpv code more complex.
