### ISSUE TITLE
i went to move to Linux and get confused by mpv FAQ

### ISSUE THREAD

**Issue by amayra** [mpv-player/mpv#8594]
I'm trying to move to Linux and everyone recommend me to use Pop!_OS or ubuntu

but mpv wiki say gnome is not supported by mpv so I think I should go with manjaro KDE so here my Questions :

Q1: Can I use gnome and have the same experience as Windows 10 without any screen blanking or tearing because I don't care about windows decorations and I don't use Screensaver or screen lock

Q2: I have Ivybridge CPU with HD 4000 and after I read in FAQ

> If you manage to pick the right driver versions, things will probably work very well up to medium settings.

what the right driver versions I should try "modesetting" or "xf86-video-intel" or maybe "i965" and "mesa" I don't know how the driver works in Linux yet there too many drivers 

Q3: should I use the Wayland protocol for a better experience but in discord they told me that KDE doesn't support Wayland quite well like gnome compositor if you went better performance 

Q4: Can I use Vulkan with log say `WARNING: Ivy Bridge Vulkan support is incomplete` this my GPU Vulkan report 
https://vulkan.gpuinfo.org/displayreport.php?id=10349 is up to Vulkan 1.2.145 I think what Vulkan extensions mpv use?

ps: Please Be Patient I'm new to all this and try to move from Windows 10 to Linux for better performance and stability

**Comment by LaserEyess** [comment]
I think you'll find that if you just install it most things will Just Werk™ for you. Since your hardware is so old, you probably won't be able to use vulkan, but wayland will work. I think you should just install linux and mpv and you'll probably be surprised to learn that everything will work.

The only deal breaker is that GNOME doesn't support idle-inhibit, which means your screensaver will activate after a while. This is a [GNOME bug](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/111).

**Comment by amayra** [comment]
I don't use a screensaver my laptop connect to the TV when I use it 
there any other downside if I use gnome?

**Comment by Digitalone1** [comment]
You can try Celluloid. It's based on mpv and is targeted to be used on Gnome. Maybe it uses a few CPU cycles because of GTK interface, but shouldn't be a real issue if you enable hardware decoding.

Otherwise, you can start mpv from terminal with `gnome-session-inhibit` to prevent black screen during playback: https://github.com/mpv-player/mpv/issues/5459#issuecomment-361236848

**Comment by Akemi** [comment]
the question has been answered.
