### ISSUE TITLE
How to rotate video in real time with input.conf?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8605]
I tried to add shortcuts to rotate video in real time.

### Log file

[test.txt](https://github.com/mpv-player/mpv/files/6058486/test.txt)

**Comment by guidocella** [comment]
You can use something like:
```
r cycle-values video-rotate 270 180 90 0
t cycle-values video-rotate 90 180 270 0
```

**Comment by laichiaheng** [comment]
@guidocella Cool! How do you know this? I can't find it in the manual.

**Comment by guidocella** [comment]
> @guidocella Cool! How do you know this? I can't find it in the manual.

I don't remember where I first found that keybinding, but video-rotate is just a regular property that you can alter with cycle-values like any other. I do think it would be nice to have it as an example in the manual or even as a default keybinding since it's not obvious how to do it and it's very useful.

**Comment by Akemi** [comment]
that's something more for the wiki than the manual, i would say.

**Comment by guidocella** [comment]
Added it to the wiki.
