### ISSUE TITLE
Encoding mode: error messages generated during conf parsing appear at the beginning of the encoded output stream when piping output (--o=-)

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#8608]
### Important Information

- mpv version: git master latest

### Reproduction steps

mpv.conf:
```
af-add=non-existent-filter
```

Command line:

```
mpv --of=matroska --o=- "video.mp4" >out.mkv
```

But the resulting media is unplayable.

Opening out.mkv in a hex editor reveals the problem, observe the text error at the beginning before the matroska header bytes:

![Frhed_Rs1TwNeQzN](https://user-images.githubusercontent.com/5526342/109502579-140a5480-7a91-11eb-8a77-39765a11f0ff.png)

So any errors generated during the conf loading stage are sent to the output stream when using `--o=-`, creating a corrupted media stream that cannot be read.

A similar command where we try to pipe the output to another process also fails:

```
mpv --of=matroska --o=- "video.mp4" | ffplay -i -
```

**Comment by Akemi** [comment]
this is me making a very naive remark, but since this error happens in the config parser, eg at a point where we don't know which options are passed to mpv (since option haven't be parsed yet), we don't know yet that we are using encoding mode. so it is probably impossible for us to know, with our usual way, to properly circumvent this without some 'hacky'/ugly workaround?


https://github.com/mpv-player/mpv/blob/dcec6d9556c6cfca11b865442174479096f55111/options/m_config_frontend.c#L745

**Comment by hedgehog90** [comment]
I've managed to get around it by adding to mp_msg_force_stderr in msg.c:
```
if (force_stderr)
        fseek(stdout, 0, SEEK_SET);
```
Which just sets the stdout write position to 0 so any messages that might have been written gets overwritten by the output stream.

I can put this in a pull request but like you said it is a bit hacky.
