### ISSUE TITLE
Media keys not recognized

### ISSUE THREAD

**Issue by dbrookman** [mpv-player/mpv#8620]
### Important Information

mpv 0.33.0-93-gaac18441
macOS 11.2.1 (arm64)
`./waf configure --lua=luajit && ./waf build`

### Reproduction steps

Run `mpv --input-test`, focus to the mpv window and press any media key.

### Expected behavior

A line with the media key and what it's bound to should be shown.

### Actual behavior

No line is shown, even when accessibility permissions are set for mpv in System Preferences.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/6092338/mpv.log)

**Comment by Akemi** [comment]
your reproduction steps are incomplete, `mpv --input-test` doesn't work by itself. you should use `mpv --input-test --force-window --idle`.

accessibility permissions are not needed anymore, since we use the media player api.

does this script work https://gist.github.com/Akemi/b264beb7df3bbbb8f1bbad8c659fbba8?

**Comment by dbrookman** [comment]
`mpv --input-test --force-window --idle` still doesn't react to media keys.
The script doesn't react to media key input, but it did react to the pause button in the control center's now playing.

Looking further, the media keys don't seem to work in QuickTime or Music either, so I'm starting to think it's actually an OS regression, or something else.

**Comment by dbrookman** [comment]
Don't be like me. Don't unload `/System/Library/LaunchAgents/com.apple.rcd.plist` and forget about it. 😬
