### ISSUE TITLE
Fix tearing in fullscreen mode with Intel UHD 620 on X11 / Gnome

### ISSUE THREAD

**Issue by agostonbarna** [mpv-player/mpv#8682]
### Important Information

This is probably a GNOME bug (I even found an extension that may provide a workaround for it: https://github.com/kazysmaster/gnome-shell-extension-disable-unredirect, but didn't try it as I'd rather not disable it globally).
The reason why I opened the ticket is to mention the workaround that I found for mpv: using the `--x11-bypass-compositor=never` option eliminated the tearing. I found the `--x11-bypass-compositor=no` option in the [FAQ](https://github.com/mpv-player/mpv/wiki/FAQ#X11Intel), but it didn't work for me with setting it to `no`, but only with `never`. Maybe this worth a mentioning there.

Provide following Information:
- mpv version:
  ```
  mpv 0.33.0-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
   built on UNKNOWN
  FFmpeg library versions:
     libavutil       56.51.100
     libavcodec      58.91.100
     libavformat     58.45.100
     libswscale      5.7.100
     libavfilter     7.85.100
     libswresample   3.7.100
  FFmpeg version: n4.3.2
  ```
- Linux Distribution and Version: Arch Linux, 5.10.26-1-lts
- Source of the mpv binary: https://github.com/archlinux/svntogit-community/blob/aea9f1bf85ca5c2ef58dded9aff806317e4f8e9c/trunk/PKGBUILD
- Window Manager and version: GNOME Shell 3.38.4
- GPU driver and version: Intel Corporation UHD Graphics 620 (rev 07) with i915, kernel modesetting, without `xf86-video-intel`

### Reproduction steps

```sh
mpv --no-config --video-sync=display-resample --fullscreen http://www.oc-burner.de/ftp/Videos/juddertest/juddertest_60.mp4
```

### Expected behavior

No tearing in fullscreen

### Actual behavior

The video is tearing in fullscreen (but actually there is no noticable tearing in windowed mode)

**Comment by Dudemanguy** [comment]
Tearing and X11 is an ancient problem unfortunately. With the right combination of drivers + compositor it *shouldn't* tear, but sometimes it happens. There's not really anything we can do about it from our end. As for the `x11-bypass-compositor` option, setting it to `no` just doesn't send any hints to the WM but GNOME probably unredirects it anyway (which causes tearing for whatever reason; GNOME bug? Driver bug?). `never` explicitly hints to never disable the compositor which is why it stops the tearing for you. Normally, that shouldn't be something you need to do, but apparently it happens. It is worth mentioning `never` on the FAQ though yeah.
