### ISSUE TITLE
[Request] --force-window parameter: image

### ISSUE THREAD

**Issue by bitingsock** [mpv-player/mpv#869]
I'm wondering how popular it would be to add a parameter to the --force-window option. This parameter would set an image file as the video. Preferably, one could designate relative paths and wildcards: --force-window=%X/*.jpg(delimiter)png

**Comment by mvucBmM0** [comment]
I would just like to reinforce this request.
Apart from using audio files with embed art, i haven't found any other way to show album art while playing an audio file in mpv. This would fit the bill.

**Comment by sljunkie** [comment]
This could be useful - one could create a profile for using mpv as a music player from the file browser with a fixed image or a file named "cover|front.png|jpg" located at the same directory as the audio file(s).

**Comment by sljunkie** [comment]
I have an idea that could be easily implemented: instead of a black screen, by default a image with the mpv logo at the center could be drawn in the --force-window mode, if the media has only audio and there's no embedded cover art. Something like this:

![mpv-background](https://cloud.githubusercontent.com/assets/7532854/10355358/3d2ba976-6d41-11e5-8883-698a2a3be18f.png)

**Comment by woodruffw** [comment]
Another +1 for this.

**Comment by thebombzen** [comment]
Is there any particular reason you can't just *play* the image, and set `--image-display-duration=inf`?

**Comment by bitingsock** [comment]
that partially works but then the osc and scripts to operate on the audio-file that you would load; they operate on the image file

**Comment by bitingsock** [comment]
as it turns out, the --external-file option as explained in https://github.com/mpv-player/mpv/issues/3056 seems to work for this purpose now.
