### ISSUE TITLE
Crash with quitting on macOS

### ISSUE THREAD

**Issue by pervel** [mpv-player/mpv#8704]
### Important Information

mpv: stable 0.33.1 (bottled), HEAD

Mac OS X 10.15.7 (19H524)

From Homebrew

I have reverted to mpv version 0.32.0 and have NOT seen the problem on that version.

### Reproduction steps

Crash happens sometimes after quitting mpv. It does not happen always. I always start mpv from the terminal.

One time the crash resulted in a kernel panic.

### Log file

MacOS crash file attached

[mpv_2021-04-07-180739_GigaMac.crash.zip](https://github.com/mpv-player/mpv/files/6274759/mpv_2021-04-07-180739_GigaMac.crash.zip)

**Comment by Akemi** [comment]
please try with a master build, not the release. also don't ignore parts of the issue template. try with --no-config like it asked you to do, post a log, etc.

this sounds like a driver, sdk or OS bug, especially since it supposedly causes a kernel panic. to be frank, with the relationship apple and nvidia has i wouldn't be surprised.

**Comment by pervel** [comment]
I'm not going to try with --no-config since it doesn't happen everytime. Also, after getting a kernel panic I have no desire to try with the current version anytime soon. I hope you can use the attached crash log. I will just remain on version 0.32.0 for now.

**Comment by CounterPillow** [comment]
Then I guess your problem won't be looked into.

**Comment by pervel** [comment]
I don't have a problem on 0.32.0. But if you don't want to look into the crash problem in 0.33.1, that is your prerogative.

**Comment by CounterPillow** [comment]
It's crashing on your system, and the steps being asked of you are there to find a way to reproduce the issue on the system of someone who is willing to look into it. I'm sure refusing to provide that info will work out well for you though, especially because the crash log does not contain enough information to conclude anything other than "nvidia did an oopsie".
