### ISSUE TITLE
dash-case extension files unavailable for script-binding

### ISSUE THREAD

**Issue by hxss** [mpv-player/mpv#8718]
### Important Information

Arch linux
```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.1
```

### Reproduction steps

```js
// ~/.config/mpv/scripts/my-tools.js

mp.add_key_binding(
	null,
	'my-command',
	function () {
		mp.osd_message('asdasd');
	}
);
```

```
# ~/.config/mpv/input.conf

v           script-binding my-tools/my-command
c           script-message-to my-tools my-command
```

Press v/c.

### Expected behavior

OSD expected.

### Actual behavior

Nothing happens.

Commands runs only after renaming script to `my_tools.js`.

### Log file

--

### Sample files

--

**Comment by Pikanet128** [comment]
Same thing for me except I thought it was because I had a binding that had the same name as it's script but I guess its just the dashes (I checked).

in input.config
`ctrl+o script-binding open-file-dialog/open-file-dialog`
fails
`ctrl+o script-binding open-file-dialog`
works

interestingly 
`ctrl+o script-binding open_file_dialog/open-file-dialog`
works even if the file is named 
open-file-dialog.lua

I guess that can work

I wonder if it has anything todo with what happens when the keybinding is created in the script

in open-file-dialog.lua
`mp.add_key_binding('ctrl+o', 'open-file-dialog', open_file_dialog)`

log.txt
`[   0.025][d][cplayer] Run command: define-section, flags=64, args=[name="input_open_file_dialog", contents="ctrl+o script-binding open_file_dialog/open-file-dialog\n", flags="default"]`

**Comment by Dudemanguy** [comment]
What's happening here is mpv is replacing the "-" in the script name with "_" and using that as the name of the client. That's why `my_tools` will work even though the script is named `my-tools.js`. Note that the same thing is true if you name it something like `my tools.js`. Any non-alphanumeric characters are replaced with an underscore. 
https://github.com/mpv-player/mpv/blob/f1d0365a6f72b88f7427814f636863ae1656f72a/player/scripting.c#L75-L80.

We could potentially add more valid separators, but I'd lean towards just documenting this behavior properly instead.

**Comment by Dudemanguy** [comment]
I don't think anyone wants to add more separators, so I went ahead and documented this behavior with 7df9ebda6c9828b75b814facd4267c8da0eca736.
