### ISSUE TITLE
Current release policy

### ISSUE THREAD

**Issue by t-8ch** [mpv-player/mpv#8719]
Currently the `README.md` and `DOCS/release-policy.md` specify that each month a new release is supposed to happen.
This is not really the case at the moment, the last release is five months old.

Is this a temporary hiccup, has nothing release-worthy happened or should users use the `master` branch again?

**Comment by LaserEyess** [comment]
It also says:
> The goal of releases is to make Linux distributions happy.

So they're not really meant to be standard "releases". If I were you I would just build from master.

**Comment by avih** [comment]
> last release is five months old

Less than a week ago there was a minor release.

Regardless, mpv did not make rapid progress in recent times, and even when it did the release policy was more a wishful thinking than actual practice.

The practice was and is to make a release when enough useful stuff was added since the last release.

Master is generally stable, and if things get broken then they're usually fixed quickly. The developers, and many users, use the master branch daily. Whether or not you want to do the same is up to you.

**Comment by t-8ch** [comment]
Thanks for the quick responses.

My goal was not to suggest that a release would be needed;
only to find out if I should ask my distro to package the git version if this is what the developers prefer.

> The practice was and is to make a release when enough useful stuff was added since the last release.

Then I'll wait for that and continue to use the `git` version as before.
