### ISSUE TITLE
How to execute a IPC command after a given one has been completed?

### ISSUE THREAD

**Issue by rdrg109** [mpv-player/mpv#8782]
I'm asking this because I want to execute `seek` after the file has been completely loaded. In the code block shown below, the second command fails because apparently the loaded file hasn't been fully loaded.

```
#!/bin/bash
echo '{ "command": ["loadfile", "/home/user/v/1.mkv" ] }' | socat - /tmp/mpvsocket
echo '{ "command": ["seek", "90", "absolute"] }' | socat - /tmp/mpvsocket
```

```
$ ./main.sh
{"data":{"playlist_entry_id":4},"request_id":0,"error":"success"}
{"request_id":0,"error":"error running command"}
```

I've solved this issue by doing the following but I'd rather not using `sleep`.

```
#!/bin/bash
echo '{ "command": ["loadfile", "/home/user/v/1.mkv" ] }' | socat - /tmp/mpvsocket
sleep 1
echo '{ "command": ["seek", "90", "absolute"] }' | socat - /tmp/mpvsocket
```

```
$ ./main.sh
{"data":{"playlist_entry_id":5},"request_id":0,"error":"success"}
{"data":null,"request_id":0,"error":"success"}
```

**Comment by avih** [comment]
To deal with JSON IPC properly, you need some events framework so that you can get notified and act upon completions of things you care about. This is usually done using some programming language rather than one-off commands from the shell.

You can look at some existing external bindings using the JSON-IPC interface, like https://github.com/jaseg/python-mpv or https://github.com/j-holub/Node-MPV (they're not associated with mpv, and I don't know how good or well-meintained they are).

There might be some way to create such minimal framework using a shell script and socat, but I haven't tried that. If you can come up with such minimal framework, then you can post here and we might even include it at the examples section.
