### ISSUE TITLE
Change colors of mpv

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#8789]
I have changed some colors of mpv, but this area was impossible (white text, numbers, bar and symbols below playback window)
It's not possible?

![Captura](https://user-images.githubusercontent.com/78575427/116486543-23b4d800-a84b-11eb-8bb3-ef092d481df9.jpg)

**Comment by ChrisK2** [comment]
Not the normal way, since those are the best colors. If you still want to change them, you have to copy the [OSC script](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua), modify the [colors values there](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L68-L87) (see the [ASS "specs"](http://www.tcax.org/docs/ass-specs.htm) to understand that mess) and load it as [external script](https://mpv.io/manual/stable/#script-location) while[ disabling the built-in OSC script](https://mpv.io/manual/stable/#options-no-osc).
