### ISSUE TITLE
Some kind of "automatic zoom" to scale using as input a selected region

### ISSUE THREAD

**Issue by fboumol** [mpv-player/mpv#8794]
While mpv is playing (and with zoom level to 0, i.e., the initial and default one) I would like to select a rectangle region inside the windows running mpv (the selection could be easily done using https://github.com/naelstrof/slop ) in such a way that mpv  automatically calculates and applies the right zoom level and span (whatever is convenient: rightward, downward, etc ) for the aim that now this selected region is the only one showed in the window.

I have been unable to find anything like this in the documentation. If this is not already implemented I would like you to consider adding this feature (it seems to me really useful and I suspect it would be just a few lines of code). 

The best way I can think of using this feature would be in such a way that can be activated using a shortcut.

Thanks for "mpv" (a really lovely piece of software).

**Comment by avih** [comment]
mpv won't support this, and it can be done with scripts, like https://github.com/occivink/mpv-scripts#croplua

Also, you can easily define key bindings to move the video around and zoom or stretch in one/both directions so you can reach your target zoom/crop easily.

**Comment by fboumol** [comment]
> mpv won't support this, and it can be done with scripts, like https://github.com/occivink/mpv-scripts#croplua

Thanks. This is exactly what I was looking for.

> Also, you can easily define key bindings to move the video around and zoom or stretch in one/both directions so you can reach your target zoom/crop easily.
I was aware of the key bindings for moving around the video but I was looking for automating it. Your suggested scripts solve the issue of automatizing it.

**Comment by fboumol** [comment]
Sorry to bother again, but while the croplua script is working it is not exactly the same I was asking for. The difference is due to the fact that I do not want to crop, I also need to be able to move around the "zoomed" video (leftwards, downwards, etc).

I am thinking of using this as a kind of magnifying glass (for people with vision problems) and the fact of cropping kills this purpose.

Is anyone aware of some lua script that applies the zoom but without cropping? If not, I guess I will have to take a look at the lua code to learn how to adapt it to my aim.

**Comment by avih** [comment]
> If not, I guess I will have to take a look at the lua code to learn how to adapt it to my aim.

This could be nice, especially if you later add it to the user scripts WIKI - https://github.com/mpv-player/mpv/wiki/User-Scripts

In general, mpv focuses on very high configurability with command line or scripting or external interface with JSON-IPC, but not so much about GUI. It's just not really a GUI player, and if your focus is on GUI, then you should look at other players, possibly ones which use (lib)mpv as backend.

The little GUI which mpv does have (the OSC) is the minimum to make it useful also with a mouse, but it's still only for convenience and you could do with the KB alone everything which the OSC can do with the mouse.

Luckily, mpv is relatively easy to extend with scripts, which is why we prefer auxiliary functionality to not add complexity to the mpv itself.

**Comment by fboumol** [comment]
Let me just point out here that the user occivink has added a soft mode to his croplua script which does this "automatic zoom". The details are at https://github.com/occivink/mpv-scripts/issues/50
