### ISSUE TITLE
a mangled title in the mpv window makes all GNOME windows disappear until GNOME is restarted

### ISSUE THREAD

**Issue by slidercrank** [mpv-player/mpv#8812]
### Important Information

Provide following Information:
- mpv version
_mpv 0.33.1 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4_

- Linux Distribution and Version
_Fedora 34 (the bug has existed at least since Fedora 30)

- Source of the mpv binary
fedora repository
Source RPM  : mpv-0.33.1-1.fc34.src.rpm
Build Date  : Mon 05 Apr 2021 08:29:07 PM MSK
Build Host  : buildvm-06.virt.rpmfusion.net
Packager    : RPM Fusion
Vendor      : RPM Fusion
URL         : http://mpv.io/_

- If known which version of mpv introduced the problem
_unknown_

- Window Manager and version
_gnome-shell v4.0 (but the bug existed in gnome-shell v3.x too)
- GPU driver and version
on the kernel side it's amdgpu, kernel version is 5.11.16-300.fc34.x86_64
on the userspace side it's xorg-x11-drv-amdgpu-19.1.0-8.fc34.x86_64_

- Possible screenshot or video of visual glitches
_https://0x0.st/-aU3.png
or the output on the terminal
$ wmctrl -l
0x04200002  0                   N/A ����������� ����_2021_BDRip - mpv_

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.
_start a video file with mpv
press SUPER (winkey) OR move the mouse cursor the upper left corner_

### Expected behavior
_miniature windows of running apps are shown allowing to choose windows by their look rather than only by name_

### Actual behavior
_all windows are gone. no way to switch between them any more. Not even with alt-tab_

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.
_a 34k video sample enough to reproduce the issue
https://0x0.st/-aUy.avi
run mpv with --pause_

**Comment by jeeb** [comment]
Basically any non-utf8 text which contains invalid UTF-8 will probably make this happen, so we have two alternatives that I could initially think of:

1. We attempt to check strings which we read from metadata etc sources for valid utf-8 (at the very least those that we read from media files) - IMHO better.
2. We do the check when operating with specific attributes/APIs. this means that the data can be invalid but when pushed to certain APIs etc, it is validated.

In either case, the invalid UTF-8 code points should probably be dropped (instead of adding a replacement character)?

**Comment by Akemi** [comment]
just for additional info, since i looked it up just now:
i believe where the meta tags are checked and converted if applicable: https://github.com/mpv-player/mpv/blob/f1d0365a6f72b88f7427814f636863ae1656f72a/demux/demux.c#L4581-L4599
the actual conversion which is called from visit_meta and the callback : https://github.com/mpv-player/mpv/blob/f1d0365a6f72b88f7427814f636863ae1656f72a/demux/demux.c#L4561-L4579
mp_charset_guess and mp_iconv_to_utf8: https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/misc/charset_conv.c#L95-L242

**Comment by decent-name** [comment]
It's a feature, not a bug.

**Comment by jeeb** [comment]
For the record, the first thing I highlighted to this user on IRC, and then later even the GNOME people themselves apparently noticed - is that some application killing your window management by sending out an invalid UTF-8 string as the window title is not something that should happen. So I hope the user followed up on his word and did what also the GNOME people in the end requested and filed a bug on that side, as that is quite definitely the higher priority side with this issue. They already apparently validate the string (possibly accidentally), and just fail to catch an error/exception.

Otherwise, I just think that if we expect a thing to be UTF-8, that we might want to just validate/sanitize it when passing/exposing it. But I am also acutely aware that it should be somehow limited to cases where that is needed, as in various places we might need/want to have the exact original binary string (such as in file paths. f.ex.). A "nice to have" if it can be somehow nicely implemented (one could split attributes/properties to printable/non-printable stuff but it just doesn't sound like the greatest idea).

Until then the clearest thing is to catch it in those places where it gets passed on to whatever interface specifies UTF-8, and then you have that case improved. The less than nice part of that would then be that you are then playing whack-a-mole figuring out which things require it, and which don't :) .

**Comment by decent-name** [comment]
> and then later even the GNOME people themselves apparently noticed - is that some application killing your window management by sending out an invalid UTF-8 string as the window title is not something that should happen.

To be honest, that surprises me.

> Otherwise, I just think that if we expect a thing to be UTF-8, that we might want to just validate/sanitize it when passing/exposing it. 

Maybe. You could argue it's sane and reasonable not to send corrupted UTF-8 when it's not expected. On the other hand, the problem starts with the fact that not everyone agrees with how "valid UTF-8" is defined. mpv has a ``bstr_decode_utf8`` function, and it has a comment about libavcodec (using the "toxic" word "retarded", well, fuck you), which, in my opinion, demonstrates how the definition of "strictly valid UTF-8" varies across software. Some software has  stricter definition, some is looser out of necessity. Take Python: it has A "trick" to encode invalid UTF-8 as equally invalid UTF-8 for the sake of compatibility with Linux filesystem byte strings (https://www.python.org/dev/peps/pep-0383/). This blows up with some other Python 3 libraries or bindings. This leads me to believe that my opinion to just accept any byte sequence is correct. I'm a fan of "fail early", but this really shouldn't apply to stuff like filenames.

> Until then the clearest thing is to catch it in those places where it gets passed on to whatever interface specifies UTF-8, and then you have that case improved. The less than nice part of that would then be that you are then playing whack-a-mole figuring out which things require it, and which don't :) .

Indeed. To be fair, in  the x11 case, UTF-8 is even explicitly specified though. mpv doesn't make an effort here, except for libvcodec subtitle input (which was enforced by a certain person who probably still haunts the FFmpeg project to this day).

**Comment by jeeb** [comment]
> > Otherwise, I just think that if we expect a thing to be UTF-8, that we might want to just validate/sanitize it when passing/exposing it.
> 
> Maybe. You could argue it's sane and reasonable not to send corrupted UTF-8 when it's not expected. On the other hand, the problem starts with the fact that not everyone agrees with how "valid UTF-8" is defined. mpv has a `bstr_decode_utf8` function, and it has a comment about libavcodec (using the "toxic" word "retarded", well, fuck you), which, in my opinion, demonstrates how the definition of "strictly valid UTF-8" varies across software. Some software has stricter definition, some is looser out of necessity.

Yup. That is why I am not having a glare in my eye and talking about how everything should be Right without knowing what that actually looks like (like those who have just learned an ism they really like, but haven't yet seen how the sausage gets made). Reality tends to be much more of a grey place than that.

> Take Python: it has A "trick" to encode invalid UTF-8 as equally invalid UTF-8 for the sake of compatibility with Linux filesystem byte strings (https://www.python.org/dev/peps/pep-0383/). This blows up with some other Python 3 libraries or bindings. This leads me to believe that my opinion to just accept any byte sequence is correct. I'm a fan of "fail early", but this really shouldn't apply to stuff like filenames.

Ayup. I think we are pretty much on the same page here, and that's why I did mention paths as an example.
 
> > Until then the clearest thing is to catch it in those places where it gets passed on to whatever interface specifies UTF-8, and then you have that case improved. The less than nice part of that would then be that you are then playing whack-a-mole figuring out which things require it, and which don't :) .
> 
> Indeed. To be fair, in the x11 case, UTF-8 is even explicitly specified though. mpv doesn't make an effort here, except for libvcodec subtitle input (which was enforced by a certain person who probably still haunts the FFmpeg project to this day).

Yup. I wonder if `mp_iconv_to_utf8` configured as UTF-8 -> UTF-8 (possibility utilizing the `UTF-8//IGNORE` alternative in case the replacement characters are not wanted) would do it, possibly either:

1. When initializing the x11 window + VOCTRL_UPDATE_WINDOW_TITLE event.
2. During `vo_x11_update_window_title`, as that's more or less the only place that needs it.

**Comment by decent-name** [comment]
> mp_iconv_to_utf8 configured as UTF-8 -> UTF-8 

mpv has that as bstr_sanitize_utf8_latin1.

> During vo_x11_update_window_title, as that's more or less the only place that needs it.

Maybe GNOME should just fix their bug.

**Comment by avih** [comment]
For what it's worth, IMHO, unless mpv knows for a fact that the string it uses for the title should adhere to some standard, then it should not transform it.

In this case I think it's clearly the task of the WM or whoever uses this value to decide for themselves whether they can use this string without blowing up. Different consumers might validate it differently, and we probably don't want to venture into transforming it by guesswork and without a clear standard to adhere to.

**Comment by jeeb** [comment]
Well, in this case it's:

0. Not sure if I have to mention this, but just in case. I am not talking about transforming the actual internal "global" title attribute/property/whatever.
1. (in my opinion) this is not a clear problematic case like a file path. It's a window/icon title.
2. something we clearly pass it as-is as `UTF8_STRING` (and `Xutf8TextListToTextProperty`/`XSetTextProperty`).
3. Possibly me being overly optimistic on that just passing something through iconv or so will strip out UTF-8 code points generally considered invalid, since clearly you feel that there's a way high enough risk of it ending up interpreted "invalid" anyways. I do agree that if there's an arms race, then at that point it's OK to raise your hands and note that the different sides sort it out.

I think I have gone into enough specifics in the earlier posts that I agree that the problem on a global level is probably not easily solvable, and a response of such style is completely OK. Also I do not consider this a high priority thing on mpv's side. Just that the response of _"it's a feature"_ prompted me to write something since clearly things were being seen differently.

To explain my view in other sorts of words:
_"I just saw two people dancing together, and both doing something wrong. One on a much more worse level, and another with something minor."_

Thus I:
1. Attempted to make sure that the first thing got reported (and it seems to be getting fixed),
2. Accepted that a bug report could be raised here as well. Which I don't think is completely bonkers.

But if people disagree, I am fine with that. I'd just like to understand the logic behind it.
