### ISSUE TITLE
Opening a media file that is currently being written to (in realtime) at the latest start time.

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#8829]
I'll be hosting and streaming a live games tournament tonight involving several players, I'll also be recording the broadcast to my harddrive for YouTube.

I thought it might be useful to use the recording as a way to verify possible disputes or things I might have missed in the moment (difficult to keep track of several players at once!)

Currently, if I open the MKV file being recorded to by OBS, the OSD shows the time left as -00:00:01, as the duration increases with playback, but it doesn't show the full recorded duration thus far.
If I use the keys to seek towards the end it'll often stall completely or close.

I've tried the following: 

```mpv --keep-open=always --start=99999999999 "2021-05-14 11-50-58.mkv"```

It opens paused on the last frame, without any user input it remains there indefinitely.
However, if I seek backwards 5 seconds and manually un-pause, it does begin playing.

Just wondering then if there might be a slightly better way of doing this?

**Comment by decent-name** [comment]
Written files trigger an "appending mode", which you can see on the terminal. Should work relatively well with mkv, but is somewhat unreliable because it's a heuristic than can disable itself any time. Using `appending://2021-05-14 11-50-58.mkv` might make it slightly more robust (it won't terminate itself not even if the writer actually stops).

> --start=99999999999

This will really try to seek to this position. Since the file is being appended to, the seek index is not available, and it will rightfully wait until it's done.

You can instead enable the cache with `--cache`. If the cache is configured large enough, the cache will read the entire file until the current end, so the OSC can show you where the cached range currently ends. (You could enable the disk cache if the file is going to be large; stupidly that will use twice the disk space, but at least it works.)

**Comment by Akemi** [comment]
@decent-name since avih voiced his concerns of me just barging in on 'your' issue, since even though you answered the question you could have closed it yourself if you didn't intend to do anything more.

should this question be kept open or are you fine with it being closed?

**Comment by decent-name** [comment]
It doesn't really matter.
