### ISSUE TITLE
Support wlr-layer-shell (Wayland)

### ISSUE THREAD

**Issue by hyarsan** [mpv-player/mpv#8830]
### Expected behavior of the wanted feature
I want mpv to have a way to open itself as a desktop background via [wlroots Layer Shell], for Wayland.
This way, we can have animated wallpapers that take advantage of mpv's hardware acceleration and other awesomeness.
Whether it should be able to be interacted with could be a setting, probably.

[wlroots Layer Shell]: https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-layer-shell-unstable-v1.xml

**Comment by Dudemanguy** [comment]
Ideally mpv would only support upstream protocols (wayland-protocols) and not have to rely on any compositor specific ones. That said, wayland-protocols moves like molasses so maybe one day I'll break this rule. As for the usecase here (animated wallpapers), that doesn't really seem like an appropriate feature for mpv. I think a better idea would be to use libmpv and build a separate program that does this for wlroots/sway using the protocol you mentioned here. Maybe one already exists.

**Comment by hyarsan** [comment]
just found this: https://github.com/GhostNaN/mpvpaper

**Comment by Quackdoc** [comment]
I wonder if it could be worth revisiting this or rather instead of wlr_layers, the draft protocol based on it maybe? with the draft protocol seeming to be getting somewhat more attention as of late. While I think using it as a background is really cool, I personally would like if ontop would work again on wayland, since doing it via compositor is not always a good experience if it is possible in the first place. 

assuming the draft PR for ext-layer-shell would be accepted into wayland, would that be on the table for adding explicit layer support then?

https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28

**Comment by Dudemanguy** [comment]
Sure if that would let us get ontop support in a reasonable way that would be fine with me. Just glancing at it, it appears to support that concept (the `top` layer).
