### ISSUE TITLE
Return to the beginning of the file

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#8843]
I was trying to binding the _Home key_ to the beginning of the video, like MPC-HC works, if you are watching a video and press _Home key_ the video start again.
I use in input.conf
**Home start=00:00:00**
and I also tried
**Home script-binding start=00:00:00**
But don't work, any idea?

**Comment by Akemi** [comment]
find out what the key name is for home with, the key name will appear in the upper left corner:
```
mpv --input-test --force-window --idle
```

bind the key to to your home key (replace X), leave the equal sign out since it's not an option or property:
```
X seek 0 absolute
```

example bindings can be found here with comments and explanations, those are the default bindings (# needs to be removed): https://github.com/mpv-player/mpv/blob/master/etc/input.conf
possible input command can be found here, including an explanation of the seek command: https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst

**Comment by jimmy-1000** [comment]
Thanks !! It works.
