### ISSUE TITLE
With Pipewire, if I rapidly move to another part of the video, the audio is distorted for some seconds.

### ISSUE THREAD

**Issue by All3xJ** [mpv-player/mpv#8861]
### Important Information

Provide following Information:
- Version: mpv 0.33.1-dirty
- Distro: archlinux
- Source: archlinux official repos
- Window Manager: mutter 40.1
- GPU driver and version: xf86-video-amdgpu 19.1.0-2 (?)
- Possible screenshot or video of visual glitches: https://streamable.com/imbk40

### Reproduction steps

starting with --no-config does not make difference.

i have Pipewire installed. Since I switched to Pipewire I have this issue. Basically you have to open a video and then go with right or left arrow in another point of the video.

### Actual behavior
Audio is distorted

### Log file

https://0x0.st/-eh3.txt

**Comment by paulguy** [comment]
I seem to have a similar issue since switching to Pipewire, but it's basically always reproducible by back stepping some then unpausing and it becomes similarly juicy crackles.  I haven't extensively tries a bunch of stuff to narrow it down though so I never bothered to say anything but if there's some corroborating and more information needed I could probably try some stuff.

**Comment by debiangamer** [comment]
mpv 0.32.0 and vlc 3.0.12 works fine  with pipewire master so there is a regression in mpv.

**Comment by fartsniffer104** [comment]
First bad commit https://github.com/mpv-player/mpv/commit/b74c09efbf7c6969fc053265f72cc0501b840ce1

**Comment by fartsniffer104** [comment]
https://github.com/mpv-player/mpv/issues/8510

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/841#note_940993

**Comment by All3xJ** [comment]
> #8510
> 
> https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/841#note_940993

it seems to be fixed now after updating
