### ISSUE TITLE
Discuss: default subtitle behavior

### ISSUE THREAD

**Issue by rcombs** [mpv-player/mpv#8863]
The current defaults are probably not what the user wants in the majority of cases, and we can do better:

- `slang` should almost certainly default to the user's UI language (derived from `LANGUAGE`, `LC_ALL` or `LANG` on Linux, `CFLocaleCopyPreferredLanguages` on macOS; not sure on Windows?) rather than nothing
  - These generally return 2-component IETF language tags, which need everything past the `-`/`_` trimmed to get an ISO language identifier
  - We should probably make an attempt to convert between 2-char and 3-char codes here… since unfortunately files use both
- `subs-with-matching-audio` should probably default to `no`, as most playbacks of user's-language content don't require subtitles
- Similarly, if no subtitle track matches `slang`, we probably shouldn't play a track that _doesn't_ match just because it has the default flag
  - Maybe we should, however, assume that a subtitle track with _no_ language set _is_ in the user's language?
- Current behavior (since c9474dc) when no subtitle track matches the audio language is somewhat inconsistent when the default track is also a forced track. We should probably:
  - Remove the `&& !pick->forced_track` from `select_default_track`
  - Possibly also remove `&& !pick->default_track`?
  - Add an option to make `select_fallback` always apply
  - Add an option to always prefer forced tracks (even when the language doesn't match)

Any thoughts? The default `slang` in particular should be pretty significant.

**Comment by DanOscarsson** [comment]
Here are some things I would like to have without looking at what works today.
Many things need to have an option to allow the user to select their preference.

- if user does not want any subtitles shown by default, none should be selected
- only subtitles in languages the user understands/wants should be selected
- if audio language matches a language the user understands well (may be more then one) a subtitle should not be selected except if a forced track exists in same language (as they are expected to be for foreign parts). Note that the user may have languages they understand well and do not need subtitles and they may have other languages they understand the audio but still want subtitles for it.
- prefer non SDH track over SDH track
- prefer normal track instead of forced track if track is not a language the user understands
- do not select commentary tracks unless audio is commentary
- select external tracks before internal
- select .srt before .ass and select text subtitles before image subtitles

For tracks without a language defined, should we assume a language?
A default `slang` is not that easy to take from UI language. I have friends using English as UI language while native language is something else.

**Comment by avih** [comment]
> subs-with-matching-audio should probably default to no, as most playbacks of user's-language content don't require subtitles

> if audio language matches a language the user understands well (may be more then one) a subtitle should not be selected except if a forced track exists in same language

I can't speak for others, but personally my system language is English, most of the content I watch is English - and I still prefer with subtitles. Because it helps if some of the audio is not clear, or if using low audio volume at night, etc.

So personally I'd prefer it enabled by default, though that's just one datapoint.

**Comment by rcombs** [comment]
> I can't speak for others, but personally my system language is English, most of the content I watch is English - and I still prefer to watch with (English) subtitles. Because it helps if some of the audio is not clear, or if using low audio volume at night, etc.

There are plenty of people in this use-case for sure, but I'm fairly confident it's not a majority (I checked Plex's telemetry and subtitles are used in <25% of playbacks). You can set `subs-with-matching-audio=yes` in your config if you want this, just, _most_ playbacks don't, and that's what defaults are meant to target.

After some discussion on Discord, we concluded that another heuristic is probably useful by default:
If no subtitle stream matching `slang` is found, but there's a forced subtitle stream matching the selected audio track's language, we should default to that.

@DanOscarsson Agreed on most of these points (though some of them are basically just the `subs-with-matching-audio` pref). SDH-vs-non-SDH should be easier now that Matroska has a flag for that; same with commentary.

**Comment by TheDevilsHyper** [comment]
I don't know about any of that technical stuff and all but listen to me just once.

I do not want to use slang and alang to set priority I just an mkv to play just like it's supposed to be which is play default and/or forced subs/audio and if they aren't marked default then just don't play (setting a priority order/using slang and alang shouldn't really be compulsory) I've never used plex in my life and I don't even plan to, plus I don't think mpv is only used by plex users.


I don't care about the changes which happen in mpv but I don't think not playing default and forced subs is really a good choice if slang and alang aren't even in my conf. My mpv plays default subs well but problem occurs when those default one are marked as forced subs too (for me).

for example
![xsMnAT](https://user-images.githubusercontent.com/68007236/119859651-34806880-bf33-11eb-8064-2f2f206f3745.jpg)


In the screenshot above there are multiple subs present in it but none of them is marked as default and/or forced. So, not playing any of them is normal unless I have slang=eng in my conf


![0oLtKl](https://user-images.githubusercontent.com/68007236/119860375-df912200-bf33-11eb-9e7b-b3673fa18d9b.jpg)
Now in this one there is only one sub and marked as default only so it plays that default marked sub (even if there were multiple subs the result would still be the same).



![D4bgcG](https://user-images.githubusercontent.com/68007236/119860731-431b4f80-bf34-11eb-9875-fbd3db10b430.jpg)
And now in this one Video, eng audio, eng (Signs and Songs) are marked as default and forced now video and audio plays but sub doesn't. That is my issue and I was trying to seek some help and got roasted for on discord.


Any mpv version > or = 3.2.x plays them just fine.


I don't know what "logic" was everyone talking about since slang and alang are supposed to be priority orders for the sake of simplicity (I guess) not compulsory to play mkv.

**Comment by rcombs** [comment]
Please actually read the suggested changes, and don't comment on random irrelevant stuff. This GHI aims to _solve_ most of the issues you're describing, and the rest are down to your configuration being incorrect for your use-case.

**Comment by ValZapod** [comment]
FFmpeg still need to apply https://patchwork.ffmpeg.org/project/ffmpeg/patch/CAB0OVGp=Xi=X2x139VnvLyE6fZLkj2YQRWXGEMMYV+Yfe3uA2w@mail.gmail.com/

**Comment by lilydjwg** [comment]
Other than trying to be better by default, is there a way to specify in the config file that which `slang`s are preferred?

**Comment by rcombs** [comment]
`slang` is an option; you can configure it like any other. This already works as-is.

**Comment by lilydjwg** [comment]
Thanks! I searched for `sub` and didn't see it.
