### ISSUE TITLE
Detecting if the current stream is live? (e.g. a live youtube stream)

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#8864]
In my lua script I need to know if the currently playing file is live, whereby the duration is continually growing.
I need to distinguish between a live source and a regular youtube video or remote/local file.

I can do this by checking if the duration value increases but this takes time.
Or I can check if the format is HLS, but I'm not sure if this is a catch-all solution for all live streams.

What's the surest way of detecting this?

**Comment by CounterPillow** [comment]
I think checking the property `seekable` might be an indicator too, if a stream is not seekable it's a livestream.

**Comment by hedgehog90** [comment]
> I think checking the property `seekable` might be an indicator too, if a stream is not seekable it's a livestream.

Not sure about that, if I open a youtube live stream I can seek backwards, so I would assume 'seekable' is true.

**Comment by TheAMM** [comment]
`seekable` should be a valid indicator. You can seek within cache with seekable being false. Check in console yourself if you want to: `show-text ${seekable}`

You can also easily detect youtube-dl by comparing `path` and `stream-open-path`,  since other `stream-open-path` hooks are currently rare. (It would be neat to have a small key-value storage for scripts to set flags or share state, but I digress)

**Comment by hedgehog90** [comment]
OK, didn't realise the property 'seekable' didn't actually mean 'seekable' :)
Got my script working now, thanks!

**Comment by sfan5** [comment]
If you want to disregard the cache additionally take a look at the `partially-seekable` property.

**Comment by ValZapod** [comment]
But youtube-dl still does not support VP9 live streams...
