### ISSUE TITLE
How to change only one Style for .ass subtitle file?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#8870]
Hi,

I did found about sub-ass-force-style and profile-cond= option today and about mine question I think I could better explained with examples . Sorry for mine bad English.

So I have a .ass subtitle file and in subtitle there are multiple **Style:**

Format:Name, Fontname....
Style: Sub no 1,
Style: Sub no 2,
Style: Sub no 3,

How can I only change `Sub no 2` and keep the other two untouched? 
I want only to give `Sub no 2` a different look.

```
Mine mpv.conf :

[Movie]
profile-cond=string.match(get("filename", ""), "Movie")~=nil
sub-ass-force-style='Fontname=Arial,Fontsize=60,PrimaryColour=&H00FFFFFF,SecondaryColour=&H0000FFFF,OutlineColour=&H00000000,BackColour=&H7F404040,Bold=-1,Italic=0,Underline=0,StrikeOut=0,Spacing=0,Angle=0,BorderStyle=1,Outline=6,Shadow=3,Alignment=2,MarginL=60,MarginR=60,MarginV=66,Encoding=0'
```

**Comment by Akemi** [comment]
https://mpv.io/manual/master/#options-sub-ass-force-style `--sub-ass-force-style=<[Style.]Param=Value[,...]>`

the options lists a `Style.` before the parameter. so i would guess it would be sub-ass-force-style='STYLE_NAME.Fontname=Arial' for example.

**Comment by erickyun** [comment]
> https://mpv.io/manual/master/#options-sub-ass-force-style `--sub-ass-force-style=<[Style.]Param=Value[,...]>`
> 
> the options lists a `Style.` before the parameter. so i would guess it would be `sub-ass-force-style='STYLE_NAME.Fontname=Arial'` for example. you just need to get the style name.

I tried like this
 but **sub no 1** and **sub no 3** do get changed too it didn't work for only **sub no 2** ?

Mine mpv.conf :

[Movie]
profile-cond=string.match(get("filename", ""), "Movie")~=nil
sub-ass-force-style='Sub no 2.Fontname=Arial,Fontsize=60,PrimaryColour=&H00FFFFFF,SecondaryColour=&H0000FFFF,OutlineColour=&H00000000,BackColour=&H7F404040,Bold=-1,Italic=0,Underline=0,StrikeOut=0,Spacing=0,Angle=0,BorderStyle=1,Outline=6,Shadow=3,Alignment=2,MarginL=60,MarginR=60,MarginV=66,Encoding=0'

**Comment by Pazu5512** [comment]
Hi, I'll bump this recent closed ticket as my question is directly related to erickyun's question + the answer provided by Akemi, and is not worth opening a new one. So...
> 
> 
> https://mpv.io/manual/master/#options-sub-ass-force-style `--sub-ass-force-style=<[Style.]Param=Value[,...]>`
> 
> the option lists a `Style.` before the parameter. so i would guess it would be `sub-ass-force-style='STYLE_NAME.Fontname=Arial'` for example. you just need to get the style name.

... let's say one of the sub style is named "Character XYZ Dialogue", a simple `sub-ass-force-style='Character XYZ Dialogue.Fontname=Arial'` will override that particular style with the Arial font, and it works fine. 

But what if I want it to be a bit more dynamic, and work if the style name contains the word "Dialogue" instead of using a fixed style name? That way it would work for the "Character XYZ Dialogue" style as well as for a "Character ABC Dialogue" style.

I tried with %, * or other usual wildcard characters, but couldn't make it work. Is it even possible to make such a thing work in that option list?

**Comment by Akemi** [comment]
it's not possible. i don't think libass supports something like this and would need to add support for wildcard style names.

**Comment by Pazu5512** [comment]
All right, thanks for your answer. In a way, I'm relieved to know it's not possible, as I was scratching my head at what the hell I was doing wrong with my wildcards tries :relaxed:
