### ISSUE TITLE
How do I install youtube-dl on linux?

### ISSUE THREAD

**Issue by 5271** [mpv-player/mpv#8926]
I'm using Linux Mint and I'm trying to install mpv player on it. I installed the player from Software Manager but I couldn't find a way to install youtube-dl in order to play videos from URLs.
How do I do that?

**Comment by garoto** [comment]
http://ytdl-org.github.io/youtube-dl/download.html

**Comment by 5271** [comment]
i did these commands:
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

sudo chmod a+rx /usr/local/bin/youtube-dl

and there was no error.
But it still doesn't work and i get this error
[ytdl_hook] /usr/bin/env: ‘python’: No such file or directory 
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
Failed to recognize file format.

I have Python 3 installed.
What am I doing wrong?

**Comment by CounterPillow** [comment]
Your distribution's python3 package doesn't have a symlink for "python" to python3.

Please do not do what garoto said, instead, try installing youtube-dl from your distribution
```
# remove our local thing
sudo rm /usr/local/bin/youtube-dl
# install from the distro packages
sudo apt install youtube-dl
```

**Comment by 5271** [comment]
I've done what you said and now I get a different error.

[ytdl_hook] ERROR: BAw1isoV8ic: YouTube said: Unable to extract video data 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 
Failed to recognize file format.

**Comment by garoto** [comment]
The `youtube-dl` version on Ubuntu repos is awfully outdated.

**Comment by 5271** [comment]
So what should I do?

**Comment by garoto** [comment]
Well I'm on Windows, but If I used Loonix as my daily OS, I would use the `curl` method and then create a symlink to the distros's native python3.x binary in my `~/bin/` dir (`ln -s /usr/bin/python3.9 ~/bin/python`) to avoid messing with the distro-wide python setup.

**Comment by 5271** [comment]
I did what u said but nothing changed/still have the same error.

**Comment by rubyFeedback** [comment]
You can try e. g. https://github.com/ytdl-org/youtube-dl/releases/download/2021.06.06/youtube-dl-2021.06.06.tar.gz

download it, extract, then try to install it; run setup.py there. This should work. It works on my system.

With distributions it can be annoying because sometimes you are missing stuff that isn't instantly obvious.

I always compile from source so I avoid distribution-specific annoyances (but admittedly it is more work to do so, so this is a trade off).

Try to download some other files and see whether that works; perhaps your ffmpeg/mpv version is also old. Try to get all the versions of these, and put them into a text file, and perhaps show where and how you obtained these, then give that information to the issue tracker - I am sure people can give more help the moment they know more about your setup. You can be sure that others will 100% have made it work even on e. g. debian and what not.

You can also request the mpv team to add some more information to a FAQ or the wiki, so that this may then become useful for other folks in the future.

**Comment by 5271** [comment]
I downloaded what you sent and did some stuff and it works! Huge thanks!
