### ISSUE TITLE
mpv caps download speed when streaming from sftp server

### ISSUE THREAD

**Issue by siferati** [mpv-player/mpv#8961]
### Important Information

Provide following Information:
- mpv version 0.33.0
- Windows 10 Pro 1909
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/

### Reproduction steps

`mpv sftp://user:pass@domain/file.mkv`

### Expected behavior

Video is streamed from sftp server at max bandwidth capacity.

### Actual behavior

Video stream is capped at ~18 Mbps.

### Additional Context

If I **download** the file from the sftp server, the network bandwidth is **fully used**. But when **streaming** the file through mpv, it only uses ~18Mpbs. Why is mpv capping the download speed when streaming and how can I fix it?

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/6719949/output.txt)

**Comment by avih** [comment]
The actual network access is performed by ffmpeg, and mpv doesn't try limit the rate (I don't know if ffmpeg has an API for that), however, mpv does have a limited prefetch buffer size, so if that buffer gets filled, then mpv will not request ffmpeg to fetch more.

Does it still happen with `--demuxer-max-bytes=4G` ? (this will increase the buffer size from 200M to 4G).

**Comment by siferati** [comment]
> Does it still happen with `--demuxer-max-bytes=4G` ? (this will increase the buffer size from 200M to 4G).

Yup,  the problem remains.

**Comment by avih** [comment]
> it only uses ~18Mpbs

What IS the maximum bandwidth you expect?

**Comment by siferati** [comment]
> What IS the maximum bandwidth you expect?

I'm expecting mpv to stream at the same speed I get when downloading directly from the sftp server, which is around ~50Mbps. Streaming through mpv is not even giving me half of that.

**Comment by avih** [comment]
> Why wouldn't the download speeds be the same?

Assuming it's not limited by mpv buffers (since you reported that `--demuxer-max-bytes=4G` didn't help), then It's possible that the sftp protocol implementation used by ffmpeg is limited in some ways. I don't have ideas other than this.

> streaming through mpv is not even giving me half of the download speed I get when downloading directly from the sftp server.

Out of curiosity, why does that matter to you? Is playback stuttering? Does mpv pause sue to buffering?

**Comment by siferati** [comment]
> Out of curiosity, why does that matter to you? Is playback stuttering? Does mpv pause due to buffering?

Yup, that's exactly my problem -- constant buffering because of the slow streaming speed.

**Comment by avih** [comment]
> Yup, that's exactly my problem -- constant buffering because of the slow streaming speed.

Assuming the file does play without stuttering if you first download it to local storage and then play it locally in mpv (please do confirm that is indeed the case), then it sounds to me like an ffmpeg issue, and I don't think mpv can do anything about it...

**Comment by siferati** [comment]
> Assuming the file does play without stuttering if you first download it to local storage and then play it locally in mpv (please do confirm that is indeed the case), then it sounds to me like an ffmpeg issue, and I don't think mpv can do anything about it...

Yeah that's the case. Also, if I wait a bit before playing in order to give time for the cache to build up then mpv plays fine (until it eventually catches up to the cache).

**Comment by avih** [comment]
> Yeah that's the case. Also, if I wait a bit before playing in order to give time for the cache to build up then mpv plays fine (until it eventually catches up to the cache).

Right, then so far it does sound to me like either an sftp issue in ffmpeg, or a specific file issue which requires ffmpeg to seek to the end of the file before playback can begin (or periodically), or maybe an sftp server issue with seeking to an arbitrary position at the file, or maybe just a combination of the specific file (which needs seeking) and the protocol - not sure if the [s]ftp protocol (or specific server) supports seeking, unlike most http servers for instance.

Also, is the log you attached initially taken where such issues happen? As far as I can tell this log doesn't show buffering or other playback issues.

It does seem to take long to start (11 s), possibly because ffmpeg needs to seek to the end of the file (1.8G) to read some attachment (fonts?), but then until you quit (around 22 s), I don't think I can recognize any playback issues...

Can you try with other players (e.g. vlc) which support sftp?
Can you try with an http server instead of [s]ftp?

**Comment by avih** [comment]
Also, where did you get that 18Mbps number from? observing network usage with some network monitor?

And how did you accomplish 50Mbps with the same file on the same ftp server? Is it possible you downloaded it with some program which supports "download acceleration"? (requests different parts of the file in parallel)? If yes, can you limit it to just one part and try again? (ffmpeg doesn't do parallel download).

**Comment by avih** [comment]
At shis stage though, I'm quite convinced the issue is outside the control of mpv, and it's some combination of general network issues and/or specific-file issues and/or sftp server issues and/or ffmpeg sftp issues.

Regardless, it would still be nice to figure out the discrepencies.

**Comment by siferati** [comment]
> Also, is the log you attached initially taken where such issues happen? As far as I can tell this log doesn't show buffering or other playback issues.

The log I attached does have the bandwidth cap, but there is no buffering -- the ~18Mbps are enough to play this specific file. When I tried on a different network the cap was lower than 18Mbps and it buffered a lot, to the point where it was unplayable. I'll get you a log of that network and the buffering issues later today.

>  read some attachment (fonts?)

The mkv file does have a lot of font attachments.

> Also, where did you get that 18Mbps number from? observing network usage with some network monitor?

I used Windows's built-in Resource Monitor to measure network usage when using mpv and when using sftp.

> And how did you accomplish 50Mbps with the same file on the same ftp server?

Using OpenSSH client for Windows 10:

1. `sftp user@domain`
2. type password
3. `get file.mkv`

**Comment by avih** [comment]
> the ~18Mbps are enough to play this specific file. When I tried on a different network the cap was lower than 18Mbps and it buffered a lot

Is it the same file?
With this different network, does downloading outside of mpv still achieves 50Mbps?
Please attach a log where the (playback) issues actually happen.

**Comment by siferati** [comment]
> Can you try with other players (e.g. vlc) which support sftp?

I tried with VLC and the problem does **not** happen -- VLC uses the whole bandwidth unlike mpv.

> Is it the same file? With this different network, does downloading outside of mpv still achieves 50Mbps?

Yes and yes.

> Please attach a log where the (playback) issues actually happen.

I'll do that in a few hours once I have access to that network.

**Comment by avih** [comment]
It seems that ffmpeg uses libssh for sftp - https://ffmpeg.org/ffmpeg-protocols.html#libssh

And your build - from shinchiro does build and use libssh - https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/libssh.cmake

So I would say the issue is probably at libssh. It does look like libssh had sftp performance issues - https://bugs.libssh.org/T89 but I don't know if that's still the case currently.

Either way, it looks to be an issue at libssh or between ffmpg and libssh, and definitely outside the control of mpv.

I'll close this issue now, but you can still post further logs or info, and we can re-open it in case it does turn out to be an mpv issue.

**Comment by garoto** [comment]
My solution to streaming media with mpv and the `ssh` protocol on Windows is to install [sshfs-win](https://github.com/billziss-gh/sshfs-win) and then mount a network share via e.g. `net use P: "\\sshfs\root@192.168.1.250"`, and then mess with `--stream-buffer-size=` values, because by default the thoughput will be equally as bad as the libssh+ffmpeg implementation, specially with high latency connections (~210ms).

**Comment by siferati** [comment]
> My solution to streaming media with mpv and the `ssh` protocol on Windows is to install [sshfs-win](https://github.com/billziss-gh/sshfs-win) and then mount a network share via e.g. `net use P: "\\sshfs\root@192.168.1.250"`, and then mess with `--stream-buffer-size=` values, because by default the thoughput will be equally as bad as the libssh+ffmpeg implementation, specially with high latency connections (~210ms in my case).

That's exactly the situation I'm in, trying to stream something halfway across the globe. I tried following your approach of using sshfs-win but the results are still bad. What values are you using for `stream-buffer-size`?

I measured the speeds today and I managed to download the file from the SFTP server at 4~5 Mb/s -- let's assume this is the maximum possible value for the download speed.

When streaming through sshfs-win using the default `stream-buffer-size` I get around 150~300 KB/s. By setting `stream-buffer-size=2048Kib` the speed increased to 600~700 KB/s, but that's still nowhere near the regular SFTP speed, and not enough for the video to not stutter.

Here's the logfile (please excuse all the syncplay garbage logs):
[output.txt](https://github.com/mpv-player/mpv/files/6912749/output.txt)

**Comment by garoto** [comment]
`--stream-buffer-size=14M` yields around 7.4MiB/s and that seems to be the cap with the option and  with my setup.

> By setting stream-buffer-size=2048Kib the speed increased to 600~700 KB/s [...]

For reference, using `--stream-buffer-size=2048Kib` I get ~3.8MiB/s.

**Comment by debug686** [comment]
Hello! Can we explore this again? In my testing it seems like there is a bottleneck here, that sits at around 3.8MiB/s, which is about 1/5 the speed of the network I'm testing this on. (And unfortunately just below the magical industry standard 4.3MB/s (4.5 with audio) of physical media)

The number of about 3.8MiB/s has also been reported earlier in this thread.

Just to be clear: The bottleneck is not that the buffer is filling at 3.8MiB/s because the network bandwidth is maxed out. It's that the network is only used at 3.8MiB/s, when it could be going about 5x that fast. Nothing else is maxed out here. CPU, GPU, Network, Host, Client. Everything seems underutilized. 

I have experimented with different values for stream-buffer-size, and have not managed to get above the 3.8MiB/s. If the exact speeds at different values are of any help, I can document them and make a table.

**Comment by debug686** [comment]
> Is it possible you downloaded it with some program which supports "download acceleration"? (requests different parts of the file in parallel)? If yes, can you limit it to just one part and try again? (ffmpeg doesn't do parallel download).

This may be the key issue here. I tested it with a single request at any one time with `sftp -R 1`, and sftp the used connection bandwidth was just a little fast than what mpv uses.

Is using ffmpeg to fetch a single request at a time a hard limitation? Can multiple ffmpegs fetch multiple requests at the same time? Is using ffmpeg for networking the best way to do sftp networking (instead of using sftp into a buffer, then use ffmpeg to read from the buffer)?

**Comment by debug686** [comment]
I did tests on a faster network, where I saw a bandwidth reduction of about 1/3 over using sftp directly. So I'm guessing an improvement in how mpv fetches data over sftp can give a speed improvement of about 3-5x depending on the network.
