### ISSUE TITLE
have larger limits for pan & scan

### ISSUE THREAD

**Issue by marcespie** [mpv-player/mpv#8974]
I regularly use mpv to look at pictures
I know that it's not its primarily intended use, but with --loop-file=inf, it works just fine for that.

I frequently run into pan&scan arbitrary limitations. Any reason to limit the option to the 0.0, 1.0 range ?  I've compiled it with M_RANGE(0.0, 3.0) and so far, it works perfectly !

**Comment by occivink** [comment]
It sounds like you're using pan & scan for zooming purposes. `video-zoom` should work better for that, and can be combined with `video-pan-x` and `video-pan-y` for moving the image around.

**Comment by marcespie** [comment]
indeed! somehow I missed that... works fine :)

**Comment by occivink** [comment]
For what it's worth I have some scripts for using mpv to view images
https://github.com/occivink/mpv-image-viewer

**Comment by marcespie** [comment]
oooh nice.
not usually a fan of lua, but I might have a go on those.

**Comment by eugenesvk** [comment]
Would you please reopen the issue as I have the same use case and 3 isn't enough for screenshots, especially "tall/narrow" ones, to make panning reach the screen's side you have to make them too large, otherwise they can easily be panned out of the screen at the top/bottom, but not even reach the screen left/right

The proper solution is still to either remove the arbitrary -3/3 limits or somehow make them "smart" so that they depend on not just the picture size, but also the screen size (but practically would accept any number as input)
