### ISSUE TITLE
Strange vertical sync issue.

### ISSUE THREAD

**Issue by StephVD** [mpv-player/mpv#8988]
Hi everyone,

I am facing a strange problem when I run mpv with a playlist. Example :

In terminal :

`mpv --hwdec=cuda-copy --screen=1 --fs-screen=1 --quiet --loop-playlist --no-input-default-bindings --no-border  'video1' 'video2' 'video3' 'video4'`

Result : video1, video2 and video3 works perfectly. video4 has a vertical synchronization problem (video is cut off by a line in the center of the screen).

Now i use the same videos but in reverse order. Example

In terminal :

`mpv --hwdec=cuda-copy --screen=1 --fs-screen=1 --quiet --loop-playlist --no-input-default-bindings --no-border  'video4' 'video3' 'video2' 'video1'`

Result : video4, video3 and video2 works perfectly. video1 has a vertical synchronization problem (video is cut off by a line in the center of the screen).

I have tried other videos with different resolutions and encoders, the result is always the same.

My configuration :

- Ubuntu 20.04, Xorg, dual screen (screen 0=desktop, screen 1=Samsung 4k with mpv), Nvidia GTX 1050Ti (with nvidia-driver-460), mpv 0.32.0.

Does anyone have an idea?

Thanks

**Comment by snylonue** [comment]
> mpv 0.32.0

try to update to latest version (0.33.1) though it most probably doesn't help

**Comment by LaserEyess** [comment]
Logs? Screenshots of artifacts? Example videos (or does any work)?

**Comment by StephVD** [comment]
> > mpv 0.32.0
> 
> try to update to latest version (0.33.1) though it most probably doesn't help

Updated to 0.33.1, same problem.

**Comment by LaserEyess** [comment]
That's not a log, and I can't view the video you uploaded.

Please try to reproduce with `mpv --no-config`, if you can't reproduce the issue with that, then slowly add options back until you can reproduce it, but always with --no-config. Also you will need a log file for cases that work and cases that don't work. I can't help you because you're not providing enough information, for example:

 - Is it only triggerable with 4 videos? what about 5?
 - Do any videos work? Does it have to be videos downloaded with youtube-dl?
 - Do you need those options to trigger the bug? does `--hwdec=no` also trigger it?
 - Is mpv even *using* the settings you give it? Is it falling back to other values?

Things like these are crucial for helping developers find out what's wrong.

**Comment by StephVD** [comment]
> That's not a log, and I can't view the video you uploaded.
> 
> Please try to reproduce with `mpv --no-config`, if you can't reproduce the issue with that, then slowly add options back until you can reproduce it, but always with --no-config. Also you will need a log file for cases that work and cases that don't work. I can't help you because you're not providing enough information, for example:
> 
> * Is it only triggerable with 4 videos? what about 5?
> * Do any videos work? Does it have to be videos downloaded with youtube-dl?
> * Do you need those options to trigger the bug? does `--hwdec=no` also trigger it?
> * Is mpv even _using_ the settings you give it? Is it falling back to other values?
> 
> Things like these are crucial for helping developers find out what's wrong.

I ran several tests with the mpv options, and found which option is problematic: --no-border

I don't know why the problem only occurs when this option is enabled. I searched the mpv documentation but couldn't find a workaround for this option.

**Comment by LaserEyess** [comment]
You have to give a log file if you want more help. Please do `mpv --no-config --no-border --log-file=log.txt video1 video2 video3 video4`.

**Comment by Dudemanguy** [comment]
Old issue, no log, so I will close it.
