### ISSUE TITLE
Specific loop time frames or loop synchronization

### ISSUE THREAD

**Issue by Gellyboy** [mpv-player/mpv#8998]
Lots of questions as of late. Anyways,
So if I have two of the exact same file playing side by side, is there some way to set a loop at the exact same point, without so much as a frame difference looking at two different areas on the video?
I could just manually select the frame using the , and . keys, and then do that for both videos, but I was just wondering if there was a way to do that more efficiently.

**Comment by guidocella** [comment]
You want to use `lavfi-complex` to completely sync the videos instead of 2 mpv instances:
`mpv --external-file=foo.mp4 --lavfi-complex='[vid1] [vid2] hstack [vo]' foo.mp4`

**Comment by Hrxn** [comment]
If the files are actually identical, seeking to the same position should also work in such a case.
And since you can set `time` like this with optional milliseconds, `seconds[.milliseconds]`e.g. `mpv --start=ss.ms`
You should be able to do something like this: `mpv --start=96.90 --ab-loop-a=96.90 --ab-loop-b=98.20 YourFileHere.mp4`

**Comment by Dudemanguy** [comment]
The question appears to be answered.
