### ISSUE TITLE
quit-watch-later only for videos that have saved positions previously (a smarter `quit-watch-later` option)

### ISSUE THREAD

**Issue by rieje** [mpv-player/mpv#9015]
`quit-watch-later` currently saves video position when a video is closed and when the video is `quit` again, playing the video starts from the beginning because it was not saved.

It would be nice to have a `smart-quit-watch-later` so that videos that had their positions saved with a `quit-watch-later` will automatically resume *and* save positions thereafter, even if just `quit` was used to close the video. 

This is useful because those who use this feature often do not want to `quit-watch-later` *all* videos--only some. And for those videos whose positions should be saved, they typically want to be saved every time, not just once (e.g. a movie, a long podcast, etc.). This feature removes the need for the user to make a conscious choice to either `quit-watch-later` or `quit` *every time* he closes a video. It avoids the common problem of accidentally just `quit`ing a video that you wanted to `quit-watch-later` instead because `quit` is often used for most videos. Smart quitting makes the process transparent and seamless.

**Comment by Dudemanguy** [comment]
I think you should probably just use a lua script for this. If I am understanding you correctly, you just want to always `quit-watch-later` if the video you are loading is using previous watch-later data. In that case, this is easy to script since watch-later data always has a start value not equal to nil. Anyways this should do the trick as long as you don't manually set the `--start` option.

```
function smart_quit()
    local start = mp.get_property("start")
    if start ~= nil then
        mp.command("quit-watch-later")
    else
        mp.command("quit")
    end
end

mp.add_forced_key_binding("q", "smart-quit", smart_quit)
```
