### ISSUE TITLE
What exactly does try_ytdl_first=yes do?

### ISSUE THREAD

**Issue by github-account1111** [mpv-player/mpv#9042]
My guess is this option is there to potentially improve startup. It says it "will try parsing the URL with youtube-dl first, instead of the default where it's only after mpv failed to open it." Open it with what? The fork I defined with `ytdl_hook-ytdl_path`? If so, I would definitely want to set it to `no`.

**Comment by avih** [comment]
mpv doesn't need youtube-dl to open network streams. youtube-dl is only used when the URL is of a web page which contains a video inside it - like youtube web pages.

Trying to check if a URL is a video stream can take time. This is true both if mpv opens the URL directly, or uses youtube-dl to find a video inside a page.

This option lets you choose which one of them mpv tries first.

**Comment by garoto** [comment]
Adding the below line to your .conf can greatly reduce startup times when opening URLs which are supposed to be opened by `youtube-dl` in the 1st place, since it avoids the initial `ffmpeg` network request to probe the mime/type of the URL itself.

`script-opts=ytdl_hook-try_ytdl_first=yes,ytdl_hook-exclude="%.webm$|%.ts$|%.mp3$|%.m3u8$|%.m3u$|%.mkv$|%.mp4$|%.VOB$"`

**Comment by github-account1111** [comment]
How does `ytdl_hook-exclude="%.webm$|%.ts$|%.mp3$|%.m3u8$|%.m3u$|%.mkv$|%.mp4$|%.VOB$"` reduce startup time? Tbh the explanation for that option doesn't make much sense to me either.. Exclude every URL that ends with one of those patterns, but I've just tried feeding it a URL that ends with `.mp4`, and it opened just fine.

**Comment by guidocella** [comment]
mpv doesn't open mp4 urls with youtube-dl, but with ffmpeg. youtube-dl is for extracting a video url from an HTML webpage, for example it converts https://www.youtube.com/watch?v=YbJOTdZBX1g to the URL of a dash playlist that ffmpeg can play.

The default `ytdl_hook-try_ytdl_first=no` tries ffmpeg first and then youtube-dl, which is faster for real video URLs like those that end with mp4. `ytdl_hook-try_ytdl_first=yes` tries youtube-dl first and then ffmpeg, which is faster for URLs of web pages from which youtube-dl has to extract the actual video URL.

The configuration suggested by garoto is faster because it tries ffmpeg first for most video URLs, and youtube-dl first for HTML URLs.
