### ISSUE TITLE
Option to not print entire path when taking a screenshot

### ISSUE THREAD

**Issue by qsniyg** [mpv-player/mpv#9054]
### Expected behavior of the wanted feature

When setting `screenshot-directory`, taking a screenshot will print the entire path, which can take multiple lines on the OSD (obscuring the video). I would prefer if there was a way to only print the filename (`mpv-shot...jpg`) rather than the full pathname (`{screenshot-directory}/mpv-shot...jpg`).

### Alternative behavior of the wanted feature

Since it appears that the reason it displays is because of a log message (`mp_cmd_msg(cmd, MSGL_INFO, "Screenshot: '%s'", filename);`), perhaps if there was some way for a script to filter/modify log messages? Or at least for what is displayed on-screen.

E.g. something like:

```
mp.register_event("log-message", function(message) {
  message.text = message.text.replace(/(Screenshot: ).*\//, "$1");
  return message;
});
```

**Comment by avih** [comment]
You can add `no-osd` to the screenshor command at your input.conf - https://mpv.io/manual/master/#command-interface-no-osd

And then use something like your script to catch the log message, and display an osd message of your own, e.g. using `mp.osd_message`.

**Comment by avih** [comment]
Can we close this? I don't think we'll add options for that (the dir is not very long usually, and the file name could be long too...), and the solution I suggested should cover your needs 100%,

**Comment by qsniyg** [comment]
Yes, thank you!

For anyone else stumbling on this issue, this script does the trick for me:

```
mp.enable_messages("info");
mp.register_event("log-message", function(message) {
	if (message.prefix !== "cplayer" || message.level !== "info")
		return;
	if (!/^screenshot:/i.test(message.text))
		return;

	mp.osd_message(message.text.replace(/^(screenshot:\s+)["']?(?:.*\/)?(.*?)["']?\s*$/i, "$1$2"));
});
```

**Comment by avih** [comment]
Also, the reason your approach won't work is because scripts can't be used as filters, because they recieve their input asynchronously.

There are only tow cases where a script can block mpv from progressing in its tasks:
- Script init (i.e. when the script runs for the first time to register its things etc) - mpv waits for all scripts to finish init before it starts playback.
- WIth hooks - mpv waits for the script to complete the hook action before it continues.

But other than this scripts don't block mpv and therefore can't be used as filters.
