### ISSUE TITLE
why shift cannot be bound with number in `input.conf`

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9060]
As the question mentioned in the title.
I tried `shift+1` in the input.conf but it doesn't work as my expectation.
I know `!` can work but I'm confused why I cannot use the another way to bind. (`shift+123456` should be clearer than `!@#$%^`)

### Log file

I do not think it is a bug.

**Comment by avih** [comment]
Different keyboards (layouts, languages) have different mappings (output) for shift+number, and for simplicity mpv looks at the output rather than the raw KB state.

That's not likely to change anytime soon.

**Comment by hooke007** [comment]
Thanks for answering. Maybe add some tips in the manual or console warning (when people try to do that) would be better.

**Comment by avih** [comment]
If you have a useful and short note to add at the manual, you can send a pull request with your suggested changes.

**Comment by avih** [comment]
Or rather, a more correct way to describe it, is that with the usual ways to get KB output - shift changes the key output fundamentally and is not sent to the program as "SHIFT+KEY" but rather the result of holding shift while pressing the key (like ! for shift+1), and that's unlike ALT or CTRL which are sent as base-key + ALT and/or CTRL.

On some systems it's possible to get the raw KB values and understand that the press was, for instance, shift+1, however that's usually more complex, different between systems, and adds complexity of how should the default bindings be configured (because this doesn't work on all systems). So mpv is not likely to support it anytime soon.

**Comment by hooke007** [comment]
A long and specific description is difficult for me to write by one PR (English is not my mother language).
Short and simple note would be possible for me but I think users maybe confused.

**Comment by avih** [comment]
> but I think users maybe confused

Yeah. I think people usually figure it out on their own, or they can ask, like you did.

**Comment by garoto** [comment]
There's an old and busy issue regarding keyboard layout/mappings woes here: https://github.com/mpv-player/mpv/issues/351
