### ISSUE TITLE
Support game-music-emu

### ISSUE THREAD

**Issue by Nikoli** [mpv-player/mpv#91]
vlc and mpd use game-music-emu for playing various format, it would be nice to support them in mpv.

https://code.google.com/p/game-music-emu/

**Comment by ThomS8312** [comment]
Is there a way to configure libmodplug as well as change soundfonts? What I'm hearing by default leaves a lot to be desired...it sounds like a music box with a harsh sound.

**Comment by wm4** [comment]
I'm not sure what you even mean.

**Comment by ThomS8312** [comment]
I thought libmodplug was a software synthesizer (had never heared of it before) and was an alternative to fluidsynth/timidity. What is "libmodplug" and how do I get it to work properly? I already have ffmpeg installed with it enabled.

**Comment by wm4** [comment]
> What is "libmodplug" and how do I get it to work properly?

I don't know either, just that it's obviously a library. If you know a better library, tell me.

**Comment by lachs0r** [comment]
Modplug isn’t a synth. It just plays a few tracker music file formats which use prerecorded samples.

**Comment by ThomS8312** [comment]
<blockquote>Modplug isn’t a synth. It just plays a few tracker music file formats which use prerecorded samples.</blockquote>

Are the "prerecorded samples" sound banks that are included in the library itself?

**Comment by lachs0r** [comment]
> Are the "prerecorded samples" sound banks that are included in the library
> itself?

No, they’re part of each file.

**Comment by ThomS8312** [comment]
Seeking seems to be broken with .mid (MIDI) and .xm (FastTracker 2) files. The player sometimes exits or playback loops to the beginning while seeking in certain scenarios. Some .mid and .xm files won't play at all (the player itself won't even load), while other players can without issue.

I think mpv would benefit the most with FluidSynth support for MIDI playback. It's a popular choice in other linux audio players and an interest in it was expressed previously.

Based on what I've heard from libmodplug, it's not suitable for MIDI. Almost anything would be better. Maybe something's wrong with the playback? There's no percussion and it sounds like only one instrument is playing overall, and that instrument is more like a piercing "beep" that plays at different tones.

**Comment by ThomS8312** [comment]
In fact, including Timidity++ support too would give greater MIDI support to mpv. FluidSynth or Timidity++ are usually the two choices for software synths (MIDI playback) in audio programs. If only one is supported, users of the unsupported synth are out of luck.

**Comment by ThomS8312** [comment]
After looking into this further, I've concluded that Timidity++ is the best choice for MIDI playback. There's no need to support more than one synth.

I think the focus of a software synth for mpv should be playing .mid files. I've tested playback with a few .mid files I have and Timidity++ played them even better than Fluidsynth did (using the FluidR3_GM soundfont). Fluidsynth wouldn't play one particular .mid file I had, and complained that the file "wasn't a Sound Font file" and "couldn't load" it. Fluidsynth also plays .mid files with an overly emphasized chorus while recessing the other instruments. Timidity++ played the .mid files without these issues.

Timidity++ prints out the metadata of a currently playing .mid file in the terminal too. That's useful because <code>ffprobe</code> doesn't seem to retrieve that kind of information from .mid files. Another benefit of Timidity++ is that it loads faster than Fluidsynth. Timidity++ loads right away, but Fluidsynth takes a moment or two before it begins playing.

I also briefly looked into Wildmidi. It's not as mature as Timidity++ is, so it wouldn't be a viable alternative.

**Comment by wm4** [comment]
Frankly, I can't seem to find a Timidity++ lib or API. Where did they hide it?

>Timidity++ prints out the metadata of a currently playing .mid file in the terminal too. That's useful because ffprobe doesn't seem to retrieve that kind of information from .mid files. 

A proper library should never print anything to the terminal, unless explicitly asked to. Anyway, I'm not sure if ffprobe or mpv can dump the information you want, because they use a generic API designed for video media files.

**Comment by timofonic** [comment]
@wm4 thanks for your nice reply on the other project! ;)

I find there are some alternative midi players:
https://github.com/Mindwerks/wildmidi

**Comment by ThomS8312** [comment]
<blockquote>Frankly, I can't seem to find a Timidity++ lib or API. Where did they hide it?</blockquote>

I'm not sure about Timidity++'s code, but I read somewhere it isn't a library.

A certain approach needs to be taken with MIDI playback because it's an entire context in and of itself. Mpv would need to accomadate that context for complete support.

What I used to test both Fluidsynth and Timidity++ were the <code>timidity</code> and <code>fluidsynth</code> command line programs. Both synths are MIDI players and have their own configuration files. <code>timidity</code> prints the metadata of the currently playing file in the terminal.

Proper MIDI support <b>must</b> include a means to configure the synth (options, changing sound banks). I visualize the support for Timidity++ to be similar to how youtube-dl is supported, meaning options from a separate program can be passed through mpv. <code>timidity</code> would be the backend for MIDI playback and its configuration file would be acknowledged as well.

<blockquote>I find there are some alternative midi players:
https://github.com/Mindwerks/wildmidi</blockquote>

Wildmidi doesn't support SF2 (so the FluidR3_GM2-2.sf2 sound bank is not an option), and Timidity++ has more support than both Wildmidi and Fluidsynth for standard .mid files.

**Comment by wm4** [comment]
>I'm not sure about Timidity++'s code, but I read somewhere it isn't a library.

Then it's not useable by ffmpeg or mpv. You still could probably make timidity output raw audio and pipe that to mpv, though.

**Comment by ThomS8312** [comment]
Actually, Timidity++ can be run as a daemon, providing ALSA with MIDI support. That's probably the point of connection you're looking for. Other programs are able to utilize Timidity++ in this way.

**Comment by wm4** [comment]
Can you point me at a program that uses timidity in such a way?

**Comment by ThomS8312** [comment]
<code>aplaymidi</code> is a program that does.

**Comment by lachs0r** [comment]
On Monday 08 June 2015 13:12:33 V. Lang wrote:
> Can you point me at a program that uses timidity in such a way?
There’s SDL_mixer… which contains a stripped-down copy of timidity itself.

**Comment by ThomS8312** [comment]
<code>aplaymidi</code> is a simple program that is part of the ALSA project. Test MIDI playback with command <code>aplaymidi FILE.mid -p 128:0</code>, assuming  you have the Timidity++ deamon running beforehand with the default client/port (command <code>timidity -iA</code>).

Another one is Rosegarden. It's a music composer/editor program and is fully featured compared to <code>aplaymidi</code>.

**Comment by psi29a** [comment]
Not sure if this ship has sailed, but wildmidi is in the process of adding support for soundfonts. It also supports more file formats than just MID and do so with less CPU usage than either fluidsynth and timidity.

**Comment by wm4** [comment]
API seems reasonable, so if anyone wants to implement this.

**Comment by shmerl** [comment]
> Proper MIDI support must include a means to configure the synth (options, changing sound banks).

Fluidsynth allows external control through QSynth for example.

**Comment by lachs0r** [comment]
FWIW FFmpeg has added support for GME years ago. Not sure why you’re necro posting here now.

**Comment by clort81** [comment]
I am adding here the note that as of 2023-03-03, mpv does playback via gme via ffmpeg, if that is built-in.  this can be added to the ffmpeg options in the mpv-build script on this repository.

If I find out how to get stereo separation (libgme supports this) working over mpv, I'll add the note. Some degree of stereo makes old chiptunes much more tolerable to the ear.
