### ISSUE TITLE
unreasonable handling of long filename

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9135]
### Important Information

Provide following Information:
- mpv version
- 20210815
- Windows Version
- 20h2
- Source of the mpv binary
- shinchiro
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches
![Snipaste_2021-08-18_19-33-15](https://user-images.githubusercontent.com/41094733/129891303-5ef6f3ef-ac11-40ad-9cfd-51054ef4a9f8.jpg)

### Reproduction steps

just open the files which has long file names and see the osd filename.
Some long filenames cannot be handle normally.

### Expected behavior

filenames couldn't be cut or early truncated

### Actual behavior

the picture posted previously.

### Log file

I'll post it if needed.

### Sample files

example filenames:
`[aaaaaaa&bbbbbbb][ccccccc dd eeeee][00][1080p][xx][kkk].mp4`
`aaaaa.bbbbb.cccccc.1996.bluray.1080p.x265.10bit.8audio.10subs.mp4`

**Comment by avih** [comment]
I don't really understand what the issue is.

I think you mean this?
- With some file names, there's no word-wrap (first screenshot) but you expect it to word-wrap.
- With some other file names, it does word-wrap (second screenshot) but you expect it to NOT word wrap.

It's not clear to me what "normal" means to you and how you expect it to look instead for each of the file-names you gave as example.

If that's not what you meant, you can try explaining again, one issue at a time:
- I do this and that.
- The result is (screenshot).
- But I expect it to look like this (describe exacty).

Either way, libass is responsible for word-wrap, and the wrap happens if there's a space or other characters which allow word-wrap according to Unicode. This means that some filenames cannot be word-wrapped (if they don't have spaces), while other file-names will get word-wrapped if they contain spaces.

That's normal behavior with word wrapping, and even if it wasn't, mpv doesn't have much to do about it. It appears that all the libass word-wrapping modes don't break the line if there are no spaces.

You can try smaller font size if you have very long file names, using `--osd-font-size` - https://mpv.io/manual/master/#options-osd-font-size

**Comment by hooke007** [comment]
expectation:
![Snipaste_2021-08-23_18-35-08](https://user-images.githubusercontent.com/41094733/130433699-ce5d2e54-5483-406e-bb90-e61207f5c8a3.jpg)

>libass is responsible for word-wrap

And it seems there is nothing can do here.

**Comment by avih** [comment]
> expectation:

Thanks, at least it's now clear what you meant.

For the first screenshot, I think it's a reasonable expectation, however, las mentioned, ibass currently doesn't support word wrap for lines without any spaces.

For the second screenshot, I'm not sure. Word-wrap (in any editor or web browser) always breaks the line on spaces before it breaks in places without spaces. So I think libass does the right thing in this case.

**Comment by hooke007** [comment]
Thanks for your explanation.
