### ISSUE TITLE
How to disable icc color management

### ISSUE THREAD

**Issue by estaf1001** [mpv-player/mpv#9139]
Hi all
In manual of mpv I had meet a next phrase "when ICC color management is not being used", but I can't find how to disable)) that "icc color managed" option.
There are all features with icc etc, but not only how to disable icc color management system.

When I open mpv and watch movie with that player and compare it with vlc player, that I see that mpv use cms. vlc don't use cms, afaik.

**Comment by Akemi** [comment]
`--icc-profile=` and `--icc-profile-auto`. neither are set by default, so colour management is disabled.

**Comment by estaf1001** [comment]
had tested --icc-profile=no, --icc-profile=none, --icc-profile-auto.
wasn't disabled. I compare it with vlc.

**Comment by porg** [comment]
@Akemi thanks for stating here that in mpv by default color management is disabled.

1. I'd appreciate if such an important information would be mentioned in the official manual at the relevant sections like https://mpv.io/manual/master/#options-icc-profile-auto
Because on macOS media apps by default use ColorSync and you rather must opt out than opt in. For example all the first party media playback apps Preview.app, QuickTime Player.app and image/video display in Safari.app all use ColorSync by default, that is they respect color profiles if embedded, or they assume a default profile for files without an embedded profile or profile reference name in the metadata/header section of the media file. Having an colors unmanaged, not going through ColorSync is rather exceptional for Mac apps.

3. And last but not least, I'd like an open discussion why you got to that decision to be without color management? I don't doubt it! I rather know simply less about color management of videos, especially in the context of lossy web videos. And would like to hear what aspects lead to that decision. Thanks!
