### ISSUE TITLE
SPONSKRUB

### ISSUE THREAD

**Issue by TheAlphaReturns** [mpv-player/mpv#9146]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
Sponskrub. Sponsorblock. anything. remove sponsor from yt videos

### Alternative behavior of the wanted feature
none

**Comment by LaserEyess** [comment]
Those are browser extensions, mpv is not a web browser so that's just never going to work. mpv technically doesnt' even work with youtube without youtube-dl. You can try using [youtube-dlp](https://github.com/yt-dlp/yt-dlp) which has [explicit support ](https://github.com/yt-dlp/yt-dlp#sponskrub-sponsorblock-options) for it. YMMV.

Otherwise, there's no way mpv can implement this.
