### ISSUE TITLE
Is it possible to break an EDL list to several lines?

### ISSUE THREAD

**Issue by TCH68k** [mpv-player/mpv#9186]
If i have a very big EDL list and i call `mpv --playlist=x.edl`, then it says
```
[playlist] Reading plaintext playlist.
[file] error reading line
Error reading playlist 'x.edl'
```
Here is an example file: http://oscomp.hu/depot/x.edl

**Comment by garoto** [comment]
> Here is an example file: http://oscomp.hu/depot/x.edl

that's not how an .edl file should be constructed, even retarded me knows that much.

Read https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst

And then read it again. And then again still.

**Comment by TCH68k** [comment]
Too bad, because it works with smaller files and also i was on IRC and it turned out that the error was caused by a buffer not big enough.
https://github.com/mpv-player/mpv/blob/master/demux/demux_playlist.c#L53
It will be increased to 2 MB.

BTW, I've read that manual and it said it can be splitted into lines. It did not work.

**Comment by avih** [comment]
> I've found a list bigger than 2 MB: https://youtube.com/watch?v=iII1nQn5DH0

Hmmm... we increased it from 512K to 2M after I explicitly asked you to assess how much should suffice - because we just don't know, and only you need this. The biggest you could find was about 520K, and we agreed 2M should be enough for the foreseeable future.

And now you say it's not enough, and I believe you, but we can't just increase it every few weeks. Using a dynamic buffer instead of a static one should solve it, but it needs to be assessed (it definitely wouldn't be as simple) - especially when we're talking about the limit for a _single_ input line.

Not sure what to do about it.

**Comment by avih** [comment]
> How about simply making the linebuffer dynamic? For that, there is a patch already.

Unless this the only correct solution - which I don't know right now (and it would require effort to know), then to me this feels like a hack, which is why I prefer to not go through with this.

If another mpv developer wants to take over and make it happen, no objection here.
