### ISSUE TITLE
About the compiled mpv-1.dll file

### ISSUE THREAD

**Issue by ITSweets** [mpv-player/mpv#9259]
Hi. I am trying to compile libmpv to use msys2 on window. I compile according to compile-windows.md and everything is going well. But I found that the size of the compiled mpv-1.dll is only about 10 mb, while the size of the mpv-1.dll in libmpv I downloaded from sourceforge is at least 60 mb. What's the situation? In addition, how to modify the name of the generated mpv-1.dll? For example, change to MpvCore.dll.
Looking forward to your reply.

**Comment by zhongfly** [comment]
see https://github.com/shinchiro/mpv-winbuild-cmake

**Comment by Dudemanguy** [comment]
There's a million different variables for why the filesize is different (probably some windows shenanigans who knows). In principle, there should not be a large difference because libmpv is basically just mpv but compiled to a library instead of an executable. Also, you shouldn't really arbitrarily rename .dll files.
