### ISSUE TITLE
How to raise volume with 0 while stats are toggled

### ISSUE THREAD

**Issue by bardaniel** [mpv-player/mpv#9292]
In commit 1e90ec6 it was possible to have stats toggled (by punching 'I') and raise the volume using '0', however it seems in the commits after that a stats page was added to the key '0', making it not possible to raise the volume. Is there a way to bind back the '0' while stats is toggled to raise volume? I am using a portable mpv on windows

**Comment by avih** [comment]
The stats script binds several keys when it's active, and those keys don't do their normal function until stats is exited. Recently key "0" was indeed added, but the "issue" is the same for all those keys, and it just happens that you care particularly about this specific key.

You can configure them to use different keys, as documented here https://mpv.io/manual/master/#id2

Specifically, e.g. use `--script-opts-add=stats-key_page_0=ctrl+0` to use control+0 instead of just 0.
