### ISSUE TITLE
Hide window title bar? 

### ISSUE THREAD

**Issue by kotobuki09** [mpv-player/mpv#9303]
The current update makes some changes to the title bar. I used to hide it with this command script-opts=osc-windowcontrols=no into mpv.conf but it seems like it's not working anymore.
How can I hide or disable taskbar 1 or 2?
https://i.imgur.com/yKg0Tan.jpeg

**Comment by avih** [comment]
> I used to hide it with this command script-opts=osc-windowcontrols=no into mpv.conf but it seems like it's not working anymore.

It's working like before, but you probably added some other script opts later in your config file (but impossible to tell because you didn't provide a log like you were requested), and they replaced (and removed) the earlier ones.

If you to add script opts instead of replacing the existing ones, use `script-opts-add=WHATEVER` instead of `scripts-opts=WHATEVER`.
