### ISSUE TITLE
hwdec option for Windows

### ISSUE THREAD

**Issue by xswqaz** [mpv-player/mpv#932]
CPU usage was about 40% in My windows 8.1 machine with intel HD gpu,
But Only 12% in wmp

I Think hwdec option was not valid in Windows

hwdec=auto
vo=opengl

Is it any proper option for Windows?

**Comment by parkerlreed** [comment]
What exactly is supported? auto and dxva2-auto aren't playing fullspeed on an Atom 7340 (1080p@60 H264 is what I'm trying) I'm only passing in the hwdec. Is there anything else that is needed?

**Comment by wm4** [comment]
>What exactly is supported? 

That's all.

**Comment by kevmitch** [comment]
could be the sse4 copyback voodoo doesn't work on atom

**Comment by wm4** [comment]
>could be the sse4 copyback voodoo doesn't work on atom

Possible. Show a log?

**Comment by wp9015362** [comment]
> @wm4 wrote:
> 
> also only copy-back mode is available now.

Looks like there is still only dxva2-copy avaialble at the moment?

Are there any plans to also add dxva2-native?

Regards

**Comment by wm4** [comment]
>Are there any plans to also add dxva2-native?

Not really, because it's a huge effort (especially because we'd have to use D3D/OpenGL interop). And we still wouldn't get YUV data from the surfaces, only driver-mangled RGB. (From what I understood.)

**Comment by wm4** [comment]
(Which is not that we won't ever do it, but I wouldn't expect improvements any time soon.)

**Comment by wp9015362** [comment]
@wm4 :

Thanks, but that's sad to hear, because the performance on an Intel Bay Trail unfortunately is very bad :worried:.

I have set:

--hwdec=dxva2-copy --vo=opengl

and the performance is extremely bad and nowhere near comparable to MPC-HC + LAVFilters.

Unfortunately it's unusable like that and no alternative for MPC-HC :worried:.

You were asking for showing a log in an earlier post.

Would that be done with --log-file=<path>?

Regards

**Comment by wm4** [comment]
Yes.

Is the performance equally bad if you use copy mode in lavfilters? (Or whatever it's called htere.)

**Comment by wp9015362** [comment]
> @wm4 wrote:
> 
> Is the performance equally bad if you use copy mode in lavfilters? (Or whatever it's called htere.)

In the LAV Video Decoder you can select the following:

![Image](https://github-cloud.s3.amazonaws.com/assets%2F7558360%2F10957792%2Ff76ae14e-8367-11e5-8751-e92e722a18a4.png)

When selecting "DXVA2 (native)" in the LAV Video Decoder, the performance is superb and even 1080p60 and 2160p30 videos with high bitrates can be played back.

When selecting "DXVA2 (copy-back)" in the LAV Video Decoder though, then the performance is a lot worse, but still slightly better than mpv with --hwdec=dxva2-copy --vo=opengl.

In MPC-HC it also makes a difference which renderer is selected.

You can select among the following:

![Image](https://github-cloud.s3.amazonaws.com/assets%2F7558360%2F10957822%2F55a7571a-8368-11e5-9af4-8ae0504349ba.png)

"Enhanced Video Renderer" has the best performance by far.

"Enhanced Video Renderer (custom presenter)" is the default in MPC-HC, but the performance is worse than just "Enhanced Video Renderer".

> @wm4 wrote:
> 
> Yes.

Here is the log:

https://gist.github.com/wp9015362/885ebc4d3ff308091ee4

Is it any helpful?

PS:

By the way, I am wondering:

Is mpv also using the Enhanced Video Renderer (EVR) on Windows?

EVR is native to Windows since Windows Vista:

https://en.wikipedia.org/wiki/Media_Foundation#Enhanced_Video_Renderer

If mpv is not using it at the moment, maybe it would be wise to do it?

Regards

**Comment by wm4** [comment]
Can you try with ``--vo=opengl:dumb-mode`` or ``--vo=direct3d`` whether it approaches MPC-HC's performance in the copy-back case?

>Is mpv also using the Enhanced Video Renderer (EVR) on Windows?

No. It's very obviously using OpenGL, and you even force OpenGL on the command line.

>If mpv is not using it at the moment, maybe it would be wise to do it?

No. If you want this, you're better off with a DirectShow or MediaFoundation based player.

**Comment by wp9015362** [comment]
> @wm4 wrote:
> 
> Can you try with --vo=opengl:dumb-mode or --vo=direct3d whether it approaches MPC-HC's performance in the copy-back case?

Unfortunately no difference compared to --vo=opengl.

> @wm4 wrote:
> 
> No. It's very obviously using OpenGL, and you even force OpenGL on the command line.

Yeah, sorry for asking :yum: . I just wasn't quite sure if OpenGL in mpv is the pendant to EVR in MPC-HC.

> @wm4 wrote:
> 
> No. If you want this, you're better off with a DirectShow or MediaFoundation based player.

Well, but I don't know of any other player that can handle YouTube DASH videos on Windows, that's why I am looking into mpv.

By the way, in case this information helps:

In Kodi (http://kodi.tv/), the performance is as good as in MPC-HC with DXVA2 native.

PS:

The performance with mpv under Linux is very good on the same system :smiley: ! So in that case mpv is really nice. It would just be cool, if mpv would also perform that well under Windows.

Regards
