### ISSUE TITLE
A new release maybe?

### ISSUE THREAD

**Issue by birdie-github** [mpv-player/mpv#9335]
There haven't been formal releases of mpv for more than half a year already, so I'm curious why.

Of course one can compile a GIT snapshot but it's not clear whether it's stable enough and whether all the included merges/patches/code so far are bug-free and ready to use.

**Comment by CounterPillow** [comment]
From `releace-policy.md`:

> The goal of releases is to provide Linux distributions with something to package. If you want the newest features, just use the master branch. We try our best to keep it deployable at all times.

So using git master is fine.

The reason why no new release has been cut yet is because nobody has gotten around to making one, and each time it's brought up there's invariably just one more thing somebody wants to get done first because the fear is that any new release will be one that some Debian will be shipping for the next decade.
