### ISSUE TITLE
Add ability to use save-position-on-quit when file name changes

### ISSUE THREAD

**Issue by TAAPArthur** [mpv-player/mpv#9346]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

I primary use mpv to play remote media and the remote server often changes the filename. The exact url is determined by the an external script which launches mpv. For all intents an purposes it is fair to say the url is random but there is some unique, constant metadata that is known to the script that could in theory be passed to mpv. I wish for mpv to be resume position for said remote urls even when the url is completely different

### Expected behavior of the wanted feature
I invoke mpv with some flag (like --hash HASH) and said flag (or hash of that flag) is used in place of the filename/url for resuming playback. That is the passed in value is saved instead of the file name and if I invoke mpv with the same value and different file name, it should resume as if the file names were the same.

### Alternative behavior of the wanted feature
Instead of adding a new flag, my usecase would be satisfied with using an exiting one like title for the hash. For my usecase at least the title passed in will uniquely identify the video.

### Log file

I don't think it'll be helpful but here is the log file: [output.txt](https://github.com/mpv-player/mpv/files/7403804/output.txt)

**Comment by LittleBenjiBoy** [comment]
I just wanted to vouch for @TAAPArthur's proposal. I am a user that would also like a solution to this problem. The situation that he described in his initial post and in https://github.com/mpv-player/mpv/issues/9346#issuecomment-952463091 is something that I always encounter. Having mpv use the video's title to resume the video instead of the path or filename resolves my issue. I have went through the trouble of building from source to test his commit/change at [options: Add watch-later-use-title](https://github.com/TAAPArthur/mpv/commit/8818548926b7239e93c84278d89e623be8caae4e) and it had exactly what I needed. Please implement this change to the original mpv so that I can get it in the Windows version of mpv rather than a built version of mpv that depends on the .dll files in `C:\msys64\mingw64\bin`, which cannot be made portable.
