### ISSUE TITLE
differences in performance between windows and ubuntu

### ISSUE THREAD

**Issue by feanor3** [mpv-player/mpv#9363]
### Important Information

Provide following Information:
- mpv version 0.32.0
- Linux Distribution and Version Ubuntu 20.04
- Source of the mpv binary apt install mpv
- GPU driver and version maybe [this](https://pastebin.com/xZHhf69i)?
- 
### Reproduction steps
On windows I'm able to run the first shader of "lower-end gpu" of [Anime4k](https://github.com/bloc97/Anime4K/blob/master/GLSL_Instructions.md) without loosing frames on a video, using my laptop with ryzen 2500u and vega 8 graphics.
On ubuntu, which I've installed on an external ssd but I run on the same laptop, the framerate with shaders is the half (30 instead of 60fps).

### Expected behavior
Why does this happen? Hardware is the same, except that the ssd is connected through usb. Thanks.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/7428672/output.txt)

**Comment by lavilao** [comment]
try using gpu-api=vulkan to see if the performance increases, also on my experience with a weaker cpu than yours using ACNet instead of anime4k gives better quality and performance. Another thing that might help is to use a newer mpv, look for 0.34.0 do NOT use 0.33.x as its broken with vulkan using vaapi (at least that was my case until yesterday with an intel igpu)

**Comment by Dudemanguy** [comment]
Performance differences in this case is mostly down to drivers. In general on Linux you want to be on up-to-date kernel and mesa versions (also mpv versions).
