### ISSUE TITLE
[vo=gpu-next] subtitles along with HDR video are not displayed properly

### ISSUE THREAD

**Issue by quietvoid** [mpv-player/mpv#9389]
### Important Information
```
mpv 0.34.0-11-g8bd0dee531 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Wed Nov  3 10:24:13 EDT 2021
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4
```
- Arch Linux
- git master
- vo=gpu-next branch
- Sway 1.6.1, wlroots 0.14.1
- GPU: AMD Navi 5500 XT
- Kernel Driver: amdgpu 5.14.15
- OpenGL Driver: Mesa 21.2.4 (OpenGL 4.6)
- libplacebo: v4.157.0.102.g84c6bd4-1

### Reproduction steps

Play HDR video file.
- Commande line: `mpv -v --no-config --vo=gpu-next test.mkv`

Enable subtitle stream.
Find a timestamp where subtitles should appear.

### Expected behavior
Text should be rendered correctly.

### Actual behavior
The subtitles rendered are garbled in playback.
Screenshots are different like in #9388.

This is happening for ASS, SRT and image based subtitles like PGS/SUP.

Rendered picture:
https://0x0.st/-5rm.png

Screenshot:
https://0x0.st/-5rB.jpg

### Log file
[gpu-next-hdr-subtitles.log](https://github.com/mpv-player/mpv/files/7470346/gpu-next-hdr-subtitles.log)

### Sample files
https://0x0.st/-5rM.mkv

**Comment by haasn** [comment]
Can't reproduce. Renders fine for me. Not sure where to start. Can you try `--gpu-dumb-mode=yes --tone-mapping=clip --hdr-compute-peak=no`?

**Comment by quietvoid** [comment]
> --gpu-dumb-mode=yes --tone-mapping=clip --hdr-compute-peak=no

It renders fine when either of `--gpu-dumb-mode=yes` or `--hdr-compute-peak=no` are enabled.

**Comment by haasn** [comment]
Can you test if https://github.com/haasn/libplacebo/commit/93baeef2f59f3b2c0f4a3afeedf5f13f83613020 fixes it?

**Comment by quietvoid** [comment]
@haasn It doesn't fix it.

Rendered: https://0x0.st/-5MK.png
New log: [gpu-next-hdr-subtitles.log](https://github.com/mpv-player/mpv/files/7490497/gpu-next-hdr-subtitles.log)

**Comment by haasn** [comment]
Oh, I see. I can reproduce it using amdvlk on my end, too.

**Comment by haasn** [comment]
Well, this is certainly a bizarre one. It has nothing to do with HDR, that only inadvertently triggers it because it's the only compute shader in your render pipeline. You can reproduce the same bug using any other compute shader (e.g. `ewa_lanczos`).

It seems like _any_ sort of attempt to write to a VkImage, that was previously being used as a compute shader, from a render pass, causes the areas written to to contain some sort of weirdly corrupted/undefined memory. If I had to guess, it seems like some sort of bug related to framebuffer compression modes. Something about the transition to `GENERAL` image layout just completely breaks rasterization to those textures.

I'm going to tentatively call this one an AMD driver bug.

**Comment by quietvoid** [comment]
Alright. I went and downgraded to check when this starts happening and ended up on version `2020.Q1.2`.
`2020.Q1.1` is OK, and everything after `2020.Q1` has the problem.

I'm not intending on reporting the bug upstream, since I don't really know what's happening myself.

**Comment by quietvoid** [comment]
By the way, I can't reproduce this issue anymore regardless of `amdvlk` version used.
So maybe something else fixed it since.

**Comment by haasn** [comment]
@quietvoid It might have been the change to resource synchronization that happened in [2de791e5b2](https://code.videolan.org/videolan/libplacebo/-/commit/2de791e5b2c04716afaacac7d42e40f6ae9ce15d)
