### ISSUE TITLE
FR: Remapping the mouse functions

### ISSUE THREAD

**Issue by Ainson** [mpv-player/mpv#9400]
IMO it's much more logical and easy to have:

Left click - Play/pause
Right click - Toggle full screen
Mouse wheel up - Jump backward
Mouse wheel down - Jump forward

**Comment by avih** [comment]
You can configure all of those, except left-click which is also used for dragging the window.

**Comment by Ainson** [comment]
Sweet, I didn't know you could configure it.

I just looked in the player itself for a way, I now see you have to make a input.conf file and edit that:
https://github.com/kba/mpv-config/blob/master/input.conf

So now it all works the way I like, even the single left click to toggle pause (can still be used to move the window like you say)

**Comment by Ainson** [comment]
Thanks for the fast response

**Comment by hooke007** [comment]
Manual should be the real thing you need , I guess.
https://mpv.io/manual/master/#input-conf-syntax

**Comment by Ainson** [comment]
No that didn't work for me. Just too confusing.

The example file I linked to above solved it however.

**Comment by Ainson** [comment]
> You can configure all of those, except left-click which is also used for dragging the window.

Also don't understand why left-click is hardwired to drag window, when that's rarely done compared to play/pause, and dragging window could be done by grabbing the menu bar as is the common way.

**Comment by avih** [comment]
> Also don't understand why left-click is hardwired to drag window, when that's rarely done compared to play/pause

That's your use case maybe, but it's been like that from the very beginning and most people are fine with it. Also, it's not like you can't pause/play - you have hundreds of keys/mouse combos you can bind to toggle pause/play. Most people are absolutely fine with that.

It's also a complicated subject. Mouse events and dragging are done at the VO, (windows, x11, wayland, osx, etc) but the events are managed centrally in mpv. This interaction is not simple, and it's hard for the core mpv to differentiate between a plain click and a click which starts a drag. That's why it's not recommended to bind the left click.

**Comment by avih** [comment]
> Also don't understand why left-click is hardwired to drag window

It's not hardwired. It's just the default. You can disable that - https://mpv.io/manual/master/#options-no-window-dragging

And then you can bind the left mouse button without issues.
