### ISSUE TITLE
vo_gpu_next: Failed mapping filter function 'ewa_lanczossharp'

### ISSUE THREAD

**Issue by snylonue** [mpv-player/mpv#9408]
### Important Information

Provide following Information:
- mpv version `mpv 0.34.0-16-gec16769c2d`
- Windows Version `21H1 19043.1288`
- Source of the mpv binary shinchiro's build

### Reproduction steps

Run `mpv /path/to/video --no-config --vo=gpu-next --scale=ewa_lanczossharp`

### Expected behavior

`ewa_lanczossharp` is applied

### Actual behavior

mpv reports `[vo/gpu-next] Failed mapping filter function 'ewa_lanczossharp', no libplacebo analog?`
while `--vo=gpu` works.

### Log file

[gpu-next.log](https://github.com/mpv-player/mpv/files/7491537/gpu-next.log)

**Comment by hooke007** [comment]
For gpu-next: haasn said some algorithm had been drop.
If u want it back

```
 builtin-scalers = no
 scale           = ewa_lanczos
 scale-blur      = 0.9812505644269356
 scale-radius    = 3.2383154841662362
```

**Comment by snylonue** [comment]
> 
> 
> For gpu-next: haasn said some algorithm had been deleted. If u want it back
> 

Thanks. Hopefully the removal can be documented

**Comment by haasn** [comment]
> For gpu-next: haasn said some algorithm had been deleted. If u want it back
> 
> ```
>  builtin-scalers = no
>  scale           = ewa_lanczos
>  scale-blur      = 0.9812505644269356
>  scale-radius    = 3.2383154841662362
> ```

Don't use `builtin-scalers = no`, it serves no purpose here. (Also, that's the default radius of `ewa_lanczos`)

**Comment by hooke007** [comment]
> it serves no purpose here. 

The manual said `builtin-scalers = yes` is the default setting which makes `scale-*= ` options not work.
It makes me confused.

> that's the default radius of ewa_lanczos

sry, I couldn't found the related code so I treat it 3 as in vo_gpu.

**Comment by haasn** [comment]
> The manual said `builtin-scalers = yes` is the default setting which makes `scale-*= ` options not work. It makes me confused. Does it mean `builtin-scalers` only contains `nearest bilinear bicubic`?

Yeah, it's only those three. And in mpv actually just `bicubic_fast`, not even regular `bicubic`. I removed the option again because I don't think it serves any purpose.

> sry, I couldn't found the related code so I treat it 3 as in vo_gpu.

[It's here](https://code.videolan.org/videolan/libplacebo/-/blob/master/src/filters.c#L609). All of the jinc-based filters got configured to 3 taps by default in libplacebo, rather than 3 *pixels* as in mpv. It was an intentional change, especially because it means dropping the awkward `ewa_lanczossharp` (which doesn't *really* serve a purpose other than using the proper number of taps - the extra sharpening is barely visible).

**Comment by monarc99** [comment]
I think, they use it, because the manual says to use it:

----------

https://mpv.io/manual/master/#options-ewa-lanczossharp

A slightly sharpened version of ewa_lanczos, preconfigured to use an ideal radius and parameter. If your hardware can run it, this is probably what you should use by default.

--------------

**Comment by hooke007** [comment]
It has been mentioned in this commit https://github.com/mpv-player/mpv/commit/73563cebf9ae6c3c8f5ca4a84f67b2e96c08f51f
