### ISSUE TITLE
[ffmpeg] mov_text: The "sub_text_format" option is deprecated

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#9413]
### Important Information

Provide following Information:
- mpv version git master
- Windows Version win11
- Source of the mpv binary https://github.com/zhongfly/mpv-build/releases/tag/2021-11-06

### Reproduction steps
play ytdl --embed-subs  --sub-lang="chi,chs,zh,zh-Hans,zh-CN"  --merge-output-format mkv https://www.youtube.com/watch?v=BoZ0Zwab6Oc

### Expected behavior
no warning shows

### Actual behavior
[ffmpeg] mov_text: The "sub_text_format" option is deprecated: Deprecated, does nothing

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/7492103/mpv.log)

### Sample files
see Reproduction steps

**Comment by jeeb** [comment]
Yes, this was recently deprecated in FFmpeg. I will make it conditional as I check what the relevant versions are.

Technically as it's a case of runtime option setting, it will not break even if left as-is, since when the AVOption gets removed that  `av_dict_set(&opts, "sub_text_format", "ass", 0);` will just not set anything in `sub/lavc_conv.c`. But as it's the correct thing to do, it will be made conditional.

**Comment by ilf** [comment]
I still get this with mpv 0.34.1-dirty and FFmpeg version: n5.0:

`[ffmpeg] srt: The "sub_text_format" option is deprecated: Deprecated, does nothing`

**Comment by bugisbuggingme** [comment]
> I still get this with mpv 0.34.1-dirty and FFmpeg version: n5.0:
> 
> `[ffmpeg] srt: The "sub_text_format" option is deprecated: Deprecated, does nothing`

Confirmed.

> mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
>  built on UNKNOWN
> FFmpeg library versions:
>    libavutil       57.17.100
>    libavcodec      59.18.100
>    libavformat     59.16.100
>    libswscale      6.4.100
>    libavfilter     8.24.100
>    libswresample   4.3.100
> FFmpeg version: n5.0

**Comment by jeeb** [comment]
As I noted before:

> Technically as it's a case of runtime option setting, it will not break even if left as-is, since when the AVOption gets removed that `av_dict_set(&opts, "sub_text_format", "ass", 0);` will just not set anything in `sub/lavc_conv.c`.

This is why I do not think this required a bug fix to be put into the release branch (in addition to master, where it has been ever since late 2021). We already utilize the "newer" subtitle mode since 2019, and we are specifying it. Now the option does nothing. This should also not fail if the option just does not exist, either. In other words, It is a harmless warning. Thus does not require putting into already previously created release branches.

**Comment by rokezu** [comment]
Just a heads up that I'm getting this warning as well, and I'm not setting the option anywhere? So, technically not my fault, but anyways mpv scolded me. 😅

`[ffmpeg] srt: The "sub_text_format" option is deprecated: Deprecated, does nothing`

My version:

```
$ mpv --version
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0
```
