### ISSUE TITLE
[vo=gpu-next] linear-downscaling or linear-upscaling clips the highlights in HDR movies

### ISSUE THREAD

**Issue by epicfilmmaker93** [mpv-player/mpv#9414]
## Important information:
- mpv rebuilt from source, c478a1efbaf0ccee46d11036be6b921e5a4d5036
- libplacebo rebuilt from source, 72cd260ad7d5aa564ff5e68caf16ec2633f3460e
- Linux

## Reproduction steps:
- add linear-downscaling or linear-upscaling or profile=gpu-hq to mpv.conf
- open an HDR10 video

## Expected behavior:
Everything works fine, like without those options

## Actual behavior:
Highlights are clipped

## Sample files:
https://www.youtube.com/watch?v=LXb3EKWsInQ

**Comment by haasn** [comment]
Can you fill out the issue template?

**Comment by epicfilmmaker93** [comment]
Sorry, done now

**Comment by haasn** [comment]
Can't reproduce on my end. Screenshots?

**Comment by epicfilmmaker93** [comment]
Sorry, my mistake, it only happens with this glsl shader: https://gist.github.com/igv/36508af3ffc84410fe39761d6969be10

Should I close this issue or just rename it?

**Comment by haasn** [comment]
As the script says, it requires `linear-downscaling=no`.

I don't think there's anything I can do on my end. In `gpu-next`, HDR is represented using out-of-range values (below 0.0 or above 1.0). The script, in several places, explicitly clamps its input to the range `[0.0, 1.0]`. This clips highlights by design.

You need to ask igv to update the script.
