### ISSUE TITLE
[vo=gpu-next] Add error diffusion dithering

### ISSUE THREAD

**Issue by epicfilmmaker93** [mpv-player/mpv#9415]
Not mentioned in #8799, but console output says that error diffusion dithering is not currently implemented for vo=gpu-next, so here is an issue for that

**Comment by haasn** [comment]
I personally don't see the value in error diffusion dithering, so I'm unlikely to work on this. Why not just use `--dither=fruit`?

**Comment by epicfilmmaker93** [comment]
Error diffusion is a higher quality algorithm, and it is especially noticeable if you look at gradients. Try yourself with 6 bit RGB here: https://doodad.dev/dither-me-this/. I understand it will take some time to implement, but please consider doing it. Thanks

**Comment by haasn** [comment]
Sure, but 6-bit RGB is an excessively extreme example, corresponding to `--dither-depth=2`. Try with 24-bit RGB for a more realistic use case. Or even with 18-bit RGB (corresponding to a very low quality, ancient, 6-bit TN panel).

That tool doesn't even offer those settings.

**Comment by epicfilmmaker93** [comment]
Yes, but I think that picture quality even on true 8 bit displays would benefit from good dithering, especially with HDR movies

**Comment by haasn** [comment]
> Yes, but I think that picture quality even on true 8 bit displays would benefit from good dithering

Until I see a screenshot otherwise I think it's entirely in your head.

> especially with HDR movies

8-bit HDR isn't a thing I've ever seen, HDR is practically always 10 bits or more.

**Comment by epicfilmmaker93** [comment]
>Until I see a screenshot otherwise I think it's entirely in your head.

I've just tested 10 bit gradients with fruit dithering to 8 and 6 bit and it's pretty good, so now I think I'm wrong. Should I close this issue then?

>8-bit HDR isn't a thing I've ever seen, HDR is practically always 10 bits or more.

I mean watching 10 bit HDR movies on 8 bit or even 6 bit display

**Comment by haasn** [comment]
>  Should I close this issue then?

Unless you can produce a screenshot where error diffusion provides a visible advantage, I'd be inclined to close this as wontfix, yeah.

> I mean watching 10 bit HDR movies on 8 bit or even 6 bit display

If you're doing that then you're also tone-mapping to SDR which happens *before* dithering.

**Comment by epicfilmmaker93** [comment]
Ok then, thanks for clarifying, closing this issue

**Comment by bjin** [comment]
> Btw, I think you can still port the mpv vo_gpu diffusion algorithm to a user shader and use it with --gpu-shaders if you really want it. 

error diffusion filters can't be ported to user shader at this moment. The main loop depeds on video and screen dimension and is hardcoded. It also need to hook another "DITHER" target and require fallback to fruit when out of shared memory.

@haasn besides the argument about error diffusion overkilling or not, please consider porting it to libplacebo. The implementation is fairly standalone and I image it won't take much effort. I personally don't now much about libplacebo codebase, otherwise I will take the time to do it myself.

The error diffusion implementation in mpv is the only FULL gpu implementaion on video plager that I know. I don't know about the current version of madvr, but when madshi introduce this feature, he implemented it with compromises (see the q&a thread reply after announcement of the new feature).

**Comment by haasn** [comment]
Btw, have you ever thought about doing something like tiled error diffusion + some naive blue noise dithering for the edges?

**Comment by bjin** [comment]
tiled error diffusion looks worse than blue noise (at least for the straight forward implementation). I don't see any benefits of it.

**Comment by haasn** [comment]
> @haasn besides the argument about error diffusion overkilling or not, please consider porting it to libplacebo. The implementation is fairly standalone and I image it won't take much effort. I personally don't know much about libplacebo codebase, otherwise I will take the time to do it myself.

I would take a merge request for it. The main shader code should be basically compatible (we use the same `GLSL` macro, so no changes there). The main effort of porting it would be adding the user-facing APIs, documentation, and a tiny bit of overhead for negotiating shared memory and such. The main entrypoint would probably be `src/shaders/colorspace.c` (and corresponding header), see the existing dither code there (in `pl_shader_dither`). Add it to `pl_dither_method` (and any extra parameters you need to `pl_dither_params`). 

(Btw, looking at the current mpv code, why do you do an extra fbo indirection before and after `pass_error_diffusion`? Is that only so you can control the group size?)

That said, while I can see the feature having its place in libplacebo (which is more of a general-purpose GPU image processing library than mpv), I still think that error diffusion only has benefits when dithering to such a low bit depth that gamma correction starts becoming a relevant factor, so it might be a good idea to also update the code to take into account the transfer curve when estimating the error to be propagated, if that's possible.

**Comment by bjin** [comment]
> why do you do an extra fbo indirection before and after pass_error_diffusion?

the `finish_pass_tex ()` call after `pass_error_diffusion` because in mpv the last render pass in vo_gpu somehow can't be compute shader, an extra copy pass is necessary.

> so it might be a good idea to also update the code to take into account the transfer curve

It probably won't work with my implementation. There are multiple assumptions on error propagation I made for optimization, one of them is range of propagated error is in `[-0.5/d, 0.5/d)` so I can encode them into binary representation. This won't hold when taking transfer curve into account.

**Comment by haasn** [comment]
(You could hard-code a gamma curve of 2.2 and retain that assumption while still improving gamma correctness of dithering)

**Comment by bjin** [comment]
> why the finish_pass_tex before dithering?

IIUC, a finish_pass_tex call is always necessary before a compute shader rendering pass in mpv vo_gpu.

My understanding is that:

1. if the previous pass is fragment shader, two passed can't be rendered in one pass for obvious reason.
2. two compute shader pass can't be rendered altogether because they both rendered to `output` shader.

> since the error will only ever get smaller (for progressively darker colors)

I see, assuming a fixed gamma value is always possible and only minimal shader code change is required.

**Comment by bjin** [comment]
> improving gamma correctness of dithering

Hmm, I take some thought and found that I don't quite understand the definition of the mentioned correctness.

Take transfer curve function `y=f(x)`(and `x=f'(y)` for recovery function), `error(x)` could be defined as `dither(f(x))-f(x)`. But you can't apply recovery function `f'(y)` to `error(x)` since it can be negative. And you can't apply `dither()` directly to `x` as well, since the purpose of dithering is rounding `y` to discrect amount of values, not `x`. This is especially true for non-linear `f(x)`.

**Comment by bjin** [comment]
I get your points here, but I feel it's over complicated and probably only matters much for HDR passthrough.

Please also note that dithering is done on RGB instead of just luma, a sound solution involving dither slope over multiple-variable space is rather complicated.

**Comment by ObsessedHacker** [comment]
So `dither=error-diffusion` won't be implemented to `vo=gpu-next`?
I'm not an expert but as I understand it offers greater quality and colors, and since my screen is 12bit ( `dither-depth=12` ) it shows correct colors.

My screen:
![image](https://user-images.githubusercontent.com/13978119/142807548-80e38970-ba9a-4bf5-aa10-fdbef581c0f7.png)

In case it won't ever be implemented - what would be the next best setting for dithering? fruit? ordered?

**Comment by haasn** [comment]
> So `dither=error-diffusion` won't be implemented to `vo=gpu-next`?

Not unless somebody writes code for it.

>  I'm not an expert but as I understand it offers greater quality and colors, and since my screen is 12bit ( `dither-depth=12` ) it shows correct colors.

At 12 bits you could probably disable dithering entirely without noticing a difference.

> In case it won't ever be implemented - what would be the next best setting for dithering? fruit? ordered?

`fruit`
