### ISSUE TITLE
Youtube links are unusably slow.

### ISSUE THREAD

**Issue by martin-sweeny** [mpv-player/mpv#9493]
### Important Information

> Provide following Information:
> - mpv version
> - Linux Distribution and Version
> - Source of the mpv binary
> - If known which version of mpv introduced the problem
> - Window Manager and version
> - GPU driver and version
> - Possible screenshot or video of visual glitches
> 
> If you're not using git master or the latest release, update.
> Releases are listed here: https://github.com/mpv-player/mpv/releases

![image](https://user-images.githubusercontent.com/3329959/142744149-c6d6a545-fdc6-4201-9bb7-a2a05b8269f2.png)
![image](https://user-images.githubusercontent.com/3329959/142744216-4af8ee88-ab1a-4f32-a0d7-744778128256.png)

### Reproduction steps

1. Run `mpv https://youtu.be/watch\?v\=dQw4w9WgXcQ --no-config`
1. Observe it's excessively slow load

> Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.
> 
> Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

1. Run `mpv https://youtu.be/watch\?v\=dQw4w9WgXcQ`
1. Observe it's excessively slow load

### Expected behavior

For the video to stream at approximately the same speed as a browser.

### Actual behavior

The video streams unusably slowly.

### Log file

> Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

[Available here](https://bin.snopyta.org/?a69ddefe212aeae9#CFEiRt9bNwWirchdDEKyvU9d5pricp3SYTmFdMHfmmKf). 
Password is `ec475d1351f7ab30d4a4b18b`

The issue will be closed for ignoring the issue template.

### Sample files

> Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
> or similar sites. (Only needed if the issue cannot be reproduced without it.)
> Do not use garbage like "cloud storage", especially not Google Drive.

Related to #9468

**Comment by LaserEyess** [comment]
Your logs show some classic issues with youtube-dl only buffering at ~20 kbps. This is really out of mpv's control for two reasons:

1. The URL is fetched by youtube-dl and if google doesn't like the URL you're using to fetch it and tries to throttle it, you're SoL
2. Actual downloading of the data is done by ffmpeg (libavformat), mpv has no http code

Try [yt-dlp](https://github.com/yt-dlp/yt-dlp), it uses youtube's android API instead of the web one, and I've had *much* better success with videos downloading. mpv has native support for yt-dlp as a dropin for youtube-dl in 0.34. Otherwise, there's not much else mpv can do here, because google hates you and wants you instead to watch about 3 minutes of ads for every video you watch.
