### ISSUE TITLE
How to remove the logo of Christian commemoration

### ISSUE THREAD

**Issue by b4zz4** [mpv-player/mpv#9548]
I prefer atheist software

**Comment by garoto** [comment]
>  How to remove the logo of Christian commemoration

Complaining on Twitter seems to work for most people that feel oppressed and offended nowadays by any topic. Just don't forget to mention the official @mpv_player account when you do so.

**Comment by garoto** [comment]
Make a tweet about it.

**Comment by TheAMM** [comment]
Add `greenandgrumpy=yes` in your `osc.conf`.

The hat is not intended to be religious or christian, just a festive easter (heh) egg. If it calms your nerves, the feature was written by an atheist with no intents beyond a bit of fun, doing wm4 even the smallest of favors, and including an easter egg within an easter egg (the very *specific* hat used here - a cookie to those who manage to recognize it!)
My condolences if the hat reminds you of religion or a specific religion or the proliferation commercialism or whatever negative stuff you may personally associate with December festivities instead of the happy parts. Luckily it's easily disabled!

**Comment by CounterPillow** [comment]
The hat is needed for feature parity with VLC.

**Comment by haasn** [comment]
>  How to remove the logo of Christian commemoration

Hi,religious appropriation is not appropriate for this issue tracker. Please don't try misrepresent a securalized national holiday based on a pagan festival as a Christian invention.

**Comment by b4zz4** [comment]
> The hat is needed for feature parity with VLC.

It's the reason I stop using VLC and go to mplayer years ago.

**Comment by Hrxn** [comment]
> > The hat is needed for feature parity with VLC.
> 
> It's the reason I stop using VLC and go to mplayer years ago.

If that's not a reason to roll your own fork of mpv, then tapdancing Christ, I don't know what the hell is...
