### ISSUE TITLE
Mac: mpv should be listed as capable handler to open APNG (animated PNG) files which it indeed can play back!

### ISSUE THREAD

**Issue by porg** [mpv-player/mpv#9574]
### Important Information
- mpv 0.34.0
- macOS 12.6.1
- Installed via HomeBrew

### My compliments first
- mpv played back an animated PNG which I had created with [apngasm](https://github.com/apngasm/apngasm) just fine
- In contrast to
  - QuickLook which showed drastic playback artefacts and glitches
  - Preview.app which showed it as an image series
  - QuickTime Player which did not recognize it as an animation at all and instead jumped right into the Create Image Sequence workflow.

### Reproduction
- In the Finder select an animated PNG file with a .png file extension.
- Right click the file, a context menu opens.

### Expected
- The "Open with" tree should list mpv as an app capable of handling that file type

### Actual
- mpv is not listed there.
- Info.plist > CFBundleDocumentTypes > does not list PNG or APNG there.

**Comment by Dudemanguy** [comment]
Isn't this entirely up to your OS settings? macOS is a special snowflake so maybe it's different there dunno.

**Comment by porg** [comment]
## Let me clarifiy
* On macOS applications get installed into `/Applications/`
* So for mpv this is `/Applications/mpv.app/`
* `.app` is a so called application bundle. A folder with an `.app` suffix.
  * The Finder shows bundles to the user as a file, but on the filesystem in reality it is a folder.
  * In that folder are all the resources, libraries and the executable(s), sometimes for multiple architectures (Intel, Intel 64bit, Apple Silicon).
  * Among the resources is also a manifest file, always called `Info.plist` , plist as in "property list" in XML format.
* In `Info.plist` there's a section "CFBundleDocumentTypes".
  * If this section lists certain file types (by extension, MIME-type or UTI (Uniform Type Identifier)) then this tells the OS "I am capable of opening (viewing, not necessarily writing) these file types".
* When adding/removing `.app` bundles to anywhere on your Mac the OS scans the manifest and updates the file-type/app catalog on the fly.

## Default Behavior & User Customization
- If a file type can only be handled by one app on the Mac, then double clicking will automatically open it with this one.
- If multiple apps can handle it
  - then you can either open with a certain app per instance by:
    - using context menu "Open with"
    - or drag-n-drop onto a particular app
    - or in Finder use Menu > File > Info and in the dialog set "Open with" to your desired app (which is persisted in the metadata of that particular file, next double click will open it with that chosen app, by this you can make exceptions to the general handler app on a file basis.)
  - or permanently change the file type to app handler association by: File > Info > "Open with" > Your desired app, then additionally click the "Change all…" button.
- The  "Open with" dialogs only show apps knowing to be capable to handle that file type. BUT you can also choose an arbitrary app to override. This is the last resort for users, if developers did not supply file-types correctly in the `Info.plist`.

## TODO
- Please make sure that APNG is in the `CFBundleDocumentTypes` section of the `Info.plist`.

**Comment by Dudemanguy** [comment]
Oh I see, there is indeed a `Info.plist` in the osxbundle. I'll ping @Akemi since this is his wheelhouse.

**Comment by ValZapod** [comment]
Please note that APNG was recently fixed in ffmpeg and it still has some strange issues, see

Crome implementation is better.

**Comment by Akemi** [comment]
@ValZapod please stop littering issues with unrelated crap.

**Comment by Akemi** [comment]
strictly speaking mpv is a video and audio player with subtitle support. mpv is not an image viewer. even so it can open various image formats due to ffmpeg support, the image support is not perfect and some assumptions are being made.

we don't currently have any image section in the info.plist and neither does the .desktop file for linux. i believe the general consensus atm is to not advertise mpv as an image viewer.

if the general situation and opinion changes we can reconsider adding image formats, but for now i will close this.

**Comment by porg** [comment]
- APNG is a file format for "moving images" aka "movie" aka "video".
- It is wrong to consider it an image format.

**Comment by Akemi** [comment]
so we disagree on the terminology. imo it's not worth arguing about this, so i won't go into detail.

the decision was made from a technical standpoint and that doesn't change.

**Comment by Akemi** [comment]
simplified, nearly all support for any formats, codecs, container, etc comes from ffmpeg. we just pass the data to ffmpeg. the support depends on the ffmpeg version and with what features it was build with. we are not forcefully restricting the features of ffmpeg. so mpv just automatically supports 'anything' thrown at it.

theoretically the info.plist would need to be dynamically generated by the features the linked ffmpeg supports. as of now the info.plist is neither complete nor completely right in all circumstances (eg it could advertise formats that aren't supported by that specific build).

technically all images are handled as video streams, with a duration and frame rate etc, which is kinda wrong. we believe mpv should first properly handle image formats, before we 'advertise' it as an image viewer. there are also some other issues that need to be fixed, like tiled rendering for example. anyway apng is technically closer to an image format because of it's roots, being an extension of the png format, than a video format and is handled internally like this.

if/when we sort out these problems and deem the experience as appropriate we will reconsider.

**Comment by porg** [comment]
- Thanks for laying it out that clearly.
- Well documented now, for anyone looking for it!
