### ISSUE TITLE
Is there a way to use autoload with save position?

### ISSUE THREAD

**Issue by WilsonNet** [mpv-player/mpv#9586]
When I use autoload it erases the last saved position.
If I advance and goes back, it goes back to `00:00`

I assume this is the intended behavior, since people like to watch things from the start.

**Comment by Dudemanguy** [comment]
Could you clarify what you mean? Are you saying that `save-position-on-quit` doesn't work when using autoload.lua?

**Comment by WilsonNet** [comment]
Yes, kind of.
I have `save-position-on-quit=yes` on my `mpv.conf`
If I open `video-01.mkv` and quit on `15:00` and reopen it. It's there.

But if inside the video, I use autoload's functionality to go to the next video by pressing the button at `15:00`, and come back, it will go back to `00:00`.

**Comment by vitormathews** [comment]
Did you find a solution? I'm having the same problem.

**Comment by WilsonNet** [comment]
> Did you find a solution? I'm having the same problem.

Nope, I use VLC for playlists nowadays and PotPlayer on windows.

**Comment by Dudemanguy** [comment]
>But if inside the video, I use autoload's functionality to go to the next video by pressing the button at 15:00, and come back, it will go back to 00:00.

Sorry I missed this. If by "pressing the button" you just mean going forward in the playlist, then `save-position-on-quit` isn't triggered at all (because you aren't actually quitting). A potential workaround would be to use the `write-watch-later-config` command to save the position manually before moving to the next item in the playlist.
