### ISSUE TITLE
DirectX 12

### ISSUE THREAD

**Issue by ObsessedHacker** [mpv-player/mpv#9601]
https://devblogs.microsoft.com/directx/announcing-new-directx-12-feature-video-encoding/

DirectX 12 will be added to mpv?

**Comment by haasn** [comment]
Seems redundant with Vulkan Video.

**Comment by jeeb** [comment]
For video decoding we already have d3d11va that spits out d3d11 surfaces which can be put onto d3d11 rendering (although I haven't yet succeeded in passing the d3d11 context to libplacebo successfully so no vo=gpu-next with it yet :< ), and Vulkan video is incoming for both decoding and encoding. Vulkan also has support for d3d11 surfaces - in theory at least - so some sort of interoperability from d3d11va to Vulkan rendering might be possible.

And finally, the primary meaning for that is to have a d3d encoding API similar to Vulkan video. And mpv is not really an encoder. FFmpeg might gain support for this API if someone cares about it for encoding (since apparently you can import d3d11 surfaces as d3d12 surfaces), but personally I don't think there's too much use of this in the context of mpv.

**Comment by ValZapod** [comment]
Chrome already added it via Directx11on12 and libpacebo also has some plans. Nvidia added it into video encode sdk.
