### ISSUE TITLE
Cant Open any YouTube link

### ISSUE THREAD

**Issue by hexxone** [mpv-player/mpv#9624]
### Important Information

Provide following Information:
- mpv version: `latest`
- Windows Version `10 lateest updates etc`
- Source of the mpv binary `update.ps1`
- If known which version of mpv introduced the problem `latest`

- video ===>  https://streamable.com/j134ub

### Reproduction steps

Drag & Drop any YouTube Link like:
https://www.youtube.com/watch?v=Z-eooUWgtHw

The mpv player shows the thumbnail for a second, then just crashes.

### Expected behavior

Play the video, or do just anything at all

### Actual behavior

Minimizing & Crashing

### Log file

There is no log getting created.
No output written to the console.
Nothing ???

**Comment by 01yakiek** [comment]
It appears you may be missing [youtube-dl](https://github.com/ytdl-org/youtube-dl) or [yt-dlp ](https://github.com/yt-dlp/yt-dlp) binaries.
Those are needed to play youtube videos.

You may need get a little advanced and configure mpv through command-line or adding mpv.conf in the same directory as mpv, then add options there.

For example putting this inside mpv.conf;
`
script-opts=ytdl_hook-ytdl_path="C:\babayada\yt-dlp\yt-dlp.exe"
`

You may point the conf if you need it to be somewhere else, point to its default config directory with other config files you may need;
`
START "" "mpv.exe" --force-window=yes --idle --config-dir="C:\bebebebebe\config_directory"
`
The --idle and --force-window=yes helps keeping the window open.

Incidentally, you may also need [Ffmpeg](https://www.ffmpeg.org/download.html) binaries to play youtube, I think. Download that and point to its extracted bin folder as follows;

`
ytdl-raw-options=ffmpeg-location="C:\bibobubu\ffmpeg\bin"
`

Some of these options are found in ffmpeg and youtube-dl/yt-dl documentation.
As for mpv's, it is found [here](https://mpv.io/manual/).

**Comment by bamper45** [comment]
@01yakiek I can't understand either. I have yt-dlp in C: /Temp/yt-dlp.exe (I installed it according to some instructions) and ffmpeg in C: / ffmpeg (there are 3 files with exe extension). Mpv.conf in user / appdata / roaming / mpv by default.
  What do i do? There are no bin.
  There are no instructions, I cannot understand

**Comment by CounterPillow** [comment]
Put yt-dlp.exe next to mpv.exe. That's literally all you have to do.

**Comment by bamper45** [comment]
@CounterPillow Remove from the original folder or copy another one?

**Comment by 01yakiek** [comment]
@bamper45 Yes.

Okay let me explain if anyone else is still confused.

Mpv does not have the ability to detect youtube-dl, yt-dlp, ffmpeg, config files, or etc everywhere EXCEPT in two locations; the default config location "%appdata%\mpv", AND its own directory where the mpv.exe is.

This is why I said configure mpv to tell it where those files are, it's best way to avoid all headaches. This info is written in the mpv's reference manual link I gave above.

As for yt-dl config, the [hyperlink](https://mpv.io/manual/stable/#options-ytdl-path) reads as follows:
```
ytdl_path=youtube-dl
    Configure paths to youtube-dl's executable or a compatible fork's.
    The paths should be separated by : on Unix and ; on Windows.
    Mpv looks in order for the configured paths in PATH and in mpv's config directory.
    The defaults are "yt-dlp", "yt-dlp_x86" and "youtube-dl".
    On Windows the suffix extension ".exe" is always appended.
```

The info above mentions the [PATH](https://en.wikipedia.org/wiki/PATH_(variable)), which is the window's environment path that gives programs ability to know where most used binaries are.

For example if you installed ffmpeg via the installer instead of extracting the zip as portable use, the path to the ffmpeg's bin folder will be added to the %PATH%. This is same goes for yt-dlp.exe.

HOWEVER, as of writing this, yt-dlp does not release with installer for windows unless you're using python, which then you can install via python's pip.

Which means without adding yt-dlp to the path that is done by installing via installer, mpv has no way to tell where yt-dlp is installed UNLESS you specifically points its config to the location, OR put youtube-dl.exe/yt-dlp.exe in same folder as mpv.exe, you can also put it in "%appdata%\mpv" if you choose to.

You can find the information about how it handles environment path can be found all the way at the bottom of the [reference manual](https://mpv.io/manual/stable/#files-on-windows).

Thank you.

**Comment by bamper45** [comment]
@01yakiek 
Thank you, very clear and detailed.  But one more question, I have installed yt-dlp also for downloading videos from youtube.  So you don't need to delete from the original folder if you want to download a video?  Sorry for the meticulousness, but I want to understand once and for all, because I have been looking for answers for a long time.

**Comment by 01yakiek** [comment]
@bamper45 No worries. I am quite happy to help!

Well, it depends on how do you download videos via yt-dlp.exe. Because I don't know how to do you use yt-dlp to download videos.

For example if you use some kind of third-party software that specifically configured to detect yt-dlp only on "C:/Temp/yt-dlp.exe", then I suppose you should keep it there. Unless the software has the option to point to where the new yt-dlp.exe location is.

Unless you're an advanced user write your own batch, powershell, python, or some other languages to launch yt-dlp.exe specifically configured on "C:/Temp/yt-dlp.exe", then you can leave it there untouched and just duplicate yt-dlp.exe, one for download-videos, and one for mpv. Or modify it to point it to the new yt-dlp.exe location.

Or, you could also reorganize your file structures and use relative paths to make everything portable:
![2021-12-24_05 34 38_Friday](https://user-images.githubusercontent.com/7377351/147293295-5cc10288-fd9a-456d-b589-c9fcb2d9197d.png)

For example the screenshot above, I keep ffmpeg, mpv, and yt-dlp in separate folders. Each have their own use and function.

- Ffmpeg folder - For encoding, decoding, recording, mixing, demuxing, concat, editing media files, etc.
- Mpv folder - For watching videos, listening to music, watch streams, watch live streams, etc.
- yt-dlp folder - For downloading videos, downloading live streams, downloading aprons, etc.

Then each of these can be configured in a way that they are all connected through relative paths, so they can make use of each other.

mpv launch .bat command line inside mpv folder (only if you don't have ffmpeg installed in %PATH%), this is not permanent change to the %PATH%, only scoped to the running process:
```
SET PATH=%~dp0..\ffmpeg\bin;%PATH%
"mpv.exe"
```

mpv.conf inside mpv folder:
```
script-opts=ytdl_hook-ytdl_path="..\yt-dlp\yt-dlp.exe"
ytdl-raw-options=ffmpeg-location="..\ffmpeg\bin"
```
yt-dlp.conf inside yt-dlp folder:
```
--ffmpeg-location "..\ffmpeg\bin"
```

Then you can quite literally jam the example portable_programs folder containing ffmpeg, mpv, and yt-dlp inside thumbdrive/flash drive/sd card/whatever portable storage and it will work right off the bat portable across supported windows!

Thank you.

**Comment by bamper45** [comment]
@01yakiek I think I got it, thanks for the detailed explanation!

**Comment by Sorin-M-Oprea** [comment]
Hi, I have FFMPEG in PATH, system install so if I pop-up the cmd and type "ffmpeg" I get help output with ffmpeg version.
I have placed ytdl near mpv.exe and also linked it through ytdl_hook-ytdl_path="C:\Program Files\mpv\yt-dlp.exe" but I still cannot play youtube videos.

**Comment by 01yakiek** [comment]
@Sorin-M-Oprea You forgot to use --script-ops. ytdl_hook-ytdl_path can only be used in the --script-ops as far as I could tell as documented [here](https://mpv.io/manual/master/#options-ytdl).

Taken from the hyperlink documentation as of writing this:
```
This accepts a set of options, which can be passed to it with the --script-opts option (using ytdl_hook- as prefix):
```

So the correct way is:
```
--script-opts=ytdl_hook-ytdl_path="C:\Program Files\mpv\yt-dlp.exe" 
```

**Comment by CounterPillow** [comment]
There is a lot of bad advice in here, so let me clarify a few things:

1. if you place yt-dlp.exe next to mpv.exe, you do not need to set the ytdl_path. Setting it to an incorrect path in fact prevents mpv from finding yt-dlp
2. You do not need to install ffmpeg at all.
3. You do not need to change anything about your PATH

All you have to do is place yt-dlp.exe next to mpv.exe. Everything else in this issue is unhelpful hoops you don't need to jump through, and which will make it not work if you jump through them the wrong way.

**Comment by Sorin-M-Oprea** [comment]
I fixed my issue by downloading a new MPV version. Thanks for all the advice.
