### ISSUE TITLE
.TS video file format jiggering - is there a solution in MPV

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#9639]
This set `hr-seek=yes` works well for almost all video formats.
Today I needed to play the `.TS` video file format and I see none of the `seek` options doesn't help for precisely seeking.
There are lots of `.TS` video file formats. MPV and also VLC players do jiggering when I play them.

**Comment by jeeb** [comment]
MPEG-TS is a streaming file format without an index as it is meant for linear broadcast, you really can't expect too great exact seeking with it unless you index it first (you can see Vapoursynth with ffms2 as an example of something that first goes through the file and indexes it in order to have frame-exact seeking).

We could add progressive re-seek based on something, but rather than time it'd be based on byte offsets. Generally speaking, it doesn't seem like worth the extra effort.

My general recommendation is that you remux that content into either MP4 or Matroska, and then seek in those (you can utilize `ffmpeg` or `mkvmerge(gui)` to do that). If you need to keep the original files around, so be it. I also keep original files around, but then if I actually have to actively utilize the footage without indexing, I remux into a container that has an index.

**Comment by Max-Enrik** [comment]
Thank you for the good explanation.

**Comment by tmm1** [comment]
You could try this: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20190507032623.80375-1-ffmpeg@tmm1.net/

**Comment by Max-Enrik** [comment]
Thank you a lot.
I never used Patch. I have to research it and then set it up.

**Comment by Max-Enrik** [comment]
I see I have to change that two lines of code.
But I don't know what to do it afterward.

_This kind of thing is for people who have developer knowledge._

**Comment by ValZapod** [comment]
@tmm1 Can your patch fix LG CHESS sample here?  https://trac.ffmpeg.org/ticket/9412 Thanks.

**Comment by ValZapod** [comment]
@tmm1 so it does not fix it, I checked :(

**Comment by ValZapod** [comment]
@tmm1 There is also this commit! 
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20190831101039.2179-2-fumoboy007@me.com/
