### ISSUE TITLE
`os.tmpname()` crashes mpv

### ISSUE THREAD

**Issue by archiif** [mpv-player/mpv#9644]
### Important Information

Provide following Information:
- mpv version: mpv 0.34.0-116-gd92cf77be5
- Windows Version: Microsoft Windows [Version 10.0.19043.1415]
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files

### Reproduction steps

1. Temporarily move your config directory somewhere else and create a fresh and empty config directory
2. Open a media file with mpv, it should open successfully
3. Add a lua script to your new config directory with the following line: `os.tmpname()`
4. Try to open another media file, mpv will now crash

### Expected behavior
mpv should not crash

### Actual behavior
mpv crashed

### Log file
- With `os.tmpname()`: https://0x0.st/orQt.txt
- Without `os.tmpname()`: https://0x0.st/orQv.txt

**Comment by avih** [comment]
I can't reproduce the issue, with latest luajit and the following script:
```lua
print(os.tmpname())
```
where invoking `mpv --idle --script=tmpname.lua` prints something like `\s6vc.` (which is a bit weird, but I guess that's how it is).

The log doesn't show anything special, and unless you can demonstrate otherwise, I don't see how it can be an mpv issue.

Also, luajit code for `os.tmpname` has not changed in 12(!) years: https://github.com/LuaJIT/LuaJIT/blame/20f556e53190ab9a735b932f5d868d45ec536a70/src/lib_os.c#L94

So I don't think it's a luajit issue either, but it's still possible.

I'm closing now because I find it highly unlikely that `os.tmpname` crashes mpv.

It's possible that something else crashes, but I can't tell without seeing an actual minimal script to reproduce the issue, and I can't reproduce it on my own.

**Comment by avih** [comment]
Actually, I can reproduce a "segmentation fault" with @shinchiro latest build mpv-x86_64-20211226-git-d92cf77.7z , however, there are no debug symbols available (latest symbols are from 2019 here https://sourceforge.net/projects/mpv-player-windows/files/debug-symbol/ ), so I can't check where's the crash.

I'm assuming it was some bug at luajit, and hopefully the next build will have that fixed. If not, then we'll need debug symbols (inclusing of luajit, though it could be hard to tell, jit is hard to debug...).

Keeping it closed for now, please report after the next shinchiro build.

**Comment by archiif** [comment]
On the way of trying to solve the issue, I discovered that calling the C function directly with `NULL` for some reason returns saner temp paths on Windows (`C:\Users\name\AppData\Local\Temp\sboc.0`, etc.). It also doesn't crash on the latest shinchiro build, so I'll just use that for now.
```lua
local ffi = require("ffi")
ffi.cdef[[
    char *tmpnam( char *filename );
]]
local p = ffi.gc(ffi.C.tmpnam(nil), ffi.C.free)
print(ffi.string(p))
```

**Comment by avih** [comment]
FWIW, the crash is still happens with `mpv-x86_64-20220109-git-777628e.7z`.

And I still can't reproduce the crash with my own build - not with luajit 2.1 latest (a91d0d9), and not with luajit master latest (e73916d).

I'm now wondering, maybe @shinchiro luajit patch https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/luajit-0001-add-win32-utf-8-filesystem-functions.patch is incompatible with some recent luajit changes, which causes it to crash?

**Comment by avih** [comment]
I just tested older @shinshiro builds, and this issue started nearly a year ago:

OK: mpv-x86_64-20210103-git-3e175df
OK: mpv-x86_64-20210228-git-d1be8bb

CRASH: mpv-x86_64-20210316-git-5824d9f
CRASH: mpv-x86_64-20210404-git-dd86f19
CRASH: mpv-x86_64-20210502-git-39630dc
CRASH: mpv-x86_64-20211226-git-d92cf77
CRASH: mpv-x86_64-20220109-git-777628e

So the last working build is 2021-02-28 and the first crashing build is 2021-03-16 - nearly a year ago.

What happened between these dates?

**Comment by avih** [comment]
@shinchiro I tried to apply your patch https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/luajit-0001-add-win32-utf-8-filesystem-functions.patch to luajit master, and it applied cleanly but then failed to build. First errors (there are many more):
```
lj_fs_io.c: In function 'get_file_ids_win8':
lj_fs_io.c:107:5: error: unknown type name 'FILE_ID_INFO'
     FILE_ID_INFO ii;
     ^
lj_fs_io.c:108:10: warning: implicit declaration of function 'GetFileInformationByHandleEx' [-Wimplicit-function-declaration]
     if (!GetFileInformationByHandleEx(h, FileIdInfo, &ii, sizeof(ii)))
          ^
lj_fs_io.c:108:42: error: 'FileIdInfo' undeclared (first use in this function)
     if (!GetFileInformationByHandleEx(h, FileIdInfo, &ii, sizeof(ii)))
                                          ^
```

Would you mind helping here? This crash issue affected your builds for nearly a year now, and I can't reproduce it, and also can't test with your patch because it fails to build.

Could you please remove that patch and provide a test build?

**Comment by archiif** [comment]
Do you mind reposting that as an issue directly to shinchiro's repository? Do @ really works if he's not a participant in this thread?
Also, my solution above doesn't actually work so I just resorted to calling an external program to generate temp names for now...

**Comment by avih** [comment]
You can open an issue there and link here.

**Comment by avih** [comment]
FWIW, 3rd party builds using shinchiro's cmake setup also have this segfault. Tested: https://github.com/zhongfly/mpv-winbuild/releases/tag/2022-01-28

**Comment by zhongfly** [comment]
> FWIW, 3rd party builds using shinchiro's cmake setup also have this segfault. Tested: https://github.com/zhongfly/mpv-winbuild/releases/tag/2022-01-28
> 
> For reference, I'm running from a cmd.exe shell: `mpv.com --no-config --script=tmpname.lua --idle`, where tmpname.lua is this script:
> 
> ```lua
> print("before")
> print(os.tmpname())
> print("after")
> ```
> 
> And it prints "before", but not "after", and exits without further printouts after about a second.
> 
> If I run it from a cygwin env, then it prints "before", a reasonable tmp name (e.g. `C:\cygwin64\tmp\sb48.0`), and "after", and exits with segmentation fault after about a second.

My latest ci build provide debug symbol now, hope that helps you solve this problem.
https://github.com/zhongfly/mpv-winbuild/actions/runs/1766562067

**Comment by avih** [comment]
> My latest ci build provide debug symbol now, hope that helps you solve this problem.
> https://github.com/zhongfly/mpv-winbuild/actions/runs/1766562067

Thanks.

Unless I'm doing something wrong though, I don't think it helps. Do note the warning "section .gnu_debuglink not found in D:\mpv-x86_64-20220129-git-4d3ebb9\mpv.debug", but I _think_ it loads the symbols anyway.

Here's the full session log:
```
D:\mpv-x86_64-20220129-git-4d3ebb9>gdb mpv.exe
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mpv.exe...Reading symbols from D:\mpv-x86_64-20220129-git-4d3ebb9\mpv.debug...
warning: section .gnu_debuglink not found in D:\mpv-x86_64-20220129-git-4d3ebb9\mpv.debug
done.
done.
(gdb) run --no-config --idle --no-video --script=tmpname.lua
Starting program: D:\mpv-x86_64-20220129-git-4d3ebb9\mpv.exe --no-config --idle --no-video --script=tmpname.lua
[New Thread 7780.0x2558]
[New Thread 7780.0x1f4]
[New Thread 7780.0x2950]
[New Thread 7780.0x2bf0]
[New Thread 7780.0x263c]
[New Thread 7780.0xdf0]
[New Thread 7780.0x1e50]
[New Thread 7780.0x3270]
[New Thread 7780.0x2678]
[New Thread 7780.0xfc8]

Thread 10 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 7780.0xfc8]
0x00007ff63e0003af in ?? ()
(gdb) bt
#0  0x00007ff63e0003af in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) bt full
#0  0x00007ff63e0003af in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

At this stage I'd simply try to remove the patch for luajit, because as far as I can tell it's otherwise direct upstream version, and that's the only modification which is being made to luajit at this build setup.

**Comment by avih** [comment]
@zhongfly note that in your most recent CI build https://github.com/zhongfly/mpv-winbuild/releases/tag/2022-01-30 the file `mpv-debug-x86_64-20220130-git-4d3ebb9.7z` is 535 bytes (unlike the link which you posted previously), so I guess something went wrong there.

**Comment by zhongfly** [comment]
> @zhongfly note that in your most recent CI build https://github.com/zhongfly/mpv-winbuild/releases/tag/2022-01-30 the file `mpv-debug-x86_64-20220130-git-4d3ebb9.7z` is 535 bytes (unlike the link which you posted previously), so I guess something went wrong there.

Yes, I'm also confused because I haven't modified any build settings, not even my repo has changed between these two builds

**Comment by zhongfly** [comment]
@avih  BTW, have you tried shinchiro's latest debug sumbol(`mpv-debug-x86_64-20220116-git-1ba0547.7z`) from  https://sourceforge.net/projects/mpv-player-windows/files/debug-symbol/ ?

**Comment by avih** [comment]
> edit: The size of the debug file is back to normal in the latest build( https://github.com/zhongfly/mpv-winbuild/actions/runs/1768840325 ), I have no idea about it

Hmm.. no idea either, but good that it's OK now. Thanks.

> @avih BTW, have you tried shinchiro's latest debug sumbol(`mpv-debug-x86_64-20220116-git-1ba0547.7z`)

No. I wasn't aware they're back (the previous one is exactly one year ago - I did look there not long ago), but I also don't think it would be different than with yours. I _think_ the symbols are fine, but I'm guessing that gdb is having a hard time figuring the stack at the luajit thread? (that's a guess).

As I said, I can't reproduce the issue with my builds with luajit, and I don't have time to debug 3rd party patches.

**Comment by avih** [comment]
> If I run it from a cygwin env, then it prints "before", a reasonable tmp name (e.g. `C:\cygwin64\tmp\sb48.0`), and "after", and exits with segmentation fault after about a second.

So this made me think - what does it depend on.

So I tried with a TMP var of 14 chars, and the crash is gone:
```
D:\mpv-x86_64-20220129-git-4d3ebb9>set TMP=C:\45678901234

D:\mpv-x86_64-20220129-git-4d3ebb9>mpv.com --idle --no-config --script=tmpname.lua
[tmpname] before
[tmpname] C:\45678901234\s7jc.0
[tmpname] after
Exiting... (Quit)
```

`(Quit)` is after few seconds without crash, where I pressed `q` to quit.

If I add one more char to the TMP value so that it's 15 chars, then it prints the name and crashes after about a second:
```
D:\mpv-x86_64-20220129-git-4d3ebb9>set TMP=C:\456789012345

D:\mpv-x86_64-20220129-git-4d3ebb9>mpv.com --idle --no-config --script=tmpname.lua
[tmpname] before
[tmpname] C:\456789012345\sbk8.0
[tmpname] after
# (mpv crashes here)
```

Making TMP longer keeps behaving the same (completes the printout, crashes after about a second) till it's 30 chars, but starting from TMP of 31 chars it only prints "before":
```
D:\mpv-x86_64-20220129-git-4d3ebb9>set TMP=C:\4567890123456789012345678901

D:\mpv-x86_64-20220129-git-4d3ebb9>mpv.com --idle --no-config --script=tmpname.lua
[tmpname] before
# (mpv crashes here)
```

So it's definitely a buffer overflow somewhere, which happens when the TMP var length is 15 chars or more, and the behavior changes further when it's 31 chars or more (it crashes earlier).

**Comment by avih** [comment]
So, that's the implementation of `os.tmpname` at luajit master:
```c
LJLIB_CF(os_tmpname)
{
#if LJ_TARGET_PS3 || LJ_TARGET_PS4 || LJ_TARGET_PSVITA
  lj_err_caller(L, LJ_ERR_OSUNIQF);
  return 0;
#else
#if LJ_TARGET_POSIX
  char buf[15+1];
  int fp;
  strcpy(buf, "/tmp/lua_XXXXXX");
  fp = mkstemp(buf);
  if (fp != -1)
    close(fp);
  else
    lj_err_caller(L, LJ_ERR_OSUNIQF);
#else
  char buf[L_tmpnam];
  if (tmpnam(buf) == NULL)
    lj_err_caller(L, LJ_ERR_OSUNIQF);
#endif
  lua_pushstring(L, buf);
  return 1;
#endif
}
```

For Windows (non-posix), it calls `tmpnam(buf)`, where `buf` is of `L_tmpnam` bytes (that's fine according to MSDN docs), and with my mingw that's 14 chars (I added a print of this value and compiled it and linked with mpv).

14 seems sufficient for the values I get with upstream luajit master, because it prints values such as this, regardless of the value which the vars TMP or TEMP hold (that's with my print of L_tmpnam):
```
D:\run\mpv64\test>set TEMP=c:\foo

D:\run\mpv64\test>set TMP=c:\bar

D:\run\mpv64\test>mpv.com --no-config --idle --script=tmpname.lua
[tmpname] before
L_TMPNAME: 14
[tmpname] \sdng.
[tmpname] after
Exiting... (Quit)
```

According to the msdn [docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/tempnam-wtempnam-tmpnam-wtmpnam?view=msvc-170) a value like this is valid for the current working directory.

However, with @shinchiro build, it does take the TMP var into account, and also it prints a full path (see the previous comment), like `C:\45678901234\s7jc.0` (this is already a buffer overflow even if it doesn't crash).

So something makes it both refer to the TMP var, AND return a full path. This doesn't fit into `buf[L_tmpnam]`, which results in a buffer overflow and then a crash.

I do suspect that it's from the utf8 names patch, but because I can't build with this patch then I can't confirm this hypothesis.

**Comment by shinchiro** [comment]
Unfortunately, you're wrong. Even the patch is applied or not, the crash still there. The patch didnt affect `os_tmpname`. This might be mingw bug as reported [here](https://sourceforge.net/p/mingw-w64/bugs/915/) .I didnt try to test `tmpnam` yet whether it works correctly or not in my system.

**Comment by rorgoroth** [comment]
Yeah ^
FWIW I did try this a few hours ago with & without the patch and it makes no difference.

**Comment by avih** [comment]
> This might be mingw bug as reported [here](https://sourceforge.net/p/mingw-w64/bugs/915/)

Good. It does seem to be the issue. Are you using clang? I thought you were using gcc...

**Comment by avih** [comment]
So, it seems that before VS2015, msvc behaved like my mingw does (short name which technically points to the root of the current drive, and is now documented to be valid for the current working directory), while with VS2015 and later it changed to return the full path like shinchiro's mingw does.

Search for "tmpnam" here https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015?redirectedfrom=MSDN&view=msvc-170

With VS2015 L_tmpnam is 260, which is presumably sufficient for the full path.

I'm guessing that mingw tried to change to the behavior of newer msvc with the full path, but forgot to ensure that L_tmpnam is bigger too to accomodate.

While the report linked earlier speaks of clang, and as far as I know shinchiro uses gcc, it does seem overall like a mingw bug, which will hopefully get fixed before their next release.

Closing as upstream mingw issue, and possibly a result of using mingw master rather than a stable release.

**Comment by rorgoroth** [comment]
>possibly a result of using mingw master rather than a stable release.

I use use stable mingw releases and the issue is present there. Nice investigative work anyway 👍

**Comment by avih** [comment]
For reference, for the following C program:
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv) {
    char buf[L_tmpnam] = {0};
    printf("L_tmpnam: %d\n", (int)L_tmpnam);

    if (tmpnam(buf)) {
        printf("tmp name: '%s' (%d+1 chars)\n", buf, strlen(buf));
    } else {
        printf("tmpnam error\n");
    }

    return 0;
}
```

I get the following results:

MSYS2 mingw (git, named 9.0.0.6373.5be8fcd83-1), cygwin mingw (seemingly 9.0.0), my mingw (6), all print a result like this, with same L_tmpnam of 14 and a short name:
```
L_tmpnam: 14
tmp name: '\s4hs.' (6+1 chars)
```

VS2015 `cl.exe` 64:
```
L_tmpnam: 260
tmp name: 'C:\Users\UNAME\AppData\Local\Temp\savk.0' (40+1 chars)
```

So even the MSYS2 mingw which uses git master has a name which fits the buffer. It remains unknown why the mingw at the cmake mpv build setup has small buffer and a long name which results in buffer overflow.

**Comment by avih** [comment]
> I use use stable mingw releases and the issue is present there

Use where? I tried 3 mingw setups, and all of them don't have this issue.

What's your mingw setup, and which issue exactly is present, and how did you test it?

**Comment by archiif** [comment]
@avih
> ```
> L_tmpnam: 14
> tmp name: '\s4hs.' (6+1 chars)
> ```
> 
> VS2015 `cl.exe` 64:
> 
> ```
> L_tmpnam: 260
> tmp name: 'C:\Users\UNAME\AppData\Local\Temp\savk.0' (40+1 chars)
> ```

Thanks, with this info I managed to fix my previous `ffi` workaround:
```lua
local ffi = require("ffi")
ffi.cdef[[
    void free( void* ptr );
    char *tmpnam( char *filename );
]]
local filename = ffi.new("char[?]", 260)
local p = ffi.gc(ffi.C.tmpnam(filename), ffi.C.free)
print(ffi.string(p))
```

Btw, even though the msdn docs says that a value like `\sdng.` is valid for the current working directory, this does not seem to be true from my experience. You can easily test the validity because of the predictability of lua's tmp filenames:
```
D:\subdir>luajit
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2021 Mike Pall. https://luajit.org/
JIT: ON SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> print(os.tmpname())
\sago.
> print(os.tmpname())
\sago.1
> io.open("D:\\subdir\\sago.2", "w"):close()
> print(os.tmpname())
\sago.2
> print(os.tmpname())
\sago.3
> io.open("D:\\sago.4", "w"):close()
> print(os.tmpname())
\sago.5
> print(os.tmpname())
\sago.6
>
```

**Comment by rorgoroth** [comment]
> What's your mingw setup, and which issue exactly is present, and how did you test it?

Sorry, it's the same as shinchiros toolchain but uses mingw 9.0.0 release, and I mean the OP issue about segfaults with the test lua script.

When I try what you mention in https://github.com/mpv-player/mpv/issues/9644#issuecomment-1025224642 I get the following output:

```
PS C:\Users\rorgo\test6> .\a.exe
L_tmpnam: 14
tmp name: 'C:\Users\rorgo\AppData\Local\Temp\s9z4.0' (40+1 chars)
```

**Comment by avih** [comment]
> When I try what you mention in [#9644 (comment)](https://github.com/mpv-player/mpv/issues/9644#issuecomment-1025224642) I get the following output:
> 
> ```
> PS C:\Users\rorgo\test6> .\a.exe
> L_tmpnam: 14
> tmp name: 'C:\Users\rorgo\AppData\Local\Temp\s9z4.0' (40+1 chars)
> ```

Much appreciated. That's the final piece of the puzzle we needed. I assumed it would result in this, but this was not guaranteed.

So something at this mingw setup is incorrect even for the stand alone test program, wihle in 3 other mingw setups which I tried (cygwin 9.0.0 mingw, msys2 git master mingw, MXE mingw 6) all didn't have this issue.

So it's up to debugging this mingw setup and how it differs from others.

**Comment by shinchiro** [comment]
Actually the bug came from configuring mingw to use `ucrt`. The bug gone if configured using default `msvcrt `

**Comment by rorgoroth** [comment]
Can confirm ^^
