### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9683]
The reason why I do not use "stealing codes" as title is that I do not have enough evidence. But I think mpv's devs should know it. 

Recently I was told that a new great video renderer which is called [JRVR](https://yabb.jriver.com/interact/index.php/topic,130657.0.html). Its source is not open. And JRVR is closely integrated with the MC player. Which block me to check what it is.

But I found the shaders they packed in the installers.
![Snipaste_2022-01-08_02-46-24](https://user-images.githubusercontent.com/41094733/148628875-af5ecdfa-7d04-4d85-a9fc-d1fa330768f5.jpg)
[FSRCNNX_x2_16-0-4-1.glsl.txt](https://github.com/mpv-player/mpv/files/7832457/FSRCNNX_x2_16-0-4-1.glsl.txt)
No diff with the original repo (ignoring the `//! DESC`) https://github.com/igv/FSRCNN-TensorFlow/releases/tag/1.1
My poor knowledge told me these glsl use the mpv syntax. Could it be possible to directly use them in their own renderer without changing codes ?

Well, when I was posting this issue. I found some another files(see below).
![Snipaste_2022-01-08_02-47-25](https://user-images.githubusercontent.com/41094733/148629169-d37d9623-98ff-409d-a062-ccc08584f573.jpg)
I think I know why the options in JRVR look similar with mpv(gpu-next).

**Comment by CounterPillow** [comment]
They appear to be violating the LGPL license of libplacebo and ffmpeg.

**Comment by haasn** [comment]
I'm confused. I downloaded the JRVR thing but I don't even see libplacebo.so anywhere and the dropdown for choosing the renderer doesn't work (via wine). The linux version is a .deb, which I can't even install. So I have no idea how to even confirm if they're using our code or not.

That said, I indeed don't see any mentions to libplacebo or ffmpeg in the EULA, which seems like a clear-cut license violation (you must include the entire LGPL license, and attribution, at the very least in the legal documents).

On a more personal level I do think it's a dick move of them not to at least point out that the renderer is based on libplacebo, rather than trying to misrepresent it as an internal work. But that is not a legal requirement of the LGPL.

**Comment by haasn** [comment]
Update: I had a chat with nevcairiel, seems like:

* The EULA omission is an oversight, they will fix/augment it. (Not that I care because literally nobody reads through EULAs)
* As for attribution, he changed the wiki/forum post to point out that JRVR is based on libplacebo. (Not a legal requirement but still what I'd *expect*)
* The reason it's not included in the .deb is because components are installed/downloaded dynamically or something. (I can't really test it because I'm on an rpm system, and I also don't *really* want to install it system-wide). Legally, it's all "above ground" on a technical level: the .so's use the normal ABI and you can swap them out for your own built versions if you want to. The source code for any modifications are publicly hosted [here](https://code.videolan.org/h.leppkes/libplacebo/-/commits/jr/),

So I'm tentatively closing this one as "not a violation of license", since this is within the legal permissible usage of the LGPL (except for the lack of the license disclaimers in the EULA-nobody-reads-anyway, but that one seems a genuine oversight and will eb fixed).
