### ISSUE TITLE
Playing Switch through Capture Card in MPV shows noticeable latency even with low latency profile.

### ISSUE THREAD

**Issue by MRiGGz** [mpv-player/mpv#9703]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-20220109-git-777628e
- Windows 10 21H1 19043.1415
- Source of the mpv binary
- If known which version of mpv introduced the problem: unknown

### Reproduction steps
Create shortcut for MPV
Edit properties
In target area, put **D:\Tools\MPV\mpv.exe ./mpv.com av://dshow:video="EVGA XR1 Lite Capture Box Video":audio="HDMI (EVGA XR1 Lite Capture Box Audio)" --profile=low-latency --untimed --fullscreen --no-config --sharpen=0.2**
Run shortcut.

### Expected behavior
MPV opens, shows video and audio from capture card device with low latency.

### Actual behavior
MPV opens, shows video and audio from capture card device but has very noticeable latency, making the experience unplayable.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/7851280/output.txt)

Additional Info:
To get the idea of what I'm trying to accomplish, I'm essentially following this guide here in order to play my Switch through my PC:
![Guide](https://user-images.githubusercontent.com/24858069/149055479-4a2f5369-6c1b-4347-84d9-da9187ca63f6.png)

**Comment by lextra2** [comment]
What makes you think you can reduce latency enough in the first place to be not noticeably?

And what makes you think the bigger latency increase does not come from your capture card?

**Comment by MRiGGz** [comment]
> 

I'm sure the Capture Card itself does add a tiny bit of latency. However I noticed that when I left out the ":audio="HDMI (EVGA XR1 Lite Capture Box Audio)" part of the command line, and tested the input delay with my controller to when something happens on screen, there's almost no noticeable delay. When adding back in that line of the command, I notice that there's about a 2 to 3 second delay when testing with the controller again.

**Comment by SgtBlade** [comment]
Did you manage to find a solution? 
Using OBS I barely have any latency but with MPV I'm having 2-3s delay

**Comment by meoow** [comment]
> What makes you think you can reduce latency enough in the first place to be not noticeably?
> 
> And what makes you think the bigger latency increase does not come from your capture card?

Don't be condescending. This is a real issue I would say.

When using OBS, there is almost no noticeable latency. 
When using ffplay with `-f dshow -i video="Capture device"`, there is tiny bit latency.
When using mpv, the latency is much larger.

**Comment by dullahan8** [comment]
Thanks, you helped point me in the right direction while I was searching for this very issue today. 

I did some additional digging and I think the issue is not with MPV, but with with ffplay. 
`ffplay.exe -f dshow -i video="USB Video":audio="HDMI Capture Card (USB Digital Audio)"`
This causes a lot of the same delay. 

However adding `-audio_buffer_size 4` and increasing the buffer size reduces the delay more and more. Anything less than 4 causes audio glitching and at 0 it becomes as laggy as I saw in MPV. I went up to 100 with decent results. I didn't take it any further but seems like just having it at 0 or unset was an issue.

YMMV, play with the buffer size to find the best result. This is what I will be using:
`ffplay.exe -f dshow -i video="USB Video":audio="HDMI Capture Card (USB Digital Audio)" -audio_buffer_size 30`

Perhaps ffplay will be a better fit for what you are trying to do?

**Comment by garoto** [comment]
> As a feature request it'd be handy to have an option to change the DirectShow audio input delay, or otherwise know of a way to pass `-audio_buffer_size` to the ffmpeg remuxer. This would help audio devices getting a lower latency for playback.

```
mpv --demuxer-lavf-o-add=video_size=1280x720,framerate=20,rtbufsize=20M,channels=1,sample_rate=48000,audio_buffer_size=100 av://dshow:video="CEVCECM":audio="Microphone (2- CEVCECM)"
```
