### ISSUE TITLE
icc-profile-auto is desaturating images

### ISSUE THREAD

**Issue by garamond13** [mpv-player/mpv#9795]
### Important Information
- mpv 0.34.0-142-g1ba0547bfb win 11

### Reproduction steps
no-config: everything is ok

With these settings and icc profile gotten with hardware calibration. Open original srgb.jpg than take a screenshot, open that  screenshot again and take a screenshot. Continue doing that.

[icc profile.zip](https://github.com/mpv-player/mpv/files/7963938/icc.profile.zip)

icc-profile-auto=yes
icc-intent=1 #or with 0 same thing
icc-3dlut-size=128x128x128
icc-cache-dir=C:\mpv\icc_cache

### Expected behavior
Colors should stay the same no matter how many times you open and screenshot image.

### Actual behavior
Each time you open image and take screenshot colors are desaturated (not just in screenshot).
![srgb ss1](https://user-images.githubusercontent.com/98652255/151666130-ec08cc46-3076-430d-91df-4226f1cc5c8f.png)
![srgb ss2](https://user-images.githubusercontent.com/98652255/151666131-c8550821-b2f2-4813-8d6c-c83c81736f49.png)
![srgb ss3](https://user-images.githubusercontent.com/98652255/151666133-2e5b424e-8ea6-4f63-8c32-29a0de110dd7.png)
![srgb ss4](https://user-images.githubusercontent.com/98652255/151666134-a1559ef3-9e4d-41e7-b5ed-1f9f74066e9c.png)

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/7963951/mpv.log)

### Sample files
![original srgb](https://user-images.githubusercontent.com/98652255/151666286-0b6b4c3c-5e03-4304-b30a-5564fc1e0a26.jpg)

**Comment by hooke007** [comment]
> open that screenshot again and take a screenshot. Continue doing that.

Of course you will get desaturating images. If no changes, it would be a bug.

**Comment by garamond13** [comment]
Just tested this in photoshop, same behavior. Also, compared image opened in mpv and same image opened in photoshop, colors look same. So I guess everything is fine.

**Comment by haasn** [comment]
Seems like a duplicate of #7840

**Comment by TheFeelTrain** [comment]
I am experiencing this as well. Screenshots taken with an ICC profile enabled in MPV result in the image being de-saturated. Opening the screenshot PNG file in Firefox, Chrome, Gnome's photos viewer, and even MPV itself all show the same de-saturated colors. FF and Chrome both have the ICC profile enabled, so I would expect those to be correct but they're not. The only other application that looks correct is GIMP for whatever reason.

If I disable the ICC profile in MPV, the colors are then over-saturated (I'm using a wide gamut monitor so that makes sense) during playback but then screenshots display correctly in other applications. They appear exactly same as the video in MPV with the ICC profile enabled. Except now GIMP has the over-saturated colors.

I'm not sure if that makes any sense so I want to explain it a different way just in case:
With `icc-profile-auto`: Colors are correct while video is playing, wrong when viewing screenshot (except in GIMP)
Without `icc-profile-auto`: Colors are wrong while video is playing, correct when viewing screenshot (except in GIMP)

I'll also add the problem occurs whether or not `target-trc=srgb`, `screenshot-tag-colorspace=yes/no`, or `vf=format:gamma=gamma2.2` settings are used in any combination. My lack of understanding of how ICC profiles work doesn't help, and the fact colors appear correct in GIMP is throwing me off even more.

**Comment by canmom** [comment]
I have also had this issue. Screenshots taken in mpv are in the monitor's colour space, but the monitor's ICC profile is not embedded in the image (regardless of whether `screenshot-tag-colorspace` is set), so it is incorrectly interpreted as an sRGB image by most programs - resulting in a desaturated-looking image when it's viewed in a colour-managed application such as mpv.

As a workaround, I overrode my screenshot command to:
```
s async apply-profile screenshot; screenshot; apply-profile screenshot restore
```
where the screenshot profile is:
```
# Disable ICC profile for accurate screenshots
[screenshot]
icc-profile-auto=no
profile-restore=copy
```
However, this is not ideal, since the video is temporarily displayed in the incorrect colour space. I would expect either that images would be saved in sRGB without the colour profile applied, or that there would be some way to embed the monitor profile in the image so that the screenshot could be displayed correctly by colour-managed applications. (Ideally an option to select which behaviour to apply.)

**Comment by x64x2** [comment]
> I have also had this issue. Screenshots taken in mpv are in the monitor's colour space, but the monitor's ICC profile is not embedded in the image (regardless of whether `screenshot-tag-colorspace` is set), so it is incorrectly interpreted as an sRGB image by most programs - resulting in a desaturated-looking image when it's viewed in a colour-managed application such as mpv.
> 
> As a workaround, I overrode my screenshot command to:
> ```
> s async apply-profile screenshot; screenshot; apply-profile screenshot restore
> ```
> where the screenshot profile is:
> ```
> # Disable ICC profile for accurate screenshots
> [screenshot]
> icc-profile-auto=no
> profile-restore=copy
> ```
> However, this is not ideal, since the video is temporarily displayed in the incorrect colour space. I would expect either that images would be saved in sRGB without the colour profile applied, or that there would be some way to embed the monitor profile in the image so that the screenshot could be displayed correctly by colour-managed applications. (Ideally an option to select which behaviour to apply.)


what version are you running and on which device??
