### ISSUE TITLE
fullscreen animation: fake Black borders should be generated before resize

### ISSUE THREAD

**Issue by ValZapod** [mpv-player/mpv#9839]
### Important Information

Provide following Information:
- mpv version mpv 0.34.0-174-g67a2b2852c
- Windows Version windows 11 21H2 22000.469
- Source of the mpv binary https://github.com/ValZapod/mpv-winbuild
- If known which version of mpv introduced the problem

### Reproduction steps

--no-config allows to reproduce the issue.

Imagine you have a video (nowadays Apple TV+ loves doing it, see sample from #9774) that is not IMAX from Disney+ and thus should have some bigger black borders (IMAX 1.90 also have small borders) and yet Apple TV+ just removes them and you have 
Width                       : 3 840 pixels
Height                      : 1 920 pixels.

(This is just like 1920x1080 vs 1920x808 before that.)
So such a video when you press fullscreen will first resize to 4K and only then will add black borders. That destroys the aspect ratio for a second and looks horrible and of course requires some extra (milli)seconds to work, not to mention **that is supposed to be a different not aspect ration preserving option!**

### Expected behavior
You first add black borders and then resize.
### Actual behavior
You first resize, then add black borders and then (sic!) resize again.
### Log file
[aaaa.txt](https://github.com/mpv-player/mpv/files/8011298/aaaa.txt)

### Sample files

https://user-images.githubusercontent.com/31514790/151272160-38f86919-a48f-49a4-bfdf-b1881a0a8996.mp4

**Comment by avih** [comment]
If I understand correctly, you say it's OK before changing to/from fullscreen, OK after changing to/from fullscreen, but during the change between window/fullscreen (and/or for some milliseconds after) you observe some temporarily incorrect image aspect ratio. Is that correct?

If yes, then it's most likely that mpv can't do much about it.

mpv doesn't animate the window - Windows(TM) does. Whenever the (win32) VO observes that the window size changes (which includes into/out-of fullscreen), it reports to mpv, and in response mpv adapts the window content to the new size so that the aspect ratio is correct and black bars are added as/if needed, and it does that as soon as it can on every observed window size change.

I'm guessing that the animation is performed by Windows itself without reporting intermediate sizes during the animation. I'm also guessing that it's Windows itself which stretches the window content during the resize animation without preserving the aspect ratio the same way that mpv would do it if it knew of the intermediate sizes.

So, unless there's reasonable evidence that mpv could do something useful here, I'd assume that most of my guesses are correct and mpv can't do much about it - and not consider it an mpv issue.

**Comment by ValZapod** [comment]
> and not consider it an mpv issue.

https://github.com/mpv-player/mpv/issues/9817 can fix it as it hides all changes.

> Is that correct?

Yep.

>also guessing that it's Windows itself which stretches the window content during the resize animation without preserving the aspect ratio 

Can you prove it? I have NO IDEA how to debug this.

**Comment by avih** [comment]
> > also guessing that it's Windows itself which stretches the window content during the resize animation without preserving the aspect ratio
> 
> Can you prove it?

Your log shows it - mpv sees the new (fullscreen) size 4 ms after changing to fullscreen:
```
[   5.398][v][cplayer] Set property: fullscreen -> 1
...
[   5.402][v][vo/gpu-next/win32] resize window: 3840:2160
```

There are no intermediate sizes which Windows reported to mpv.

**Comment by ValZapod** [comment]
It does not happen with actual 3840x2160 sources. At all. Also (!) even VLC cannot do 3840x2160 like mpv does, it first resises to top and bottom and then to all fullscreen.

**Comment by avih** [comment]
> Also even VLC ... And our Chrome...

This is mpv issue tracker, please don't add irrelevant noise.

The point is that one moment mpv sees the windowed size, and 4 ms later it sees the fullscreen size, and between those, it responds to resize reports as soon as it can.

**Comment by ValZapod** [comment]
Okay, I believe only hiding the window and thus accelerating to 1 fps to fullscreen will fix this (DWMWA_CLOAK).

For posterity I will attach what happens when you go into fullscreen for (3 840x1920) and **it also happens when you go out**. I still think there should be a way to fix it even if using some undocumented APIs. Only second and last photos here are correct. The first shows wrong fullscreen and last shows fake borders still present on fullscreen. Sorry for such big images, but hey it is 2022.

![Screenshot_20220207-034215_Photos](https://user-images.githubusercontent.com/31514790/152709103-c2c94170-e7c3-47fc-a675-5a5e632bbc88.png)
![Screenshot_20220207-034224_Photos](https://user-images.githubusercontent.com/31514790/152709107-90ceb94d-3b7d-45ec-b089-52a58c84cdc3.png)
![Screenshot_20220207-034251_Photos](https://user-images.githubusercontent.com/31514790/152709117-778104df-856a-42e6-8421-83a252628eec.png)
![Screenshot_20220207-034257_Photos](https://user-images.githubusercontent.com/31514790/152709121-e2842000-5353-4355-97f1-f46a45bda803.png)
