### ISSUE TITLE
JPEG XL support?

### ISSUE THREAD

**Issue by askasys-code** [mpv-player/mpv#9843]
I'm using MPV as image viewer with a custom config.
It's work like a charm for many image formats.

Some issues discovered with AVIF files, 
but totally lack of support of JPEG XL files.

**Comment by CounterPillow** [comment]
mpv gets its decoders from ffmpeg, and ffmpeg [is already in the process of adding support](https://www.mail-archive.com/ffmpeg-devel@ffmpeg.org/msg130399.html).

**Comment by askasys-code** [comment]
Ah good it's very recent [Fri, 07 Jan 2022], so it won't be long before it's supported. Great news!

**Comment by ValZapod** [comment]
Of course ideally AVIF support for perfect lossless 10 bit tagged as PQ and stuff is really needed. Again, patches for HEIC conteiner used in AVIF and HEIF are there. Lossless AVIF was fixed when Cark fixed the lossless aom.

**Comment by CounterPillow** [comment]
@ValZapod stop posting irrelevant garbage in every issue. It's annoying.

**Comment by ValZapod** [comment]
> irrelevant garbage in every issue

In what way was my comment was irrelevant? Also if exr request is still open why close this one? #7814

**Comment by CounterPillow** [comment]
AVIF and HEIC are not relevant to a feature request for JPEG XL. That you cannot see this, and continue to bombard every issue with your deranged babbling, goes to show that you should probably have your commenting privileges revoked.

**Comment by rubyFeedback** [comment]
Hmm. If ffmpeg supports it eventually, can we then, for instance, use mpv to split a video (say 10 seconds) into individual jpeg-xl files or whatever the name is? Similar to how we can do so into .jpg and .png files (I think ... has been quite some years since I last used it, but I recently purchased an outdoor camera for monitoring my cats, so I may want to look into this eventually).
