### ISSUE TITLE
mpv auto quote spaced-argument for "run" command without a way to disable the behavior

### ISSUE THREAD

**Issue by CrendKing** [mpv-player/mpv#9861]
### Important Information

Provide following Information:
- mpv version: 0.34.0-185-g0197729949
- Windows Version: Windows 11 v22000.493
- Source of the mpv binary: Scoop
- If known which version of mpv introduced the problem: N/A
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

1. Open mpv.
2. Open console with tilde key.
3. Type `run my_app /a="b c"` (my_app could be any external app). The expectation is that my_app receives exactly one argument `/a="b c"`.
4. my_app actually receives two arguments. The first is `/a=\"b` and the second `c\"`. Basically instead of `/a="b c"`, mpv turns it into `"/a=\"b" "c\""` by quoting the whole thing and escape existing quotes.
5. If instead we `run my_app /a=b c`, it's still two arguments, `/a=b` and `c`.
6. If we put "b c" in a variable `x` and do `run my_app /a=${x}`, my_app receives one argument `/a=b c` (notice the missing quotes).

### Expected behavior

User should be able to tell mpv to run an external app with exactly how the argument is quoted.

### Actual behavior

mpv always quote argument if it sees a space in it (maybe related to https://github.com/mpv-player/mpv/issues/375?). The problem is, sometimes the external app expects quote in different position.

### Log file

https://0x0.st/oXDO.json

### Sample files

N/A

**Comment by avih** [comment]
> 3\. Type `run my_app /a="b c"` (my_app could be any external app). The expectation is that my_app receives exactly one argument `/a="b c"`.

I don't know why you expect this. You can't expect it at the (POSIX) shell, and you can't expect it in mpv.

At most, at the shell it would be interpreted as `/a=b c` (i.e. the quotes will be removed, but it still remains a single argument), but this doesn't work the same in mpv, because mpv doesn't support mixed quotes (some of the argument is unquoted or quoted with one type of quotes, and other parts of the arguments quoted with other type of quotes).

The documentation states exactly 4 ways to specify arguments: unuoted, double-quoted, single-quoted, custom-quoted. In your case single quotes would do the work, but do read the docs - https://mpv.io/manual/master/#flat-command-syntax .

> my_app actually receives two arguments. ...

As documented:

>  Arguments with whitespaces or other special characters must be quoted, or the command cannot be parsed correctly.

And it's indeed not parsed correctly in this case.
