### ISSUE TITLE
Automatically expand playlists added to queue before playing

### ISSUE THREAD

**Issue by JJRcop** [mpv-player/mpv#9868]
Right now mpv must "play" a playlist file in order to expand it and queue up its contained entries. This is tedious when I want to queue up a few playlists in order to shuffle them up together at once, I have to "play" each of them first before shuffling.

### Expected behavior of the wanted feature
When adding an entry to mpv's playlist, mpv checks if the entry is itself a playlist, and expands it if so. Entries inside that expanded playlist that are themselves playlists are also expanded.
It does this for a maximum depth of 3 to prevent fork bombs.

### Alternative behavior of the wanted feature
Keybind or console command to check every entry currently in the playlist and expand if they are playlists.

**Comment by avih** [comment]
WIll not happen as part of mpv itself.

mpv doesn't work that way. mpv only knows that an argument is a playlist when it tries open and play it, and opening it can be a relatively long process (think e.g. on a playlis over network).

You can write a script which will do that by start playing all entries one after the other and skipping to the next one as soon as it starts an actual playback (i.e. a file is actually being played as audio/video). You might want to do that in reverse order (so that playlists which expand to items won't interfere with the iteration process). You might want to skip http or other network items because this will definitely make it slower, and possibly other tricks. But it will be slow, and mpv will not do that on its own.

**Comment by guidocella** [comment]
This is possible if you add playlist items with `loadlist <url> append`.

**Comment by JJRcop** [comment]
> You can write a script which will do that by start playing all entries one after the other and skipping to the next one as soon as it starts an actual playback (i.e. a file is actually being played as audio/video). You might want to do that in reverse order (so that playlists which expand to items won't interfere with the iteration process). You might want to skip http or other network items because this will definitely make it slower, and possibly other tricks - e.g. maybe you only want to expand items which have `.pls` file extension (even if playlists can have any file extension, including none). But it will be slow, and mpv will not do that on its own.

This is a great idea, thanks, I will try this.

> This is possible if you add playlist items with `loadlist <url> append`.

Thanks for the tip! This works great for basic playlist files, if only it worked with internet-based ones, but thanks anyway.
