### ISSUE TITLE
Idle Inhibitor should continue if mpv is playing something

### ISSUE THREAD

**Issue by stacyharper** [mpv-player/mpv#9872]
### Important Information

mpv version:

mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1

Linux Distribution and Version:

PostmarketOs Edge

Source of the mpv binary:

The Alpine package 

If known which version of mpv introduced the problem:

Nope

Window Manager and version:

Sway 1.7.0

### Reproduction steps

- Play a youtube playlist with mpv
- Use a short duration swayidle timeout (ex: swayidle timeout 4 'notify-send "not idle"')

### Expected behavior

As mpv is playing, the window environment should not be considered idle.

### Actual behavior

Between one video and the next one, the swayidle timeout trigger.

I guess this can also happen if yt-dlp have to restart the stream for some reason as network issue.

I use sxmo on a mobile phone and listen to playlist in a screenoff mode. We use a very short idle timer to put the mobile device in suspension. This unfortunately trigger between videos.

### Log file

https://paste.sr.ht/~stacyharper/803b072bc8fbd0a6a2755daa4702d9b662b4da9e

**Comment by Dudemanguy** [comment]
Well what happens here is that mpv restores the screensaver after the file finishes. The timeout in your case is so short that it triggers in the time between mpv finishing the current file and trying to open the next one (where it will kill the screensaver again). It's probably pretty reasonable to simply not restore the screensaver if mpv is still in the playing state and not at the end of the playlist (can't think of a real reason why it shouldn't be like this). In the meantime, you might be able to workaround this by setting the `stop-screensaver` property.

**Comment by Dudemanguy** [comment]
Actually looking at this some more, this shouldn't happen. `playback_active` is supposed to be true in this case which wouldn't change the screensaver state.

**Comment by stacyharper** [comment]
So something is wrong somewhere ?

**Comment by Dudemanguy** [comment]
Yeah the comment in the `core.h` is completely incorrect but that's kind of a separate issue. This was discussed a bit in IRC but would simply adding `always` as an option for `stop-screensaver` suffice? Currently there is no way for users to completely control how mpv inhibits screensavers because the default `yes` option turns itself on and off depending on the circumstances. It's, of course, possible to change how `playback_active` is currently handled but that would have a ton of implications that's probably best to avoid.

**Comment by stacyharper** [comment]
If this new option enable the idle inhibitor permanently I think no, it isnt enough. I already can configure my wm to prevent inhibition if mpv is running and visible. I would expect something more precise from mpv itself. 

Basically the player is on, then inhibit, the user pause (or quit) disable it. If that require more works or refactorisations then this can wait for a better moment to be fixed.

Anyway this new option could still helps users on wm that doesnt have that much control. But if the goal is to close this issue, and in the end it add complexity for a feature no one would use, then imo it is pointless. I prefer to wait :D

**Comment by Dudemanguy** [comment]
Hmm yes my proposal wouldn't really help you then. Changing what the player considers `active` or not is actually very trivial. The current logic is just a bunch of various boolean conditions that all must be met in order to enable/disable the inhibition. It does seem unnecessarily complicated and could probably be simplified but I would need to go through every condition to make sure it doesn't have some kind of unexpected consequence.

**Comment by stacyharper** [comment]
Perfect, I'll be patient ! Thanks by advance :]

**Comment by avih** [comment]
> If this new option enable the idle inhibitor permanently

it does - as long as you don't manually change it yourself later (at runtime).

Basically, currently even if you enable idle inhibiton, then under some conditions mpv would still not inhibit idle, e.g. when nothing is playing - and you can't override it by force-inhibiting.

Even if we modify it to behave exactly like _you_ want, then someone else will come up with some other use case which still doesn't fit their needs.

But if we add a new value "always" then you could change it between "always" and "no" at runtime, depending on the exact conditions you care about. this would effectively allow YOU to decide when idle should be inhibited, instead of letting mpv decide.

System idle timeout of 4 seconds is extremely unusual. Your issue is about going to the next playlist entry, but with such a short timeout it can suspend before even the first entry starts.

So mpv can't account for every unusual conditions which users might have. But it can allow to relieve control to the user in such case - to tailor it specifically to their needs and use case.

And that's what adding support for "always" does.

**Comment by stacyharper** [comment]
I openned the issues cause it looks wrong that mpv prevent
screenlocker correctly except when it load the next video.

I think that my current special context revealed this strange behavior
and exposeed that the current idle inhibitor rules arent great.

But if you statues that this is the expected behavior then I'm okay with
that and I'll take the workarround you offer.

**Comment by Dudemanguy** [comment]
With the new always setting + a simple script, you can achieve the behavior you need now so I will go ahead and close this.

**Comment by beyond9thousand** [comment]
> With the new always setting + a simple script, you can achieve the behavior you need now so I will go ahead and close this.

@Dudemanguy how exactly?

**Comment by Dudemanguy** [comment]
It was posted earlier.

```
mp.observe_property("pause", "bool", function(_, paused)
    mp.command("set", "stop-screensaver", paused and "no" or "always")
end)
```

**Comment by Flashwalker** [comment]
The only thing that helps me is to run like this:  
`$ systemd-inhibit --what=idle mpv ...`
