### ISSUE TITLE
Little kinda sorta stupid question

### ISSUE THREAD

**Issue by lavilao** [mpv-player/mpv#9896]
With DRM leasing on for example Sway would I be able to use -gpu-context=drm -vo=drm without the need of going to a TTY or DRM leasing is for another different stuff?

**Comment by CounterPillow** [comment]
As far as I understand, DRM leasing is so that you can have a certain monitor (usually VR headsets) driven by an application other than the DRM master (in this case, compositor), e.g. you could have a second monitor driven by mpv's DRM code directly.
I don't know if this allows you to have a DRM master hand off control of a certain display it is already using dynamically as the application is started, but I also don't really see the point of that when the likely use-case (low latency "exclusive fullscreen") would be better satisfied by direct scanout/unredirection.

> -gpu-context=drm -vo=drm

this combination of options is nonsense, by the way. Either/or, not both. Preferably the former, as it will use the gpu accelerated gpu VO.

**Comment by lavilao** [comment]
First of all, thanks for answering. My reason d'etre is libva-intel-driver-hybrid, this is a driver that allows my intel celeron n3050 to do hardware decoding of vp9. With vo=gpu the gpu hangs hard, hole desktop frozen for like 10 seconds, with gpu-context=drm and vo=drm on a TTY this does not happen.

**Comment by philipl** [comment]
In principle it can be used this way. I wrote proof-of-concept code for `gpu-context=displayvk` to steal a display using the vulkan display extensions and the special extension for acquiring an x11 display. Mesa has an equivalent extension for acquiring a drm display and in theory it should work the same way, but I've never tried.

As @CounterPillow says, under normal conditions, a fullscreen window in your normal desktop environment is perfectly fine for this job. Unfortunately your CPU doesn't have fully vp9 decode support, and jumping through these kinds of hoops to get _something_ working is probably disproportionate to the benefits.

**Comment by lavilao** [comment]
Oh, I know that the results wont outperform the methods, it is just a pride thing to tell to a friend (who has the same model of laptop) "This is something that can only be found on linux, behold the power of FOSS!" and maybe to tell that to myself. As Oscar Wilde said "lo unico capaz de consolar a un hombre por las estupideces que hace, es el orgullo que le proporciona hacerlas." (I would translate the phrase but I dont know the exact words so I leave it as I found them)

**Comment by Quackdoc** [comment]
I realize this is fairly old, however I wonder if this could be used to get HDR without swapping to a TTY when using displayvk?

**Comment by lavilao** [comment]
in theory yes
