### ISSUE TITLE
How to get position of pixel?

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#9899]
Is there a way to retrieve the position of a pixel by hovering the mouse over part of the video/image?

This would be useful for cropping video using ffmpeg. I don't want to have to download an entirely new program for this

**Comment by avih** [comment]
> Is there a way to retrieve the position of a pixel by hovering the mouse over part of the video/image?

No.

You can save a screenshot of the window (using an mpv command) and process it with whatever external tools you want, but mpv doesn't provide a method to retrieve the content of the window to a script or client.

**Comment by avih** [comment]
> > Is there a way to retrieve the position of a pixel by hovering the mouse over part of the video/image?
> 
> No.

Sorry, I thought you wanted the value (color) of a pixel.

You can retrieve the mouse position at the window in (usually) pixels using the `mouse-pos` property.

Translating it into a position at the video source is not trivial, because there could be black bars and scaling and anamorphic video, etc, but the `osd-dimensions` property should probably have enough info to translate from position-at-window to position-at-video.

**Comment by guidocella** [comment]
```lua
mp.add_key_binding('F1', function ()
    local mouse_pos = mp.get_property_native('mouse-pos')
    local osd_dims = mp.get_property_native('osd-dimensions')
    local video_params = mp.get_property_native('video-params')
    print('x: ' .. (mouse_pos.x - osd_dims.ml) * video_params.w / (osd_dims.w - osd_dims.ml - osd_dims.mr))
    print('y: ' .. (mouse_pos.y - osd_dims.mt) * video_params.h / (osd_dims.h - osd_dims.mt - osd_dims.mb))
end)
```

**Comment by cerealXDD** [comment]
Thanks ill look into it

**Comment by cerealXDD** [comment]
I will test this out
