### ISSUE TITLE
"Dynamic" stats in recent versions

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9901]
The mpv's build is based on shinchiro's toolchain.
In recent win-build's versions, there is a weird behaviour about stats.lua.

Just watch the video to know the strange behaviour intuitively：

https://user-images.githubusercontent.com/41094733/155220955-d807fec1-e0f8-4fcd-9606-ad4e3663188c.mp4

_(up) 20220210git_   VS   _(down) 20220222git_

In practical usage (i.e. use more shaders/ debanding/ scaling), the "redraw" and "fresh" would change more frequently...(looks funny)

https://user-images.githubusercontent.com/41094733/155222181-94aa8401-2d28-4db1-965d-abf60a3cb588.mp4

What I am sure is that it is not a mpv's bug which is caused by one commit. Because I cannot reproduce it on 20220210git, the first version I met with "issue" is 20220213git. And apparently there is no related change on this aspect during those days.

I want to know if it's upstream/dep's bug, or what mpv could do to avoid that.

### Log file

N/A

**Comment by avih** [comment]
The order between "Fresh" and "Redraw" is random (specifically, arbitrary, because they're unordered keys in a map).

There weren't changes in `stats.lua` or in how the VO constructs the data, so I don't know why it changes more frequently. Maybe something changed in luajit (which I presume you use) in how it iterates over table keys.

Anyway, let's assume we can control the order. Do you think one of them should always be first? or some other idea how to decide which should be first?

**Comment by hooke007** [comment]
> Do you think one of them should always be first? If yes - which one, and why? or maybe some idea on how to decide which should be first according to the data they contain?

Yes, but which one should be first may not be much important.
The fixed order is convenient for users to observe the status of shaders. In my usage case, I often apply mulitple shaders at the same time.
