### ISSUE TITLE
ao_pipewire: possible slight crackling maybe caused by low pipewire-buffer value?

### ISSUE THREAD

**Issue by AtticFinder65536** [mpv-player/mpv#9992]
### Important Information

- mpv version:
```
mpv 0.34.0-233-gf871294204 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0
```
- Platform and Version: Arch Linux, most system-related packages are from official repos but my customisations shouldn't be an issue.
- Source of the mpv binary: Me, built from personal PKGBUILD, from master https://github.com/mpv-player/mpv.git

### Reproduction steps

`no-config` as the only argument will use `ao=pulse` first if it's available.

1. Play a file containing audio with `no-config` and `ao=pulse`.
2. Enjoy the audio
3. Play that file with `no-config` and `ao=pipewire`
4. You might hear slight crackling in some parts of the track.

### Expected behavior

No crackling like `ao=pulse`.

### Actual behavior

I hear a faint crackling noise in some parts of a song. With `ao=pulse` I don't hear it at all.

Looking at easyeffects output, mpv with `ao=pulse` has a latency of 60 ms. mpv with `ao=pipewire` has a latency of 20 ms (matches pipewire-buffer https://github.com/mpv-player/mpv/blob/f871294204529374dd3056f7b616381400233036/audio/out/ao_pipewire.c#L593).

Setting `pipewire-buffer` to something like 60 fixed the issue. Actually I think I might've heard something still a little bit a few times but that could just me.

I hope that someone who knows more than I do can say if this is a problem or not, or someone can successfully/unsuccessfuly reproduce this. Possibly 20 is too low of a value for pipewire-buffer and it may cause issues for most people?

### Log file

I can provide one if needed but I don't think it's necessary.

### Sample files

Detecting this issue is hard for me and I think it should happen on any audio file, some might be easier to detect the issue than others. I could provide some if needed.

### Other

If you want to hear a sick nightcore remix of your song and you can use `ao=pipewire`, play the song with `pipewire-buffer=1` (this GitHub issue comes with ABSOLUTELY NO WARRANTY for your ears). Display an external cover image of an anime girl wearing headphones in a futuristic environment for greater effect.

**Comment by lextra2** [comment]
Can confirm. Pipewires buffer is too aggressively low which causes crackling even with ryzen 9 3900x as cpu...

**Comment by qmega** [comment]
I'd think this is dependent on hardware and config. A log would probably be useful to see if there are underruns, etc.

My box is a monster, but I don't get underruns even with `pipewire-buffer=1`. My CPU is a 3960X and I'm running linux-zen kernel, which is latency-optimized compared to stock so that might have an effect. I'm running Pipewire at 96 kHz with a quantum of 512. My output is a USB audio device.

Pulse, AFAIK, increases the buffer any time there's an underrun, and never decreases it again, so no crackling but potentially pretty bad latency if you just have a spike of activity or something.

Maybe the default buffer size should be greater -- fewer wakeups is good and I wouldn't think a media player is very latency-sensitive -- but I think the buffer size is also how much audio you'll skip if you pause and unpause (very noticable with `pipewire-buffer=2000`). More data points on what buffer sizes work for people might be good to have.

**Comment by philipl** [comment]
@t-8ch Good for you to take a look.

Also note that we started with a much larger buffer size and it was causing stuttering in the video playback.

**Comment by arzeth** [comment]
```
mpv 0.34.0-234-gfcc81cd940 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0
```
Kernel: 5.16.14-247-tkg-pds (which is kinda similar to linux-zen; cpu scheduler PDS works the best for me)
PipeWire: 0.3.48
Ryzen 5 2600 (6 cores, 12 threads, ~10-20% weaker than Ryzen 5 3500 and Ryzen 5 3300X)
USB 2.0 sound card which supports only 48 and 96 kHz (but I disabled 96 kHz to avoid any potenial useless upsampling).
`/etc/pipewire/pipewire.conf`
```
    default.clock.rate          = 48000
    default.clock.allowed-rates = [ 48000 ]
```
Also I have `resample.quality = 15` https://wiki.archlinux.org/title/PipeWire#Sound_quality_(resampling_quality) (**the slowest resampling**)

Also I use a startup script
```
systemctl --user daemon-reload
systemctl --user stop pipewire.service pipewire-pulse.service pipewire-media-session.service
systemctl --user start pipewire.service pipewire-pulse.socket pipewire-media-session.service

# pactl is compatible with PipeWire
pactl -- set-sink-volume @DEFAULT_SINK@ 100%
sleep 0.3
pactl load-module module-ladspa-sink sink_name=ladspa_tonestack plugin=caps label=ToneStack control=4,0.43,0.5,0.5
pactl set-default-sink ladspa_tonestack
sleep 0.3
pactl -- set-sink-volume @DEFAULT_SINK@ 50%

renice -n -17 -p `pidof pipewire`
renice -n -17 -p `pidof pipewire-pulse`
renice -n -17 -p `pidof pipewire-media-session`
```
(ToneStack just happens to improve sound for my headphones; I still hate all other sound "improvers")

With `--no-config --ao=pipewire --pipewire-buffer=1`
A 48000 Hz audio file: perfect.
A 44100 Hz audio file (`Vibrasphere - Aguas Calientes.flac`): plays 2x or 3x times faster. Plus radiation-like noise. Plus strange distortions (I don't know the right terms).
A 192000 Hz audio file: plays ~2x faster. Unlike with 48000 Hz, in this case distortions are because of being played faster.
Same results with ToneStack and without ToneStack.
Same results with `resample.quality = 1` + no ToneStack.

With `--no-config --ao=pipewire`
A 48000 Hz audio file: perfect.
A 44100 Hz audio file (`Vibrasphere - Aguas Calientes.flac`): plays 2x or 3x times faster. Plus radiation-like noise.

Resampling seems to be single-threaded in PipeWire (source code: https://gitlab.freedesktop.org/pipewire/pipewire/-/tree/master/spa/plugins/audioconvert), so the bottleneck is CPU's single-thread performance. Ryzen 5 2600 has 2250 points, Core i9-12900KF has 4219 points in https://www.cpubenchmark.net/singleThread.html. Someone mentioned that `--pipewire-buffer=1` works for them, but for me neither 1 nor 3 nor 40 work, but my CPU isn't 40x slower.

There are more distortions with `--pipewire-buffer=1` than `--pipewire-buffer=20`.
And `--pipewire-buffer=20` ("radioactive" noise) is worse than `--pipewire-buffer=46`.
With `--pipewire-buffer=46`, there is a click every ~60 ms (not sure if "click" is the right term), and the speed is 2x faster than needed.
**BUT** with `--pipewire-buffer=47` everything is perfect even if I run `nice -n -20 stress -c 10`

Also, unlike with `--ao=pulse`, with `--ao=pipewire --pipewire-buffer=47` sound drops every ~200ms for ~50ms if I run `nice -n -12 stress -c 12` in background (no difference whether it is `-n -12`, `-n -15`, or `-n -20`). `-c 12` means all my 12 CPU threads. With `-c 11` there are much less sound drops, but still unusable. The result is same for both `--pipewire-buffer=47` and `2000`. I've run mpv with nice level default `0` and `-17`. The most interesting thing is: no distortions happen, no speed-up, it's just a lot of sound dropping. That means that those distortions and speed-up happened probably not because of a CPU performance.

I wonder why so much difference because of 1 ms (46ms vs 47ms).

**Comment by qmega** [comment]
Didn't consider that pipewire's resampler would be the cause of these artifacts, but I tested a bit and it does seem to have an impact on my machine too.

A peculiarity of my setup which I almost mentioned the first time but didn't see as relevant -- should've checked first: I have mpv set up (with `audio-samplerate=96000`) to always output to pipewire at 96 kHz (which is pipewire's configured rate) and make up the difference with `audio-swresample-o=resampler=soxr,precision=28` (equivalent to soxr-vhq, suitable for 24-bit audio). Soxr has the least artifacting of any resampler I know of and is light on CPU usage as well; the only downside I'm aware of is latency, which is a non-issue with a video player since the audio can be resampled ahead of time and stay in sync with the video. So I never actually pass mpv's audio through pipewire's resampler (which I've left at the default quality setting to avoid adding latency to clients potentially more sensitive to it).

If I don't configure mpv to resample, and let pipewire do it, I _do_ get a terrible mess of audio if I play 44.1 kHz audio with `pipewire-buffer` set to 1 or 2. At 3 it seems fine, with cursory testing, even with load. With 48 kHz or 96 kHz audio, it's fine even at 1. (This is, again, with pipewire's graph and the audio hardware (USB) running at 96 kHz.)

> I wonder why so much difference because of 1 ms (46ms vs 47ms).

I think a resampler would by definition have to look at multiple samples at a time, and presumably can do a better job by looking at more of them. Obviously the details depend on the algorithm -- and I know nothing about the one Pipewire uses -- but I can imagine that for a given algorithm and quality level, there may be a certain number of samples that need to be looked at, i.e. a buffer. If the buffer you provide to pipewire is smaller than that number, there would be issues, and that would be deterministic and not dependent on load. It wouldn't surprise me if that number grows with the quality setting of the resampler. 46-47 ms sounds like a lot, but you do have it on the highest setting, so maybe that's actually how much audio it wants to look at? (I'm just spitballing, of course. Don't really have the energy to dig through the code and find out at the moment.)

**Comment by qmega** [comment]
I wonder if https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/9f3237b74edc3df467cca50af7c09f1e3c89abea fixes this for anybody?

**Comment by MacGyverNL** [comment]
### Request for information

Could anyone affected by this paste the output of `pw-top` (`pw-top | cat` for easy copying), specifically the `QUANT` and `RATE` columns for the mpv process(es) and the output device they're under?

E.g.:
```
R   70    256  48000 168.7us   7.8us  0.03  0.00    5    S32LE 6 48000 alsa_output.pci-0000_00_1f.3.analog-surround-51
R  311    256  48000 114.2us  15.2us  0.02  0.00    5    S16LE 8 48000  + wenger
R  205    960  48000  18.8us  13.3us  0.00  0.00    5     S32P 6 48000  + mpv
```

Also, could you run mpv from the commandline using
```
PIPEWIRE_DEBUG=3 PIPEWIRE_LOG_SYSTEMD=false mpv --ao=pipewire [file]
```
and see if xruns are accompanied by output along the lines of
```
[I][18390.555396] pw.node      | [     impl-node.c: 1202 node_on_fd_events()] (mpv-0) client missed 1 wakeups
```

### Rationale & Possible cause of this issue

I'm being affected by this, on an i9 10940x. Not exactly an underpowered system. This happens because *another* client on the same output device is requesting a lower quantum, which results in a lower quantum on the output device. This in turn means that mpv is being forced to wake up more often, because pipewire uses the lowest quantum across devices using the same driver (see the last paragraph of https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ#pipewire-buffering-explained and https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2845 for an explanation of this).

So in my case, mpv's thread delivering audio to pipewire *has* to wake within 256/48000 = 5.3 milliseconds to deliver 256 samples to pipewire, otherwise an xrun occurs. This is effectively the same as setting `--pipewire-buffer=256`.

Now 5.3 milliseconds is actually quite an eternity, but it just so happens that when this other client is running, mpv is competing with all other desktop processes on just 3 (hyperthreaded) cores. These aren't actually very loaded, they're only at about 10% utilization each, at most. But it's enough scheduling contention for mpv to miss some wakeups.

### Fix / workaround

If this indeed turns out to be the issue, the fix is making sure that that thread wakes up in time. For me it's sufficient to have mpv use pipewire's (unchanged, in my case) `client-rt.conf`  rather than `client.conf` (which mpv uses by default in my case). I do this by running mpv as `PIPEWIRE_CONFIG_NAME=client-rt.conf mpv`. This loads pipewire's `libpipewire-module-rt` which handles setting that single thread to realtime priority (if I'm interpreting rtkit's output correctly).

Pipewire apparently defaults to `client.conf` because misbehaving clients getting realtime piority might cause system stability issues, see <https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2024>.

Now I understand from https://github.com/mpv-player/mpv/issues/3399 that (at least in 2016) mpv devs do not believe they should touch / be responsible for system scheduling; but the behaviour of pipewire might be sufficient cause to either:

1. default to pipewire's `client-rt.conf` instead of `client.conf` when `--ao=pipewire`,
2. provide an additional switch for `--ao=pipewire` (like `--pipewire-buffer`) to select a pipewire config file, or
3. document this issue and point users at the possibility of using `PIPEWIRE_CONFIG_NAME=client-rt.conf`, or
4. I don't know too much about the internals of either mpv or pipewire, so whatever else sounds sane.

### Reproducing

For people trying to reproduce this: if you don't have a client that behaves like this, and an overpowered system that will never hit this, you may be able to reproduce the issue and verify the fix by forcing pipewire to a lower quantum and restricting the system to use fewer cores.

You can make mpv itself use a lower quantum but bear in mind that `--pipewire-buffer` uses *milliseconds*, so `1` is actually a quantum of 48 on a rate of 48000. If you want to set a specific quantum, run `pw-metadata -n settings 0 clock.force-quantum 256` (or 128 or even lower).

To restrict the system to use fewer cores using e.g. systemd-controlled cgroups:
```
systemctl set-property --runtime -- user.slice AllowedCPUs=0-2,14-16
systemctl set-property --runtime -- system.slice AllowedCPUs=0-2,14-16
systemctl set-property --runtime -- init.scope AllowedCPUs=0-2,14-16
```
(limited appropriately with hyperthread pairs and maybe even fewer cores, until the issue shows up).

To undo these, `pw-metadata -n setting -d 0 clock.force-quantum`, and
```
systemctl set-property --runtime -- user.slice AllowedCPUs=0-27
systemctl set-property --runtime -- system.slice AllowedCPUs=0-27
systemctl set-property --runtime -- init.scope AllowedCPUs=0-27
```
(altered appropriately for the actual number of CPUs your system reports).

**Comment by MacGyverNL** [comment]
Oh, I forgot to say: @qmega:

> Maybe the default buffer size should be greater -- fewer wakeups is good and I wouldn't think a media player is very latency-sensitive -- but I think the buffer size is also how much audio you'll skip if you pause and unpause (very noticable with pipewire-buffer=2000). More data points on what buffer sizes work for people might be good to have.

> And does a higher buffer still cause video stuttering? If not maybe we should raise the default.

So, raising the default mpv uses probably doesn't fix that pipewire forces a lower quantum on mpv when it's not the only thing producing audio, and "delivering audio to the audio subsystem" actually *is* quite latency-sensitive.

**Comment by t-8ch** [comment]
@MacGyverNL This research and the pointers are great, thanks!
I think we can just enable proper RT processing.
The mpv code running on the realtime thread is nonblocking and does no processing.

I'll prepare a PR.

**Comment by MacGyverNL** [comment]
One more thing to bear in mind when debugging pipewire buffer issues, and in particular @arzeth :

> I wonder why so much difference because of 1 ms (46ms vs 47ms).

Pipewire by default rounds quantum down to the nearest power of two, unless you set `clock.power_of_two_quantum = false` (see <https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PipeWire#setting-buffer-size-quantum>, bottom of the section.)

I'm guessing you tested that with a 44100 rate, because then with 46ms it's 2028/44100, which is *actually* going to be running at 1024/44100. 47 ms pushes it over the magic 2048 boundary: 2072/44100, which becomes 2048/44100. So with 47ms, pipewire actually *has* nearly 47ms to wakeup, but with 46ms, it *actually* only has  a little over 23ms. The *effective* difference between your tests was 23ms, not 1ms.

You can verify this by looking at the quantum applied to the sound device that's playing in `pw-top`, that will be the rounded power of two even if mpv's requested quantum is higher.

In effect, unless the user has set `power_of_two_quantum = false` in pipewire config, `--pipewire-buffer` effectively has *ranges* of numbers that end up meaning the same thing. On 48khz (and multiples of 48), these ranges are between 5 and 10 (256/48000, or 512/96000, or 1024/192000), 11 and 21 (512/48000, or 1024/96000, or 2048/192000), 22--42, and 43--85, etc. On 44.1khz they're slightly shifted; 6--11, 12--23, 24--46, 47--92, etc.

This also means that for most users, the *default* of 20ms probably actually means more like 11 or 12ms.

**Comment by pinkflames** [comment]
I can probably chime in on the maximum acceptable latency. Last time this came up, PipeWire's position was that the acceptable maximum for consumers should be 1024/48000 s (~21 ms).

Unfortunately the current default is higher, because some users have pathological systems that cannot reliably deliver 20 ms audio latency and that is not a job anyone wants to deal with. Personally I prefer ~5-10 ms latency as the maximum for my own use but it can be admittedly challenging to get everything running at that.

Regarding power consumption, my own testing using desktop system and measuring the total system power draw at the wall, I have not observed meaningful differences between 256 and 2048 quantum. Additionally, if I remember correctly, 128 quantum was still not that much worse than those. However going below 128 quantum there was rapidly increasing higher power draw at the wall. Unsurprisingly this was correlated with observably higher CPU usage in pw-top and other system monitoring tools, so CPU residency time and frequency can be used as proxies for estimating impact of chosen latency on power consumption. Highly efficient laptop hardware might fare differently of course, so best double check my numbers.

**Comment by sta-c0000** [comment]
Yes, please change mpv's default pipewire buffer to **24ms**.  It makes sense and would provide a much more realistic latency for average systems.

I've noticed some audio glitches under certain circumstances with mpv on some systems since upgrading to Debian bookworm.

I think mpv should have sane defaults for average systems/users.

**Here's why**: as already explained by @MacGyverNL in this thread, for performance reasons pipewire defaults to using `clock.power-of-two-quantum = true`…

So, to reiterate: with `default.clock.rate = 48000` the default 20ms latency ends up being _**half**_ the intended one:
- `20ms = (960/48000)s` is rounded down to `(512/48000)s = 10⅔ms` (see `pw-top` *output* channel's `quant`)
- `24ms = (1152/48000)s` would be rounded down to `(1024/48000)s = 21⅓ms` …which is _very close_ to the original intended 20ms.

I'm proposing 24ms to also cover 44100Hz `(1024/44100)s ≈ 23.22ms`; but anything up to 42 should have the same end result (2^10).

Again, basically 48000Hz round-down ranges are (ask vs get): 6-10ms = 5ms, 11-21ms = 10ms, 22-42ms = 21ms, 43-85ms = 42ms, etc.

Thanks.

**Comment by pinkflames** [comment]
Indeed, defaults should be good for the average system. However the average system can do 10.7 ms latency. If not, we'd hear about it way more than someone posting about this once every month or two. 5.3 ms is also still quite commonly supported with PipeWire. And presumably Windows uses 5.0 ms latency, since there's some games which expect that. That would indicate that Windows capable hardware should inherently be expected to handle 5.0 ms client buffers.

And, no, it's not for performance reasons that `clock.power-of-two-quantum = true` is the default. If I understand correctly, some JACK software might crash if the quantum was not a power of two. That being said, I have been testing with that option set to false for a few months now and I have not found anything that was consistently broken. Then again, it would likely pick such a value only with a few Proton games, so I don't think most programs have even been run with such quantum even if they're technically allowed.

**Comment by philipl** [comment]
Did cb6b4af help with this @t-8ch ?

**Comment by pinkflames** [comment]
In terms of UX, yes, about 20 ms it's the highest audio latency most people would consider good enough and not outright iffy. Musicians would disagree but mpv is not a virtual MIDI keyboard, so I'll grant you that. ;)

**Comment by t-8ch** [comment]
> Did https://github.com/mpv-player/mpv/commit/cb6b4af1d7711e31b1a58d3771f779fbd5079351 help with this @t-8ch ?

I'm not entirely sure.

@sta-c0000 @pinkflames Could you take a look at `--pipewire-buffer=native`?

I'm also fine with changing the default to 24ms. Or if native works then that.

**Comment by pinkflames** [comment]
`--pipewire-buffer=native` should result in use of either the existing quantum (i.e. no switching in case of an already open device). If the device was not open at the time, it would be opened with the default value (quantum 1024 @ 48000 Hz).

I guess that might be a better pick conceptually, unless mpv has a reason to use the particular 20 ms default. It's worth noting that the PipeWire default is 1024 @ 48000 Hz which is not that much different from the current 960 @ 48000 Hz, so the native buffer size would by coincidence result in the same actual latency as @sta-c0000 is requesting. Unless another client had already caused the device to have a non-default config but that's not really an mpv issue, since the user should not permit quantum values that do not work (which is why the upstream recommendation has always been to adjust the min-quantum for systems where the default is too low).

**Comment by sta-c0000** [comment]
Thank you very much for your work @t-8ch!  I’ll build and try.

>[…](which is why the upstream recommendation has always been to adjust the min-quantum for systems where the default is too low)[…]

Personally I don’t agree that the global min-quantum should be set higher, even on mid to low powered systems, here’s how I see it:

If you are working on music or audio/video production, then I agree you want very low latency, but you also obviously won't be running other CPU hogging background processes while doing so.  In this case you don’t want a global min latency override.

However, if you are listening to music using mpv, you don’t need very low latency, and certainly don’t want glitching / crackling playback while you are doing other things on your PC, like compiling code, or running any other software that may be taxing (even temporarily) the CPU.  Heck, a PC can do a lot in the background even while watching a video using mpv, as long as mpv has some wiggle room (not too low latency) it won’t glitch.

It seems clear to me, but maybe I’m missing something about why you think mpv generally needs very low latency?

Cheers.

**Comment by pinkflames** [comment]
10 ms is not a low latency.. That would be 1 or 2 ms buffer (at which point there's a lot of caveats regarding additional latency causes such as the ALSA itself amongst other gotchas).

If a system has trouble running mpv at 10 ms latency, I'd expect it has no hope of running 2.5 ms latency for audio production purposes, because from PipeWire's perspective all clients are essentially the same. So any given quantum value either works with the particular system or it's probably various degrees of glitched and broken.

The only reason higher values are used for media applications rather than everything running at the same low latency is because Wim insists that doing so saves power by decoding ahead of time and batching a large buffer for playback. Personally I have never measured any significantly different power draw on a desktop system with any quantum above 256 but maybe it's true for a laptop or a different CPU architecture. On the other hand going down to double digit quantum will eat a lot of CPU and also electric power even when just producing silence.

**Comment by NekoCWD** [comment]
Same issue on Arch Linux. Fixed with `pipewire-buffer=47`

**Comment by kasper93** [comment]
> Same issue on Arch Linux. Fixed with `pipewire-buffer=47`

See https://github.com/mpv-player/mpv/issues/16367
